doc/changes/latest.inc
mne/channels/_standard_montage_utils.py
mne/channels/montage.py
mne/channels/tests/test_montage.py
mne/channels/tests/test_standard_montage.py
tutorials/forward/35_eeg_no_mri.py

Closes #10321
The difference is subtle, but it's there:
| Main | PR |
| ------ | ----- |
| ![Screenshot from 2022-02-11 10-48-02](https://user-images.githubusercontent.com/2365790/153625894-5d2aceab-fabc-47f0-b880-3d1d19989db5.png) | ![Screenshot from 2022-02-11 10-47-07](https://user-images.githubusercontent.com/2365790/153625833-ffaf461c-2b7f-43f1-bc44-5a1358422ed6.png) |
| ![Screenshot from 2022-02-11 10-48-09](https://user-images.githubusercontent.com/2365790/153625898-a2aaf4cb-0d52-4353-8e80-3c6b29351469.png) | ![Screenshot from 2022-02-11 10-47-21](https://user-images.githubusercontent.com/2365790/153625835-8ded0e88-bcd1-44d3-ba12-c31ceeec7080.png) |
| ![montage_projected](https://user-images.githubusercontent.com/2365790/153626343-ed4b79a4-4c29-48a8-95ae-5879741a11ed.png) | …

BUG: Fix bug with scaling and fids for standard montages

---

doc/changes/latest.inc
mne/conftest.py
mne/io/meas_info.py
mne/io/proj.py
mne/io/tests/test_raw.py
mne/minimum_norm/tests/test_inverse.py
mne/proj.py

A concrete proposal for #10286:
1. Make the check depend on a 10%+ reduction in projector norm, which is better than looking for a 10% channel count reduction, and 
2. Improve the warning to make it clear that this can be problematic, or not
An alternative idea of adding a `suppress_proj_warning` or so has also been suggested, but I'm -1 on that because I think there are probably dozens of places we'd need to add it (i.e., anywhere that we apply proj -- creating epochs, creating evoked, plotting functions, cov computation, inv computation, ...).
Another alternative is to try to infer a possible problem during `compute_proj_*`, but I think that's going to be even more difficult given that some legitimate interference patterns are concentrated on a few channels. Warning later is admittedly …

ENH: Better logic and message

---

mne/viz/_figure.py

The "qt"-backend stems from [mne-qt-browser](https://github.com/mne-tools/mne-qt-browser) and will only support plotting Epochs and ICA from `version>=0.2.0` on. This PR adds a warning, an instruction on how to update the version of mne-qt-browser and defaults to matplotlib if the version is not sufficient.

MNT: Warn about insufficient version for qt-backend for Epochs and ICA

---

doc/changes/latest.inc
mne/gui/_ieeg_locate_gui.py

This is a small bug where 2D lines were supposed to only be shown in the max projection because that's where they make sense (they go through multiple slices so it doesn't make sense for them to be shown in the 2D slice plots). This fixes the bug where they were shown in the 2D slice plots as well because the lines weren't removed ever. Also removing contacts didn't result in the line changing, rather being added which is also bad.

[BUG, MRG] Fix bug where 2D lines were not removed in ieeg GUI

---

mne/io/base.py
mne/utils/docs.py

I removed a `=` in the docstring for ``%(phase)s`` and added a couple of missing backticks.

MRG: Fix typos in notch_filter docstrings

---

tools/azure_dependencies.sh
tools/github_actions_dependencies.sh

Should hopefully fix our --pre builds while we wait for https://github.com/numpy/numpy/pull/21054, and fixes a bug where installing Numba caused our `--pre` numpy to be rolled back to `<1.22` on Linux

MAINT: Fix --pre

---

mne/viz/utils.py

The `cnorm` parameter was not used correctly (or rather, at all) in `AverageTFR.plot()`.

Fix cnorm not used in `AverageTFR.plot()`

---

doc/changes/latest.inc
mne/viz/_brain/_brain.py
mne/viz/_brain/tests/test_brain.py

When adding foci to a plotted brain, the `map_surface` parameter allows the user to project them onto a mesh. This was not implemented in the latest master yet, so I copied over [the relevant code from PySurfer](https://github.com/nipy/PySurfer/blob/master/surfer/viz.py#L1688-L1697). Seems to work nicely. Needs a test maybe?

[MRG] Implement map_surface parameter for Brain.add_foci

---

mne/commands/tests/test_commands.py
mne/conftest.py
mne/tests/test_coreg.py
mne/tests/test_source_space.py
mne/utils/_logging.py
mne/utils/_testing.py
mne/utils/tests/test_progressbar.py
mne/utils/tests/test_testing.py
mne/viz/backends/_pyvista.py

This PR follows https://github.com/mne-tools/mne-python/pull/10319#discussion_r804679165 and introduces a `pytest.fixture` called `options_3d` to disable advanced 3d rendering options.
I tried setting `scope='session'` but I got the following error:
```
_______________________________________________________________ ERROR at setup of test_3d_functions[pyvistaqt] _______________________________________________________________
ScopeMismatch: You tried to access the 'function' scoped fixture 'monkeypatch' with a 'session' scoped request object, involved factories
mne/conftest.py:655:  def options_3d(monkeypatch)
../anaconda3/envs/mne-py38/lib/python3.8/site-packages/_pytest/monkeypatch.py:29:  def monkeypatch() -> Generator[ForwardRef('MonkeyPatch'), NoneType, NoneType]
```
cc @larsoner

WIP,MNT: disable 3d options during testing

---

doc/changes/latest.inc
mne/report/report.py
mne/report/tests/test_report.py

Closes #10169
If a user passes an `ndarray` (pixels), a PyVista figure, or mpl Figure to `add_figure`, we shouldn't:
1. Resize it (wasn't happening for mpl, but was for ndarray and PyVista)
2. Close it
We should trust that the user has resized to the size they want and not close the figure on them (they should be in charge of doing so)

BUG: Fix bug with closing and resizing

---

mne/conftest.py
mne/utils/config.py
mne/viz/_3d.py
mne/viz/backends/_pyvista.py

This PR adds an option to control smooth shading to be complete with the other 'advanced rendering' options.
It also effectively removes `MNE_3D_BACKEND_TESTING` from `_PyVistaRenderer`.

MNT: Smooth shading 3d option

---

examples/time_frequency/time_frequency_erds.py

The latest Matplotlib version scales the colorbar logarithmically for a `TwoSlopeNorm`. This is used in the ERDS maps example and doesn't look nice at all. This PR sets the colorbar scale to linear (how it used to be).

Fix colorbar scaling in ERDS example

---

doc/changes/latest.inc
doc/changes/names.inc
mne/io/edf/edf.py
mne/io/utils.py

In some EDF files created in Japan, Shift_JIS mu (`\x83\xCA`) is used in the header for the unit.
This change allows to read the unit correctly and assign the correct scale.

ENH: add Shift_JIS mu in _read_edf_header

---

tutorials/clinical/60_sleep.py

Fixes #10360.
Fix arguments (stim_channel, misc) of [read_raw_edf](https://mne.tools/stable/generated/mne.io.read_raw_edf.html?highlight=read_raw_edf#mne.io.read_raw_edf) in the [Sleep stage classification](https://mne.tools/stable/auto_tutorials/clinical/60_sleep.html#tut-sleep-stage-classif) tutorial.

BUG: fix stim_channel/misc usage in Sleep stage classification tutorial

---

doc/changes/latest.inc
mne/annotations.py
mne/tests/test_annotations.py

In [Annotations.crop](https://github.com/mne-tools/mne-python/blob/ad095ba6e0e5b97ddbbb0def3846fa8551add30d/mne/annotations.py#L491) function,
onset values must be passed as `seconds` instead of `dates` (first argument).
Another change allows passing float and None at the same time.
Currently, if tmin or tmax is None, the value is obtained as datetime and it can not be compared with float.
By calculating `absolute` values before checking `tmin > tmax`, float can be used with None.
In most cases, this bug does not affect 
because original annotations data has tmin=0, and too large tmax just allow all period.

BUG: Fix datetime conversion for timin/tmax=None cases in Annotations.crop

---

.circleci/config.yml
doc/conf.py
mne/viz/_scraper.py
tools/circleci_dependencies.sh
tutorials/epochs/20_visualize_epochs.py
tutorials/intro/10_overview.py
tutorials/intro/15_inplace.py

@marsipu I can see the gc failure with the following in the `doc` folder:
```
$ make clean && PATTERN=15_inplace MNE_SKIP_INSTANCE_ASSERTIONS="brain,_Renderer,Plotter,BackgroundPlotter,vtkPolyData" make html_dev-pattern-memory
loading intersphinx inventory from https://www.fatiando.org/pooch/latest/objects.inv...
intersphinx inventory has moved: https://dipy.org/documentation/latest/objects.inv/ -> https://dipy.org/documentation/1.4.1./objects.inv/
generating gallery...
Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
Clean    8.8 s : 442.5 MBto_tutorials/intro... [ 28%] 15_inplace.py                                                                                                                 
File …
```

ENH: Use Qt backend for doc build

---

tutorials/preprocessing/20_rejecting_bad_data.py
tutorials/raw/30_annotate_raw.py

This adapts the following tutorials to the qt-backend:
https://mne.tools/dev/auto_tutorials/raw/30_annotate_raw.html?highlight=annotate_raw#annotating-raw-objects-interactively
https://mne.tools/dev/auto_tutorials/preprocessing/20_rejecting_bad_data.html?highlight=rejecting_bad#annotating-bad-spans-of-data

DOC: Adapt annotation-tutorials to the qt-backend

---

doc/_static/style.css
tutorials/epochs/40_autogenerate_metadata.py
tutorials/intro/70_report.py
tutorials/inverse/10_stc_class.py
tutorials/inverse/30_mne_dspm_loreta.py

Minor tweaks from browsing our docs
1. Now that sphinx-gallery uses better HTML for the thumbnails, our own `style.css` tweaks are actually detrimental -- they force a minimum height when it's not necessary.
2. Having `/`-separated MNE/dSPM/... makes an example title overflow
3. Having `:class:` markup on the titles makes them look bad on the main page
All three problems are visible here:
This PR fixes them:

DOC: Improve CSS

---

doc/changes/latest.inc
examples/visualization/brain.py
mne/dipole.py
mne/forward/_make_forward.py
mne/utils/docs.py
mne/viz/_3d.py
mne/viz/_brain/_brain.py
mne/viz/_brain/tests/test_brain.py
tutorials/inverse/35_dipole_orientations.py

This adds the plotting of dipoles similar to `mne.viz.plot_alignment` to `mne.viz.Brain`. I just extended it to support plotting the forward model as well:
I touched `tutorials/inverse/35_dipole_orientations.py` so if this messed things up (especially scale) for `plot_alignment` we can fix that.

[ENH, MRG] Add dipole plotting to mne.viz.Brain

---

tools/azure_dependencies.sh
tools/github_actions_dependencies.sh

Let's see if we can lose the NumPy pins, and use nightly-built statsmodels on Windows.

FIX: Bump deps

---

doc/Makefile
doc/conf.py
mne/gui/_coreg.py
mne/gui/tests/test_coreg_gui.py
mne/gui/tests/test_gui_api.py
mne/utils/misc.py
mne/viz/_brain/_brain.py
mne/viz/backends/_abstract.py
mne/viz/backends/_notebook.py
mne/viz/backends/_qt.py
tutorials/clinical/10_ieeg_localize.py
tutorials/preprocessing/70_fnirs_processing.py

Some functions need to be called before the closing event (i.e: dialog, ...etc) and some after (qt object cleanup). This PR adds a bit of flexibility to the GUI API to do just that. 
Locally, it solves the issue with doc building.
<details>
```
File "/home/guillaume/source/anaconda3/envs/mne-py38/lib/python3.8/site-packages/sphinx/events.py", line 101, in emit
results.append(listener.handler(self.app, *args))
File "/home/guillaume/source/sphinx-gallery/sphinx_gallery/gen_gallery.py", line 464, in generate_gallery_rst
generate_dir_rst(src_dir, target_dir, gallery_conf,
File "/home/guillaume/source/sphinx-gallery/sphinx_gallery/gen_rst.py", line 399, in generate_dir_rst
intro, title, cost = generate_file_rst(
File …
```

FIX: close_connect

---

doc/changes/latest.inc
mne/gui/_ieeg_locate_gui.py

I don't have a page up or page down button on my macbook keyboard so I thought we should change the anterior posterior slice scrolling to use </>. I kept the page up and page down scrolling for backward compatibility.

[ENH, MRG] Add gui slice scrolling buttons

---

tutorials/io/30_reading_fnirs_data.py

Adds a list of fNIRS manufacturers whose data we can import using the SNIRF format.
The primary aim of the PR was to indicate that MNE can read @cortivision files correctly. Previously, our docs did not state that MNE can read cortivision files. Now, hopefully, if someone googles `fNIRS cortivision processing` then MNE will be in the results.

Add cortivision to list of fNIRS data that MNE can read

---

doc/changes/latest.inc
mne/gui/_ieeg_locate_gui.py
mne/gui/tests/test_ieeg_locate_gui.py
mne/tests/test_transforms.py
mne/transforms.py
tutorials/clinical/10_ieeg_localize.py

Closes #9755
When working on that, I found a bunch of small stuff that I thought should be fixed:
1. Add `cval` arg to `apply_volume_registration` so that you can choose what value to use/assume outside the bounds of the image domain during interpolation. (Naming chosen to match `scipy.ndimage` convention, but we could change it.) For the CT image the background value is -1024, and passing `cval='1%'` uses the first percentile of the image data (which is -1024).
2. Refactor iEEG GUI to be much more DRY by:
1. Routing all `self._ras` changes through a `self._update_ras(ras)` that does clipping to valid (in-image) values only
2. Using a `self._vox` property to avoid repeated `apply_trans(...).round().astype(int)`
3. Making `self._current_slice` a property as well
This should also help …

ENH: Bounds around brain

---

mne/gui/tests/test_gui_api.py
mne/viz/backends/_abstract.py
mne/viz/backends/_notebook.py
mne/viz/backends/_qt.py

This PR refactors Qt dialog button management and switches from using `button.text()` (which is platform/desktop dependant) to using the [Qt standard button enum value](https://doc.qt.io/qt-5/qmessagebox.html#StandardButton-enum) (called `button_id` in the PR).
It's an item of https://github.com/mne-tools/mne-python/pull/10378

ENH: dialog button id

---

doc/changes/latest.inc
mne/viz/_figure.py

This fixes signal containing `np.nan` being incorrectly displayed in the raw browser (as described in https://github.com/cbrnr/mnelab/pull/313).

Use np.nanmean for remove_dc=True

---

.circleci/config.yml
doc/changes/latest.inc
mne/viz/backends/_pyvista.py

Closes #10391
We actually *shouldn't* use `_get_gpu_info` from #10385 because it takes 740 ms on my powerful workstation, which is too much. So instead we'll just use the already-opened renderer to call `plotter.ren_win.ReportCapabilities()`, which takes a negligible amount of time (< 1 ms).

ENH: Autodetect mesa and disable antialiasing

---

doc/changes/latest.inc
tutorials/stats-sensor-space/50_cluster_between_time_freq.py

In the example I changed, the T-statistic for the significant clusters was plotted with no `vmin` or `vmax` arguments to `imshow` with a diverging (`RdBu_r`) colormap. The T-statistic is strictly positive so I think this is misleading as it colored significant but smaller T values blue and significant and larger T values red. The intent was, as far as I can tell, to plot decreases power in blue and increases in red, so I made a change to multiply the T statistic by the sign of the difference in means of the two conditions.
cc @agramfort since you're listed as the author and hopefully I didn't mess things up :)

[DOC, MRG] Fix misleading colorbar in cluster permutation example

---

doc/changes/latest.inc
mne/annotations.py
mne/tests/test_annotations.py

[mne.Annotations.crop](https://mne.tools/stable/generated/mne.Annotations.html#mne.Annotations.crop) can accept both `float` and `datetime` types for `tmin` and `tmax`.
If the Annotations object does not have the `orig_time` parameter, float values correspond to `onset` values in the Annotations object.
If `orig_time` exists, users need to obtain unix time of orig_time and add it to onset values.
`use_orig_time=False` allows to use `onset` values directly even if `orig_time` exists.

ENH: Add use_orig_time option to mne.Annotations.crop

---

doc/changes/latest.inc
examples/time_frequency/time_frequency_erds.py
mne/stats/cluster_level.py
mne/stats/parametric.py
mne/stats/tests/test_cluster_level.py
mne/stats/tests/test_parametric.py
tutorials/stats-sensor-space/50_cluster_between_time_freq.py
tutorials/stats-sensor-space/75_cluster_ftest_spatiotemporal.py
tutorials/stats-source-space/20_cluster_1samp_spatiotemporal.py
tutorials/stats-source-space/30_cluster_ftest_spatiotemporal.py
tutorials/stats-source-space/60_cluster_rmANOVA_spatiotemporal.py
tutorials/stats-source-space/70_cluster_rmANOVA_time_freq.py

Cleans up leftovers from https://github.com/mne-tools/mne-python/pull/10393.
So the first thing was that the default test was an F-test for the non-1-sample tests and so it should be called `F_obs` which gets output. That was actually done for the spatiotemporal but not the regular cluster test already so I made that consistent.
The next thing is that it really wasn't hard at all to add support for an arbitrary array shape of features (i.e. (times,) or (times, frequencies) or even (times, frequencies, whatever else)). Not that people should be using more than time-frequency dimensions, but its more general written this way. I do think spatiotemporal time-frequency clustering should be supported directly (rather than collapsing the time-frequency array before passing it as an argument) and …

[BUG, ENH, MRG] Tename clustering that uses F-tests to F_obs and refactor to allow time-frequency spatiotemporal clusters

---

mne/viz/backends/_qt.py
mne/viz/backends/_utils.py

Along with https://github.com/mne-tools/mne-qt-browser/pull/66, before:
After:

MAINT: Refactor for mne-qt-browser

---

doc/changes/latest.inc
mne/epochs.py
mne/io/base.py
mne/preprocessing/ica.py
mne/utils/docs.py
mne/viz/_brain/_brain.py
mne/viz/_figure.py
mne/viz/_mpl_figure.py
mne/viz/epochs.py
mne/viz/ica.py
mne/viz/raw.py

1. Add `theme='auto'` to `raw.plot` and related methods that should work with the PyQtGraph backend once https://github.com/mne-tools/mne-qt-browser/pull/66 is merged
2. Fix handling of partially supported kwargs, like `splash`. We don't actually need to check if it's in the `kwargs`, since it just gets put in `self.mne.splash` for example. This can then be used (or not) by each backend.

ENH: Add theme to raw.plot, etc.

---

doc/changes/latest.inc
mne/datasets/config.py
mne/io/snirf/_snirf.py
mne/io/snirf/tests/test_snirf.py
mne/tests/test_surface.py

Continuous-wave fNIRS data can be acquired in the "raw" type, then converted to optical density, then converted to haemoglobin. As such, each of these data types is supported in MNE already. Some devices (namely [Artinis](https://www.artinis.com)) save the data directly as optical density, removing the burden of the first processing step from the end-user.
The [SNIRF file format](https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#appendix) provides a mechanism for storing data in optical density form. MNE already supports reading the data as "raw" or "haemoglobin", but not in optical density form. This PR adds support for reading the data in this middle form, optical density, or MNE type `fnirs_od`. 
Adds the ability to read optical density fNIRS data stored in the SNIRF …

Add support for reading SNIRF files with optical density data

---

mne/gui/_ieeg_locate_gui.py
mne/viz/_brain/_brain.py

@GuillaumeFavelier feel free to review/merge
We shouldn't (implicitly) call `render=True` in `remove_actor`. We should instead call `self._renderer._update()` ourselves when we want to update.

BUG: Dont force render on remove

---

.github/workflows/linux_conda.yml

The workflow could not even start because the name is invalid. This PR fixes it and sorry for the delay.
```
The workflow is not valid. .github/workflows/linux_conda.yml (Line: 14, Col: 3): The identifier 'py3.9' is invalid. 
```

FIX: linux_conda job

---

azure-pipelines.yml
mne/conftest.py
mne/utils/_testing.py
tools/azure_dependencies.sh
tools/github_actions_dependencies.sh

Dipy has 3.10 wheels on scipy-nightly, let's use them. And I think we can bump windows --pre to 3.10 if we use VTK's wheel. Let's see...

MAINT: Update deps

---

mne/channels/channels.py
mne/channels/tests/test_channels.py
mne/epochs.py
mne/evoked.py
mne/io/base.py
mne/io/meas_info.py
mne/io/tests/test_meas_info.py
mne/preprocessing/ica.py
mne/time_frequency/tfr.py

Fixes issue for https://github.com/mne-tools/mne-bids/pull/983.
This seems a lot more natural to me. It would be nice if an `Info` object could `get_montage` and allow why not `__contains__` and `get_channel_types` while we're at it, those both operate on the `info`.

[ENH, MRG] Refactor `ContainsMixin` and `MontageMixin`

---

mne/viz/circle.py
tutorials/clinical/20_seeg.py

It would be nice if you could control the node heights, I have smaller subplots and they are too small for my figure. It looks like the code is duplicated in `mne-connectivity`... any thought on how that would be refactored ideally? All in `mne-python` might be easiest... I can work a bit on that since I'm pushing to mess up the duplication.

[ENH, MRG] Add `node_height` keyword argument

---

mne/viz/circle.py

Okay, one last fix with the changes. Before, `fig.tight_layout` didn't work and so the title overlapped the text. When I let `ax` be passed directly, it allowed `fig.tight_layout` but the colorbar didn't work with it. This allows the previous functionality of specifying the position of the colorbar, but makes the default not have overlapping text with `fig.tight_layout`.

[MAINT] Fix colorbar

---

mne/coreg.py
mne/gui/_coreg.py
mne/gui/tests/test_coreg_gui.py

Fixes two bugs:
1. The `callback` in ICP should be called before the `break` (otherwise the last/final iteration is not reflected)
2. The GUI should not limit the scale to `<=100` (percent) but rather something much higher like 10000. This makes the updates work properly:
https://user-images.githubusercontent.com/2365790/158857774-591a9d51-9e0f-40fe-bfdf-d1b2d61ec30c.mp4

BUG: Fix ICP update bug

---

mne/beamformer/tests/test_lcmv.py

This PR changes the bounds of `test_lcmv` to fix:
```
================================== FAILURES ===================================
_ test_localization_bias_free[testing_data-testing_data-0.0-vector-unit-noise-gain-True-None-44-46-0.97-0.98] _
mne\beamformer\tests\test_lcmv.py:711: in test_localization_bias_free
assert lower <= perc <= upper
E   assert 47.289972899729 <= 46
_ test_localization_bias_free[testing_data-testing_data-0.0-vector-nai-True-None-44-46-0.97-0.98] _
mne\beamformer\tests\test_lcmv.py:711: in test_localization_bias_free
assert lower <= perc <= upper
E   assert 47.289972899729 <= 46
```
Related to https://github.com/mne-tools/mne-python/pull/10438

FIX: test_lcmv

---

mne/gui/_coreg.py
mne/viz/backends/_notebook.py

This PR fixes the layout of checkboxes on the `notebook` 3d backend and adjusts the size of the dock. It also changes the 'Reset' button of the coreg app to 'Reset Parameters' and moves it to its own line.
backend\branch | main | PR
--|--|--
notebook | ![image](https://user-images.githubusercontent.com/18143289/159722541-b0691256-9e17-4b8b-861b-5a602c73ff3b.png) | ![image](https://user-images.githubusercontent.com/18143289/159721725-e928c95d-6f95-4ca3-a6ae-9647aceab754.png)
pyvistaqt | ![image](https://user-images.githubusercontent.com/18143289/159722177-2d3eda5a-85b0-44dc-9fdd-49b40b40ba94.png) | ![image](https://user-images.githubusercontent.com/18143289/159722003-5aa57986-d9cd-4848-8b11-ea933e21adcf.png)
It's an item of #8833

FIX: notebook checkbox layout

---

mne/gui/_coreg.py
mne/viz/backends/_abstract.py
mne/viz/backends/_pyvista.py

This PR adds a legend to the coreg app. It helps make the association fiducial <> color:
It's an item of #8833

ENH: coreg legend

---

tutorials/preprocessing/25_background_filtering.py

This very PR fixes:
```
[broken] http://www.fieldtriptoolbox.org/reference/ft_preproc_bandpassfilter: 404 Client Error: Not Found for url: https://github.com/fieldtrip/fieldtrip/blob/release/ft_preproc_bandpassfilter.m
```
The line with the updated URL is  > 80 characters (88), is that okay?

FIX: broken link

---

mne/viz/montage.py

When playing around with `raw.plot_sensors` and `montage.plot` I figured that the docstrings are not accurate.
`raw.plot_sensors()` takes either a bool or a list of channel names, this is also possible in `montage.plot()`
I thought this should also be reflected in the docstring

[minor] Update docs of montage.plot(show_names)

---

mne/time_frequency/multitaper.py

Fixes #10469.
This is a really tiny, nitpicky fix. 
If anyone wants more more text here please comment and I will expand the description.

Use a `float` default value for `fmin`-param in `mne.time_frequency.psd_array_multitaper`

---

doc/install/advanced.rst

The command `conda create --name=mne --file=server_environment.yml` does not work, as pointed out here: https://github.com/conda/conda/issues/6827#issuecomment-365614464
I am not a conda user, so I might be mistaken, but I think I've changed it correctly.

MRG: Fix command for headless installation

---

mne/gui/_coreg.py
mne/gui/tests/test_gui_api.py
mne/icons/dark/actions/folder.svg
mne/icons/light/actions/folder.svg
mne/viz/_brain/_brain.py
mne/viz/backends/_abstract.py
mne/viz/backends/_notebook.py
mne/viz/backends/_qt.py

This PR refactors icon loading in the GUI API and replaces the "Load" buttons by a :file_folder:  icon in the coreg app.
light theme | dark theme
--|--
It makes for a subtle change:
backend\branch | main | PR
--|--|--
notebook | ![image](https://user-images.githubusercontent.com/18143289/160094745-8b6d96f5-ed87-4cc0-98e9-a83db2f71caf.png) | ![image](https://user-images.githubusercontent.com/18143289/160093472-e594968f-121d-42e1-bd03-d8c1aafeaed3.png)
qt | ![image](https://user-images.githubusercontent.com/18143289/160094601-cf4e22c8-a3a5-473d-94c5-1e9e788efae9.png) | ![image](https://user-images.githubusercontent.com/18143289/160093603-64498072-2b90-49ec-a009-8660a81cbbf7.png)
This PR cannot be merged before https://github.com/mne-tools/mne-python/pull/10456
It's an item of #8833

ENH: load icon

---

doc/changes/latest.inc
doc/conf.py
mne/report/report.py
mne/report/tests/test_report.py
mne/utils/_bunch.py
mne/utils/docs.py
mne/viz/_scraper.py
mne/viz/backends/_pyvista.py
mne/viz/backends/renderer.py
mne/viz/epochs.py
mne/viz/ica.py
mne/viz/raw.py
mne/viz/utils.py
tutorials/intro/70_report.py

Closes https://github.com/mne-tools/mne-qt-browser/issues/77
Locally:
```
import mne
raw = mne.io.read_raw_fif(mne.datasets.sample.data_path() / 'MEG' / 'sample' / 'sample_audvis_raw.fif')
report = mne.Report()
report.add_figure(raw.plot(), title='Raw plot')
report.save('test.html', overwrite=True)
```
Now produces:
Note I cut out the statusbar and toolbar to at least move toward what @cbrnr was looking for.
For the overview bar, I think we should do that separately, if at all. It probably adds enough information in some examples (e.g., annot/event timing) that we want to keep it. If someone's motivated, it's easy enough to implement custom code-block parsing that would allow us to move to a "scrape only if a `# sphinx_gallery_include_overview_bar` comment present" functionality where the …

BUG: Fix add_figure for MNEQtBrowser

---

mne/viz/raw.py

Fix #10486 on my windows computer.
It probably also fixes it on my macOS (can't remember if I did set the config variable or not..), but I can't test until Monday.

MRG: Fix passing of argument theme for raw.plot()

---

mne/viz/misc.py
tutorials/preprocessing/25_background_filtering.py

There is an error in the transfer function equation (a 1 term is missing in the denominator). I suggest to remove the second version with sum signs altogether, because the first version contains all information and is just as easy to read.

Fix error in filtering documentation

---

mne/viz/_figure.py

I don't think that the messages currently logged at the info level related to opening and closing a raw/epochs browser are really informative for users. If at all, they should be demoted to debug level messages, which is what I've done here.

Set open/close browser log messages to debug

---

tutorials/evoked/30_eeg_erp.py

I tried to streamline the [ERP tutorial](https://mne.tools/stable/auto_tutorials/evoked/30_eeg_erp.html) a bit, after which it hopefully reads a bit better.
Two questions:
- Screenshots of `Raw.plot()` or `Epochs.plot()` should use the `matplotlib` backend I think because it looks better in non-interactive documents.
- Do we not append () to methods and functions? If so, should I prepend `:meth:` (or :func:) in this tutorial?
[Before](https://mne.tools/stable/auto_tutorials/evoked/30_eeg_erp.html) vs. [after](https://output.circle-artifacts.com/output/job/b2394614-3553-438a-b7e2-c8f1ee0365fa/artifacts/0/dev/auto_tutorials/evoked/30_eeg_erp.html)

Improve ERP tutorial

---

mne/viz/backends/_utils.py

This makes the splash screen about half the size on macOS, but I think it still looks good. And this way, it's displayed in HiDPI mode, which I think looks better.
| main | PR |
| -- | -- |
| <img width="558" alt="Screen Shot 2022-04-07 at 6 17 42 PM" src="https://user-images.githubusercontent.com/2365790/162328676-a5a4eaa4-795c-4744-81d6-68c9f1d686f1.png"> | <img width="302" alt="Screen Shot 2022-04-07 at 6 16 49 PM" src="https://user-images.githubusercontent.com/2365790/162328692-1298aba0-d0f4-42e9-aaeb-df3533e7ab19.png"> |

ENH: Use HiDPI splash screen on HiDPI screens

---

mne/utils/misc.py
mne/viz/_brain/_brain.py
mne/viz/backends/_qt.py

CicleCI is failing on `main`, let's see what the actual error is.

CI: Test circle

---

doc/changes/latest.inc
mne/channels/channels.py
mne/channels/tests/test_channels.py

Add metadata to combine_channels

---

doc/install/installers_platform_selector.html

Once https://github.com/mne-tools/mne-installers/releases/tag/v1.0.1 finished building I'll test all download links and the macOS installer, then merge and backport

MAINT: Bump installer links

---

mne/commands/tests/test_commands.py
mne/conftest.py
mne/gui/tests/test_gui_api.py
mne/utils/check.py
mne/utils/config.py
mne/viz/backends/_utils.py
mne/viz/backends/tests/_utils.py
mne/viz/tests/test_ica.py
requirements.txt

For qtpy support in mne-qt-browser, we need to update our testing infrastructure in MNE-Python, since our checks currently look to see if PyQt5 is installed.
I also added `pyqtgraph` to `mne sys_info`.

MRG: Updates for qtpy in mne-qt-browser

---

.circleci/config.yml
azure-pipelines.yml
doc/changes/latest.inc
doc/conf.py
doc/install/advanced.rst
doc/install/check_installation.rst
mne/conftest.py
mne/utils/config.py
mne/utils/misc.py
mne/viz/_3d.py
mne/viz/_brain/_brain.py
mne/viz/_brain/callback.py
mne/viz/_brain/tests/test_brain.py
mne/viz/_scraper.py
mne/viz/backends/_pyvista.py
mne/viz/backends/_qt.py
mne/viz/backends/tests/test_utils.py
mne/viz/tests/test_scraper.py
mne/viz/tests/test_utils.py
mne/viz/utils.py
requirements.txt
tools/azure_dependencies.sh
tools/circleci_dependencies.sh
tools/github_actions_dependencies.sh
tools/setup_xvfb.sh
tutorials/inverse/50_beamformer_lcmv.py

~~I think we should cut a release. Given that this will be the first to support Qt6, I bumped to 0.3.0 (last release was 0.2.6).~~
~~@agramfort or @hoechenberger feel free to merge and I'll cut a release~~
Uses PySide6 as our preferred framework in testing. We can't change `environment.yml` until conda-forge manages to release PySide6, which will require Qt6 first. So it might be a while!
Todo

MAINT: Prefer PySide6 in testing

---

doc/changes/latest.inc
mne/datasets/config.py
mne/io/eeglab/eeglab.py
mne/io/eeglab/tests/test_eeglab.py

closes #10474
@cmadjar this should fix your problem.

FIX : read fids in eeglab

---

examples/preprocessing/muscle_detection.py

Line noise was set at the wrong frequencies, see here https://neuroimage.usc.edu/brainstorm/Tutorials/Auditory#Power_line_contamination.

Fix line noise at wrong frequencies

---

mne/commands/tests/test_commands.py
mne/io/_digitization.py

Should fix `compat` build failures like https://github.com/mne-tools/mne-python/runs/6014763984?check_suite_focus=true
SphinxWindows should be fixed by https://github.com/numpy/numpydoc/pull/382 (so we have to wait)

FIX: Fix for old build

---

doc/changes/latest.inc
mne/io/brainvision/brainvision.py

Example: Fixes #10516 .
If in the header high cutoff is 0, then the lowpass filter is considered as disabled.

Avoid lowpass=0 in brainvision data

---

doc/changes/latest.inc
mne/bem.py

Several (all?) Windows users attending a workshop @agramfort and I hosted yesterday were running into issues when working with BEM surfaces we had shared with them as part of a FreeSurfer subjects directory.
The reason was that transferring the symlinks turned out to be problematic, and thus, users ended up with invalid files. They had to manually copy over the BEM surfaces from the `bem/flash` or `bem/watershed` (?) directories to `bem/` and rename them.
Since our collaborators are working in highly heterogenous settings (macOS, Linux, Windows), this is indeed a huge problem for data sharing, and it's not obvious at all to a common user WHY things are not working as expected.
I therefore here propose an API change without deprecation cycle, changing the default value of the …

WIP: Copy BEM surfaces by default (don't symlink)

---

azure-pipelines.yml
requirements.txt

6.3.0 came out April 16th, so I'm guessing that's what's causing our Qt failures. Let's find out!

CI: Avoid bad PySide6

---

doc/changes/latest.inc
mne/channels/channels.py

This allows to e.g. to suppress messages about removed projectors.

MRG: Add "verbose" parameter to pick_channels() method

---

doc/changes/latest.inc
mne/channels/tests/test_montage.py
mne/io/_digitization.py

Before, both lines below would not raise.
```
montage = make_dig_montage(ch_pos={'A1': ['0', '0', '0']})
montage = make_dig_montage(ch_pos={'A1': 5})
```
The first one, in particular, is problematic, in case you read [x, y, z] values from a file and forget to convert from str to float (definitely never happened to me 🙈).
After, both raise an error at creation and I also added a conversion to a float array at an earlier stage for the [x, y, z].

MRG: Add error checking to prevent the creation of montage with invalid [x, y, z]

---

mne/decoding/base.py

We're actually using 5 splits and have been for quite a while now, but this bit of the docs hasn't been updated.

MRG: Correct documented default number of CV splits in cross_val_multiscore()

---

examples/decoding/decoding_time_generalization_conditions.py
examples/decoding/linear_model_patterns.py
tutorials/machine-learning/50_decoding.py

Use liblinear solver instead of lbgfs in all decoding examples

---

doc/changes/latest.inc
mne/annotations.py
mne/channels/channels.py
mne/io/base.py
mne/io/ctf/info.py
mne/io/meas_info.py
mne/tests/test_annotations.py

Closes #10490
So far just replicates the problem. True TDD time!

BUG: Fix annot meas_date / crop

---

mne/conftest.py
mne/viz/backends/_pyvista.py
mne/viz/backends/_qt.py
mne/viz/backends/_utils.py

On gnome-shell in Linux, running `pytest mne/viz` is really annoying because of focus stealing. This makes our code respect the current code path for deciding whether or not to activate a window when it's shown (using `rcParams`). This in turn can be easily controlled in `conftest` to always be False.

MAINT: Respect activation

---

doc/changes/latest.inc
examples/preprocessing/muscle_ica.py
mne/preprocessing/ica.py
mne/viz/ica.py
mne/viz/tests/test_ica.py
mne/viz/topomap.py

The topomap for `ICA.plot_properties` defaults to the first on the list of channel types, usually `mag`. I think, especially when this is popped out in the `ICA.plot_sources` figure, it would be super helpful to be able to toggle the type of channel shown in the topomap. I threw in log scaling as well although now that I'm writing this, maybe just the parameter is sufficient, although you can't easily pass the parameter in `ICA.plot_sources` so maybe I'll leave it in and see what other people think and remove it if it's not popular. The thing that I haven't figured out is how to inform the user of this functionality. I think a help button would probably be fine but wanted to see what others think, maybe just add it to the text of the tutorial would work as well.

[ENH, MRG] Add keypresses to ICA to toggle topomap channel type and psd scale

---

doc/changes/latest.inc
mne/gui/tests/test_gui_api.py
mne/viz/_brain/_linkviewer.py
mne/viz/_brain/tests/test_notebook.py
mne/viz/backends/_abstract.py
mne/viz/backends/_notebook.py
mne/viz/backends/_qt.py

This PR fixes Qt toolbar callbacks (*e.g.* in `Brain`):
```
Using pyvistaqt 3d backend.
File "/home/guillaume/source/mne-python/mne/viz/backends/_qt.py", line 428, in callback
weakself.app_window,
AttributeError: '_Renderer' object has no attribute 'app_window'
```
It also adds a test to avoid regression and does simple refactoring of 'actions' (Qt name for callables which can have an icon and shortcut).

FIX: Qt toolbar

---

environment.yml

This should fail until eeglabio finishes building on conda-forge and lands on the CDNs. I'll restart the CIs in a few hours then hopefully merge when green!
This shouldn't have a big impact on CIs since these are already in `requirements_testing_extra.txt`, but any users who use `environment.yml` should hopefully benefit.

MAINT: Add export functions to env

---

doc/changes/latest.inc
mne/forward/_field_interpolation.py
mne/io/open.py
mne/viz/_3d.py
mne/viz/tests/test_3d.py

No need to add a test here I think because it's just a pass-through argument, and tests of `get_head_surface` should be sufficient to test arg validity.
I also improved a few error messages in `mne/io/open.py` that helped me know which file was actually problematic.

ENH: Add head_source option

---

mne/gui/_coreg.py
mne/gui/tests/test_gui_api.py
mne/viz/backends/_abstract.py
mne/viz/backends/_notebook.py
mne/viz/backends/_qt.py

This small PR allows setting the Qt dialog box icon (instead of using only :warning: ). The default remains `'Warning'` though.
It's part of https://github.com/mne-tools/mne-python/pull/10565

MNT: dialog box icon

---

mne/viz/backends/_qt.py

This small PR allows setting dock areas other than 'left' and 'right' (namely 'top' and 'bottom').
Here is a small code snippet to try:
<details>
```py
from mne.viz.backends.renderer import _get_renderer
renderer = _get_renderer()
for area in ['top', 'bottom', 'left', 'right']:
renderer._dock_initialize(area=area)  # <---- new parameter here
renderer._dock_add_button(area, lambda x: None)
renderer.show()
```
</details>
It's a part of https://github.com/mne-tools/mne-python/pull/10565

MNT: dock area

---

doc/changes/latest.inc
doc/preprocessing.rst
doc/references.bib
doc/visualization.rst
examples/preprocessing/eeg_bridging.py
examples/preprocessing/muscle_ica.py
mne/preprocessing/__init__.py
mne/preprocessing/_csd.py
mne/preprocessing/tests/test_csd.py
mne/utils/docs.py
mne/viz/__init__.py
mne/viz/tests/test_topomap.py
mne/viz/topomap.py

Fixes #10561.
This tutorial is pretty compelling even though there are a lot of parameters https://psychophysiology.cpmc.columbia.edu/software/eBridge/tutorial.html so I just did an exact replication despite there being a few different strategies in the literature that depend less on the histogram of electrical distance values and more on the projection of the nearest neighbors onto each electrode (intrinsic Hjorth) e.g. below.
However, I'm getting a weird effect where the bridged electrodes are predominantly lateral to each other in the EEGBCI dataset. If anyone had a second to look through the code, it's not that complex but I'm guessing I did something wrong.
I'll keep looking as well and hopefully fix it soon. I think this is pretty valuable for EEG users.

[ENH, MRG] Compute Electrode Bridging in EEG

---

doc/install/advanced.rst
doc/install/manual_install.rst

Also re-ordered the instructions, as I've seen several users end up with only 2D  support & minimal installs as these instructions were at the very top. I moved  those minimal installs down, as this is a special case that only select users will want.
Also we're now suggesting users use <strike>mamba</strike> libmamba for the "full" install  (we keep recommending conda for the minimal installs).
Fixes #10577
cc @marsipu @larsoner @agramfort

MRG: Update installation instructions to ensure users end up with latest version of the conda-forge package

---

examples/preprocessing/eeg_bridging.py
mne/viz/topomap.py

After thinking about it, https://github.com/mne-tools/mne-python/pull/10571 used the default colormaps which didn't represent the data well based on our intuitive associations with colors. This sets high distances to green and low to yellow for the bridging and has a typical green, yellow, red impedance topoplot.

[ENH, MRG] More intuitive colormaps for EEG bridging tutorial

---

examples/preprocessing/eeg_bridging.py

Fixes https://app.circleci.com/pipelines/github/mne-tools/mne-python/14007/workflows/4ea467af-75f3-4cd5-810a-df3798341439/jobs/44109 introduced by https://github.com/mne-tools/mne-python/pull/10571, cc @alexrockhill this is a slightly nicer way to have long URLs in examples (in this case it also fixes the fact that the URL was broken due to extra spaces)

MAINT: Fix link [skip azp] [skip actions]

---

doc/changes/latest.inc
doc/preprocessing.rst
examples/preprocessing/eeg_bridging.py
mne/preprocessing/__init__.py
mne/preprocessing/_csd.py
mne/preprocessing/interpolate.py
mne/preprocessing/tests/test_interpolate.py
mne/transforms.py

Follow-up to https://github.com/mne-tools/mne-python/pull/10571.
I thought it would be nice instead of just dropping bridged electrodes to use them in the interpolation. This just makes a virtual channel halfway between bridged electrodes and then interpolates with the aid of the virtual channel before dropping it. I thought this would be one last nice thing to add.

[ENH, MRG] Add interpolate bridged electrodes function

---

doc/_static/style.css

`main`:
PR:
**Must not be backported!**

MRG: Fix dev documentation warning

---

doc/install/manual_install.rst
doc/install/manual_install_platform_selector.html

Followup for #10580
cc @marsipu

MRG: Recommend mamba instead of libmamba for installation

---

tutorials/intro/70_report.py

I found this functionality by inspecting the API. I think we can increase the visibility by applying it in the tutorial, wdyt?
https://output.circle-artifacts.com/output/job/f2f60271-519a-44af-a7d6-9131d56fee6a/artifacts/0/dev/auto_tutorials/intro/70_report.html#adding-custom-html-e-g-a-description-text

DOC: report.add_html in tutorial

---

doc/changes/latest.inc
mne/utils/docs.py
mne/viz/tests/test_topomap.py
mne/viz/topomap.py

Also improve the documentation and mention that the time windows for averaging actually get clipped at the "ends" of the data.
`main` | this PR
---|---
```python
import mne
preload=True)
evoked = epochs.average()
evoked.plot_topomap(average=0.1);
evoked.plot_joint(topomap_args=dict(average=0.1));
```

MRG: Display averaged time period in Evoked topomap title

---

tutorials/stats-sensor-space/75_cluster_ftest_spatiotemporal.py

seen in https://mne.tools/stable/auto_tutorials/stats-sensor-space/75_cluster_ftest_spatiotemporal.html#find-the-fieldtrip-neighbor-definition-to-setup-sensor-adjacency
The topoplots have a title "0.000 s" that does not make sense in this case and should be removed:

minor, doc: fix subplot titles in tutorial

---

mne/io/snirf/_snirf.py

I noticed this because the mne-bids CI failed. These are probably reasonable fixes, wdyt @rob-luke?
https://github.com/mne-tools/mne-bids/runs/6338742975?check_suite_focus=true#step:15:400

[MRG] FIX: snirf length units

---

doc/changes/latest.inc
mne/utils/docs.py
mne/viz/tests/test_topomap.py
mne/viz/topomap.py
tutorials/evoked/20_visualize_evoked.py

We can now do things like:
```python
evoked.plot_topomap(average=[0.1, 0.2, None, 0.1])
```
to produce
This comes in handy e.g. when plotting topographies for different time periods that were found to be significant e.g. using a cluster-based permutation test.
MWE:
```python
import mne
preload=True)
evoked = …
```

MRG: Allow to pass array of "average" values to plot_evoked_topomap()

---

doc/changes/latest.inc
mne/evoked.py
mne/viz/evoked.py
mne/viz/tests/test_evoked.py
mne/viz/utils.py
tutorials/evoked/20_visualize_evoked.py

Allows to conveniently produce figures like:
Becomes really powerful when combined with `Evoked.plot_topomap()`'s `average` parameter:
MWE:
```python
import mne
preload=True)
evoked = epochs.average()
evoked.plot(
spatial_colors=True, picks='mag', gfp=True,
highlight=[(0.05, 0.13), (0.23, 0.3)]
);
evoked.plot_joint( …
```

MRG: Add "highlight" parameter to Evoked.plot() to conveniently highlight time periods

---

doc/references.bib
tutorials/clinical/10_ieeg_localize.py

Happy to change the wording if it doesn't fit with MNE style but I think it would be nice to promote the addition of new modules to MNE with additional publications. I tried to be subtle about it but I think it would be nice to advertise a tiny bit.

[ENH, MRG] Add citation for intracranial JOSS paper

---

doc/changes/latest.inc
mne/preprocessing/_csd.py
mne/preprocessing/tests/test_csd.py

This is an attempt to fix the issue reported at https://mne.discourse.group/t/saving-epoch-error-no-eeg-channel-found
WIP:

Drop EEG rejection thresholds when replacing EEG with CSD channels

---

tools/azure_dependencies.sh
tools/github_actions_dependencies.sh

For some reason it takes a long time to resolve https://pypi.anaconda.org/scipy-wheels-nightly/simple/pandas/ . We could disable it but hopefully the speed issue is just temporary and this will become a noop over time

MAINT: Fix timeout

---

azure-pipelines.yml
doc/changes/1.0.inc
mne/beamformer/tests/test_lcmv.py
mne/preprocessing/_csd.py
mne/preprocessing/tests/test_csd.py
mne/viz/backends/_utils.py
tools/azure_dependencies.sh
tools/github_actions_dependencies.sh

MRG: Backport #10619 and #10620

---

doc/install/installers_platform_selector.html

The new installers include pqdm and MNE-ICALabel (for Linux and macOS)

MRG: Update installer links to point to 1.0.2_1

---

.github/workflows/linux_conda.yml
environment.yml
tools/setup_xvfb.sh

No idea why but on our 3.9-conda builds we get a deficient OpenGL version:
```
pyvista:             0.34.0 {OpenGL 3.1 Mesa 21.2.6 via llvmpipe (LLVM 12.0.0, 256 bits)}
```
Compared to the one we get from 3.10 pip:
```
pyvista:             0.35.dev0 {OpenGL 4.5 (Core Profile) Mesa 21.2.6 via llvmpipe (LLVM 12.0.0, 256 bits)}
```
This PR bumps to 3.10 and sets `MESA_GL_VERSION_OVERRIDE`

CI: Fix conda [skip azp] [skip circle]

---

doc/overview/faq.rst
mne/channels/tests/test_interpolation.py
mne/io/nirx/nirx.py
mne/io/nirx/tests/test_nirx.py
mne/io/snirf/_snirf.py
mne/io/snirf/tests/test_snirf.py
mne/preprocessing/nirs/tests/test_beer_lambert_law.py
mne/preprocessing/nirs/tests/test_temporal_derivative_distribution_repair.py
tutorials/io/30_reading_fnirs_data.py

Fixes the ordering issue I mentioned in https://github.com/mne-tools/mne-python/pull/10555. Desired orders were pulled from `maint/1.0` where the test passes, and fails on `main` (after #10555). These orders shouldn't ever really need to be read or modified so they are `# noqa: E501`'ed on long lines.
I also restored a bunch of the modified test lines from #10555.
@rob-luke feel free to merge if you're happy
@samuelpowell you might want to reprocess your files if you have read-write round-tripped them after #10555 (e.g., after doing Beer-Lambert or other processing), especially because a naive string sort does not even produce the (presumably) desired result:
```
>>> sorted(['S1_D9', 'S1_D10'])
['S1_D10', 'S1_D9']
```

BUG: Fix bug with fNIRS reordering

---

mne/viz/backends/_utils.py

In Spyder, the IPython Console used to stay inaccessible after a MNEQtBrowser-instance with `raw.plot(block=True)` has been closed. This connects `lastWindowClosed` with the termination of the `QApplication`-instance, which seems to be necessary to make the console accessible again in Spyder.

BUG: Keep IPython in Spyder accessible after MNEQtBrowser closes

---

mne/viz/topomap.py

It looks like there is a typo in the description of the `vmin` argument of `plot_topomap`.
> The value specifying the lower bound of the color range.
>  If None, and vmax is None, -vmax is used.
-> `vmax is NOT None`?

Fix typo in vmin description for plot_topomap

---

mne/viz/topomap.py

Following #10649
Docstring should be correct this time and I added some missing formatting.
If `vmin` AND `vmax` are set to None: https://github.com/mne-tools/mne-python/blob/1349ad88bdfe72d9214fe7496f74b1629985673d/mne/viz/utils.py#L77-L81
If `vmin` is set to None: https://github.com/mne-tools/mne-python/blob/1349ad88bdfe72d9214fe7496f74b1629985673d/mne/viz/utils.py#L87
If `vmax` is set to None: https://github.com/mne-tools/mne-python/blob/1349ad88bdfe72d9214fe7496f74b1629985673d/mne/viz/utils.py#L94

Improvements to the plot_topomap docstring

---

doc/changes/latest.inc
doc/changes/names.inc
mne/channels/channels.py
mne/io/fiff/tests/test_raw_fiff.py

If exclude="bads" (default),
channels marked as bad will not be included.
This will lead to coil type not being fixed
in call to mne.preprocessing.maxwell_filter
3022 (FIFFV_COIL_VV_MAG_T1)to 3024 (FIFFV_COIL_VV_MAG_T3).
`mne.preprocessing.maxwell_filter` fixes the coil type of magnetometers from `3022 (FIFFV_COIL_VV_MAG_T1)` to `3024 (FIFFV_COIL_VV_MAG_T3)`. However, the coil type is not fixed for channels marked as bad. This is because `exclude` argument is `bads` by default for `pick_types`-function.
Tests run only for `mne/preprocessing/tests/test_maxwell.py`.
```bash
>pytest mne/preprocessing/tests/test_maxwell.py
=========================================================================== test session starts =========================================================================== …
```

Pick also bad channels when selecting T1T2 mag indices

---

doc/changes/latest.inc
mne/preprocessing/maxwell.py

We used to not re-filter only if the already-applied filter hfreq was smaller than what was requested, but actually to correct comparison is `<=`.

MRG: In find_bad_channels_maxwell(), do not filter data if existing lowpass filter frequency is equal to the one requested

---

mne/channels/interpolation.py
mne/conftest.py
mne/fixes.py
mne/io/nirx/nirx.py
mne/io/nirx/tests/test_nirx.py
mne/io/snirf/_snirf.py
mne/io/snirf/tests/test_snirf.py
mne/preprocessing/ica.py
mne/preprocessing/nirs/__init__.py
mne/preprocessing/nirs/_beer_lambert_law.py
mne/preprocessing/nirs/_optical_density.py
mne/preprocessing/nirs/_scalp_coupling_index.py
mne/preprocessing/nirs/_tddr.py
mne/preprocessing/nirs/nirs.py
mne/preprocessing/nirs/tests/test_beer_lambert_law.py
mne/preprocessing/nirs/tests/test_nirs.py
mne/preprocessing/nirs/tests/test_optical_density.py
tutorials/io/30_reading_fnirs_data.py

cc @rob-luke I'll ping you when this is ready to go

ENH: Don't require specific order for fNIRS

---

mne/gui/tests/test_gui_api.py
mne/viz/backends/_abstract.py
mne/viz/backends/_notebook.py
mne/viz/backends/_qt.py

This PR refactors `_QtWindow`:
* adds support for custom central layout
* adds `_window_create` to spawn a window 'without pyvista support' (instance of `_MNEMainWindow`)
* ~adds the option `theme_support` to opt-out from automatic theming~
and `_QtLayout`:
* adds support for grid layout
Here is a code snippet to try:
```py
from mne.viz.backends.renderer import _get_renderer
renderer = _get_renderer()
renderer.show()
window = renderer._window_create()
window.show()
```
Further consideration:
* With more refactoring it should be possible to use `_get_renderer()` to spawn `_MNEMainWindow` instead of using `_PyVistaRenderer`. This more important matter is about about having a GUI API which does not depends on `pyvista`.
It's an item of https://github.com/mne-tools/mne-python/pull/10565

MNT: window and layout in GUI API

---

doc/changes/latest.inc
mne/datasets/config.py
mne/io/nirx/nirx.py
mne/io/nirx/tests/test_nirx.py

The fNIRS vendor NIRx released a new version of their acquisition software "2021.9.0.6".
This version changed the way they store triggers in the `.tri` file.
This PR enables reading of the new trigger file format.
Associated testing data and description of file format change is at https://github.com/mne-tools/mne-testing-data/pull/97
Testing data version and hash will be updated when merged.

Support NIRx Aurora 2021.9.6 files

---

mne/viz/ica.py

This is a followup of #10557 and adds the following improvements to the docstrings:
- Mentions newly-introduced keyboard shortcuts
- Adds a `versionadded` tag for the new `log_scale` kwarg
Following some user confusion voiced at https://mne.discourse.group/t/how-to-plot-ica-component-properties-in-log-log-scale
cc @alexrockhill

Improve ICA docstrings following #10557

---

doc/changes/latest.inc
mne/evoked.py
mne/export/tests/test_export.py
mne/io/egi/tests/test_egi.py
mne/tests/test_evoked.py
mne/tests/test_source_estimate.py

We didn't apply the temporal mask to the data when checking if all values are either positive or negative, and hence these checks didn't always fire when they were supposed to.
This issue was reported on the forum:
https://mne.discourse.group/t/get-peak-mode-pos-also-gives-negative-values/4931

MRG: Fix sign checks in Evoked.get_peak()

---

doc/changes/latest.inc
mne/channels/channels.py
mne/channels/tests/test_channels.py

As discussed [here](https://mne.discourse.group/t/when-is-baseline-correction-applied/4986), this PR retains baseline information after using `mne.channels.combine_channels()` on `Epochs` or `Evoked`.

Retain baseline after combining channels

---

doc/changes/latest.inc
mne/tests/test_epochs.py
mne/utils/mixin.py

Fixes #10700. Let's see if all tests still pass.

Replace metadata eval with query

---

mne/surface.py
mne/tests/test_surface.py

Take care of pip-pre failures like https://github.com/mne-tools/mne-python/runs/6766628211?check_suite_focus=true by using a generic SpatialImage rather than Nifti1Image

MAINT: Deal with nibabel deprecation

---

doc/references.bib
tutorials/forward/25_automated_coreg.py

Minor cleanup, no issue
I noticed a few minor typos (e.g., slashes not quoted) and have addressed. Copy-and-paste into python should now work for this one. Also added a cite for the paper that assessed the reliability of the method.

Fix coreg tutorial typos

---

azure-pipelines.yml
mne/annotations.py

One easy step from #10704: make Azure steps depend on the style step succeeding. This first commit adds a style error, so hopefully what we see is red CI with only Azure running the style tests, not everything. Then I'll push a commit to remove the style error, then hopefully we see all green Azure.

CI: Add style conditional

---

mne/utils/docs.py

#10722 introduced a few mistakes into the docdict. This fixes them, and also uses the `_reflow_param_docstring()` function to make them look nice in the terminal (see example below).
on main:
```py
In [1]: import mne
In [2]: mne.io.Raw.pick?
Signature: mne.io.Raw.pick(self, picks, exclude=(), *, verbose=None)
Docstring:
Pick a subset of channels.
Parameters
----------
picks : str | list | slice | None
Channels to include. Channels to include. Slices and lists of integers will be interpreted as channel indices. In lists, channel *type* strings
(e.g., ``['meg', 'eeg']``) will pick channels of those
types, channel *name* strings (e.g., ``['MEG0111', 'MEG2623']``
will pick the given channels. Can also be the string values
"all" to pick all channels, or "data" to pick :term:`data channels`. …
```

fix recent docdict mistakes

---

doc/changes/latest.inc
mne/viz/utils.py
tutorials/intro/70_report.py

`main`:
PR:
MWE:
```python
import mne
preload=True)
evoked = epochs.average()
evoked.pick_types(eeg=True)
r = mne.Report(title='Test Report')
r.add_evokeds(
evokeds=evoked,
titles='Evoked Responses',
projs=False,
n_time_points=1,
)
r.save('/tmp/test.html', overwrite=True)
```

MRG: In Report, remove black border appearing on figures created from NumPy arrays

---

mne/coreg.py

`density` exists already in our min NumPy (1.18) and is preferred to `normed` so just use it directly.

FIX: For NumPy pre

---

doc/changes/latest.inc
mne/channels/montage.py
mne/channels/tests/test_montage.py
mne/utils/docs.py
tutorials/intro/40_sensor_locations.py

The motivation was to make it easier for users to programmtically find out which standard montages are available.
WIP:

MRG: Add "descriptions=False" kwarg to get_builtin_montages, and use get_builtin_montages in sensor location tutorial

---

mne/utils/check.py

MRG: Remove recommended upper PyQt version bound for macOS in warning

---

doc/install/contributing.rst

The new URL makes me a little bit suspicious that this will be fragile. Let's try it, and if it fails in another week or month maybe we'll add one to `_static` outselves

FIX: Fix link [ci skip]

---

mne/conftest.py
mne/datasets/config.py
mne/decoding/time_delaying_ridge.py
mne/filter.py
mne/stats/regression.py

I manually made a 0.136 tarball because I can't download it from GH, let's see if I did it correctly. If not, I can work to fix it.
Hopefully we can revert this very soon, but even if we can't, we could sustain this way of doing things at least until we run out of osf.io space. In the meantime, we should really have CIs working right around release time...

MAINT: Work around GH download failures

---

doc/_includes/forward.rst
doc/_includes/morph.rst
doc/_static/style.css
doc/install/contributing.rst
doc/install/mne_tools_suite.rst
doc/overview/datasets_index.rst

This PR:
- makes the sphinx-gallery generated "download notebook" buttons look like other buttons on our site
- styles the `.. sidebar::` directive to use the theme colors & sphinx-design shadows

unify style of sidebars & SG-buttons w/ sphinx-design

---

mne/io/ctf/ctf.py
mne/io/ctf/eeg.py
mne/io/ctf/hc.py
mne/io/ctf/res4.py
mne/io/ctf/tests/test_ctf.py

Currently when a `.meg4` file cannot be found a cryptic error message is given:
```
UnboundLocalError: local variable 'first_samps' referenced before assignment
```
This raises a proper error like:
```
Could not find any data, could not find the following files: ['testdata_ctf.meg4'], and the following files had no valid samples: []
```
No need for a `latest.inc` here I think since it just improves an error message.

MAINT: Better error when missing a file

---

.github/workflows/linux_pip.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

doc/changes/latest.inc
doc/conf.py
mne/commands/mne_coreg.py
mne/gui/__init__.py
mne/gui/_coreg.py
mne/gui/_ieeg_locate_gui.py
mne/gui/tests/test_coreg_gui.py
mne/gui/tests/test_ieeg_locate_gui.py
tutorials/clinical/10_ieeg_localize.py
tutorials/forward/20_source_alignment.py

Fixes https://github.com/mne-tools/mne-python/issues/9451, fixes https://github.com/mne-tools/mne-python/issues/10801.

[ENH, MRG] Add coregistration video and execute GUI in tutorial to show window & add show and block to GUIs

---

doc/conf.py

Fixes bug from https://github.com/mne-tools/mne-python/pull/10777.

[MAINT, MRG] remove memory profiler, makes zombie processes on MacOS

---

mne/conftest.py
mne/gui/_core.py
mne/gui/_ieeg_locate_gui.py
mne/gui/tests/test_core_gui.py
mne/gui/tests/test_ieeg_locate_gui.py

The goal is to abstract the slice browsing for the other GUI that does time-frequency viewing on a volumetric source estimates. Here is a working version of the slice browser itself:
```
import nibabel as nib
import nilearn.plotting
from dipy.align import resample
import mne
from mne.datasets import fetch_fsaverage
from mne.gui._core import SliceBrowser
misc_path = mne.datasets.misc.data_path()
sample_path = mne.datasets.sample.data_path()
subjects_dir = op.join(sample_path, 'subjects')
fetch_fsaverage(subjects_dir=subjects_dir, verbose=True)  # downloads if needed
mne.viz.set_3d_backend('pyvistaqt')
T1 = nib.load(op.join(misc_path, 'seeg', 'sample_seeg', 'mri', 'T1.mgz'))
CT_orig = nib.load(op.join(misc_path, 'seeg', …
```

[ENH, MRG] Abstract slice browser

---

.github/workflows/compat_old.yml
examples/decoding/decoding_unsupervised_spatial_filter.py
mne/channels/tests/test_channels.py
mne/commands/tests/test_commands.py
mne/conftest.py
mne/io/eeglab/tests/test_eeglab.py
mne/io/nirx/tests/test_nirx.py
mne/preprocessing/_csd.py
mne/source_space.py
mne/tests/test_annotations.py
mne/tests/test_cov.py
mne/viz/misc.py
mne/viz/tests/test_raw.py
tutorials/intro/70_report.py
tutorials/preprocessing/25_background_filtering.py

We shouldn't need some warning skips I put in recently as they should have been fixed by https://github.com/scipy/scipy/pull/16393 .
While we're at it, I figured we should see how many other warning skips we can remove completely. Tests pass locally for me with these changes, but I expect some issues with the old/compat builds.
There is a list in `doc/conf.py` that should be updated, too, but I'll do that in a separate PR. I'll iterate locally on that one first to save CircleCI some time.
Closes #10837

FIX: Remove most warning skips

---

doc/changes/latest.inc
mne/io/ctf/ctf.py

Fix an overflow error that prevents reading large files on Windows. No new test added because we'd need a file > 4 GB and I'm not sure how to mock one.

BUG: Fix bug on CTF + Windows

---

mne/viz/tests/test_topomap.py
mne/viz/topomap.py

`mne.viz.plot_topomap` takes a `cnorm` parameter to allow one to pass a [`matplotlib.colors.Normalize`](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.Normalize.html#matplotlib.colors.Normalize) object to control how the colormap is applied to the values. Common use cases is to force the 0 to be at the center of the colormap. Before, only `TwoSlopeNorm` was allowed, but there is no reason not to accept all subclasses of `Normalize` here.
closes #10871

Relax the type checking for the cnorm paramter of plot_topomap

---

doc/changes/latest.inc
mne/io/artemis123/artemis123.py
mne/io/base.py
mne/io/brainvision/brainvision.py
mne/io/brainvision/tests/test_brainvision.py
mne/io/egi/egi.py
mne/io/egi/egimff.py
mne/io/egi/tests/test_egi.py

Closes #10848.
I'm, 99% sure the `dtype` for EGI recordings is `float32`, and that seems coherent with the code in MNE (`'<f4'` and in `mffpy`). Instead of setting the `.orig_format` attribute to `"float"`, it now sets the attribute to `"single"`.
EDIT: I've checked the specification, it is float32.
The QT browser is compatible with `"single", "double", "int", and "short"`: https://github.com/mne-tools/mne-qt-browser/blob/d9c23703658abfc56113cdaff8470952bf3100b1/mne_qt_browser/_pg_figure.py#L3853-L3856
I added a check of the `orig_format` value in `BaseRaw.__init__`, let's see if other readers provide a different value.

MRG: Change orig_format for EGI, BrainVision ASCII and artemis123 recordings to "single"

---

doc/install/contributing.rst
doc/links.inc

updates our guidance on using `make` in windows.
I started to deduplicate the links on that page with `links.inc` but will leave that for another PR.

fix contrib guide

---

doc/_templates/autosummary/class_no_inherited_members.rst
doc/conf.py
doc/forward.rst
requirements_doc.txt

Needs https://github.com/numpy/numpydoc/pull/415. Removes super class stuff we don't want to document.
Perhaps we want this for `Info`, too, but there it's not so simple because we want the methods from some subclasses but not others.

DOC: Clean up Forward and SourceSpaces

---

requirements_doc.txt

@drammock I think I'd rather do this on CircleCI so that we see problems (and get fixes) early.
If you don't like this approach, another option would be to update this pin to another commit, make sure it's okay, then in the `dev` build only use latest `main`. But hopefully pydata-sphinx-theme is stable enough that we can just stick with `main`...?

MAINT: Always use latest main of pydata-sphinx-theme

---

mne/utils/docs.py

Following #10934 and #10936
Anand and I got confused with the docstring of `picks_ica`: an int would pick only one IC and I thought at the beginning it would pick up to this IC.
Does this look better in your opinion?

Improve documentation of picks for IC

---

doc/changes/latest.inc
mne/epochs.py
mne/time_frequency/tests/test_tfr.py
mne/time_frequency/tfr.py
mne/utils/__init__.py
mne/utils/mixin.py

Fixes memory failures here https://github.com/mne-tools/mne-python/pull/10920. 
I just needed the decimate method but while I was changing that, it made sense to add in `tmin` and `tmax` and to mak `times` readonly as in `Epochs`.

[ENH, MRG] Add decimate to EpochsTFR object

---

mne/utils/check.py

should address the CI failures seen in #10930, i.e. https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=20750&view=logs&j=305851a9-a7bb-55db-0042-7e2b6f48aa1c&t=77eb5bf7-3205-5b54-06c6-183c8195d846&l=3208
closes #10943

fix _ensure_events for numpy 1.24

---

doc/glossary.rst

DOC: FIX: circular reference in events

---

doc/changes/latest.inc
mne/io/ctf/info.py
mne/io/ctf/tests/test_ctf.py

I encountered a bug when reading a CTF dataset with an empty string in the `res4['data_date']` and  `res4['data_time']` fields.
This sets the field to January 1st of the year 1001 (earlier make a date parsing bug)

FIX: ctf data can sometimes have no date time.

---

doc/changes/latest.inc
mne/datasets/config.py
mne/io/edf/edf.py
mne/io/edf/tests/test_edf.py

Fixes #10960. The [EDF standard](https://www.edfplus.info/specs/edfplus.html#annotation) mandates that annotations are encoded as UTF8 (we used `latin-1`). I am a bit hesitant to make this change though, because of the comment in this section:
> `use of latin-1 because characters are only encoded for the first 256 code points and utf-8 can triggers an "invalid continuation byte" error`
However, if all tests pass we should probably be fine.

Support UTF8 EDF annotations

---

mne/surface.py
mne/tests/test_surface.py

Following #10930 I noticed a slowdown in tests:
```
14.56s call     mne/tests/test_surface.py::test_project_onto_surface[accurate-False]
```
My goal was to speed this up, but in so doing I improved the test to actually sanity check the returned values (by making use of our unit sphere surfaces) and found a bug with the normal vector return value.
No need for `latest.inc` update since this is a private function

BUG: Fix bug with normal return

---

examples/simulation/simulated_raw_data_using_subject_anatomy.py
examples/simulation/source_simulator.py
examples/time_frequency/source_power_spectrum_opm.py
examples/time_frequency/time_frequency_global_field_power.py
examples/visualization/3d_to_2d.py
examples/visualization/brain.py
examples/visualization/meg_sensors.py
examples/visualization/mne_helmet.py
mne/forward/_field_interpolation.py
mne/io/bti/bti.py

This should take care of the last few cases of `op.join` in our examples. While at it I  applied `isort` to the imports in those files.

use pathlib (and sort imports) in last few examples

---

doc/changes/latest.inc
mne/decoding/tests/test_transformer.py
mne/decoding/transformer.py

Closes #10924
The bug turned out to be that the *outputs* were used incorrectly. The `l_stop` and `h_stop` that are returned by `_triage_filter_params` were assumed to be the `l_trans_bandwidth` and `h_trans_bandwidth`. We can avoid this just by not calling the function twice.

BUG: Fix bug with TemporalFilter

---

mne/tests/test_proj.py

Loosening one bound from 19 to 18 decimal places fixes a test failure when using Netlib BLAS on x86_64; see https://github.com/mne-tools/mne-python/issues/10985#issuecomment-1201968450 and the following comments.
See https://github.com/mne-tools/mne-python/issues/10985#issuecomment-1201968450; but this does not fix or close the issue in which that comment appears.
Slightly loosens a very strict test bound to allow for implementation differences.
Fixes the following failure on `x86_64` when numpy is using (flexiblas with) Netlib BLAS backend:
```
________________________ test_make_eeg_average_ref_proj ________________________
mne/tests/test_proj.py:341: in test_make_eeg_average_ref_proj
assert_array_almost_equal(reref._data[eeg].mean(axis=0), 0, decimal=19)
E   AssertionError: 
E   Arrays …
```

TST: Loosen test_make_eeg_average_ref_proj bound

---

doc/changes/latest.inc
mne/io/eeglab/_eeglab.py
mne/io/eeglab/eeglab.py
mne/io/eeglab/tests/test_eeglab.py
mne/utils/__init__.py
mne/utils/check.py

Fixes #11005. Tests need to be adapted to test HDF5 and non-HDF5 files separately.

Use `scipy.io.loadmat()` fallback for EEGLAB reader

---

mne/tests/test_docstring_parameters.py
mne/utils/docs.py

One for @alexrockhill to review. This was motivated by [this CI error](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=21039&view=logs&j=2bd7b19d-6351-5e7f-8417-63f327ab45bc&t=0c49e006-47ab-5675-a040-5d301cde7356&l=3268) which should be fixed by the explicit `encoding` param; while I was at it I simplified the test and added a test case.

improve docdict test

---

mne/export/_eeglab.py

N/A
Adds support for annotations when exporting epochs to eeglab (set) format. Based on updates to the [eeglabio](https://github.com/jackz314/eeglabio) package.
Annotations will be converted and merged with the events array in eeglab, this behavior is consistent with when exporting raw data to eeglab. 
users with the older version of eeglabio and the updated version of mne would have to update eeglabio to `>=0.0.2`, since the `annotations` field doesn't exist in older versions.

Add annotations support for exporting epochs to eeglab format

---

mne/forward/tests/test_make_forward.py

Closes #11023
Locally I could not replicate with `conda env create -n mne -f environment.yml`. We'll see if CIs are happy with this. I'm not too worried about this as a fix since it's possible/likely that fitting is slightly worse here for one dipole because the fitting optimization is non-convex and we're probably just finding a local minimum somewhere due to numerical precision differences...

MAINT: Bump SNR to help CIs

---

doc/changes/latest.inc
mne/transforms.py
tutorials/clinical/10_ieeg_localize.py

I was using this pipeline for my own research and noticed on the manual registration, we used the T1 affine to transform back but since it's not aligned this doesn't make any sense; it needs to go back to RAS coordinates of the CT. I've tested and this works but it's tough to test in the documentation because it would require manual input in freesurfer.

[BUG, MRG] Fix wrong affine used in T1/CT manual registration

---

doc/_includes/channel_types.rst
doc/changes/0.23.inc

I assume this is a leftover from:
- https://github.com/mne-tools/mne-python/pull/11022
came up in:
-  https://github.com/mne-tools/mne-bids/issues/1046
cc @hoechenberger @larsoner 
xref for why I label the units as "Volts":
- #8858

fix remaining resp: respiration!=response

---

mne/export/tests/test_export.py

These red CIs are a pain, let's `xfail` the `eeglabio` epochs export test for now

MAINT: xfail for now

---

doc/changes/latest.inc
mne/viz/misc.py
mne/viz/tests/test_misc.py

When plotting a 'ba' type filter with `compensate=True` on the function would crash, because arguments were passed wrongly

mne.viz.plot_filters was failing for ba filter, fixed

---

.github/workflows/codespell_and_flake.yml
ignore_words.txt

switches our CIs to use a pinned version of the upstream codespell action instead of Guillaume's fork of it.  I'm not 100% sure this will work, since we were previously running off [a branch of Guillaume's fork that had some changes vs upstream](https://github.com/codespell-project/actions-codespell/compare/master...GuillaumeFavelier:actions-codespell:feat/quiet_level), but then again, in the workflows YAML file we're specifying `quiet_level: 3` so I think we weren't even making use of Guillaume's customizations (?)
tagging @GuillaumeFavelier to possibly clarify this

use upstream codespell action

---

doc/changes/latest.inc
mne/viz/topomap.py
tutorials/time-freq/20_sensors_time_frequency.py

This avoids plotting a colorbar next to every topomap when we know that all of them have the same color scale.

plot_psd_topomap: suppress redundant colorbars when vlim='joint'

---

tutorials/time-freq/20_sensors_time_frequency.py

reverts a tutorial change that was mostly meant as a test of changes to module code; turns out it's already demoed elsewhere (and is more appropriate in those other contexts)
ref: https://github.com/mne-tools/mne-python/pull/11051#issuecomment-1220354886  and subsequent comments.

revert vlim=joint in TF tutorial

---

mne/utils/config.py
requirements.txt
tutorials/intro/50_configure_mne.py

[threadpoolctl](https://pypi.org/project/threadpoolctl/) is the standard way to get info about bindings, let's use it instead of our own parser (which fails sometimes anyway).

ENH: Use threadpoolctl for better linalg parsing

---

.circleci/config.yml

I don't remember why we've been using Python3.8 on CircleCI. Let's see if we can upgrade to 3.10.
While we're at it, let's build on 22.04 instead of 20.04

MAINT: Upgrade Python on CircleCI

---

doc/changes/latest.inc
doc/changes/names.inc
mne/bem.py
mne/dipole.py
mne/forward/_field_interpolation.py
mne/forward/_make_forward.py
mne/forward/tests/test_field_interpolation.py
mne/source_estimate.py
mne/utils/docs.py
mne/viz/_3d.py

Hello - this is my first PR - let me know if I've missed anything
Example: Fixes #10784.
This PR changes the loading of the trans information in `make_field_maps` and `plot_alignments`. This now uses the standard `mne.transforms._get_trans` logic and preserves the possibility to use `trans='auto'` to load from a specified fs subject directory. 
Docstrings have been updated and the `test_field_map_ctf` now loads the trans via a `pathlib.Path`.
Where these functions tested for `trans is None`, we now check if `trans == 'identity'` as this this is the default of `_get_trans`

Fix trans loading logic in make_field_map

---

.circleci/config.yml
doc/changes/latest.inc
mne/channels/channels.py
mne/channels/tests/test_channels.py

Example: Fixes #11043.
This PR adds _on_missing functionality to UpdateChannelsMixin to customise behaviour when specified channel names are not found in object.

Add _on_missing functionality to UpdateChannelsMixin

---

doc/changes/latest.inc
doc/changes/names.inc
mne/evoked.py
mne/viz/topomap.py

Fixes #10725 .
Add `vmin` and `vmax` specification to `mne.Evoked.animate_topomap`

Add `vmin` and `vmax` specification to `mne.Evoked.animate_topomap`

---

doc/changes/latest.inc
mne/viz/tests/test_topomap.py
mne/viz/topomap.py

I remember seeing that it was now possible to set `sphere="eeglab"` but it requires that an `Info` gets provided to `_check_sphere`.
Failing on main, fixed here:
```
import mne
raw_fname = mne.datasets.eegbci.load_data(subject=6, runs=(1,))[0]
raw = mne.io.read_raw(raw_fname, preload=True, verbose=False)
mne.datasets.eegbci.standardize(raw)  # set channel names
raw.set_montage("standard_1005", verbose=False)
bridged_idx, ed_matrix = mne.preprocessing.compute_bridged_electrodes(raw)
mne.viz.plot_bridged_electrodes(
raw.info, 
bridged_idx, 
ed_matrix, 
topomap_args=dict(vmax=5, sphere="eeglab")
)
```
The test I added is a bit indirect, but it was simpler 😅

[BUG] Fix plot_topomap with sphere="eeglab"

---

doc/changes/latest.inc
doc/changes/names.inc
mne/io/eeglab/eeglab.py
mne/io/eeglab/tests/test_eeglab.py

Load a specific `.set` file broke in the latest release of MNE. The reason is a regression introduced along with 5e60e475ef8019af73cc81e184a10bde524c681f, which assumes that certain fields exist, thus resulting in a crash when they don't. It's possible that my `.set` is non-standard, I'm not familiar enough with the format to be able to say that, but this PR seems safe enough in any case.
closes #11039

BUG: don't assume that channel info contains particular keys

---

.github/ISSUE_TEMPLATE/documentation.md
Makefile
mne/beamformer/tests/test_dics.py
mne/bem.py
mne/coreg.py
mne/data/FreeSurferColorLUT.txt
mne/filter.py
mne/forward/forward.py
mne/io/base.py
mne/io/eeglab/tests/test_eeglab.py
mne/io/snirf/_snirf.py
mne/report/js_and_css/report.js
mne/simulation/raw.py
mne/utils/docs.py
mne/viz/_brain/_brain.py

Found using codespell and regex

Fix various typos

---

doc/changes/latest.inc
mne/channels/montage.py
mne/channels/tests/test_montage.py
mne/io/_digitization.py

When calling `.set_montage()`, all digitized points are transformed into head coordinate space if possible. This is not possible when there are no fiducials and the original points are not in head space already. MNE-Python is lenient when the coordinate space of the original points is marked as "unknown", assuming they are in head space. However, when the points are explicitly marked as being in some other space (e.g. MRI), then they will not get converted without fiducials.
Since MNE-Python requires all EEG channel positions to be in head space, we should raise an error when `.set_montage()` fails to do this.
Fixes #10946.

Add error message when conversion of EEG locs to head space fails

---

doc/changes/latest.inc
mne/io/edf/edf.py
mne/utils/docs.py

related to https://github.com/mne-tools/mne-bids/pull/1045 and https://github.com/mne-tools/mne-bids/issues/1044
now with the data from ds003775 you can just do:
`raw = mne.io.read_raw_edf(bp, units='uV')`
and in mne-bids
`raw = read_raw_bids(bp, extra_params={'units': 'uV'})`
what do you think @sappelhoff @hoechenberger ?

ENH : add units parameter to read_raw_edf in case units is missing from the file

---

doc/changes/latest.inc
mne/io/bti/bti.py
mne/io/bti/tests/test_bti.py

We can do better with the logic:
1. Unknown channels should be MISC not ECG
2. Check for HEOG/VEOG prefixes to set as EOG
3. Check for EMG prefix to set as EMG
4. Check for `anode-cathode` pattern for EEG channel names to automatically set as EEG
Closes #10988

BUG: Improve logic for bti

---

mne/io/edf/edf.py
mne/io/edf/tests/test_edf.py

follow up on https://github.com/mne-tools/mne-python/pull/11099#issuecomment-1229152014

add test for edf units param

---

doc/changes/latest.inc
mne/channels/channels.py
mne/io/pick.py

@larsoner I discovered a bug (mapping temperature to Coulomb instead of Celsius) and an oversight in #11090 when trying to actually read GSR and temperature data.

MRG: Fixes for #11090

---

mne/utils/__init__.py
mne/utils/docs.py
mne/utils/tests/test_docs.py

Add legacy decorator

---

doc/conf.py
requirements_doc.txt
tools/circleci_dependencies.sh

Related to https://github.com/sphinx-gallery/sphinx-gallery/pull/983. Just building first, can add a link in documentation after.

Add API entry list and map

---

examples/visualization/topo_customized.py
mne/time_frequency/psd.py
tools/azure_dependencies.sh
tools/github_actions_dependencies.sh
tutorials/time-freq/20_sensors_time_frequency.py
tutorials/time-freq/50_ssvep.py

Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/16083/workflows/81bf3b30-eac1-462f-a71b-ecadc0dee745/jobs/48513
@drammock I'm going to mark for merge when green to fix CircleCI, but feel free to take a look and open a follow-up PR with better changes if you have some in mind!
FYI one tutorial could be cleaned up nicely when `EpochsSpectrum` gets a `.average(method='mean' | 'median')` mode, but I'm assuming that's already in the plan somewhere!

BUG: Spectrum deprecation cleanup

---

mne/dipole.py
mne/forward/_compute_forward.py
mne/forward/_make_forward.py
mne/forward/forward.py
mne/forward/tests/test_make_forward.py
mne/preprocessing/maxwell.py
mne/preprocessing/tests/test_maxwell.py
mne/simulation/raw.py
mne/simulation/tests/test_evoked.py

Refactor forward solution code to eventually make it easier to add channel types. This PR's goals:

MAINT: Refactor forward solution code

---

mne/time_frequency/spectrum.py
mne/utils/docs.py
mne/viz/epochs.py
mne/viz/raw.py
mne/viz/topomap.py
mne/viz/utils.py

follow-up to #11097
- marks several functions/methods as legacy
- slight clean-up of the `logger.info` message that is generated by the decorator
@larsoner as we discussed, I poked around in the recent issues/PRs but didn't find any clear cases of things that should be marked `@legacy`.  Feel free to push here, or just mention what they are if you think of them.

Mark legacy

---

examples/inverse/psf_ctf_vertices.py
examples/inverse/psf_volume.py
mne/minimum_norm/resolution_matrix.py

The example modifications I made took the example from 427.1 MB to 2289.5 MB, which [killed CircleCI](https://app.circleci.com/pipelines/github/mne-tools/mne-python/16149/workflows/768c215e-75b1-4df4-9b4d-585b373cbca3/jobs/48654). Let's see if we can get it down to at least 1-1.5GB. If not we might have to compute a lower-resolution volumetric forward/inv :(

MAINT: Fix mem usage

---

mne/viz/backends/_pyvista.py

This should be more forward-compatible with our use of this private attribute. Related to https://github.com/pyvista/pyvista/pull/3245

MAINT: Pop instead of del

---

doc/changes/latest.inc
examples/time_frequency/time_frequency_simulated.py
mne/time_frequency/_stockwell.py
mne/time_frequency/tests/test_stockwell.py

I think this is an important methods comparison as the Hilbert transform is a popular choice in some electrophysiology circles. I definitely have been asked about it and I think it's nice to compare in this example. Also, it's a good demonstration of how to coerce this kind of data to fit within the API since it doesn't fit naturally very well with the other time-frequency methods.

[ENH, MRG] Add Hilbert to TFR methods comparison

---

mne/preprocessing/ica.py
mne/preprocessing/tests/test_ica.py

This is mostly a code health change fixing an internal inconsistency that I just ran into while working on another feature:
When calling the private `ICA._reset()` method, we forgot to reset `ICA.current_fit` as well.
This change causes no user-facing alterations.
MWE:
```python
import mne
mne.set_log_level('WARNING')
sample_dir = mne.datasets.sample.data_path()
raw = (
mne.io.read_raw_fif(sample_fname)
.crop(tmax=60)
.pick_types(eeg=True)
.load_data()
)
ica = mne.preprocessing.ICA(n_components=15, method='picard')
print(f'Before fit:\t{ica.current_fit}')
ica.fit(raw)
print(f'After fit:\t{ica.current_fit}')
ica._reset()
print(f'After reset:\t{ica.current_fit}')
```
On `main`:
```
Before fit:	unfitted
After fit:	raw …
```

On ICA._reset(), reset current_fit to "unfitted"

---

mne/channels/montage.py
mne/io/kit/coreg.py
mne/io/meas_info.py
mne/preprocessing/artifact_detection.py
mne/transforms.py

Minor improvements to the documentation formatting and x-ref related to `mne.transforms.Transform`.

[DOC] Improve doc format and x-ref related to coordinate transformation

---

mne/io/edf/edf.py
mne/io/edf/tests/test_edf.py

Should fix within-cycle bug introduced by @agramfort #11099, visible in [this MNE-BIDS-Pipeline Circle run](https://app.circleci.com/jobs/github/mne-tools/mne-bids-pipeline/31945?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). The use of `read_raw(..., units='uV')` there should be acceptable it seems since all channels do have uV units.

BUG: Allow pass-through of correct units

---

mne/preprocessing/annotate_amplitude.py

It's looking a bit weird, so I removed the non-formatted `5` and only kept the unit in brackets.

[DOC, MRG] De-duplicate default value for bad_percent in annotate_amplitude

---

doc/changes/latest.inc
mne/io/bti/bti.py
mne/io/cnt/cnt.py
mne/io/curry/curry.py
mne/io/curry/tests/test_curry.py
mne/io/egi/egi.py
mne/io/fieldtrip/tests/helpers.py
mne/io/fieldtrip/tests/test_fieldtrip.py
mne/io/tests/test_raw.py
mne/io/utils.py

Fixes bugs with a few `read_raw_*` functions where `info['dig']` was not set even though EEG channel locations were read. Also moves us toward using `eeg_ch['loc'][:3] = np.nan` rather than `= 0`, which at some point I think we decided was a better way to go.

BUG: Fix bugs with digitization

---

mne/io/pick.py
mne/viz/_figure.py
mne/viz/raw.py
mne/viz/tests/test_raw.py
mne/viz/utils.py

This minimal example now produces a plot:
```
import mne
data = np.random.RandomState(0).randn(2, 1000)
data[0] += 37  # deg C
info = mne.create_info(2, 1000., ['temperature', 'gsr'])
raw = mne.io.RawArray(data, info)
fig = raw.plot()
```
Can't really tell if the scale is reasonable until the dataset in #11112 is confirmed as correct or fixed.
Helps with #11112 but does not close it, because we still haven't ensured that temperature and GSR data are actually displayed properly, as we don't yet have a reliable dataset to check with.

BUG: Fix bugs with temperature and GSR plotting

---

tools/azure_dependencies.sh
tools/github_actions_dependencies.sh

NumPy folks were lightning fast fixing the memory bug (https://github.com/numpy/numpy/pull/22236) and even pulled the offending wheels, so let's restore the nightly. While we're at it, restore the PyQt6 one (which appears to be fixed) and try to streamline some others and prefer the Anaconda wheels to the rackcdn.

MAINT: Restore NumPy nightly

---

doc/changes/latest.inc
mne/io/edf/edf.py
mne/io/edf/tests/test_edf.py
mne/utils/docs.py

Fixes #11135. This PR adds a new parameter `encoding` to `read_raw_edf()` and `read_raw_bdf()` (as well as the underlying `RawEDF` class). Users can set a custom encoding of their annotation channel(s), which by default (and according to the EDF+ standard) is UTF8, but many files in the wild seem to ignore the standard and use Latin-1.

Add encoding parameter to read_raw_{eb}df()

---

mne/channels/channels.py
mne/io/base.py
mne/io/edf/tests/test_edf.py
mne/io/fiff/tests/test_raw_fiff.py

Closes #11119
1. Make `raw._orig_units` always a dict (often empty), easier than dealing with `is not None` (just check for emptiness if needed)
2. Fix bug where `_orig_units` was not updated when picking/dropping channels or when adding channels
No need for `latest.inc` update because this is a private param only used AFAIK by `MNE-BIDS`. Maybe someday we should make this public somehow. But it seems like the correct fix is really perhaps to use the channel info about units and/or cals better someday.

BUG: Fix consistency bug with orig units

---

mne/chpi.py

Fixes #11162 by adding the `on_missing` argument to the get_active_hpi function
Not sure why, but I have problems using the `%(on_missing_chpi)s` pattern, even though I just copy&pasted within that same file. So the documentation doesn't properly render yet.

add on_missing keyword to mne.chpi.get_active_hpi()

---

doc/changes/latest.inc
mne/viz/evoked.py
mne/viz/tests/test_evoked.py

…for spatial_colors feature
Fixes #6870
Evoked butterfly plots with spatial_colors=True will plot all traces in black when any of the DigMontage coordinates are nan. The expected behaviour is that sensors with nan coordinates will be in black, while the remaining traces will be coloured.
This fix uses `np.nanmin` and `np.nanmax` instead of `np.amin` and `np.amax` when transforming x,y,z coordinates into colours, resulting in the expected behaviour.

ignore nan values when transforming 3d coords into colours

---

tutorials/simulation/70_point_spread.py

At first I thought https://app.circleci.com/pipelines/github/mne-tools/mne-python/16450/workflows/137bf0a0-695c-4e40-80de-ccee2cfade73/jobs/49292 was a false alarm, but I think it did the right thing to warn that an EEG channel was missing from the projector.

BUG: Fix bug with tutorial

---

mne/viz/_brain/tests/test_brain.py

At some point I'll debug why this only happens on matplotlib 3.6 on conda-forge, but in the meantime let's make things green.

MAINT: Tweak tol for screenshot

---

doc/changes/latest.inc
mne/_freesurfer.py
mne/coreg.py
mne/dipole.py
mne/tests/test_coreg.py

Closes #11184
1. Introduce a `mne.head_to_mri(..., kind=None)` that via deprecation changes from `kind='ras'` (1.2) to `kind='mri'`. Everywhere else in MNE when we say MRI coordinate frame we mean FreeSurfer surface RAS, so it should mean that here, too...
2. ... fixes a bug where we were using `kind='ras'` implicitly in `Dipole.to_mri`
3. Adds the `unscale=False` proposed in #11184

ENH: Add unscale=True to head_to_mri

---

.circleci/config.yml

@drammock feel free to merge if you agree the linkcheck can be checked once a month rather than once a week. To me if a link breaks it's not super high priority, and given that there are false alarms due to server outages more weekends than not, let's clean up our notifications a bit...

MAINT: Fix cron for CircleCI

---

doc/changes/latest.inc
mne/io/hitachi/hitachi.py
mne/io/hitachi/tests/test_hitachi.py
mne/io/tests/test_raw.py
mne/preprocessing/nirs/_beer_lambert_law.py
mne/preprocessing/nirs/nirs.py
mne/utils/docs.py

If you have multiple probes simultaneously for Hitachi systems, it outputs separate CSVs that correspond to the same recording. This allows passing list-of-str to `read_raw_hitachi` to get these as a single raw instance.
An alternative would maybe be to use `raw.add_channels(other)`, but this will create problems with channel name collisions that we can avoid here.
Also fixes a minor bug with the `source_detector_distances` docstring, and `beer_lambert_law` that I don't think are worth mentioning in `latest.inc` because until now I don't think they were really possible to hit (because there were no non-fNIRS channels in between fNIRS channels in our readers until now).
Closes #11130

ENH: Add list-of-str support to Hitachi

---

.circleci/config.yml
.github/workflows/linux_pip.yml
doc/changes/latest.inc
mne/epochs.py
mne/morph.py
mne/tests/test_docstring_parameters.py
mne/time_frequency/spectrum.py
mne/utils/_logging.py
tools/azure_dependencies.sh
tools/check_qt_import.sh
tools/github_actions_dependencies.sh

While working on MNE-BIDS-Pipeline I kept getting logging messages I didn't expect about split files like (anything not prefixed by a date/time is bad):
```Console
[2022-09-19 23:04:16] preprocessing/_06_ptp_reject sub-01 Using PTP rejection thresholds: {}
Overwriting existing file.
Splitting into 6 parts
Overwriting existing file.
Overwriting existing file.
Overwriting existing file.
Overwriting existing file.
Overwriting existing file.
```
This is because a `verbose=True` snuck into our API in #4827 specifically [here](https://github.com/mne-tools/mne-python/pull/4827/files#diff-a6032a51226f9175d84fb340bab2a4238ddc24bf0c0f979bd1921f9d2f54c9fbR1571) by @larsoner :)
This adds a test that `verbose=None` in all the public API endpoints we currently check in `test_docstring_parameters.py`, …

MAINT: Enforce verbose=True in public API

---

doc/changes/latest.inc
mne/bem.py
mne/chpi.py
mne/cov.py
mne/dipole.py
mne/minimum_norm/inverse.py
mne/report/report.py
mne/utils/__init__.py
mne/utils/_logging.py
mne/utils/check.py
mne/utils/tests/test_check.py

A lot of places in our code, if we're doing something internal we might do:
```
def _check_sphere(...):
out = fit_sphere_to_headshape(..., verbose=False)
```
with the goal of the `verbose=False` being "don't print info messages". However, this has an unintended side effect where this code:
```
with mne.use_log_level('error'):
_check_sphere(...)
```
can still emit warnings even though the log level is ERROR. This PR adds a `_verbose_safe_false` function that returns `False` (which will be used as WARNING) if the current logging level is low enough (debug or info), but returns None ("do not modify") otherwise.
I cleaned up a few use cases for this in our codebase but not all of them. I think we can put more in as we see `verbose='error'` failing to silence warnings in the future.
It's …

MAINT: Clean up use of verbose

---

doc/changes/latest.inc
mne/io/base.py

Fixes #11202
```python
import mne
n_seconds = 1
sfreq = 100
ch_names = ['1']
data = np.ones((len(ch_names), sfreq*n_seconds))
info = mne.create_info(ch_names=ch_names, sfreq=sfreq)
raw = mne.io.RawArray(data, info)
raw
```
`main`:
PR:
I'm don't feel like adding a regression test for this…

MRG: Fix displayed Raw duration in Jupyter notebook

---

doc/changes/latest.inc
mne/io/base.py
mne/io/fiff/tests/test_raw_fiff.py

Closes https://github.com/mne-tools/mne-python/issues/11196

Fix `include_tmax` not considered in `mne.io.Raw.crop` to check `tmax` in bounds

---

doc/conf.py
doc/glossary.rst
mne/time_frequency/multitaper.py
mne/time_frequency/psd.py
mne/time_frequency/spectrum.py
mne/utils/docs.py

A couple of minor formatting fixes, and I removed the entry for `array-like` in favor of the one defined in the `numpy` glossary.
Also looking if I can figure out which CSS variable to override to format `terms` in the same way as `py:obj`.

[DOC, MRG] Minor documentation improvements and remove glossary entry for array-like

---

.circleci/config.yml
azure-pipelines.yml
doc/conf.py
doc/references.bib
mne/conftest.py
mne/forward/_compute_forward.py
mne/forward/_field_interpolation.py
mne/forward/_lead_dots.py
mne/forward/_make_forward.py
mne/io/ctf/constants.py
mne/io/ctf/ctf.py
mne/io/ctf/res4.py
mne/utils/misc.py
mne/viz/backends/tests/test_utils.py
mne/viz/tests/test_raw.py
mne/viz/tests/test_scraper.py
requirements.txt
tools/circleci_dependencies.sh
tools/github_actions_dependencies.sh
tutorials/forward/35_eeg_no_mri.py
tutorials/forward/50_background_freesurfer_mne.py
tutorials/forward/80_fix_bem_in_blender.py
tutorials/intro/70_report.py

MAINT: Fix CircleCI error

---

doc/changes/latest.inc
doc/changes/names.inc
mne/evoked.py
mne/viz/_proj.py
mne/viz/evoked.py
mne/viz/ica.py
mne/viz/tests/test_evoked.py

closes #10612
replaces/supersedes #11017

Fix spatial colors

---

.github/workflows/macos_conda.yml
doc/conf.py
mne/viz/backends/_pyvista.py
mne/viz/backends/renderer.py
tutorials/forward/50_background_freesurfer_mne.py

This should fix the mesh display color bug that has been in `tutorials/forward/50_background_freesurfer_mne.py` since the 1.0 release (last known good was 0.24).  Unfortunately we probably won't be able to tell because that tutorial is bricking Circle in other ways right now:
```
generating gallery for auto_tutorials/forward... [ 75%] 50_background_freesurfer_mne.py
Clean 1636.6 s : 1.73 GB
qt.qpa.xcb: QXcbConnection: XCB error: 128 (Unknown), sequence: 15178, resource id: 2098234, major code: 130 (Unknown), minor code: 2
```
...and I haven't been able to pinpoint the cause of that yet.

Fix mesh display in tutorial

---

mne/datasets/tests/test_datasets.py
mne/datasets/utils.py
mne/utils/config.py
mne/viz/backends/tests/test_abstract.py

There have been a few times `mne.datasets.testing.data_path()` have snuck into our tests without the `download=False` that avoids a download, leading to interpreters that seem hung while a lengthy large download occurs. This PR adds a check via `inspect` that we don't do this, along with a private attribute that other packages like mne-bids can use to enable a similar check.
I'm hoping that these checks will reveal a problem here or in MNE-BIDS, otherwise more investigation is necessary why this download happens.

MAINT: Ensure no datasets are downloaded in tests

---

mne/beamformer/tests/test_lcmv.py
mne/decoding/tests/test_search_light.py
mne/fixes.py
mne/io/what.py
mne/preprocessing/ica.py
mne/tests/test_cov.py
mne/tests/test_morph.py
mne/utils/dataframe.py
mne/utils/misc.py
mne/viz/backends/_pyvista.py
mne/viz/utils.py

closes #11089
@larsoner in all but one case, a simple `signature(f).parameters` (or `list(signature(f).parameters)` was sufficient.  IMO the helper function is not really needed, but if you disagree feel free to close this without merging.

purge _get_args helper func

---

mne/utils/misc.py

Fixes #11218
@larsoner could you take a look please? This seems to resolve my issue.
I believe the logger automatically appends a newline character, so we end up with two subsequent ones at the end of a line if the input string already contains a `\n`  at the end.

Don't insert superfluous newlines in subprocess log messages

---

mne/time_frequency/tests/test_tfr.py
mne/time_frequency/tfr.py

closes #11091
after reading through the TFR code, to me it seems that #10978 introduced a mistake.  Specifically, the changed coef here:
https://github.com/mne-tools/mne-python/blob/71271588e7d7fd3e165ad158571f40085eaa05e0/mne/time_frequency/tfr.py#L2439-L2440
is only appropriate for complex data (which have been converted to real-valued amplitude a few  lines above).  Data that is already real-valued will be power, not amplitude, and so should have coef `10` not `20` in the dB conversion.
My only hesitation is the case of `avg_power_itc` where the data will be complex, but the complex part is ITC, so it seems like the test of `if np.iscomplexobj` is too coarse here:
https://github.com/mne-tools/mne-python/blob/71271588e7d7fd3e165ad158571f40085eaa05e0/mne/time_frequency/tfr.py#L2413-L2414 …

Fix tfr db

---

examples/connectivity/README.txt
mne/cov.py
mne/dipole.py
mne/epochs.py
mne/io/meas_info.py
mne/morph.py
mne/viz/backends/_abstract.py
mne/viz/backends/_pyvista.py

Closes #11226
Fixed by a quick
```
python -m sphinx.ext.intersphinx https://mne.tools/mne-connectivity/stable/objects.inv > mne-connectivity.txt
```
then inspection, plus doc check with `make html_dev-noplot`. So should come back green for the Circle run, but I'll merge manually since the `skip`s won't allow auto-merge to work.
I then tweaked and unified our "don't instantiate directly" lines. @drammock feel free to review and approve if you're happy with the wording and `.. note::` I chose to unify around. If not I'm happy to change them:

MAINT: Fix link and update instantiation note

---

.circleci/config.yml

Missed this one in the refactoring -- CircleCI now uses PyQt6. But I guess PySide6 was also installed by something!

MAINT: Better check

---

mne/utils/misc.py
mne/utils/tests/test_misc.py

@hoechenberger fixes a regression due to #11219. We shouldn't remove the `\n` from the `stdout` *returns*, only remove it when actually `logger.info` and `logger.warning`'ing them.
This should fix https://app.circleci.com/pipelines/github/mne-tools/mne-bids/4710/workflows/a2f8cafe-dd31-49cc-952d-3e46e06b5c14/jobs/6848, marking for merge-when-green

BUG: Fix regression with run_subprocess

---

doc/_templates/layout.html
doc/conf.py
doc/install/installers.rst
doc/install/manual_install_python.rst
requirements_doc.txt

cc @choldgraf
When the CircleCI build is done here, it should demonstrate the "empty right-side TOC" on the MNE homepage and on the first page after that in the TOCtree (`install/index.html`)

testing new features of website theme

---

doc/changes/latest.inc
mne/preprocessing/ica.py
mne/report/report.py
mne/report/tests/test_report.py
mne/utils/check.py
mne/utils/docs.py
mne/viz/ica.py

Over in mne-bids-pipeline I'm trying to squash all warnings, but I get:
mne_bids_pipeline/scripts/preprocessing/_05a_apply_ica.py:122: RuntimeWarning:
The data you passed to ICA.apply() was baseline-corrected. Please note that ICA can introduce
DC shifts, therefore you may wish to consider baseline-correcting the cleaned data again.
This adds a `on_baseline='warn'` that we can set to `on_baseline='reapply'` to avoid this and reapply the baseline after `ica.apply`. Internally `report.add_ica` will always use `on_baseline='reapply'` for `ica.plot_overlay`, but in principle we could expose this as a parameter.
Okay for you @agramfort ?

BUG: Avoid warning in report.add_ica

---

mne/time_frequency/tfr.py

Just adds `verbose` to `read_tfrs`, so not worth `latest.inc` update I think. Inspired by https://github.com/mne-tools/mne-bids-pipeline/pull/628 where I want to suppress a warning about my filename.

ENH: Add verbose to read_tfrs

---

mne/channels/channels.py

Closes #11252
Adds the missing `verbose` command to the `combine_channels` function. 
Changed three lines of code: 
1. Added @verbose before the function call
2. Added verbose=None to the function arguments
3. Added %(verbose)s to the docstring

BUG: add missing `verbose` argument in combine_channels function

---

mne/time_frequency/spectrum.py
mne/time_frequency/tests/test_spectrum.py

reported here https://mne.discourse.group/t/is-this-a-bug-in-the-new-compute-psd-method/5734
The corrected computation was based on what they do in scipy.signal._fft_helper
The new test fails on main and passes here.

Fix welch windows

---

doc/changes/latest.inc
doc/changes/names.inc
mne/viz/topomap.py

N/A.
When debuging a code snippet(will paste it later) with Spyder today, I found that the X coordinate of `ear_left` and `ear_right` may have been exchanged accidentally at …

BUG: Fix X coordinates of ear_left and ear_right in head outlines dict

---

doc/changes/latest.inc
mne/viz/backends/_pyvista.py
mne/viz/backends/_qt.py
mne/viz/backends/tests/test_renderer.py
mne/viz/tests/test_topomap.py

Closes #10991
Fixes a bug with Mesa detection, and now emits a warning if someone is using a version of MESA that is too old to work.

BUG: Correctly detect MESA

---

doc/_templates/autosummary/class.rst
doc/_templates/autosummary/class_no_inherited_members.rst
doc/_templates/autosummary/class_no_members.rst
doc/_templates/autosummary/function.rst
doc/conf.py
doc/file_io.rst
doc/reading_raw_data.rst

For #11173, avoid documenting BaseRaw and BaseEpochs methods. This makes it so that searching `plot_psd` for example no longer shows BaseRaw or BaseEpochs. It's not perfect because the pages still list the names, but I think this is okay -- end-users will ignore these and can easily look at `Raw` or `Epochs` for them.

DOC: Avoid documenting base class methods

---

mne/utils/misc.py
mne/utils/tests/test_misc.py

Over in `mne-bids-pipeline` I want to call `run_subprocess(..., stdout=sys.stdout, stderr=sys.stderr)` because I don't want to capture the output when entering debug mode on failure. This should be fine, but on `main` we get:
1. An error message at the beginning of the `run_subprocess` call
2. An error message at the end of the `run_subprocess` call
3. A `print` of the `(stdout, stderr)` tuple, which we didn't ask for and is also two empty strings anyway
See:
<details>
```
📝 Running the following tests in debug mode: ERP_CORE_ERN
Exception in thread Thread-1 (_enqueue_output):
File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-2 (_enqueue_output):
File …
```

BUG: Fix bugs with passing stdout/stderr to run_subprocess

---

doc/changes/latest.inc
mne/viz/tests/test_topo.py
mne/viz/topo.py

Fixes #11258.
Lines of the first plot are now explicitly passed to plt.legend as handles. 
Includes one test.

Fix misbehaving legend colors in plot_evoked_topo

---

mne/conftest.py
mne/time_frequency/tests/test_spectrum.py

Works around `py` no longer being required by `pytest`, and adds a `xfail` that should be reverted/fixed as part of #11278. In the meantime it'll get things green for other PRs

MAINT: Update for latest pytest

---

mne/time_frequency/tests/test_spectrum.py

closes #11278
I think the relevant upstream issue is https://github.com/pandas-dev/pandas/issues/49223 but to be honest I spent way too long trying to figure out the root cause and just gave up and implemented the expedient workaround of sorting the DFs before comparing them. (all we really need to care about in the test is the correctness of the values, not the order).

fix spectrum dataframe test

---

azure-pipelines.yml
mne/inverse_sparse/mxne_optim.py
mne/time_frequency/tests/test_tfr.py
mne/time_frequency/tfr.py
mne/utils/tests/test_misc.py
requirements.txt

Closes #10985
Closes #10984
Ubuntu 22.10 fixed the QEMU bug that was stopping me from tracking this down. There must be a bug in OpenBLAS 3.19 with `np.convolve`->`multiarray.correlate` for complex arrays, but I haven't followed the chain to see what this wraps to under the hood. In the meantime, this workaround should be fine and have a negligible performance hit.

BUG: Work around ppc64le bugs

---

mne/time_frequency/multitaper.py
mne/time_frequency/psd.py
mne/time_frequency/tfr.py
mne/utils/docs.py

I've been giving a shot at TFR representation for the first time today, and it took me a while to grasp how it works. And it's still a bit of a headache for now 🤯 
With that in mind, I'd like to improve the documentation. I've been starting with multitapers, the goal of this PR is to describe better the relation between `freqs`, `n_cycles`, `time-window size`, and `time_bandwith`.
That said I could really use an advanced course on signal processing one of those days, so please let me know if anything I wrote is wrong! 
---------
**PR Status:** for starters, I'll only update `tfr_array_multitaper`, and once the documentation is consolidated there, I will update `tfr_multitaper`, deduplicate docstrings and update the tutorial. 
Covered:

[DOC] Improve argument documentation for TFR multitaper

---

doc/changes/latest.inc
mne/preprocessing/ica.py
mne/preprocessing/tests/test_ica.py

Closes #11299 
cc @alexrockhill since you authored this function in #10534.

[BUG] Fix channel selection when retrieving positions in ICA.find_bads_muscle

---

doc/changes/latest.inc
mne/time_frequency/psd.py
mne/time_frequency/tests/test_psd.py

[BUG] Fix computation of welch's PSD when the number of jobs exceeds the number of channels

---

doc/changes/latest.inc
mne/filter.py
mne/time_frequency/csd.py
mne/time_frequency/multitaper.py
mne/time_frequency/tests/test_multitaper.py
mne/time_frequency/tfr.py

closes #11292
@larsoner @mmagnuski this goes a bit beyond what you two discussed in #11292, but the changes are well-segregated by commit so it will be easy to revert part of it if needed:
Feel free to review now (just the DPSS changes) and I'll add the morlet / CWT changes in the next couple days (or can bump that to a separate PR if you prefer)

rely more on SciPy for DPSS tapers

---

mne/tests/test_chpi.py

By way of PR, showing that I can't replicate https://mne.discourse.group/t/passing-head-position-to-maxwell-filter/5374/3
I wonder if it's really "just" a problem with the ProgressBar representation, and that by doing `.load_data()` it's faster so they don't cancel it early. But in the meantime this at least helps ensure that it does work with and without preloading data.

MAINT: Add test for preload during cHPI

---

mne/epochs.py
mne/tests/test_epochs.py
mne/utils/docs.py

Seems potentially useful/cleaner even if we also add https://github.com/mne-tools/mne-python/pull/11287

MAINT: Return EpochsArray instead of BaseEpochs for concatenate_epochs

---

doc/changes/latest.inc
mne/report/report.py
mne/report/tests/test_report.py

Iteration was done over `content[::-1]` but the `idx` used came from `enumerate`ing this, which meant it was in the wrong order. What needed to be used was `len(content) - idx - 1`. This code just simplifies things by iterating over all elements (which should be fast enough even for hundreds of them) and taking the last matching index directly.

BUG: Fix bug with report replacement

---

doc/changes/latest.inc
mne/decoding/base.py
mne/decoding/search_light.py
mne/utils/docs.py

Related to #7478, but not quite the same (though I remember this being an issue there, too).
Now with this code:
<details>
<summary>Code</summary>
```
import mne
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import mne
from mne.decoding import GeneralizingEstimator, cross_val_multiscore
raw_fname = data_path / 'MEG/sample/sample_audvis_filt-0-40_raw.fif'
events_fname = data_path / 'MEG/sample/sample_audvis_filt-0-40_raw-eve.fif'
raw = mne.io.read_raw_fif(raw_fname, preload=True)
picks = mne.pick_types(raw.info, meg=True, exclude='bads')  # Pick MEG channels
events = mne.read_events(events_fname)
event_id = {'Auditory/Left': 1, …
```

BUG: Fix bug with parallel progress bars

---

mne/viz/backends/_pyvista.py

I get a RuntimeError with no description for my mesa setup. The key part of the gpu info string is
```
OpenGL vendor string:  Intel
OpenGL renderer string:  Mesa Intel(R) Xe Graphics (TGL GT2)
OpenGL version string:  4.6 (Core Profile) Mesa 22.2.0
```
This appears to be a difference from previous where in the comments it says the CIs say
```
OpenGL renderer string: Mesa 20.0.8 via llvmpipe (LLVM 10.0.0, 256 bits)
```
So this just fixes so that it gets the version from the version string if it's not in the render string.

[MAINT, MRG] fix is_mesa

---

mne/epochs.py
mne/evoked.py
mne/io/base.py
mne/utils/docs.py

Minor documentation fix for the `apply_function` methods, e.g. https://mne.tools/dev/generated/mne.io.Raw.html#mne.io.Raw.apply_function
```
If n_jobs > 1, more memory is required as len(picks) * n_times additional time points need to be temporarily stored in memory.
```
-> n_jobs * n_times and not len(picks).

[DOC, MRG] fix/improve documentation of n_jobs for apply_function

---

doc/_templates/sidebar-quicklinks.html
doc/conf.py
doc/install/contributing.rst
doc/install/index.rst
doc/install/installers.rst

fix fontawesome icon display

---

doc/changes/latest.inc
mne/viz/evoked.py
mne/viz/tests/test_epochs.py

fix epochs.plot_image for EMG data

---

doc/changes/latest.inc
mne/conftest.py
mne/time_frequency/tests/test_tfr.py
mne/time_frequency/tfr.py
mne/viz/utils.py
tools/azure_dependencies.sh
tools/github_actions_dependencies.sh

I added support for passing a `callable` to control how the channels are combined when plotting a TFR.
For now, it only supported `'mean'` and `'rms'`. I could use this feature as I'd like to do a weighted average instead.

MRG: Add support for a callable in the combine argument of TFR plots

---

mne/time_frequency/psd.py
mne/viz/tests/test_raw.py

Improvement to make sure the arguments `n_fft`, `n_overlap` and `n_per_seg` are integers in Welch's method, to avoid this crpytic traceback when a float is provided (which is common if you do `duration * raw.info["sfreq"]` and forget to convert to int):
```
Effective window size : 4.000 (s)
File "/Users/rellis/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
pydev_imports.execfile(file, globals, locals)  # execute the script
File "/Users/rellis/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File …
```

Ensure n_fft, n_overlap and n_per_seg are integers

---

doc/changes/latest.inc
mne/time_frequency/spectrum.py

closes #11343 
there was already code in there to use the old default `n_fft` in hopes of avoiding this bug, but that code wasn't getting triggered in some cases because it looked for `method=='welch'` and was receiving `method=='auto'`.  Now we convert "auto" to a proper method name right away.

fix default n_fft for spectrum plots

---

mne/gui/__init__.py

While preparing teaching, I found that the video link in the coregistration docstring seems to be broken (on stable and dev). I replaced the link with a matching video I found on the MNE-Python Youtube channel.
Seems to fit the link that was mentioned before merging here: https://github.com/mne-tools/mne-python/pull/10802#issuecomment-1164772429
Someone please double check it is the intended one? @drammock @larsoner @alexrockhill

[DOC] Fix video link for coregistration

---

doc/changes/latest.inc
mne/report/report.py
mne/report/tests/test_report.py
tutorials/intro/70_report.py

Saves ~50% in mne-bids-pipeline
```
$ python -c "import mne; print(mne.report.open_report('~/mne_data/derivatives/mne-bids-pipeline/ds000248_base/sub-01/meg/sub-01_task-audiovisual_report.h5'))"
<Report | 28 titles | 78 items | sub-01, task-audiovisual  | 31.2 MB
Raw (original run 01), run 01                             |  1.0 MB
Data quality                                              |  0.2 MB
Raw (maxwell filtered), run 01                            |  0.9 MB
Raw (filtered), run 01                                    |  0.8 MB
Events                                                    |  0.0 MB
Epochs: before cleaning                                   |  0.5 MB
Epochs: after cleaning                                    |  0.5 MB
Condition: Auditory                                       | …
```

ENH: Add webp support to Report

---

doc/install/contributing.rst

Adding information about how and when to clean up your doc building folders using `make clean`, as discussed with @drammock.

[DOC] Adding make clean to contributing guide

---

doc/references.bib
mne/beamformer/_compute_beamformer.py
tutorials/inverse/50_beamformer_lcmv.py

Adapting the LCMV tutorial for the new-ish default of `weight_norm='unit-noise-gain-invariant'`. Happy to discuss the change in the reconstructed activity for the vector beamformer - it seems to now be more in line with what we get from the scalar beamformer, and the third orientation seems to be floating around 0.
We could probably do with a different color limit, but wanted to keep it as is for comparison first.
Also added a few references to the beamformer overview paper I published earlier this year - I think it could be a helpful resource if I may say so myself.
Otherwise, some minor fixes in the tutorial and docstring text.

[DRAFT][DOC] Adapt LCMV tutorial

---

doc/install/mne_tools_suite.rst

In your list of MNE-friendly packages I replaced my former package ESINet with my updated package "invertmeeg" which implements various EEG inverse solutions. ESINet is replaced since all features are now available in the new package as well.
The package utilizes many mne-python objects like Evoked, Raw, Epochs, Forward, SourceEstimate etc., wherefore I think my package may be of interest to the community.
Keep up the good work!
-Lukas
all user contributions, no matter how minor they …

Replaced package mention ESINet by invertmeeg

---

azure-pipelines.yml
doc/changes/latest.inc
doc/changes/names.inc
doc/install/contributing.rst
doc/links.inc
doc/overview/roadmap.rst
environment.yml
mne/io/snirf/_snirf.py
mne/io/snirf/tests/test_snirf.py

Before this PR, when reading SNIRF files, the annotation durations were ALL set to 1.0
This PR changes the `read_raw_snirf` function to read annotation durations from the file. 
Relevant file type definition is here: https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#nirsistimjdata
A PR has been opened to add correct stimulus duration to SNIRF writing at https://github.com/mne-tools/mne-nirs/pull/497

[ENH] Read annotation duration from SNIRF files.

---

doc/changes/latest.inc
mne/annotations.py
mne/cov.py
mne/forward/forward.py
mne/io/meas_info.py
mne/io/proc_history.py
mne/io/proj.py
mne/io/write.py
mne/tests/test_evoked.py

Closes #11392
*EDIT: Adapts solution from #7288 to all `NAME_LIST`s*

MAINT: Sanitize name lists

---

doc/changes/latest.inc
mne/io/meas_info.py

Adds a save method to the info class in addition to `mne.io.write_info` for convenience.

[ENH, MRG] Add info save method

---

doc/changes/latest.inc
mne/filter.py
mne/io/base.py
mne/tests/test_annotations.py
mne/utils/docs.py

Partial fix for #10447 
This adds a `skip_by_annotation` for notch filtering

[MRG] ENH: add skip_by_annotation to notch_filter

---

doc/changes/latest.inc
mne/_freesurfer.py
mne/tests/test_freesurfer.py

Here is one example lta file, notice that the source and destination files are both a CT that is 512 385 512:
```
type      = 0 # LINEAR_VOX_TO_VOX
nxforms   = 1
mean      = 0.0000 0.0000 0.0000
sigma     = 1.0000
1 4 4
9.966146945953369e-01 -7.456155866384506e-02 3.480117395520210e-02 -2.464399566650391e+02 
6.968625634908676e-02 9.901284575462341e-01 1.214500889182091e-01 1.951967315673828e+02 
-4.351313412189484e-02 -1.188529580831528e-01 9.919724464416504e-01 3.338456115722656e+02 
0.000000000000000e+00 0.000000000000000e+00 0.000000000000000e+00 1.000000000000000e+00 
src volume info
valid = 1  # volume info valid
filename = CT_High_Def_20221108082419_104.nii.gz
volume = 512 385 512
voxelsize = 4.149999916553497e-01 4.154182076454163e-01 4.149999916553497e-01
xras   = …
```

[BUG, MRG] Fix mne.read_lta for different source and destination volumes

---

mne/channels/channels.py
mne/channels/interpolation.py

A couple of minor style fixes while I was looking at the interpolation code.
Before:
After:
If you don't think this is an improvement, feel free to close the PR 😉

[Doc] Minor doc fixes for interpolate_bads

---

mne/conftest.py
mne/viz/_3d.py
mne/viz/_brain/_brain.py
mne/viz/_mpl_figure.py
mne/viz/backends/tests/test_utils.py
mne/viz/tests/test_epochs.py
mne/viz/tests/test_raw.py
mne/viz/tests/test_topomap.py
mne/viz/utils.py
tools/azure_dependencies.sh
tools/github_actions_dependencies.sh

I decided to upgrade to latest `matplotlib` dev today and hit a bunch of failures (in addition to #11332). This PR aims to restore our `--pre` testing of matplotlib, decorating with `xfail` if needed (e.g., for button-related tests). This seems better than sticking with `<3.7`, which will continue to allow us to accumulate more incompatibilities in addition to the button one.
Also fixes (hopefully) the theme testing, which was broken for me on Ubuntu 22.10 on a dark theme.
Mostly complementary with #11409, which hopefully will be an easy rebase/merge after this PR is in and can remove some `xfail`s.

MAINT: Matplotlib 3.7 compat

---

mne/chpi.py
mne/preprocessing/maxwell.py
mne/utils/docs.py

A couple of typos/formatting while I was looking at MNE's version of Maxwell filters.

Fix typo in Maxwell filter documentation

---

doc/changes/latest.inc
mne/io/edf/edf.py

addresses https://mne.discourse.group/t/mass-dataset-mne-function-read-half-file-when-infer-types-true/6193
it was a nasty one...

FIX reading of EDF data with different sampling rates of a mix of data channels when using infer_types=True

---

doc/changes/latest.inc
mne/epochs.py
mne/viz/epochs.py

When plotting epochs, we currently get a window titlte that is exactly the same as the comment we'd put into the evoked produced by averaging the displayed epochs.
This is actually misleading – nothing has been averaged yet, so, strictly speaking, the formula doesn't make sense; and it's quite noisy when many different event types are involved.
I have two different proposals, both of which involve removal of the plus signs:
a) we could remove the fractional numbers like this:
I like how clean that is.
b) instead of having fractions, we could display the absolute numbers of epochs for each event type. However, this again is very verbose for many conditions – but it makes it very nice and easy to sanity-check whether you're looking at the correct subset of epochs while viewing them.
In this …

MRG: In epochs plot window title, don't use "evoked-style" fractional-sum notation

---

doc/changes/latest.inc
mne/datasets/config.py
mne/preprocessing/ieeg/_projection.py
mne/preprocessing/ieeg/tests/test_projection.py

Followup on previous issue setting the `info.chs` locations directly in the `ieeg_locate` GUI but for sensor projections in ECoG.

[MAINT/BUG, MRG] Use make_dig_montage for ECoG projection

---

mne/viz/_brain/_brain.py
requirements.txt
tutorials/evoked/20_visualize_evoked.py

Hopefully works around:
```
/home/circleci/project/mne/viz/_brain/_brain.py:docstring of mne.viz._brain._brain.Brain:134: WARNING: py:meth reference target not found: pyvista.Plotter.add_scalar_bar
```
and a AttributeError related to `plotter.image` from PyVista 0.38 release.
I'm opening PRs/bug reports to PyVista. Once those are fixed, we can link back to `add_scalar_bar` properly

MAINT: Work around PyVista bug

---

doc/changes/latest.inc
doc/changes/names.inc
mne/datasets/eegbci/eegbci.py
mne/utils/misc.py
requirements_base.txt

Fixes #11448.
`mne` currently relies on `pkg_resources`, which is a part of `setuptools`, without declaring it as a dependency. This can cause issues in environments where `setuptools` is not present by default (see #11448 for an example). 
This PR updates `mne` to use `importlib.resources` for Python >= 3.9 or its backport `importlib_resources` for Python < 3.9 as recommended [here](https://setuptools.pypa.io/en/latest/pkg_resources.html). `importlib` is part of the standard library.
The only `importlib` function this PR uses is `importlib.resources.files()`, which was added in Python 3.9. I added a dependency to `importlib_resources` in `requirements_base.txt` for Python versions < 3.9. Please advise if this is ok. If not I will update the PR accordingly, but it would mean that `mne` …

Fix: Use `importlib.resources` or `importlib_resources` instead of `pkg_resources`

---

doc/changes/latest.inc
doc/changes/names.inc
mne/decoding/ssd.py
mne/decoding/tests/test_ssd.py

**Spatio-spectral decomposition (SSD) implemented in `mne.decoding.SSD` can fail to fit data that is not full rank**, even when specifying an appropriate number of components to reduce the dimensionality of the data to using the `rank` argument. This is due to the dimensionality reduction performed when computing covariance producing matrices which are not positive definite, causing the subsequent eigenvalue decomposition to fail with a `LinAlgError`:
<br />
**This change adds a new private function for performing the dimensionality reduction** after the covariance matrices have been computed (`mne.decoding.ssd._dimensionality_reduction()`; called by the `fit()` method of `mne.decoding.SSD`), **which allows `SSD` to fit both full and non-full rank data**. The `rank` argument of `SSD` …

[ENH] Adjusted SSD algorithm to support non-full rank data

---

doc/conf.py
mne/conftest.py
mne/viz/_brain/tests/test_brain.py

Let's see if it works
Closes #11476

MAINT: Deal with pkg_resources usage bugs

---

mne/channels/montage.py

Closes #8830
Improves the unclear error message raised by:
```
from mne import create_info
info = create_info(["Fpz", "EEG2", "EEG1"], 1000, "eeg")
info.set_montage("standard_1020")
```
The main change is `channel missing from the montage [...] Consider using inst.rename_channels to match the montage nomenclature`.

[MRG] Improve error message raised on channels missing from DigMontage

---

doc/changes/latest.inc
doc/changes/names.inc
mne/channels/montage.py
mne/channels/tests/test_montage.py
mne/utils/docs.py
mne/viz/montage.py
mne/viz/utils.py

This PR enables:
```
montage = ...  # DigMontage
f, ax = plt.subplots(1, 1)
montage.plot(axes=ax)
```
I noticed it was missing when I tried to plot 3 montages on the same figure. One more step towards a unified plotting API :smiley: 
Closes #11404

[MRG] Forward argument axes from plot_sensors to DigMontage.plot

---

doc/changes/names.inc
mne/decoding/ssd.py

Implementation of comments/suggestions in merged PR #11458.
- Fixed incorrect default values in the docstring.
- Reworded the docstring to better reflect the behaviour of the class.
- Changed the naming of internal variables for consistency and clarity.
- Changed a logging message to more accurately reflect the behaviour of the code.
Cheers, Thomas!

[DOC] Updated decoding.SSD documentation and internal variable naming

---

doc/changes/latest.inc
mne/gui/_core.py

Fixes https://github.com/mne-tools/mne-python/issues/11484

[BUG, MRG] Fix pial surface loading, logging in locate_ieeg

---

mne/viz/_mpl_figure.py

Fixes #11487.
A little heads up: Matplotlib 3.7 is out, and it breaks our raw plot in several places (meaning that the annotations window cannot even be opened). This is for another PR though.

Accept only left-clicks for adding annotations

---

tutorials/simulation/10_array_objs.py

A simple example of how to put custom power spectral data into an average Spectrum class.
A proper SpectrumArray class could follow if there is interest.
Discussed with @drammock  @hoechenberger in past 2 office hours.

[MRG] ENH/DOC: demo custom spectrum creation

---

examples/simulation/simulate_evoked_data.py

Typo fix and added colons before code

---

tutorials/inverse/80_brainstorm_phantom_elekta.py

A minor typo in a tutorial: 60s -> 30s.

Fix typo in tutorial

---

doc/changes/latest.inc
doc/changes/names.inc
mne/time_frequency/multitaper.py

Fixes #11324
Several folks noticed that the default bandwidth in `time_frequency.psd_multitaper()` was not documented correctly, and that the bandwidth was incorrectly documented as a half-bandwidth. The documentation has been updated to specify that it is the full frequency bandwidth, and the documentation of how the default bandwidth is 'computed'. The old version saying that the default bandwidth was 4 Hz was incorrect, as the 4 was the normalized time-half-bandwidth product.
Also updated the `ValueError` in `_compute_mt_params` when computing `half_nbw` to specify which is full bandwidth and which is half-bandwidth.

Updating documentation to clarify full vs half-bandwidth and defaults in time_frequency.multitaper.py

---

.github/workflows/compat_minimal.yml
.github/workflows/compat_old.yml
.github/workflows/linux_conda.yml
.github/workflows/macos_conda.yml
environment.yml
tools/github_actions_dependencies.sh

~~One way to move toward being able to recommend mamba is by including it in `environment.yml`, so I added it here.~~ I made our solvers use `mamba` by including it in the `setup-miniconda` action [according to the instructions here](https://github.com/marketplace/actions/setup-miniconda#example-6-mamba). Note that they even say it's experimental, and I'm assuming that's because `mamba` is moreso than the action itself:
> Example 6: Mamba
> Experimental! Use mamba to handle conda installs in a faster way. mamba-version accepts a version string x.y (including "*"). It requires you specify conda-forge as part of the channels, ideally with the highest priority.
FWIW @drammock Azure was already using `mamba env update` on Windows, IIRC to speed up the solve time.

MAINT: Use mamba in CIs

---

doc/conf.py

Let's get the full build working while we wait for https://github.com/mne-tools/mne-python/pull/11409

MAINT: Fix Circle

---

doc/changes/latest.inc
doc/conf.py
mne/conftest.py
mne/viz/_mpl_figure.py
mne/viz/tests/test_epochs.py
mne/viz/tests/test_raw.py
mne/viz/tests/test_topomap.py
mne/viz/topomap.py
mne/viz/utils.py
requirements.txt
tutorials/clinical/30_ecog.py
tutorials/evoked/20_visualize_evoked.py
tutorials/inverse/20_dipole_fit.py
tutorials/preprocessing/50_artifact_correction_ssp.py

closes #11332 
So far this is just proof of concept that the new MPL RadioButtons API can do what we need it to do.  Tested against [this commit](https://github.com/matplotlib/matplotlib/pull/24838/commits/2c895fb01600cdef5afb35bb8f62256ac2621234) in [this open MPL PR](https://github.com/matplotlib/matplotlib/pull/24838). The radio buttons look OK:
...but our current min version of MPL is 3.1 and MPL 3.7 isn't even out yet (probably end of January according to @tacaswell). So we should talk about how we want to handle this; presumably some combination/sequence of 
- pin MPL<3.7 once it's released (in user-facing files, not just in the CI pre jobs)
- finish implementing this PR (and related changes to CheckButtons)
- remove the warning filter and CI version pin from:
- …

BUG: updates for MPL 3.7 compatibility

---

mne/datasets/config.py
mne/export/_eeglab.py

Fixes #11434.
The code verifies is annotations exists (not type None) before attempting to fetch the length of the annotations' object.
Missing annotations is probably caused by mne.concatenate_epochs(). Fixing the function will avoid having None type annotations. However I am not sure that's the only case, as such this fix may help in more than a situation.

fixed annotations error on export

---

mne/io/egi/events.py

Some EGI events can be outside (before or after) the EEG recording. E.g. for video-synchronization markers or "IEND" codes. In this case, the code  breaks with an "index out of bounds" error. Examples are shown in the forum: https://mne.discourse.group/t/index-error-when-trying-to-read-data/2823 https://mne.discourse.group/t/index-error-while-reading-data/5535 I had a similar issue with an EEG with video segments terminating later then the EEG recording.
The edits here should make sure to skip events that are placed illegally, i.e. below 0 (see forum example) or after the EEG end (other forum example+my case). This edit fixed the problem for me and should not harm the usual function. However, out-of-bounds events will be skipped/lost. As alternative, the length of the events array could …

EGI/MFF events outside EEG recording should not break the code

---

doc/changes/latest.inc
mne/channels/layout.py
mne/channels/tests/test_layout.py

Closes #11483
As discussed in #11483, those 2 arguments don't play well and could be replaced by a common explicit `fname` argument.

Deprecate 'kind' and 'path' in favor of 'fname' in the layout reader

---

examples/visualization/3d_to_2d.py

Just a tiny commit following https://github.com/mne-tools/mne-python/pull/11500 to avoid using the deprecated arguments. Should fix the [CircleCI main failure](https://app.circleci.com/pipelines/github/mne-tools/mne-python/18112/workflows/37b4fa1d-378d-458e-9153-401211685e91/jobs/52763).

BUG: Fix deprecated API usage in example

---

.github/workflows/linux_conda.yml
doc/install/advanced.rst
environment.yml

Based on a diff of what `conda` installs between when [it worked](https://github.com/mne-tools/mne-python/actions/runs/4270263385/jobs/7433949955) and [didn't](https://github.com/mne-tools/mne-python/actions/runs/4306180548/jobs/7509648948), it's most likely either ipython 8.11 or jupyter_console 6.6.2 that broke our `notebook` run. This avoids `8.11` for now, let's see if it comes back green. If it does, I'll merge to get `main` green again, then try to figure out how to fix it properly.

MAINT: Avoid bad version for nb tests

---

doc/conf.py
mne/conftest.py

This should fix CIs that hit a deprecation warning related to `pkg_resources` (follow-up to #11478).

Ignore pkg_resources deprecations

---

doc/changes/latest.inc
mne/datasets/utils.py

Expand user in config paths

---

doc/changes/latest.inc
mne/io/_read_raw.py
mne/io/tests/test_read_raw.py

Improve read_raw file extension detection

---

.github/workflows/compat_minimal.yml
.github/workflows/compat_old.yml
README.rst
doc/install/contributing.rst
doc/install/manual_install_python.rst
mne/preprocessing/ica.py
requirements.txt
requirements_base.txt
setup.py

Most related packages (e.g. SciPy, Scikit-Learn) require Python 3.8, and given that 3.7 is EOL very soon, we should also bump to 3.8.
To Do:

Bump minimum Python to 3.8

---

.github/workflows/compat_old.yml
README.rst
doc/conf.py
mne/decoding/tests/test_base.py
mne/fixes.py
mne/surface.py
mne/tests/test_annotations.py
mne/tests/test_surface.py
mne/utils/check.py
mne/utils/numerics.py
mne/utils/tests/test_linalg.py
mne/utils/tests/test_numerics.py
mne/viz/_brain/_scraper.py
mne/viz/_mpl_figure.py
mne/viz/tests/test_topomap.py
requirements_doc.txt

Bumps min reqs in README.rst to those ~2 years old this April, and adjusts/removes code shims for deps lower than those. Also `nibabel` is now required for `read_surface` which I think is reasonable (it is pure Python and has been stable and pip/conda-installable for years now).
Closes #10977

MAINT: Bump minimums

---

.github/workflows/compat_minimal.yml
doc/conf.py
tutorials/preprocessing/25_background_filtering.py

Just a way to get CIs green until we decide on #11564. Marking for merge when green so that other PRs are unblocked

MAINT: Temporary regression workaround

---

azure-pipelines.yml
mne/commands/mne_sys_info.py
mne/utils/config.py
requirements_base.txt

Fixes #11543, supersedes #11544.

Slightly rework `mne.sys_info()`

---

doc/changes/latest.inc
mne/export/_edf.py
mne/export/tests/test_export.py

Today, I had a researcher from our sleep lab that came-in  with a ~8 hours long night recording that could not be converted to EDF either through the BrainVision software or through MNE. The converted signals were all "flat" (or mostly flat), and this was due to 10' in the recording (around hour 7 ) where the signal went completely off-scale, for whatever reason.
The physical range is estimated here https://github.com/mne-tools/mne-python/blob/6384a8901182272c48f3e72a10142ea75184f47f/mne/export/_edf.py#L122-L131
On a good file, I get: `pmin = ~ -130k` and `pmax= ~ 80k`. The range is in the `~ 250k` scale. On the bad file, the range was in the `~ 10M` or `100M` range, several order of magnitude larger. Thus, the conversion failed.
By setting the `physical_range` to `(-150000, 80000)` in …

Fix export to EDF format with a set physical range smaller than the data range

---

azure-pipelines.yml
mne/utils/__init__.py
mne/utils/_testing.py
mne/utils/config.py
mne/utils/tests/test_config.py

Fixes #11576. I'm replacing `-` with `_` at in the import call, and for a better look I think we should use `-` in the output. I've also removed the colons after the package names (which @hoechenberger suggested previously but we forgot) and fixed the alignment.

Fix bug in new `mne.sys_info()`

---

doc/conf.py

Fixes [pycodestyle error](https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes) F601:
```
dictionary key name repeated with different values
```
`Forward` keys added by:
* 6d84371 / #5840 / 2019-01-29
`SourceMorph` keys added by:
* 6d84371 / #5840 / 2019-01-29
* b65a045 / #6046 / 2019-09-15

DOC, MAINT: Fix pycodestyle issue F601

---

mne/beamformer/_compute_beamformer.py
mne/gui/tests/test_gui_api.py
mne/io/curry/tests/test_curry.py
mne/label.py
mne/morph.py
mne/report/report.py
mne/simulation/tests/test_evoked.py
mne/simulation/tests/test_raw.py
mne/simulation/tests/test_source.py
mne/source_space.py
mne/stats/tests/test_cluster_level.py
mne/stats/tests/test_permutations.py
mne/tests/test_coreg.py
mne/tests/test_epochs.py
mne/tests/test_label.py
mne/tests/test_source_space.py
mne/utils/check.py
mne/utils/tests/test_check.py
mne/viz/tests/test_topomap.py

1. Restore `has_nibabel` with deprecation so that `mne-bids` users don't have `import mne_bids` fail once we cut a release (https://github.com/mne-tools/mne-bids/pull/1128) -- not worried about `requires_*` that we removed since those are purely testing mechanisms
2. Use `git grep "check_version(['\"].*['\"],.*"` to find occurrences of `check_version(<name>, <ver>)` that are automatically satisfied by our min numpy/scipy/matplotlib.

MAINT: Remove unnecessary checks

---

environment.yml
requirements.txt

Every release in the pyvista 0.38 series is failing, so let's just pin to <0.38 until it's sorted out.

pin pyvista to fix circle

---

mne/io/artemis123/artemis123.py
mne/io/base.py
mne/io/boxy/boxy.py
mne/io/brainvision/brainvision.py
mne/io/bti/bti.py
mne/io/cnt/cnt.py
mne/io/ctf/ctf.py
mne/io/curry/curry.py
mne/io/eeglab/eeglab.py
mne/io/egi/egi.py
mne/io/egi/egimff.py
mne/io/eximia/eximia.py
mne/io/fil/fil.py
mne/io/hitachi/hitachi.py
mne/io/kit/kit.py
mne/io/nedf/nedf.py
mne/io/nicolet/nicolet.py
mne/io/nihon/nihon.py
mne/io/nirx/nirx.py
mne/io/persyst/persyst.py
mne/io/snirf/_snirf.py

Vaguely related to #11588.
Change
> Documentation of attribute and methods.
into
> Documentation of attribute**s** and methods.
Matches an existing `attributes` here:
https://github.com/mne-tools/mne-python/blob/7d389814213b1f2c9e67c5af4049ee1b07654744/mne/io/edf/edf.py#L94

DOC: attribute → attributes

---

environment.yml
requirements.txt

Now that the scraping bug is fixed in PyVista, we know the set of versions to avoid (0.38.0->0.38.5). If their next release is 0.39.0 we can change this to just `!=0.38` but for now this should work

MAINT: Avoid specific PyVista versions

---

examples/preprocessing/contralateral_referencing.py

this adds a new example, based on this forum post:
https://mne.discourse.group/t/referencing-to-contralateral-mastoids/6587/6

add contralateral referencing example

---

mne/datasets/brainstorm/bst_phantom_elekta.py
mne/datasets/hf_sef/hf_sef.py
mne/decoding/transformer.py
mne/dipole.py
mne/io/meas_info.py
mne/io/open.py
mne/io/proc_history.py
mne/io/tests/test_meas_info.py
mne/morph.py
mne/preprocessing/artifact_detection.py
mne/preprocessing/ica.py
mne/preprocessing/maxwell.py
mne/simulation/raw.py
mne/tests/test_chpi.py
mne/viz/_brain/colormap.py
mne/viz/misc.py
tutorials/stats-sensor-space/10_background_stats.py

None.
In Python 3, string literals are `str` and support Unicode by default. No need to prefix with `u` to change them into `unicode` as in Python 2.

MAINT: In Python 3, do not prefix literals with `u`

---

doc/changes/latest.inc
mne/transforms.py

[BUG, MRG] Don't modify info in place for transform points

---

doc/changes/latest.inc
doc/changes/names.inc
mne/annotations.py
mne/time_frequency/spectrum.py
mne/utils/docs.py
mne/viz/_brain/tests/test_brain.py
mne/viz/backends/_utils.py

From `py-spy` profiling based on https://github.com/mne-tools/mne-qt-browser/issues/161#issuecomment-1490649689 , i.e., Raw with thousands of annotations, I've found a couple of things so far:
1. `Annotations.__iter__` can be slow due to `_any_ch_names()`. The fix is to check this once and pass it to `__getitem__`.
2. Actually `setApplicationIcon` was taking tens of seconds for `pytest mne/viz` (!), so check to see if we actually need to set it based on the `cacheKey()` property.
Draft for now just so I can see if I've broken anything so far. I plan to add other stuff as I find it.

ENH: Speed up code a bit

---

azure-pipelines.yml
mne/viz/backends/_utils.py
requirements.txt
requirements_testing.txt
tools/azure_dependencies.sh
tools/circleci_dependencies.sh
tools/github_actions_dependencies.sh
tools/setup_xvfb.sh

I'm moving mne-qt-browser to setuptools_scm-based versioning so we need to use `git+` to install it now. Might as well future-proof the other repos we currently `zipball` while we're at it

MAINT: Use git rather than zipball

---

mne/utils/__init__.py

From https://github.com/mne-tools/mne-installers/actions/runs/4658808262/jobs/8245584263?pr=184 we can see that the backward compat shim was missing the import in `mne/utils/__init__.py`

API: One cycle of backward compat

---

.github/workflows/circle_artifacts.yml

CircleCI is getting pickier about API endpoints. Procedure:
1. Add new token with admin permission to https://app.circleci.com/settings/project/github/mne-tools/mne-python/api
2. Add the string as a CIRCLECI_TOKEN repo secret in https://github.com/mne-tools/mne-python/settings/secrets/actions
3. Open this PR
4. Merge and hope a rerun of a circle job (like in #11619) shows status again

MAINT: Add token [ci skip]

---

mne/time_frequency/tests/test_spectrum.py

removes the warning filter added in #11616 and avoids generating the warning instead.
closes #11624

make test compatible with future pandas

---

doc/changes/latest.inc
examples/preprocessing/contralateral_referencing.py
mne/channels/channels.py
mne/channels/tests/test_channels.py

Previously, only indices would be returned. But users may commonly be interested in the channel names. This new parameter makes things easier while retaining backward compatibility.
Fixes #11597

MRG: Allow retrieval of channel names via make_1020_channel_selections()

---

mne/conftest.py
mne/datasets/eegbci/eegbci.py
mne/datasets/eegbci/tests/test_eegbci.py
mne/datasets/sleep_physionet/tests/test_physionet.py
tutorials/preprocessing/40_artifact_correction_ica.py

Should fix https://github.com/mne-tools/mne-python/pull/11635#issuecomment-1514865685
Will add a test shortly

BUG: Fix bug with paths

---

.circleci/config.yml
.github/workflows/circle_artifacts.yml
azure-pipelines.yml
doc/Makefile
doc/conf.py
doc/install/contributing.rst
doc/sphinxext/gen_commands.py
environment.yml
requirements_testing_extra.txt
tools/circleci_download.sh
tools/github_actions_dependencies.sh

I realized `build_dev_html` was a relic of when we used to inject/modify our build based on being dev or stable. Removing this we can simplify our `Makefile` to avoid `make html_dev-noplot` --  we can just do `make html-noplot` as the result is the same. So I've simplified a bunch of stuff and tried to keep aliases for the old commands. I also updated to a newer sphinx iterator to avoid a Sphinx 6 warning.
Note that the CircleCI artifacts redirector won't point to a valid file on this PR but it should once the PR is merged, as the redirector action only runs the `main` version of the action.
Helps a little bit with #11507

MAINT: Simplify doc/conf.py

---

.circleci/config.yml
doc/_static/style.css
tutorials/preprocessing/10_preprocessing_overview.py

Closes #11571
@drammock I think I lean toward this being a pydata-sphinx-theme issue, if you agree I can open a near-dup of #11571 over there (or feel free to do it)

DOC: Fix table formatting

---

doc/changes/latest.inc
mne/channels/channels.py
mne/channels/tests/test_channels.py
mne/channels/tests/test_interpolation.py
mne/export/tests/test_export.py
mne/preprocessing/tests/test_ecg.py
mne/tests/test_epochs.py
mne/viz/tests/test_topo.py

In MNE-BIDS we commonly change the units during an ordinary reading operation. This is expected behavior and should not yield a warning.
However, trying to **catch and filter** the warning that MNE emits is quite cumbersome, esp. inside the MNE-BIDS test suite.
I, therefore, believe the best approach is to allow the silencing of the warnings in MNE-Python directly.
This PR adds a new parameter, `on_unit_change`, to the `.set_channel_types()` methods. The default is to warn, but users can now also choose to `'ignore'` this.
x-ref https://github.com/mne-tools/mne-bids/issues/1100
cc @sappelhoff

MRG: Allow silencing of "The unit for channel(s) ... has changed" warnings

---

mne/decoding/base.py
mne/decoding/tests/test_base.py
mne/io/array/tests/test_array.py
mne/report/tests/test_report.py
mne/time_frequency/spectrum.py
mne/utils/docs.py
mne/utils/spectrum.py
mne/viz/tests/test_epochs.py
mne/viz/tests/test_raw.py

Warns users of impending change to Spectrum.plot defaults:
- picks `good_data_noref` -> `all_data_noref`
- exclude `"bads"` -> `()`
motivation is that spectrum plots are frequently used as QC and it's a useful default to have the bad channels show up.

Spectrum plot picks

---

doc/changes/latest.inc
mne/time_frequency/tfr.py

As reported on the forum [here](https://mne.discourse.group/t/i-think-that-is-a-bug/6853).
To reproduce:
```
import mne
from mne.time_frequency import tfr_morlet
raw_fname = sample.data_path() / "MEG" / "sample" / "sample_audvis_raw.fif"
raw = mne.io.read_raw_fif(raw_fname, preload=False)
raw.crop(120, 200).load_data().resample(200)
events = mne.find_events(raw, stim_channel="STI 014")
picks = mne.pick_types(raw.info, meg="grad", eeg=True, eog=True, stim=False)
event_id, tmin, tmax = 1, -1.0, 3.0
epochs = mne.Epochs(
raw,
events,
event_id,
tmin,
tmax,
picks=picks,
baseline=(None, 0),
reject=dict(grad=4000e-13, eog=350e-6),
preload=True,
)
freqs = np.logspace(*np.log10([6, 35]), num=8)
n_cycles = freqs / 2.0 …
```

Fix call to plot_tfr_topomap from interactive AverageTFR.plot_topo function

---

doc/changes/0.19.inc
doc/changes/latest.inc
doc/changes/names.inc
doc/conf.py
doc/inverse.rst
doc/references.bib
examples/inverse/trap_music.py
mne/beamformer/__init__.py
mne/beamformer/_rap_music.py
mne/beamformer/tests/test_rap_music.py

Example: Fixes #7679 .
It implements TRAP-MUSIC, which is a very simple variant of RAP-MUSIC.
Basically at each step the signal space is reduced by one dimension instead of being kept of constant diemnsion.
I also noticed some unused parameters and functions which I removed.
On a simple example I tested the approach, it did not make a lot of difference. But technically, this is more sound than the original RAP. Yet, I kept the default to RAP instead of TRAP to avoid changing a behaviour.
The changes were tested outside of mne (but calling mne routines for everything outside the _rap_music_implementation.py file. I also did not test the new test in test_rap_music.py, but the change is very trivial. I leave it to any checker to catch eventual copy-paste errors, I may have made when I …

Trap music

---

doc/changes/latest.inc
mne/forward/forward.py
mne/forward/tests/test_forward.py
mne/proj.py

Closes #11689
@dasdiptyajit the `fwd['src'][0]['pinfo']` was not adjusted so internally the call to `convert_forward_solution` with `use_cps=True` (the default) broke stuff.

BUG: Fix bug with fwd restriction

---

mne/viz/topomap.py
mne/viz/utils.py

So.. I broke the update of the canvas in #11696, my bad :sweat_smile: The title are not changing color anymore when you select/deselect a component, except for the last figure. When I changed the structure of `plot_ica_components` to remove the recursion and call only once `plt.show()` after gathering the figures, it overwrote the variable `fig` used in the callback.
Should also be backported as #11696 was?

Fix canvas.draw() in callback

---

doc/changes/latest.inc
doc/changes/names.inc

Small update to change log, after PR #11575 was merged.

Updating change log after PR #11575

---

doc/install/installers.rst

Reported on the forum here: https://mne.discourse.group/t/unable-to-download-the-linux-version-of-mne/6978
I updated the links to [v1.4.0-post1](https://github.com/mne-tools/mne-installers/releases/tag/v1.4.0-post1), do you prefer [v1.4.0](https://github.com/mne-tools/mne-installers/releases/tag/v1.4.0)?
I'm away for the weekend, feel free to push to this PR and merge it.

Fix installer links

---

doc/changes/latest.inc
mne/baseline.py
mne/tests/test_epochs.py
mne/utils/check.py

Since we typically require arguments to be "array-like", I think it is convenient to add such a type union to `_validate_type()`. I've used this new addition to now accept `baseline` to be array-like (instead of just `tuple`).
Let me know if this already exists and I just missed it.

Add "array-like" to `_validate_type()`

---

doc/changes/latest.inc
mne/preprocessing/stim.py
mne/stats/tests/test_regression.py
mne/utils/check.py

We had a user on the forum who got an error message about a missing file that didn't actually **seem** to be missing. Turns out a trailing space was present in the search path, which was hard to spot.
https://mne.discourse.group/t/the-source-estimate-is-not-displayed-i-think-it-may-be-a-bug/6993/4
Here, I'm changing the `FileNotFoundError` message to put the path in quotation marks to help identify such issues quicker in the future.

MRG: If _check_fname() cannot find a file, display the path in quotation marks to help spot accidental trailing spaces

---

azure-pipelines.yml
doc/changes/latest.inc
mne/viz/backends/_pyvista.py
mne/viz/backends/_qt.py
requirements.txt

Companion PR to https://github.com/pyvista/pyvista/pull/4486, doesn't need to be reviewed or merged until that lands
Closes #11716

MAINT: Fix PySide6 and PyVista compat

---

doc/overview/roadmap.rst
mne/report/tests/test_report.py

Just some simple roadmap updates, mostly moving two `Open` issues to `Completed` and adding eye-tracking

MAINT: Update roadmap

---

doc/changes/latest.inc
mne/surface.py
mne/tests/test_surface.py
mne/viz/_brain/_brain.py

Fixes https://github.com/mne-tools/mne-python/issues/11728

[BUG] Fix mne.viz.Brain.add_volume_labels matrix ordering bug

---

doc/changes/latest.inc
doc/changes/names.inc
mne/viz/_brain/_brain.py
mne/viz/_brain/surface.py
mne/viz/_brain/tests/test_brain.py

Fixes #11703
Makes curv.*h files optional for creating Brain objects

removed requirement for curv.*h files to create Brain object

---

doc/changes/latest.inc
mne/event.py

This function was raising when an ID `np.int64` retrieved from the event array returned by `mne.find_events` was used.

Allow int-like as ID of make_fixed_length_events

---

mne/channels/channels.py
mne/channels/tests/test_channels.py

MNE does not use the channel `unit_mul` key a lot, most of the time it is hard-coded to `FIFF.FIFF_UNITM_NONE`, a.k.a. 0.
I am however using it to store the unit of the channels from data streams (most of the time EEG streams in microvolts). When changing the type of a channel, MNE will warn if the unit is changed. But since the field `unit_mul` is not that used in the MNE-ecosystem, it's simply left as is. Instead, I would like to reset the field to `FIFF.FIFF_UNITM_NONE` when the unit of a channel is changed.
```
from mne import create_info
from mne.io import RawArray
from mne.io.constants import _ch_unit_mul_named
info = create_info(["MISC1", "EEG1"], 2, ch_types="eeg")
raw = RawArray(np.zeros((2, 5)), info)
raw.info["chs"][0]["unit_mul"] = _ch_unit_mul_named[-6] …
```

Reset the channel unit multiplication factor on unit change

---

mne/viz/_figure.py

Part of https://github.com/mne-tools/mne-qt-browser/pull/172
The Qt Browser has a dialog menu to edit existing annotation. At the moment, editing an annotation from "whatever" to "bad" would not change the color to red. It would use the same color as what "whatever" had.
With this PR, all annotations starting with "bad" or "edge" will have their color overwritten to red *before* checking if the annotation name already had an attributed color.

Change color from annotation to red if name changes to "bad_" or "edge_"

---

doc/changes/latest.inc
mne/chpi.py
mne/tests/test_chpi.py

If cHPI was off for part of the recording the estimation would fail. Now it puts in `np.nan` for the values, which should work correctly with plotting etc.

BUG: Fix bug with cHPI off

---

doc/install/manual_install.rst
requirements_doc.txt

I've tweaked the manual install docs a little (e.g. shortened headings). I've also corrected an error – PyCharm Community is open-source (https://github.com/JetBrains/intellij-community/tree/master/python).

Update manual install docs

---

mne/io/reference.py

For consistency, change from `0` to `FIFF_UNITM_NONE` the `unit_mul` of an added reference channel.

[MRG] Use FIFF.FIFF_UNITM_NONE instead of 0 when adding a reference channel

---

doc/conf.py
mne/io/eeglab/eeglab.py

In `io.eeglab.RawEEGLab`, read annotations should also pass argument `uint16_codec`.
This problem has been reported in the group, click link for details:
https://mne.discourse.group/t/bug-report-an-error-in-io-eeglab-and-solution-to-it/7173
Merely by passing the correct codec argument to function call.
No

Fix eeglab.py, an error for read annotations in `RawEEGLab`

---

doc/changes/latest.inc
mne/viz/ica.py
mne/viz/tests/test_ica.py

No idea why my other branch is broken; but even on the website I can visualize it only once out of 5 tries.
Same as #11763 but working.
Fixes #11762

[MRG] By-pass set_annotations when plotting ICA sources 

---

mne/datasets/eegbci/eegbci.py
mne/datasets/utils.py

This PR
- fixes an error in the example (run 6 instead of run 4),
- expands the user's home directory if a path is supplied,
- and reflows some lines so that we can get rid of `#noqa`.

Refresh eegbci code and docstrings

---

mne/preprocessing/artifact_detection.py

Units were incorrectly documented for both of these. Could change the code to reflect the SI unit for rad/sec for rotation velocity limit, but given that degrees/s was the existing *behavior* this seems like a less invasive change (and also the units are wrong in docs for translation and must be changed anyway).
Pushed with `[ci skip]` because we don't need CIs for this I think :)

DOC: Fix incorrect docs for annotate_movement [ci skip]

---

mne/channels/channels.py

Fixes #11784
When combining channels on `mne.Epochs` object, the resulting instance will keep the event names of the input instance.

Keeping event names when combining channel on epochs objects

---

doc/changes/latest.inc
mne/time_frequency/tests/test_spectrum.py
mne/utils/spectrum.py

closes #11772 
new behavior is
- any kwargs passed to legacy `raw.plot_psd()` that are not recognized params of that method but happen to be params of Spectrum.plot() now raise a warning. 
- those kwargs will be respected though, instead of overwritten with the fallback values drawn from the defaults of `plot_raw_psd()`.
@larsoner @mscheltienne LMK if you think this is a good approach... normally unrecognized kwargs will raise a TypeError (and we could do that here) but my feeling was that since this is a legacy method whose kwargs are getting split up and translated to be passed into a chain of two new methods, it might be nice/smart/OK to be more forgiving.
Once we agree on an implementation I can add test/changelog

Fix kwarg handling in legacy .plot_psd() method

---

doc/changes/latest.inc
doc/events.rst
mne/__init__.py
mne/annotations.py
mne/tests/test_annotations.py

Similar to `mne.count_events()`, I think a function to count unique annotations would be quite useful. This PR adds a function `mne.count_annotations()` as well as a method `mne.Annotations.count()`.

Add `mne.count_annotations()`

---

tutorials/preprocessing/45_projectors_background.py

tiny change (missing space) that caused bad rendering in the projectors background tutorial:

fix tutorial whitespace

---

doc/changes/latest.inc
mne/viz/ica.py
mne/viz/tests/test_ica.py

Fixes #11800.
ICA.plot_sources raised an indexing error under specific conditions described in #11800. This error is no longer raised.
The problem was that ICA component numbers, as stored in the variable ``picks``, were being used to index into a variable ``label_props`` that describes the style in which lines should be plotted. ``label_props`` is as long as ``picks``, not as long as the total number of ica components. Hence, the index of the component in ``picks``, not the ICA component number itself, should be used.

Fix small bug that raised error under some conditions

---

doc/_static/js/contrib-avatars.js
doc/_static/style.css
doc/_templates/homepage.html
doc/_templates/layout.html

I saw this over on https://github.com/conda-incubator/setup-miniconda#contributors and thought it was neat, thought we might consider adding something similar. It ends up looking like this currently:

ENH: Show contributor image on homepage

---

doc/changes/latest.inc
mne/channels/montage.py
mne/io/egi/egimff.py
mne/io/egi/tests/test_egi.py

A channel can be its own reference (and thus be all zero) -- its `info['chs'][ii]['loc'][3:6]` should still be set properly and it wasn't before. Moreover I don't think this counts as a `FIFFV_MNE_CUSTOM_REF_ON` because really *something* has to be the ref, and I don't think it being in the dataset is necessarily problematic / custom. I think that's more meant for use cases like some channels having bipolar ref etc.
While investigating this I simplified some logic (with equivalent operations) in `montage`.
@scott-huberty according to `git blame` I think you worked on this most recently, please have a look when you get a chance!

BUG: Fix bug with MFF reference setting

---

doc/_static/style.css
doc/conf.py
mne/cov.py
mne/io/eyelink/eyelink.py
mne/io/proj.py
mne/time_frequency/tfr.py
mne/utils/docs.py
mne/viz/epochs.py
mne/viz/topomap.py

closes #11816 
First attempt worked pretty well, I thought:
Until I did a quick scan of `git grep versionadded` results, and checked some other API pages, and found this in `CSP.plot_filters`:

shrink versionadded notes in docstrings

---

doc/changes/latest.inc
doc/changes/names.inc
mne/bem.py

Fixes #11842.
convert_flash_mris function in bem.py file
crush when flash30==True and no flash5_reg.mgz file generated
add dd missing_ok=True as it is done in line 2074

convert_flash_mrism: crush when flash30 and no flash5_reg.mgz file

---

doc/changes/latest.inc
mne/io/_read_raw.py

MRG: Allow reading Curry and NEDF raw data via io.read_raw()

---

azure-pipelines.yml
mne/conftest.py
mne/tests/test_source_estimate.py
mne/viz/backends/_qt.py
mne/viz/utils.py
requirements_testing.txt

1. Add `pytest-qt`
2. Fix bugs that now show up thanks to re-throwing errors in callbacks
3. Add Qt option during testing to prefer windows stay at the back (helps with interactive testing not to have a ton of windows pop up)
Closes #11655

MAINT: Use pytest-qt

---

mne/io/bti/bti.py
mne/io/bti/tests/test_bti.py

Closes #11850
A private change just for the use of MNE-BIDS. Ideally we'd find some public way to do this but in the meantime the addition to the test with a comment saying MNE-BIDS needs the private attr is hopefully okay.
Split into two commits, the first modernizes the BTi tests using `pytest.mark.parametrize` and the second actually fixes #11850. In theory we could rebase+merge this then add to the `revs-ignore` but it might not be worth it. I'll mark what I actually changed in the test...

ENH: Add pdf_fname to RawBTi._raw_extras

---

doc/changes/latest.inc
mne/preprocessing/ica.py
mne/preprocessing/tests/test_ica.py
tutorials/preprocessing/40_artifact_correction_ica.py

Pretty sure from going back to the original paper that our `corrmap` code has been *EDIT: a little bit incorrect* ever since it was added in 0.10 in #2104 (which took over #1985, which took over #1795 -- the bug is present in all). We used the mean of some weirdly transformed maps  instead of just the mean of rms-normalized maps like noted in the paper. Our code in `main` did something like a z-score but not quite, even when fixing the incorrect usage of `std` to `mean`.
Fortunately I don't think it makes a big difference -- at least in our tutorial and tests the `newtarget` in this PR and the `newtarget` on `main` have a correlation coefficient > 0.99. But it should be better to use the correct / reference implementation I think.
Looking at the paper, one difference still remains where …

BUG: Fix bugs with corrmap computation

---

examples/visualization/sensor_noise_level.py
tutorials/intro/10_overview.py
tutorials/preprocessing/10_preprocessing_overview.py

Even if the method used is `.compute_psd(...).plot(...)`, I think a x-ref to `compute_psd` is better than a x-ref to the legacy `plot_psd` method.

Replace xref to plot_psd with compute_psd

---

doc/_static/js/contrib-avatars.js
tools/generate_codemeta.py

excludes bots from our homepage contributor avatars grid, and from our `codemeta.json` and `CITATION.cff` files.

Exclude bots from homepage and project metadata

---

doc/changes/latest.inc
mne/viz/evoked.py

On `main`, creating a topographic map by drag (SpanSelector) on a PSD plot, and then closing the topographic map yields:
```
File "/home/scheltie/pyvenv/mscheltienne/mne-python/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 309, in process
func(*args, **kwargs)
File "/home/scheltie/git/mscheltienne/mne-python/mne/viz/evoked.py", line 229, in _topo_closed
ax.lines.remove(line)
AttributeError: 'ArtistList' object has no attribute 'remove'
```
And the lines/fill are not removed from the PSD plot.

Fix closing topographic map created from PSD/Evoked plot

---

.circleci/config.yml
.github/workflows/circle_artifacts.yml
.github/workflows/tests.yml
.pre-commit-config.yaml
.yamllint.yml
azure-pipelines.yml
codecov.yml
doc/changes/latest.inc

Going to see if the "slow rendering" was actually a Numba problem as well as fixing recent CircleCI failures on `main`

FIX: Fix bug with arm64

---

mne/viz/topomap.py
tutorials/epochs/20_visualize_epochs.py

Fixes bug reported on the forum: https://mne.discourse.group/t/how-to-suppress-redundant-colorbars-when-using-epochsarray-plot-psd-topomap/7338

fix colorbar suppression when vlim is joint

---

mne/io/eyelink/_utils.py
mne/preprocessing/eyetracking/calibration.py
mne/preprocessing/eyetracking/tests/test_calibration.py

Was hoping to squeeze this in before 1.5 release, i.e. when the `Calibrations` class will be part of a stable version of MNE:
Here are 2 changes:
1. Allow a `Calibration` to have a negative onset time. While initially creating the (EDIT: `Calibrations`) PR, [we agreed](https://github.com/mne-tools/mne-python/pull/11719#discussion_r1235552854) that it should be okay for a calibration to have a negative onset time (i.e. for calibrations that were conducted before the task/recording started). However, on the main branch, these calibration onsets were forced to be `0` (_mea culpa_).
2. for the `plot` method of the `Calibrations` class, there is a `title` parameter. However, since we added an `axes` parameter so that users can pass in a custom axes and make whatever customizations they want, I …

FIX: A couple of minor changes to eyetracking Calibrations

---

mne/beamformer/_rap_music.py
mne/bem.py
mne/cov.py
mne/dipole.py
mne/forward/_field_interpolation.py
mne/inverse_sparse/_gamma_map.py
mne/inverse_sparse/mxne_inverse.py
mne/io/proj.py
mne/label.py
mne/minimum_norm/time_frequency.py
mne/preprocessing/otp.py
mne/preprocessing/tests/test_xdawn.py
mne/proj.py
mne/tests/test_cov.py
mne/transforms.py
mne/viz/misc.py
mne/viz/tests/test_epochs.py

A coworker ran into the annoying SVD error:
```
File "/somewhere/mne-python/mne/minimum_norm/time_frequency.py", line 51, in _prepare_source_params
U, s, Vh = linalg.svd(K, full_matrices=False)
File "/elsewhere/lib/python3.10/site-packages/scipy/linalg/_decomp_svd.py", line 131, in svd
raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
```
This transitions us to using `_safe_svd` in place of `scipy.linalg.svd` to work around the issue.

MAINT: Prefer _safe_svd for SVDs

---

mne/io/eyelink/eyelink.py
mne/io/eyelink/tests/test_eyelink.py

This is an issue as PR. 
I hit an edge case in one of my Eyelink files, where the participant was in the middle of a saccade upon recording start. This edge case results in missing values (i.e. ".") in the "ESACC" event of the ASCII file, that need to be properly converted to nans during reading. 
it was a quick fix, and I added a line to the test suite to simulate this edge case, but Let me know if you want me to share a file and code to reproduce the error, or if you need more info.

FIX: Missing Saccade information in Eyelink File

---

mne/tests/test_epochs.py

Second attempt on PR #11876.
Start with refactoring  tests related to saving epochs splits, while keeping the library code intact.
Related issues:
#11870
#7897
#5102

Refactor test_epochs.py::test_split_saving (1 out of 2)

---

doc/changes/devel.rst
mne/viz/backends/_pyvista.py
requirements_doc.txt
tutorials/simulation/70_point_spread.py

Closes https://github.com/mne-tools/mne-bids-pipeline/issues/770
x-ref https://github.com/pyvista/pyvista/issues/4788

FIX: Fix pyvista rendering

---

examples/time_frequency/time_frequency_erds.py

Fixes #11895. This PR corrects the y-axis labels (from "ERDS (%)" to just "ERDS") and changes the violin plots so that violins do not exceed the data range (-1 is the lowest possible value).

Minor fixes for ERDS maps example

---

doc/install/mne_tools_suite.rst

n/a
Adds the new [niseq](https://github.com/john-veillette/niseq) package to the list of related packages on "Overview of the MNE tools suite" page.
n/a

adds niseq package to "Related software"

---

mne/io/base.py
mne/io/utils.py
mne/utils/check.py

- a small follow-up indexing simplification when creating bids split fnames.
- a small fix to a docstring.
- check writing over a split when saving raw also for neuromag schema (we did the same fix for epochs earlier)

Small splits fix

---

doc/changes/devel.rst
mne/io/snirf/_snirf.py

Fixes #11710
Instead of checking that the `stim.data` size is strictly greater than 0, we check that it has at least 3 columns. This would follow the [*snirf* specifications](https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#nirsistimjdata) about `stim.data`:
> This is a numeric 2-D array with at least 3 columns, specifying the stimulus time course for the jth condition. Each row corresponds to a specific stimulus trial. The first three columns indicate `[starttime duration value]`.
@rob-luke @larsoner

Fix snirf loader

---

tutorials/simulation/10_array_objs.py

#11769 introduced a new `remove_dc` param to `Spectrum.__init__` but we forgot to add it to the relevant tutorial.

fix Spectrum init in tutorial

---

doc/changes/devel.rst
doc/file_io.rst
mne/_fiff/meas_info.py
mne/_fiff/pick.py
mne/_fiff/tests/test_pick.py
mne/decoding/ssd.py
mne/io/__init__.py
mne/io/_fiff_wrap.py
mne/preprocessing/_annotate_amplitude.py
mne/preprocessing/ica.py
mne/tests/test_rank.py
mne/time_frequency/tfr.py
mne/viz/epochs.py
mne/viz/evoked.py
mne/viz/topomap.py

Some TODOs I noticed:
1. Shouldn't need `_pick_inst`, just use `inst.pick` directly
2. From @alexrockhill we should have `write_info` to match `read_info`
3. `_get_channel_types` always operates on `info` and we have a public `info.get_channel_types` so we should just use it directly

MAINT: Cleanup use of _fiff

---

doc/install/contributing.rst

I got a bit confused when I couldn't find `latest.inc` in my doc folder anymore! - Thinking I may have forgot something I checked the contributing guide and it still points users to `latest.inc`.  I updated the doc to point users to `devel.rst`, which seems to be the new changelog file name!
Since this is a very minor change, I included `[skip actions] [skip azp]` in my commit message, but let me know if you want to trigger a full run of the CI.

DOC: update name of changelog in contributing guide

---

doc/install/manual_install.rst

Since there were reports that some users got confused by our suggestion to use the `mamba` command. Now we say to use `conda`, yet we can still ensure that the `mamba` solver is being utilized.
Also make use of `--override-channels` instead of `--strict-channel-priority` (should achieve the same thing but is less to type)

MRG: Suggest to use conda-libmamba-solver instead of mamba in install docs

---

doc/changes/devel.rst
mne/export/_edf.py
mne/export/tests/test_export.py
mne/io/edf/edf.py
mne/io/edf/tests/test_edf.py
mne/io/edf/tests/test_gdf.py

Fixes https://github.com/mne-tools/mne-python/issues/11947
"subject_info" were never actually set in the `RawEDF.info` object when loading an EDF file. Plus, additional subject's information were not correctly set in `RawEDF._raw_extras`. This PR aims at fixing this and therefore prevent any subject information from being lost when either reading or exporting data.
As per @larsoner's suggestion (see https://github.com/mne-tools/mne-python/issues/11947#issuecomment-1703037741), `info` are updated from `edf_info` in func `_get_info()` from [mne/io/edf/edf.py#L521](https://github.com/mne-tools/mne-python/blob/maint/1.5/mne/io/edf/edf.py#L521) following `subject_info` description in the Notes section from https://mne.tools/stable/generated/mne.Info.html description.
Tests have been modified …

Fix bug with subject_info when loading from and exporting to EDF file

---

doc/changes/devel.rst
examples/visualization/roi_erpimage_by_rt.py
mne/io/eeglab/eeglab.py
mne/io/eeglab/tests/test_eeglab.py
mne/preprocessing/ica.py
tutorials/intro/20_events_from_raw.py

Follow-up to #11925 by @jackz314 to simplify the logic a bit and fix [CircleCI](https://app.circleci.com/pipelines/github/mne-tools/mne-python/20496/workflows/c463dfaf-1a7a-4eff-9916-0d1707a1f730/jobs/58294). Basically by waiting to process `montage_units` until later we can avoid having to check if there are positions available, and we only try to figure out the radius if they are. This refactoring -- which involved moving the logic deeper in `_get_info` -- made it clear that it should also be added to `mne.preprocessing.read_ica_eeglab`, too, which is nice.

MAINT: Simplify logic for radius

---

doc/changes/devel.rst
mne/annotations.py
mne/export/_edf.py
mne/export/tests/test_export.py
mne/io/edf/edf.py
mne/io/edf/tests/test_edf.py

Fixes https://github.com/mne-tools/mne-python/issues/11959.
This PR aims at enabling to save channels when defined in channel-specific annotations. It basically writes each annotation with an extra `"@@{ch_name}"` appended to its description. Equally the channel info is parsed when reading the annotation file.

Handle channel information in annotations when loading data from and exporting to EDF file 

---

mne/io/base.py
mne/io/fiff/tests/test_raw_fiff.py
mne/io/nsx/tests/test_nsx.py

Necessary for PR #11924
- Purge recursion from `_write_raw()` and `_write_raw_fid()` interaction
- Improve general code readability
In #11924 I'm adding support for reading and writing from zip archives via using `Path` interface in the reading and writing functions. At the moment such change is not possible because `zipfile.Path`s don't support writing to several `fid`s at once. It's a problem because currently MNE-Python writes splits recursively, such that it keeps the `fid` for the first file open until we're done writing all the remaining splits.  
This PR attempts at fixing this recursion problem by using a simple `while` loop. As a bonus, no-recursion implementation is easier to understand and maintain (hopefully).

Refactor writing raw file

---

mne/viz/backends/_notebook.py

`%matplotlib notebook` doesn't work in Jupyter-Lab and since now also the plain notebook runs on the jupyterlab engine, it would be nice to support it. This means not using the internal `matplotlib.backends.backend_nbagg` but rather the `ipympl` package.

Use newer ipympl package for drawing matplotlib figures into a notebook

---

doc/install/mne_c.rst

it is getting harder and harder to get hands on `libxp.so.6`... soon MNE-C may need to run inside Docker running Ubuntu trusty or something.

update MNE-C install docs

---

doc/changes/devel.rst
mne/annotations.py
mne/io/edf/edf.py
mne/io/edf/tests/test_edf.py

The goal is to harmonize `_read_annotations_edf()` with other annotation reading functions and make it return an `mne.Annotations` object instead of a tuple containing its content. This simplifies `mne.annotations.read_annotations()` and reduces a bit the codebase.
**Note:** the same could apply to `_read_annotations_txt()`.

Make `_read_annotations_edf()` and `_read_annotations_txt()` return an `mne.Annotations` instance

---

.github/CODEOWNERS

@britta-wstnr @drammock in anticipation of asking other people to add themselves, I added more examples and myself in a few places (I should probably add myself more places but I'll do that later I think!). I tried to go by "category of knowledge" rather than file hierarchy, so @britta-wstnr you can see I added a couple of wildcards to the beamforming sections that I think should help catch relevant `tutorials/` and `examples/` without too many false alarms hopefully.

MAINT: Refactor codeowners

---

mne/time_frequency/spectrum.py
mne/time_frequency/tests/test_spectrum.py

following discussion in #11803 (summarized in [this comment](https://github.com/mne-tools/mne-python/pull/11803#issuecomment-1697994547)) this deprecates support for complex output in Spectrum and EpochsSpectrum objects.

Deprecate complex spectrum obj

---

tools/check_steering_committee.py

To follow steering committee policies we need to know member activity levels. This PR adds a tool to use PyGitHub to figure out the steering committee member activity levels across all of `mne-tools` for commits, issue comments, and PR comments:
```
{'GuillaumeFavelier': {'Commit': 0, 'IssueComment': 8, 'PullRequestComment': 0, 'Total': 8},
'adam2392         ': {'Commit': 18, 'IssueComment': 95, 'PullRequestComment': 125, 'Total': 238},
'agramfort        ': {'Commit': 24, 'IssueComment': 351, 'PullRequestComment': 141, 'Total': 516},
'alexrockhill     ': {'Commit': 35, 'IssueComment': 262, 'PullRequestComment': 103, 'Total': 400},
'bloyl            ': {'Commit': 0, 'IssueComment': 0, 'PullRequestComment': 0, 'Total': 0},
'britta-wstnr     ': {'Commit': 5, 'IssueComment': 76, …
```

MAINT: Add maintenance tool to check status

---

.circleci/config.yml

I logged in to CircleCI to an unpleasant surprise. The 250k credits we buy per month plus all our roll-over credits had been spent. This is why :scream: :
Switching to a scheduled run once a week is probably good enough given the upstream abstractions/testing in place. And this also fixes an existing misnomer with a "weekly" run that was actually being done monthly.

MAINT: Switch to scheduled runs for macOS [skip azp] [skip actions]

---

mne/utils/check.py
tools/azure_dependencies.sh
tools/github_actions_dependencies.sh

Following #11994
The change introduce by @larsoner seems wrong, `out` can never be None and numpy versions `1.9.x` are 7/8 years old.
```
def _check_edflib_installed(strict=True):
"""Aux function."""
out = _soft_import("EDFlib", "exporting to EDF", strict=strict) is not None
try:
from importlib.metadata import version
ver = version("EDFlib-Python")
except Exception:
pass
else:
out &= not check_version("numpy", "1.9.9") or _compare_version(
ver, ">", "1.0.7"
)
return out
```

Fix _check_edflib_installed

---

doc/changes/devel.rst
doc/conf.py
examples/io/elekta_epochs.py
mne/utils/docs.py
mne/viz/evoked.py
mne/viz/misc.py
mne/viz/topo.py
mne/viz/topomap.py
tutorials/preprocessing/70_fnirs_processing.py
tutorials/time-freq/20_sensors_time_frequency.py

I don't think `clip_box` ever really worked. Worked in local testing when doing for example `ylim=dict(mag=[-10, 10], grad=[-10, 10])` in the `examples`. Probably wasn't noticed much because by default we compute the limits to include the `max(abs(evoked.data))`.Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/20804/workflows/fb9767de-6f57-4a69-9585-d964ec4e5bd9/jobs/59196

BUG: Fix bug with clip box setting

---

doc/changes/devel.rst
mne/transforms.py

There were some parameters that `write_transform` has but `Transform.save` does not. This adds them.

Add the missing overwrite and verbose parameters to Transform.save

---

.circleci/config.yml
.github/workflows/circle_artifacts.yml
.gitignore
doc/Makefile
tools/circleci_download.sh

Once https://github.com/sphinx-gallery/sphinx-gallery/pull/1198 is merged we should merge this. Then "check built docs" will link to the root-level `sg_execution_times.html` which will have at the top any changed or modified examples, which is something I've wanted easy access to for a while now!
Draft until https://github.com/sphinx-gallery/sphinx-gallery/pull/1198 lands. I also simplified the circleci logic a tiny bit by always running a PATTERN variant (and when there are no examples that have changed, use a pattern that will have no matches).

MAINT: Link to sg_execution_times

---

doc/conf.py
examples/decoding/receptive_field_mtrf.py
examples/inverse/mixed_norm_inverse.py
mne/conftest.py
mne/fixes.py
mne/transforms.py
mne/viz/_3d.py
tutorials/io/60_ctf_bst_auditory.py
tutorials/machine-learning/30_strf.py
tutorials/stats-sensor-space/10_background_stats.py

Should hopefully fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/20874/workflows/654c85d4-7c99-4d06-801f-e5f99fad6e23/jobs/59342 and failures in https://github.com/mne-tools/mne-python/pull/11798, including a `distance="auto"` we need in `plot_sparse_stc` from changes to the camera system.

BUG: Fix doc building bugs

---

doc/changes/devel.rst
mne/annotations.py
mne/epochs.py

On `main`, creating Epochs including only MEG channels from an MEG + EyeLink re-aligned recording raises.
```
epochs = Epochs(
raw, events, event_id, tmin=-0.3, tmax=1, baseline=(None, 0), picks="meg"
)
```
Traceback:
```  
Cell In[1], line 19
epochs = Epochs(
File <decorator-gen-201>:12 in __init__
File ~/git/mscheltienne/mne-python/mne/epochs.py:3111 in __init__
super(Epochs, self).__init__(
File <decorator-gen-187>:12 in __init__
File ~/git/mscheltienne/mne-python/mne/epochs.py:694 in __init__
self.set_annotations(annotations)
File <decorator-gen-184>:12 in set_annotations
File ~/git/mscheltienne/mne-python/mne/annotations.py:823 in set_annotations
new_annotations._prune_ch_names(self.info, on_missing)
File ~/git/mscheltienne/mne-python/mne/annotations.py:496 in _prune_ch_names …
```

Correctly prune channel-specific annotations when creating Epochs

---

mne/io/base.py
mne/io/brainvision/brainvision.py

MAINT: Fix typos found by codespell

---

doc/changes/devel.rst
mne/_fiff/pick.py
mne/_fiff/tests/test_pick.py

Fixes #12018
Now, `inst.pick("eyegaze")` or `inst.pick("pupil")` will work. 
EDIT: Note to self, verify that tests pass, then update changelog.

FIX: allow user to pick "eyegaze" or "pupil" (fix in triage_eyetrack_picks)

---

mne/channels/channels.py
mne/channels/interpolation.py
mne/channels/tests/test_interpolation.py

Partially fixes #11481 (the other part was fixed in #12014).

Adding nan method to interpolate channels

---

tutorials/forward/20_source_alignment.py
tutorials/forward/30_forward.py

Closes #9181 
Per discussion with @drammock and @britta-wstnr,  the relevant information is already there in `tutorials/forward/20_source_alignment.py` so just adding a crossref to there from `30_forward.py`.

adding crossref from forward to create trans

---

mne/datasets/config.py

Relates to #11874 and WIP PR #11969. 
Update version number and checksum in `mne/datasets/config.py` to reflect the [release 0.149](https://github.com/mne-tools/mne-testing-data/releases/tag/0.149) of mne-testing-data which had Neuralynx testing dataset added.
Note: the version in `config.py` was updated from `0.147` to `0.149` (it seems there hasn't been an update for 0.148)

[ENH] update version and checksum in config.py for testing datasets

---

.github/workflows/release.yml

Closes #11509 
... then we wait to tag a GitHub release to see if it actually works!
Eventually we should also add `package` and `bandit` to PR merge requirements

MAINT: Use PyPI upload action for published releases

---

doc/changes/devel.rst
doc/changes/names.inc
mne/channels/tests/test_channels.py
mne/datasets/tests/test_datasets.py

This PR mark tests `test_adjacency_matches_ft` and `test_fetch_uncompressed_file` as network tests as they touch the internet.

Mark tests as network tests

---

Makefile
doc/install/advanced.rst
doc/install/contributing.rst

Skipped CIs because it seems unnecessary based on `git grep "make test"` and `"make pytest"`
Closes #11768
Closes #10526

DOC: Remove make test

---

doc/changes/devel.rst
mne/io/edf/edf.py
mne/io/edf/tests/test_edf.py

In the light of https://github.com/mne-tools/mne-python/pull/12017 (and issue https://github.com/mne-tools/mne-python/issues/12007), the following PR aims at preventing an annotation channel to be set when parsing an EDF+ annotation' description that contains the channel information (through [EDF+ "@@" convention](https://www.edfplus.info/specs/edftexts.html)) but that the parsed channel does not exist in the input data (see https://github.com/mne-tools/mne-python/pull/12017#discussion_r1337576499 for an example).
In such cases, the description is left as is and no channel is associated to the annotation, therefore making it global.

Do not set annotation channel when missing from input data when reading EDF

---

mne/_fiff/meas_info.py
mne/conftest.py
mne/html_templates/repr/info.html.jinja
mne/html_templates/repr/raw.html.jinja
mne/io/base.py
mne/utils/tests/test_misc.py
tutorials/intro/30_info.py
tutorials/intro/70_report.py
tutorials/raw/10_raw_overview.py

closes #9255 (supersedes)
closes #9249
@vagechirkov I marked you as co-author on the commit since I basically re-implemented what you did in #9255 (changes on main were too drastic to do a simple rebase)

Collapsible html repr for raw/info

---

mne/io/__init__.py
mne/io/tests/test_deprecation.py
mne/source_space/__init__.py
mne/source_space/tests/test_source_space.py

these are some things that need to happen before converting our lazy imports to type stubs. NB @hoechenberger: I have a script working locally that automatically generates *ALL* `.pyi` files and also automatically changes all `__init__.py` files to use `attach_stub()`, but it needs this PR first.

clean  up some deprecations

---

doc/changes/devel.rst
mne/_fiff/tag.py
mne/_fiff/write.py
mne/tests/test_evoked.py

add unicode roundtrip for FIF

---

doc/_templates/sidebar-quicklinks.html
doc/conf.py

should fix #12093 (the last part: error in conf.py when writing redirects). Changes:
- uses pathlib.Path for redirect handling
- splits the redirect creation into 3 functions (the logic for each type of redirect is quite different)
- updates the homepage sidebar quicklinks to use the new locations of those pages
- adds a few redirects that were missed in #12043
- strips `.html` off of the specification of custom redirects, which lets us eliminate several more `noqa E501` comments

Fix redirects

---

.git-blame-ignore-revs

Self-merging without CIs because this one is trivial. Removed `SetChannelsMixin` one because it doesn't show up in `git log` (must have been squash-merged?)

MAINT: isort

---

doc/api/covariance.rst
doc/api/creating_from_arrays.rst
doc/api/datasets.rst
doc/api/decoding.rst
doc/api/events.rst
doc/api/export.rst
doc/api/file_io.rst
doc/api/forward.rst
doc/api/inverse.rst
doc/api/logging.rst
doc/api/most_used_classes.rst
doc/api/mri.rst
doc/api/preprocessing.rst
doc/api/reading_raw_data.rst
doc/api/report.rst
doc/api/sensor_space.rst
doc/api/simulation.rst
doc/api/source_space.rst
doc/api/statistics.rst
doc/api/time_frequency.rst
doc/api/visualization.rst

after #12403 the URL of API pages moved from `generated/` to `api/generated/`. This will break lots of links from the forum (as pointed out by @mscheltienne) and will also break the version switcher's ability to find corresponding pages in different docs versions.
This PR puts the autodoc stub files back where they used to be, to avoid all that badness.
supersedes / closes #12100

restore original location of API stubs

---

doc/changes/devel.rst
mne/channels/channels.py
mne/channels/tests/test_interpolation.py

Better error message raised when someone accidentally provided the `method` argument as a `str`, e.g.
```
from mne.io import read_raw_fif
directory = sample.data_path() / "MEG" / "sample"
raw = read_raw_fif(directory / "sample_audvis_raw.fif", preload=False)
raw.pick("eeg", exclude=[]).load_data()
raw.interpolate_bads(method="spline")
```
On main:
```
ValueError: Invalid value for the 'method['meg']' parameter. Allowed values are 'MNE' and 'nan', but got 'spline' instead.
```
On this PR:
```
TypeError: method must be an instance of dict or None, got <class 'str'> instead.
```

Better error message when a bad method type is provided

---

mne/report/report.py
mne/viz/topomap.py
mne/viz/utils.py

Should fix the mysterious timeout observed in https://github.com/mne-tools/mne-bids-pipeline/pull/793. This one was tough to track down. Somehow having `n_jobs > 1` and having these `subscribe`s caused what I assume is a circular reference problem. Could be related to `Agg` backend not emitting the `close` event, not sure. Locally this `_auto_weakref` fixes the error at least when testing with:
```
rm -Rf ~/mne_data/derivatives/mne-bids-pipeline/ds000248_base/ && pytest mne_bids_pipeline -k ds000248_base
```
cc @wmvanvliet we'll need to be mindful of creating these circular references going forward I think :shrug: 
No idea how to make a nicely self-contained test for this so I'll open a PR to mne-bids-pipeline to make sure the doc build works when built against this branch, then I'll …

BUG: Fix bug with weakref

---

doc/changes/devel.rst
mne/conftest.py
mne/io/egi/egimff.py
mne/io/egi/tests/test_egi.py

I'm going to guess that some version of the EGI software, including the one at my site, store events on channels `DIN`. Those events are delivered from a parallel port (0 to 255) and the `DIN` names span:
```
DIN1, DIN2, ..., DIN9, DI10, DI11, ... DI99, D100, D101, ..., D255
```
The MFF format does not store them in order, but in the order of occurrence. If a `DIN2` occurs before a `DIN1`, the `DIN2` event is stored "first". Thus, when combining the binary event channels into a synthetic trigger channel, simply remapping to `events_ids = np.arange(len(include_)) + 1` yields incorrect values and swap between events.

Fix combination of DIN events channels with EGI reader

---

mne/utils/check.py
mne/utils/tests/test_check.py

Fixes #12127. Previously, a string was considered to be array-like, but now only the following types are accepted: list, tuple, set, and np.array. For all other list-like types: YAGNI for now.

Fix array-like check

---

tutorials/preprocessing/60_maxwell_filtering_sss.py

missing whitespace between word and following `:func:` crossref is causing the `:func:` to get rendered.

typo fix in maxwell filtering tutorial

---

doc/development/governance.rst
doc/overview/people.rst

Document update of governance structure following discussion in the last month or so in `mne-python-steering-council` in accordance with our governing guidelines:
1. BDFL @agramfort -> @drammock
2. Removal of @bloyl and @GuillaumeFavelier from steering council (inactivity)

DOC: Document governance updates

---

.lgtm.yml

LGTM.com has been deprecated and replaced by GitHub code analysis:
https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/
File initially added by #5914.

Remove LGTM.com configuration file

---

mne/utils/config.py

@adam2392 configured the `mne-icalabel` repository to use the datasets downloads infrastructure from MNE-Python.
For now, it issues:
```
RuntimeWarning: Setting non-standard config type: "MNE_DATASETS_ICALABEL_TESTING_PATH"
```

Add mne-icalabel wildcard

---

doc/changes/devel.rst
mne/commands/mne_coreg.py
mne/gui/_gui.py
mne/viz/_3d.py

Closes #12123
@nordme feel free to try it. Now I get after running this and clicking "Lock Fiducials":
```
mne coreg --subjects-dir=~/mne_data/MNE-sample-data/subjects -s sample -f ~/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw.fif --trans ~/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw-trans.fif
```
And after clicking "Fit Fiducials" just to get more points outside the scalp:
Also fixes a bug where env var setting had no effect, and deprecates some parameters that we haven't had support for for years so probably will never add. We were already emitting a warning for these so officially deprecating them is easy enough.

BUG: Fix bug with interior points not showing

---

doc/changes/devel.rst
mne/report/report.py
mne/report/tests/test_report.py
tutorials/intro/70_report.py

Closes https://github.com/mne-tools/mne-bids-pipeline/issues/573
See for example https://mne.tools/mne-bids-pipeline/1.4/examples/ds000248_ica/sub-01_task-audiovisual_report.html#ICA 
1. Fix component numbers which used to just be `range(len(picks))` as noted in https://github.com/mne-tools/mne-bids-pipeline/issues/573
2. Always write the cumulative variance explained. Even though it's not informative for the first component, it makes the slider behavior between the first and second components more uniform and thus easier to use.
3. Fix bug where `{round(x)}` was used, but `round` always returns a `float` so these were displayed with `.0` at the end, which is misleading (looks like there is one decimal point of precision when there are none). This now formats better with …

BUG: Fix bug with Report.add_ica component number

---

doc/changes/devel.rst
mne/report/report.py
mne/report/tests/test_report.py

Tries to fix CI error we get for mne-bids-pipeline:
https://github.com/mne-tools/mne-bids-pipeline/pull/807#issuecomment-1791571387
This is a followup-fix for #12156

Try to fix ICA Report

---

doc/changes/devel.rst
mne/io/eeglab/eeglab.py

Fixes #11641 (I can successfully load the files linked in this issue). However, he code is likely still dysfunctional, because we are currently searching for labels `"Nasion"`, `"Right periauricular point"`, and `"Left periauricular point"` (case sensitive). I am not sure if these names are even standardized, but "periauricular" seems to be a typo on our end, because I have only ever heard the term "preauricular".
But unless we know more about how fiducials are stored in EEGLAB files, we are stuck with what we have I guess.

Fix inferring fiducials from EEGLAB

---

doc/changes/devel.rst
mne/_fiff/meas_info.py
mne/_fiff/reference.py

Example: Fixes #5619
Adds documentation that explains that the montage must be set after adding a reference.
Should I also add a warning that runs inside the code itself after running `set_montage`?

[DOC] Add documentation for setting montage order

---

doc/changes/devel.rst
doc/changes/names.inc
mne/io/edf/edf.py

When reading in raw GDF files I got the following error
>UFuncTypeError: Cannot cast ufunc 'clip' output from dtype('float64') to dtype('uint32') with casting rule 'same_kind'
Referring to the usage of `np.clip` here: https://github.com/mne-tools/mne-python/blob/87d6be9047bbd5b234e22eafd79ab7695814fb41/mne/io/edf/edf.py#L1446
This error can reproduced noting that `np.inf` has dtype of `float64`. 
```python
dur = np.ones(10, dtype=np.uint32)
np.clip(dur, 1, np.inf, out=dur)
>>> UFuncTypeError: Cannot cast ufunc 'clip' output from dtype('float64') to dtype('uint32') with casting rule 'same_kind'
```
Changing aforementioned line 1446 to `np.clip(dur, 1, np.inf, out=dur, casting="unsafe")` seemingly fixes this issue.
Additionally, there is a typo when using the …

Changed casting rule in np.clip to allow reading of raw GDF files

---

doc/changes/devel.rst
mne/viz/backends/_pyvista.py

Okay @nordme on this branch if you do:
```
MNE_COREG_HEAD_OPACITY=0.25 mne coreg --subjects-dir=~/mne_data/MNE-sample-data/subjects -s sample -f ~/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw.fif --trans ~/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw-trans.fif
```
you should see:
You can see the points inside, as well as scale-by-distance working again (it wasn't before).
Closes #12123

FIX: Fix bug with coreg scalars

---

mne/io/eyelink/_utils.py

This PR Fixes a problem with reading an Eyelink file that was raised on the Discussion forum: https://mne.discourse.group/t/issue-with-read-raw-eyelink/7787
The problematic file provided by the researcher had a line that only contained a newline character, which broke the parser.
This branch checks for and skips empty lines, fixing the problem.
I did a quick performance check to see how much longer file reading takes with the additional checks:
```
import mne
fname = mne.datasets.eyelink.data_path() / "eeg-et" / "sub-01_task-plr_eyetrack.asc"
%timeit mne.io.read_raw_eyelink(fname)
```
on main:
```
860 ms ± 30.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
on this branch:
```
997 ms ± 139 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

FIX: skip empty lines in read_raw_eyelink

---

doc/changes/devel.rst
mne/time_frequency/spectrum.py
mne/time_frequency/tests/test_spectrum.py
tutorials/preprocessing/50_artifact_correction_ssp.py

Closes #12075
1. Only warn if the channel isn't in bads
2. Warn even if complex when the value is actually zero

BUG: Fix bug with spectrum warning

---

mne/viz/_3d.py
mne/viz/backends/_pyvista.py
tutorials/forward/20_source_alignment.py

I noticed two 3D rendering bug I introduced recently, fixed on this PR:
| [stable](https://mne.tools/stable/auto_tutorials/forward/20_source_alignment.html) | [dev](https://mne.tools/dev/auto_tutorials/forward/20_source_alignment.html) | PR |
| -- | -- | -- |
| ![image](https://github.com/mne-tools/mne-python/assets/2365790/6760c7b0-8336-4649-93dc-44024c6f4234) | ![image](https://github.com/mne-tools/mne-python/assets/2365790/40505023-daba-4a66-9c4d-4cf72f117b7f) | ![image](https://github.com/mne-tools/mne-python/assets/2365790/7727d7e2-966e-4a12-935b-6992675ec6a2) |
1. The axes are errantly multicolored
2. The MEG sensor opacity is too high
This PR fixes those two issues

BUG: Fix bug with default alpha and axes

---

doc/changes/devel.rst
mne/html_templates/repr/ica.html.jinja
mne/preprocessing/ica.py
mne/preprocessing/tests/test_ica.py

I was experimenting with different optional `fit_params` when working with ICA, generating Reports that included the HTML representation of ICA instances. However, I then realized that we don't display those fit parameters yet, even though we apply some defaults if the user doesn't explicitly pass any values. This PR adds this feature:

MRG: Add ICA's `fit_params` to HTML representation

---

.pre-commit-config.yaml

This was needed on my end to have the rstcheck pre-commit hook work correctly.

Add tomli to rstcheck dependencies

---

.circleci/config.yml
mne/_fiff/meas_info.py
mne/commands/mne_browse_raw.py
mne/preprocessing/artifact_detection.py
mne/preprocessing/maxwell.py
mne/utils/config.py

Just a couple of minor docstring updates I found while working with some functions/commands.

DOC: Update docs

---

.github/workflows/tests.yml
.pre-commit-config.yaml
README.rst
doc/development/contributing.rst
environment.yml
mne/utils/config.py
pyproject.toml

Now that v1.6 is out, it's time to remove support for Python 3.8. We should also add support for Python 3.12, but since I don't know if there are any major blockers (likely!), we'd better tackle this in another PR.
This PR is required for #12218.

Remove Python 3.8

---

pyproject.toml

My linter showed the entire pyproject.toml file in red, so I went on the investigate.
Turns out both section and key names were incorrect. I fixed that. I also removed the zip-safe flag because it's been deprecated for many years and isn't used anymore.
BTW the linter I'm using is https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml
It's pyproject.toml-aware.

Fix pyproject.toml setuptools configuration

---

pyproject.toml

A few dependencies were only included in `test_extra`, but they should also be included in `full` (e.g., `pybv`). This now adds duplication – should we add a "private" variant to avoid this?
Another `doc` dep was needed for running `mne/report/js_and_css/bootstrap-icons/gen_css_for_mne.py`

Add some omitted dependencies to "full" and "doc" variants

---

doc/api/reading_raw_data.rst
doc/changes/devel.rst
doc/changes/v1.6.rst
doc/conf.py
mne/io/neuralynx/neuralynx.py

An incorrect type hint sneaked in via #11969, causing confusion to static type checkers.
Since we don't use type hints in MNE yet (except for some very rare exceptions), I simply removed the faulty one instead of fixing it.
cc @KristijanArmeni 
FYI the correct hint for our supported versions of Python would be `Optional[List[str]]` or `Union[None, List[str]]`

Fix incorrect type hint in Neuralynx I/O module

---

environment.yml
mne/gui/tests/test_coreg.py
mne/report/tests/test_report.py
pyproject.toml
tools/azure_dependencies.sh
tools/github_actions_dependencies.sh

Put NumPy 2.0 back and remove HDF5 and dipy, which we'll have to omit until they release builds built against NumPy 2.0. Also fix a transition from EDFlib-Python to edfio in the install step that we missed.

MAINT: Restore NumPy 2.0 testing

---

.git_archival.txt
.gitattributes
Makefile
doc/development/contributing.rst
doc/install/manual_install.rst
doc/install/updating.rst
mne/__init__.py
pyproject.toml

I added `.git_archival.txt`, which allows us to entirely remove the `mne/_version.py` file:
- When downloading an archive from GH, this file will then contain the  correct version number
- When building an sdist, the version number is added to `PKG-INFO`
I have also included some tiny corrections / touchups in the install & contributions guides.

MRG: Remove `_version.py` file; and small doc cleanups

---

doc/changes/devel.rst
mne/io/base.py
mne/io/tests/test_raw.py

Perhaps I'm the first person to try `raw[:, -1]` because it returns an empty array on `main` which is wrong:
```
>>> raw[:, -1][0].shape
(63, 0)
```

BUG: Fix bug with last item access

---

mne/utils/docs.py

#11922 
This PR fixes two small details in the description of `max` and `mean_flip` modes for `mne.extract_label_time_course`.

DOC: fix the description of extract_label_time_course modes

---

mne/surface.py

I used strictly less than before but since some of the images (e.g. CTs) have clipping, that caused equally high intensity neighbors not to be counted so this fixes that.

[BUG, MRG] Account for clipping when finding voxel neighbors

---

.gitignore
doc/sphinxext/contrib_avatars.py
tools/circleci_bash_env.sh

See title, should make it easier to build our docs. @britta-wstnr can you try building docs on this branch and see if it works? I made the avatar image gen opt-in (and opted CircleCI in) rather than opt-out so you should just be able to check out my branch, and run `make clean` then `make html` and see if it succeeds. I think we should iterate until things work for you to improve our odds of other contributors being able to build docs.

MAINT: Make selenium optional and use on CircleCI

---

LICENSE.txt

I've updated the text to be in line with [Wikipedia](https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_(%22BSD_License_2.0%22,_%22Revised_BSD_License%22,_%22New_BSD_License%22,_or_%22Modified_BSD_License%22)) and [OSI](https://opensource.org/license/bsd-3-clause/). I've also updated the year to 2023, knowing that we'll need to change it in less than four weeks again.

Update year and use "official" text

---

doc/changes/devel.rst
mne/io/base.py
mne/io/fiff/tests/test_raw_fiff.py

Turns this cryptic error (from MNE-BIDS-Pipeline but the idea is clear I think):
```
│13:37:40│ 🐛 sub-01 run-noise A critical error occurred. The error message was: /mnt/ssds2/larsoner/mcq/natural-conversations-bids/derivatives/mne-bids-pipeline/sub-emptyroom/ses-20230412/meg/sub-emptyroom_ses-20230412_task-noise_proc-filt_split-01_raw.fif
Starting post-mortem debugger.
<traceback object at 0x7f11e2640d80>
> /home/larsoner/python/mne-python/mne/io/base.py(2606)__init__()
-> assert op.isdir(op.dirname(fname)), fname
```
into a useful one:
```
13:46:43│ 🐛 sub-01 run-noise A critical error occurred. The error message was: parent directory does not exist: "/mnt/ssds2/larsoner/mcq/natural-conversations-bids/derivatives/mne-bids-pipeline/sub-emptyroom/ses-20230412/meg"
```

BUG: Fix bug with parent dir check

---

README.rst

I've removed the license text at the bottom of README.rst (now it just says that the license is BSD-3-Clause). I think this is sufficient, and the license text is linked in at least two places on GitHub (right sidebar and tab right next to README, Code of conduct, and Security).
We could even remove the entire section here, WDYT?

Remove license text in README

---

doc/changes/devel.rst
mne/annotations.py
mne/epochs.py
mne/evoked.py
mne/io/base.py
mne/source_estimate.py
mne/tests/test_annotations.py
mne/time_frequency/tfr.py
mne/utils/dataframe.py

~~it's working, but a bit hackish, so marking as draft while I clean it up.~~
closes #12274 
```pycon
In [1]: import mne
In [2]: foo = mne.Annotations(onset=[1,5,11], duration=[2, 2, 3], description=list('abc'))
In [3]: foo.to_data_frame(None)
Out[3]: 
onset  duration description
0    1.0       2.0           a
1    5.0       2.0           b
2   11.0       3.0           c
In [4]: foo.to_data_frame("datetime")
Out[4]: 
onset  duration description
0 1970-01-01 00:00:01       2.0           a
1 1970-01-01 00:00:05       2.0           b
2 1970-01-01 00:00:11       3.0           c
In [5]: foo.to_data_frame("ms")
Out[5]: 
onset  duration description
0   1000       2.0           a
1   5000       2.0           b
2  11000       3.0           c
In [6]: foo.to_data_frame("timedelta")
Out[6]: 
onset …
```

support different time formats in Annotations.to_data_frame()

---

doc/changes/devel.rst
doc/conf.py
mne/io/brainvision/brainvision.py
mne/io/bti/bti.py
mne/io/eeglab/eeglab.py
mne/io/fieldtrip/fieldtrip.py
mne/io/kit/kit.py
mne/io/nedf/nedf.py

Also clean up a little after #12296, where I accidentally put a few return types in quoation marks that were, in fact, no forward references; and forgot to annotate the BV reader.
Also updated the changelog.

MRG: Add return type hints to all `read_epochs_*()` functions

---

doc/_static/style.css
doc/conf.py

Should make our video embedding a bit nicer (and much smaller) by using standard browser controls:
| main | PR |
| -- | -- |
| <img width="940" alt="Screenshot 2023-12-15 at 1 19 24 PM" src="https://github.com/mne-tools/mne-python/assets/2365790/14dd6bcd-6b96-4ba3-b784-81ed22243a65"> | <img width="847" alt="Screenshot 2023-12-15 at 1 18 19 PM" src="https://github.com/mne-tools/mne-python/assets/2365790/e64e865e-a3ff-4624-8149-0603fcbfce3b"> |

MAINT: Use HTML5 embedding for examples

---

doc/changes/devel.rst
mne/time_frequency/multitaper.py
mne/time_frequency/tfr.py

Follow-up of #12305.
As discussed, I have just switched the `epoch_data` parameter for the `tfr_array_morlet` and `tfr_array_multitaper` functions to `data`, and have added a `FutureWarning` if `epoch_data is not None`.
The `_compute_tfr` function which is called internally has the `epoch_data` parameter, but I haven't touched that here.
https://github.com/mne-tools/mne-python/blob/b1dd84c36264d716beebd5f6c6ae470a36c762e8/mne/time_frequency/tfr.py#L417-L431

Switch from `epoch_data` to `data` for TFR array functions

---

CONTRIBUTING.md
doc/development/index.rst

reported here: https://github.com/mne-tools/mne-python/pull/12309#issuecomment-1863180667
also closes #12312

fix 404 link on devel landing page

---

tools/azure_dependencies.sh

Until https://github.com/scipy/scipy/issues/19713 and https://github.com/scipy/scipy/issues/19605 are resolved, we can't test NumPy 2.0 on Windows. But in theory we should still be able to use the nightly wheels for other packages that were compiled against NumPy 2.0. Rolling back to NumPy < 2.0.0.dev0 means we can reenable h5py, too, which is nice while we wait for https://github.com/h5py/h5py/pull/2355.

MAINT: Work around bad SciPy nightly wheels

---

doc/changes/devel/12319.bugfix.rst
doc/changes/names.inc
mne/report/report.py

Discussion [on Discourse](https://mne.discourse.group/t/report-add-html-does-not-obey-section/8016/2) about Report.add_html().
HTML chunks were added to the main level, not within the supplied `section`. 
The section value passed to `self._add_or_replace` was hard coded as `None` and didn't use the supplied section argument.

fix section parameter to allow proper hierarchy

---

.github/workflows/tests.yml
mne/conftest.py
mne/viz/epochs.py
pyproject.toml

Calling `plt.colorbar` isn't as clean because it uses `gcf().colorbar(...)`. Instead let's use `ax.figure.colorbar` to avoid warnings like https://github.com/mne-tools/mne-qt-browser/actions/runs/7324019308/job/19960149079?pr=222#step:11:195 :
```
UserWarning: Adding colorbar to a different Figure <Figure size 600x400 with 4 Axes> than <Figure size 640x480 with 0 Axes> which fig.colorbar is called on.
```

BUG: Fix bug with epochs image

---

doc/development/contributing.rst

I added a missing colon. The contributing guide mentions that changelog entries can be skipped for such minor changes, but it doesn't say how (the check is failing). I think it would be good to be explicit here (i.e. it is supposed to fail). Let me know how it's done and I can add a sentence in this PR.

Fix typo in contributing guide

---

doc/changes/devel/12336.bugfix.rst
doc/development/contributing.rst
mne/channels/channels.py
mne/channels/interpolation.py
mne/channels/tests/test_interpolation.py
mne/defaults.py

Fixes https://github.com/mne-tools/mne-python/issues/12333.
It also looked like there was a bug where epochs would have the channel indices of their epochs set to `nan` if `nan` was the method which was also fixed.

[ENH] Add support for ieeg interpolation

---

mne/epochs.py

Closes #12346
Not a pandas expert but `mne/tests/test_epochs.py` passes on my machine now and `metadata.dtypes` and contents look reasonable at first look

MAINT: Fix for pandas pre

---

doc/changes/devel/12345.bugfix.rst
mne/viz/evoked.py
mne/viz/topo.py

Code snippet to reproduce:
```python
from mne import Epochs, find_events
from mne.io import read_raw_fif
from mne.viz import plot_evoked_topo
directory = sample.data_path()
fname = directory / "MEG" / "sample" / "sample_audvis_filt-0-40_raw.fif"
raw = read_raw_fif(fname, preload=False)
raw.pick(("eeg", "stim")).load_data()
events = find_events(raw)
epochs = Epochs(raw, events, dict(cond1=1, cond2=2), tmin=-0.2, tmax=0.5, preload=True)
evokeds = {"cond1": epochs["cond1"].average(), "cond2": epochs["cond2"].average()}
fig = plot_evoked_topo(
[evokeds["cond1"], evokeds["cond2"]],
color=["#3498DB", "gray"],
vline=[0, 0.080],
)
```
On `main`, clicking on axis yields:
```python
File …
```

[MRG] Fix clicking on an axis of mne.viz.plot_evoked_topo when multiple vertical lines are added

---

.pre-commit-config.yaml
mne/_fiff/open.py
mne/decoding/tests/test_search_light.py
mne/epochs.py
mne/fixes.py
mne/preprocessing/_annotate_amplitude.py
mne/preprocessing/artifact_detection.py
mne/preprocessing/interpolate.py
mne/preprocessing/tests/test_realign.py
mne/proj.py
mne/report/report.py
mne/source_space/_source_space.py
mne/stats/cluster_level.py
mne/stats/tests/test_cluster_level.py
mne/tests/test_annotations.py
mne/utils/numerics.py
mne/viz/_mpl_figure.py
mne/viz/evoked_field.py
pyproject.toml

From the NumPy 2.0 migration guide they mentioned that there is a new ruff rule NPY201, so let's go ahead and enable it. It caught some `==` where we should have used `is` in a few places. It also false-alarms on stuff like `if x.dtype == float`, which we shouldn't change to `if x.dtype is float` because `is` does not give the behavior we want:
```
>>> np.dtype(float) == np.dtype("<f8")
True
>>> float == np.dtype("<f8")
True
>>> float is np.dtype("<f8")
False
```
so this PR just uses the explicit `if x.dtype == np.dtype(float)` in those cases.

MAINT: Check and format with NPY201

---

tools/github_actions_dependencies.sh

this should hopefully make the pip-pre CI green again, so that #12358 and #12354 can go in.

MAINT: workaround for pyvista / numpy dtypes in CIs

---

.github/workflows/tests.yml
doc/conf.py
mne/conftest.py
mne/export/_egimff.py
tools/github_actions_dependencies.sh

I've replaced Python 3.11 with Python 3.12 in our `pip-pre` test on `ubuntu-latest`.
Which versions do we want to test explicitly? Currently (with this change), we're testing 3.9 (ubuntu-latest/minimal, macos-latest/mamba, ubuntu-20.04/old), 3.10 (ubuntu-latest/conda, windows-latest/mamba), and 3.12.

Add Python 3.12

---

environment.yml
mne/annotations.py
mne/conftest.py
mne/io/fiff/tests/test_raw_fiff.py
pyproject.toml
tools/azure_dependencies.sh
tools/github_actions_dependencies.sh

Band-aid until https://github.com/mne-tools/mne-python/pull/12376 lands, but allows us to have green CIs in the meantime. Will remove this pin in https://github.com/mne-tools/mne-python/pull/12376

MAINT: Work around pytest issue

---

doc/changes/devel/12371.newfeature.rst
mne/io/neuralynx/neuralynx.py

Fixes #12370.
**Drop `np.where` and compute onsets via `np.cumsum`** Instead of using `np.where` to iterative over gap indices and search over the recording samples, in this PR I compute all segment start samples by cumulatively summing segment sample sizes (see this change: [5b40d2](https://github.com/KristijanArmeni/mne-python/commit/5b40d21f33e92e1d101aa6de8866a15aea0b997d)).
This gives starting indices for all segments, then I select only those corresponding to gaps. Doing it this way, yields substantial improvements over using `np.where` as confirmed on a a few local datasets with increasing numbers of gaps (see Figure in #12370) 

[ENH] Speed up `read_raw_neuralynx()` on large datasets with many gaps

---

mne/viz/misc.py

seems misleading to refer to SVD plots as "spectra" given that eigenvalue indices are discrete; a spectrum 
> is a condition that is not limited to a specific set of values but can vary, without gaps, across a continuum. (Wikipedia)
xref: https://mne.discourse.group/t/spectra-plot-of-the-covariance-explanation/8141

fix misleading docstring return description for covariance SVD plot

---

.circleci/config.yml
.github/workflows/tests.yml

In theory this should work:
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
But who knows if `setup-micromamba` actually handles it properly, etc. Let's see!
Shouldn't merge until the one run of interest is green and I uncomment the other ones.

MAINT: Test arm64 on GHA

---

doc/conf.py
mne/epochs.py
mne/utils/docs.py

The "Edit on GitHub" link is broken for all *generated* pages on our site (which means all tutorials, and all API pages below the top-level "python reference" page). This is a known problem at the theme level; until fixed let's just disable it.
Thanks @britta-wstnr for pointing it out.

disable (mostly broken) "edit on GitHub" link in sidebar

---

mne/utils/config.py
mne/utils/docs.py

Remove `jinja2` and `pooch` from `sys_info`

---

mne/io/neuralynx/neuralynx.py

Fixes #12413.
So far, to insert gap data (0's representing missing samples), the `AnalogSignalGap` class with a dummy `load()` method was defined and used to mirror the `neo.AnalogSignalProxy` object which loads recorded samples from disk.
As of v13, `neo` allows only`AnalogSignal`/`AnalogSignalProxy` types to be appended to `Segment.analogsignals` attribute. To fix this, we drop the over-engineered `AnalogSignalGap` class. Instead, we create zero-arrays directly with `AnalogSignal` and use a simple control statement to distinguish loading real data (via `AnalogSignalProxy.load().magnitude`) and padding 0's (via `AnalogSignal.magnitude`) when looping over segments and creating the output data array.

[FIX] remove AnalogSignalGap

---

pyproject.toml

Should fix this, which appeared in #11776
```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'pydocstyle' -> 'lint.pydocstyle'
- 'per-file-ignores' -> 'lint.per-file-ignores'
```
https://github.com/mne-tools/mne-python/actions/runs/7811101140/job/21305620584?pr=12207

ruff TOML updates

---

mne/_fiff/meas_info.py

Fixes #12407
Label `no-changelog-entry-needed` to add i think

DOC: Specifies that a custom reference is anything but an average projector

---

doc/changes/devel/12436.bugfix.rst
mne/source_estimate.py
tutorials/clinical/20_seeg.py

Fixes broken CI from https://github.com/mne-tools/mne-python/pull/12382#issuecomment-1937367062
Ok so, I forgot to test that the shape was the same so volume source estimates with a different rr shape caused an error so I fixed that. But also, in doing so I noticed that the default, `surface='pial'` was being used (right). I'm not sure if this was on purpose but I think the `surface=None` version looks a lot better (left) which uses the src vertices. I think it actually was super confusing having an STC projected to pial surfaces and I would think maybe is a bug.

Fix stc_near_sensors error

---

.github/workflows/tests.yml

Since #12419 the coverage tanked to 29%.
Likely because token-less uploads are not supported anymore, thus the secrets `CODECOV_TOKEN` should be added to this repository if it is missing.
c.f. https://github.com/codecov/codecov-action?tab=readme-ov-file#usage

Specify CODECOV_TOKEN in codecov/codecov-action@v4

---

mne/conftest.py
mne/source_space/tests/test_source_space.py

should prevent pytest warnings like this one:
```
======================================== warnings summary ========================================
mne/conftest.py:836
/opt/mne/python/mne/conftest.py:836: PytestRemovedIn9Warning: Marks applied to fixtures have no effect
See docs: https://docs.pytest.org/en/stable/deprecations.html#applying-a-mark-to-a-fixture-function
@pytest.fixture(scope="session")
../../mambaforge/envs/mnedev/lib/python3.11/site-packages/_pytest/mark/structures.py:357
/opt/mambaforge/envs/mnedev/lib/python3.11/site-packages/_pytest/mark/structures.py:357: PytestRemovedIn9Warning: Marks applied to fixtures have no effect
See docs: https://docs.pytest.org/en/stable/deprecations.html#applying-a-mark-to-a-fixture-function
store_mark(func, self.mark)
-- Docs: …
```

don't put pytest marks on test fixtures

---

doc/changes/devel/12430.bugfix.rst
doc/changes/names.inc
mne/_fiff/meas_info.py
mne/io/snirf/_snirf.py

Reformats channel and detector lookup from array based to dictionary based. Removes incorrect assertions that every detector and source must have data associated with every registered optode position.
Example: Fixes #12429.
Reformats channel and detector lookup from array based to dictionary based. Removes incorrect assertions that every detector and source must have data associated with every registered optode position.

Remove incorrect assertions in snirf parsing

---

mne/report/report.py

Very minor change -- just omit nan rather than putting `NaN` in epoch event count report sections, makes things more readable. For example:
| main | PR |
| -- | -- |
| ![Screenshot from 2024-02-16 15-24-51](https://github.com/mne-tools/mne-python/assets/2365790/6fce19e9-c3b0-4f6c-a032-43c7276d8c1d) | ![Screenshot from 2024-02-16 15-25-00](https://github.com/mne-tools/mne-python/assets/2365790/09d51901-e274-4d94-9ab1-54727a9e5b76) |
Don't think this warrants a changelog entry since it's so minor.

FIX: na_rep for reports

---

mne/channels/channels.py

Adds missing doc info forgotten in a recent PR.

DOC: add missing info to interpolate bads docstring

---

doc/changes/devel/12456.bugfix.rst
mne/io/brainvision/brainvision.py

I recently came across a BrainVision file, which contains a channel `SpO2` (peripheral oxygen saturation) with a unit `%`. However, reading this file raises a `configparser.InterpolationError`, because by default `configparser.ConfigParser` uses `interpolation=configparser.BasicInterpolation` (see [here](https://docs.python.org/3/library/configparser.html#interpolation-of-values)). This means that it uses percent-based interpolation, e.g. it replaces `%(some_dir)` with the value of the variable `some_dir` (defined elsewhere in the config file).
I am pretty sure that BrainVision header files do not contain such format strings, and therefore, I suggest that we disable interpolation when parsing this file. That way, channels can be specified to have a unit `%`.

Disable interpolation in BrainVision config parser

---

doc/changes/devel/12451.bugfix.rst
doc/changes/devel/12451.dependency.rst
mne/conftest.py
mne/datasets/__init__.pyi
mne/datasets/_infant/__init__.py
mne/epochs.py
mne/fixes.py
mne/io/base.py
mne/io/fiff/tests/test_raw_fiff.py
mne/tests/test_epochs.py
mne/utils/check.py
pyproject.toml

In https://github.com/mne-tools/mne-bids-pipeline/issues/852 there is a bug where BIDSPath-based files were being written as:
```
sub-155_task-tiwm_proc-ica_split-01_split-01_epo.fif
```
This is because a mne-bids-pipeline naively did something like:
```
fname = BIDSPath(..., split="01")
epochs = read_epochs(fname)
...
epochs_out.save(fname.copy().update(proc="something))
```
but it needed to have `split=None` in the `update` call to avoid the double `_split-01_split-01`.
This is because currently MNE-Python takes `fname`, converts it to a `pathlib.Path` (automatically via dunder `BIDSPath.__fspath__`, which is an alias for `str(BIDSPath.fpath)`), *then* checks to see if splits need to be done, and if so appends `_split-01` while writing. So you end up with a filename …

BUG: Fix bug with BIDS split saving

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
doc/changes/devel/12461.other.rst
doc/changes/names.inc

Fixes #12460 (also related to #12316). 
Such a simple fix I thought I should probably just implement it. Hope that's appropriate!

Fix dead links to contribution guidelines

---

doc/changes/devel/12463.newfeature.rst
mne/decoding/base.py
mne/decoding/search_light.py
mne/io/neuralynx/neuralynx.py
mne/io/neuralynx/tests/test_neuralynx.py

Fixes #12404.
So far, `read_raw_neuralynx()` did not propagate online filter information (highpass/lowpass) or acquisition date from the .ncs file headers to relevant `RawNeuralynx().info` fields. The challenge is that filter params can be different across .ncs files/channels in the dataset.
For each .ncs file, it reads in the lowpass/highpass freqs and then stores, conservatively, the highest highpass freq and the lowest lowpass frequency as the dataset frequencies. If settings are non-uniform across channels and there's a channel with no online filters, then it assumes nyquist as the highpass value and 0 as the lowpass value.
A small test asserts are added in `test_neuralynx()` to test that `info` fields are correctly populated on the testing dataset (has online filter applied).

store online filter freqs and meas_date to from .ncs headers in `RawNeuralynx.info`

---

doc/changes/devel/12470.bugfix.rst
mne/viz/_brain/_brain.py

I guess this got lost at some point. `mne.viz.Brain.add_text` should by default use `_fg_color` for the color of the text, but didn't and defaulted to always be black, even when the background color of the figure is black.

Fix default color of mne.viz.Brain.add_text

---

doc/changes/devel/12450.other.rst
mne/export/_brainvision.py

I think it makes sense to maintain helper functions used to prepare input for `pybv` from `Raw` objects in MNE instead of pybv. See https://github.com/bids-standard/pybv/pull/120.
BTW, the test does not compare annotations in the original and exported/imported file, probably because our BrainVision reader does not support channel-specific markers yet?

Include helper functions from pybv

---

doc/changes/devel/12462.newfeature.rst
examples/preprocessing/epochs_metadata.py
mne/epochs.py
mne/tests/test_epochs.py
tutorials/epochs/40_autogenerate_metadata.py

This makes it possible to auto-generate metadata in time windows of varying duration, e.g., from a stimulus cue to a participant's response. Here, the response might occur at different times in every epoch. Now, one can specify `tmax="response"` in this case, and capture all events from `tmin` until the response for metadata generation. I imagine this to be particularly useful for MNE-BIDS-Pipeline (in fact, I'm already using this feature in my personal pipeline branch)

MRG: Allow `tmin` and `tmax` in `mne.epochs.make_metadata()` to accept strings

---

doc/changes/devel/12481.bugfix.rst
mne/io/eyelink/_utils.py

closes #12480
the new parameter set is also not perfect:
`direction=nearest` can lead to duplicating samples (as a sample on an uneven ms is equally distanced to the previous and subsequent millisecond). you can see this behavior running the simplified example code in the issue.
but i think this is better than `forward/backward` which does not duplicate samples, but works worse with sfreqs < 500 Hz, as it can shift samples in the wrong direction

fix merge_asof usage in read_raw_eyelink()

---

doc/changes/devel/12483.bugfix.rst
mne/viz/backends/_qt.py
mne/viz/backends/_utils.py

See https://github.com/mne-tools/mne-qt-browser/pull/233#issuecomment-1978881862, but in short:
1. Setting the global `QIcon.setThemeSearchPaths` to *only* our path is not compatible with other bits of software like mne-qt-browser and MNELAB
2. Instead, prepend our path
3. When calling `QIcon.fromTheme`, ask for the correct icon name but also provide a fallback in case the user has switched to a theme name that does not provide the correct icons. In MNE-Qt-browser and MNE we provide support for "light" and "dark" and I checked to make sure these work concurrently (they seem to at least!)
@cbrnr feel free to see if this helps with MNELAB

MAINT: Play nicer with themes

---

doc/changes/devel/12489.bugfix.rst
mne/utils/misc.py
mne/utils/tests/test_misc.py

Reported on the forum here: https://mne.discourse.group/t/error-when-trying-to-plot-projectors-ssp/8456
MWE: 
```
from mne import read_proj
from mne.io import read_info
from mne.viz import plot_projs_topomap
directory = Path.home() / "Downloads"
info = read_info(directory / "test-info.fif")
projs = read_proj(directory / "test-proj.fif")
plot_projs_topomap(projs, colorbar=True, vlim="joint", info=info)
```
Dataset: [test-projs.zip](https://github.com/mne-tools/mne-python/files/14557013/test-projs.zip)
------------
I'm not sure if this is the best fix as I'm not familiar with the channel name format of old vectorview system and of CTF system; thus I'm not certain about the intended purpose of `_clean_names`.

Fix cleaning of channel names which can create duplicate for non vectorview or CTF systems

---

mne/viz/backends/_utils.py

Fixes https://github.com/mne-tools/mne-qt-browser/issues/234. This sets the app icon of the MNE Qt Browser only if it has not already been set (by e.g. MNELAB).

Do not set browse raw icon when app icon already exists

---

doc/changes/devel/12510.newfeature.rst
mne/export/_edf.py
mne/export/tests/test_export.py
mne/utils/docs.py

Fixes #12493 by adding `physical_range="channelwise"`. The default behavior remains `physical_range="auto"`, which sets the physical range per channel *type*. However, in some cases where channels vary wildly in their ranges (mainly due to different offsets), which is often the case if the amplifier used no DC HP filter (e.g. Biosemi), setting individual physical ranges per channel ensures that each channel uses the maximum resolution afforded by the EDF format (only 16 bits). This seems to be perfectly compatible with the EDF standard (please correct me if I'm wrong), but I've added a note that some tools might be incompatible with such EDF files.

Add `physical_range="channelwise"` for EDF export

---

doc/changes/devel/12518.newfeature.rst
mne/io/edf/edf.py
mne/io/edf/tests/test_edf.py
mne/utils/docs.py

This pull request addresses an issue with handling EDF/BDF/GDF files that contain channels with duplicate names. Previously, channels with duplicate names were assigned a suffix (-N) after the process of including/excluding channels, which made it impossible to selectively include or exclude specific instances of these channels.
The proposed solution is to apply the `_unique_channel_names` function before the inclusion/exclusion process. Additionally, the original channel names (`orig_ch_names`) are now stored in `Raw._raw_extras`. This inclusion is particularly useful as it allows users to determine whether channel names have been modified and facilitates a more detailed examination of the raw data alongside other contents of `_raw_extras`.
This modification could impact existing …

Add exclude_after_unique option to mne.io.read_raw_edf/read_raw_edf to search for exclude channels after making channel names unique

---

tools/install_pre_requirements.sh

numexpr just cut a 2.0-compatible release so we should be able to reenable `python-picard` installation

MAINT: Reenable picard in pre testing

---

README.rst

There appears to have been a change at some point with how Github renders badge links in rst files. 
On main, in the table of badges and links, there are now trailing underscores rendered, and clicking on the badges no longer directs to the desired link, but instead to the image file. 
This PR updates the approach for setting the links for the badges, using the :target: operative, which updates the links to direct to the badges and makes the badges work as previously.

Update README badge links

---

azure-pipelines.yml
mne/fixes.py
mne/proj.py
tools/install_pre_requirements.sh

1. Slight tweaks to `proj` logging to make it clear how many epochs are dropped in `compute_proj_raw` and how much variance was explained by each projector created
2. Put `statsmodels` back in pip-pre because their wheels should be back up now

MAINT: Reinstall statsmodels and improve logging

---

mne/_fiff/pick.py
mne/_fiff/tests/test_pick.py
mne/channels/channels.py
mne/cov.py
mne/forward/forward.py
mne/time_frequency/csd.py
mne/utils/docs.py

MAINT: Complete API change of ordered

---

mne/viz/_3d_overlay.py
mne/viz/backends/_pyvista.py

While doing `git grep FutureWarning` I was struck by how many places we catch potential PyVista warnings. I suspect these are from early days of PyVista so I'm going to remove them and hopefully things are okay. If they're not, hopefully we can use more targeted ignores. If not, then we can at least use a `with _pyvista_context()` to DRY the code a bit, and ideally have more targeted use of the context (rather than having tens of lines inside it!).
Once we merge this in a follow-up PR I'll add it to `git-blame-revs-ignore` since it's 95% whitespace changes.

MAINT: Clean up PyVista contexts

---

doc/changes/devel/12535.bugfix.rst
mne/io/base.py
mne/time_frequency/spectrum.py
mne/time_frequency/tests/test_spectrum.py

closes #12519 
For now, with the 1.7 release pending, @larsoner and I agreed that disallowing multitaper on Raws when there are `bad_*` annotations present (and `reject_by_annotation=True`) is the best way to go.
In the long term, we could make that combination actually work by adding a new param (`chunk_size` or so, analogous to `n_per_seg` in Welch) and basically doing a welch-MT combination (using multitaper for each chunk, then combining the estimates from each chunk at the end).  It's a bit complicated because (we think) you would need to aggregate across-chunks-within-taper first, and then agg across tapers afterward. (cc @mmagnuski who I think has done that for his research before / maybe even implemented in borsar?)

explicitly disallow multitaper in presence of bad annotations

---

mne/time_frequency/psd.py

follow-up to #12536
- corrects bug where weights were discarded for spans shorter than `n_per_seg` (the wrapped function actually just shrinks `n_per_seg` in those cases)
- reduces weights for long spans to the number of *used* samples (where we expect trailing samples to be discarded)

fix PSD weights handling when bad annotations present

---

mne/datasets/config.py
mne/preprocessing/tests/test_ica.py
mne/utils/numerics.py
mne/utils/tests/test_numerics.py
tutorials/preprocessing/80_opm_processing.py

Helps with https://github.com/mne-tools/mne-python/issues/11276. Should render a decent auditory inverse.
Once this is in, we can work on some of the other steps in #11276 like adjusting the dig, dev_head_t, and trans (somehow) by using the MRI fiducials to fix the definition of the head coordinate frame.

ENH: Improve OPM auditory dataset and example

---

pyproject.toml

Sphinx 7.3 causes all sorts of problems, see for example https://github.com/sphinx-gallery/sphinx-gallery/pull/1289 and related issues. For now let's pin to `<7.3`. Then hopefully we can release

MAINT: Pin Sphinx

---

doc/changes/devel/12561.bugfix.rst
mne/report/js_and_css/report.js

In `main`, clicking multiple times on the same TOC entry would cause the content to jump up and down.
`main`:
https://github.com/mne-tools/mne-python/assets/2046265/9a657572-ba18-41d1-b09b-3aab31c8f97e
This PR:
https://github.com/mne-tools/mne-python/assets/2046265/e9961786-df8f-4d24-93e7-53899d697261
Importantly, this fix still ensures that the URL in the location bar gets updated.

In `Report`, fix scrolling when clicking on the same TOC entry multiple times

---

doc/conf.py

This fixes the width of all social icons to 25px (previously, only the Discord icon was 25px wide, whereas the other icons were 18px wide). I'm also removing the Twitter (X) social icon to increase horizontal space in the navbar. Finally, I've moved the GitHub logo all the way to the right to make it stand out more.

Try fixed-width social icons on website

---

doc/conf.py
doc/sphinxext/mne_doc_utils.py
pyproject.toml

Fix for latest Sphinx leveraging https://github.com/sphinx-gallery/sphinx-gallery/pull/1289
The solution is just to move a bunch of code to `sphinxext/mne_doc_utils.py` and then pass `"mne_doc_utils.<whatever>"` as `str` config values to `sphinx_gallery_conf`

MAINT: Fixes for sphinx 7.3

---

mne/io/persyst/persyst.py

The `order` argument is kw-only in NumPy >= 2 (https://numpy.org/devdocs/reference/generated/numpy.reshape.html), so this should hopefully fix the pip-pre tests.

Fix NumPy 2 related reshape in Persyst

---

.github/workflows/autofix.yml
doc/conf.py
examples/preprocessing/eeg_bridging.py
mne/preprocessing/_csd.py

Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/23902/workflows/ea14ec98-52fd-48f7-b359-61761835a068/jobs/65760 by just making the link more generic.

MAINT: Fix faulty links

---

doc/changes/devel/12597.bugfix.rst
mne/io/fil/fil.py
mne/io/fil/tests/test_fil.py

Fixes #12594.
Changes the ordering that the `info` struct is populated in `read_raw_fil` so that bad channels can be read straight from the `channels.tsv` file without raising an error.

FIX: `mne.io.read_raw_fil` handling of bad channels 

---

.github/ISSUE_TEMPLATE/bug_report.yml
doc/changes/devel/12600.other.rst
doc/changes/names.inc

Currently, there are 2 dead links in the issue template. This PR updates the links to their up-to-date locations.

Updated dead links in bug report issue template

---

doc/conf.py
mne/viz/_brain/_brain.py
pyproject.toml
tools/circleci_dependencies.sh

Draft until https://github.com/Carreau/intersphinx_registry/pull/5 lands then we can remove more lines
Basically upstreams the maintenance of links, and if they die we can update there and everyone benefits

MAINT: Use intersphinx_registry

---

doc/changes/devel/12605.bugfix.rst
mne/_fiff/pick.py
mne/viz/tests/test_topomap.py
mne/viz/topomap.py
mne/viz/utils.py

Example: Fixes #12599.
For a detailed explanation, please refer to the associated issue.
In essence, this PR addresses the issue where `animate_topomap()` fails to function with "csd" data. The proposed solutions in the issue include a straightforward addition of "csd" to the list of permitted `ch_types` for `animate_topomap`, as well as a more intricate approach that consolidates the `ch_type` selections from both `animate_topomap()` and `plot_evoked_topomap()`.
This PR implements the latter solution, as I find it to be the more comprehensive approach. However, I may have missed a specific reason for maintaining different channel selections in `animate_topomap()` and `plot_evoked_topomap()`. Should such reasons exist, I am open to adjusting this PR accordingly.

animate_topomap - CSD fix

---

doc/changes/devel/12612.bugfix.rst
mne/viz/_brain/_brain.py

This updates the logic that determines the ranges for the three sliders (fmin, fmid, fmax) on the left of a `Brain` figure. There was an overflow when the data is all zeros (`np.log10(fmax)`) which this PR fixes by using `np.log10(max(fmax, 1e-30))` instead. While I was there, I noticed that the minimum and maximum values for the sliders were set based on the `fmin` and `fmax` of the current timepoint instead of the entire data. Finally, on second thought, the minimum value for the sliders should always be `0`, that makes a lot more sense to me than capping it to `fmin`.
To check out the new behavior:
```python
import mne
path = mne.datasets.sample.data_path()
stc = mne.read_source_estimate(path / "MEG/sample/fsaverage_audvis-meg")
brain = stc.plot("fsaverage", hemi="both", …
```

Fix Brain slider ranges

---

mne/_fiff/meas_info.py

A minor clean-up, I got mislead by the line `info = self if isinstance(self, Info) else self.info` to believe I could do `'eeg' in info`, which is (1) not working and (2) too difficult to add support for since the default `__contains__` method from dictionary is actually used through the codebase.

Clean-up __contains__ code and add comment for Info

---

doc/changes/devel/12609.bugfix.rst
doc/changes/names.inc
mne/stats/cluster_level.py
mne/stats/tests/test_cluster_level.py
tools/dev/ensure_headers.py

No ref, only a post in the forum
In mne.stats.cluster_level.py :
The use of TFCE with large 2D data implied a huge amount of memory because of the creation of as many boolean arrays of the same size of the data as the number of data points (with TFCE, each point is considered as a cluster - consisting of a single point - and need an array to describe it). For this case, I replace the large boolean array by a single index, and removed the clusters output when it was not necessary.
It is my first ever PR, all comments are welcomed

Permutation cluster test with TFCE: improvement of speed and memory usage in 2D

---

doc/changes/devel/12616.bugfix.rst
mne/channels/channels.py
mne/time_frequency/tests/test_tfr.py

`EpochsTFR.add_channels()` is currently broken, since it adds the objects in the wrong dimension (0, but should be 1). I think this should be backported if possible.

Fix `EpochsTFR.add_channels()`

---

doc/conf.py
pyproject.toml

c.f. https://github.com/Carreau/intersphinx_registry/commit/9aa7ec5f934d5215dad5e9673d48d2bbcebf312d
Reported upstream on commit comments to avoid API breaks on keyword-only arguments. I'm not pinning the version here as I'm not confident the version schema in `intersphinx_registry` will not change again.

Fix intersphinx_registry API break

---

mne/datasets/utils.py

Should help with situations where `osf.io` is slow to respond like in https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/4566/workflows/9b8fd064-fe8c-4d1d-a30b-fa01000777f2/jobs/66642 for example. There it works after repeated retries of the job, but setting this to 15 instead of the default (which appears to be 5 based on the traceback).

MAINT: More lenient timeout for downloader

---

doc/changes/devel/12633.bugfix.rst
mne/time_frequency/csd.py
mne/time_frequency/tests/test_csd.py

Discussed in call with @larsoner & @wmvanvliet.
Currently, computing the CSD with the `csd_multitaper`, `csd_fourier`, `csd_array_multitaper`, or `csd_array_fourier` functions of the `time_frequency` module will return a `CrossSpectralDensity` object whose frequencies do not match the `fmin` and `fmax` parameters supplied to the functions.
E.g. calling the functions with `fmin=5, fmax=10` could be expected to return a CSD object with frequencies `[5, 6, 7, 8, 9, 10]` (assuming a 1 Hz resolution). Instead, the following frequencies are returned `[6, 7, 8, 9]`.
This occurs because of the logic used to generate the internal frequency mask:
```
orig_frequencies = rfftfreq(n_fft, 1.0 / sfreq)
freq_mask = (orig_frequencies > fmin) & (orig_frequencies < fmax)
```
As such, the `fmin` and `fmax` …

[BUG] Cross-spectral density missing frequencies

---

.github/workflows/circle_artifacts.yml

The redirector has (finally!) been migrated to somewhere more official, should just work but let's see!

MAINT: Update action [skip azp]

---

doc/changes/devel/12649.newfeature.rst
mne/epochs.py
mne/tests/test_epochs.py
mne/utils/docs.py

Requested by a colleague in Geneva for sleep study epochs.
Adds the argument `'random'` to `mne.epochs.equalize_epoch_counts` to randomly select epochs.

Add equalization of epochs randomly

---

doc/changes/devel/12650.other.rst
doc/changes/names.inc
doc/help/faq.rst
mne/utils/docs.py

This update revises the **documentation** sections related to the `decim` parameter in `mne.Epochs` and the `mne.Epochs.decimate` function. It adds specific recommendations for applying a low-pass filter based on the Nyquist criterion to prevent aliasing artifacts when decimating data.

Enhance documentation on decimation filtering to prevent aliasing

---

doc/changes/devel/12655.newfeature.rst
doc/changes/devel/newfeature.rst
mne/viz/_3d.py
mne/viz/tests/test_3d.py
tools/install_pre_requirements.sh

Pretty straightforward PR to add support for passing `axes` when calling `plot_head_positions(..., mode="field")`.
Cleaned up tests and added a kw-only `*` in there while I was changing code anyway.

ENH: Support axes arg for field mode

---

doc/changes/devel/12664.other.rst
mne/decoding/ssd.py

Discussed with @drammock: https://github.com/mne-tools/mne-connectivity/pull/193#discussion_r1638760912
The [`fit()`](https://mne.tools/dev/generated/mne.decoding.SSD.html#mne.decoding.SSD.fit) method of the SSD class has argument `y` which is unused, but retained for compatibility with scikit-learn. Suggestion is to rewrite this entry of the docstring to make it clearer that `y` is not used.

[DOC] Make SSD fit docstring clearer

---

doc/changes/devel/12661.bugfix.rst
mne/io/edf/edf.py
mne/io/edf/tests/test_edf.py

Addresses the most urgent issue in #12643. The warning was incorrectly emitted because there was a bug with iterating over selected channel indices.
Note that I still don't know if the behavior is actually correct or not, so this needs to be fixed in a follow-up PR. However, fixing the warning is more important, and I'd appreciate if we pushed a hotfix release with a backport soon.

Fix EDF/BDF filter warning bug

---

.github/workflows/check_changelog.yml
.github/workflows/release.yml

Now that backports are done by PR it'll be nice to have checks run against them in case we want to pay attention to them. Conversely I think we don't need the changelog checker.

MAINT: Tweak which branches actions run on

---

doc/sphinxext/mne_doc_utils.py
tools/circleci_dependencies.sh

There are (only!) two NumPy 2.0 compatibility problems showing up in our CircleCI builds:
```
../examples/io/read_neo_format.py failed leaving traceback:
File "/home/circleci/project/examples/io/read_neo_format.py", line 18, in <module>
import neo
File "/home/circleci/python_env/lib/python3.10/site-packages/neo/__init__.py", line 15, in <module>
from neo.core import *
File "/home/circleci/python_env/lib/python3.10/site-packages/neo/core/__init__.py", line 35, in <module>
from neo.core.block import Block
File "/home/circleci/python_env/lib/python3.10/site-packages/neo/core/block.py", line 12, in <module>
from neo.core.container import Container, unique_objs
File "/home/circleci/python_env/lib/python3.10/site-packages/neo/core/container.py", line 13, in …
```

NumPy 2.0 compat problems in doc build

---

doc/changes/devel/12676.bugfix.rst
mne/export/_edf.py
mne/export/tests/test_export.py

Fixes #12654.
Changes how `mne.export.export_raw(..., fmt='edf')` handles data that cannot be segmented into equal-length data blocks. The original zero-padding is not optimal for uncentered data and may unexpectedly enlarge the physical range. Here, zero-padding is replaced with `np.pad(array, pad_width, mode='edge'`. The last available value in each channel will be used to pad the data. It also adds a "BAD_ACQ_SKIP" annotation to denote the padded data.
Corresponding tests also added.

Change EDF zero-padding to edge-padding with annotation and test

---

.github/workflows/tests.yml

`macos-latest` has now been promoted to macOS 14 running natively on Apple Silicon.

Ensure we're testing macOS on Intel machines, too

---

doc/changes/devel/12687.bugfix.rst
mne/io/eyelink/_utils.py
mne/io/eyelink/tests/test_eyelink.py

FIX: Gracefully handle missing datetime in Eyelink File

---

doc/changes/devel/12697.other.rst
mne/utils/docs.py
mne/viz/evoked.py
mne/viz/tests/test_evoked.py

Aims to address the 2 following forum posts:
- https://mne.discourse.group/t/units-before-and-after-compute-current-source-density/8897/4
Document better the valid keys of the dictionary.
- https://mne.discourse.group/t/cannot-modify-y-axis-limits-for-evoked-plot-joint-function/9021/2
Validate the type of the argument to prevent passing tuples.
And a bunch of style improvements through the addition of missing double backticks around values.

Improve documentation of ylim argument through Evoked plotting function

---

tools/circleci_dependencies.sh
tutorials/preprocessing/70_fnirs_processing.py

Let's see if this fixes:
https://app.circleci.com/pipelines/github/mne-tools/mne-python/24519/workflows/d7b1e478-c51f-46e3-96c4-259b5be3b627/jobs/67052
It should, in which case we can wait for https://github.com/pyvista/pyvista/pull/6356 to be merged, then change this to use the `main` branch of PyVista, which would have caught this months ago *before* they cut 0.44.

MAINT: Fix doc build

---

.circleci/config.yml
doc/conf.py
doc/sphinxext/mne_doc_utils.py
mne/report/report.py
mne/report/tests/test_report.py
tools/circleci_bash_env.sh
tools/circleci_download.sh

In theory this should make our doc build quite a bit faster.
1. Switch to a machine executor which should give us ~15GB memory instead of 8GB. This will also move to ubuntu-24.04 so might need a bit of tweaking to get packages etc. correct, we'll see!
2. Use the new [Sphinx-gallery parallel building](https://github.com/sphinx-gallery/sphinx-gallery/pull/877) with 4 jobs (when running a full build) to hopefully speed up doc builds. Last build time was ~2.5h so hopefully this gets us closer to 1h. I'm optimistic based on looking at the CPU usage of the last full `main` build was mostly at 25% (and the peaks we can squash by setting `OPENBLAS_NUM_THREADS=1` from where it was at `4`):
4. Directly copy output report files to the output folder rather than use `copyfiles` -- not sure why we did …

ENH: Parallel example execution in doc build

---

mne/stats/erp.py

In #12707, I forgot to include a license header in the source.

Add license header to mne.stats.erp

---

examples/visualization/evoked_topomap.py
tutorials/machine-learning/50_decoding.py

fixes the erroneous `sphinx_gallery_thumbnail_number = 5` header in the examples, see here: https://mne.tools/stable/auto_examples/visualization/evoked_topomap.html#plotting-topographic-maps-of-evoked-data

DOC: do not use sphinx gallery comment as section header

---

pyproject.toml

needed for datetime.date support; otherwise writing to hdf5 will fail sometimes (e.g., the nirx tests; noticed when looking into https://github.com/mne-tools/mne-nirs/issues/543, not sure why that didn't surface in #12720)
cc @larsoner

pin h5io to >= 0.2.4

---

tutorials/epochs/30_epochs_metadata.py

The tutorial looked like this before:
Now it looks like this:
The reason is that `Epochs.metadata` may be `None`, in which case all the Pandas methods won't work; hence, the type checker complains.

Add a type guard to the metadata tutorial

---

mne/channels/channels.py
mne/evoked.py
mne/html_templates/_templates.py
mne/preprocessing/ica.py
mne/report/report.py
mne/viz/_3d.py
mne/viz/ui_events.py

Makes the existing annotations much cleaner and more readable.

Remove need for `Union` and `Optional` type annotations in Python 3.9

---

doc/changes/devel/12724.bugfix.rst
examples/io/elekta_epochs.py
examples/visualization/topo_compare_conditions.py
mne/viz/topo.py

fixes #12723
The handling of the `ylim` parameter in `mne.viz.plot_evoked_topo` is currently weirdly converted into a list of lists, but then transposed... This PR changes it to just remain a dictionary and do away with conversions.

Simplify keeping track of ylim dictionary in _plot_topo

---

doc/install/installers.rst
doc/install/manual_install.rst
mne/preprocessing/ecg.py
mne/preprocessing/tests/test_ecg.py
mne/rank.py
pyproject.toml

The bulk of this has to do with us no longer packaging Spyder in our installers and adjusting the install docs (mostly) minimally to comply with this change. #10707 and #11615 for example ask for something more comprehensive and aren't meant to be addressed here. This does help a tiny bit (maybe!) with #10707 in the sense that it deduplicates some stuff. I also snuck in a couple of tiny single-digit-line changes to close three other issues:
1. Pinning `numpy<3`
2. Adding a note that `compute_rank` operates on data channels
3. Improving an error message
@hoechenberger for the Spyder stuff, think this is good enough?
Closes #12672
Closes #12705
Closes #11540
Closes #11482

DOC: Update install docs for Spyder

---

mne/_fiff/meas_info.py

I am important eye tracking data from a tobii device (XDF format), and kept running into this issue when trying to `set_channel_types`:
> KeyError: 0 (FIFFV_COIL_NONE)
After some digging, I found that there is a different function that I should call. With this PR I want to make this more obvious in the documentation. However, the above issue also points out that there is probably a bug when setting channel types for eye-tracking.

channel_types: add important note on eye-tracking

---

tools/get_minimal_commands.sh

As evidenced by this [mne-bids-pipeline PR](https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/4622/workflows/66058499-726d-4685-bba7-728c84593225/jobs/67932) working, we need this `\$` to avoid variable expansion. Basically having the bare `$` causes the `PATH` variable to be expanded *at the time of script running* when really we want it to run *whenever the BASH_ENV gets run* in subsequent steps. It prevents errors like [this](https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/4621/workflows/f56cca01-af93-4260-8595-ce867ccc04e0/jobs/67931).

BUG: Fix bug with CircleCI Path [skip azp] [skip actions]

---

doc/changes/devel/12754.bugfix.rst
mne/io/edf/edf.py
mne/io/edf/tests/test_edf.py

As reported here: https://mne.discourse.group/t/wrong-in-mne-io-read-raw-edf/9123/14
Refactors the loading of the measurement date with a bunch of `try/except` and removes the collection of un-used fields: `meas_id["study_id"]`, `meas_id["technician"]`, and `meas_id["equipment"]`.

Safeguard loading of meas_date in EDF files

---

doc/changes/devel/12730.bugfix.rst
mne/io/nirx/_localized_abbr.py
mne/io/nirx/nirx.py
mne/utils/docs.py

Add new param `encoding` to `read_raw_nirx`. Default ~~`None`~~ `"latin-1"` should be backward compatible. Also adds another strptime pattern (zh-locale appropriate) to check the meas_date against when reading the file.
Fixes https://github.com/mne-tools/mne-nirs/issues/543
Draft PR because I haven't added a test yet, and because IDK how many of our readers might need such functionality. Input welcome on that question.

add encoding parameter to read_raw_nirx

---

doc/changes/devel/12763.bugfix.rst
doc/changes/names.inc
mne/channels/channels.py
mne/channels/tests/test_channels.py

Fixes  #12762.
Avoids dropping all channels in an object by raising a ValueError with the message: `All channel(s) would be dropped.`

ENH: check for dropping all channels

---

doc/_static/style.css
doc/_templates/copyright.html
doc/_templates/sidebar-quicklinks.html

This PR:
- re-does the fixes to navbar icon colors from #12301 (CSS rule broke because fontawesome icons are now `<svg>` instead of `<i>` tags)
- fixes color contrast problems on sphinx-gallery page elements (closes #12750)
- fixes sidebar quicklink icon colors on dark theme
- fixes frontpage gallery text colors on dark theme
Does *not* address https://github.com/mne-tools/mne-python/issues/12750#issuecomment-2269424078 for which #12775 has been opened.

Website fixes

---

tutorials/stats-sensor-space/70_cluster_rmANOVA_time_freq.py

Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/24939/workflows/56cc382c-a845-4109-8d43-f2e54f79c483/jobs/67947. Basically the example assumes that there is exactly one good cluster, which is not best practice and seems to have been affected in this case by the random state somehow.

BUG: Fix bug with example

---

.github/workflows/credit.yml

Might need a few of these. Switching to 30 minute schedule so I can get feedback on the `pr` line sooner, and merging with [ci skip]

MAINT: Iterate faster on credit [ci skip]

---

doc/changes/devel/12801.newfeature.rst
mne/gui/_coreg.py
mne/gui/_gui.py

This will now work:
```
coreg = Coregistration(
raw.info,
subject,
subjects_dir,
)
coreg.fit_fiducials()
coreg.fit_icp(n_iterations=40)
coregistration(
subject=subject,
subjects_dir=subjects_dir,
inst=file,
trans=coreg.trans,  # previously, required the path to a file
block=True,
)
```

Add support for a Transform in the trans argument of the coregistration GUI

---

doc/changes/devel/12803.bugfix.rst
mne/_freesurfer.py
mne/source_space/_source_space.py
mne/utils/check.py

Related to: https://github.com/h5io/h5io/issues/113
I had several failures saving a forward model where the `mri` field was provided as a path object.
```
File "/mnt/Isilon/9003_CBT_HNP_MEEG/temp-mathieu/meg-eeg-fMRI/subject-03.py", line 237, in <module>
fwd.save(directory / "Sources" / "forward" / f"sub_{subject}-pos_{pos}-fwd.h5")
File "<decorator-gen-341>", line 12, in save
File "/pyvenv/mne/lib/python3.10/site-packages/mne/forward/forward.py", line 176, in save
write_forward_solution(fname, self, overwrite=overwrite)
File "<decorator-gen-345>", line 12, in write_forward_solution
File "/pyvenv/mne/lib/python3.10/site-packages/mne/forward/forward.py", line 903, in write_forward_solution
_write_forward_hdf5(fname, fwd)
File …
```

Cast paths to string before saving to h5

---

mne/annotations.py

minor fix of the docstr, as BDF and GDF are also supported, but not mentioned, see: 
https://github.com/mne-tools/mne-python/blob/0aae72dda030242d992866ce6d551206749474b2/mne/annotations.py#L1235-L1236

DOC: read_annotations also reads BDF and GDF

---

doc/changes/devel/12811.newfeature.rst
doc/changes/v1.8.rst
mne/_fiff/utils.py
mne/epochs.py
mne/io/base.py
mne/io/fiff/tests/test_raw_fiff.py
mne/io/tests/test_raw.py
mne/tests/test_epochs.py

Implements #12809.
Return filenames when saving files which might be splitted. Users can have access to the path of each split without additional code.

Return filenames on save

---

examples/io/read_neo_format.py
mne/_fiff/meas_info.py
mne/conftest.py

Almost all fields are safeguard behind an `if dict.get(...) is not None`, and yet I manage to hit one of the only one that was not during saving of a `RawArray` in a unit test  ;)

[MRG] Fix missing safety around device_info field

---

mne/datasets/config.py
mne/io/ant/ant.py
mne/io/ant/tests/test_ant.py
tools/vulture_allowlist.py

Improves functionality added in [#12792](https://github.com/mne-tools/mne-python/pull/12792)  
- Adds following meta information in `RawANT.info`:
- `'subject_info'` (`'his_id'`, `'first_name'`, `'sex'`, `'birthday'`)
- `'device_info'` (`'type'`, `'model'`, `'serial'`, `'site'`)
- `'meas_date'`
- Enables lazy data reading (i.e.`preload=False` argument) in `read_raw_ant()` 
This requires bumping up the `antio` version to `0.3.0.dev0`.

[MRG] Improves functionality of ANT Neuro reader

---

doc/changes/devel/12829.apichange.rst
mne/decoding/csp.py

Closes #12665.
In the `plot_filters` and `plot_patterns` methods used by the `CSP` and `SPoC` classes, adds a `FutureWarning` for the `average` parameter that it will be removed in v1.10.
Currently in the tests, `average` isn't called anywhere. Should I add a new test for the `FutureWarning`?

[API] Deprecate average parameter from CSP and SPoC plotting methods

---

doc/changes/devel/12827.other.rst
mne/decoding/csp.py
mne/decoding/ssd.py

Example: Addresses #12766.
Adds custom docstrings for the `fit_transform` method of the `CSP`, `SPoC`, and `SSD` classes of the `decoding` module. The docstrings now accurately reflect the parameters of the `fit` and `transform` methods for each class (previously used the generic docstring of `TransformerMixin`).

[DOC] Fix misleading `fit_transform` docstrings

---

mne/utils/config.py

Fixes #12790. Once the missing symbols get added to Cascadia Mono, we can enable Unicode on Windows as well.

Disable unicode symbols in `mne.sys_info()` on Windows

---

mne/channels/_standard_montage_utils.py
mne/channels/montage.py
mne/channels/tests/test_montage.py
tutorials/inverse/70_eeg_mri_coords.py

- follow up to #12830 
- see also #12837 
@larsoner a proper test to include would be to add to each pytest.parametrize item the expected channel names that the montage should contain. Do you think that's overkill, or should we do it?

hotfix elc reader

---

doc/changes/devel/12846.bugfix.rst
examples/visualization/eyetracking_plot_heatmap.py
mne/defaults.py
tutorials/io/70_reading_eyetracking_data.py
tutorials/preprocessing/90_eyetracking_data.py

closes #12756
- Updated `mne.defaults` so that eyegaze channels are expected to be radians and pupil size channels are expected to be meters. When specifying the scalings, I matched the scalings with other MNE channel types that have  a radians/meters unit (e.g. fnirs_fd_phase for radians, hbo/hbr for meters).
- Updated the eyetracking tutorials such that eygaze units are converted to radians as early as possible.
- I did not update the example [plot_eyetracking_heatmaps](https://mne.tools/stable/auto_examples/visualization/eyetracking_plot_heatmap.html#tut-eyetrack-heatmap). I'd have to play with the code a bit to make the heatmap overlay with the stimulus image (which is in pixels) nicely. Maybe a follow up PR?
- in this PR I did not demonstrate converting Eyelink Pupil size data to …

Use SI units for eyetracking data, update tutorials

---

doc/changes/devel/12850.bugfix.rst
mne/defaults.py

fixes #12849 
I actually need to simulate some pupil data in meters and  test this plotting function to see if the scalings make sense (we probably need to adjust them).

FIX: use meters for pupil SI, not moles

---

doc/changes/devel/12853.bugfix.rst
mne/viz/tests/test_topomap.py
mne/viz/topomap.py

Fixes #12852
Stops `colorbar=False` from being overwritten in `plot_psds_topomap()` (and also in e.g., `*Spectrum.plot_topomap()` which calls it).
Also includes a small unit test to check the `colorbar` flag isn't ignored.

[BUG] Fix ignored `colorbar` flag in `plot_psds_topomap()`

---

doc/Makefile
doc/_static/js/set_installer_tab.js
doc/_static/js/update_installer_version.js
doc/install/installers.rst

A collaborator recently asked me about uninstallation so I was reminded to do this.
Closes #12528
Closes https://github.com/mne-tools/mne-installers/issues/89

DOC: Document installer uninstallation

---

mne/io/brainvision/brainvision.py

This was not clear from the documentation before.

DOC: impedances may be obtained for BrainVision

---

doc/changes/devel/12844.other.rst
examples/datasets/limo_data.py
examples/preprocessing/epochs_metadata.py
mne/viz/misc.py
tutorials/clinical/60_sleep.py
tutorials/intro/10_overview.py
tutorials/preprocessing/70_fnirs_processing.py
tutorials/raw/20_event_arrays.py

- xref #12835 
@larsoner what do you think of this "low hanging fruit" improvement?
Using this MWE (if you checkout and install my branch here), this scales well to a number of 40 unique events. It looks a bit small in this PR preview, but on my screen it looks fine. Beyond scaling factor 2, it all gets wonky.
```python
import mne
events = np.arange(300).reshape(-1, 3)
if 1:
for i in range(10, 100, 10):
fig = mne.viz.plot_events(events[:i, :], show=True)
figsize = fig.get_size_inches()
print(f"previous was: n events: {i}, Figure size: {figsize}")
report = mne.Report("try")
report.add_events(events[:40, :], title="events", sfreq=100)
report.save("try.html", overwrite=True)
```

scale figsize in plot_events depending on n unique events

---

doc/changes/devel/12862.other.rst
mne/preprocessing/ica.py
mne/preprocessing/tests/test_ica.py

This is an "issue as PR", that also contains some commits from #12860 that can be ignored.
The main point that I would like to discuss is, that [`find_bads_muscle`](https://mne.tools/stable/generated/mne.preprocessing.ICA.html#mne.preprocessing.ICA.find_bads_muscle) is using three criteria to flag components as bad by muscle activity. However, two of these criteria require sensor positions to work.
I have a dataset without sensor positions available (and no option to add standard positions), and I would still like to run this function, using only the first criterion to flag channels.
In the diff below, I show that this is easily accomplished in principle. In practice I would much rather have **some** guidance in what components **may** be muscle related, than none at all.
What are your …

Let users run `find_bads_muscle` also when no sensor positions are available

---

mne/viz/misc.py

Follow up to:
- #12844 
Beyond 3 columns (75! unique event IDs), adding more columns just ends up being chaotic.

FIX: limit ncols to a reasonable max in plot_events

---

mne/preprocessing/ecg.py
mne/preprocessing/ica.py

btw: Does anyone know why the automatic ECG channel creation only works for MEG channels? It would be really nice/helpful to also support this for EEG channels.
With references like this one, it seems possible: https://doi.org/10.1016/j.cmpb.2019.105092

DOC: clean up ECG ICA docstrs

---

mne/io/fiff/raw.py
mne/io/fiff/tests/test_raw_fiff.py

Fixes https://github.com/mne-tools/mne-python/pull/12843#issuecomment-2380491528 @sappelhoff locally the MNE-BIDS `line_freq` test works for me. This is a within-release fix so no need for changelog update. This one is pretty trivial so I'll self-mark for merge-when-green.

BUG: Fix bug with Path casting

---

mne/html_templates/repr/_channels.html.jinja
mne/html_templates/repr/forward.html.jinja
mne/html_templates/repr/static/_channels.html.jinja
tutorials/forward/35_eeg_no_mri.py

Just noticed the mismatch, thought this would improve consistency. There is a slight change in behavior, in that in the HTML repr for Forward, the hover tooltip for channels used to be "show good channel names" and now is "click to open in popup" followed by the actual channel names (consistent with the Channels section in other HTML reprs).

make HTML repr for Forward match others

---

mne/io/base.py

@sappelhoff Is this better? c.f. https://github.com/mne-tools/mne-python/pull/12843#issuecomment-2402147170
Now:
```py
import mne
sampling_freq = 1000
times = np.linspace(0, 1, sampling_freq, endpoint=False)
sine = np.sin(20 * np.pi * times)
cosine = np.cos(10 * np.pi * times)
data = np.array([sine, cosine])
info = mne.create_info(
ch_names=["10 Hz sine", "5 Hz cosine"], ch_types=["misc"] * 2, sfreq=sampling_freq
)
raw = mne.io.RawArray(data, info)
a = Path.cwd() / "IDoNotExist.jpg"
raw.filenames = (a,)
raw.filenames = [a]
#path_to_file_that_exists = ...
#raw.filenames = [path_to_file_that_exists]
raw._filenames = (a,)
```

Cast tuple of filenames to list to improve error handling

---

doc/conf.py

trailing slashes for intersphinx base URLs on readthedocs.io are triggering redirection warnings. Most are fixable upstream in https://github.com/Quansight-Labs/intersphinx_registry/pull/34, except this one.

remove trailing slash from pybv base URL [ci skip]

---

.pre-commit-config.yaml
README.rst
pyproject.toml
tools/hooks/sync_dependencies.py

closes #12889 (supersedes)
The new pre-commit hook is added in 9d799c4b3e7cb6791ba1cc00c1cb31f42a38355c but was committed with `--no-verify` so that you can see its action separately in subsequent commit 4693515c75196eb923274e6265a81a7e9b90a87f

Sync README dependencies with pyproject.toml

---

doc/changes/devel/12909.bugfix.rst
mne/io/edf/edf.py

Fix GDF NumPy >= 2

---

doc/changes/devel/12911.bugfix.rst
mne/export/_edf.py
mne/export/tests/test_export.py

Currently, exporting to edf fails if one channel contains only constant values and `physical_range="auto"`, because `edfio` requires that (explicitly passed) physical minimum and maximum differ from each other ([link](https://github.com/the-siesta-group/edfio/blob/v0.4.4/edfio/edf_signal.py#L420-L423)). This requirement is suggested in Q8 in the [EDF FAQ](https://www.edfplus.info/specs/edffaq.html), because min == max leads to a division by zero when calculating the signal offset, which might cause an error when loading the file. This PR ensures that physical minimum and maximum are always different when using `physical_range="auto"`. For `physical_range="channelwise"`, `edfio` takes care of that , as `mne` passes no physical range to `edfio.EdfSignal`.

Allow exporting edf where a channel contains only constant values

---

.github/workflows/tests.yml
doc/sphinxext/mne_doc_utils.py
mne/conftest.py
mne/decoding/receptive_field.py
mne/decoding/tests/test_receptive_field.py
mne/stats/regression.py
mne/stats/tests/test_regression.py

Couldn't figure out why only the Azure pip-pre was failing, it was because `continue-on-error: true` was set which means the failed test in pip-pre was ignored because the `codecov` step after it succeeded :grimacing: 
Also the doc build is failing because of a new deprecation warning in selenium.
I expect this to fail with a sklearn error in the Linux pip-pre job. Once it does, I'll push a fix for that, then self-merge if it's trivial.

MAINT: Fix tests

---

mne/io/ant/ant.py

A couple of fixes thanks to a problematic file shared by ANT's support which go with https://github.com/mscheltienne/antio/commit/21406289b4784b0d8e35a1fb7f148eb7eb4a72d4 and https://github.com/mscheltienne/antio/commit/05e5ebb8a39a2567785fff2f10c146d3cbf28649
I didn't add any tests in `antio` for now as this file was strange with birthday partially set, sex set to `[`, and with this encoding issue that needs more attention/information for now.

Fix unit handling for µV and parsing of birthday in ANT format

---

doc/_templates/layout.html

a google search console report made me realize we've been doing canonical hints wrong. We had been telling crawlers that the stable docs homepage was the canonical version for *every page* in our docs. This fixes it so that the *corresponding* stable docs page is marked as canonical, e.g., https://mne.tools/**dev**/auto_tutorials/preprocessing/10_preprocessing_overview.html will now have https://mne.tools/**stable**/auto_tutorials/preprocessing/10_preprocessing_overview.html as its canonical version.

fix ref=canonical in HTML page headers

---

doc/changes/devel/12960.other.rst
tutorials/inverse/35_dipole_orientations.py

Based on [a discussion on the forum](https://mne.discourse.group/t/frequency-content-of-lcmv-beamformer-discrepancy/10511/2), it may be a good idea to mention these common gotchas/pitfalls when doing analyses in source space. Because we pool activity across dipoles by default, source activity is always positive. Hence, don't expect sine waves to remain sine waves, don't expect averaging across multiple epochs to produce a nice evoked response (noise cancelling out).
Also, some of the figures needed some fixes to render properly.

Some additions to the dipole orientation tutorial.

---

doc/changes/devel/12962.bugfix.rst
mne/source_space/tests/test_source_space.py
mne/tests/test_source_estimate.py
mne/utils/misc.py

Fix units in sizeof_fmt

---

doc/changes/devel/12955.bugfix.rst
doc/changes/devel/12955.newfeature.rst
doc/changes/names.inc
doc/conf.py
mne/io/base.py
mne/io/fiff/raw.py
mne/io/tests/test_raw.py

Fixes: #12954
Now the duration calculation takes into account the length of the last sample, by calculating the duration in seconds based on the number of samples divided by the sampling frequency.
Instead of using `len(self.times) / self.info['sfreq']` as suggested in the bugfix, I used `self.n_times / self.info['sfreq']` instead, as `self.times` is calculated from the same info `self.n_times` is calculated from, but `self.n_times` seems to be "cheaper".
I humbly suggest reviewing commit by commit.

Add BaseRaw.duration property and fix duration calculation for BaseRaw "repr/html" display

---

mne/_fiff/meas_info.py
mne/_fiff/proc_history.py
mne/_fiff/tests/test_meas_info.py
mne/_fiff/write.py
mne/io/fiff/tests/test_raw_fiff.py
mne/io/tests/test_raw.py
mne/utils/_testing.py
mne/utils/numerics.py

Closes #12963
Within-cycle fix so no need for changelog entry.
Our anonymization tests were a bit lacking so changes ended up being a bit bigger than I expected.

BUG: Fix bug with anonymization

---

doc/changes/devel/12968.bugfix.rst
mne/io/edf/edf.py

I have EEG data that I  saved to EDF with MNE a long time ago (maybe 2 years ago). Reading that file back used to work, but I believe a regression/bug was introduced in #11952 . Specifically this block:
https://github.com/mne-tools/mne-python/blob/d810cc5977f95f76c3eb82db6b7003af68bd6176/mne/io/edf/edf.py#L826-L830
This code logic  assumed that patient hand info would be something like `"hand=1"` or `"hand=2"` but in my case it was `"hand=None"` which caused a `ValueError` because you cannot do `int('None')`.
This PR just wraps things in a try-except block to gracefully handle weird cases like mine.
I really don't know much about the EDF format, so cc'ing @paulroujansky as the author of https://github.com/mne-tools/mne-python/pull/11952. LMK if you think this looks reasonable to you!. …

FIX: gracefully handle bad patient info in edf reader

---

doc/changes/devel/12971.newfeature.rst
mne/io/eeglab/_eeglab.py

The `uint16_codec` argument for `mne.io.read_raw_eeglab()` is only used if the optional dependency `pymatreader` is installed. This PR adds support for this argument for the case when `pymatreader` is not installed and hence the base implementation via `scipy.io.loadmat()` is used.
Note that `uint16_codec` is an undocumented parameter of `scipy.io.loadmat()` (which is also used by `pymatreader`). However, since it seems to work in practice, I guess adding it should be fine.
This issue was originally reported in our forum [here](https://mne.discourse.group/t/why-is-the-uint16-codec-parameter-of-mne-io-read-raw-eeglab-not-passed-to-loadmat/10547/1).

Use `uint16_codec` argument

---

mne/channels/channels.py

channel order DOES matter if ordered=True (default)
- closes #12969

DOC: fix note in legacy pick_channels func

---

mne/decoding/transformer.py

I added these changes because the previous example was confusing in some ways, for example:
- what is SpatialFilter?
- what is _XDawnTransformer, and why do we use a private class here?
- the example [did not render](https://mne.tools/stable/generated/mne.decoding.Vectorizer.html) due to lack of `>>>`
How it was before this PR:
How it is [now](https://output.circle-artifacts.com/output/job/18c00058-093c-45c0-a4d6-374cee496619/artifacts/0/html/generated/mne.decoding.Vectorizer.html):

DOC: fix numpy docstr example Vectorizer()

---

mne/_fiff/reference.py
mne/_fiff/tests/test_reference.py

- fixes https://github.com/mne-tools/mne-python/issues/12959

do not log about using set_montage AGAIN if it has never been used

---

.github/workflows/tests.yml
azure-pipelines.yml
tools/azure_dependencies.sh
tools/install_pre_requirements.sh

This should work now that https://github.com/pyvista/setup-headless-display-action/pull/21 is in

MAINT: Unpin VTK

---

mne/io/ant/ant.py
mne/io/base.py
mne/io/kit/kit.py
mne/io/snirf/_snirf.py
mne/io/tests/test_raw.py
mne/preprocessing/ica.py
mne/preprocessing/tests/test_ica.py
mne/viz/raw.py

following https://github.com/mne-tools/mne-python/pull/12843
I think it'd be good to reduce the use of private attributes in our own code base as well, if we might as well use the public attribute.

remove some ._filenames uses in favor of .filenames

---

azure-pipelines.yml
doc/sphinxext/mne_doc_utils.py
pyproject.toml

The selenium workaround from #12928 is no longer needed, as an upstream fix has been released, and our CI is already pulling in the latest version:
https://app.circleci.com/pipelines/github/mne-tools/mne-python/25889/workflows/48bc89d6-279f-4b79-a579-b061f59c38af/jobs/69943?invite=true#step-118-9020_36

pin selenium and stop filtering its warning

---

doc/changes/devel/13007.bugfix.rst
mne/io/cnt/cnt.py
mne/io/cnt/tests/test_cnt.py

Fixes #13006
Closes #13005 
Currently all annotation descriptions are imported from event.StimType. This means all responses are recorded as 0, even when they should be read as a number representing the button the participant pressed. I correctly imported the response and appended `KeyPad Response` and `Keyboard Response` to the annotation because MNE does not differentiate explicitly between stimuluses and responses like Neuroscan does.

Fix cnt response

---

doc/development/contributing.rst

The section "Running the test suite" was labeled as `_run_tests` although the references are to `_run-tests`. For some reason, the _run_tests reference points to a similar section in the documentation of statsmodels. This glorious one-character PR fixes the bug and the link now works correctly.
I skipped the changelog entry for this tiny thing.

[BUG] Fix simple documentation bug

---

doc/changes/devel/13019.newfeature.rst
mne/viz/circle.py
mne/viz/tests/test_circle.py

This fixes [Issue 262](https://github.com/mne-tools/mne-connectivity/issues/262) in `mne_connectivity`.
I added a `fig.mne` `SimpleNamespace`, which holds the `Colorbar` for a circular plot. This allows users to directly access the `Colorbar` after creating a figure using `mne_connectivity.viz.plot_connectivity_circle`, which calls `mne.viz.circle._plot_connectivity_circle`. 
I will add something in the docstring of `plot_connectivity_circle` to describe this functionality and modify one of the examples to use it.

[ENH] Add fig.mne container for colorbar

---

.github/workflows/automerge.yml

Let bot PRs get marked automatically as merge-when-green. I can't think of a time so far that we haven't wanted this (or couldn't have lived with the result at least), and if something does accidentally get merged that we didn't want then it's easy enough to revert.

MAINT: Automerge for bot PRs

---

doc/changes/devel/13018.newfeature.rst
doc/sphinxext/related_software.py
mne/conftest.py
mne/io/base.py
mne/io/tests/test_raw.py
tools/circleci_dependencies.sh

Add `raw.rescale`

---

environment.yml
mne/io/ant/ant.py
mne/io/ant/tests/test_ant.py
mne/preprocessing/tests/test_fine_cal.py
mne/utils/check.py
mne/utils/tests/test_check.py
pyproject.toml
tools/circleci_dependencies.sh
tutorials/intro/70_report.py

Depends on https://github.com/conda-forge/antio-feedstock/pull/6#issuecomment-2547387329

Add support for different encoding in ANT neuro CNT format reader

---

README.rst
doc/changes/devel/13028.bugfix.rst
mne/time_frequency/tests/test_tfr.py
mne/time_frequency/tfr.py

Fixes #13027
Expands the logic for `EpochsTFRArray` default `drop_log` initialisation so `__getitem__()` works with default params.

Fix `EpochsTFRArray` default drop log initialisation

---

.github/workflows/tests.yml
.pre-commit-config.yaml
azure-pipelines.yml
environment.yml
mne/conftest.py
mne/decoding/tests/test_ssd.py
mne/gui/tests/test_gui_api.py
mne/tests/test_parallel.py
mne/viz/_brain/tests/test_brain.py
mne/viz/tests/test_evoked.py
mne/viz/tests/test_raw.py
pyproject.toml
tools/azure_dependencies.sh
tools/get_minimal_commands.sh
tools/get_testing_version.sh
tools/github_actions_env_vars.sh
tools/github_actions_test.sh
tools/hooks/update_environment_file.py
tools/install_pre_requirements.sh

Looking at our logs recently I was unhappy that some tests were skipped that I thought should be run on the given CI. So:
1. Add pytest hooks that optionally treat skips as errors based on `MNE_TEST_ALLOW_SKIP` (which defaults to not treating any skips as errors)
2. Set `MNE_TEST_ALLOW_SKIP` to reasonable values for a few CIs (Windows pip-pre, Ubuntu pip-pre, and Ubuntu conda)
3. Change some `>> $GITHUB_ENV` into `| tee -a $GITHUB_ENV` so that what we're storing gets printed (nicer CI debugging)
4. Remove a `junit_family` which is unneeded now that it's the default
5. Add some missing deps from some CIs
I expect this to fail due to some deps being missing, so I'll need to add one or two more or expand the `ALLOW_SKIP` regex to allow them (depending on which makes more sense). Ready for …

MAINT: Ensure limited set of tests are skipped

---

doc/changes/devel/13069.bugfix.rst
mne/conftest.py
mne/io/edf/edf.py
mne/io/edf/tests/test_edf.py

Fixes #12897.
When loading an EDF with mixed sample frequencies and using `preload=False` and then requesting a channel that has lower sample frequency than the maximum resulted in an `AssertionError`.
This Assertion was in place to make sure that enough samples were read, but only made sense when one of the channels of maximum sample frequency was loaded.
It can simply be removed as I don't think that the case can actually occur. Additionally, there is another check for zeros a few lines later that serves a similar purpose.

[FIX] Reading an EDF with preload=False and mixed frequency

---

doc/changes/devel/13067.bugfix.rst
mne/time_frequency/tests/test_tfr.py
mne/time_frequency/tfr.py

Fixes https://github.com/mne-tools/mne-python/issues/13023
When computing TFRs using the multitaper method, taper weights were not being applied to the tapered spectra when converting complex coefficients in to power.
This PR makes sure the taper weights are applied, along with unit tests.

[BUG] Fix taper weighting in computation of TFR multitaper power

---

doc/changes/devel/13067.bugfix.rst
mne/export/_export.py
mne/time_frequency/tests/test_tfr.py
mne/time_frequency/tfr.py
mne/utils/docs.py

@larsoner My attempt at a manual backport of #13067 due to some merge conflicts.
Also had to add some code from #12910 which ensured the correct weights were returned from `_make_dpss`, and removed part of a unit test that would no longer function (to do so would require API changes introduced in #12910).

Backport PR #13067 on branch maint/1.9 ([BUG] Fix taper weighting in computation of TFR multitaper power)

---

doc/changes/devel/12656.bugfix.rst
mne/export/_export.py
mne/forward/tests/test_make_forward.py
mne/preprocessing/tests/test_fine_cal.py
mne/utils/docs.py
tools/github_actions_dependencies.sh
tools/github_actions_env_vars.sh

Numba cut a new release that is 3.13 and NumPy 2.1 compatible, so let's use it in our 3.13 CI run. Still waiting on pyvista to get VTK 9.4 compatible so we can have 3D viz working there.

MAINT: Add Numba to 3.13 test

---

doc/changes/devel/13097.bugfix.rst
mne/io/eeglab/eeglab.py

Use a safe way to try and access `eeg.chaninfo["nodatchans"]`. Fixes #13094.

Fix EEGLAB import (nodatchans)

---

.github/workflows/tests.yml
azure-pipelines.yml
doc/changes/devel/13101.bugfix.rst
mne/conftest.py
mne/viz/evoked_field.py
mne/viz/tests/test_3d.py

Plotting evoked fieldlines on top of distributed source estimates is very cool:
But, `mne.viz.Brain` can use either `units="m"` or `units="mm"`. The `plot_evoked_field` function always assumed it would be kept at the default `units="mm"`. This PR makes it actually pay attention to the unit. Another bug fixed is that when plotting in millimeters, the helmet surface would be modified in place: `surf["rr"] *= 1000`. This causes trouble as now the surface will forever be upscaled and should you plot it again, it will be upscaled again. In this PR a `deepcopy()` is made first.

Take units (m or mm) into account when showing fieldmaps on top of brains

---

doc/changes/devel/13100.bugfix.rst
mne/io/brainvision/brainvision.py
mne/io/brainvision/tests/test_brainvision.py

Fixes #13095. This PR skips the first "New Segment" BrainVision marker, as it only contains the recording time (which is already available in `info["meas_date"]`). I decided to not do anything with subsequent "New Segment" markers, as such changes could be unexpected.

Skip first "New Segment" BrainVision marker

---

doc/changes/devel/13107.newfeature.rst
mne/_fiff/meas_info.py
mne/_fiff/tests/test_meas_info.py

- closes [#131004](https://github.com/mne-tools/mne-python/issues/13105)

add overwrite and verbose params to info.save

---

mne/_fiff/_digitization.py
mne/_fiff/constants.py
mne/_fiff/tests/test_constants.py
mne/channels/tests/test_montage.py
mne/transforms.py

Fixes bugs in mne-bids `main` introduced by #13083, see for example [here](https://github.com/mne-tools/mne-bids/actions/runs/13504084782/job/37729445482?pr=1376). Short fix would have been to just change a `.get(coord_frame)` to `.get(coord_frame, coord_frame)`, but then I realized we didn't fully test consistency of coord frame constant use. So this PR also cleans that up.
Notably there are some coordinate frames that AFAIK we never use, so those have been singled out a couple of places here. But critically I added some tests to make sure three private constants that we use in many places are now internally consistent. We could in principle include these, but it will bloat all `_check_option` errors that people see so I don't see much value. And these tests/comments will make it easy to …

BUG: Fix bug with coord frame reading

---

doc/changes/devel/13122.bugfix.rst
doc/changes/devel/13123.bugfix.rst
doc/changes/names.inc
mne/chpi.py

Fixes #13122 👍 : Insufficiently sensitive head movement detection for chpi extraction.
This implement fixes the issue of waiting for all the head coordinates to change from a previous frame in order to detect change. It'll now detect changes even for any head coordinate changes.
Changes were made according to the requirement in the issue.  **{ np.all --> np.any }**
This is my first PR to MNE-Python repository, aimed towards contributing in GSOC'25.
Please let me know if there are any further requirement for changes in the current implementation..

 Solving issue #13122: Aiming to achieve better sensitivity of head movement detection for chpi extraction

---

pyproject.toml

sphinxcontrib-towncrier was updated and released so now we can remove the pin. (Note all releases of theirs on PyPI have an alpha tag so it should be the best we can do to pin to `>=` the currently released "alpha" version.) Will mark for merge-when-green once I make sure the dev whats new looks okay.

MAINT: Update towncrier dep

---

doc/sphinxext/mne_doc_utils.py
mne/event.py
mne/io/eyelink/_utils.py
mne/io/eyelink/tests/test_eyelink.py
tutorials/preprocessing/90_eyetracking_data.py

Workaround for #13139
I also realized that we haven't tried culling our list of warning ignores in a while, so I got rid of all of them and pushed a `[circle full]` so we could see what fails, and just add back the ones we need.

BUG: Fix bug with parallel doc build

---

doc/_includes/forward.rst
doc/documentation/cookbook.rst

This PR:
- puts an rST table caption all on one line, which fixes an irregularity in how mkdocs parses the `objects.inv` file. This will enable intersphinx-like xrefs from the MNE-BIDS-Pipeline docs into MNE-Python docs. needed for https://github.com/mne-tools/mne-bids-pipeline/pull/1066
unrelated tweaks, since I was mucking in that file already:
- removes trailing periods from a couple table captions
- utilizes the preferred docutils `:name:` syntax for defining tables as xref targets

Fix intersphinx

---

doc/changes/devel/13145.bugfix.rst
mne/io/egi/events.py
mne/io/egi/tests/test_egi.py

I have a few MFF files which contain a corrupt XML file (a tag didn't close properly).
This PR uses defensive programming to gracefully handle the scenario, while also providing more information to the user about the XML file that couldn't be parsed.
```python
import mne
import shutil
egi_fname = mne.datasets.testing.data_path() / "EGI" / "test_egi.mff"
test_fname = shutil.copytree(egi_fname, Path("./bad_xml_egi.mff").resolve())
bad_xml = test_fname / "bad.xml"
bad_xml.write_text("<bad>")
raw = mne.io.read_raw_egi(test_fname)
test_fname.unlink()
```
```
Reading EGI MFF Header from /Users/scotterik/devel/repos/mne-python/bad_xml_egi.mff...
Reading events ...
File ~/.local/share/uv/python/cpython-3.10.16-macos-x86_64-none/lib/python …
```

FIX: Gracefully handle bad XML files in EGI reader

---

mne/io/egi/egimff.py
mne/io/egi/tests/test_egi.py

The EGI MFF reader already tries to account for the case where a sensor coordinate file (`coordinates.xml`) is missing:
https://github.com/mne-tools/mne-python/blob/a5073bf977b73e9981a2222cc546c93081914a7d/mne/io/egi/egimff.py#L275-L284
So if this variable `mon` can be `None`, then _all_ the code dealing with it should be nested inside the if-block below: 
https://github.com/mne-tools/mne-python/blob/a5073bf977b73e9981a2222cc546c93081914a7d/mne/io/egi/egimff.py#L449
https://github.com/mne-tools/mne-python/blob/a5073bf977b73e9981a2222cc546c93081914a7d/mne/io/egi/egimff.py#L488-L491
I also updated a test to simulate this case.

FIX: Missing coordinates.xml in MFF file

---

mne/parallel.py
mne/tests/test_filter.py

I noticed lately that even with `n_jobs=None` (which should really be equivalent to `n_jobs=1`) I would see parallel stuff in logging:
```
FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal lowpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Upper passband edge: 40.00 Hz
- Upper transition bandwidth: 10.00 Hz (-6 dB cutoff frequency: 45.00 Hz)
- Filter length: 331 samples (0.331 s)
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.6s
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed:    1.4s
[Parallel(n_jobs=1)]: Done 287 tasks      | elapsed:    2.4s
[Parallel(n_jobs=1)]: Done 431 out of 431 | …
```

BUG: Fix bug with not short-circuiting n_jobs=1

---

mne/_fiff/meas_info.py
mne/dipole.py

This PR also comes with a question: Why do we support saving Dipoles in dip and bdip, but FixedDipoles in FIF? would it not be possible to support all formats for all objects?
https://mne.tools/stable/generated/mne.DipoleFixed.html#mne.DipoleFixed.save
https://mne.tools/stable/generated/mne.Dipole.html#mne.Dipole.save

doc: point to read_dipole

---

tutorials/preprocessing/50_artifact_correction_ssp.py

noticed a stray crossref anchor that was visible in the rendered tutorial (just above this heading: https://mne.tools/dev/auto_tutorials/preprocessing/50_artifact_correction_ssp.html#visualizing-the-empty-room-noise). Turns out it's not referenced anywhere, so removing instead of fixing.

remove misformatted (and unused) crossref anchor

---

mne/beamformer/_rap_music.py
mne/dipole.py

turn dipole attrs into properties

---

doc/changes/devel/13174.bugfix.rst
mne/export/_edf.py
mne/forward/tests/test_make_forward.py
mne/preprocessing/tests/test_fine_cal.py
mne/preprocessing/tests/test_maxwell.py
mne/simulation/tests/test_raw.py
tools/install_pre_requirements.sh

The export code for EDF files was calling `np.pad` incorrectly, causing the *channels* axis to also get padded with however many extra samples were needed to make equal-sized data blocks along the *time* axis.  Marking as draft because it's the end of the day and I haven't had time to write a test yet.  ~~This should shrink almost all exported EDF files, possibly quite significantly.~~ *EDIT: the error is self-correcting in the output, because the extra channels are never added to the exported file (there's a for-loop over the channels in the original raw). But it **is** a bug in that it triggers allocating an unnecessarily large intermediate array, and for me was leading to `MemoryError`s when the pad value was big.*
https://numpy.org/doc/stable/reference/generated/numpy.pad.html

fix EDF export

---

doc/changes/devel/13184.bugfix.rst
doc/changes/devel/13184.newfeature.rst
mne/io/snirf/_snirf.py
mne/io/snirf/tests/test_snirf.py

closes #12508 
@kdarti I think this will fix the sampling rate estimation problem for snirf files. Can you provide the file that was showing the problem for you, so I can test it / write a test that emulates that case?

fix sfreq estimation for snirf files

---

doc/install/mne_tools_suite.rst
doc/sphinxext/related_software.py
tools/circleci_dependencies.sh

I noticed we had a few `links` in `mne_tools_suite.rst` that weren't used, probably cruft from when our old related software stuff. This PR just adds `invertmeeg` and I want to make sure that comes back green for CircleCI, then we should wait for https://github.com/mne-tools/mne-installers/pull/342 to land then restart CircleCI to make sure `alphacsc` can be parsed correctly.

ENH: Update related software list

---

doc/_includes/institutional-partners.rst

My employment by FCBG ended at the end of 2024, so I think it should be moved to former partners.

Move FCBG to former partners

---

mne/time_frequency/spectrum.py

https://mne.tools/stable/generated/mne.time_frequency.EpochsSpectrum.html#mne.time_frequency.EpochsSpectrum

fix typo (missing space) that messed up rst rendering

---

doc/changes/devel/13184.bugfix.rst
doc/changes/names.inc
mne/io/snirf/_snirf.py

Fixes #13117.
Enhanced the calculation of the sampling rate to avoid potential indexing errors. 
It is recommended to include `rtol` as a function parameter for [_extract_sampling_rate(dat)](https://github.com/mne-tools/mne-python/blob/4c98f8ae5524fea24968fb1aa2bf2028886d5934/mne/io/snirf/_snirf.py#L534) in the future.

ENH: Improve robustness in extracting sfreq

---

doc/changes/devel/13233.newfeature.rst
doc/changes/names.inc
mne/io/base.py

Fixes #13230.
Provides an error message that makes more clear that data need to be preloaded if one wishes to overwrite files (`save()` with the parameter `overwrite=True`).

Improve error message for overwrite

---

doc/changes/devel/13144.newfeature.rst
doc/changes/names.inc
mne/channels/layout.py
mne/datasets/config.py
mne/preprocessing/tests/test_ica.py
mne/viz/tests/test_ica.py
mne/viz/tests/test_topomap.py
mne/viz/topomap.py
tutorials/preprocessing/80_opm_processing.py

Adds features from https://github.com/mne-tools/mne-python/issues/11579
This PR extends topomaps to accommodate OPM data with colocated sensors.
It modifies the code used for colocated fNIRS, which now handles both fnirs and OPM. 
In contrast to fNIRS which averages the colocated sensors, for OPM sensors we just take the most radial sensor.
- I've written an opm test, but would like guidance about how to access `mne.datasets.ucl_opm_auditory`. Test won't work as is (eg can't update UCL dataset, and wanted to confirm proper method), but the test is structured on the fnirs overlap test so probably won't need much more
- I rely on some hard-coded look-ups:
- lookup OPM sensor coil types (quspin currently included)
- I need to use different `loc` triplets for dual-axis vs triaxial sensors, …

Colocated topomaps for OPM

---

.circleci/config.yml

Sometimes the CircleCI `coverage.yml` is junk (see [this failure](https://app.circleci.com/pipelines/github/mne-tools/mne-python/27424/workflows/2dfc70f1-faa7-4d56-bd9b-66a47bede8d6/jobs/73144)). Not 100% sure why but it shouldn't kill the build. We can investigate the failure separately, but it's a pretty small issue since the coverage report is not super useful yet anyway (the doctest for `doc/` is very limited!).

FIX: Tolerate bad coverage.xml

---

doc/changes/devel/13232.newfeature.rst
mne/forward/_field_interpolation.py
mne/report/report.py
mne/report/tests/test_report.py
mne/tests/test_transforms.py
mne/transforms.py
mne/viz/_3d.py

ENH: support auto and fsaverage for add_trans in report

---

mne/report/report.py

- fixes #13243 
The footer will now read approx like this:
> Created on 2025-05-13 09:21:51 via MNE-Python ...

ENH: Add time to date stamp of mne.Report footer

---

doc/documentation/datasets.rst
mne/datasets/_fsaverage/base.py
tutorials/forward/10_background_freesurfer.py
tutorials/forward/35_eeg_no_mri.py

these links can be helpful for people who do not know what the "magic" "fsaverage" is, that is used so often throughout the codebase, examples, and tutorials.
It links to: https://mne.tools/stable/auto_tutorials/forward/10_background_freesurfer.html#fsaverage

DOC: link to background info on fsaverage

---

doc/changes/devel/13208.bugfix.rst.rst
mne/preprocessing/maxwell.py
mne/preprocessing/tests/test_maxwell.py
tools/install_pre_requirements.sh

Following https://mne.discourse.group/t/montage-error-in-preparing-empty-room-for-maxfilter-for-simultaneous-meg-eeg/11089
In Geneva, an acquisition with combined MEG / EEG was done while preserving the EEG channels enabled. If you blindly apply `maxwell_filter_prepare_emptyroom` you get a failure during the `get_montage(...)` / `set_montage(...)` step. Beside the fiducial digitization, I can't think of an information from the `DigMontage` required by MaxWell filter to be set on the ER. Pointing in that direction, the existing `test` are removing EEG channels from the test files prior to running `maxwell_filter_prepare_emptyroom`.
This PR adds a tiny piece of documentation about it; and drops EEG (and ECOG, sEEG, DBS channels which might also not played nicely since they would contain …

Improve tests of maxwell_filter_prepare_emptyroom

---

mne/commands/tests/test_commands.py
mne/cov.py
mne/datasets/tests/test_datasets.py
mne/decoding/csp.py
pyproject.toml
tools/circleci_dependencies.sh

- closes #13254 
The changes proposed here clean up the logging substantially.
Outputs are as follows:
```
Estimating class=1 covariance (average over epochs; LEDOIT_WOLF)
Estimating class=2 covariance (average over epochs; LEDOIT_WOLF)
Estimating class=1 covariance (average over epochs; EMPIRICAL)
Estimating class=2 covariance (average over epochs; EMPIRICAL)
Estimating class=1 covariance (average over epochs; EMPIRICAL WITH SHRINKAGE)
Estimating class=2 covariance (average over epochs; EMPIRICAL WITH SHRINKAGE)
```
previously this was:
Closes #13258

CSP: only log once if cov is computed epoch wise

---

doc/changes/devel/13280.bugfix.rst
mne/preprocessing/maxwell.py

`prepare_empty_room` only includes bad channels if they are MEG channels (make sense), but it does this by looking for "MEG" in at the start of the channel name. This breaks for OPM sensors (or any sensors without this formatting).
Fixed to use `pick_types` instead.

fix Maxwell bads filtering

---

mne/viz/topomap.py

Before:
> ValueError: Number of channels in the Info object (60) and the data array (59) do not match.Pick Info with e.g. mne.pick_info and mne.channel_indices_by_type.
After:
> ValueError: Number of channels in the Info object (60) and the data array (59) do not match. Pick the Info object (e.g., using mne.pick_info and mne.channel_indices_by_type).

DOC: fix missing space, use f-strings, structure->object

---

mne/channels/layout.py

Some of the docstrings were factually wrong. This is fixed here.

DOC: fix docstrs around layout functions

---

mne/time_frequency/spectrum.py

https://mne.tools/stable/generated/mne.time_frequency.EpochsSpectrum.html#mne.time_frequency.EpochsSpectrum

doc: fix rendering typo rst docstr

---

doc/conf.py
doc/links.inc
mne/annotations.py
mne/utils/docs.py

Fixes #13295.
I modified the base docstring to signal the potential difference in default. It seems like all the other methods do default to `None` except the one for annotations. Instead of removing the default base docstring for all the other methods, I modified it to read unless otherwise specified and then added the specification to the annotation method.

Update docstring to reflect default setting in annotations

---

doc/changes/devel/13298.bugfix.rst
mne/time_frequency/spectrum.py
mne/time_frequency/tfr.py
mne/utils/docs.py
mne/viz/tests/test_raw.py
mne/viz/utils.py
tutorials/time-freq/10_spectrum_class.py
tutorials/time-freq/20_sensors_time_frequency.py

Use more common y-axis label for PSD plot. Fixes #13296.

Tweak y-axis label

---

.github/workflows/tests.yml
environment.yml
mne/decoding/_fixes.py
mne/decoding/tests/test_base.py
mne/decoding/tests/test_csp.py
mne/decoding/tests/test_ems.py
mne/decoding/tests/test_ssd.py
mne/decoding/tests/test_time_frequency.py
mne/decoding/tests/test_transformer.py
mne/decoding/transformer.py
mne/inverse_sparse/tests/test_mxne_inverse.py
pyproject.toml
tools/environment_old.yml
tools/hooks/update_environment_file.py

Closes #13138
Should expose the problem first (true TDD!). Then I'll push fixes, then uncomment the other CI runs.

BUG: Fixes for old sklearn

---

azure-pipelines.yml
mne/_fiff/tests/test_constants.py
mne/bem.py
mne/conftest.py
mne/datasets/tests/test_datasets.py
mne/html_templates/report/forward.html.jinja
mne/html_templates/report/image.html.jinja
mne/preprocessing/tests/test_fine_cal.py
mne/report/report.py
mne/report/tests/test_report.py
tutorials/intro/70_report.py

Tightening up the API a bit from https://github.com/mne-tools/mne-python/pull/12848 before merge:
1. Make `add_forward(..., plot=False)` new kwarg, so keep old behavior (don't try to plot unless asked)
2. Make `report.parse_folder(..., plot_src=False)` a new kwarg
3. Add `add_inverse_operator(..., plot=False)` new kwarg to allow showing the source space for the inverse operator in the same way
4. Don't try to calculate distances using `info` from fwd/inv (dig points are not stored)
5. Only add the source space plot, not the alignment or the BEM
(1) and (2) are backward compat fixes I missed, (3) improves consistency, (4) is a bugfix, and (5) is done because we already have `report.add_trans` and `report.add_bem` which have this functionality (with more options!), so better not to …

ENH: Cleaner forward solution plotting options

---

doc/changes/devel/13314.bugfix.rst
mne/defaults.py

closes #13244 
There have been several iterations on the issue of eyetracking units, so let me summarize for brevity:
Stemming from Issue https://github.com/mne-tools/mne-python/issues/12756#issuecomment-2260832644 (and PR https://github.com/mne-tools/mne-python/pull/12846#issuecomment-2349960065 + https://github.com/mne-tools/mne-python/pull/12850), we changed MNE internals to assume all incoming Eyetracking data were already represented in Meters (SI unit of distance, as _some_ eyetrackers report pupil size in mm). In those PR's I adjusted the scaling for Pupil channels so that data in meters would look nice when plotting by default. I chose a scaling factor of 1e6 (meters -> micro meters). 
This caused `inst.to_data_frame()` to convert from meters -> micrometers which is probably not …

Adjust Pupil channel units (again)

---

doc/_static/js/custom-icons.js
doc/_static/style.css
doc/conf.py

- adds links to https://github.com/sponsors/mne-tools and https://opencollective.com/mne-python with appropriate icons and colors
- switches from squarish GitHub icon to round one
- tweaks the hover text of some of the icons:
- "Forum" -> "Q&A Forum"
- "Discord" -> "Discord (office hours)"
- "GitHub" -> "Code Repository"
- "Mastodon" is unchanged
here's screenshots of a local build, hovering over each of the two new icons:

Add icon links to our donation pages

---

doc/sphinxext/mne_doc_utils.py
mne/gui/_coreg.py

Trivial change to fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/28099/workflows/74d468b2-1e5d-4071-9b4d-9f27248ca762/jobs/74553

MAINT: Fix ref cycle with vtkPolyData

---

tools/install_pre_requirements.sh

Should be doable [now](https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/statsmodels/):

MAINT: Restore statsmodels to pip-pre

---

mne/decoding/_ged.py
mne/decoding/base.py
mne/decoding/tests/test_ged.py

Fixes #13342.
validate covariances more precisely: 
- for GED S should be at least symmetric and R should be at least positive semi-definite
- for AJD all covs should be at least positive semi-definite
- use more reasonable tolerances for symmetricity and definiteness
- improve tests accordingly

BUG: Fix GED tolerances and improve cov validation

---

mne/utils/misc.py
tutorials/preprocessing/70_fnirs_processing.py

Will fail until https://github.com/pyvista/pyvista/pull/7746 lands. In the meantime, we should be able to see the improved traceback in the CircleCI output of the touched example (which is [failing on `main`](https://app.circleci.com/pipelines/github/mne-tools/mne-python/28164/workflows/d33ebd65-7d1d-4d7b-963a-144c2be17bec/jobs/74694)) that takes
```
3 vtkPolyData @ mne/conf.py:Resetter.__call__:after:70_fnirs_processing.py:
list: len=1, 4 referrers: dict/list
list: len=1, 4 referrers: dict/list
list: len=1, 4 referrers: dict/list
```
and makes it a bit more informative:
```
3 vtkPolyData @ mne/conf.py:Resetter.__call__:after:70_fnirs_processing.py:
list[0] with len=1 | 3 referrers: dict['_glyph_geom'] / list[1] / list[743437]
list[0] with len=1 | 3 referrers: dict['_glyph_geom'] / …
```

MAINT: Fix CircleCI

---

pyproject.toml

As per PEP 639, licenses should be declared with two fields (see https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files).

Update license fields

---

mne/transforms.py
pyproject.toml

I'm seeing "undefined marker" errors during pytest collection, but only for some markers.  This registers the `pgtest` and `pvtest` marks in the pyproject.toml file (as is recommended in [the docs](https://docs.pytest.org/en/stable/example/markers.html#registering-markers)).  I don't understand why it isn't working when they're here:
https://github.com/mne-tools/mne-python/blob/f7cab3af285eb3e1e7afd3879d76b5539942a01e/mne/conftest.py#L88-L95
or why I don't see "undefined marker" for those other markers.  Possible clue: `pytest --markers` on main currently doesn't show any of those defined in conftest, but on this branch, `pytest --markers` *does* show them all, and *also* shows `pvtest` and `pgtest` twice (once from pyproject.toml and once from conftest.py).  PR is draft until I get the …

specify `testpaths` in pytest config
