- mne/report.py
cc @kambysese 
closes https://github.com/mne-tools/mne-python/issues/1724
> FIX trans for single layer BEM

- mne/io/fiff/raw.py
@mshamalainen @LauriParkkonen @Eric89GXL looks good?
> warning to use maxfilter on IAS data

- mne/fixes.py
- mne/tests/test_cov.py
- mne/viz/evoked.py
hope it fixes the dinosauric inria build bot.
cc @agramfort @Eric89GXL
> misc fixes

- doc/source/python_reference.rst
- doc/source/whats_new.rst
- mne/__init__.py
- mne/channels/interpolation.py
- mne/channels/tests/test_interpolation.py
- mne/evoked.py
- mne/preprocessing/ica.py
- mne/tests/test_evoked.py
cc @dengemann see fix of interpolation code
> MRG : Evoked grand average 3

- mne/report.py
Minor fix for report so it does what it says it will do (cc @mainakjas). Waiting to see if Travis is happy about it...
> FIX: Fix report

- mne/viz/topomap.py
topomap currently broken with e.g. magnesWH3600 layout. this is the fix.
> FIX: topomap plot from certain layouts

- mne/cov.py
- mne/io/constants.py
- mne/tests/test_cov.py
Addresses and closes #1745 
cc @agramfort
> ENH: add cov new io

- doc/source/python_reference.rst
- doc/source/whats_new.rst
- mne/__init__.py
- mne/evoked.py
- mne/source_estimate.py
- mne/tests/test_evoked.py
One issue is the weighting. @agramfort you had something much more complex:
https://github.com/mne-tools/mne-python/pull/461/files#diff-738430c6d6954d2d42b2632b6fd1a0bdR631
Is that because you wanted to be able to use weights like e.g. `[1, -1]` instead of `[evoked1.nave, -evoked2.nave]` for a simple subtraction?
> ENH: combine_evoked

- examples/decoding/plot_decoding_spatio_temporal_source.py
- examples/stats/plot_cluster_stats_spatio_temporal_repeated_measures_anova.py
- mne/forward/forward.py
- mne/label.py
- mne/source_estimate.py
- mne/source_space.py
- mne/surface.py
- mne/viz/raw.py
Fixes our use of `np.array([])` when we mean `np.array([], int)`. Also adds scrolling support to `raw.plot()`.
Ready for review/merge once the CIs are happy.
> FIX: Minor fixes

- mne/io/edf/edf.py
A patch to bdf reader. this bug came about after fixing another bug. This should resolve the current issue mentioned on the listserv. The edf standard format is super (too) flexible, for better or for worse ;)
> FIX block loop

- mne/preprocessing/bads.py
> FIX: find_outliers

- mne/channels/interpolation.py
- mne/channels/tests/test_interpolation.py
- mne/preprocessing/ecg.py
> Fixes #1774 and #1775

- mne/report.py
- mne/tests/test_report.py
closes #1778 
cc @agramfort @mainakjas
> FIX: mayavi figure support

- mne/io/edf/edf.py
Instead of using sfreq to determine the reading, read_segment now uses
the number of samples information from the header for all cases. Addresses #1767.
> FIX: define edf._read_segment in terms of samples

- mne/viz/misc.py
orientation takes axial instead of transverse
> EDIT docstring

- doc/source/python_reference.rst
- doc/source/whats_new.rst
- mne/epochs.py
- mne/tests/test_epochs.py
Makes it easier to handle high sample frequencies with many runs.
cc @agramfort @cmoutard
> WIP/ENH: various cleanups and cat_epochs functionality

- doc/source/whats_new.rst
- mne/label.py
- mne/tests/test_label.py
Subtract labels from each other. Should be a straight forward extension from Label addition behavior.
> Label subtraction

- mne/epochs.py
- mne/io/pick.py
- mne/tests/test_epochs.py
we did only half the work ... should be good with the changes I proposed here.
> ENH: improve cat epochs

- examples/plot_read_epochs.py
- mne/viz/epochs.py
fixes #1803 
picks seems to work fine.
> fix #1803 : scalings in plot_epochs

- mne/epochs.py
- mne/tests/test_epochs.py
> ENH: another round of cat epochs

- mne/io/edf/edf.py
Fixes error mentioned in #1826.
> FIX: remove block multiplier

- doc/source/python_reference.rst
- mne/__init__.py
- mne/dipole.py
- mne/source_space.py
- mne/tests/test_dipole.py
> WIP: Dipole IO

- mne/io/tag.py
Workaround for #1823, so we can read raw files processed with MNE-C versions that had the byte swapping bug. 
Not sure what the best way is to test this..
> FIX: workaround MNE-C byteswapping bug

- doc/source/python_reference.rst
- doc/source/whats_new.rst
- examples/decoding/plot_decoding_time_generalization.py
- examples/decoding/plot_decoding_time_generalization_conditions.py
- mne/decoding/__init__.py
- mne/decoding/tests/test_time_gen.py
- mne/decoding/time_gen.py
- mne/tests/test_utils.py
- mne/utils.py
- mne/viz/__init__.py
- mne/viz/decoding.py
- mne/viz/tests/test_decoding.py
Closes #1302. 
@kingjr sorry rebasing was a mess, I had to squash your commits to get started within a finite amount of time. Your commits are supposed to be logged and counted anyways
Here's a list of things I addressed.
1. Enforce sklaern API that distinguishes between parametersa and attributes
2. make score and predict return the corresponding values
3. fix unfarable expression which create references not copies e.g ```[[]] * len(test_times``` creates a list of len(test_times) times the same list object.
4. fix the default y and simplify the example. I figured out that sklearn apparently expects 0 and 1 or True and False for the binary case. Using scipy.stats.rankdata as a trick to achieve this.
5. isolated the changes related to the new class from the changes related to the previous …
> MRG: New time gen class

- mne/io/write.py
Closes #1850.
@agramfort see if you're happy with this.
> FIX: Check for 2GB limit

- doc/source/python_reference.rst
- examples/inverse/plot_snr_estimate.py
- mne/minimum_norm/__init__.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_snr.py
- mne/viz/__init__.py
- mne/viz/evoked.py
- mne/viz/tests/test_misc.py
Moves us toward something like #1453.
> ENH: Add MNE-C style SNR estimate

- doc/source/whats_new.rst
- mne/epochs.py
- mne/evoked.py
- mne/filter.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
Closes #347.
@agramfort see what you think of the API.
> ENH: Add savgol

- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
> Add label arg to apply_inverse

- doc/source/whats_new.rst
- mne/report.py
- mne/tests/test_report.py
> Add methods to render bem, add html str to report

- doc/source/whats_new.rst
- mne/tests/test_report.py
> ENH whats_new, test_add_htmls_to_section

- mne/report.py
- mne/tests/test_report.py
Add a default for section like the other function.
Fixes my fail at html_101 with the proper slash.
> ENH add default arg to section

- doc/source/whats_new.rst
- examples/inverse/plot_lcmv_beamformer.py
- mne/__init__.py
- mne/label.py
- mne/tests/test_label.py
> Deprecate label_time_courses

- examples/plot_read_noise_covariance_matrix.py
- mne/cov.py
- mne/viz/misc.py
- mne/viz/tests/test_misc.py
Closes #1863.
@teonlamont see if you're happy with this.
> FIX: Fix example

- examples/inverse/plot_lcmv_beamformer_volume.py
here is how it looks like:
needs an unreleased version of nilearn so let's wait before merging.
> WIP use nilearn viz for LCMV vol example

- mne/datasets/utils.py
- mne/utils.py
Should be good to go if the CIs are happy.
> FIX: Use GitHub for testing dataset

- mne/io/meas_info.py
- mne/io/proc_history.py
- mne/io/tests/test_meas_info.py
Closes #1875.
@agramfort ready for merge from my end assuming the CIs are happy. `test_meas_info.py` passes on my 3.4 and 2.7 so I'm optimistic this might be a one-commit change.
> FIX: Unicode

- examples/inverse/plot_dipole_fit.py
- examples/inverse/plot_read_source_space.py
- examples/plot_read_bem_surfaces.py
- mne/forward/forward.py
- mne/minimum_norm/inverse.py
- mne/source_space.py
- mne/surface.py
- mne/tests/test_source_space.py
- mne/tests/test_surface.py
> DOC: rename add_geom to patch_stats

- mne/io/__init__.py
- mne/io/base.py
- mne/io/fiff/__init__.py
- mne/io/fiff/raw.py
- mne/io/reference.py
> RawFIFF -> RawFIF

- mne/source_estimate.py
- mne/tests/test_source_estimate.py
Closes #1526. Ready for review/merge @dengemann.
> ENH: Warn on insufficient steps

- mne/cov.py
- mne/epochs.py
- mne/preprocessing/ecg.py
- mne/preprocessing/eog.py
- mne/preprocessing/ica.py
- mne/preprocessing/ssp.py
- mne/proj.py
- mne/realtime/epochs.py
Closes #1894.
@mainakjas see if this is better.
> DOC: Clearer docstring

- examples/datasets/plot_spm_faces_dataset.py
- examples/inverse/plot_covariance_whitening_dspm.py
- examples/plot_coregistration_transform.py
- examples/plot_make_forward.py
- examples/plot_meg_eeg_fields_3d.py
- mne/forward/_field_interpolation.py
- mne/forward/_make_forward.py
- mne/forward/forward.py
- mne/forward/tests/test_field_interpolation.py
- mne/forward/tests/test_make_forward.py
- mne/report.py
- mne/tests/test_report.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
Closes #1055.
Ready for review/merge from my end @agramfort @dengemann.
> FIX: Fix trans use

- mne/io/base.py
> FIX docstring for raw.filter

- mne/io/reference.py
- mne/viz/ica.py
> Checks for the base class instead of class inst

- mne/fixes.py
- mne/utils.py
> FIX Backport numpy.isclose for np.version < 1.7

- Makefile
- mne/parallel.py
- mne/stats/cluster_level.py
- mne/stats/tests/test_cluster_level.py
> FIX: Fix for buffer_size=None

- doc/sphinxext/gen_rst.py
- examples/connectivity/plot_sensor_connectivity.py
- examples/inverse/plot_dipole_fit.py
- examples/inverse/plot_read_inverse.py
- examples/inverse/plot_read_source_space.py
- examples/plot_decimate_head_surface.py
- examples/plot_read_bem_surfaces.py
- mne/commands/mne_flash_bem_model.py
- mne/report.py
- mne/utils.py
- mne/viz/_3d.py
> FIX: Safe not to have mayavi

- mne/io/base.py
- mne/io/meas_info.py
- mne/io/tests/test_apply_function.py
- mne/utils.py
> FIX: Fix apply_function order

- doc/source/whats_new.rst
- examples/connectivity/plot_sensor_connectivity.py
- examples/inverse/plot_dipole_fit.py
- examples/inverse/plot_read_inverse.py
- examples/inverse/plot_read_source_space.py
- examples/plot_decimate_head_surface.py
- examples/plot_read_bem_surfaces.py
- mne/channels/channels.py
- mne/forward/forward.py
- mne/forward/tests/test_forward.py
- mne/io/array/array.py
- mne/io/base.py
- mne/io/brainvision/brainvision.py
- mne/io/bti/bti.py
- mne/io/bti/tests/test_bti.py
- mne/io/edf/edf.py
- mne/io/egi/egi.py
- mne/io/fiff/raw.py
- mne/io/fiff/tests/test_raw.py
- mne/io/kit/kit.py
- mne/io/reference.py
- mne/preprocessing/ica.py
- mne/realtime/tests/test_mockclient.py
- mne/tests/test_event.py
More red than green should make @agramfort happy, and the repo more DRY. Ready for review/merge from my end.
Closes #1633.
> FIX: Refactor raw to add necessary attributes

- mne/epochs.py
- mne/tests/test_epochs.py
Use the value specified at initialization.
> ADD baseline arg

- doc/source/python_reference.rst
- doc/source/whats_new.rst
- examples/inverse/plot_dipole_fit.py
- examples/inverse/plot_gamma_map_inverse.py
- examples/plot_simulate_evoked_data.py
- mne/channels/channels.py
- mne/evoked.py
- mne/forward/tests/test_field_interpolation.py
- mne/io/pick.py
- mne/io/tests/test_pick.py
- mne/simulation/tests/test_evoked.py
- mne/tests/test_evoked.py
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
Closes #1138.
Closes #1270.
Ready for review/merge.
> ENH: Add pick_types and crop

- mne/decoding/tests/test_time_gen.py
- mne/decoding/time_gen.py
This implements a score() with a parallelization across estimators (training time samples).
@jona-sassenhagen
> EHN: parallelization of gat.score() 

- mne/viz/raw.py
Allows clicking in between the channels to draw a vertical line like in `mne_browse_raw`.
> ENH: Add vertical line to raw plot

- mne/epochs.py
I'm not sure if this is right or wrong,
> Minor typo in equalize_epoch_counts

- doc/source/whats_new.rst
- mne/report.py
- mne/tests/test_report.py
Closes https://github.com/mne-tools/mne-python/issues/1882
> [MRG] FIX section ordering if pre-defined section was used

- mne/epochs.py
- mne/evoked.py
- mne/time_frequency/tfr.py
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
Allows us to generate figures like this one:
https://www.dropbox.com/s/5qpykqyh8fcc6bp/Screenshot%202015-04-17%2012.47.52.png?dl=0
> [MRG] ENH/MAINT: improvements to plot_topomap for custom outlines and image masks.

- mne/viz/topomap.py
Taking over #1920 so @mainakjas can use it. @dengemann can you take a look and see if it's what you wanted?
> ENH: Colorbar width

- mne/io/base.py
- mne/io/brainvision/brainvision.py
- mne/io/edf/edf.py
- mne/io/egi/egi.py
- mne/io/fiff/raw.py
- mne/io/kit/kit.py
Make `_cals` computation consistent across modules. comment brought up in #1952.
> ENH make _cals computation the same across modules

- doc/source/whats_new.rst
> Reformat whats_new

- mne/report.py
- mne/tests/test_report.py
closes https://github.com/mne-tools/mne-python/issues/1887
cc @dengemann
> FIX report for section names having only digits

- doc/source/whats_new.rst
- examples/plot_virtual_evoked.py
- mne/evoked.py
- mne/forward/__init__.py
- mne/forward/_field_interpolation.py
- mne/forward/_lead_dots.py
- mne/forward/_make_forward.py
- mne/forward/tests/test_field_interpolation.py
- mne/utils.py
- mne/viz/topomap.py
Closes https://github.com/mne-tools/mne-python/issues/1080. Here's what you get when you remap mag to grad for sample.
Still needs to be made nicer with tests and better options in API.
cc @Anevar @agramfort
> WIP: Virtual sensors / remap sensors

- doc/source/faq.rst
- doc/source/mne-python.rst
First pass ....
@christianbrodbeck @Eric89GXL @agramfort
> DOC: FAQ for cov estimation

- .travis.yml
- mne/beamformer/tests/test_dics.py
- mne/preprocessing/tests/test_infomax.py
- mne/stats/tests/test_cluster_level.py
- mne/tests/test_cov.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
- mne/utils.py
- mne/viz/tests/test_circle.py
- mne/viz/tests/test_epochs.py
- mne/viz/tests/test_evoked.py
- mne/viz/tests/test_ica.py
- mne/viz/tests/test_misc.py
- mne/viz/tests/test_raw.py
- mne/viz/tests/test_topo.py
- mne/viz/tests/test_topomap.py
- mne/viz/tests/test_utils.py
> ENH: Use old versions on one run

- doc/source/whats_new.rst
- examples/plot_topo_compare_conditions.py
- mne/epochs.py
- mne/tests/test_epochs.py
Added final tweaks for  #1975 (cc @jona-sassenhagen). Example updated:
Closes #1562.
> ENH: Multi-index

- .travis.yml
- mne/bem.py
- mne/channels/channels.py
- mne/channels/tests/test_channels.py
- mne/inverse_sparse/mxne_optim.py
- mne/io/tests/test_pick.py
- mne/label.py
- mne/preprocessing/stim.py
- mne/preprocessing/tests/test_stim.py
- mne/source_estimate.py
- mne/tests/test_label.py
- mne/viz/topomap.py
Simple change to allow specifying the shells. I needed it sooner than I thought @agramfort :)
> FIX: Expand options

- mne/beamformer/_dics.py
- mne/channels/channels.py
- mne/channels/layout.py
- mne/connectivity/spectral.py
- mne/forward/_field_interpolation.py
- mne/forward/forward.py
- mne/forward/tests/test_field_interpolation.py
- mne/io/base.py
- mne/io/bti/bti.py
- mne/io/bti/tests/test_bti.py
- mne/io/meas_info.py
- mne/io/open.py
- mne/io/proj.py
- mne/minimum_norm/inverse.py
- mne/preprocessing/ecg.py
- mne/source_estimate.py
- mne/source_space.py
- mne/stats/cluster_level.py
- mne/surface.py
- mne/tests/test_epochs.py
- mne/tests/test_utils.py
- mne/utils.py
- mne/viz/_3d.py
- mne/viz/epochs.py
- mne/viz/evoked.py
- mne/viz/topo.py
- mne/viz/topomap.py
- mne/viz/utils.py
> ENH: generator expressions for builtin `all` and `any`

- mne/viz/circle.py
- mne/viz/epochs.py
- mne/viz/evoked.py
- mne/viz/ica.py
- mne/viz/misc.py
- mne/viz/montage.py
- mne/viz/raw.py
- mne/viz/topo.py
- mne/viz/topomap.py
Adds a bunch of shows. This might be an API change, since it could cause shows where there previously weren't shows. But I think most of the time people want something shown, so maybe it's okay. The alternatives are 1) to have some default to `show=False` and some (most) to `show=True`, which would not be good or 2) have `show=None` for the new functions now, which operates like "False" but gives a DeprecationWarning that it will change to "True" in 0.10.
> ENH: Add shows

- mne/viz/topomap.py
@teonlamont @dengemann I think this is what we actually want... the `show` should be delayed until the very end, no?
> FIX: Show at correct time

- mne/viz/evoked.py
- mne/viz/topomap.py
Fixes the figure handle for `plot_projs_topomap`
> MRG Projs topomap

- mne/report.py
> Remove div class

- mne/report.py
- mne/tests/test_report.py
> Fixes report comments

- examples/plot_meg_eeg_fields_3d.py
- mne/forward/_field_interpolation.py
- mne/forward/tests/test_field_interpolation.py
- mne/transforms.py
@BushraR this will give you the MEG fields in the scalp if you put to True the head_surf. It will do a remapping to the scalp surf instead of the helmet one. I put in the example how you can use it (commented at the end)
I was using it for my own plots. I don't know if @agramfort @Eric89GXL find this kind of useful to keep it.
Closes #2002.
> ENH be able to plot MEG fields to the scalp surf

- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
> ADD file extension test

- mne/channels/layout.py
- mne/epochs.py
- mne/evoked.py
Following  [#1984](https://github.com/mne-tools/mne-python/pull/1984), show argument is carried forward to class functions and co.
> carrying show argument forward to class functions and co

- mne/evoked.py
- mne/viz/evoked.py
> DOC: plot_white_evoked

- doc/source/mne_report_tutorial.rst
- doc/source/whats_new.rst
- mne/commands/mne_report.py
- mne/report.py
- mne/viz/evoked.py
- mne/viz/topomap.py
closes https://github.com/mne-tools/mne-python/issues/1730
almost ready. Just needs a few final touches.
> MRG: Whitening in report

- mne/preprocessing/ecg.py
- mne/preprocessing/eog.py
The doc strings had incorrect information for finding ECG automatically, and some wrong labeling.
also, these docs have no author labels or license! could someone let me know who wrote them or send my branch a pull request
> MRG Edit docs

- doc/source/whats_new.rst
- examples/plot_interpolate_bad_channels.py
- mne/channels/channels.py
- mne/channels/interpolation.py
- mne/channels/tests/test_interpolation.py
- mne/commands/tests/test_commands.py
- mne/evoked.py
- mne/forward/__init__.py
- mne/forward/_field_interpolation.py
- mne/io/tests/test_apply_function.py
- mne/tests/test_source_estimate.py
- mne/viz/tests/test_misc.py
This works fine but I need to make it DRY and add documentation
> MRG: interpolate bad meg channels

- doc/source/whats_new.rst
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
- mne/preprocessing/ica.py
Add montage to create_info for ease in setting channel information
> MRG Add montage option to create_info

- mne/channels/tests/test_layout.py
- mne/cov.py
- mne/defaults.py
- mne/epochs.py
- mne/evoked.py
- mne/io/base.py
- mne/io/chpi.py
- mne/tests/test_defaults.py
- mne/tests/test_import_nesting.py
- mne/viz/_3d.py
- mne/viz/__init__.py
- mne/viz/epochs.py
- mne/viz/evoked.py
- mne/viz/raw.py
- mne/viz/topo.py
- mne/viz/topomap.py
- mne/viz/utils.py
Closes #2032.
Unifies our use of mutable defaults. I modified `_mutable_defaults` to only operate on a single parameter for simplicity. It also cleaned up the code quite a bit (as there were a bunch of `_mutable_defaults(('scalings', scalings))[0]` without it).
> MRG: Bugfix rank signals

- doc/source/python_reference.rst
- examples/inverse/plot_gamma_map_inverse.py
- examples/inverse/plot_lcmv_beamformer.py
- examples/inverse/plot_lcmv_beamformer_volume.py
- examples/inverse/plot_make_inverse_operator.py
- examples/inverse/plot_mixed_norm_inverse.py
- examples/inverse/plot_tf_lcmv.py
- examples/inverse/plot_time_frequency_mixed_norm_inverse.py
- mne/cov.py
- mne/viz/epochs.py
Takes care of the 0.9 part of #1989 so we can hopefully release soon.
This will require an update to the sample dataset :( But in the meantime people can manually add the file from here:
http://staff.washington.edu/larsoner/sample_audvis-shrunk-cov.fif
> MRG: FIX: Remove regularize from examples

- mne/datasets/sample/__init__.py
- mne/datasets/sample/sample.py
- mne/datasets/somato/__init__.py
- mne/datasets/somato/somato.py
- mne/datasets/spm_face/__init__.py
- mne/datasets/spm_face/spm_data.py
- mne/datasets/testing/__init__.py
- mne/datasets/testing/_testing.py
- mne/datasets/tests/test_datasets.py
- mne/datasets/utils.py
- mne/io/base.py
- mne/tests/test_docstring_parameters.py
- mne/viz/raw.py
- setup.py
> MRG FIX: Version checking

- .travis.yml
- mne/channels/tests/test_channels.py
- mne/fixes.py
- mne/io/array/tests/test_array.py
- mne/minimum_norm/inverse.py
- mne/report.py
- mne/source_estimate.py
- mne/source_space.py
- mne/tests/test_docstring_parameters.py
- mne/tests/test_epochs.py
- mne/tests/test_import_nesting.py
- mne/tests/test_report.py
- mne/time_frequency/tests/test_psd.py
- mne/viz/evoked.py
- mne/viz/tests/test_circle.py
- mne/viz/tests/test_epochs.py
- mne/viz/tests/test_evoked.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
Closes #2071.
Closes #2015.
Ready for testing / review / merge @teonlamont.
> ENH: Add butterfly channel picking

- mne/tests/test_label.py
- mne/viz/tests/test_circle.py
> FIX: Test works on Py26

- mne/io/proj.py
> Proj empty default

- mne/io/base.py
- mne/io/brainvision/tests/test_brainvision.py
- mne/io/bti/tests/test_bti.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/egi/tests/test_egi.py
- mne/io/fiff/raw.py
- mne/io/kit/kit.py
- mne/io/kit/tests/test_kit.py
Closes #2040.
~~We'll see if Travis is happy. Still some optimizations to do, but the architecture is there.~~
> MRG ENH: Preload data

- examples/connectivity/plot_mne_inverse_coherence_epochs.py
- examples/connectivity/plot_mne_inverse_psi_visual.py
- examples/datasets/plot_spm_faces_dataset.py
- examples/decoding/plot_decoding_spatio_temporal_source.py
- examples/inverse/plot_compute_mne_inverse.py
- examples/inverse/plot_covariance_whitening_dspm.py
- examples/inverse/plot_dics_beamformer.py
- examples/inverse/plot_dics_source_power.py
- examples/inverse/plot_label_from_stc.py
- examples/stats/plot_cluster_stats_spatio_temporal.py
- examples/stats/plot_cluster_stats_spatio_temporal_2samp.py
- examples/stats/plot_cluster_stats_spatio_temporal_repeated_measures_anova.py
- mne/coreg.py
- mne/label.py
- mne/source_estimate.py
- mne/source_space.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
This allows both `colormap` and `clim` to be `'auto'`. This way I get a plot using `mne_analyze` colormap with this:
```
stc.plot(lims=dict(pos_lims=(10, 50, 90)))
```
and a plot with `hot` colormap I get this:
```
stc.plot(lims=dict(lims=(10, 50, 90)))
```
@wronk please have a look and see if you're happy.
> FIX: Minor fixes to plotting

- doc/source/whats_new.rst
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
Addresses and closes #2087 .
Thank @mdelpozobanos for reporting.
> BUG: fix ICA resetting

- mne/io/fiff/tests/test_raw.py
- mne/preprocessing/tests/test_ssp.py
- mne/tests/test_proj.py
Extends speedups from #2090 to other tests.
> ENH: Faster tests

- doc/Makefile
Split output dirs to facilitate https://github.com/mne-tools/mne-tools.github.io
> FIX: Split dev and stable builds

- doc/source/_static/navy.css
- doc/source/_templates/layout.html
Gives us a slightly nicer doc font.
> MRG ENH: Update font

- doc/Makefile
- doc/sphinxext/gen_rst.py
@agramfort I think we want our builders to raise on failure, it will be easier to detect and fix failures.
> MRG FIX: Raise error on gallery failure [ci skip]

- mne/io/kit/kit.py
Update __repr__ so that it reflects the correct shape if it's been concatenated.
Add the raw filename to the info.
Update docstring for the get_kit_info
> ENH: Change to docstring, COSMITS

- doc/source/python_tutorial.rst
> Update python_tutorial.rst [ci_skip]

- mne/io/base.py
- mne/io/edf/tests/test_edf.py
Should allow us to be safe for 0.9. Ready for review/merge from my end.
> FIX: Prevent bad concatenations

- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
would fail for time vectos that have rounding issues.
Also uses vectorized test based on safe function.
cc @mainakjas @Eric89GXL
> FIX: precision errors in times plot topomap

- doc/source/whats_new.rst
Just a few formatting fixes to the whats_new.rst.
> FIX formatting [ci skip]

- mne/viz/ica.py
> Typo [ci skip]

- mne/report.py
cc @dengemann the bug that we found at circus
> FIX wrong class name

- mne/datasets/utils.py
- mne/utils.py
Use Amazon AWS for storage of our datasets :)
> ENH: Use AWS storage

- mne/preprocessing/ica.py
- mne/viz/ica.py
- mne/viz/tests/test_ica.py
> ENH picks and FIX typo

- .travis.yml
- mne/viz/raw.py
- mne/viz/utils.py
Closes #2157.
~~I need to test to see if this actually works, but it follows suggestions in https://github.com/matplotlib/matplotlib/issues/1852. I have a feeling it will not fix our immediate problem.~~
> MRG: Fix OSX plotting

- mne/dipole.py
- mne/tests/test_dipole.py
fixes #2108 
taking over #2147
cc @jmontoyam
> [MRG] Fix issue 2108 dipole

- mne/cov.py
- mne/datasets/__init__.py
- mne/datasets/_fake/__init__.py
- mne/datasets/_fake/_fake.py
- mne/datasets/eegbci/eegbci.py
- mne/datasets/megsim/megsim.py
- mne/datasets/megsim/urls.py
- mne/datasets/tests/test_datasets.py
- mne/datasets/utils.py
- mne/io/tests/test_chpi.py
- mne/label.py
- mne/source_estimate.py
- mne/tests/test_cov.py
- mne/tests/test_fixes.py
- mne/tests/test_label.py
- mne/tests/test_source_estimate.py
- mne/tests/test_source_space.py
- mne/viz/tests/test_topo.py
- mne/viz/tests/test_utils.py
- mne/viz/topo.py
- setup.py
A bunch of changes to improve our coverage.
@dengemann there seems to be an issue with the `cov` code, I couldn't use `method='pca'` in the tests. Can you have a look?
> MRG: Better coverage

- mne/viz/evoked.py
- mne/viz/ica.py
- mne/viz/tests/test_ica.py
> MRG ENH enable clicking on ica.plot_sources(Evoked)

- mne/epochs.py
- mne/tests/test_epochs.py
Closes #2175. Ready for review/merge from my end. I'll also backport to 0.9 once merged.
> MRG: Fix epoch naming

- mne/viz/utils.py
This fixes the error raised while doing this: https://gist.github.com/fraimondo/0919a0d1aeef8de62207
Don't really know if its a bug fix or just a workaround.
> Fix AGG problem with layout

- mne/io/array/tests/test_array.py
- mne/io/base.py
- mne/io/brainvision/tests/test_brainvision.py
- mne/io/bti/tests/test_bti.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/egi/tests/test_egi.py
- mne/io/fiff/tests/test_raw.py
- mne/io/kit/tests/test_kit.py
> MRG: Fix repr

- mne/io/pick.py
- mne/io/tests/test_pick.py
mne.pick_info cleans info['bads'] when bad_channels are excluded
> mne.pick_info cleans info['bads'] when bad_channels are excluded

- mne/dipole.py
- mne/tests/test_dipole.py
> [MRG] Min distance fit dipole

- mne/tests/test_cov.py
> fix pca test for cov est (WIP)

- mne/io/fiff/tests/test_raw.py
- mne/source_space.py
- mne/utils.py
This should fix our recent issues with Travis memory consumption killing builds. Ready for review/merge from my end.
> MRG: Fix Travis

- mne/epochs.py
- mne/io/base.py
- mne/viz/epochs.py
- mne/viz/raw.py
- mne/viz/tests/test_epochs.py
- mne/viz/tests/test_raw.py
Added scaling to raw plot and proj button is hidden if there are no projectors to apply. Also made it possible to scale up with '=' for mac users.
closes https://github.com/mne-tools/mne-python/issues/2204 https://github.com/mne-tools/mne-python/issues/2207
> MRG Improvements to raw plot.  Related to issue #2204

- doc/source/whats_new.rst
- mne/stats/multi_comp.py
- mne/stats/tests/test_multi_comp.py
> FIX: Bonferroni reject mask bug

- mne/report.py
Because of the comment addition, the add_bem_to_section was silently
broken
> [MRG] Fix add_bem_to_section

- mne/report.py
- mne/tests/test_report.py
cc @teonlamont
closes https://github.com/mne-tools/mne-python/issues/2212
> FIX toggling of html section

- Makefile
- doc/source/mne_report_tutorial.rst
- doc/source/python_tutorial.rst
Makes `make test-doc` work over here, and should make Jenkins happy. Ready for review/merge from my end.
> MRG: Minor fixes

- appveyor.yml
- mne/tests/test_cov.py
- mne/utils.py
AppVeyor has been broken (e.g., https://ci.appveyor.com/project/Eric89GXL/mne-python/build/1.0.2318), this should fix it.
> FIX: Fix AppVeyor

- mne/epochs.py
- mne/tests/test_epochs.py
Fixes an issue from the mailing list.
> MRG: Fix reading epochs with missing events

- mne/io/base.py
This should return self for chaining.
> [MRG] raw.preload_data returns self

- doc/source/whats_new.rst
This is a copy of the sklearn pattern for the what's new page (note just one example to test first). I'm not sure if it will work or the best way to test. Comments, thoughts welcome.
closes #2138
> MRG: whats new test

- .travis.yml
Seeing if we can get rid of any `sudo` calls so we can move to Travis's new container-based system.
> MRG: Use Travis container builds

- mne/epochs.py
- mne/tests/test_epochs.py
> FIX : BaseEpochs repr

- doc/source/whats_new.rst
- mne/report.py
closes https://github.com/mne-tools/mne-python/issues/1996
> MRG press 'h' to hide or show all in report

- mne/bem.py
- mne/tests/test_filter.py
Will merge if the CIs are happy.
> FIX: Fix for old scipy

- doc/source/whats_new.rst
- mne/report.py
> change toggle from 'h' to 't'

- mne/io/pick.py
> Make channel_indices_by_type return for all types

- doc/source/whats_new.rst
- mne/commands/mne_freeview_bem_surfaces.py
one more MNE bash command converted to python
> [MRG]: Mne freeview bem surfaces

- mne/gui/__init__.py
- mne/gui/_coreg_gui.py
- mne/gui/_file_traits.py
- mne/gui/tests/test_file_traits.py
- mne/tests/test_docstring_parameters.py
closes https://github.com/mne-tools/mne-python/issues/2235
Allows for coregistration to take any instance that has info (Epochs, Evoked, Raw)
> [MRG] Coregistration

- doc/source/whats_new.rst
- mne/epochs.py
- mne/io/base.py
- mne/io/fiff/raw.py
- mne/io/open.py
- mne/io/write.py
- mne/tests/test_epochs.py
- mne/viz/tests/test_epochs.py
I still have to modify the read function and clean up + add tests
> WIP: split big epochs files when saving

- mne/evoked.py
- mne/io/proj.py
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
- mne/viz/tests/test_topomap.py
- mne/viz/topo.py
- mne/viz/topomap.py
> [MRG] Axes param to tfr.plot.

- mne/cov.py
- mne/decoding/csp.py
- mne/preprocessing/xdawn.py
This is a PR to factorize shared code between Xdawn and CSP. (cf #2296 )
The shared method is _regularized_covariance.
> ENH : CSP and Xdawn share code

- mne/epochs.py
- mne/tests/test_epochs.py
Closes #2326.
Ready for review/merge from my end @dengemann
> MRG: Fix epoch decimation bug

- mne/stats/regression.py
> fix rERP event number count

- mne/bem.py
- mne/time_frequency/tfr.py
Currently there's a pep8 problem.
> [MRG] FIX PEP8

- doc/whats_new.rst
- mne/channels/channels.py
- mne/epochs.py
- mne/evoked.py
- mne/io/base.py
- mne/io/fiff/tests/test_raw.py
- mne/io/meas_info.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
While writing the tutorial for how to concatenate channels across `Raw` objects, we realized that there actually wasn't a way to concatenate channels across `Raw` objects. So here's a quick method to do so using the _merge_info function and some quick checks to make sure that data makes sense to merge. Thoughts @wmvanvliet @agramfort @dengemann @Eric89GXL?
> MRG+1: Add append channels raw

- mne/evoked.py
- mne/report.py
- mne/viz/topomap.py
> [MRG] Fixes

- mne/commands/mne_kit2fiff.py
Simple fix to the mne command script for kit2fiff. 
h/t @noahbenson
> FIX split chans

- mne/dipole.py
- mne/forward/_make_forward.py
- mne/io/write.py
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
> [MRG] Maxwell Filter cleanup

- mne/beamformer/tests/test_rap_music.py
- mne/epochs.py
- mne/simulation/evoked.py
- mne/simulation/tests/test_evoked.py
- mne/tests/test_epochs.py
> MRG: Fix for epochs _raw_times

- mne/stats/regression.py
as discussed w/, and mostly written by, @dengemann
Cuts memory usage by approximately a factor of 2 in typical usage cases on our machine. Maybe now the example will run on @mainakjas' laptop!
Partially adresses #2331
> MRG: decrease memory usage of rERPs

- mne/epochs.py
Closes #2379.
@jona-sassenhagen this takes `_minimize_time_diff` on your sample files from 32 sec to 2.9 sec on my machine.
> ENH: Faster time diffs

- doc/whats_new.rst
- mne/time_frequency/tfr.py
- mne/viz/tests/test_topomap.py
- mne/viz/topo.py
- mne/viz/topomap.py
Rubber band selection draws a topomap figure from TFR.
> [MRG] Rectangle selector for drawing topomap from tfr.

- mne/channels/channels.py
- mne/io/fiff/tests/test_raw.py
- mne/io/pick.py
- mne/io/tests/test_pick.py
- mne/realtime/tests/test_mockclient.py
- mne/simulation/evoked.py
- mne/tests/test_event.py
Sorry for the double PR @Eric89GXL
> MRG: Check for non-lists/tuples/ndarrays before picking channels

- doc/whats_new.rst
- examples/visualization/plot_clickable_image.py
- examples/visualization/plot_evoked_topomap_delayed_ssp.py
- examples/visualization/plot_topo_compare_conditions.py
- mne/evoked.py
- mne/tests/test_docstring_parameters.py
- mne/viz/__init__.py
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
- mne/viz/topo.py
Just chained the function calls for evoked.plot_topo. https://github.com/mne-tools/mne-python/issues/2240
> [MRG] Evoked.plot_topo.

- mne/preprocessing/stim.py
- mne/preprocessing/tests/test_stim.py
cc @agramfort I'll let you check and merge since you wrote this
closes https://github.com/mne-tools/mne-python/issues/2385
> MRG fix bug with stim_artifact fixer

- mne/decoding/tests/test_time_gen.py
- mne/decoding/time_gen.py
See https://github.com/mne-tools/mne-python/issues/2397#issuecomment-130426930
> FIX: GAT deals with cv without the n_fold parameter

- mne/viz/evoked.py
> FIX : only plot eeg, mag, grad in evoked plots

- doc/index.rst
also a bit of trailing whitespace caught by my text editor. Ready for review.
> docs: missing underscores in sample code

- doc/python_reference.rst
- mne/stats/__init__.py
Add functions to the reference
> [MRG] ENH Ref

- mne/decoding/tests/test_transformer.py
- mne/decoding/transformer.py
closes https://github.com/mne-tools/mne-python/issues/2428
cc @trachelr
> FIX inverse transform to work for different n_epochs

- mne/io/base.py
- mne/io/fiff/tests/test_raw.py
Mentioned in #2419. Rather than figuring out how to add zeros to a raw dataframe, I made some short tweaks to the Hilbert code. Think that's reasonable @Eric89GXL?
> Added ability to supply 'N' to Hilbert transform

- mne/filter.py
- mne/tests/test_filter.py
cc @wmvanvliet, I had to tweak your resampling to avoid an error in `io/base.py`'s resampling.
> MRG: Fix resampling

- examples/time_frequency/plot_time_frequency_simulated.py
I just noticed that https://github.com/mne-tools/mne-python/pull/2411 broke one of the examples. Just a quick fix.
> Fix to plot_time_frequency_simulated.

- mne/cuda.py
- mne/filter.py
- mne/proj.py
- mne/tests/test_filter.py
- mne/tests/test_proj.py
Fix for rename of scikit-cuda. Ready for review/merge @agramfort @dengemann 
cc @mmittag this should fix your problem
> MRG: Fix for scikit-cuda rename

- doc/manual/time_frequency.rst
- mne/minimum_norm/time_frequency.py
Only a small diff here, but red lines ;-)
In preparation for future extensions.
cc @Eric89GXL @mainakjas @agramfort ...
> ENH: simplify minimum norm TFR code and imrpove readability

- examples/decoding/plot_decoding_csp_eeg.py
- mne/__init__.py
- mne/channels/channels.py
- mne/channels/interpolation.py
- mne/channels/layout.py
- mne/channels/tests/test_channels.py
- mne/channels/tests/test_layout.py
- mne/cov.py
- mne/decoding/time_gen.py
- mne/epochs.py
- mne/event.py
- mne/forward/forward.py
- mne/io/base.py
- mne/io/meas_info.py
- mne/io/pick.py
- mne/io/tests/test_pick.py
- mne/minimum_norm/inverse.py
- mne/preprocessing/ica.py
- mne/realtime/mockclient.py
- mne/stats/regression.py
- mne/tests/test_epochs.py
Closes #2218.
Added some consistency checking of `info` regarding bads and found a few minor bugs along the way.
> MRG: Check info consistency

- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
title says it. this is a fix. if we want a more consistent checking at the constructor level let's address it separately. In the moment I have to move in small steps.
> FIX: make sure info is an info, plotting will break otherwise after reading

- mne/minimum_norm/time_frequency.py
improves speed up to a factor of 2
> ENH: inplace operator power

- doc/python_reference.rst
- doc/whats_new.rst
- examples/preprocessing/plot_xdawn_denoising.py
- examples/visualization/plot_channel_epochs_image.py
- mne/tests/test_docstring_parameters.py
- mne/viz/__init__.py
- mne/viz/epochs.py
- mne/viz/tests/test_epochs.py
> [MRG] ENH depr plot_image_epochs

- mne/dipole.py
- mne/forward/_make_forward.py
- mne/simulation/evoked.py
- mne/tests/test_dipole.py
- mne/transforms.py
This cleans up the dipole code a little bit. We had the constraint both in the solver arguments *and* the fitting function, which I think is non-standard. This moves it to be only in the solver. It also ensures our fit quality is sub-mm in noiseless conditions.
> MRG: Slightly better dipole accuracy

- doc/whats_new.rst
- mne/epochs.py
- mne/io/tag.py
- mne/tests/test_epochs.py
Closes #2345.
@teonlamont this should work for you.
> MRG: Allow preload=False in read_epochs

- mne/source_space.py
- mne/tests/test_source_space.py
Minor fix where `n_jobs` didn't evenly divide into the number of source points.
> MRG: Fix for n_jobs source space

- doc/python_reference.rst
- examples/forward/plot_coregistration_transform.py
- mne/__init__.py
- mne/bem.py
- mne/dipole.py
- mne/forward/_field_interpolation.py
- mne/forward/_make_forward.py
- mne/forward/forward.py
- mne/forward/tests/test_make_forward.py
- mne/gui/_coreg_gui.py
- mne/gui/_kit2fiff_gui.py
- mne/io/bti/bti.py
- mne/io/kit/kit.py
- mne/io/meas_info.py
- mne/io/tag.py
- mne/minimum_norm/inverse.py
- mne/source_space.py
- mne/surface.py
- mne/tests/test_bem.py
- mne/tests/test_transforms.py
- mne/transforms.py
- mne/viz/_3d.py
Make our plotting functions a bit more verbose.
> MRG: Verbose output for plot_trans

- mne/bem.py
- mne/tests/test_bem.py
This should make our sphere fitting a bit more robust and general at the same time.
> MRG: Robust fitting for sphere

- mne/io/bti/bti.py
- mne/io/bti/tests/test_bti.py
> ENH: more bti tweaks

- mne/cov.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
- mne/tests/test_cov.py
- mne/utils.py
Some refactoring to clean up `Covariance` instantiation and allow `inv['noise_cov']` to be a `Covariance` instance. cc @nfoti
> MRG: Make inv["noise_cov"] a Covariance

- mne/preprocessing/ecg.py
- mne/preprocessing/eog.py
> API : add option not to preload ECG epochs (can be big)

- doc/manual/cookbook.rst
- doc/python_reference.rst
- examples/preprocessing/plot_estimate_covariance_matrix_raw.py
- examples/preprocessing/plot_xdawn_denoising.py
- mne/__init__.py
- mne/beamformer/tests/test_lcmv.py
- mne/cov.py
- mne/preprocessing/tests/test_maxwell.py
- mne/preprocessing/tests/test_xdawn.py
- mne/tests/test_cov.py
> API : rename compute_raw_data_covariance to compute_raw_covariance

- doc/python_reference.rst
- mne/channels/__init__.py
- mne/channels/channels.py
- mne/io/fiff/raw.py
- mne/io/fiff/tests/test_raw.py
> MRG: Enable fixing of mag channels

- mne/__init__.py
- mne/chpi.py
- mne/forward/__init__.py
- mne/forward/_compute_forward.py
- mne/forward/_field_interpolation.py
- mne/forward/_make_forward.py
- mne/forward/tests/test_field_interpolation.py
- mne/forward/tests/test_make_forward.py
- mne/io/__init__.py
- mne/io/constants.py
- mne/io/meas_info.py
- mne/simulation/raw.py
- mne/simulation/tests/test_raw.py
- mne/tests/test_chpi.py
- mne/tests/test_docstring_parameters.py
- mne/transforms.py
- mne/utils.py
Let's see if the CIs are happy. Private for now so I have a release cycle (next one) to work with it a bit more. But in the meantime acts as a nice validation of our raw simulator.
> MRG: cHPI position estimation

- mne/stats/cluster_level.py
with @fraimondo we figure that this removes one potential bottleneck.
Should create a linear scaling with graph components.
In out test case we improve by a factor of 17.
cc @agramfort @Eric89GXL
> ENH: partially vectorize components2list

- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
PR to implement temporal SSS into the SSS package
Will require `MNE-testing-data` to be updated
> [MRG] SSS: tSSS

- doc/manual/cookbook.rst
- mne/bem.py
- mne/io/bti/bti.py
improved comments on bem doc. closes #2478.
> DOC: more doc

- mne/viz/ica.py
The ref_meg channels are no longer shown. Issue https://github.com/mne-tools/mne-python/issues/2509
> Fix to ica.plot_sources.

- mne/viz/raw.py
Bad channel labels on raw plot are now gray. Makes it more consistent with epochs plot.
> [MRG] Bad channel names gray.

- doc/whats_new.rst
- mne/epochs.py
- mne/io/base.py
- mne/tests/test_docstring_parameters.py
> [MRG] Depr preload_data

- mne/chpi.py
- mne/io/base.py
- mne/io/fiff/tests/test_raw.py
- mne/simulation/raw.py
- mne/simulation/tests/test_raw.py
Tweak raw simulation with cHPI on to indicate that the coils were actually on.
> MRG: Tweak simulation

- doc/whats_new.rst
- mne/io/base.py
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
- mne/io/kit/kit.py
> FIX: Unify BrainVision reading

- doc/whats_new.rst
- examples/visualization/plot_evoked_erf_erp.py
- mne/evoked.py
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
Issue https://github.com/mne-tools/mne-python/issues/2491.
Left click is used to paint an area, but a small selection area doesn't draw the topomaps so there shouldn't be problems when trying to click a line. As far as I know there is no easy way of implementing Spanselector for right click.
> Topomap from evoked plot

- .travis.yml
- mne/stats/regression.py
Hopefully this makes Travis happy
> FIX: Fix division

- mne/viz/tests/test_ica.py
- mne/viz/topomap.py
Take over from https://github.com/mne-tools/mne-python/pull/2336.
> [MRG] Autoselect ch type

- mne/io/bti/bti.py
- mne/io/bti/tests/test_bti.py
- fix coord frames on no convert
- facilitate accessing partial information without reading raw
> WIP/ENH: more bti tweaks

- mne/commands/__init__.py
- mne/commands/mne_compare_fiff.py
- mne/commands/tests/test_commands.py
- mne/commands/utils.py
- mne/io/base.py
- mne/io/fiff/raw.py
Useful little utility to do e.g. `mne compare_fiff test_raw.fif test_raw_sss.fif`.
> MRG: Add compare_fiff

- doc/python_reference.rst
- doc/whats_new.rst
- mne/__init__.py
- mne/forward/_make_forward.py
- mne/label.py
- mne/simulation/raw.py
- mne/simulation/source.py
- mne/source_estimate.py
- mne/source_space.py
- mne/surface.py
- mne/tests/test_source_space.py
- mne/tests/test_utils.py
- mne/utils.py
One more thing to sneak into 0.10 :)
cc @dengemann @agramfort
> MRG: Add source space morphing

- mne/connectivity/tests/test_spectral.py
This is a stupid workaround, but it's better than having Travis time out.
> FIX: Travis workaround

- doc/whats_new.rst
- examples/preprocessing/plot_corrmap_detection.py
- mne/cov.py
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- mne/tests/test_import_nesting.py
- mne/tests/test_utils.py
- mne/time_frequency/ar.py
- mne/utils.py
See #1985 and discussion there.
I've only fixed a few minor things that went broke with the streamlining done by @dengemann and @Eric89GXL.
Passes tests on my machine, and works on my sample data.
Anybody wanna give it a try?
> MRG: More work on Corrmap

- mne/decoding/time_gen.py
See https://github.com/mne-tools/mne-python/issues/2535
> BUG: fix error withttesting_time<n_jobs

- examples/plot_from_raw_to_epochs_to_evoked.py
- mne/evoked.py
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
> ENH: Add gfp plot

- mne/chpi.py
- mne/cov.py
- mne/filter.py
- mne/io/array/tests/test_array.py
- mne/preprocessing/ica.py
- mne/simulation/source.py
- mne/simulation/tests/test_raw.py
- mne/source_space.py
- mne/tests/test_chpi.py
- mne/tests/test_coreg.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
- mne/tests/test_import_nesting.py
- mne/tests/test_source_space.py
- mne/time_frequency/tests/test_psd.py
- mne/utils.py
- mne/viz/tests/test_epochs.py
- mne/viz/tests/test_raw.py
We'll see if the CIs are happy first, then this might fix the buildbot.
> MRG: Backports

- mne/forward/forward.py
- mne/forward/tests/test_forward.py
Closes https://github.com/mne-tools/mne-python/issues/2493
> [MRG] apply_forward_raw takes info instead of raw_template.

- examples/forward/plot_source_space_morphing.py
- mne/datasets/utils.py
- mne/io/bti/bti.py
- mne/source_estimate.py
- mne/source_space.py
- mne/tests/test_source_space.py
@agramfort can you test the example?
> ENH: BTI tweaks and source space morphing work

- doc/whats_new.rst
- examples/visualization/make_report.py
- examples/visualization/plot_report_slider.py
- mne/report.py
- mne/tests/test_report.py
Add the ability to create a general html slider with a list of figs. This can be expanded for a list of images as well.
This is currently functional. Feel free to take over the pr if it requires non-trivial reworking since I'm a bit occupied with things.
> [MRG] General Image Slider

- mne/io/meas_info.py
- mne/preprocessing/ica.py
Closes #2558.
@sstober can you see if it works for you? Works over here.
> FIX: Clean old bads

- examples/visualization/plot_clickable_image.py
- examples/visualization/plot_topography.py
- mne/decoding/base.py
> [MRG] Fixed plot_topography example.

- mne/epochs.py
- mne/viz/epochs.py
- mne/viz/ica.py
Closes https://github.com/mne-tools/mne-python/issues/2556
> [MRG] Epochs browser loads data on horizontal shift.

- examples/visualization/plot_clickable_image.py
- mne/viz/topo.py
Closes https://github.com/mne-tools/mne-python/issues/2567
> Fix to clickable image example.

- mne/io/base.py
- mne/viz/__init__.py
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
Closes https://github.com/mne-tools/mne-python/issues/2553.
The problem with IAS channels in the beginning of data makes using ``iter_topography`` for custom plots really annoying, but because the function does exactly as the docs say, I didn't want to change it. Instead I made a function for plotting the psd of raw data as topography.
> [MRG] Raw psd as topography.

- mne/io/edf/edf.py
> Bit 17 - EDF

- .travis.yml
- appveyor.yml
> FIX: Force path

- doc/whats_new.rst
- examples/preprocessing/plot_maxwell_filter.py
- mne/evoked.py
- mne/io/pick.py
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
- mne/viz/utils.py
Requires `testing` and `sample` dataset updates. @agramfort feel free to try the example and see if it's good enough for you now :)
cc @wronk feel free to have a look and review. Note that I refactored a bit to have chunked data processing instead of processing everything at once. This should reduce memory requirements by a factor of ~2.
> ENH: Maxwell filter component regularization

- .travis.yml
- doc/sphinxext/numpy_ext/docscrape.py
- mne/connectivity/spectral.py
- mne/decoding/base.py
- mne/epochs.py
- mne/fixes.py
- mne/io/brainvision/brainvision.py
- mne/parallel.py
- mne/preprocessing/ica.py
- mne/preprocessing/maxwell.py
- mne/realtime/epochs.py
- mne/tests/test_docstring_parameters.py
- mne/utils.py
- mne/viz/_3d.py
- mne/viz/epochs.py
Closes #2603.
@ignatenkobrain can you see if this fixes your issue?
> FIX: Fixes for Py35

- mne/__init__.py
- mne/channels/channels.py
- mne/evoked.py
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
- mne/utils.py
> MRG : Add generic grand_average

- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
Fix bug where corrmap with `plot=False, show=False` fails.
> MRG Fix corrmap no-plot bug

- mne/datasets/utils.py
Fixed issue #2609 by changing the hash value of the sample data set
> Fix: changed sample hash to correct value

- mne/tests/test_report.py
> FIX: 3.5/mpl workaround

- mne/decoding/base.py
- mne/decoding/time_gen.py
Some small changes to the docstrings in decoding I thought would be beneficial.
> Small changes to the docstrings in decoding

- doc/whats_new.rst
- mne/report.py
closes #2611
cc @agramfort @jaeilepp
> FIX:  report render bem

- doc/advanced_setup.rst
Changed the Martinos path to the Anaconda distribution and encouraged Martinos users to join the mailing list.
> Updating the Advanced Installation page

- doc/whats_new.rst
- mne/preprocessing/ecg.py
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ecg.py
- mne/preprocessing/tests/test_ica.py
- mne/viz/ica.py
- mne/viz/tests/test_ica.py
cc @Eric89GXL @agramfort @jona-sassenhagen 
work in progress.
> MRG+1: serialize labels for ICA, plot labels and fix ECG guessing (broken)

- mne/preprocessing/ecg.py
- mne/viz/ica.py
- tutorials/plot_ica_from_raw.py
> some more fixes on ICA labels viz

- mne/decoding/csp.py
> Simplified CSP algorithm

- mne/decoding/csp.py
Here's the fix for #2630. Sorry about that. I'll create a test to avoid this error in the future in a separate PR.
> Fix bug in index resorting

- doc/python_reference.rst
- mne/channels/channels.py
- mne/channels/tests/test_layout.py
- mne/coreg.py
- mne/forward/_make_forward.py
- mne/forward/forward.py
- mne/io/__init__.py
- mne/io/meas_info.py
- mne/io/tests/test_pick.py
- mne/preprocessing/tests/test_ica.py
- mne/realtime/fieldtrip_client.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
Just filling out some last bits of information about `Info`.
Closes #2287.
> MRG+1: Fix information about info

- doc/whats_new.rst
- mne/epochs.py
- mne/tests/test_epochs.py
> MRG: Tweak reject API

- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
Some minor tweaks to make Maxwell filtering a tiny bit faster. Also another validation of our basis calculations.
@wronk you want to have a look? Thanks @jnenonen and @staulu for the discussions about all this.
> MRG: Faster basis calculation

- mne/viz/ica.py
- tutorials/plot_ica_from_raw.py
bring back ica component numbers in plot_sources_evoked
cc @jaeilepp @Eric89GXL
> ENH: viz tweaks

- mne/channels/tests/test_layout.py
- mne/io/array/tests/test_array.py
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
- mne/io/bti/bti.py
- mne/io/bti/tests/test_bti.py
- mne/io/ctf/info.py
- mne/io/ctf/tests/test_ctf.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/egi/egi.py
- mne/io/egi/tests/test_egi.py
- mne/io/fiff/tests/test_raw.py
- mne/io/kit/kit.py
- mne/io/kit/tests/test_kit.py
- mne/io/meas_info.py
- mne/io/nicolet/nicolet.py
- mne/io/nicolet/tests/test_nicolet.py
- mne/io/tests/test_raw.py
- mne/realtime/fieldtrip_client.py
- mne/tests/test_epochs.py
Closes https://github.com/mne-tools/mne-python/issues/2151.
I made a function for testing different kind of readers. The filtering precision probably depends on the data a lot, so I'm not sure if it should be included here or tested separately for each reader. What do you think? For now it is implemented only for nicolet reader, but I will implement for others too once we have tuned this and if you think it's useful.
Also included a small optimization for ``test_epochs``.
> [MRG] Test refactoring

- mne/bem.py
- mne/tests/test_bem.py
Maybe could have saved @agramfort some pain. Better late than never I guess.
> MRG: Warn if head size is too large

- mne/io/meas_info.py
If you don't do this, all the channel locations will be same even if you modify them
> FIX chan locs in create_info

- mne/io/reference.py
> MRG: Fix epochs type in reference

- mne/epochs.py
- mne/forward/forward.py
- mne/preprocessing/stim.py
Fixing ```isinstance(inst, Epochs)``` by subbing in ```_BaseEpochs```. I think I got them all.
> Type fix _BaseEpochs

- mne/viz/evoked.py
Works on my data, works on example, let's see what Travis says.
Closes #2694
> MRG: Fix nonalphabetically sorted chan names for spatial_colors legend

- doc/advanced_setup.rst
- doc/getting_started.rst
- mne/channels/montage.py
- tutorials/plot_introduction.py
Closes #2042.
Closes #1225.
@teonlamont I think this is what @agramfort was hinting at, see if it's good enough for you. We can also change the `__repr__` in some meaningful way if you want, but I couldn't think of a better one.
> MRG: Fix docstring

- .travis.yml
- mne/epochs.py
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
- mne/tests/test_epochs.py
Some minor tweaks I came across when re-reading the code.
> FIX: Minor fixes for Maxwell filtering

- mne/io/base.py
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
Noticed a bug. If you try ``mne.viz.plot_raw(raw)``, it failed because ``n_channels=None``.
> [MRG] Bug fix with plot_raw

- mne/io/ctf/ctf.py
- mne/io/ctf/tests/test_ctf.py
Closes #2698.
Unfortunately we don't have the files to add a test for this, but it works with the user's dataset.
> MRG: Minor fix for CTF systems

- mne/preprocessing/ica.py
> [MRG+2] Force ica.n_samples_ to int during serialization

- doc/this_project.inc
- mne/datasets/utils.py
- mne/tests/test_utils.py
- mne/utils.py
@jasmainak hopefully this helps. For some reason the resuming does not work properly, though. It resumes at a reasonable place, but the hash won't match and the archive won't decompress. Not sure why it's happening. But this is probably already worth merging, since it at least allows the user to see progress properly, while only adding a minor inconvenience for PRs that require a testing dataset update.
Closes #2706.
> MRG: Allow data size for testing dataset

- doc/whats_new.rst
- mne/evoked.py
- mne/tests/test_evoked.py
> [MRG+2]: fix bad ch_names due to picks in get_peaks

- mne/channels/montage.py
- mne/channels/tests/test_montage.py
@Eric89GXL I updated the docstring here a bit to fix some of the errors. It still make need to be flushed out better but I figured this is a start.
> [MRG] Update montage.py

- doc/python_reference.rst
- doc/whats_new.rst
- mne/epochs.py
- mne/io/__init__.py
- mne/viz/__init__.py
- mne/viz/epochs.py
Closes #2730.
@agramfort works for me, ready for review/merge. Didn't add a test because it's for a `viz` function.
> MRG: Fix drop log plot

- mne/viz/raw.py
Closes https://github.com/mne-tools/mne-python/issues/2731.
Are we happy with this?
> [MRG][FIX] Hack to work around conflict with seeg fiff constant.

- mne/preprocessing/tests/test_maxwell.py
@wronk can you have a quick look? I didn't realize that mags (only) were supposed to be used to calculate the shielding factor. This gives us more reasonable shielding values, do you agree?
> MRG: Use mags for shielding factor

- mne/source_space.py
Fixes a deprecated way of using `ravel` and streamlines our code a bit.
> MRG: Fix deprecated ravel

- mne/viz/evoked.py
Closes https://github.com/mne-tools/mne-python/issues/2742
> [MRG] Fix to gfp with ylim.

- mne/io/brainvision/brainvision.py
- mne/io/bti/bti.py
- mne/io/egi/egi.py
- mne/io/kit/kit.py
- mne/io/tests/test_raw.py
- mne/io/utils.py
Closes https://github.com/mne-tools/mne-python/issues/2691.
Refactored kit and egi so far...
> [FIX][MRG+1] Read raw in 100mb blocks

- examples/visualization/plot_joint_evoked_topomap.py
- mne/evoked.py
- mne/viz/evoked.py
- mne/viz/tests/test_topo.py
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
- mne/viz/utils.py
Add a viz function for a joint topo and butterfly plot, EEGLAB style, see #2664
Try it with ```mne.viz.evoked.joint_plot(evoked)```.
Edit: now also with a method, `evoked.plot_joint()`
> [MRG] Implement joint_plot

- mne/viz/evoked.py
Closes https://github.com/mne-tools/mne-python/issues/2776
> [MRG] Fix to spatial colors legend.

- doc/whats_new.rst
- mne/dipole.py
- mne/viz/_3d.py
> MRG: Remove mesh_color parameter from plot_dipole_locations

- doc/whats_new.rst
- mne/commands/tests/test_commands.py
- mne/connectivity/spectral.py
- mne/cov.py
- mne/dipole.py
- mne/epochs.py
- mne/evoked.py
- mne/inverse_sparse/tests/test_mxne_inverse.py
- mne/io/__init__.py
- mne/io/base.py
- mne/io/fiff/__init__.py
- mne/io/fiff/raw.py
- mne/io/tests/test_raw.py
- mne/simulation/evoked.py
- mne/source_estimate.py
- mne/tests/test_epochs.py
- mne/time_frequency/psd.py
- mne/time_frequency/tfr.py
- mne/utils.py
> MRG: Unify crop and Epochs constructor

- mne/tests/test_utils.py
- mne/utils.py
> ENH: Allow printing of valid keys

- doc/whats_new.rst
- mne/channels/channels.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/datasets/utils.py
- mne/io/kit/kit.py
- mne/io/meas_info.py
- mne/tests/common.py
> MRG+1: Add FIF montage reading

- mne/viz/evoked.py
Fix docstring for evoked plotting lims. Alternative to #2823
(Sorry if this isn't the proper way ...)
@jasmainak @teonlamont
> DOC: evoked.plot_ plot lim docs

- doc/manual/channel_interpolation.rst
- doc/manual/index.rst
- doc/manual/interp.rst
- doc/whats_new.rst
- mne/channels/interpolation.py
> MRG: spline interp fixes

- doc/whats_new.rst
- mne/epochs.py
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
> MRG: Fix projector removal

- doc/whats_new.rst
- mne/decoding/tests/test_time_gen.py
- mne/decoding/time_gen.py
Pretty bad mistake on my part. Here's a fix
> [MRG+1] FIX: bug non passed parameter

- mne/decoding/tests/test_csp.py
> MRG: Make test more lenient

- mne/channels/channels.py
- mne/channels/tests/test_channels.py
> MRG: Fix raw setting

- mne/io/pick.py
- mne/io/tests/test_pick.py
- mne/viz/raw.py
> MRG: Fix picking

- doc/whats_new.rst
- mne/epochs.py
- mne/io/proj.py
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
- mne/tests/test_epochs.py
Some minor fixes to `maxwell_filter`.
> MRG: Fix translation

- mne/epochs.py
- mne/io/meas_info.py
- mne/io/proj.py
- mne/io/tag.py
This should universally speed up our FIF reading functions at least a little bit. On `master` `test_read_write_epochs` takes ~15 sec and on this PR it takes ~13. So a small improvement, but worthwhile. It also makes the code a little bit easier to parse.
> MRG: Faster reading

- doc/whats_new.rst
- mne/cov.py
- mne/evoked.py
- mne/inverse_sparse/_gamma_map.py
- mne/inverse_sparse/tests/test_gamma_map.py
- mne/preprocessing/tests/test_maxwell.py
- mne/tests/test_cov.py
- mne/tests/test_epochs.py
- mne/tests/test_utils.py
- mne/utils.py
Hopefully this makes our CIs more robust and actually pass.
> MRG: Fix tests

- mne/io/bti/bti.py
- mne/io/bti/tests/test_bti.py
Reimplementing some changes that got lost in the last month due to missing test.
> MRG+1: partial info construction if no pdf_file is available

- mne/tests/test_dipole.py
- mne/utils.py
> MRG: Fix warning filtering

- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
> MRG: Allowing missing chs in maxwell filter

- mne/datasets/utils.py
WIP until we fix permissions on the new location.
> WIP: Fix paths

- mne/time_frequency/psd.py
- mne/time_frequency/tfr.py
This is to fix the Debian build. These are the only places I think it can fail.
> [MRG] Removed ellipsis with time_mask.

- mne/viz/topomap.py
@Eric89GXL try again...
floating point rounding-safe way of getting time points to plot in `plot_topomap`
closes #2901
> have topomap use _time_mask

- mne/evoked.py
- mne/viz/topo.py
Continuation for https://github.com/mne-tools/mne-python/pull/2824.
> [MRG] Fix to docstring

- doc/whats_new.rst
- mne/bem.py
- mne/channels/layout.py
- mne/channels/tests/test_layout.py
- mne/preprocessing/maxfilter.py
- mne/simulation/raw.py
- mne/tests/common.py
- mne/tests/test_bem.py
Ready for review/merge from my end @dengemann.
> MRG: Allow fitting "auto" mode and units

- doc/python_reference.rst
- mne/evoked.py
- mne/viz/evoked.py
it should have been like that in the first place, no deprecation needed.
> FIX: public API for joint plot in viz (following common patterns)

- mne/datasets/utils.py
- mne/io/ctf/ctf.py
- mne/io/ctf/eeg.py
- mne/io/ctf/tests/test_ctf.py
I used this reader for extracting hpi points for bst auditory tutorial to help with the coregistration. The original hpi points seem messed up (only five points available and coregistration doesn't seem to line up). 
I checked the results with @agramfort and they seem surprisingly good. I'm not sure this is the right way to do it or if we even want something like this for the ctf reader.  Maybe @Eric89GXL has some insight.
> [MRG] Read ctf digitizer points from .pos file.

- mne/datasets/utils.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
@kingjr can you try this?
@teonlamont can you have a look to see if it makes sense to you? The conditional is kind of awful, but I think it's correct.
AFAICT we currently don't have any test files that actually test that this warning gets thrown. @kingjr do you have some small sample EDF/BDF file that we could add to the testing dataset to hit this warning? We've had problems with these lines not being tested before.
> MRG: EDF warning

- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
No test added yet because I need #2928 fixed first.
> MRG: Fix bounds check

- mne/io/bti/bti.py
- mne/io/bti/tests/test_bti.py
cc @Eric89GXL this fixes a bug that's been existing since you added the preloading functionality.
And another test.
> MRG+1: reading raw if channels are not reordered

- mne/io/base.py
- mne/io/bti/tests/test_bti.py
- mne/tests/test_utils.py
A couple of minor test tweaks to make the CIs happy. Will merge if it comes back okay.
> FIX: Fix tests

- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
> [MRG+2] Ica proj mat2

- doc/whats_new.rst
- mne/io/compensator.py
- mne/io/ctf/info.py
- mne/io/ctf/tests/test_ctf.py
So far I just fixed some normal stuff. @agramfort do you want to review and merge this now, or should I tackle #2937 here, too?
> MRG: Fix CTF normals

- mne/viz/tests/test_topo.py
- mne/viz/topo.py
This uses collections and a single axis to speed up topo plottting. So far it took a simple Neuromag example from ~12 sec to ~2 sec on my machine.
Todo:
BTW we should also look into using collections for raw.plot. It could speed it up. I plan to do it soon.
> MRG: Faster topo plotting

- doc/whats_new.rst
- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/pick.py
taking over #2949 for using _pick_data_channels
just for the day we add the ecog channel type...
> Fix raw filter pick seeg

- circle.yml
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
I don't know when ``plot_psd_topo`` stopped working, but here is a fix to it. Also,  seems that megsim downloading wasn't included in circle, so it's included here.
> [MRG][FIX] Fixes to psd_topo and added megsim data download to circle.

- circle.yml
- mne/datasets/utils.py
Turns out that megsim dataset also needed an approval from the user.
> [MRG] Force update of dataset path for circleci.

- mne/viz/epochs.py
- mne/viz/evoked.py
- mne/viz/ica.py
- mne/viz/raw.py
Closes #2919.
Ready for review/merge from my end. @jaeilepp do you have time to look?
Running `plot_from_raw_to_epochs_to_evoked` with `import seaborn` added to the top, before/after:
> MRG+2: Better zorder

- mne/epochs.py
- mne/io/array/array.py
- mne/io/array/tests/test_array.py
- mne/tests/test_epochs.py
Two minor fixes in one PR to (hopefully) save reviewer and CI time.
Closes #2858.
Closes #2855.
> MRG+1: Fix reject check

- mne/preprocessing/ica.py
> fix typo in ica docstring

- mne/time_frequency/multitaper.py
@jaeilepp see the minor fix, just needed to set the dims properly.
We could fix `dpss` so that it's always 2D at some point, too.
Closes #2967.
> FIX: FFT memory

- mne/forward/forward.py
- mne/forward/tests/test_forward.py
> FIX: resolves issue with restrict_forward_to_label

- mne/io/base.py
> [MRG] FIX filename splitting

- circle.yml
- mne/datasets/brainstorm/bst_auditory.py
- mne/datasets/brainstorm/bst_raw.py
- mne/datasets/brainstorm/bst_resting.py
- mne/datasets/utils.py
Closes https://github.com/mne-tools/mne-python/issues/2981
> [MRG] Updated urls.

- mne/datasets/utils.py
Forgot that I also changed the spm path. My bad. Merging
> Updated hash.

- doc/python_reference.rst
- mne/__init__.py
Closes https://github.com/mne-tools/mne-python/issues/2983#issuecomment-192182428
> [MRG+1] FIX: `concatenate_epochs` available from mne

- doc/whats_new.rst
- mne/epochs.py
- mne/viz/epochs.py
- mne/viz/tests/test_epochs.py
This closes #2809. I did not add tests as they are already taken care at `viz.tests`. 
@teonlamont @jona-sassenhagen please review when you have time.
> [MRG+1] Added plot_image method in epoch, calling plot_epochs_image from viz

- .travis.yml
- mne/decoding/base.py
- mne/decoding/csp.py
- mne/evoked.py
- mne/preprocessing/ica.py
- mne/time_frequency/tfr.py
- mne/viz/topomap.py
Updated the scipy version and fixed some PEP8 violations that had sneaked through.
Let's see if travis passes now.
> Travis fix

- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
Closes #2976.
@kambysese can you confirm this works for you? It seems to work for both `bad_306a_am_raw` and `bad_129a_am_raw` that you sent me.
> FIX: More tolerant

- doc/sphinxext/cited_mne.py
Probably a better place for it to be to match up with `flow_diagram.py` anyway
> MRG: Move so doctest doesnt use it

- MANIFEST.in
Closes https://github.com/mne-tools/mne-python/issues/3022
Is this what was wanted?
> Added kit2fiff.json to MANIFEST.

- .gitignore
- mne/epochs.py
- mne/tests/test_epochs.py
Taking over #2486. Ready for review/merge.
> MRG: Offset when decimating

- doc/index.rst
- examples/realtime/plot_compute_rt_average.py
- mne/io/constants.py
Closes https://github.com/mne-tools/mne-python/issues/3025
The mayavi figure problem seems to have fixed itself. See https://circle-artifacts.com/gh/mne-tools/mne-python/501/artifacts/1/home/ubuntu/mne-python/doc/_build/html/auto_examples/index.html
Now trying to replicate the success for stable 0.11.
> [MRG] Fixes to example and website + constant.

- circle.yml
Closes #3029.
Let's see if this works.
> ENH: Build non-plots for PRs

- mne/viz/evoked.py
- mne/viz/topomap.py
> MRG: _find_peaks and _plot_joint picks fix

- examples/forward/plot_coregistration_transform.py
- examples/visualization/plot_meg_sensors.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
So far I've modified the example and it looks good.
Before:
After:
I'm thinking of adding to the example to plot layouts from other systems since we have those now. Think it's worthwhile? I guess I should at least beef up the tests so that our coverage doesn't take a hit.
Closes #2330.
> MRG: Draw sensors

- doc/whats_new.rst
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/meas_info.py
> MRG: Fix anonymization

- mne/event.py
- mne/tests/test_event.py
> MRG: Fix stim

- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
Since https://github.com/mne-tools/mne-python/pull/3031 is now merged, might as well systematically use the decimation function at the lowest possible level in all cases.
> ENH: decim wavelet at lowest level

- examples/time_frequency/plot_time_frequency_sensors.py
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
- mne/viz/raw.py
Bug created by https://github.com/mne-tools/mne-python/pull/3034
Identified in https://github.com/mne-tools/mne-python/pull/3033#issuecomment-199816018
* fixed bug
* added more exhaustive testing
* fix example plotting (unrelated viz issue)
> FIX: bug in the decimation of the time frequency decomposition 

- doc/whats_new.rst
- mne/epochs.py
- mne/time_frequency/tfr.py
- mne/viz/raw.py
- mne/viz/tests/test_topo.py
- mne/viz/topo.py
Now all the topo_plots use Eric's speedier unified axis.
EDIT:
Closes https://github.com/mne-tools/mne-python/issues/2953
> [MRG] Speedup topos

- circle.yml
Needed for one of the examples, see the bad logging that shows up in the example here:
https://circle-artifacts.com/gh/mne-tools/mne-python/543/artifacts/1/home/ubuntu/mne-python/doc/_build/html/auto_examples/preprocessing/plot_movement_compensation.html#sphx-glr-auto-examples-preprocessing-plot-movement-compensation-py
@jaeilepp feel free to merge if you agree.
Also, it looks like we're getting errors on `master` with the uploading step, the key is getting rejected...?
> MRG: Add misc to circle data

- mne/preprocessing/ica.py
Closes #3052.
@dengemann feel free to merge if you're happy.
> MRG: Remove extra copy

- circle.yml
- doc/Makefile
Also, doesn't push on example failure and removed some data that is not used.
> Dev docs pushed to master branch.

- circle.yml
- examples/visualization/plot_meg_sensors.py
Closes https://github.com/mne-tools/mne-python/issues/3056
> Fix paths in plot_meg_sensors.

- doc/whats_new.rst
- mne/label.py
- mne/tests/test_label.py
> MRG: Fix sign flip

- circle.yml
> Fix to circle

- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
Ready for review/merge @teonbrooks.
Closes #3070.
> MRG: Deprecate get_brainvision_events

- doc/whats_new.rst
- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
A start. Partially adresses #3070.
As simple as this right? @teonbrooks @kingjr 
~~Missing test.~~ (Actually simplifies the tests ...)
> MRG raw.filter copy param

- mne/epochs.py
- mne/evoked.py
- mne/filter.py
- mne/io/base.py
- mne/io/fiff/raw.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/tests/test_evoked.py
Lots of minor docstring fixes.
Closes #3070.
> MRG: Minor fixes to docstring and more copy params

- doc/whats_new.rst
- mne/stats/regression.py
> MRG: Add cholesky solver for rERP

- doc/whats_new.rst
- mne/epochs.py
- mne/evoked.py
- mne/stats/regression.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
> MRG: Fix regression type

- README.rst
> MRG Update README.rst

- doc/whats_new.rst
- mne/io/edf/edf.py
> Fix highpass filter storage

- mne/surface.py
- mne/tests/test_surface.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
A few minor fixes for `plot_trans` I needed to get through an example.
> MRG: Fixes for coreg

- mne/epochs.py
closes #3099 . ready for review @agramfort
> DOC: Epochs.next and Epochs.iter_evoked

- mne/decoding/transformer.py
- mne/io/pick.py
- mne/io/tests/test_pick.py
closes #3103
Surely my most interesting PR ever.
> Check type==bool for pick_types

- mne/io/base.py
it's a follow up on a question I got during my lectures in Lyon this week...
> Filter warning

- mne/epochs.py
- mne/evoked.py
> DOC: clarify handling of conditions

- doc/whats_new.rst
- examples/simulation/plot_simulate_evoked_data.py
- examples/time_frequency/plot_compute_raw_data_spectrum.py
- examples/time_frequency/plot_temporal_whitening.py
- examples/visualization/plot_evoked_topomap_delayed_ssp.py
- examples/visualization/plot_ssp_projs_sensitivity_map.py
- examples/visualization/plot_ssp_projs_topomaps.py
- mne/commands/mne_browse_raw.py
- mne/datasets/utils.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/proj.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
- mne/tests/test_proj.py
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
Closes https://github.com/mne-tools/mne-python/issues/3117
I updated the datasets, but made a new file with version number 1 to aws so that the old one didn't get overwritten. Perhaps the old one can be removed when this gets merged?
> Fix plotting of grad projectors. Updated datasets.

- mne/epochs.py
- mne/evoked.py
- mne/io/base.py
- mne/io/cnt/tests/test_cnt.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/preprocessing/maxwell.py
- mne/source_estimate.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
- mne/tests/test_source_estimate.py
> MRG: Mixin time_as_index

- examples/visualization/plot_ssp_projs_sensitivity_map.py
- mne/proj.py
- mne/tests/test_proj.py
> MRG: Fix proj

- doc/whats_new.rst
- mne/forward/tests/test_make_forward.py
- mne/source_space.py
- mne/tests/test_source_space.py
No fix yet, just currently adds code to demonstrate the error referred to by #3140.
> MRG: Fix surf ori

- doc/manual/cookbook.rst
- doc/manual/preprocessing/annotations.rst
- doc/tutorials.rst
- doc/whats_new.rst
- examples/datasets/plot_brainstorm_auditory.py
- mne/annotations.py
- mne/cov.py
- mne/epochs.py
- mne/io/base.py
- mne/io/eeglab/eeglab.py
- mne/io/kit/kit.py
- mne/preprocessing/ecg.py
- mne/preprocessing/eog.py
- mne/preprocessing/ica.py
- mne/realtime/epochs.py
- mne/stats/regression.py
- mne/tests/test_epochs.py
- mne/viz/raw.py
- mne/viz/utils.py
- tutorials/plot_brainstorm_auditory.py
The annotation descriptions are also visible in ``raw.plot``.
> [MRG] Epoch rejection by annotations.

- mne/evoked.py
Allows e.g. `for x in range(2): evoked.copy().detrend(x).plot()`
> WIP evoked.detrend return self

- doc/whats_new.rst
- mne/selection.py
- mne/tests/test_selection.py
> MRG: Allow read_selection to deal with new style names

- .gitignore
- doc/manual/memory.rst
- doc/whats_new.rst
- examples/inverse/plot_tf_lcmv.py
- examples/plot_from_raw_to_epochs_to_evoked.py
- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_dics.py
- mne/beamformer/tests/test_lcmv.py
- mne/decoding/ems.py
- mne/epochs.py
- mne/minimum_norm/tests/test_time_frequency.py
- mne/preprocessing/ssp.py
- mne/tests/test_epochs.py
- mne/utils.py
- mne/viz/epochs.py
- mne/viz/tests/test_epochs.py
- tutorials/plot_artifacts_correction_rejection.py
- tutorials/plot_brainstorm_auditory.py
- tutorials/plot_object_epochs.py
the idea is to remove the work epochs in a method that belongs to the Epochs class.
I find it cleaner this way but you can object :)
> MRG: Epochs API

- doc/python_reference.rst
- mne/forward/__init__.py
- mne/forward/_make_forward.py
- mne/forward/forward.py
- mne/forward/tests/test_make_forward.py
@jona-sassenhagen where did you see `do_forward_solution` in a tutorial?
> MRG: Deprecate do_forward_solution

- tutorials/plot_eeg_erp.py
- tutorials/plot_epoching_and_averaging.py
- tutorials/plot_visualize_evoked.py
Adding a bit to the tutorials.
@agramfort this what you were thinking about?
> MRG Extend tutorials - HED epochs, evoked plots and arithmetic

- mne/stats/parametric.py
Fix some simple typos in the comments.
> DOC: Correct typos

- doc/_static/style.css
- doc/manual/pitfalls.rst
@Eric89GXL @agramfort as requested, an updated color scheme for the docs (and a single-character typo fix).  LMK what you think.
> MRG: new color scheme for docs

- tutorials/plot_epoching_and_averaging.py
Compare lines 47 and 86.
Please merge before 0.12 :)
> MRG: Minor - epoching tutorial homogenous event_ids

- doc/manual/migrating.rst
> MRG: Minor - copy param in eeglab docs

- mne/viz/evoked.py
- tutorials/plot_artifacts_correction_ica.py
- tutorials/plot_artifacts_correction_rejection.py
- tutorials/plot_brainstorm_auditory.py
@agramfort see if you think it's clearer.
> MRG: Remove raw.index_as_time

- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
~~WIP, probably needs a test.~~
Long term, could possibly be refactored to share more code with EEGLAB.
@bburle, @teonbrooks
closes #2778
> MRG Make event_id compatible with response_trig_shift in BV event parser

- tutorials/plot_artifacts_correction_maxwell_filtering.py
- tutorials/plot_visualize_evoked.py
Too much text in comments, two almost-identical images ... This should be better. Please merge for 0.12.
> MRG: Minor - wording and redundancy on evoked visualization tutorial

- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
closes https://github.com/mne-tools/mne-python/issues/3187
> BUG: cwt_morlet decim

- doc/whats_new.rst
- mne/event.py
- mne/tests/test_event.py
Taking over #3173 from @jhouck to get into 0.12.
> MRG: Allow make_fixed_length_events to not have first_samp added

- mne/viz/raw.py
- mne/viz/tests/test_raw.py
Does two things:
1. Adds `SEEG` and `ECoG` to `raw.plot_psd`, which formely just did mag/grad/eeg.
2. Allows for a list of axes to be passed when `picks=None`.
> MRG: Fix raw PSD

- mne/event.py
- mne/tests/test_event.py
> MRG: warn when read_events drops/masks events; allow mask=None

- mne/epochs.py
- mne/tests/test_epochs.py
Fix a little bug where you try to EQ and there are no events of one type.
> FIX: Fix epoch eq with no events

- doc/_templates/class.rst
- doc/sphinxext/numpy_ext/docscrape.py
- mne/channels/channels.py
- mne/dipole.py
- mne/epochs.py
- mne/io/base.py
- mne/tests/test_docstring_parameters.py
- mne/utils.py
This adds documentation of `__contains__`, `__getitem__`, `__iter__`, and `__len__` to our docs.
Closes #2998.
> MRG: Document special members

- mne/baseline.py
- mne/epochs.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/tests/test_epochs.py
> MRG: Stricter baseline checks

- .travis.yml
- codecov.yml
Let's see if we can get coverage on 3.5 or if it's still painfully slow.
> MRG: Coverage for 2.6

- README.rst
Fixes some minor issues with our README and pushes people to the website more.
> MRG: Better README [ci skip]

- mne/evoked.py
- mne/viz/evoked.py
Closes https://github.com/mne-tools/mne-python/issues/3100
> Added selectable parameter to evoked.plot.

- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- tutorials/plot_artifacts_correction_ica.py
Closes https://github.com/mne-tools/mne-python/issues/3252
closes https://github.com/mne-tools/mne-python/issues/3168
> [MRG] Fixes to ICA.

- mne/externals/tempita/_looper.py
- setup.cfg
avoids sphinx_gallery and sphinx_bootstap_theme strongs deps for make test-doc
> ignore conf.py for doctests 

- .travis.yml
- Makefile
Let's see if this works properly.
> ENH: Use codespell from PyPi

- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/data/test.vhdr
- mne/io/brainvision/tests/test_brainvision.py
Closes https://github.com/mne-tools/mne-python/issues/3302
> [MRG] Added Newton to brainvision units.

- Makefile
- circle.yml
- doc/conf.py
- doc/faq.rst
- doc/manual/cookbook.rst
- doc/manual/io.rst
- doc/manual/source_localization/inverse.rst
- doc/python_reference.rst
- doc/tutorials.rst
- doc/whats_new.rst
- mne/epochs.py
- mne/filter.py
- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/meas_info.py
- mne/stats/parametric.py
- tutorials/plot_artifacts_correction_filtering.py
- tutorials/plot_artifacts_correction_ica.py
- tutorials/plot_background_filtering.py
- tutorials/plot_brainstorm_auditory.py
- tutorials/plot_eeg_erp.py
- tutorials/plot_epochs_to_data_frame.py
- tutorials/plot_forward.py
- tutorials/plot_sensors_time_frequency.py
- tutorials/plot_stats_cluster_time_frequency_repeated_measures_anova.py
The to-do list for this PR:
This will be a follow-up PR:
Closes #3255.
Closes #3259.
Closes #3227.
> MRG: Revise filtering

- mne/simulation/evoked.py
- mne/simulation/tests/test_evoked.py
Correct the SNR computation in the simulation module
> FIX: fixes 3305

- mne/tests/test_utils.py
- mne/utils.py
@andrewheusser can you see if this fixes the issue for you?
Closes #2748.
> MRG: Safer config reading

- mne/tests/test_transforms.py
- mne/transforms.py
For consistency with other classes.
> API:  add Transform.save()

- doc/whats_new.rst
- mne/commands/mne_show_fiff.py
- mne/datasets/utils.py
- mne/io/open.py
- mne/tests/test_dipole.py
- mne/tests/test_utils.py
Closes #3317.
@christianbrodbeck can you see if it fixes the issue for you?
> FIX: Fix show_fiff

- doc/whats_new.rst
- mne/viz/_3d.py
The color (green) as in mne_analyze.
Before:
after:
> ENH viz.plot_trans: show HPIs

- doc/whats_new.rst
- mne/label.py
- mne/source_estimate.py
- mne/source_space.py
- mne/tests/test_label.py
- mne/tests/test_source_estimate.py
- mne/tests/test_source_space.py
@nfoti can you cross-check that it gives the same COM vertex numbers as your method?
Takes care of part of #3307.
Closes #3293.
> MRG: Add label center_of_mass

- doc/whats_new.rst
- mne/cov.py
- mne/defaults.py
- mne/epochs.py
- mne/tests/test_cov.py
- mne/tests/test_epochs.py
@kingjr can you have a look to see if this would have saved you some pain?
Closes #3286.
> MRG: Check MEG<->Head transform during cov calculation

- mne/label.py
- mne/simulation/evoked.py
- mne/simulation/raw.py
- mne/simulation/source.py
- mne/simulation/tests/test_source.py
- mne/source_estimate.py
~~Needs #3314 merged first.~~
Closes #3307.
> MRG: Add "center" option to simulate_sparse_stc

- mne/viz/ica.py
- mne/viz/topomap.py
Takeover from https://github.com/mne-tools/mne-python/pull/3328
> [MRG] ICA indexing

- doc/whats_new.rst
- mne/viz/tests/test_topo.py
- mne/viz/topo.py
Closes https://github.com/mne-tools/mne-python/issues/3330
> [FIX][MRG] Fix to plot_evoked_topo.

- mne/externals/h5io/_h5io.py
The h5py wrapper code did not support writing `scipy.sparse.csr_matrices` which is inconvenient because `SourceEstimate.compute_morph_matrix` returns a `csr_matrix`.
> Support reading/writing scipy.sparse.csr_matrix type from/to hdf5 files.

- .coveragerc
- doc/python_reference.rst
- doc/whats_new.rst
- mne/filter.py
- mne/fixes.py
- mne/io/base.py
- mne/tests/test_filter.py
- mne/tests/test_fixes.py
- tutorials/plot_background_filtering.py
This should give us more stable IIR filtering.
Closes #1941.
cc @teonbrooks @jona-sassenhagen @dengemann since you were originally interested in #1941.
> MRG: Add second-order sections filtering

- .travis.yml
- mne/tests/test_docstring_parameters.py
- mne/utils.py
In my doc updates I broke our docstring checker, this should fix it.
> FIX: Fix docstring tester

- circle.yml
I really have no idea how to fix the caching issue, but I'm a bit more confident of the automatic update working after this.
> [FIX] Attempt to fix circle.

- mne/defaults.py
- mne/source_estimate.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
Addresses https://github.com/mne-tools/mne-python/issues/3351: implement changes in the PySurfer API 
- replace use of `config_opts` (deprecated by pysurfer) with corresponding arguments
- add `time_unit` parameter to deprecate conversion of time to ms.
> [MRG] Update SourceEstimate.plot() API

- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
If you want I can make this PR bigger and add axes argument in more places. 
Also - take a look at the test I've added - it takes about 40 seconds, so I may be doing something wrong...
> add axes arg to plot_psds_topomap

- mne/cov.py
- mne/tests/test_cov.py
Closes https://github.com/mne-tools/mne-python/issues/3388
> [FIX] Allow method=None for covariance.

- doc/whats_new.rst
- mne/source_estimate.py
- mne/viz/_3d.py
CC @jaeilepp @Eric89GXL, depending on https://github.com/nipy/PySurfer/pull/158
> [MRG+1] SourceEstimate.plot() with initial_time parameter

- circle.yml
- examples/inverse/plot_dics_beamformer.py
- examples/inverse/plot_lcmv_beamformer.py
- examples/inverse/plot_time_frequency_mixed_norm_inverse.py
- mne/datasets/utils.py
- mne/viz/_3d.py
- tutorials/plot_brainstorm_auditory.py
- tutorials/plot_mne_dspm_source_localization.py
- tutorials/plot_stats_cluster_spatio_temporal.py
- tutorials/plot_stats_cluster_spatio_temporal_2samp.py
- tutorials/plot_stats_cluster_spatio_temporal_repeated_measures_anova.py
- tutorials/plot_visualize_evoked.py
Some minor tweaks to make the auto-build work better.
> MRG: Tweak auto-build

- doc/tutorials.rst
- tutorials/plot_point_spread.py
This addresses #3308. Feedback on making the example more clear and concise is greatly appreciated. If there is something glaringly missing from the tutorial then I'm happy to add it, but I do think it should be focused on corrupting a signal with point spread, not how to apply further analysis to the resulting data.
Thanks.
> MRG: Tutorial on corrupting known source-space signals with point spread.

- mne/epochs.py
- mne/viz/topomap.py
@jaeilepp added the missing axes args
> add missing axes params (`plot_psd_topomap` and related)

- doc/whats_new.rst
- examples/realtime/rt_feedback_server.py
- mne/realtime/stim_server_client.py
- mne/realtime/tests/test_stim_client_server.py
I wouldn't go for a deprecation as it's more of a bug fix (+ I'm lazy)
> FIX remove extra param in StimServer

- mne/viz/evoked.py
Closes https://github.com/mne-tools/mne-python/issues/3411
Now the layout is generated from channel positions if it is not detected when plotting with ``spatial_colors``.
> [MRG] Layout created for spatial_colors if not found.

- doc/python_reference.rst
We didn't give a good way to get to our generated command list. This provides it.
> MRG: Provide a link to commands [ci skip]

- mne/bem.py
- mne/commands/mne_coreg.py
- mne/coreg.py
- mne/forward/forward.py
- mne/gui/_coreg_gui.py
- mne/gui/_fiducials_gui.py
- mne/gui/_file_traits.py
- mne/gui/tests/test_coreg_gui.py
Working on https://github.com/mne-tools/mne-python/issues/3282. I think the scaling functionality has not been used much with MRIs other than fsaverage. 
This fixes the first error but the new subject is never created. I will keep looking into it.
Also, do we still need to run `mne_prepare_bem_model` with the MNE-C call? @Eric89GXL I noticed that you added quite some BEM related functionality.
> [MRG] Coreg gui

- doc/whats_new.rst
- mne/annotations.py
- mne/channels/channels.py
- mne/io/base.py
- mne/selection.py
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
Closes https://github.com/mne-tools/mne-python/issues/3258.
I'll wait until https://github.com/mne-tools/mne-python/pull/3290 gets merged so I can use the ``fake_click`` there for testing.
> [MRG+1] Sensor selection

- tutorials/plot_brainstorm_phantom_elekta.py
> MRG: Lower mem use

- .travis.yml
> WIP: Fix travis

- doc/contributing.rst
- doc/whats_new.rst
- mne/commands/mne_browse_raw.py
> [MRG] Add the --filterchpi option to browse_raw

- doc/python_reference.rst
- doc/whats_new.rst
- examples/inverse/plot_dics_beamformer.py
- examples/inverse/plot_dics_source_power.py
- examples/inverse/plot_tf_dics.py
- mne/beamformer/_dics.py
- mne/beamformer/tests/test_dics.py
- mne/time_frequency/__init__.py
- mne/time_frequency/csd.py
- mne/time_frequency/multitaper.py
- mne/time_frequency/psd.py
- mne/time_frequency/tests/test_csd.py
Added references to `compute_epochs_csd` function to the documentation of other spectral estimation functions.
> MRG: Reference compute_epochs_csd in other spectral estimation docs.

- circle.yml
- doc/whats_new.rst
- mne/datasets/tests/test_datasets.py
- mne/datasets/utils.py
- mne/utils.py
Closes #3256. Ready for review/merge from my end.
> MRG: Use ~/mne_data for data

- mne/preprocessing/ica.py
> [MRG] Randomised pca

- mne/viz/evoked.py
solution suggested by @jona-sassenhagen
closes #3451
> MRG fix for #3451

- mne/channels/tests/test_montage.py
- mne/datasets/megsim/urls.py
- mne/epochs.py
- mne/report.py
- mne/time_frequency/tfr.py
- tutorials/plot_stats_cluster_methods.py
Will hopefully make the newer more strict `flake8` happy.
> MRG: Fixes for flake

- doc/whats_new.rst
- examples/decoding/plot_ems_filtering.py
- mne/decoding/__init__.py
- mne/decoding/base.py
- mne/decoding/ems.py
- mne/decoding/tests/test_ems.py
- mne/decoding/time_gen.py
closes https://github.com/mne-tools/mne-python/issues/3427
> MRG: EMS transformer with sklearn API

- mne/epochs.py
closes https://github.com/mne-tools/mne-python/issues/3458
> FIX: more explicit error when concatenating epochs with different dev_head_t

- doc/whats_new.rst
- mne/viz/misc.py
- mne/viz/tests/test_misc.py
- tutorials/plot_forward.py
@Eric89GXL testing your suggestion from #3429, plotting all sources in a given slice (an ico-4 source space):
> [WIP] add source spaces to viz.plot_bem

- examples/inverse/plot_morph_data.py
> remove unnecessary line

- tutorials/plot_object_raw.py
> [MRG] don't document _data attr in raw

- mne/report.py
- mne/tests/test_report.py
small addition. reviews welcome
> [MRG+1] add repr to report

- doc/whats_new.rst
- mne/decoding/csp.py
- mne/decoding/tests/test_csp.py
- mne/tests/test_docstring_parameters.py
closes https://github.com/mne-tools/mne-python/issues/3484
I still need to add some tests
> [MRG] multiclass CSP

- mne/filter.py
- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/preprocessing/ecg.py
- mne/preprocessing/eog.py
- mne/preprocessing/tests/test_eeglab_infomax.py
- mne/preprocessing/tests/test_ica.py
- mne/preprocessing/tests/test_ssp.py
- mne/tests/test_filter.py
- tutorials/plot_background_filtering.py
I got a hold of Ifeachor and Jervis, 2002 and read a little bit more -- turns out my guess of `7.` as the multiplicative factor for the filter length was close but could be a bit better. Also we should probably use a Hamming instead of Hann window in our design, so I expose (and deprecate the default for) that option.
> MRG: Add FIR window choice

- mne/annotations.py
Closes https://github.com/mne-tools/mne-python/issues/3468.
> [DOC] Docstring for annotations.

- doc/whats_new.rst
- examples/time_frequency/README.txt
- mne/decoding/__init__.py
- mne/decoding/tests/test_time_frequency.py
- mne/decoding/time_frequency.py
- mne/inverse_sparse/mxne_inverse.py
- mne/minimum_norm/time_frequency.py
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
- tutorials/plot_stats_cluster_spatio_temporal_repeated_measures_anova.py
to be able to pipe time frequency transform e.g.
```
pipe = make_pipeline(
XdawnTransformer(),
TimeFrequency(freqs, sfreq, decim=20),
Vectorizer(),
LogisticRegression()
)
pipe.fit(X, y).predict(X)
```
> [MRG] TimeFrequency transformer for sklearn pipeline

- doc/whats_new.rst
- mne/epochs.py
- mne/tests/test_epochs.py
closes https://github.com/mne-tools/mne-python/issues/3503
> FIX: detrend not bool

- doc/whats_new.rst
- mne/event.py
- mne/realtime/epochs.py
- mne/tests/test_event.py
> MRG: kwarg mask_type like MNE-C

- mne/chpi.py
- mne/filter.py
- mne/tests/test_chpi.py
- mne/tests/test_filter.py
Fixes a couple of minor bugs, one with `filter_chpi` and another with `filter_data` where sometimes we weren't returning the filtered data (!).
> [MRG+1] Minor fixes

- mne/stats/cluster_level.py
Return value was poorly documented. Hopefully this helps.
> Improve docstring of summarize_clusters_stc

- doc/whats_new.rst
- mne/realtime/fieldtrip_client.py
- mne/realtime/tests/test_fieldtrip_client.py
closes https://github.com/mne-tools/mne-python/issues/3513
cc @YingYang let me know if this fixes your problem
> [MRG] FIX picks bug in get_data_as_epoch

- mne/io/array/array.py
- mne/io/array/tests/test_array.py
Minor fix to be able to use complex data with `RawArray`.
> MRG: Fix for RawArray with complex data

- mne/annotations.py
- mne/viz/tests/test_raw.py
[This](https://mail.nmr.mgh.harvard.edu/pipermail//mne_analysis/2016-August/003534.html) came up in the mailing list. Here's a fix so that this problem doesn't happen again
cc @jaeilepp
> [MRG] fix for annotations when plotting

- mne/preprocessing/infomax_.py
A useful little note for people like me who want to use the `infomax` function directly without going through the class.
> Add note that input data should be whitened

- mne/chpi.py
- mne/tests/test_chpi.py
This gets us slightly better match to MaxFilter's logging. It also implements some simple computations we'll probably want eventually for cHPI fitting. Probably unnecessary to update `whats_new.rst` since this is mostly an under-the-hood change.
> MRG: Better cHPI checks

- doc/python_reference.rst
- doc/whats_new.rst
- mne/viz/__init__.py
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
- tutorials/plot_visualize_evoked.py
~~Not ready for merge yet.~~ Comments welcome.
Does stuff like this:
```
colors = {"control":'Crimson', 'violation':'CornFlowerBlue'}
plot_compare_evokeds(hard, picks='Cz', colors=colors);
```
Missing:
> MRG plot_compare_evoked

- doc/whats_new.rst
- mne/decoding/__init__.py
- mne/decoding/tests/test_transformer.py
- mne/decoding/transformer.py
- mne/filter.py
`Filterer` is exactly the same as `FilterEstimator` with minor changes which includes removal of `info` and `picks` parameter. This is done to follow the API as discussed in #3428.
@kingjr
> [MRG+1] Created class Filterer and deprecated FilterEstimator

- mne/channels/channels.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
closes #3542
Edit: wait, what?
> MRG drop_chans error for trying to drop channels that aren't there

- doc/index.rst
- doc/tutorials.rst
- mne/time_frequency/tfr.py
- tutorials/plot_introduction.py
Should also take care of some other things with #2906 before merge.
> MRG: Add binder to homepage

- mne/io/base.py
- tutorials/plot_background_filtering.py
There was a small bug in the filtering tutorial http://mne-tools.github.io/dev/auto_tutorials/plot_background_filtering.html#baseline-problems-or-solutions.
See if you agree.
> Fix to filtering tutorial.

- mne/channels/montage.py
Closes https://github.com/mne-tools/mne-python/issues/3558
> [MRG] Fix to read_montage.

- doc/whats_new.rst
- mne/preprocessing/ecg.py
- mne/preprocessing/tests/test_ecg.py
Closes https://github.com/mne-tools/mne-python/issues/3541
> Fixes to create_ecg_epochs.

- mne/io/eeglab/eeglab.py
- mne/io/eeglab/tests/test_eeglab.py
> MRG: eeglab io: don't warn that no events can be converted if 0 events found

- doc/whats_new.rst
- mne/annotations.py
- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/tests/test_annotations.py
- mne/tests/test_epochs.py
- mne/viz/raw.py
Closes https://github.com/mne-tools/mne-python/issues/3509.
I believe there was a problem with syncing the annotations when cropping and concatenating data with ``first_samp`` present. I'll still have to make some checks before merging.
> [MRG] Fix plotting of annotations.

- mne/annotations.py
- tutorials/plot_artifacts_correction_rejection.py
Couple of fixes that were left out from the previous PR.
> [MRG] More fixes to annotations.

- mne/epochs.py
- mne/evoked.py
- mne/viz/evoked.py
Just closing a couple of small issues.
Closes https://github.com/mne-tools/mne-python/issues/3518
closes https://github.com/mne-tools/mne-python/issues/3566
> [MRG] Fixes to epochs and baseline docs.

- mne/decoding/csp.py
> FIX: csp numpy 1.12 max takes an array

- mne/decoding/base.py
- mne/decoding/time_gen.py
attempt to close #3578 & #3579
> MRG sklearn .18 n_splits

- mne/decoding/tests/test_time_gen.py
- mne/preprocessing/tests/test_ica.py
- mne/preprocessing/tests/test_infomax.py
> FIX: random pca solver in sklearn v.18

- mne/dipole.py
- mne/tests/test_dipole.py
Moving toward fixing dipole text IO.
Closes #3244.
> MRG: Fix dipole IO

- doc/whats_new.rst
- mne/decoding/csp.py
- mne/decoding/tests/test_csp.py
closes #3583 
cc @alexandrebarachant
> MRG: add param to CSP to transform into average power or time course

- mne/cuda.py
- mne/utils.py
@kambysese can you see what error message you get for PyCUDA on this branch? Hopefully we can work through it here and improve the CUDA docs.
> MRG: Better warning for PyCUDA failure

- doc/whats_new.rst
- mne/evoked.py
- mne/io/base.py
- mne/io/fiff/raw.py
- mne/tests/test_evoked.py
Allows reading Evoked files that have MaxShield-type data in them, such as the ones that are produced during acquisition.
> MRG: Allow reading MaxShield evoked files

- doc/index.rst
> [MRG] add grants that funded mne

- mne/decoding/base.py
Adding in Average parameter to plot_patterns and plot_filters
cc: @kingjr
> FIX: plot pattern and filter average param

- circle.yml
Circle seems to fail on master now. Maybe the bug in sphinx was fixed? Let's see if this works...
> Fix circle.

- mne/evoked.py
- mne/io/fiff/raw.py
Doc for `allow_maxshield` is somewhat misleading (you don't "process" anything with MaxShield). I also expanded it a bit.
> DOC: allow_maxshield

- doc/whats_new.rst
- mne/epochs.py
- mne/tests/test_epochs.py
- tutorials/plot_epoching_and_averaging.py
@jona-sassenhagen do you have time to take a look? This deals with the hierarchical event id stuff and should make it a bit more consistent.
Closes #3599.
Closes #2875.
> MRG: Better logic for epoch selection

- README.rst
> MRG: Add logo to README [ci skip]

- mne/viz/evoked.py
Closes https://github.com/mne-tools/mne-python/issues/3647
Now misc channels included to evoked instance are also plotted.
> Added misc channel to evoked plot.

- mne/decoding/tests/test_ems.py
Closes https://github.com/mne-tools/mne-python/issues/3658
> Fix to test.

- doc/whats_new.rst
- mne/channels/layout.py
Closes https://github.com/mne-tools/mne-python/issues/3618
I suspect something is going to break...
> [MRG+1] Exclude to layout.

- tutorials/plot_creating_data_structures.py
I believe this was wrong. Thanks for @choldgraf for pointing this out on gitter.
See if you're happy with the changes.
> Fix events in tutorial.

- circle.yml
Let's see if this does a better comparison...
> MRG: Better circle [ci skip]

- doc/whats_new.rst
- mne/channels/tests/test_interpolation.py
- mne/epochs.py
- mne/evoked.py
- mne/io/array/array.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/tests/test_evoked.py
- mne/transforms.py
Closes https://github.com/mne-tools/mne-python/issues/3682
We already do it for ``EpochsArray``.
Also closes https://github.com/mne-tools/mne-python/issues/3683
> [MRG+1] Deepcopy of info in array constructors.

- circle.yml
- doc/python_reference.rst
- doc/whats_new.rst
- examples/visualization/plot_parcellation.py
- mne/datasets/__init__.py
- mne/datasets/utils.py
> MRG: Add HCPMMP1.0 parcellation

- mne/viz/evoked.py
`plot_compare_evokeds` can overwrite style dict inputs. This deepcopies them first.
I don't think a new test is necessary?
Closes #3654
> deepcopy style dicts

- examples/realtime/plot_compute_rt_decoder.py
- tutorials/plot_point_spread.py
Closes https://github.com/mne-tools/mne-python/issues/3692
Retry to see what it looks like on circle.
> [MRG] Fixes to examples

- doc/whats_new.rst
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
Fixes one bug with `plot_projs_topomap` but I found another that we should probably address in a different PR (when someone finds time).
@kambysese this should fix the bug you were hitting.
> MRG: Fix plot_projs_topomap

- doc/whats_new.rst
- examples/visualization/plot_eeg_on_scalp.py
- mne/dipole.py
- mne/forward/_compute_forward.py
- mne/forward/_make_forward.py
- mne/forward/tests/test_make_forward.py
- mne/io/bti/bti.py
- mne/io/ctf/trans.py
- mne/io/meas_info.py
- mne/surface.py
- mne/transforms.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
This allows visualizing the EEG electrodes projected onto the scalp.
Also gets the machinery in place for #3700.
> MRG: Add projection of EEG electrodes

- circle.yml
- doc/index.rst
Circle has been failing (my bad) this should hopefully fix it
> MRG: Fix circle [circle full] [ci skip]

- doc/whats_new.rst
- mne/time_frequency/tfr.py
- mne/viz/epochs.py
- mne/viz/evoked.py
- mne/viz/topomap.py
- mne/viz/utils.py
Closes https://github.com/mne-tools/mne-python/issues/3701
> Fix to topomap colormap selection.

- doc/whats_new.rst
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
Closes https://github.com/mne-tools/mne-python/issues/3722.
> Fix read_montage to return channel names in provided letter case.

- circle.yml
- doc/tutorials.rst
- doc/whats_new.rst
- mne/channels/montage.py
- mne/datasets/utils.py
- mne/io/meas_info.py
- mne/transforms.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
- tutorials/plot_ecog.py
@choldgraf can you see if this works okay for your real data?
> MRG: Add ECoG plotting to plot_trans

- doc/whats_new.rst
- mne/io/base.py
- mne/io/tests/test_apply_function.py
- tutorials/plot_modifying_data_inplace.py
> ENH/API: better defaults for .apply_function and co (closes  #3742)

- doc/manual/decoding.rst
- doc/python_reference.rst
> Removed EpochsVectorizer from docs

- mne/bem.py
- mne/commands/mne_make_scalp_surfaces.py
- mne/commands/mne_surf2bem.py
- mne/commands/tests/test_commands.py
- mne/datasets/utils.py
- mne/fixes.py
- mne/gui/_file_traits.py
- mne/gui/tests/test_fiducials_gui.py
- mne/source_space.py
- mne/surface.py
> MRG: Dont use mne_surf2bem

- mne/dipole.py
- tutorials/plot_brainstorm_phantom_elekta.py
This was actually cruft left over from my PR, we don't need it. And because it's not really valid I don't think anyone should have used it, so I think it's okay not to have a deprecation cycle here.
> MRG: No need for 122

- examples/io/plot_objects_from_arrays.py
Integration from https://github.com/mne-tools/mne-python/issues/3725.
> Updated example on data containers.

- mne/viz/_3d.py
> MRG: Fix documentation

- .travis.yml
- setup.py
Let's see if this works. Might make Anaconda a little more stable.
> MRG: Dont force IPython version

- mne/commands/mne_coreg.py
- mne/gui/__init__.py
- mne/gui/_coreg_gui.py
Closes #3761, @noreun ready to test
> ENH coreg_gui:  option to turn off guessing MRI-subject

- .travis.yml
- mne/io/bti/tests/test_bti.py
- mne/preprocessing/tests/test_maxwell.py
- mne/simulation/tests/test_raw.py
- mne/stats/tests/test_cluster_level.py
- mne/tests/test_docstring_parameters.py
Let's see if this works
Closes #3736.
> MRG: Add OSX build

- mne/source_estimate.py
- mne/tests/test_source_estimate.py
fixes and closes #3774.
cc @Eric89GXL
> FIX: add implicit overwrite h5

- mne/io/kit/kit.py
- mne/io/kit/tests/test_kit.py
Maintenance release to fix KIT reader for old files (#3721)
Thanks @agramfort, should I update the version number? Add a note on 0.13.1 to whats_new?
> FIX KIT reader in Maint/0.13

- doc/_templates/layout.html
- doc/index.rst
- doc/python_reference.rst
- doc/sphinxext/cited_mne.py
- doc/whats_new.rst
> MRG: Add news [ci skip]

- mne/inverse_sparse/_gamma_map.py
- mne/io/base.py
- mne/viz/raw.py
- tutorials/plot_epoching_and_averaging.py
> MRG: Minor fixes to examples

- doc/whats_new.rst
- mne/forward/_make_forward.py
- mne/source_space.py
- mne/tests/test_source_space.py
Closes https://github.com/mne-tools/mne-python/issues/3708
Would this be good enough?
> MRG+1: Fixes to setup_volume_source_space.

- doc/whats_new.rst
- mne/io/kit/kit.py
- mne/io/kit/tests/test_kit.py
Follow up changes to make PR #3747 just so. @Eric89GXL @agramfort
> FIX: Small changes to fix PR #3747

- doc/whats_new.rst
- mne/stats/cluster_level.py
- mne/stats/tests/test_cluster_level.py
In `master` you can pass a positive `threshold` even when doing `tail=-1` which doesn't make much sense (you can end up with positive-t-valued vertices in your "negative" cluster). This adds a check for bad parameters.
> MRG: Minor fix for clustering

- doc/whats_new.rst
- examples/forward/plot_read_bem_surfaces.py
- mne/surface.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
Closes https://github.com/mne-tools/mne-python/issues/3406
> [MRG+1] Skull surfaces for plot_trans.

- doc/whats_new.rst
- mne/filter.py
- mne/fixes.py
- mne/io/base.py
- mne/tests/test_filter.py
- tutorials/plot_background_filtering.py
> MRG: Add minimum-phase filtering

- doc/whats_new.rst
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
Closes #3740.
Still needs tests. Seems to work with data @clementdonde provided.
> MRG: Allow ASCII BV files

- mne/channels/montage.py
- mne/channels/tests/test_montage.py
Closes #3755.
Improves on tests for coords by double-checking against values from commit 2fa35d4.
@jona-sassenhagen can you see if this fixes your problem?
> MRG: Fix ELP coords

- mne/dipole.py
- mne/tests/test_dipole.py
This just adds a little sanity check to avoid a hang during fitting I was getting with some bad data.
> MRG: Fix dipole check

- mne/time_frequency/tfr.py
A few obvious fixes to the docs - mostly stuff left over after introduction of EpochsTFR I think.
@kingjr
> MRG+1: fix tfr docs

- tutorials/plot_visualize_evoked.py
Here a few more very tiny doc changes (I'd like to keep them separate so I don't get too confused :)) - things I noticed while going over the viz_evoked tutorial.
> Minor: tutorial nitpick

- mne/preprocessing/ica.py
Documentation to make clear, that the instance is modified inplace (#3807)
> Feature #3807 better documentation for apply

- doc/whats_new.rst
- mne/event.py
- mne/io/fiff/raw.py
- mne/tests/test_event.py
Takeover of #3733 based on what we converged on.
> MRG: Add raw attribute

- doc/whats_new.rst
- mne/epochs.py
- mne/viz/epochs.py
- mne/viz/misc.py
- mne/viz/tests/test_epochs.py
- tutorials/plot_visualize_epochs.py
Closes https://github.com/mne-tools/mne-python/issues/3788
> [MRG+1] Events in epochs.plot.

- tutorials/plot_creating_data_structures.py
> DOC: Small fix in tutorial

- .travis.yml
- mne/cov.py
- mne/io/eeglab/tests/test_eeglab.py
- mne/report.py
- mne/tests/test_report.py
- mne/utils.py
- mne/viz/misc.py
- mne/viz/topomap.py
- mne/viz/utils.py
Updates our CI builds to use CI-helpers. ~~Also tries to use conda-forge to get Mayavi on Py3k.~~ We'll see if it works.
> MRG: Use CI-helpers

- mne/io/edf/edf.py
There was a file from 1989. Should be good for another 30 years.
> [MRG] Century in EDF reader.

- doc/whats_new.rst
- mne/dipole.py
- mne/tests/test_dipole.py
At Otaniemi they have an older phantom with different locations. I have approximate ones listed currently, will update and set to MRG once I confirm the actual locations.
> MRG: Add older phantom type

- doc/whats_new.rst
- mne/decoding/tests/test_transformer.py
- mne/decoding/transformer.py
- mne/epochs.py
- mne/viz/tests/test_topo.py
- mne/viz/topo.py
Closes https://github.com/mne-tools/mne-python/issues/3827
I wonder if this has always been broken...
> [MRG][FIX] Copy of the data in get_data.

- doc/whats_new.rst
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- mne/viz/topomap.py
- tutorials/plot_artifacts_correction_ica.py
Remake of #3573 cause we had a lot of discussion.
closes #3536
@agramfort @mmagnuski @agostontorok
> WIP add get_components method

- mne/decoding/tests/test_transformer.py
- mne/decoding/transformer.py
Follow up to https://github.com/mne-tools/mne-python/pull/3828
> [MRG] Better fix to Scaler.

- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
Closes https://github.com/mne-tools/mne-python/issues/3790
Now a running number is added two the duplicates (leaving the first name untouched).
Not sure how to test this.
> [MRG] More lenient handling of edf channel names.

- mne/baseline.py
- mne/minimum_norm/time_frequency.py
cf. mailing list.
Now the logging message is emitted only when it is actually done.
> Small fixes to epochs baseline.

- examples/connectivity/plot_mixed_source_space_connectity.py
- examples/inverse/plot_mixed_source_space_inverse.py
- mne/__init__.py
- mne/forward/tests/test_make_forward.py
- mne/source_estimate.py
- mne/source_space.py
- mne/tests/test_source_space.py
these functions are used in neuropype to handle mixed source space in mne inverse methods
> [MRG+1] new functions to hangle mixed src spaces in inverse

- circle.yml
- examples/connectivity/plot_mne_inverse_coherence_epochs.py
- mne/viz/misc.py
- tutorials/plot_brainstorm_auditory.py
A different attempt to fix CircleCI. This will tell us if our packages are broken.
> MRG: Fix circle [circle full]

- mne/annotations.py
- mne/viz/misc.py
- tutorials/plot_brainstorm_auditory.py
> Fix bst auditory

- mne/io/edf/edf.py
Closes #3852.
This decreases time to load [the sample file](http://www.teuniz.net/edf_bdf_testfiles/eeg_recording.zip) from over 8 seconds to under 2 seconds on my system.
@skjerns can you see if it's faster on your files?
> MRG: Speed up EDF reading

- doc/contributing.rst
LMK if you want wording changed @Eric89GXL and @agramfort
> MRG+1: adding contributor guidelines line for import order

- doc/python_reference.rst
- doc/whats_new.rst
- mne/__init__.py
- mne/tests/test_utils.py
- mne/utils.py
I would use a function like this a lot, I assume I'm not alone?
> MRG+2: Add convenience function for launching docs

- mne/viz/evoked.py
- mne/viz/utils.py
Closes https://github.com/mne-tools/mne-python/issues/3862
This simplifies things quite a bit. I can't remember why I chose to do it the other way. Hopefully Travis will catch it if I broke something.
> Fix to spatial color range.

- doc/Makefile
- doc/advanced_setup.rst
- doc/conf.py
- doc/configure_git.rst
- doc/contributing.rst
- doc/customizing_git.rst
- doc/faq.rst
- doc/getting_started.rst
- doc/git_links.inc
- doc/install_mne_c.rst
- doc/install_mne_python.rst
- doc/known_projects.inc
- mne/source_space.py
Simplifies the install and contrib docs.
Closes #3723.
> MRG: Update install and contrib docs

- mne/beamformer/tests/test_dics.py
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
- mne/tests/test_source_estimate.py
#3855: removed the KeyError and added a warning instead
> #3855: turned error to warning

- doc/whats_new.rst
- mne/annotations.py
- mne/io/base.py
- mne/preprocessing/ica.py
- mne/viz/ica.py
- mne/viz/raw.py
- mne/viz/utils.py
closes https://github.com/mne-tools/mne-python/issues/3711
should we add an extra `param` to `raw.plot`? I think it's almost a bugfix ...
> MRG+1: update raw times

- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
#3886: fixed error in corrmap with labels_ eq None
> #3886: fixed error in corrmap with labels_ eq None

- doc/whats_new.rst
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/tests/test_raw.py
Closes https://github.com/mne-tools/mne-python/issues/3876
Closes https://github.com/mne-tools/mne-python/issues/3890
I think I finally got it working. Let's wait until https://github.com/mne-tools/mne-python/pull/3895 gets merged and I'll rebase.
> [MRG+1] Exclude to edf reader.

- doc/whats_new.rst
- mne/coreg.py
- mne/gui/_file_traits.py
> [MRG+2] RF Coreg-GUI:  remove MNE-C dependency for fsaverage files

- mne/chpi.py
- mne/datasets/utils.py
- mne/simulation/raw.py
- mne/simulation/tests/test_raw.py
- mne/tests/test_chpi.py
- mne/transforms.py
Takeover/rebase of #3875 by @bmaess and @hsonntag. Ready for review/merge and has my +1. No `whats_new` update needed because these are not public yet.
> MRG+1: Improve cHPI estimation

- mne/bem.py
Fix for issue 3930
no need to check for mne cmd line tools
> BUG: issue 3930- mne cmd line tools no longer needed

- mne/coreg.py
- mne/gui/tests/test_coreg_gui.py
@Eric89GXL waiting to see if CIs are fixed...
> [MRG] FIX:  path regex on windows

- examples/forward/plot_left_cerebellum_volume_source.py
- mne/source_space.py
This should fix the recent CircleCI failure.
> MRG: Fix example [circle full]

- mne/cov.py
- mne/io/proj.py
- mne/tests/test_cov.py
Closes #3945.
Checks that `projs` is actually valid when using `compute_covariance`. Would have saved @WilliamCollishaw some pain :)
> MRG: Check projectors

- README.rst
- doc/whats_new.rst
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
Closes #3951.
No need to remove projectors when using `st_only=True`.
> MRG+1: Fix projectors when st_only=True

- mne/tests/test_utils.py
- mne/utils.py
@Eric89GXL as suggested in https://github.com/mne-tools/mne-python/pull/3948
> ENH get_config(key=None):  include values from os.environ

- tutorials/plot_introduction.py
> [MRG] Small fix in documentation

- doc/whats_new.rst
- mne/io/eeglab/eeglab.py
- mne/io/eeglab/tests/test_eeglab.py
> [MRG +1]: construct Montage out of channels with position when reading eeglab files

- mne/epochs.py
- mne/evoked.py
- mne/io/array/array.py
- mne/io/meas_info.py
- tutorials/plot_creating_data_structures.py
Addresses #3970 
This PR adds the proper units of measure in the docstrings of the `*Array` classes (e.g., `RawArray`) and in `create_info`.
> Units of measure in *Array classes

- .travis.yml
- appveyor.yml
- mne/decoding/csp.py
- mne/io/fiff/tests/test_raw_fiff.py
Should hopefully help with #3948 and any other segfaults we get.
Simply doing `pip install nose-faulthandler` [enables it by default](https://pypi.python.org/pypi/nose-faulthandler):
```
nose.plugins.faulthandler: INFO: Activating faulthandler module.
```
Should be ready for merge assuming Travis and AppVeyor agree.
> MRG +1: Use faulthandler

- MANIFEST.in
For conda-forge (https://github.com/conda-forge/staged-recipes/pull/2396#pullrequestreview-21394029)
> MANIFEST:  add license

- doc/whats_new.rst
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/datasets/utils.py
I have made edits to read_dig_montage and DigMontage.transform_to_head to support reading EGI digitization xml files. I was hoping someone could do an initial review to see if my edits are appropriate as this is my first time making a contribution.
Still left to do:
- Add test coverage. I have an example dig xml file that could be added to testing data.
- Update whats_new.rst
Closes #3593
> MRG+1: Issue 3593 - Add support for EGI Dig XML File

- mne/coreg.py
- mne/defaults.py
- mne/gui/_fiducials_gui.py
- mne/gui/_file_traits.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
@Eric89GXL first component of https://github.com/mne-tools/mne-python/pull/3466
I made them smaller but same color as head fiducials to indicate the correspondence, do you think that works? Maybe slightly bigger?
The testing data has no fiducials file, if we would add one (should be very small) we could add a test...
> MRG+1: plot_trans:  add MRI fiducials

- doc/whats_new.rst
- mne/annotations.py
- mne/io/base.py
- mne/io/fiff/raw.py
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- mne/tests/test_annotations.py
- mne/viz/utils.py
- tutorials/plot_ica_from_raw.py
I want to see which tests this breaks.
> [MRG+1] Annotation aware data getter.

- mne/io/base.py
- mne/time_frequency/psd.py
- mne/viz/raw.py
- tutorials/plot_artifacts_correction_filtering.py
This should fix recent CircleCI failures.
@mmagnuski can you see if you agree? Basically it makes `raw.plot_psd()` more flexible.
> MRG: Fix example

- mne/fixes.py
Master is failing because of this.
> [MRG] Fix docstring test.

- mne/viz/topo.py
Tuples need to be specified as kwargs
> make topo plot accept rgb tuples

- doc/manual/decoding.rst
- doc/whats_new.rst
- mne/decoding/tests/test_transformer.py
- mne/decoding/transformer.py
- mne/utils.py
Closes #3665.
Ready for review/merge from my end. @kingjr can you verify this is the functionality you were thinking of? The tests should make it pretty clear.
> MRG: Fix Scaler

- mne/channels/channels.py
- mne/channels/tests/test_montage.py
Fixes issue: #4044 
**Changes made:**
I have added return self statement in `set_montage()` method so that it can be chained with other operations.
> [MRG] raw.set_montage should return self

- mne/evoked.py
- mne/tests/test_evoked.py
> MRG: support merge_grads in get_peak()

- mne/epochs.py
PR to address issue #4041.
It's very simple, I just added on_missing to EpochsArray class.
> MRG: Add on_missing argument to EpochsArray

- mne/viz/topo.py
Closes https://github.com/mne-tools/mne-python/issues/4060
> [MRG+1] Remove minor ticks from tfr plot.

- mne/chpi.py
@bloyl can you see if you agree that this is what `master` does?
> DOC: Document cHPI procedure

- doc/whats_new.rst
- mne/beamformer/_rap_music.py
- mne/beamformer/tests/test_rap_music.py
- mne/dipole.py
- mne/viz/_3d.py
- mne/viz/misc.py
Closes https://github.com/mne-tools/mne-python/issues/4049
> [MRG+1] Fix dipole amplitude + plotter.

- doc/whats_new.rst
- mne/cov.py
- mne/io/base.py
- mne/preprocessing/ecg.py
- mne/preprocessing/eog.py
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
Cf. mailing list.
I'm wondering if ``compute_raw_covariance`` should be annotation aware too.
> [MRG+2] Annotation aware eog/ecg epochs.

- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
Closes https://github.com/mne-tools/mne-python/issues/4054
> [MRG+1] Fix interactive topomap projections.

- doc/whats_new.rst
- mne/channels/channels.py
- mne/channels/layout.py
- mne/io/array/tests/test_array.py
- mne/transforms.py
- mne/viz/evoked.py
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
- mne/viz/topo.py
- mne/viz/topomap.py
- mne/viz/utils.py
Taking over https://github.com/mne-tools/mne-python/pull/3976
Closes https://github.com/mne-tools/mne-python/issues/3971
> [MRG+1] Ecog plot

- mne/annotations.py
- mne/io/base.py
- mne/io/fiff/raw.py
- mne/tests/test_annotations.py
- mne/time_frequency/tfr.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
- tutorials/plot_visualize_raw.py
> [MRG+1] Allow drawing annotations when using orig_time.

- doc/whats_new.rst
- mne/channels/tests/test_montage.py
- mne/io/egi/egi.py
- mne/io/egi/tests/test_egi.py
Closes https://github.com/mne-tools/mne-python/issues/4076
> [MRG+1] EGI channel naming.

- doc/whats_new.rst
- examples/inverse/plot_dics_beamformer.py
- examples/inverse/plot_dics_source_power.py
- examples/inverse/plot_lcmv_beamformer.py
- examples/inverse/plot_lcmv_beamformer_volume.py
- examples/inverse/plot_tf_dics.py
- examples/inverse/plot_tf_lcmv.py
- mne/beamformer/_dics.py
- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_dics.py
- mne/beamformer/tests/test_lcmv.py
taking over #3839 and #3841 
Closes #3840
Closes #3841
Closes #3832
> [MRG+1] Fix reg dics + lcmv

- mne/bem.py
> [WIP] skip high-density BEM warning if model has only one surface

- doc/whats_new.rst
- mne/epochs.py
- mne/io/eeglab/tests/test_eeglab.py
- mne/realtime/epochs.py
- mne/tests/test_epochs.py
- mne/viz/epochs.py
Closes https://github.com/mne-tools/mne-python/issues/4012
> [MRG+2] Save name attribute of Epochs.

- mne/tests/test_report.py
Changed range of crop in line 74 of test_report to avoid rendering bug
> Changed range of crop in line 74 of test_report to avoid rendering bug

- mne/channels/channels.py
- mne/io/reference.py
Closes https://github.com/mne-tools/mne-python/issues/4087
See if you're happy with this.
> [MRG] Improve eeg reference doc.

- mne/decoding/transformer.py
Fixes #4055 
**Changes Made:**
I have added `fit_transform()` in `Scaler` class and corrected the doc.
> [MRG] Doc of mne.decoding.Scaler.fit_transform() is not correct

- examples/realtime/ftclient_rt_average.py
- mne/realtime/fieldtrip_client.py
- mne/viz/evoked.py
cc @teonbrooks 
selectable was not stopping interactivity which broke real-time examples ...
> FIX selectable to be really not interactive

- examples/inverse/plot_covariance_whitening_dspm.py
- mne/forward/tests/test_make_forward.py
- mne/io/base.py
- mne/io/fiff/raw.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/simulation/tests/test_raw.py
- mne/tests/test_coreg.py
- mne/tests/test_source_space.py
It seems that recent changes caused failures to tests that were not run on travis.
> Test fixes.

- examples/io/plot_read_events.py
- examples/io/read_events.py
- mne/event.py
This adds a plot to the read_events example so that sphinx gallery renders it nicely:
> adding a plot to read_events example

- doc/manual/datasets_index.rst
- doc/whats_new.rst
> adding documentation for the module + dataset

- examples/connectivity/plot_mne_inverse_coherence_epochs.py
- examples/connectivity/plot_mne_inverse_label_connectivity.py
- examples/time_frequency/plot_compute_raw_data_spectrum.py
- examples/time_frequency/plot_time_frequency_simulated.py
I took a look at the google analytics and these were the 6 pages with the most pageviews over the last 3 months. So I went through each one and made sure that it had a good narrative flow and utilized sphinx-gallery more effectively. I think we should do this for the top N examples as well as for the tutorials, but I didn't wanna bite off too much in one PR.
> MRG+1: Improve examples

- tutorials/plot_forward.py
> MRG+1: better forward doc + fix

- mne/connectivity/spectral.py
- mne/connectivity/tests/test_spectral.py
@Eric89GXL @agramfort some refactoring, preparing for more to come.
> [MRG] ENH/MAINT: refactor connectivity

- mne/decoding/base.py
> codespell test error fixed.

- mne/preprocessing/ecg.py
- mne/preprocessing/tests/test_ecg.py
-Raw fif data will be preloaded when running create_ecg_epochs
-Added test that checks if create_ecg_epochs works with data
that is not preloaded
closes #4137
> [MRG] Fixed error when running create_ecg_epochs

- mne/dipole.py
- mne/tests/test_dipole.py
Fix this issue: https://github.com/mne-tools/mne-python/issues/4149
> repr added to DipoleFixed.

- mne/commands/mne_show_fiff.py
- mne/commands/tests/test_commands.py
- mne/dipole.py
- mne/io/open.py
Closes https://github.com/mne-tools/mne-python/issues/4095
Are we happy with this?
> [MRG+1] Fix show_fiff.

- mne/time_frequency/psd.py
Clarifies psd_welch function
closes #4147
> [MRG] Updated psd_welch documentation

- examples/io/plot_objects_from_arrays.py
CircleCI on `master` has been failing due to some neo 0.5 change. This fixes it.
> MRG: Fix for NEO

- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
Closes https://github.com/mne-tools/mne-python/issues/4028.
I'll add the test file tomorrow.
> [MRG+1] Infer number of records from file size when n_records == -1

- mne/viz/evoked.py
- mne/viz/topo.py
- mne/viz/topomap.py
- mne/viz/utils.py
Closes https://github.com/mne-tools/mne-python/issues/4161
> [MRG +1] Remove mpl deprecation warnings.

- mne/io/base.py
- mne/io/fiff/raw.py
Closes https://github.com/mne-tools/mne-python/issues/4142
> [MRG+1] Reduce the number of warnings with annotations.

- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_lcmv.py
adding warning if covariance matrix is rank-deficient but no regularization is provided
> [MRG+2] adding warning for rank-deficient cov matrix with no regularization

- examples/decoding/plot_decoding_csp_eeg.py
- examples/decoding/plot_decoding_csp_space.py
- examples/decoding/plot_decoding_csp_timefreq.py
- examples/decoding/plot_decoding_spatio_temporal_source.py
- examples/decoding/plot_decoding_time_generalization_conditions.py
- examples/decoding/plot_decoding_unsupervised_spatial_filter.py
- examples/decoding/plot_decoding_xdawn_eeg.py
- examples/decoding/plot_linear_model_patterns.py
- examples/inverse/plot_covariance_whitening_dspm.py
- examples/inverse/plot_tf_lcmv.py
- examples/io/plot_objects_from_arrays.py
- examples/preprocessing/plot_run_ica.py
- examples/preprocessing/plot_xdawn_denoising.py
- examples/stats/plot_linear_regression_raw.py
- examples/time_frequency/plot_time_frequency_global_field_power.py
- examples/visualization/plot_evoked_whitening.py
- examples/visualization/plot_topo_customized.py
- tutorials/plot_artifacts_correction_filtering.py
- tutorials/plot_artifacts_correction_ica.py
- tutorials/plot_brainstorm_phantom_elekta.py
- tutorials/plot_modifying_data_inplace.py
- tutorials/plot_sensors_decoding.py
- tutorials/plot_stats_spatio_temporal_cluster_sensors.py
This should fix the Neo problem in a backward- and future-compatible way.
Also updates a bunch of `filter` calls to avoid deprecationwarnings.
> MRG: Fix examples

- mne/preprocessing/ica.py
- mne/viz/evoked.py
- mne/viz/ica.py
- mne/viz/raw.py
- mne/viz/topomap.py
Closes https://github.com/mne-tools/mne-python/issues/4178.
I also added the checks to some other places where it seemed reasonable.
> [MRG] Fixes to integer checks.

- mne/epochs.py
Closes https://github.com/mne-tools/mne-python/issues/4180
> [MRG] Fix to size check.

- doc/whats_new.rst
- mne/commands/mne_make_scalp_surfaces.py
it seems this script's logic was broken. Surf was never None and mkheadsurf never got triggered in that case.
> FIX: checking for surfaces

- doc/whats_new.rst
- mne/viz/tests/test_ica.py
- mne/viz/topomap.py
Closes https://github.com/mne-tools/mne-python/issues/4185
> [MRG] Fix plot_properties.

- doc/whats_new.rst
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
Closes https://github.com/mne-tools/mne-python/issues/3810
> [MRG+2] Add save method for EpochsTFR.

- doc/whats_new.rst
- mne/channels/channels.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
Closes https://github.com/mne-tools/mne-python/issues/4199
@jasmainak is this what you meant?
> [MRG] Allow plotting only subset of channel names in plot_sensors.

- doc/whats_new.rst
- mne/decoding/csp.py
- mne/preprocessing/ica.py
- mne/time_frequency/tfr.py
- mne/viz/evoked.py
- mne/viz/tests/test_topo.py
- mne/viz/topomap.py
Closes https://github.com/mne-tools/mne-python/issues/4197
> [MRG + 1] Fix to topomap contours.

- mne/io/base.py
- mne/viz/raw.py
- mne/viz/utils.py
closes #4190.  @Eric89GXL are you reviewing this one or should I ping someone else?
> adds proj=True argument to plot_raw

- mne/viz/evoked.py
- mne/viz/tests/test_topo.py
Just a bit of internal work: hopefully slightly cleaner code.
@jaeilepp maybe you can take a look later?..
> MRG+1 bugfixes to plot_joint

- doc/whats_new.rst
- mne/io/reference.py
- mne/io/tests/test_reference.py
> Bipolar ref

- doc/whats_new.rst
- mne/io/base.py
- mne/viz/ica.py
- mne/viz/raw.py
- mne/viz/tests/test_ica.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
- tutorials/plot_visualize_raw.py
Butterfly mode now works when ``order`` is equal to ``position`` or ``selection``.
> [MRG+1] Butterfly mode to raw.plot.

- doc/contributing.rst
> DOC: explain deprecation 

- doc/whats_new.rst
- mne/viz/evoked.py
Closes https://github.com/mne-tools/mne-python/issues/4234
> [MRG] Small fixes to evoked.plot visuals.

- mne/forward/_make_forward.py
- mne/forward/tests/test_make_forward.py
- mne/source_space.py
> MRG: Fix for negative n_jobs

- mne/gui/_viewer.py
- mne/gui/tests/test_kit2fiff_gui.py
Small bug, probably due to a previous change
> FIX kit2fiff-GUI label color

- mne/minimum_norm/time_frequency.py
> Update docstring source_induced_power

- doc/whats_new.rst
- mne/evoked.py
- mne/io/base.py
- mne/viz/evoked.py
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
- mne/viz/topo.py
Closes https://github.com/mne-tools/mne-python/issues/4245
Does this work for you @mdclarke?
> Add axes param to topo plots.

- mne/io/edf/edf.py
Closes https://github.com/mne-tools/mne-python/issues/4252
NaNs cannot be added to integer arrays.
> [MRG] Fix reader for gdf.

- doc/whats_new.rst
- mne/io/ctf/ctf.py
- mne/io/ctf/info.py
Closes https://github.com/mne-tools/mne-python/issues/4108
This only fixes missing columns. I didn't want to change the rows as I don't quite understand how it is possible to have these missing in the first place.
> [MRG] Fix missing comps in CTF data.

- mne/utils.py
Get CPU and memory in `mne.sys_info()`, if available.
> MRG: Add CPU and memory

- mne/epochs.py
- mne/tests/test_epochs.py
- mne/transforms.py
- mne/utils.py
- mne/viz/_3d.py
- mne/viz/raw.py
Some internal cleaning up of int handling.
Closes #4265.
> MRG: Use _ensure_int

- mne/channels/channels.py
- mne/io/base.py
- mne/preprocessing/stim.py
- mne/utils.py
> FIX : preload message for epochs

- doc/whats_new.rst
- mne/event.py
- mne/tests/test_event.py
> MRG: Deprecate mask_type -> "and"

- examples/io/plot_elekta_epochs.py
- mne/event.py
Some minor tweaks:
-remove unnecessary one-line class method
-remove irrelevant comment
-simplify example (no need to instantiate the class explicitly)
> [MRG] tidy up acqparserfif + example

- mne/viz/topo.py
- tutorials/plot_visualize_evoked.py
Closes https://github.com/mne-tools/mne-python/issues/4235
> [MRG] Wrap title in tutorial.

- mne/surface.py
- mne/tests/test_source_space.py
> Fix tessellate_sphere_surf.

- doc/whats_new.rst
- examples/visualization/plot_topo_compare_conditions.py
- mne/evoked.py
- mne/viz/evoked.py
- mne/viz/tests/test_topo.py
- mne/viz/topo.py
- mne/viz/utils.py
- tutorials/plot_visualize_evoked.py
FIX : fix colors on topo with black background
+
API : add dark_background parameter to show white background
> [MRG] FIX + API : on plot topo colors

- doc/whats_new.rst
- mne/forward/_field_interpolation.py
- mne/source_space.py
- mne/transforms.py
Fixes an ugly (but not likely widely discovered) bug in `transform_surface_to`.
> MRG: Fix surface transformation

- doc/whats_new.rst
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
Closes https://github.com/mne-tools/mne-python/issues/4305
> [MRG+1] Duplicate channel names appended with a running number.

- .travis.yml
- appveyor.yml
- mne/beamformer/tests/test_lcmv.py
- mne/beamformer/tests/test_rap_music.py
- mne/cov.py
- mne/decoding/tests/test_time_gen.py
- mne/decoding/tests/test_transformer.py
- mne/event.py
- mne/forward/_make_forward.py
- mne/io/ctf/tests/test_ctf.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/meas_info.py
- mne/io/pick.py
- mne/io/proj.py
- mne/io/tag.py
- mne/minimum_norm/tests/test_inverse.py
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_ica.py
- mne/preprocessing/tests/test_maxwell.py
- mne/simulation/tests/test_raw.py
- mne/surface.py
- mne/tests/test_chpi.py
- mne/tests/test_cov.py
- mne/tests/test_source_space.py
- mne/time_frequency/_stockwell.py
- mne/transforms.py
- mne/utils.py
- mne/viz/tests/test_3d.py
- mne/viz/tests/test_raw.py
Various tweaks to speed tests and helper functions. Let's see if I broke anything.
> MRG: Speed up functions and tests

- mne/channels/montage.py
> Some of the 10-05 montage names have more than 4 chars in the name

- doc/python_reference.rst
- doc/whats_new.rst
- mne/io/__init__.py
- mne/io/edf/__init__.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/edf/tests/test_gdf.py
Closes https://github.com/mne-tools/mne-python/issues/4340
> stim_channel='auto' for read_raw_edf.

- doc/whats_new.rst
- mne/io/base.py
- mne/time_frequency/psd.py
- mne/viz/ica.py
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
- tutorials/plot_visualize_raw.py
This should speed up our raw plotting when low-passing is done.
The same thing can be done with Epochs once this is tested / works.
> MRG: Faster raw plotting with decim

- mne/io/edf/edf.py
So that documentation matches functionname in code.
> get_gdf_events -> get_edf_events in documentation

- doc/python_reference.rst
- doc/whats_new.rst
- mne/epochs.py
- mne/viz/epochs.py
- mne/viz/ica.py
- mne/viz/raw.py
- mne/viz/tests/test_epochs.py
- mne/viz/utils.py
Continuation to https://github.com/mne-tools/mne-python/pull/4346.
Also includes fixes to dead links.
> [MRG+1] decim parameter for epochs.plot.

- .travis.yml
> MRG: Split testing

- doc/whats_new.rst
- mne/connectivity/spectral.py
- mne/connectivity/tests/test_spectral.py
fixes #4364 
I can add a test later.
> fix for #4364

- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
Closes https://github.com/mne-tools/mne-python/issues/4370
> [MRG] Disable interactivity when topography information is not available.

- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
- mne/viz/utils.py
> [MRG] Interactive times in topomap.

- mne/preprocessing/ica.py
- mne/preprocessing/xdawn.py
- mne/utils.py
fast_dot is deprecated from sklearn
> remove fast_dot which is deprecated in sklearn

- doc/whats_new.rst
- mne/source_estimate.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
@agramfort wanted an alternative plotter for ``stc.plot``. It is really slow, but useful for training purposes.
> [MRG] stc.plot resorts to mpl when Mayavi not installed.

- .travis.yml
- doc/whats_new.rst
- examples/inverse/plot_lcmv_beamformer.py
- examples/inverse/plot_lcmv_beamformer_volume.py
- mne/beamformer/_dics.py
- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_lcmv.py
@agramfort , @dengemann this is how far I got now with the weight normalization.
The whitening/SSP option might need some work (more flexibility), for now I just made it optional for the comparison.
Not sure how the implemented noise normalization (also optional for now) and the to-be-implemented unit noise gain BF relate? - The unit noise gain BF  would take the same source orientation maximization approach as NAI.
Also, orientation selection and weight normalization should probably be re-ordered since weight norm. is possible without orientation maximization, too.
> MRG: Weight normalization/Neural Activity Index for LCMV

- .travis.yml
- MANIFEST.in
- setup.py
+ add check_manifest to travis
> Cleanup manifest

- .gitignore
- doc/whats_new.rst
- examples/visualization/make_report.py
- mne/commands/mne_report.py
- mne/report.py
- mne/tests/test_report.py
- mne/transforms.py
- mne/viz/_3d.py
There is also `add_figs_to_section` with default `format='png'` that we could change to `format='svg'` by deprecation. I think it's a nicer default for most figures.
I didn't change `Epochs` plotting because it seems like it will be too heavy, however.
> MRG: Add option for SVG in report

- mne/tests/test_docstring_parameters.py
Checks to make sure we have properly documented our functions. Eventually we should try to whittle down the list of missed ones.
> [MRG+1] Add documentation checker

- mne/viz/raw.py
- mne/viz/utils.py
> [MRG] Add close_key to params dict to be able to modify it from outside

- doc/python_reference.rst
- doc/whats_new.rst
- examples/inverse/plot_lcmv_beamformer_volume.py
- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_lcmv.py
Related to https://github.com/mne-tools/mne-python/pull/4389
Updating what's new and reference plus some small fixes to the LCMV code.
@agramfort should I compose an example/add to an existing LCMV example to introduce the new functionality?
cc @dengemann
> Update doc for LCMV beamformer

- mne/viz/epochs.py
- mne/viz/ica.py
- mne/viz/raw.py
As suggested by @jaeilepp in #4432.
> [MRG] Move close_key to higher-level functions

- doc/whats_new.rst
- mne/io/base.py
- mne/tests/test_epochs.py
Closes https://github.com/mne-tools/mne-python/issues/4436
> [MRG] Fix bug in to_data_frame.

- doc/whats_new.rst
- mne/chpi.py
- mne/cov.py
- mne/datasets/utils.py
- mne/dipole.py
- mne/source_space.py
- mne/tests/test_dipole.py
- tutorials/plot_dipole_fit.py
Following the [Xfit manual](http://www.unicog.org/pmwiki/files/MEG/NM20568A-D_SourceMod-5.4.pdf) I think the implementation might be correct. Still need to:
We can do the plotting modification in a subsequent PR.
Closes #4423.
> MRG: Add confidence intervals

- doc/whats_new.rst
- mne/viz/epochs.py
- mne/viz/raw.py
> [MRG] Enable anti-aliasing in plot_raw

- examples/decoding/plot_decoding_csp_eeg.py
- examples/decoding/plot_decoding_csp_space.py
- mne/decoding/csp.py
- mne/viz/topomap.py
Closes https://github.com/mne-tools/mne-python/issues/4407
There was some unused parameters and other weirdness with the csp.
> [MRG] Fixes to CSP and example.

- doc/whats_new.rst
- mne/gui/_coreg_gui.py
- mne/gui/_file_traits.py
- mne/gui/tests/test_file_traits.py
Allows reading the digitization points from a saved ``DigMontage``.
> [MRG] Add support for adding dig points from montage.

- doc/whats_new.rst
- mne/viz/evoked.py
Closes https://github.com/mne-tools/mne-python/issues/4259
Are we happy with this @jona-sassenhagen  @mmagnuski ?
> [MRG] Fix to plot_joint title.

- mne/viz/tests/test_3d.py
> fix int division in test

- doc/whats_new.rst
- mne/forward/forward.py
- mne/forward/tests/test_forward.py
> [MRG] Fix writing a forward solution after restrict_forward_to_*

- .travis.yml
- doc/whats_new.rst
- mne/source_space.py
- mne/tests/test_dipole.py
- mne/tests/test_source_space.py
This should first expose the error in #4452. Will add a fix once we decide how best to fix it.
Closes #4452.
> FIX: Fix MNE-C

- doc/python_reference.rst
- mne/channels/__init__.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
I think a function that returns all builtin montages might be useful.
> Add function that returns a list of builtin montages

- .travis.yml
- mne/preprocessing/ica.py
- mne/utils.py
Let's see if we can test on 3.6.
Closes #4402.
> MRG: Change to 3.6

- .travis.yml
This adds the MNE-C commands to the OSX Travis build, hopefully to beef up our testing a little bit.
> MRG: Add MNE commands to OSX build

- doc/whats_new.rst
- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_lcmv.py
- mne/epochs.py
Closes #4473.
We'll see if it breaks anything else.
> MRG: Save memory by removing raw from Epochs

- circle.yml
- doc/_templates/layout.html
- doc/conf.py
PR to 0.14 to see if it fixes the problem.
> MRG: Fix source

- examples/preprocessing/plot_run_ica.py
- mne/preprocessing/ica.py
- tutorials/plot_artifacts_correction_ica.py
> [MRG] Add warnings for firwin2 use in combination with ICA

- mne/decoding/tests/test_search_light.py
- mne/decoding/tests/test_transformer.py
- mne/decoding/transformer.py
- mne/dipole.py
- mne/forward/forward.py
- mne/gui/tests/test_coreg_gui.py
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/edf/tests/test_gdf.py
- mne/io/meas_info.py
- mne/preprocessing/ica.py
- mne/realtime/fieldtrip_client.py
- mne/report.py
- mne/stats/cluster_level.py
- mne/surface.py
This should fix the failing tests in `master`.
> MRG: Fix sklearn

- examples/decoding/plot_decoding_spatio_temporal_source.py
closes #4463
My mayavi isn't working anymore, so I can't check the source patterns, if someone wants to give it a look..
Also @agramfort , you said we could plot stcs with matplotlib? Didn't find how.
> MRG+1: simplify source decoding example

- .travis.yml
- Makefile
- appveyor.yml
- mne/io/tests/test_pick.py
- mne/stats/tests/test_cluster_level.py
Works on #4412 
Make tests runnable with pytest without error and migrating as little as possible
> [MRG+2] First iteration towards using pytest

- doc/whats_new.rst
- mne/time_frequency/psd.py
> MRG+2: Use Hamming window for psd_welch (and document it)

- mne/channels/tests/test_montage.py
I wrote this little test for #4403 that ended up being unnecessary but still could help us in the future.
> MRG: Add test for read_montage

- mne/preprocessing/ica.py
> Add a description of the return value to the docstring of the apply method.

- doc/carousel.inc
- examples/visualization/plot_3d_to_2d.py
- mne/viz/evoked.py
- mne/viz/topomap.py
- tutorials/plot_mne_dspm_source_localization.py
- tutorials/plot_sensors_decoding.py
- tutorials/plot_visualize_evoked.py
Gets rid of some warnings in examples and tweaks our frontpage -- will post a CircleCI link once it's up.
> MRG: Tweak examples

- mne/viz/raw.py
Looking at the plot, I was wondering about the vertical lines. Had to go into the code to find out what they mean. This should be explained in the doc.
> Explain vertical lines in plot_raw_psd

- mne/source_space.py
currently, this is broken:
```python
import mne
path = mne.datasets.sample.data_path()
fwd = mne.read_forward_solution(path + '/MEG/sample/sample_audvis-meg-oct-6-fwd.fif')
fwd['src'].plot(subjects_dir=path + '/subjects')
```
It is occasionally useful to plot the source space inside a forward operator, to see which vertices may have been discarded due to falling outside the skull. In this case, the source space is in head coordinates, so things don't line up. This PR allows the user to specify a head<->MRI transformation to make the plotting work:
```python
import mne
path = mne.datasets.sample.data_path()
fwd = mne.read_forward_solution(path + '/MEG/sample/sample_audvis-meg-oct-6-fwd.fif')
fwd['src'].plot(subjects_dir=path + '/subjects',
trans=path + …
```
> [MRG+1] Add possibility to plot a source space in head coordinates

- doc/whats_new.rst
- mne/io/pick.py
- mne/preprocessing/ica.py
- mne/viz/ica.py
- mne/viz/tests/test_topo.py
- mne/viz/topomap.py
- tutorials/plot_artifacts_correction_ica.py
Simplifies ICA by using `ICA000` as the first label.
cc @jona-sassenhagen can you take a look and see if you agree it makes things simpler? I think you did a lot of the viz code. I will post the relevant CircleCI link once it's done.
> MRG: ICA indexing

- doc/whats_new.rst
- mne/stats/cluster_level.py
- mne/stats/tests/test_cluster_level.py
- mne/stats/tests/test_permutations.py
> MRG+1: Better rng handling in cluster functions

- mne/viz/ica.py
> Fix _plot_sources_raw x labels.

- doc/whats_new.rst
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
Fresh PR based on #4493 containing only the relevant changes.
> Fix reading montage information in brainvision header file (fresh PR)

- mne/simulation/tests/test_raw.py
Closes #4532.
@smgutstein can you see if tests pass for you now?
> MRG: Fix tol

- mne/io/__init__.py
- mne/io/cnt/cnt.py
- mne/io/egi/egi.py
- mne/io/egi/egimff.py
- mne/io/meas_info.py
- mne/io/reference.py
- mne/io/tests/test_meas_info.py
- mne/report.py
> MRG: Fix datetime use

- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
The forward model was automatically converted in other scenari, I guess it'd make sense to do it for all.
Closes #4545.
@agramfort Can you give it a look?
> FIX: automatically convert fwd if necessary

- .travis.yml
- appveyor.yml
- examples/decoding/plot_receptive_field.py
- mne/decoding/receptive_field.py
- mne/decoding/tests/test_receptive_field.py
- mne/decoding/time_delaying_ridge.py
- setup.cfg
- tutorials/plot_receptive_field.py
WIP because I think there are still some small bugs to work out, but I think it's getting close.
If anyone's curious I've marked the problems with `XXX` in the code. Hopefully will fix tomorrow.
> MRG: Change to positive lags

- mne/baseline.py
- mne/minimum_norm/time_frequency.py
- mne/time_frequency/tfr.py
- mne/viz/topomap.py
> [MRG] Clarify docstring for rescaling modes

- doc/whats_new.rst
- examples/connectivity/plot_cwt_sensor_connectivity.py
- examples/inverse/plot_dics_source_power.py
- examples/time_frequency/plot_source_label_time_frequency.py
- examples/time_frequency/plot_time_frequency_simulated.py
- examples/visualization/plot_topo_customized.py
- mne/beamformer/_dics.py
- mne/beamformer/tests/test_dics.py
- mne/connectivity/effective.py
- mne/connectivity/spectral.py
- mne/connectivity/tests/test_effective.py
- mne/connectivity/tests/test_spectral.py
- mne/decoding/tests/test_time_frequency.py
- mne/decoding/time_frequency.py
- mne/minimum_norm/tests/test_time_frequency.py
- mne/minimum_norm/time_frequency.py
- mne/tests/test_docstring_parameters.py
- mne/time_frequency/csd.py
- mne/time_frequency/multitaper.py
- mne/time_frequency/tests/test_csd.py
- mne/time_frequency/tests/test_multitaper.py
- mne/time_frequency/tests/test_stockwell.py
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
- mne/utils.py
- tutorials/plot_stats_cluster_1samp_test_time_frequency.py
- tutorials/plot_stats_cluster_time_frequency.py
- tutorials/plot_stats_cluster_time_frequency_repeated_measures_anova.py
I actually hit this case today, so I figured I'd start a PR to fix #4116.
~~WIP because I've only fixed one, and haven't updated any tests.~~
Closes #4116.
> MRG: Deprecate frequencies -> freqs

- doc/whats_new.rst
- mne/source_estimate.py
- mne/tests/test_source_estimate.py
I guess I should add support in spatio_temporal_src_connectivity too.
maybe tomorrow...
my debug script : https://gist.github.com/agramfort/df1c55fd60682680eb8751207d24f6b5
> MRG : add support for vol source spaces in spatial_src_connectivity

- mne/io/eeglab/eeglab.py
closes https://github.com/mne-tools/mne-python/issues/4564
@agramfort can you live without a test here? :)
> FIX for int arrays in ep.eventtype

- setup.cfg
Closes #4572.
@smgutstein can you verify that `py.test mne/gui` works for you now?
> MRG: Fix setup.cfg
