doc/source/python_reference.rst, doc/source/whats_new.rst, mne/connectivity/spectral.py, mne/filter.py, mne/inverse_sparse/_gamma_map.py, mne/inverse_sparse/mxne_optim.py, mne/minimum_norm/time_frequency.py, mne/parallel.py, mne/tests/test_filter.py, mne/time_frequency/__init__.py, mne/time_frequency/_stockwell.py, mne/time_frequency/multitaper.py, mne/time_frequency/stft.py, mne/time_frequency/tests/test_stockwell.py, mne/time_frequency/tests/test_tfr.py, mne/time_frequency/tfr.py, mne/viz/tests/test_evoked.py
I recently wanted to compute the CWT representation of an evoked dataset, and didn't see a way to do it. Unless I missed something I think this is how it should be done with our API?
I also exposed the `cwt_morlet` function, since I'll also need it for analysis.
=> ENH: Allow AverageTFR to be computed from Evoked

mne/io/reference.py, mne/io/tests/test_reference.py
This bug slipped by the tests. I've fixed it and modified the test to cover this piece of the code. I also took the opportunity to replace a `tile` call with broadcasting. See #1750.
=> FIX: Reference bug

mne/io/edf/edf.py
EDFBrowser doesn’t store the file type in the header. If this information is not provided, it will be determined by the file extension.
There is a separate issue that is related that is to be discussed. B/EDF data are stored in terms of data records and their length is determined by the record_length in seconds. Typically the record length is 1 second but it could be the case that is longer. This issue has already been addressed for EDF files: https://github.com/mne-tools/mne-python/pull/1574, but it could potentially be a bug for BDF. I think the solution would be implement the same procedure for BDF as we did for EDF.
=> FIX file type

mne/_hdf5.py, mne/io/meas_info.py, mne/io/proc_history.py, mne/tests/test_hdf5.py, mne/tests/test_utils.py, mne/utils.py
Recent changes to `meas_info` made it so that `sparse.csc_matrix` types can be in info, which in turn means our `write_hdf5` / `read_hdf5` files need to be changed to accommodate that use case. This adds that functionality.
=> ENH: Allow sparse csc matrices in H5

mne/io/brainvision/brainvision.py
The last sample was being calculated based on the number of channels instead of the number of data channels from the header information.
=> FIX last_samp calculation

mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py
If I understand the documentation correctly, you should be able to do ICA with both max_pca_components and n_components set to ```None```.
Currently, I get an error when n_components is ```None``` - this is because the loop responsible for selecting components and logging them checks if n_components is a float, and ```else``` (assuming it to be an int I guess) it tries to log it as a string, which will fail if n_components is None. Also, the logger currently tries to log pca.components_, which can be an array. I think it should log ```len(pca.components_)```.
If this is not the intended behavior, this PR fixes it. Including these changes, I can run ICA with ```n_components=None```.
=> ICA fails if n_components=None

mne/io/edf/edf.py
There's a problem when reading certain edfs where the header information states that the record length (in seconds) is equal to zero. Proposed change is to set a default value of 1 to these cases.
The reason this is relevant is that the sampling frequency is determined by the number of samples per record divided by the record length in seconds.
=> FIX add default if record_length == 0

doc/source/whats_new.rst, mne/decoding/classifier.py, mne/decoding/tests/test_classifier.py, mne/filter.py, mne/tests/test_filter.py
There appears to be another problem. Only the first epoch appears to be getting filtered. I though `low_pass_filter` takes care of the fact that there are 3 dimensions, but it doesn't? What's the best way to fix this? Reshape to 2D and filter or filter each epoch separately?
=> FIX missing fs attribute in filter

mne/label.py
Optionally use some other surface than the white surface in grow_labels(). Keep white as default.
=> allow grow_labels to use any surface

mne/channels/channels.py, mne/channels/tests/test_channels.py
with this fix now you can do this to change type of all channels:
```
mne.rename_channels(evoked.info, dict((c, (c, 'seeg')) for c in evoked.ch_names))
```
cc @aestrivex
=> allow ch_type change without ch_name change

mne/preprocessing/infomax_.py
@cle1109 @jdammers @dengemann
This PR addresses the fixed random state in the Infomax implementation. The random state is not fixed in the original Matlab implementation. Thus, this feature should be optional.
See scot-dev/scot#55 for details.
=> [FIX] Infomax random seed

mne/io/base.py, mne/io/brainvision/tests/test_brainvision.py
Proposal for dealing with filtering data where info["highpass"] or info["lowpass"] == None. Currently, the filter compares these fields to a float, which throws an error. Now, instead of checking ```(h_freq < info["lowpass"])```, we check ```(info["lowpass"] is None or h_freq < info["lowpass"])```.
Resolves #1833
=> Protect filter against info["{high|low}pass"] None

mne/event.py, mne/tests/test_event.py
Let's say I have a data set called raw. I am extracting the events from it with the step option which gives the following:
```
>>> events_step = mne.find_events(raw, output = 'step')
Trigger channel contains negative values. Taking absolute value.
484 events found
Events id: [    0     5     6     9    10    17    18    33    34 32768]
>>> events_step[:10]
array([[222225,      0,     10],
[222229,     10,      0],
[223476,      0,     18],
[223480,     18,      0],
[224726,      0,     34],
[224730,     34,      0],
[228862,      0,  32768],
[229030,  32768,      0],
[237048,      0,      5],
[237055,      5,      0]])
```
Now I want to exclude from the events list all the events 32768, but still keeping the step format...
With the present pick_events() function, I can either use the …
=> ENH: pick_events() adapted to step events

mne/evoked.py, mne/tests/test_evoked.py
This handles contrast cases (epochs1 - epochs2) where epochs1.comment and/or epochs2.comment is/are None.
=> EHN: Contrast default comment

mne/connectivity/spectral.py, mne/cov.py, mne/dipole.py, mne/epochs.py, mne/evoked.py, mne/io/base.py, mne/simulation/evoked.py, mne/source_estimate.py, mne/tests/test_utils.py, mne/time_frequency/tfr.py, mne/utils.py, mne/viz/misc.py, mne/viz/topomap.py
Closes #1811. Note that this also hopefully fixes a few off-by-one inclusion errors that existed in previous slices.
=> FIX: Use cleaner time comparison

mne/decoding/time_gen.py
The GeneralizationAcrossTime.fit() crashes when gat.n_jobs > len(epochs.times).
This provides a quick fix by splitting the data before parallelization at a max number of n_times.
=> correct bug parallel in gat for n_jobs>n_times

doc/source/whats_new.rst, mne/viz/topo.py
I'm playing with FASTER, so I'm making plots **including** bad channels.
There's a bug in `plot_topo` where scalings are not applied to bad channels, but only when plotting EEG.
You can reproduce the bug like this:
import mne
data = op.join(mne.datasets.sample.data_path(),
'MEG', 'sample', 'sample_audvis-ave.fif')
evokeds = mne.read_evokeds(data)
l = mne.channels.make_eeg_layout(evokeds[0].info, exclude=[])
mne.viz.plot_topo(evokeds, l)
for ev in evokeds:
ev.info['bads'] += ['EEG 012']
mne.viz.plot_topo(evokeds, l)
=> FIX: plot_topo scalings for bad EEG channels

mne/decoding/classifier.py, mne/epochs.py
(I guess I'm partially responsible for this problem myself in the first place, as I helped get BV importing done when no filter is set ...)
If info["lowpass"] is None, which can happen e.g. if importing underspecified BV files, and epoching uses the decim keyword, an error is thrown b/c ```new_sfreq < 2.5 * lowpass``` in line 140 fails if lowpass is None.
This is a simple workaround.
Might be worth considering if low/highpass = None should actually be allowed, or if import filters (specifically for BV) should default to something like 0 (or 1/length) and srate instead.
=> decim keyword for epochs fails if lowpass filter is None

mne/decoding/tests/test_time_gen.py, mne/decoding/time_gen.py
@cmoutard @dengemann @agramfort 
This is a small EHN that allows using gat.score() without passing the epochs if and only if the user has already used gat.predict(). 
As the object already stores the epochs predictions (in gat.y_pred_) it already possess all the necessary information which can be useful when you want to happened to have already predicted your epochs and want to test several different scorers.
=> EHN: Gat score optional epochs

mne/epochs.py, mne/tests/test_epochs.py
The Epochs class is old, much used and has therefore inevitably grown a bit hairy.
If we ever want to smooth a few things out (such as the way bad epochs are marked and dropped and the way projections are applied), it is very important not to break anything and retain full backwards compatibility.
This PR raises the test coverage on `mne.epochs` to around 97%.
I would like to go for 100%, but the remaining missed line numbers in the coverage report are inaccurate.
While writing tests, I noticed that the `_reject_setup` and `_is_good_epoch` methods are copy/pasted between the `_BaseEpochs` and `Epochs` classes. Since the latter inherits from the first, its duplicate implementations could safely be removed.
=> MRG: More epochs tests

mne/io/reference.py, mne/io/tests/test_reference.py
This is a small tweak to the way an average reference is applied.
Originally, going from a custom reference to an average reference will give an error:
set_eeg_reference(data, 'Fz')
set_eeg_reference(data, None) # ERROR
However, it turns out this use case is quite common, as we normally first want to mark bad channels before moving to an average reference. With this PR, the error will no longer be produced when an average reference is requested through the `set_eeg_reference` function.
=> MRG: Make it possible to go from custom reference to an average reference

mne/io/brainvision/brainvision.py
EEGLAB can export to BV and it's possibly one of the easier ways to export from EEGLAB to MNE. However, EEGLAB writes very minimal BV headers. In the ones I'm working on right now, no unit information is given at all; importing the file fails with a value error, because unit and resolution info is missing.
These proposed changes allow reading these underspecified files by simply filling in a default.
Sorry for these coming in incrementally, I discover new strange things about our huge collection of BV files every day.
@teonlamont
=> MRG: importing EEGLAB exported BV files: units

mne/epochs.py
@jona-sassenhagen, @dengemann 
When decimating the epoch data, the ```msg``` variable can be unspecified which creates a crash.
I put the warning in each condition instead. I hope this follows what the original authors aimed at doing?
=> FIX: correct warning message when decimating epoch data

mne/io/base.py, mne/io/fiff/tests/test_raw.py
I think that the bug reported on the listserv is fixed. In classy fashion, by implementing the "ToDataFrameMixin" base class, I also managed to undo the fix that led me to create the Mixin in the first place. I think that I've fixed it now, take a look and let me know if all looks well.
=> Fixed the time indexing bug with to_data_frame

doc/source/whats_new.rst, mne/__init__.py, mne/cuda.py, mne/tests/test_filter.py
I had a problem with Spyder segfaulting recently on introspection of `mne` due to a CUDA problem, presumably because it loaded and un-loaded `mne` too quickly. This prompted me to want to make it so that CUDA isn't initialized on init, but instead the first time CUDA is first set up to be used. This should speed up imports generally when people have CUDA enabled.
Still WIP because I made these changes on a machine without CUDA. I won't be able to test them until Monday.
=> ENH: Cleaner CUDA use

doc/source/python_reference.rst, doc/source/whats_new.rst, mne/channels/__init__.py, mne/channels/channels.py, mne/channels/tests/test_channels.py
Currently this removes the tuple ability to resign channel type from rename_channels.
This functionality has been moved to the `define_sensors` function.
addresses issue #1909
=> MRG ADD set_channels_type function RM parts from rename_channels

mne/io/bti/bti.py, mne/io/edf/edf.py, mne/io/meas_info.py
The C tools seem to require that files have a `dev_head_t`, so this should make it so that they all do.
=> FIX: Add dev_head_t to info

examples/decoding/plot_decoding_time_generalization.py, mne/decoding/tests/test_time_gen.py, mne/decoding/time_gen.py, mne/viz/decoding.py
Following https://github.com/mne-tools/mne-python/issues/1964,  I propose to
*    Drop the 'predict_type' option. If users want to use a decision_function or a predict_proba (or anything else we currently don't support) they could easily make their own classifier with a inherited class: e.g.
```
from sklearn.svm import SVC
class my_SVC(SVC):
def predict(self, x):
probas = super(my_SVC, self).predict_proba(x)
return probas[:,0]
```
*  Drop the automatic definition of the scorer (AUC if predict_type is probabilistic, Accuracy if discrete, Least Square if Regression etc...) and let the user takes care of this by defining the scorer him/herself.
=> WIP: simplifying gat

examples/inverse/plot_lcmv_beamformer.py
Here is a quick fix for the example @teonlamont. It was because of the stc and the label were not having the same subject name.
And I don't know actually why the stc was saved.
=> fix lcmv example

mne/io/base.py, mne/viz/raw.py
Reimplementing [#1968](https://github.com/mne-tools/mne-python/pull/1968) and generalizing to all viz functions when needed.
=> ENH: addition of the argument show=True in viz functions when missing

doc/source/whats_new.rst, mne/report.py, mne/tests/test_report.py
Removes `render_bem` and `add_htmls_to_section` for `add_bem_to_section`.
Add textbox attribute to images and figs for adding notes, and commentary to the images.
=> Simplify BEM rendering closes #1443

mne/viz/topomap.py
Plots would show even when show=False because the show parameter wasn’t
being passed to helper function.
=> MRG FIX topo bug in show

mne/time_frequency/tfr.py
Closes #1986.
@dengemann this seems to fix the examples. The default `dB=False` was changed to `dB=True`. In some places `dB=True` is default (plotting PSD for raw or epochs) and in others it is `dB=False` (plotting TFRs), but I guess that is okay.
=> MRG: Revert default

mne/report.py
I couldn't actually run @teonlamont's code example because an attempted `Mayavi` import ended up raising a `SystemExit` due to `wx`. Yikes. This fixes that problem.
=> FIX: Fix Mayavi import

mne/viz/topomap.py
Closes #2026.
@teonlamont can you see if it fixes your problem? @dengemann the change from `show=show` to `show=False` on one line is more consistent with what we do elsewhere in the package, but I'm not sure if it messes with your use cases. Can you try the ICA plotting functions to see if you're happy with their behavior under this PR?
=> FIX: Delay show to end

mne/io/edf/edf.py
With the advent of DIO cards, edf/bdf data can now support 16-bit triggers. We were currently masking the bits greater than 8. this doesn't affect any of the files with the old mask, it just allows for larger trigger values. 
another question is whether we really need the mask on the trigger channel. maybe it should just be removed?
=> Add support for 16 bit triggers

mne/io/edf/edf.py
addresses stim channel scaling mentioned in #2060. this uniformly makes sure stim channel is not scaled if header info is incorrect.
=> Change to never scale stim channel

mne/io/proj.py, mne/viz/raw.py
Closes #2020.
Also fixes a long-standing bug where projectors are not updated when marking bad channels in raw. Try the following code on `master`, then on this PR, scrolling down to `EEG001` and marking it bad:
```Python
import mne
raw = mne.io.Raw(mne.datasets.testing.data_path() +
'/MEG/sample/sample_audvis_trunc_raw.fif', preload=True)
raw._data[315, 300] = 1e-2
raw.plot()
```
I also modified the line width, it looks clearer to me -- see if you agree. In either case we should disable antialiasing because it doesn't do much for data sampled this highly, and it is much faster not to have it on.
=> FIX: Fix projection in raw plotting

mne/io/base.py, mne/io/bti/bti.py
Closes #1613.
For consistency all readers should cast their inputs to 64-bit float.
=> MRG FIX: Cast to 64-bit

mne/report.py, mne/tests/test_report.py
Closes #2014.
I'm pretty sure the docstring was wrong, too, so I changed it. At least it didn't do what it said it would do on my system (set the percentage). I'm not sure how you could have it both scale the figure by `scale` *and* have `scale` be the percentage of the page it should take up...
=> MRG FIX: Fix scaling

mne/decoding/tests/test_time_gen.py, mne/decoding/time_gen.py, mne/viz/__init__.py, mne/viz/decoding.py, mne/viz/tests/test_decoding.py
This PR aims at cleaning up, testing and enhancing small features of the GAT.
* By default, the classifier is changed from an SVC to a LogisticRegression to improve memory load and computation time. (SVC keeps all support vectors, and make the gat object quite heavy)
* The ```picks``` parameters is now saved together with `ch_names`
* The size of the prediction is now estimated from the first prediction. (In most use cases, this sizes is equal to 1, but for some prediction (derived from predict_proba or decision_function for instance), we can get higher ```y_pred``` dimensionality
* The basic plots are improved:  1. chance level is estimated from the classifier,  2. the default ```ylim``` is empirically derived ([0 1] doesn't fit many classifiers) 3. a new plot gat.plot_slice(train_time) …
=> MRG: GAT small fixes

mne/decoding/tests/test_time_gen.py, mne/decoding/time_gen.py
I just found a potential bug in GAT. the attribute ```y_pred_``` must be of the same sort than ```estimators_``` and thus be a list of list not an array. I hope it's not too late for the release.
=> BUG: y_pred_ must be list of list similar to estimators_

mne/io/kit/kit.py
Found a small bug in the kit module. The kwarg should be `res` (resolution) rather than `decim` (decimation). It passed by undetected because there isn't/can't be a test for it (our test hsp file is only 500 points to save space and this auto-decimation occurs in the script at 10k+). tested it on my box and it works.
=> MRG: FIX: kwarg should be res

mne/forward/forward.py, mne/io/base.py, mne/preprocessing/ica.py, mne/realtime/tests/test_mockclient.py, mne/tests/test_event.py
This speeds up Hari's example for me by a factor of ~400. Turns out `.times` was being created really often and bogging things down.
Closes #2049.
=> FIX: Faster read speed

examples/datasets/plot_spm_faces_dataset.py, mne/channels/__init__.py, mne/channels/channels.py, mne/evoked.py, mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py, mne/time_frequency/tfr.py, mne/viz/tests/test_3d.py, mne/viz/tests/test_circle.py, mne/viz/tests/test_decoding.py, mne/viz/tests/test_epochs.py, mne/viz/tests/test_topomap.py, mne/viz/topomap.py
Closes #2113.
Closes #2027.
Example code:
```
import mne
from mne.datasets.testing import data_path
evoked_fname = op.join(data_path(), 'MEG', 'sample', 'sample_audvis-ave.fif')
evoked = mne.read_evokeds(evoked_fname)[0]
evoked.pick_types(meg=False, eeg=True)
evoked.plot_topomap()
```
On current `master` this throws an error. This is what we now get on this PR:
If change the last lines to select just the left EEG channels, with `ch_type='eeg'`:
```
left_ch = [ch['ch_name'] for ch in evoked.info['chs'] if ch['loc'][0] < 0]
evoked.pick_channels(left_ch)
evoked.plot_topomap()
```
On current master we get the left channels distributed all over the head, which is misleading:
~~On this PR we get them staying on the left at least:~~
~~Not sure if we also want to do the same …
=> MRG ENH: Center and allow ch_type=None

mne/decoding/tests/test_time_gen.py, mne/decoding/time_gen.py, mne/viz/decoding.py, mne/viz/tests/test_decoding.py
The PR aims at adopting a stricter design close to sklearn and numpy: all params are set at the ```__init__``` time, as opposed to setting each of them at ```__init__()```, ```fit()```, ```predict()``` and/or ```score()```. 
These functions update the attributes corresponding to  each params (e.g. `pick` is set at `init` and`picks_` is updated at ```fit()``` because it requires epochs to be defined)
As ```picks```, ```test_times```, ```predict_mode``` and ```scorer``` are params, the corresponding attributes are not saved with an extra ```_``` (e.g. ```self.scorer_``` becomes ```self.scorer```).
See issue: https://github.com/mne-tools/mne-python/issues/2119#issuecomment-103539540
=> FIX: ensure consistency in the GAT params and attributes

mne/gui/_kit2fiff_gui.py, mne/gui/tests/test_kit2fiff_gui.py
Just a small usability fix
Did not reset use_mrk trait, which could lead users to 
inadvertently not using a marker point in the next file they process
=> FIX:  kit2fiff GUI “clear all” command

doc/source/python_tutorial.rst, mne/epochs.py, mne/io/array/array.py, mne/io/base.py, mne/io/brainvision/brainvision.py, mne/io/bti/bti.py, mne/io/bti/tests/test_bti.py, mne/io/edf/edf.py, mne/io/edf/tests/test_edf.py, mne/io/egi/egi.py, mne/io/fiff/raw.py, mne/io/fiff/tests/test_raw.py, mne/io/kit/kit.py, mne/io/kit/tests/test_kit.py, mne/io/tag.py, mne/io/tests/test_raw.py, mne/utils.py
Refactoring is only complete for `RawFIF` so far. I have moved `_read_segment` into `_BaseRaw`, and it calls `_read_segment_file`, which is a more targeted function. Now I need to transform the reading functions for KIT and EDF to work the same way. Hopefully we'll end up with more red lines than green ones.
Closes #2121.
=> MRG FIX: Unifying raw reading

doc/source/python_reference.rst, examples/stats/plot_cluster_stats_spatio_temporal_repeated_measures_anova.py, examples/stats/plot_cluster_stats_time_frequency_repeated_measures_anova.py, mne/stats/__init__.py, mne/stats/parametric.py, mne/stats/tests/test_parametric.py
Adresses #590
Implemented the missing parts of the Rick Henson code and extended the contrasts API.
With this modifcation M-way repeated measures models can be computed on data with mutliple observations per sample and per condition.
Tests need to be updated to incorporate 1way and 3way results.
cc @virvw @kingjr @Eric89GXL @josef-pkt @agramfort
=> MRG: implement fully generalized M-way rANOVA in parametric.py

mne/decoding/time_gen.py
Fixing the GeneralizationAcrossTime docstring so that the correct default classifier is listed.
=> Fixing time decoding docstring

mne/label.py, mne/tests/test_label.py
If a user tried to save an `annot` containing only RH-labels, `ctab_rgb` was not defined in the first (LH) iteration
=> FIX write_labels_to_annot():  List of RH labels only

examples/datasets/plot_spm_faces_dataset.py, examples/decoding/plot_decoding_spatio_temporal_source.py, examples/forward/plot_make_forward.py, examples/forward/plot_read_forward.py, examples/inverse/plot_dics_beamformer.py, examples/inverse/plot_label_from_stc.py, examples/inverse/plot_mne_crosstalk_function.py, examples/inverse/plot_mne_point_spread_function.py, examples/inverse/plot_time_frequency_mixed_norm_inverse.py, examples/plot_compute_mne_inverse.py, examples/stats/plot_cluster_stats_spatio_temporal.py, examples/stats/plot_cluster_stats_spatio_temporal_2samp.py, examples/stats/plot_cluster_stats_spatio_temporal_repeated_measures_anova.py, mne/viz/_3d.py, mne/viz/tests/test_3d.py
Closes #2149.
Turns out that excluding zero points actually breaks a lot of examples, and the current implementation seems to work pretty well while simplifying some examples. Ready for review/merge from my end.
=> MRG: Fix limits

mne/forward/_compute_forward.py
This PR should eventually allow for forwards solutions to be computed directly from sensor-space to SSS space (as opposed to source space -> sensor space -> SSS space). In theory, this should reduce some noise associated with numerical imprecision and head movements.
My current goal is to add comments at every step so that the current forward operations can be linked back to white papers. I'll ask for suggestions on formatting and efficiency later, so please hold off on those critiques for the moment. If you notice any of the math description is incorrect though, please point it out -- the physics is not uncomplicated...
=> MRG: SSS Forward (for GSoC)

mne/gui/_file_traits.py
Allow the use of Neuromag raw data files with IAS turned on,
i.e., don't require first Maxfiltering the data.
I haven't come up with a scenario in which this would cause a problem, but perhaps others can?
=> ENH pass allow_maxshield to Raw when loading digpoints

doc/source/whats_new.rst, mne/io/reference.py, mne/io/tests/test_reference.py
After calling `mne.io.add_reference_channels` the number of channels in the instance is not changed.
This fixes this issue.
=> Fix add_reference not setting correctly nchan

mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py, mne/report.py
No need to pass `self.verbose` to classes when calling methods, the verbose decorator automatically checks to see if the first arg is `self` and if so checks for `self.verbose` and uses it.
=> MRG: Fix use of verbose

mne/io/fiff/raw.py
Previously, trying to read a raw FIF with IAS data resulted in a `ValueError('No raw data in`. IMHO this is misleading, though I respect the need to throw an exception in case the user does not know what they are doing.
This PR changes the behaviour of `mne.io.Raw()` to yield
* `ValueError "No data"` if FIF is neither RAW, CONTINUOUS or SMSH (maxshield)
* `ValueError "IAS detected..."` if FIF is SMSH, but `allow_maxshield=False` (default)
* `UserWarning "This file contains IAS..."` if FIF is SMSH and `allow_maxshield=True`
=> sane exception on IAS-enabled raw with allow_maxshield=False

mne/cuda.py, mne/filter.py, mne/tests/test_filter.py
Looks like we had a strange bug in filtering caused by our normalization of the frequency-domain components we get from the FFT of the filter returned by `firwin2`. Doing the `sqrt` normalization of the gains themselves, before constructing the `firwin` filter, fixes the issue. I'm not sure how prevalent this will have been in people's data. It seems to be more common for short filter lengths than long ones.
=> FIX: Fix filtering

examples/inverse/plot_tf_lcmv.py, mne/beamformer/_lcmv.py, mne/channels/channels.py, mne/channels/tests/test_layout.py, mne/epochs.py, mne/evoked.py, mne/forward/_make_forward.py, mne/io/array/tests/test_array.py, mne/io/base.py, mne/io/kit/kit.py, mne/io/meas_info.py, mne/io/pick.py, mne/io/proj.py, mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py, mne/realtime/epochs.py, mne/realtime/fieldtrip_client.py, mne/realtime/tests/test_fieldtrip_client.py, mne/tests/test_epochs.py, mne/time_frequency/tfr.py
Not working yet. I hope to keep this more red than green. To-do list:
Closes #2225.
Closes #2200.
Closes #2178.
Closes #1982.
Closes #1893.
=> MRG: Refactor Epochs classes

mne/report.py
There was still a bug with adding a section with custom html in it. The links in the table of contents would be incorrect because of that.
cc @teonlamont @dengemann
=> Fix links in toc for custom html in report

mne/filter.py
The fft length was being ascertained from the length of `h_fft`, but CUDA filtering only uses the left side of the Fourier transform, meaning that `h_fft` did not have a length of `n_fft`. This was resulting in the following error that was not picked up by the tests, since CUDA is not a part of them:
```python
Test our private overlap-add filtering function ... time: 1 sec
Test CUDA-based filtering ... Traceback (most recent call last):
File ".../mne-python/mne/tests/test_filter.py", line 339, in <module>
run_tests_if_main()
File ".../mne-python/mne/utils.py", line 1660, in run_tests_if_main
val()
File ".../mne-python/mne/tests/test_filter.py", line 297, in test_cuda
filter_length=fl, verbose='INFO')
File "<string>", line 2, in band_pass_filter
File ".../mne-python/mne/utils.py", line …
```
=> FIX: FFT length for overlap-add filtering when using CUDA

doc/source/whats_new.rst, mne/inverse_sparse/mxne_inverse.py, mne/io/pick.py, mne/minimum_norm/inverse.py, mne/minimum_norm/psf_ctf.py, mne/minimum_norm/tests/test_inverse.py
@Eric89GXL Here is the PR for the actual implementation. I've made a gist testing your suggested raw.info-reordering based on sample data:
https://gist.github.com/cjayb/60ce9a543a4665348ad4
The new ordering is based on the order I found in Triux raw files (EOG, EEG, MEG, STI), and reproduces the error. Having separate selections for sol and info dicts (@3ebdb09eba52ac7cd37089dc7d448f0b97c0bab8) indeed solves the situation, though I am a little uncertain about `fwd['_orig_sol']` and `fwd['_orig_sol_grad']`?
I tried to grasp the testing-structure, but feel I need your help to implement my gist as a proper test. Any pointers?
Closes #2223
=> allow different channel ordering in fwd['sol'] and fwd['info']

mne/filter.py, mne/tests/test_filter.py
This code rewrites the overlap-add filtering to use one pass, whether the filtering is zero-phase or not. It does that by allowing the impulse response to be acausal (which is done by taking the magnitude-squared of `h_fft`) and handling the overlap on both sides of each segment, instead of just the right side.
Here is a simple speed test on the current master:
```
<RawFIF  |  n_channels x n_times : 401 x 379200>
filter length: 1024
n_jobs=1,  time: 12.1 s
n_jobs=cuda,  time: 12.0 s
filter length: 4096
n_jobs=1,  time: 13.5 s
n_jobs=cuda,  time: 5.6 s
filter length: 16384
n_jobs=1,  time: 18.2 s
n_jobs=cuda,  time: 6.7 s
filter length: 65536
n_jobs=1,  time: 30.3 s
n_jobs=cuda,  time: 7.8 s
```
And on the proposed branch:
```
<RawFIF  |  n_channels x n_times : 401 x 379200>
filter length: …
```
=> ENH: Faster zero-phase filtering (and better tests)

mne/label.py, mne/tests/test_label.py
many of the other error messages fail with uninformative errors when `names = [None, None .... ]` such as `could not .join NoneType`. Now crashes cleanly with a useful error message.
=> Fix issue 2256

doc/source/whats_new.rst, mne/viz/epochs.py, mne/viz/raw.py, mne/viz/tests/test_epochs.py, mne/viz/utils.py
Though it turned out not to be the mess I expected, I decided to make a separate PR for this. This here would also be a good opportunity to design the layout so that it looks good. Now the layout uses pixels instead of inches so in theory it should work on all screen sizes and platforms.
Should there be a 'help' button somewhere that would open a pop up window to view all the key combinations etc. (discussed in https://github.com/mne-tools/mne-python/pull/2206)? Are there other buttons we might need?
=> MRG Layout remake

mne/viz/epochs.py, mne/viz/ica.py
Proposed at https://github.com/mne-tools/mne-python/pull/2251.
=> [MRG] EOG and ECG channels added to the bottom of ICA plot.

mne/decoding/tests/test_time_gen.py, mne/decoding/time_gen.py
The params of `test_times` were not taken into account when only partially provided (instead the GAT was computed on all test_times points).
I also added more tests to prevent the user to try meaningless time parameters.
=> FIX: GAT times params + add tests

mne/tests/test_utils.py, mne/utils.py
Helper function to emulate the same behavior than matlab's randperm function.
This function is useful for comparing against matlab scripts which use the randperm function, for instance, for comparison against the eeglab infomax code.
=> Add custom_randperm function which outputs the same random numbers than matlab's randperm function

mne/io/base.py, mne/io/tests/test_raw.py
This adds an option to round the indices returned by raw.time_as_index(). The original formulation truncates decimals after it calculates an index, which can lead to non-unique indices when doing: `raw.time_as_index(raw.times)`
=> [MRG] Rounding with raw.time_as_index()

doc/whats_new.rst, examples/decoding/plot_decoding_xdawn_eeg.py, examples/realtime/plot_compute_rt_decoder.py, examples/realtime/rt_feedback_server.py, mne/decoding/__init__.py, mne/decoding/tests/test_transformer.py, mne/decoding/transformer.py, mne/tests/test_docstring_parameters.py
@agramfort @dengemann This PR addresses issue #2313 
Is it fine to import ConcatenateChannels as EpochVectorizer in the __init__ ??
or I should copy the code of ConcatenateChannels and name it class EpochVectorizer?
=> MRG: deprecated ConcatenateChannels and renamed EpochVectorizer

mne/forward/_make_forward.py, mne/forward/tests/test_make_forward.py
Fix the error in `make_forward_solution` where user could erroneously ask for a solution with meg or eeg channels and the computation would bomb if those channels types weren't present.
=> [MRG] Fix logic checks in make_forward_solution

mne/stats/regression.py
Closes #2377 and addresses half of #2331
Q: I'd like to use find_outliers here. However, I get a circular import if I import it in mne.stats.regression. Can I move find_outliers to mne.utils? @dengemann
=> WIP: implement sparse matrices for linear_regression_raw

examples/time_frequency/plot_time_frequency_sensors.py, mne/epochs.py, mne/time_frequency/tfr.py, mne/viz/topomap.py, mne/viz/utils.py
Norm topomaps no longer shows negative values, like in ``plot_time_frequency_sensors``.
Also fixed the 'bug' with ``vmin`` and ``vmax`` discussed in https://github.com/mne-tools/mne-python/pull/2366.
=> Norm colormap.

mne/channels/montage.py, mne/io/brainvision/brainvision.py, mne/io/edf/edf.py, mne/io/egi/egi.py, mne/io/meas_info.py
This PR adds the list of build-in montages to the `mne.channels.read_montage` docstring.
=> Additional API docs for reading montages

mne/time_frequency/tfr.py, mne/viz/tests/test_topomap.py
I noticed that when using the interactive topomap feature by selecting a rectangle in TFR plot, the color maps aren't always right.
I fixed it, but the downside is that now the user has no control over the color maps on the interactive plot.
=> [FIX] Fix to cmap on interactive topomap.

mne/decoding/base.py, mne/decoding/csp.py, mne/epochs.py, mne/evoked.py, mne/preprocessing/ica.py, mne/time_frequency/tfr.py, mne/viz/tests/test_topomap.py, mne/viz/topomap.py
In some dense EEG montages, electrodes are at the side / underside of the
head. When making a topomap plot, it can help interpretation to place
these electrodes (and corresponding interpolated data) outside the head
circle. Setting outline='skirt' allows you to do this.
To see an example of the API:
https://gist.github.com/wmvanvliet/6d7c78ea329d4e9e1217
=> MRG: Add outline='skirt' option to plot_topomap

examples/preprocessing/plot_eog_artifact_histogram.py, examples/preprocessing/plot_shift_evoked.py, mne/io/pick.py
Suggestion from #2410 
I removed the `exclude="bads"` string from `pick_channels` because this doesn't make sense if we don't supply an info object, which the function `pick_channels` doesn't include.
=> Fix examples pick channels

mne/beamformer/tests/test_lcmv.py, mne/beamformer/tests/test_rap_music.py, mne/decoding/tests/test_transformer.py, mne/epochs.py, mne/filter.py, mne/forward/tests/test_make_forward.py, mne/io/tests/test_pick.py, mne/preprocessing/ecg.py, mne/preprocessing/eog.py, mne/preprocessing/tests/test_ssp.py, mne/tests/test_epochs.py, mne/time_frequency/tests/test_tfr.py, mne/viz/tests/test_decoding.py
Fixes the six bugs we had not making `events` integers. Builds on #2411. Closes #2406.
=> MRG: Enforce ints for events

mne/decoding/tests/test_time_gen.py, mne/decoding/time_gen.py
Some sklearn classifiers can predict y_pred_ with shape (n_trials, 1) instead of (n_trials,)
=> FIX: GAT y_pred error when inconsistent axis

mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_maxwell.py
This PR allows the user to specify if bad channels should be reconstructed or not.
Will require `MNE-testing-data` to be updated
=> [MRG] SSS: reconstruct bad channels

mne/epochs.py, mne/tests/test_epochs.py
cc @dengemann
Closes #2435
Closes #2434
~~Can you make a minimal example for the other error you were getting having to do with `event_id` being an integer?~~
=> FIX: Allow one-sample epochs

mne/decoding/tests/test_csp.py, mne/decoding/tests/test_time_gen.py, mne/epochs.py, mne/io/proj.py, mne/realtime/epochs.py, mne/tests/test_epochs.py
=> MRG: Cleaner epochs processing and delayed tests

doc/whats_new.rst, examples/plot_from_raw_to_epochs_to_evoked.py, mne/epochs.py, mne/tests/test_epochs.py, mne/viz/__init__.py, mne/viz/epochs.py, mne/viz/tests/test_epochs.py
It's an exceptional move, but I feel it it's for a good reason.
As dicsussed with @agramfort and @mainakjas we're just removing the old viz code from epochs.plot.
As a nice side-effect: we've got many red lines.
=> ENH: from mne impose future (no depracation for epochs trellis plot)

mne/stats/regression.py
On Python 2, you'll currently get wrong time scales for rERPs. This should fix it.
=> Fix division bug

mne/viz/topomap.py
I've noticed that the outlines on topomaps go right to the edge of the axes, which leads to the lines being cut off slightly. Setting clip_on=False is one possible solution, another would be increasing the axes limits, I am not sure if there are arguments against one or the other.
=> Minor FIX for topomap outlines:  set clip_on=False

mne/decoding/tests/test_time_gen.py, mne/decoding/time_gen.py
@dengemann @jona-sassenhagen @cmoutard
The previous implementation was parallelized across time samples, which was highly suboptimal when dealing with simple classifiers (e.g. based on a low number of features, like with eeg) and a lot of time points, because of constant jumps across CPU threads.
With the current implementation, the `predict` and `score` parallelization is made with chunked data. This is analogous to the method used for `fit`, but the chunked data is across time (not estimators), which is slightly more difficult to follow, but allows dispatching `X` across threads, as opposed to copy it in each thread.
The cpu and memory gain is pretty high for large datasets. (@agramfort No, I haven't done the profiling, but I see it by eye ;))
I apologize in advance: the syntax remains …
=> EHN: GAT parallel across chunks for predict & score

doc/whats_new.rst, mne/time_frequency/tests/test_tfr.py, mne/time_frequency/tfr.py
This is needed if you transform IC sources and try to look at their tfr because the source channels become misc, and our built-in default in these functions are `meg` and `eeg`.
=> [MRG] ENH add picks argument to tfr_morlet, tfr_multitaper

mne/viz/tests/test_topomap.py, mne/viz/topomap.py
The `pos` parameter of the `viz.plot_topomap` function expects a matrix
with shape (#nchannels, 2). It used to silently accept other dimensions
as well by selecting `pos[:, :2]`. This means 3D coordinates, such as the
ones provided by Montage objects are accepted and lead to strange
results. See issue #2389.
This PR adds error messages when a matrix with invalid dimensions is
specified as `pos` argument. To keep backwards compatibility, matrices
with shape (#nchannels, 4) are allowed, meaning a user can still pass a
`layout.pos` matrix, even though `layout.pos[:, :2]` would be more
explicit and thus preferred.
=> Add some error messages to `viz.plot_topomap`

mne/stats/parametric.py
This fixes what looks like an error in the factor naming convention.
Sidenote: this ANOVA implementation gave the same results when tested against R (with help from @drammock)
=> [MRG] Fix factor typo

mne/decoding/time_gen.py
There's a bug when n_jobs > n_testing_times and if the total number of time point is larger than the number of jobs because it tries to run some empty chunks.
=> FIX: when n_jobs > n_test_times in GAT, remove empty jobs

mne/io/tag.py
Currently getting this on `master`:
```
tag = read_tag(fid)
File "/home/larsoner/custombuilds/mne-python/mne/io/tag.py", line 221, in read_tag
tag = Tag(*np.fromstring(s, dtype=('>i4,>I4,>i4,>i4'))[0])
TypeError: data type ">I4" not understood
```
I'm running bleeding-edge numpy, so they must have gotten rid of `I4`. This change uses `u4` instead. Will merge if the CIs are happy. cc @dengemann
=> FIX: Fix type

mne/io/kit/constants.py
The band-elimination filter values have changed. The unmasked value of 3 now maps to 50Hz. It is unclear that 1 still maps to 50Hz as well. This information is not incorporated into the `raw.info` but it does cause the file to be rendered properly.
side question: why don't we store notch filter settings in the info? historical reasons?
=> [MRG] ADD add'l bef setting

doc/whats_new.rst, mne/evoked.py, mne/viz/tests/test_topomap.py, mne/viz/topomap.py
Take over from https://github.com/mne-tools/mne-python/pull/2506.
Now it calculates the ``order`` from number of samples. If more than 10 peaks are found, the largest 10 peaks are shown. With ``order = len(evoked.times) / 30`` it seems to find a bit less than 10 peaks per dataset (exactly 10 with somato).
Sample:
Somato:
Spm_faces:
=> [MRG] Automatic peak finder

mne/proj.py, mne/tests/test_proj.py
I noticed when converting the mne-script https://github.com/mne-tools/mne-scripts/blob/master/sample-data/run_meg_volume_tutorial.sh, that the sensitivity maps cannot be made for volume source space in python. With this it is possible.
=> Sensitivity map for volume source estimate.

mne/viz/evoked.py
Since color_cycle is not compatible with new version of matplotlib, I removed it altogether. I don't think it is used anywhere else in the code. You can try this with ``plot_from_raw_to_epochs_to_evoked`` for example.
Closes https://github.com/mne-tools/mne-python/issues/2616.
=> Removed color_cycle.

.travis.yml, mne/tests/test_filter.py
I encountered a failure in tests when doing the packaging. It was caused by using ``force_serial``, which caused the log to contain 3 lines instead of 2.
=> Fix to test and travis.

mne/preprocessing/ica.py, mne/time_frequency/psd.py, mne/time_frequency/tfr.py, mne/viz/_3d.py, mne/viz/circle.py, mne/viz/decoding.py, mne/viz/epochs.py, mne/viz/evoked.py, mne/viz/ica.py, mne/viz/misc.py, mne/viz/montage.py, mne/viz/raw.py, mne/viz/topo.py, mne/viz/topomap.py, mne/viz/utils.py
Some tweaks to make the code more DRY and silence some test warnings that have cropped up. If the `warn=False` is for too recent `numpy`, I can change it to use a backend-lookup pattern.
=> FIX: Fix some test warnings, DRY code

mne/epochs.py, mne/tests/test_epochs.py
Closes #2645.
The bug was due to improperly setting `tmax`. I've changed `epochs` to derive it from `.times` instead, which should be a cleaner approach.
=> MRG: Cleaner use of tmin/tmax

mne/decoding/csp.py, mne/decoding/tests/test_csp.py
Following the discussion in https://github.com/scot-dev/scot/issues/64, I added a second way to estimate the two covariance matrices. By default, the previous method (`concat`) is used, but maybe this should be changed to the new method (`epoch`) in a future release because that's how most papers describe CSP.
=> Added epoch-based covariance estimation method

mne/tests/test_utils.py, mne/utils.py
@agramfort do you know of a more stable/reliable/faster FTP URL than the `ftp://surfer.nmr.mgh.harvard.edu` one? I'd rather not keep pushing up the `timeout` value.
=> FIX: Fix timeout

mne/evoked.py
Makes it clearer when one is using a non-average (usually standard error) kind of Evoked.
=> MRG: More complete Evoked repr

doc/whats_new.rst, mne/decoding/tests/test_time_gen.py, mne/decoding/time_gen.py
The length of the slices used to be computed from an estimation of frequency, which can be lead to numerical error when the fit and predict dataset have different time length.
Instead, I changed it to an explicit definition.
Note that the print of one test was actually incorrect.
=> FIX: explicit sampling frequency to avoid numerical error

mne/io/brainvision/brainvision.py
@teonlamont I had a line (EEGLAB exported file, boundary event) where the duration was NaN that errors out. This fixes it.
=> MRG: bv read vmrks NaN duration (minor)

mne/channels/layout.py, mne/channels/montage.py, mne/channels/tests/test_montage.py
When a montage is applied, it is assumed that all the EEG channels in
the data have position information specified in the montage file. Raise
a warning if this is not the case.
Furthermore, the warning raised in `_auto_topomap_coords` when multiple
channels have the same position, has been extended to list the offending
channels.
=> [MRG] Add warnings for EEG electrodes not in montage

doc/whats_new.rst, mne/stats/regression.py, mne/stats/tests/test_regression.py
Closes #2056.
Closes #1917.
Gets rid of warnings about divide by zero and underflows in linear regression by protecting against `stderr == 0`. It effectively forces all values in mlog10_p_val to be in the range `[-9.64e-17, 0]` (i.e., `[np.log10(1. - np.finfo(np.float64).eps), 0]`).
@dengemann I'd like to also take care of #1917 with this, but practically I'm not sure if we should make any changes to the code -- it might be doing the right thing already. I think if you get a p-value of 1., you should get a `0` in your `mlog10_p_val` and `np.inf` in your `t_val`, and deal with it appropriately afterward. Do you agree, or is there some coding change to be made?
=> MRG: Fix regression

doc/whats_new.rst, examples/decoding/plot_decoding_time_generalization.py, mne/decoding/tests/test_time_gen.py, mne/decoding/time_gen.py
Joint [pair programming](https://en.wikipedia.org/wiki/Pair_programming) work with @fraimondo and @kingjr to make the time-gen considerably faster.
It looks as if we managed to impose a performance function that scales linearly with n_times. On MNE-Examples with we observed 6 seconds instead of 50 seconds single CPU time.
cc @agramfort @jona-sassenhagen @cmoutard @jdsitt
Let's see what is left to be done.
=> [MRG+1]: vectorize predictions for the standard time gen case (window-size == 1)

doc/whats_new.rst, mne/cov.py, mne/io/proj.py, mne/preprocessing/tests/test_ssp.py, mne/proj.py, mne/tests/test_proj.py
closes #2341. this is written to return an optional `explained_variance`. I am not sure if this is pythonic. The other option would be to make a separate function but then it wouldn't be DRY.
=> [MRG] ENH add explained_variance to PCA

mne/bem.py, mne/epochs.py, mne/forward/_make_forward.py, mne/io/bti/tests/test_bti.py, mne/io/ctf/tests/test_ctf.py, mne/io/kit/tests/test_kit.py, mne/io/meas_info.py, mne/io/pick.py, mne/io/tests/test_pick.py, mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_maxwell.py, mne/tests/common.py, mne/tests/test_bem.py, mne/tests/test_epochs.py
Relates to #2112.
Many chanegs to make MF run on other systems:
- ~~[ ] Fix head shape calculation for KIT data.~~
@kingjr can you try this branch on your data?
=> MRG: Allow MF to run on other systems

mne/viz/tests/test_topomap.py, mne/viz/topomap.py
A minor PR hopefully helpful for stupid people like me.
Currently, if you try `plot_topomap(..., show_names=True)` without supplying `names`, the following error is raised: `TypeError: object of type 'NoneType' has no len()`.
This adds the dependency of `show_names` on `names` to the doc, and gives a more meaningful error message when this is not done.
=> [MRG] better error msg for missing names for plot_topomap

mne/viz/evoked.py
The horizontal line for butterfly plots is in red. This looks silly (and is potentially confusing) for plots with spatial colors (see below).
This PR makes it grey for spatial_colors, but leaves it red for black plots.
Furthermore, how about a vline option..?
=> [MRG] Grey hline when spatial_colors=True

doc/whats_new.rst, mne/channels/channels.py, mne/channels/tests/test_channels.py, mne/cov.py, mne/dipole.py, mne/epochs.py, mne/forward/_field_interpolation.py, mne/io/proj.py, mne/minimum_norm/inverse.py, mne/tests/test_epochs.py
@agramfort it's probably good to take a look at this one now, esp. how `test_epochs.py` had to be changed. Writing out `EpochsArray` and reading it back by default will have avg ref added and applied.
The least intrusive change might actually be to have `add_eeg_ref=False` in `read_epochs`. If people have been using FIF, they've presumably already added the ref by that stage (during `Epochs` construction), and it avoids breaking people's `EpochsArray` use.
=> MRG: Actually do projection

mne/io/reference.py, mne/io/tests/test_reference.py
This is a typo that has slipped through the unit tests and our code review process.
@teonlamont
=> [MRG] Fix bug in add_reference_channels

mne/io/tests/test_meas_info.py
There was no unit test for this method. This PR adds a small test. I'm currently not in the mood to write an exhaustive test, but this is better than no test at all.
=> Add unit test for _merge_info

mne/stats/regression.py, mne/stats/tests/test_regression.py
The previous warning message for non-unique time points was a bit cryptic.
@kingjr
=> [FIX] Add warning for non-unique time points in `events`

doc/whats_new.rst, mne/viz/epochs.py, mne/viz/tests/test_epochs.py
here is a new parameter to display eg reaction times on top of ERP/ERF image.
For @bburle
```
import mne
epochs = mne.read_epochs('test-epo.fif')
reaction_times = epochs.events[:, 1] / epochs.info['sfreq']
order = np.argsort(reaction_times)
mne.viz.plot_epochs_image(epochs, picks=[0],
order=order, show_times=reaction_times)
```
it gives
=> ENH : add show_times parameter to plot_epochs_image

mne/connectivity/spectral.py, mne/io/tests/test_reference.py, mne/preprocessing/stim.py
Right now in calculating times it's checking `isinstance(Epochs)` rather than `_BaseEpochs`. So if you supply `EpochsArray` it doesn't catch it. This is a switch to use `_BaseEpochs`
=> Update spectral connectivity to check _BaseEpochs

mne/stats/regression.py, mne/stats/tests/test_regression.py
Currently, if events are tightly spaced and decimation is used for linear_regression_raw, it is possible overlapping events result and an unhelpful error is thrown. This replaces this with a hopefully *helpful* error.
Addresses #2790
Shoul I add a test?
@kingjr
=> MRG Error for event latency overlap due to decim in rerps

mne/decoding/tests/test_time_gen.py, mne/decoding/time_gen.py
This allows using `predict_proba` and `decision_function` for clf that allow for it, (instead of the dirty hack meta class that I proposed earlier).
Note that when shortcutting prediction with e.g. `gat.score(epochs)` this will by default use `gat.predict(epochs)`.
@dengemann @jona-sassenhagen @choldgraf
Note that, to score a probabilistic output, you still need to make an home made scorer (see example below). @agramfort you [mentionned](https://github.com/mne-tools/mne-python/issues/2176) that sklearn has an automatic way of dealing with this? To-be-dealt in another PR?
```
import mne
from mne.datasets import spm_face
from mne.decoding import GeneralizationAcrossTime
data_path = spm_face.data_path()
raw_fname = data_path + '/MEG/spm/SPM_CTF_MEG_example_faces%d_3D_raw.fif'
raw = …
```
=> EHN: allows predict_proba and decision_function

mne/epochs.py, mne/tests/test_epochs.py
Currently, if one attempts to equalize event counts with hierarchical tags, one of which matches no event_ids, an unhelpful error is raised. This provides a better message.
~~Will do a test later.~~
*Possibly* addresses #2794.
=> MRG+1: Fix: Error message for missing event_id for tag event_id selection during event count equalization

doc/python_reference.rst, doc/whats_new.rst, mne/__init__.py, mne/tests/test_utils.py, mne/utils.py
Should make things like #2834 a bit easier. Example output from doing `$ python -c "import mne; mne.sys_info()"` on my system:
```
Platform:      Linux-4.2.0-25-generic-x86_64-with-Ubuntu-15.10-wily
Python:        2.7.10 (default, Oct 14 2015, 16:09:02)  [GCC 5.2.1 20151010]
Executable:    /usr/bin/python
mne:           0.12.dev0
numpy:         1.12.0.dev0+d5cef01 (Intel)
scipy:         0.18.0.dev0+fe694ea
matplotlib:    1.5.1+1107.g1fa2697
sklearn:       0.18.dev0
nibabel:       2.1.0dev
nitime:        0.6.dev
mayavi:        4.3.1
nose:          1.3.7
pandas:        0.17.1+25.g547750a
pycuda:        2015.1.3
skcuda:        0.5.1
```
=> MRG + 1: Add sys_info

mne/viz/topomap.py
When composing a custom topomap-layout and passing the axes-parameter to `plot_topomap`, it is assumed that is a colorbar is desired, it should be in the rightmost column.
Solves issue #2887
=> plot_evoked_topomap colorbar in last subplot

mne/viz/topomap.py
@jaeilepp @agramfort @wmvanvliet I introduced a bug in PR2888 :-(
* when `axes` not given, new figure created on-the-fly
* topomap-axes created for each time point
* finally, colorbar-subplot created
* BUG: `len(fig.get_axes())` is one short and colorbar end up too far to left
FIX: take the max of `len(fig.get_axes())` and `nax` (`= n_times + bool(colorbar)`)
=> fix bug introduced by PR2888

mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_maxwell.py
Fixes a bug with channel writing for movement-compensated `Raw` instances.
Closes #2900.
=> MRG: Fix movement compensation IO

mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_maxwell.py
This allows using `maxwell_filter` in a temporal-projection-only (tSSS only) mode.
=> MRG: Add st_only option for temporal projection

mne/io/tag.py
Looks like back in 2012 I missed one:
https://github.com/mne-tools/mne-python/commit/b1634cd3a602643138161e37d83effd079a7a8ce
Ready for review/merge from my end. It wasn't caught by tests because we don't have any files that use it. I got a hold of a file that did (exported from xplotter I think?) but it's too big (13 MB) to justify adding.
=> MRG: Fix dtype

mne/io/base.py, mne/io/fiff/tests/test_raw_fiff.py
Somewhere along the way our raw `__repr__` got broken. On `master` it is:
```
<Raw  |  n_channels x n_times : 326 x 61500>
```
On this PR it is:
```
<Raw  |  phantom_moving_raw.fif, n_channels x n_times : 326 x 61500 (30.7 sec)>
```
=> MRG: Fix raw repr

mne/io/pick.py, mne/io/tests/test_pick.py
I missed a case in #2843. `pick_types` uses logic very similar to that of `channel_type` but not quite the same. At some point we should unify them.
This was breaking plotting with `raw.plot()` for files that had cHPI channels. This fixes it.
=> MRG: Fix SEEG picking (again)

mne/decoding/tests/test_time_gen.py, mne/decoding/time_gen.py
https://github.com/mne-tools/mne-python/pull/2856 had assigned `scorer_` as a function of `clf` and `predict_method` even when the user had already defined it:
e.g.
```
gat = GeneralizationAcrossTime(scorer=my_scorer)
gat.fit(epochs)
gat.score(epochs)
gat.scorer_ != my_scorer
```
This is corrected, with an additional test.
=> BUG: automatic assignement of gat scorer even if scorer is passed

mne/io/fiff/raw.py, mne/preprocessing/tests/test_maxwell.py, mne/simulation/tests/test_raw.py, mne/tests/test_chpi.py, mne/tests/test_epochs.py
For people who record with MaxShield on and plan on running `maxwell_filter` on the data, it would be nice to be able to silently load data. Now `allow_maxshield='yes'` allows us to do that.
=> MRG: Allow maxshield silently

mne/tests/test_utils.py, mne/utils.py
@jaeilepp see if you agree with the fix.
The critical thing I think is that we should only try to fudge the limits if `sfreq` is provided. If it is not, then we have no way of knowing how far apart from `tmin` and `tmax` are from the true original time values. Thinking about what to do with e.g. `_time_mask(np.array([1.], tmin=1.001, sfreq=None)` should hopefully make this clear. If in the original data had `sfreq=100.`, then the extra `0.001` is probably numerical error, and the point should be included, if `sfreq=10000.` then it probably isn't, and the point should be excluded. So in the `sfreq=None` case, which is hopefully very rare, we stay fairly strict. If this causes failures (e.g. it might for `SourceEstimate` since we have no `sfreq` there), we might need to make ad-hoc …
=> MRG: Fix time mask

doc/whats_new.rst, mne/epochs.py, mne/tests/test_epochs.py
Changed `event_id = None`, `tmin = -0.2`, `tmax=0.5`. I changed the value seeing the default in `mne/tests/test_epochs.py`. Reviews and suggestions about the default values please @agramfort @kingjr @teonlamont @jona-sassenhagen @Eric89GXL
closes #2872
=> [MRG]Changed default values of epoch parameters. Fix issue #2872

mne/time_frequency/multitaper.py, mne/time_frequency/tests/test_multitaper.py
Closes #2931.
Upstream bug https://github.com/nipy/nitime/pull/140.
=> MRG: Fix multitaper

mne/baseline.py, mne/epochs.py, mne/evoked.py, mne/io/base.py, mne/minimum_norm/time_frequency.py, mne/tests/test_utils.py, mne/time_frequency/tfr.py, mne/utils.py, mne/viz/topomap.py
Closes #2236.
Streamlines our logging messages about baselines a bit. Now it's done once per object, during instantiation / creation.
=> MRG: Cleaner logging of baselines

doc/whats_new.rst, mne/cov.py, mne/event.py, mne/tests/common.py, mne/tests/test_cov.py, mne/tests/test_event.py
Closes #2867. Related to #2448.
This simplifies our code a bit, and also shows how `compute_raw_covariance` differed from `compute_covariance` under the hood.
As shown in the code, `compute_raw_covariance` has (effectively) `keep_sample_mean=False` by default, whereas `compute_covariance` has `keep_sample_mean=True` by default. This makes me think we should have `keep_sample_mean=None` -> `False` with deprecation message saying it will change to `True` in 0.13. This would really unify the two functions. Thoughts?
=> [MRG+1]: Unify Raw and Epochs-based covariance

mne/channels/channels.py, mne/channels/tests/test_channels.py
=> ENH : better error message when unit is not known

mne/channels/layout.py
When computing 2D EEG locations for topo plotting, there is an error
message when multiple sensors have the same location. However, this
message shows the wrong sensor names when picks are provided.
=> Fix error message for auto EEG coords

examples/preprocessing/plot_resample.py, mne/cuda.py, mne/epochs.py, mne/evoked.py, mne/filter.py, mne/inverse_sparse/tests/test_gamma_map.py, mne/io/base.py, mne/io/fiff/tests/test_raw_fiff.py, mne/source_estimate.py, mne/tests/test_cov.py, mne/tests/test_epochs.py, mne/tests/test_evoked.py, mne/tests/test_filter.py, mne/tests/test_proj.py, tutorials/plot_cluster_stats_spatio_temporal.py, tutorials/plot_cluster_stats_spatio_temporal_2samp.py, tutorials/plot_cluster_stats_spatio_temporal_repeated_measures_anova.py
This PR:
1. Adds `npad='auto'` mode that will set the pad to the shortest pad >= 100 samples that will result in a signal length that is a power of 2.
2. Deprecates the `npad=100` default to have `'auto'` become default in 0.12
3. Uses `rfft` and `irfft` for computations.
This means:
1. If there is an integer ratio of resampling rates (e.g., 1200 down to 100) then it should be *much* faster.
2. Memory usage should be reduced by a factor of 2 during computations.
Closes #2035.
=> MRG: Faster raw resampling

mne/io/bti/bti.py, mne/io/bti/tests/test_bti.py
Currently no failing test is possible as in our test files these fields don't differ. More later.
=> FIX/ENH: use channel labels

mne/viz/decoding.py
closes #2874
@kingjr was there any reason for using `scorer.func_name`?
=> MRG safer plotting of bad chance level in plot_diagonal

examples/datasets/plot_spm_faces_dataset.py, examples/decoding/plot_decoding_spatio_temporal_source.py, examples/inverse/plot_covariance_whitening_dspm.py, examples/inverse/plot_tf_lcmv.py, mne/forward/_compute_forward.py, mne/forward/_lead_dots.py
More memory tweaks.
Closes #2864.
=> MRG: Better memory usage (#2)

mne/time_frequency/psd.py
By default, the seeg channels are not included.
I didn't find a test of the pick types.
Besides this quick fix, I have the impression that a `_pick_data_channels(inst.info)` could be shared across many functions, and could be thus tested once only.
=> BUG: seeg in psd

doc/whats_new.rst, mne/chpi.py, mne/fixes.py, mne/io/base.py, mne/io/fiff/tests/test_raw_fiff.py, mne/tests/test_chpi.py, setup.cfg
Fixes a bug with `chpi` filtering after MaxFilter's downsampling (and ours, even, really).
Ready for review/merge from my end. Hopefully the test comments and code make it clear why this is necessary.
=> MRG: Fix hpi filtering after MF downsample

examples/realtime/plot_compute_rt_average.py, examples/visualization/plot_evoked_erf_erp.py, mne/viz/evoked.py
It seems that some recent changes the behavior so that eog channels are included in the evoked object. This causes a couple of our examples to fail. I can't remember a recent PR that would change the behavior of evoked.
I'm wondering if this is an unintended side effect of some other fix. This seems like an API change, and before fixing the examples, maybe we should figure out why this happens. Any ideas?
This first commit includes a fix to ``plot_evoked_erf_erp`` that is broken because of this. Another one is ``plot_compute_rt_average``.
=> More fixes to examples.

mne/stats/regression.py, mne/stats/tests/test_regression.py
Factor out a bunch of helpers. Prerequisite for 
- encoding models
- reducing redundancy with XDawn (#2332)
=> [MRG+2] refactor linear_regression_raw

doc/whats_new.rst, mne/time_frequency/tests/test_tfr.py, mne/time_frequency/tfr.py
The mtm function has a `decim` param but not the wavelet. It can be useful for memory.
=> ENH: decim param in wavelet convolution

mne/viz/evoked.py
Closes https://github.com/mne-tools/mne-python/issues/3028
Fixes the problem when user provides the axes object to ``evoked.plot``.
=> [MRG] [FIX] to evoked plot when clicked.

circle.yml
With our recent streamlining of the docs and examples, it seems that ``make html_dev`` finally passes on circle without failures. This here auto updates the dev docs on https://github.com/mne-tools/mne-tools.github.io/tree/production.
=> Auto update of dev docs on master.

mne/preprocessing/ica.py
`seeg` are not picked by the ICA (which can be necessary for isolating line noise)
I had a quick look to see whether I should just make one big PR with all seeg picks, but I prefer dealing with them separately as many cases are not trivial / to be discussed (covariance, mixing, plotting, source modeling).
@dengemann
=> FIX: seeg picked by ICA

doc/whats_new.rst, mne/preprocessing/ecg.py
Closes https://github.com/mne-tools/mne-python/issues/3038
The function tried to create the synthetic channel even if channel was provided.
=> Fix to create_ecg_epochs.

mne/cov.py, mne/tests/test_cov.py
Looks like the unification I did of `compute_raw_covariance` can lead to some harsh memory requirements. Currently a copy of the raw data is made 1) when constructing epochs and then again 2) inside `compute_covariance`, tripling memory requirements. This brings it back down to where it used to be.
=> MRG: Reduce memory usage for compute_raw_covariance

mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py
Currently, the MNE version of CORRMAP (and the original) only allows to specify the template by referring to one component of those the algorithm is supposed to label. This allows to, alternatively, specify an array (an IC weight map) as a template. This allows in principle fully automatic usage, provided one has previously used the same montage. It's hopefully helpful for those who wish to preregister their analyses.
~~Missing a test.~~
=> MRG: allow an array as CORRMAP template

mne/io/cnt/cnt.py, mne/io/meas_info.py, mne/io/tests/test_raw.py, mne/io/write.py, mne/tests/test_epochs.py
Closes https://github.com/mne-tools/mne-python/issues/3130.
FIFF tree structure somehow breaks if empty strings are included in some fields. I didn't want to go and check every field at save stage. I think we should instead make sure that these don't exist in the info structure in the first place.
=> Fix to empty fields in info.

mne/tests/test_utils.py, mne/utils.py
Closes #3113.
@jjnurminen you should be able to do `mne.set_config('MNE_SKIP_FTP_TESTS', 'true')` and have it not run those tests. Can you try it?
=> MRG: Allow skipping FTP tests

doc/whats_new.rst, mne/dipole.py, mne/tests/test_dipole.py, tutorials/plot_dipole_fit.py
This is a feature of Xfit that would be nice to have -- constrain `pos` and `ori` when doing dipole fitting so time-courses can be obtained.
=> MRG: Add fixed dipole pos mode

doc/python_reference.rst, doc/whats_new.rst, mne/__init__.py, mne/bem.py, mne/channels/channels.py, mne/channels/layout.py, mne/cov.py, mne/dipole.py, mne/forward/_field_interpolation.py, mne/forward/_make_forward.py, mne/forward/forward.py, mne/io/meas_info.py, mne/preprocessing/ica.py, mne/surface.py, mne/time_frequency/tests/test_tfr.py, mne/viz/topo.py, tutorials/plot_creating_data_structures.py, tutorials/plot_info.py, tutorials/plot_object_epochs.py, tutorials/plot_object_evoked.py, tutorials/plot_object_raw.py
Closes #3149.
95% docstring changes. Now that we have a tutorial for `mne.io.Info` and it's not only for raw io, it makes more sense to have it in the `mne` namespace.
=> MRG: Move Info to mne namespace

doc/whats_new.rst, mne/epochs.py, mne/tests/test_epochs.py
Currently `EpochsArray` implicitly does `proj=True` because of the subclass default `_BaseEpochs.__init__(..., proj=True, ...)`. This makes such behavior optional.
=> MRG: Add proj option to EpochsArray

mne/bem.py, mne/dipole.py, mne/forward/_make_forward.py, mne/tests/test_bem.py, mne/tests/test_dipole.py
Found a small bug where we couldn't actually use a sphere model with no shells (i.e., just origin) in dipole fitting with MEG data only.
=> MRG: Allow use of layer-free model in MEG dipole fitting

examples/stats/plot_linear_regression_raw.py
The old example should be updated for a number of reasons:
1. the method is better memory optimized now
2. some change with projections happened that I didn't understand that actually lead to differences between two plots that should be identical
3. this was exaggerated by slightly different ylims
I've also added a plot of the differences, and made the layout horizontal, which is much nicer.
Would be cool to have for .12
New plot:
=> MRG Update rERP example

doc/getting_started.rst, tutorials/plot_introduction.py
Currently, tutorials render like this due to brackets:
Also, fun fact: Po means butt in German.
=> MRG minor tutorials spelling and formatting

doc/whats_new.rst, mne/viz/tests/test_topomap.py, mne/viz/topomap.py
Closes #3078
Try:
```
import mne
evoked_fname = data_path + '/MEG/sample/sample_audvis-ave.fif'
for type in ('mag', 'grad'):
evoked = mne.read_evokeds(evoked_fname, condition=1).pick_types(eeg=False, meg=type).detrend()
arr = evoked.data[:, 171]
mne.viz.plot_topomap(arr, evoked.info);
```
=> MRG plot_topomap from info

doc/whats_new.rst, mne/io/meas_info.py, mne/tests/test_evoked.py
Closes https://github.com/mne-tools/mne-python/issues/3175
I was able to reproduce the described bug with my own data. The problem occurs when trying to merge infos with list of dicts. In my case it was the hpi info that caused the crash. Fixed by making recursive calls to compare the dicts.
Ready for merge if tests pass.
=> [MRG] Fix to info merging.

doc/whats_new.rst, mne/cov.py, mne/tests/test_cov.py
Found a bug in our raw covariance code. In previous versions (i.e., before my big changes a couple of months ago):
1. Docstring was wrong, it only used data channels (and included bads).
2. It didn't actually do e.g. EOG rejection before even if you supplied the keys. Now it does.
Now in `master` we get an error message if `picks is None` and we reject based on EOG. This makes it still do that rejection, but only compute the covariance for data channels, which I think is the default behavior we want actually.
=> MRG: Fix raw cov

doc/whats_new.rst, mne/decoding/tests/test_time_gen.py, mne/decoding/time_gen.py
* FIX: Addresses issue raised by @dengemann  in https://github.com/mne-tools/mne-python/issues/3125, related to the fact that the current behavior of the decoding algorithm is to apply the score outside the cross-validation, which is not the conventional sklearn way
* changes default scoring mode
* ENH: allows retrieving fold-specific scores
Some [empirical tests here](https://gist.github.com/kingjr/3827a326733204e6e6b8af58c831b12c ). tl;dr: At the exception of `f1_score` (for which I need to think a bit more, I actually never use this metrics), the scoring metrics, if anything, is overestimated when applied per fold (as compared to across trials) when there is information (there isn't a systematic bias when `X` can't predict `y`). Additional simulations could be done to test different …
=> [MRG] GAT cv scores

mne/channels/channels.py, mne/io/__init__.py, mne/io/fiff/tests/test_raw_fiff.py, mne/io/meas_info.py, mne/io/tests/test_meas_info.py
In reference to #2948, this adds a function to forcible update parameters of target info objects using the values from a base info object. Generally meant to facilitate adding new channels that you created from RawArray. A couple thoughts worth mentioning:
* It hard-codes a few fields that it won't update `['chs', 'ch_names', and 'nchan']`. Is that OK and do you think I missed some?
* It will update the fields in target_info without copying first. I could do a deepcopy first and then return info objects, though that'll make it a little clunkier. I did make it so that using the force parameter in `add_channels` *will* deepcopy before updating the infos.
* In general, this is kind of a "dumb" implementation, so I tried to warn about potential ramifications in the doc for the "force" …
=> adding a function to forcibly update measurement infos

mne/io/eeglab/eeglab.py, mne/io/eeglab/tests/test_eeglab.py
Hey there,
I've just had a TypeError with the eeglab event reader with a file that contains only one event. In such case the list comprehension that gathers event types fails because `'mat_struct' object is not iterable`.
This small change fixes the problem.
This is my first PR to mne-python so please be merciful :) If I messed something up I'll be happy to clean up, add something etc.
And just BTW - thanks for your efforts with mne-python, really cool package!
=> fix reading eeglab events if there is only one event in file

tutorials/plot_object_epochs.py
Current memory use of our `plot_object_epochs.py` example is ~2GB and often crashes CircleCI, this takes it to ~600MB.
=> MRG: Fix epochs tutorial memory use

mne/datasets/utils.py, mne/label.py, mne/tests/test_label.py
This adds functionality to take a label with non-contiguous regions and split it into its components. 
Example use case: resting state network parcellations [here](https://surfer.nmr.mgh.harvard.edu/fswiki/CorticalParcellation_Yeo2011). The individual networks contain multiple components, and they need to be disconnected to more easily compute connectivity between the subparts.
=> [MRG] Split labels into contiguous regions

circle.yml, mne/datasets/__init__.py, mne/datasets/utils.py
We were missing a couple EEGBCI data files in our CircleCI downloads. This also moves the downloading code to Python land, which is hopefully a little bit cleaner, as the next time someone uses a new dataset in an example we can tell them to modify a Python function instead of CI code.
=> MRG: Fix paths

doc/whats_new.rst, mne/io/array/tests/test_array.py, mne/io/base.py, mne/io/brainvision/tests/test_brainvision.py, mne/io/fiff/raw.py, mne/io/fiff/tests/test_raw_fiff.py
Fixes a corner case bug where our auto-writing of split raw files would fail if we hit the file size limit right as we used up the last buffer. @kambysese @ChristinaZhao I don't know how you each independently managed to hit this long-standing rare bug in the span of a couple of days, but I'm impressed :) Feel free to try out the fix if you have time.
This PR does a few things to fix it:
1. Adds sanity double-check while writing that we will actually write some data.
2. Adds an extra conditional before splitting the file that only does it if we actually have more data to write.
3. Improves error messages related to bad choices of `buffer_size_sec` and `split_size`.
4. Moves `raw.annotation` reading and writing to come before the data block. This seems to make more sense than having it in …
=> MRG: Fix split file writing

mne/viz/tests/test_utils.py, mne/viz/utils.py
This is a quick extension of #3198. I realized that the function would only pull eeg or meg channels when computing the auto-scaling, but we probably want auto-scaling to work for any channel types. This should add support for the remaining channel types.
=> adding support for other channel types with auto-scale

mne/surface.py
Trying to resolve error during testing on Debian sid, see
http://stackoverflow.com/a/35131392 for origin for the "fix".
Closes #2648 
I have little to no clue in tvtk etc, just nearly blindly following the recipe from stackoverflow  which seems to avoid error during testing at least on debian sid.  Will try now across releases
=> BF: use tvtk.configure_input instead of direct input=src

mne/tests/test_epochs.py
We'll see if this fixes the weird Travis error, probably related to them moving to 0.17.1 and causing some small numerical issue.
=> MRG: Minor fix

doc/whats_new.rst, mne/io/cnt/cnt.py, mne/io/cnt/tests/test_cnt.py
Closes https://github.com/mne-tools/mne-python/issues/3232.
This allows reading cnt data in int32. The data itself has no information about the data format, so I added a parameter.
Also added a param to define the date format.
=> [MRG] Options for setting data and date formats for cnt data.

mne/io/edf/edf.py
Beer related bug when reading EDF files: strings were being decoded but not used anyway. Removed that in order to be able to read french EDF files.
=> EDF reading BUG related to unicode sting handling

doc/manual/appendix/bem_model.rst, mne/bem.py, mne/commands/mne_flash_bem.py
When analyzing data on FAT32, I encountered a non-explicit error with `mne_watershed_bem` as it attemps to create a symbolic link, which isn' possible on all types of partitions.
=> FIX: symbolic links on non NTFS partition

doc/whats_new.rst, mne/preprocessing/ica.py, mne/viz/tests/test_topomap.py, mne/viz/topomap.py
Noticed that the color range is too large for small activations when using multiple ``times`` in evoked topomaps. This is because the full range is always used. This means that the colors in colorbar don't correspond to the colors in topomaps (except the one with highest activation).
=> [MRG][FIX] Evoked topomap colors correspond to the colorbar.

doc/whats_new.rst, mne/channels/channels.py, mne/io/__init__.py, mne/io/base.py, mne/io/fiff/tests/test_raw_fiff.py, mne/io/meas_info.py, mne/io/tests/test_meas_info.py
We currently could only anonymize `raw` data. This allow anonymizing any `Info`, and add the method to `Epochs` so that we can share already preprocessed data that happened not to be anonymized.
=> MRG: anonymize_info function

mne/io/eeglab/eeglab.py, mne/io/eeglab/tests/test_eeglab.py
Old EEGLAB versions seemingly allow integer event codes.
closes #3264
Not sure how to test - we probably don't want to add another test file just for this.
=> MRG robustness to old EEGLAB versions

doc/whats_new.rst, mne/epochs.py, mne/evoked.py, mne/tests/test_epochs.py, mne/tests/test_evoked.py
Also fixes a bug with existing `Epochs.decimate` when the `offset` parameter is used.
Closes #3287.
Closes #3296.
=> MRG: Add Evoked.decimate

doc/whats_new.rst, mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py
It seems like the error with #3267 is that the user can define channels which are not supported data channels.
In my current code I have added a simple method that crashes the program if there are unsupported channels defined by the user. I also added EOG as an acceptable channel. 
@agramfort @Eric89GXL any ideas on how to proceed? 
Two things that still need to be addressed in my eyes are: 1) should EOG be included as a supported channel? 2) how would I raise an appropriate error for bad channels being present?
=> MRG: Ica inf values fix

mne/viz/topomap.py
When saving an animation to use with `HTML(anim.to_html5_video())` in
ipython notebooks it seems necessary to disable blit manually.
=> FIX: don't always overwrite blit to True

doc/whats_new.rst, mne/simulation/source.py, mne/simulation/tests/test_source.py
Adds a check that labels in `simulate_stc` do not overlap. If they did, in `master` the error would be cryptic:
```
File "/home/larsoner/custombuilds/mne-python/mne/simulation/source.py", line 219, in simulate_stc
stc = SourceEstimate(data, vertices=vertno, tmin=tmin, tstep=tstep)
File "<string>", line 2, in __init__
File "/home/larsoner/custombuilds/mne-python/mne/utils.py", line 629, in verbose
return function(*args, **kwargs)
File "/home/larsoner/custombuilds/mne-python/mne/source_estimate.py", line 975, in __init__
verbose=verbose)
File "<string>", line 2, in __init__
File "/home/larsoner/custombuilds/mne-python/mne/utils.py", line 629, in verbose
return function(*args, **kwargs)
File "/home/larsoner/custombuilds/mne-python/mne/source_estimate.py", line 443, in __init__
raise …
```
=> MRG: More strict check in simulation

mne/simulation/evoked.py, mne/simulation/source.py, mne/simulation/tests/test_source.py
@nfoti I think removing the projections is a reasonable thing to do. Would this docstring have saved you a bit of annoyance when using `simulate_evoked`?
Note I also added auto `stc.subject` setting in `simulate*_stc`.
=> MRG: Set subject when simulating source

mne/source_estimate.py, mne/tests/test_source_estimate.py
Gives a more informative error message when users request a `grade` that can't be constructed for a subject. Previously they would get an error about vertices needing to be in ascending order, now they get a more informative message like "Cannot use icosahedral grade 6 with subject sample, mapping 40962 vertices onto the high-resolution mesh yields repeated vertices".
Apparently @nfoti is hitting a lot of corner cases for us :)
=> MRG: Better error message for morph

mne/fixes.py, mne/preprocessing/maxwell.py
I keep hitting an annoying "SVD did not converge" error, and traced it to an [Intel bug] (https://software.intel.com/en-us/forums/intel-distribution-for-python/topic/628049). Who knows when they will fix it, and when that fix will make its way into Anaconda. In the meantime, this works around it if SciPy 0.18 is avaliable by using a different `lapack_driver`.
=> MRG: Workaround for Intel bug

doc/whats_new.rst, mne/io/reference.py, mne/io/tests/test_reference.py
Closes #3338
There was a test missing for setting multiple references with the `mne.io.set_bipolar_reference` function. With the back and forth on the `Info` object, this case therefore slipped through the regression testing. This PR adds the test and fixes the code.
=> Fix bug in set_bipolar_reference

mne/gui/_coreg_gui.py
Just a small usability improvement for the [+]/[-] buttons for scaling MRIs. Previously pressing [-] would lead to a sequence like `[1, 0.990099009901, 0.980296049407, 0.970590147928, ...]`. With this PR it will be `[1, 0.99, 0.98, ...]`
=> [MRG] GUI (coregistration):  scale step +/- instead of multiplicative

doc/conf.py
Takeover from https://github.com/mne-tools/mne-python/pull/3344
=> [MRG] Example link

doc/whats_new.rst, mne/evoked.py, mne/viz/evoked.py, mne/viz/tests/test_evoked.py, mne/viz/tests/test_topo.py
For spatial_colors Butterfly plots, zorder matters. Currently, channel zorder is basically random - often, but not always, the nice red lower right channels are plotted last, and thus appear on top, giving the beautiful purple rainbow.
However, often, this means if you have two overlapping effects, the stronger one will occlude the weaker. 
This PR makes it so that the channels with the least activity are plotted on top. It's less beautiful, but probably more functional.
Do you like it?
Old
New
=> MRG spatial colors z order by auc

mne/io/eeglab/eeglab.py, mne/io/eeglab/tests/test_eeglab.py
We recently fixed old EEGLAB versions that could store events as integers. However, we only fixed it for the multi-event case. This takes care of the single-event case.
=> MRG fix eeglab single integer event

mne/viz/raw.py, mne/viz/tests/test_raw.py
Currently when running `raw.plot_psd()` with data containing a dead channel an empty plot is created. Should the fix treat the dead channel like a normal channel or raise a warning or error?
=> [MRG] raw.plot_psd() with flat channel

.travis.yml, appveyor.yml, doc/python_reference.rst, mne/__init__.py, mne/bem.py, mne/commands/mne_flash_bem.py, mne/commands/tests/test_commands.py, mne/datasets/utils.py, mne/fixes.py, mne/surface.py, mne/tests/test_bem.py, mne/tests/test_surface.py, mne/utils.py
Closes https://github.com/mne-tools/mne-python/issues/3107
closes https://github.com/mne-tools/mne-python/issues/3281
For most parts I had no idea what I was doing, but it seems to give similar results.
=> [MRG] convert surface using python.

doc/whats_new.rst, mne/channels/layout.py, mne/decoding/base.py, mne/decoding/csp.py, mne/epochs.py, mne/evoked.py, mne/preprocessing/ica.py, mne/time_frequency/tests/test_tfr.py, mne/time_frequency/tfr.py, mne/viz/epochs.py, mne/viz/evoked.py, mne/viz/tests/test_epochs.py, mne/viz/tests/test_evoked.py, mne/viz/tests/test_ica.py, mne/viz/tests/test_topomap.py, mne/viz/topo.py, mne/viz/topomap.py, mne/viz/utils.py, tutorials/plot_visualize_epochs.py
Closes https://github.com/mne-tools/mne-python/issues/3005
Also:
closes https://github.com/mne-tools/mne-python/issues/3063
=> [MRG+1] Draggable colorbar.

mne/viz/utils.py
This fixes a bug that was introduced when matplotlib changed the way that axes are added. Now, if an axis is added to a figure with the same parameters as another axis, it just returns the already-existing axis instead of creating a new one. This patch adds a `label='background'` flag to the axis creation so that it's treated as a new axis. Addresses #3361 
@agramfort
=> fixing a bg plotting bug for topo plots

mne/viz/epochs.py
Another small change to `plot_epochs_image` - I made it separate from the other PR, because it is not necessarily a bug.
Currently `vmin` and `vmax` are set before smoothing (using `sigma`) so if one uses `sigma` the colorscale is not fully used (smoothed data will have lower min and max values etc.).
You can see the difference here:
*Before*:
*After*:
:warning: 
Now the vmin, vmax are not set based on the whole data, but based on the first smoothed channel (out of those in picks). I could move smoothing out of the figure-loop - so that all picks are smoothed before the loop and vmin, vmax are set based on the whole smoothed data.
=> [MRG] set vmin, vmax after smoothing in plot_epochs_image

circle.yml, mne/surface.py, mne/tests/test_bem.py, tutorials/plot_background_filtering.py, tutorials/plot_visualize_raw.py
Closes #3357.
Today is Sunday right @agramfort? :)
=> MRG: Build relevant examples

doc/whats_new.rst, mne/preprocessing/tests/test_xdawn.py, mne/preprocessing/xdawn.py
`sklearn.cross_validation.ShuffleSplit` shuffle the epochs order and broke Xdawn.
cc @kaichogami @alexandrebarachant
=> FIX: Xdawn with shuffled epochs

tutorials/plot_artifacts_correction_ica.py
=> [MRG] fix component inds in ica tutorial

mne/bem.py
Closes https://github.com/mne-tools/mne-python/issues/3112
=> Warnings for big bems.

mne/simulation/evoked.py, mne/simulation/tests/test_evoked.py
This is for testing the circle caching, but I thought I'd tackle an issue in the meantime.
Closes https://github.com/mne-tools/mne-python/issues/3370
See if this is good enough.
=> Error message for simulate evoked.

doc/python_reference.rst, doc/whats_new.rst, mne/cov.py, mne/preprocessing/ica.py, mne/tests/test_cov.py, mne/viz/__init__.py, mne/viz/ica.py
Fixes a bug where the channel order / indexing in `prepare_noise_cov` could lead to `AssertionError` or (worse) silent errant selection of channels.
=> MRG: Fix covariance order

mne/channels/montage.py, mne/channels/tests/test_montage.py
Replace file parser for .sfp files. Less efficient, but should not choke on long channel names.
~~Missing dedicated test for the specific scenario this is aimed to fix.~~
Closes #3385
=> fix long sfp chan names

mne/baseline.py, mne/time_frequency/tfr.py
* Fixes issue #3263
* Also added the documentation for the `percent` `mode` in `mne.baseline.rescale`.
* I have a pep8 issue in the number of characters per line in some comments, I don't really know what is the appropriate way to fix it (as we both want less than 80 chars and all the possible values of the argument).
=> [FIX][DOC] Fix documentation for TFR.plot

examples/realtime/ftclient_rt_average.py
This was broken when eog channel was made a default when using `plot_evoked`.  @jaeilepp suggested adding `plot_` in front of this example so we add this to continuous integration ...
=> FIX realtime example for eog channel

mne/dipole.py, mne/simulation/tests/test_raw.py, mne/tests/test_dipole.py
Fixes a minor bug where `bem` could not be a `ConductorModel` (had to be string path). Also shows disappointing dipole fit quality with BEM, but MNE-C's dipole routines and Xfit's agree with ours. Not sure if it's a limitation of dipole fitting, or of our raw simulation. I'll keep looking into it, but in the meantime this should be good to go.
=> MRG: Minor bug with dipole fitting

mne/epochs.py, mne/fixes.py, mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_maxwell.py
From talking to @staulu this seems like a better / more principled way to set `mag_scale` in Maxwell filtering. This should help remove some of the mystery from the 100 value that used to be there.
@wronk can you have a look and see if it makes sense to you?
=> MRG: Allow setting mag_scale in maxwell_filter

doc/whats_new.rst, mne/epochs.py, mne/evoked.py, mne/io/base.py, mne/io/fiff/tests/test_raw_fiff.py, mne/tests/test_utils.py, mne/utils.py
Closes #3401.
For example:
```Python
>>> print(mne.io.read_raw_fif('sample_audvis_raw.fif'))
<Raw  |  sample_audvis_raw.fif, n_channels x n_times : 376 x 166800 (277.7 sec), ~3.8 MB>
>>> print(mne.io.read_raw_fif('sample_audvis_raw.fif', preload=True))
<Raw  |  sample_audvis_raw.fif, n_channels x n_times : 376 x 166800 (277.7 sec), ~482.3 MB>
>>> print(mne.read_epochs('sample-epo.fif', preload=False))
<EpochsFIF  |  n_events : 121 (all good), tmin : -0.0998976065792 (s), tmax : 1.0006410259 (s), baseline : (-0.0998976081609726, 0.0), ~3.8 MB,
u'Auditory/Left': 57, u'Auditory/Right': 64>
>>> print(mne.read_epochs('sample-epo.fif'))
<EpochsFIF  |  n_events : 121 (all good), tmin : -0.0998976065792 (s), tmax : 1.0006410259 (s), baseline : (-0.0998976081609726, 0.0), ~233.6 MB, …
```
=> MRG: Add memory usage to primary objects

circle.yml, doc/Makefile, doc/python_reference.rst, doc/tutorials.rst, mne/cov.py, mne/datasets/brainstorm/__init__.py, mne/datasets/brainstorm/bst_phantom_ctf.py, mne/datasets/brainstorm/bst_phantom_elekta.py, mne/datasets/utils.py, mne/dipole.py, mne/forward/_compute_forward.py, mne/tests/test_cov.py, mne/tests/test_dipole.py, mne/tests/test_import_nesting.py, mne/tests/test_line_endings.py, tutorials/plot_brainstorm_phantom_ctf.py, tutorials/plot_brainstorm_phantom_elekta.py
Tutorials for the [Elekta] (http://neuroimage.usc.edu/brainstorm/Tutorials/PhantomElekta) and [CTF] (http://neuroimage.usc.edu/brainstorm/Tutorials/PhantomCtf) phantoms from the Brainstorm datasets. Our localization is similar for CTF, and slightly better for Elekta because I applied `maxwell_filter` to it (and similar otherwise).
Closes #2937.
=> MRG: phantom tutorials

doc/python_reference.rst, mne/__init__.py, mne/forward/forward.py, mne/proj.py, mne/simulation/evoked.py
Wonder if this should be changed, even though `Forward` is a `dict` subclass, to make it consistent with `read_forward_solution` which is said to return `Forward`
=> DOC:  Forward solution is `Forward` instead of `dict`

mne/decoding/tests/test_csp.py, mne/decoding/tests/test_time_gen.py, mne/tests/test_cov.py, mne/tests/test_source_space.py, mne/utils.py, mne/viz/tests/test_topo.py
It occurred to me that we might not want to omit warnings if people have `verbose='error'`
=> MRG: Only warn using given verbose level

doc/whats_new.rst, mne/datasets/utils.py, mne/gui/_file_traits.py, mne/tests/test_utils.py, mne/utils.py, mne/viz/epochs.py, mne/viz/utils.py, tutorials/plot_introduction.py
Closes #3274.
Changes `set_config(..., set_env=True)` in 0.14, so that setting config updates `os.environ`, too, by default.
=> MRG: Set env vars in set_config

doc/whats_new.rst, mne/commands/mne_make_scalp_surfaces.py, mne/commands/tests/test_commands.py
Closes #3435.
Adds an option not to decimate. @dengemann what do you use the other decimations (medium, sparse) for? I don't think they're part of the standard processing scheme...?
=> MRG: Dont require TVTK

examples/decoding/plot_decoding_xdawn_transformer.py
closes https://github.com/mne-tools/mne-python/issues/3433
@kaichogami in the future please check that your new examples are working. There were two bugs in this one.
Also note that you'll have to change the missing `EpochsVectorizer` by a `Vectorizer` in #3409
=> MRG: Fix Xdawn example using EpochsVectorizer and y.ravel()

doc/whats_new.rst, mne/channels/channels.py, mne/channels/layout.py, mne/io/base.py, mne/io/compensator.py, mne/io/ctf/info.py, mne/io/fiff/raw.py, mne/io/fiff/tests/test_raw_fiff.py, mne/io/tests/test_compensator.py, mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_maxwell.py, mne/tests/test_epochs.py, tutorials/plot_brainstorm_phantom_ctf.py
Closes #3071.
Makes our compensation a bit clearer, and should fix a couple of small bugs related to it in `maxwell_filter` and some `mne.layout` functions.
Also deprecates the `compensation` parameter of `read_raw_fif` in favor of `raw.apply_gradient_compensation`, since really it 1) should be done separately, 2) should be able to be applied multiple times, and 3) be doable both for `Raw` and `RawCTF` (i.e., moved to `_BaseRaw` as a method).
=> MRG: Clearer compensation

mne/preprocessing/tests/test_maxwell.py, mne/tests/test_utils.py, mne/utils.py
@kingjr recently hit the dreaded MKL bug. The next time it happens, this can allow us to avoid holding up a PR.
=> MRG: Add decorator for MKL errors in tests

doc/whats_new.rst, mne/viz/misc.py, mne/viz/tests/test_misc.py
I wanted to plot a brain (white matter) surface along with the other bem surfaces, to this end I modified `viz.plot_bem` by adding a `brain_surfaces` argument. If this is generally useful (and there isn't already another preferred way to do this) and you agree with the API I will document it and make this PR ready.
`mne.viz.plot_bem(subject, subjects_dir, brain_surfaces='white')`
(updated)
=> [MRG] viz.plot_bem():  include brain surfaces

doc/manual/decoding.rst, doc/whats_new.rst, examples/decoding/plot_decoding_xdawn_eeg.py, examples/decoding/plot_decoding_xdawn_transformer.py, examples/realtime/plot_compute_rt_decoder.py, examples/realtime/rt_feedback_server.py, mne/decoding/__init__.py, mne/decoding/tests/test_transformer.py, mne/decoding/transformer.py
This was previously on #3276. The idea is to support MNE transformers with scikit-learn pipeline and be compatible with `cross_val_score` and `grid_search` methods. Ideally this should be in the last step in a pipeline to convert higher dimension output into two dimension.
Example
```
clf = make_pipeline(SptialFilter(), XdawnTransformer(), Vectorizer(), LogisticRegression())
cross_val_score(clf)
```
=> [MRG] Vectorizer class to help chain MNE transformers by converting o/p into 2D

mne/epochs.py, mne/time_frequency/tfr.py, mne/viz/tests/test_utils.py, mne/viz/topo.py, mne/viz/utils.py
Exposes the `fig_background` kwarg to epochs image plots, as well as TFR plots. This had already been done for Evoked plots but not for these. If there are other plots that this would make sense for, I could do that too...
=> adding background image to other topoplots

doc/whats_new.rst, mne/datasets/utils.py, mne/io/edf/edf.py, mne/io/edf/tests/test_edf.py
Relate to the issue: https://github.com/mne-tools/mne-python/issues/3420
- skip invalid characters in EDF file annotations
- warn for not implementation of overlapping annotations instead of raising an error
=> EDF Import: invalid char & overlapping annotations

mne/decoding/base.py, mne/decoding/tests/test_search_light.py
Init was throwing an error at search light init because Ridge doesn't have a transform method, although SearchLight should accept both estimators and transformers
```
from sklearn.linear_model import Ridge
from mne.decoding import SearchLight
SearchLight(Ridge())
````
=> [MRG]: check estimator / transformer

mne/epochs.py
closes https://github.com/mne-tools/mne-python/issues/3478
I didn't manage to reproduce it with made up data :/
Shall I update whatsnew?
=> FIX: concatenate with almost equal times

examples/decoding/plot_decoding_xdawn_transformer.py
This PR is an improvement of the Xdawn transformer example. It is made to replace the `plot_decoding_csp_space.py` example. Decoding accuracy is now 99.6% instead of 90.3% for the CSP example.
Using CSP for decoding of evoked potential (with log-variance as feature) is both conceptually wrong and inefficient in practice. I suggest we remove the CSP example. MNE should not showcase bad habits. the `plot_decoding_csp_eeg.py` example is already covering the correct way to use CSP (to decode induced activity).
=> ENH: Improvement over the Xdawn Transformer example

doc/Makefile, doc/_templates/class.rst, doc/manual/pitfalls.rst, doc/whats_new.rst, mne/evoked.py, mne/io/meas_info.py, mne/tests/test_epochs.py, mne/tests/test_evoked.py, mne/utils.py, tutorials/plot_brainstorm_auditory.py, tutorials/plot_dipole_fit.py, tutorials/plot_eeg_erp.py, tutorials/plot_introduction.py
I think this is the API we talked about in #3363.
~~There is a backward-incompatible change -- `combine_evokeds(..., weights='equal')` or `combine_evokeds(..., weights=ndarray)` used to set `out.nave` using some simple computations, but according to our discussion it's safer for inverse modeling not to do that. So this makes it `out.nave = None`.~~
~~Labeled as WIP because I need to clean it up a little bit (see below) before merge, but we need to agree on the API before I do that.~~
~~I don't like the name I chose `summation_weights`, so feel free to suggest others.~~
~~Once we converge, I still need to:~~
=> MRG: Change evoked arithmetic

mne/time_frequency/tfr.py
I suspect this should yield some modest speed gains. We were using an N-dimensional general `fftn` for 1D FFTs when I think we should be able to use the 1D `fft` instead.
cc @jona-sassenhagen
=> MRG: Use fft instead of fftn

mne/channels/channels.py, mne/channels/layout.py, mne/cov.py, mne/epochs.py, mne/evoked.py, mne/io/base.py, mne/io/fiff/raw.py, mne/io/meas_info.py, mne/io/pick.py, mne/preprocessing/ica.py, mne/source_estimate.py, mne/tests/test_utils.py, mne/utils.py, mne/viz/epochs.py, mne/viz/ica.py, mne/viz/topomap.py
There is a common pattern we employ where we have a function that does something:
def plot_object(object):
"""Very long docstring, many parameters"""
and then we have a method that calls this function:
class object:
def plot(self):
"Very long docstring, many parameters"""
plot_object(self)
To have proper docstrings for both the function and the method, we copy/paste it. This is annoying, hard to read and prone to errors as we update one of the docstrings and not the other (see for example `mne.epochs.plot_drop_log` where the doc erroneously claims it returns a tuple).
This PR introduces two decorators to re-use a docstring:
@copy_doc
@copy_function_doc_to_method_doc
The first one simply copies the docstring from one function to another. This is useful when subclassing something and …
=> [MRG+2] Refactor docstrings

doc/whats_new.rst, examples/preprocessing/plot_run_ica.py, mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py, mne/tests/test_utils.py, mne/utils.py, tutorials/plot_artifacts_correction_ica.py
I'll do docs clearing in a separate PR, this is just for ic sorting.
Currently it works this way:
```python
from mne.preprocessing.ica import _ica_explained_variance, _sort_components
var = _ica_explained_variance(ica, epochs)
var_ord = var.argsort()[::-1]
ica_sorted = _sort_components(ica, var_ord, copy=True)
```
The question I have is: should components be sorted by default? It makes sense to me to sort by default, but I have eeglab background so I am used to sorted components.
BTW - both infomax and fastica components are "unsorted", but I remember someone here saying fastica sorts components by exaplained variance?
If sorting shouldn't be made default then maybe a `sort` argument to `fit` method?
=> [MRG+1] sort ica components by explained variance and add _get_inst_data

doc/whats_new.rst, mne/preprocessing/infomax_.py
Specifically, the `extended` argument now really defaults to `True` (the docstring claimed this before even though it was really `False`). I prettified the docstring and comments, added the defaults in the docstring, and replaced `if extended is True:` with `if extended:`.
=> Clean up infomax

doc/python_reference.rst, doc/whats_new.rst, mne/preprocessing/__init__.py, mne/preprocessing/ica.py, mne/viz/tests/test_ica.py, mne/viz/topomap.py, tutorials/plot_artifacts_correction_ica.py
@agramfort once asked for ic properties to be shown when clicking on a topo in `plot_components`.
This requires passing the raw/epoched data to `plot_components`. Currently the data can be passed in `data` argument, but I am open to other names/solutions.
This works ok for me, but:
* is suboptimal, it would be better/faster to copy ic topomaps from main figure and not plot them again, similarily - the spectra are calculated each time you click on an ic. However, copying topomaps and caching spectra would be good for another (potential) PR
=> [MRG] open ic properties on topo click in plot_components + changes to the wording in ica tutorial (clarifications, typos)

doc/whats_new.rst, mne/io/eeglab/eeglab.py, mne/io/eeglab/tests/test_eeglab.py
@agramfort 
Sorry it took so long, forgot about that. 
Now `read_epochs_eeglab` and `read_raw_eeglab` expose `uint16_codec`.
Additional changes:
* the warning when multiple events are found in an epoch - is now raised only once, not for each epoch.
* minor fixes to the docstrings - `verbose` arg didn't use `|` when listing possible input types
* fixes reading one channel set files
TODO:
=> [MRG] expose uint16_codec in eeglab reader (+ minor fixes)

mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_maxwell.py
Addresses cases where the `head_pos` argument are likely invalid, which can happen if MaxFilter's head position fitting routines fail badly.
=> MRG: Check and warn for bad pos

doc/whats_new.rst, mne/channels/montage.py, mne/channels/tests/test_montage.py
Previously units were not read from .elc files. This caused all
units to be interpreted as meters.
=> [MRG] FIX: Read units from .elc montage files

mne/coreg.py, mne/gui/__init__.py, mne/gui/_coreg_gui.py, mne/gui/_fiducials_gui.py, mne/gui/_file_traits.py, mne/gui/tests/test_coreg_gui.py, mne/gui/tests/test_fiducials_gui.py, mne/gui/tests/test_file_traits.py, mne/utils.py
=> [MRG] ENH coreg-GUI:  use high-res head shape if available

mne/io/reference.py, mne/io/tests/test_reference.py
This fixes a new bug where adding a reference channel without digization points fails. I've included a test that fails without the fix.
=> MRG+1: Add reference without digization points (bugfix)

mne/time_frequency/tests/test_tfr.py, mne/time_frequency/tfr.py
Is there a reason for AverageTFR.apply_baseline not to return self, like all other instance methods that modify the instance? If not, this makes it return self.
=> MRG AverageTFR.apply_baseline return self

mne/event.py, mne/io/constants.py, mne/utils.py
Newer Elekta systems (at least TRIUX) use 'STI101' as the combination trigger channel, so it should be the default. If not found, fall back to 'STI 014'
Fixes #3554
=> default to STI101 instead of STI 014

doc/whats_new.rst, mne/channels/interpolation.py, mne/channels/tests/test_interpolation.py
I added a test, which basically reproduces the problem that was there. If the trigger channel was before the MEG channels, then trying to interpolate the first MEG channel would produce an error. This PR fixes that
=> MRG bug with picks in interpolation code

doc/whats_new.rst, mne/gui/_kit2fiff_gui.py, mne/gui/tests/test_kit2fiff_gui.py, mne/io/kit/kit.py
Some enhancements to the KIT2FIFF GUI:
- button to preview the events: this is something I've wished for many times, makes it easier to make sure one has selected the right event settings
- button to plot raw (just uses `raw.plot()`). On my setup this works nicely with the traits gui.
=> [MRG] Kit2fiff GUI: Test event settings

doc/whats_new.rst, mne/io/brainvision/brainvision.py, mne/io/brainvision/tests/test_brainvision.py
Close #3577. Title really says it all --  makes the reader more consistent with the behavior of `Raw.filter` when `picks is not None`. 
Hopefully, the user is paying attention to his warnings and/or not doing online filtering, much less heterogeneous filtering. Should we include a note on this behavior somewhere in the documentation? Do any of the other file formats support heterogeneous channel filter settings?
=> use weakest filter settings for heterogeneous channel filters

mne/io/bti/bti.py, mne/io/bti/tests/test_bti.py
After 4 years no one has cried about the compensation matrices. Currently these warnings are driving me nuts in mne-hcp. I'd suggest to degrade them to simple info messages. I updated the tests accordingly.
cc @Eric89GXL @jaeilepp
=> ENH/FIX: get rid of comp matrix warning

mne/time_frequency/_stockwell.py, mne/time_frequency/tests/test_stockwell.py
This is the continuation of PR #3605, which was closed due to commit chaos.
There were two related errors in `time_frequency/_stockwell.py`. Both were relevant only if the input data to the Stockwell transform has 2**N samples.
1) in `_check_input_st(x_in, n_fft)`: Return was indented wrongly and zero_pad was undefined iff `n_fft == 2**N`.
2) In _precompute_st_windows: The computation of TFR was wrong if `zero_pad == 0`.
This PR fixes these errors and adds two new tests in `time_frequency/tests/test_stockwell.py`
=> Fix Stockwell transform when n_fft is power of two

doc/whats_new.rst, mne/preprocessing/infomax_.py, mne/preprocessing/tests/test_infomax.py
@Eric89GXL , @agramfort (this is the bug that I talked to you this week)
This pull request aims to solve an issue related with infomax when weights in not None.
The current infomax implementation does all its calculations using a transposed version of the weights matrix, and at the end it returns weights.T. But, if the user gives as input a weights matrix, infomax will take it as it is, that is, it will not transpose it, which results in a subtle error:
the algorithm will run, but the result will not be correct because it has not used the correct initial weights matrix.
Reproducibilitiy of this subtle error: 
If we run infomax using max_iter=0, the resulting weights matrix should be the same initial weights matrix provided by the user: …
=> Solving issue related with infomax when weights in not None

doc/whats_new.rst, mne/io/base.py, mne/io/edf/edf.py, mne/io/nicolet/nicolet.py
This fixes a long-standing bug where we defaulted to 10. sec instead of 1. sec for our raw FIF buffer size.
=> MRG: Buffer size 1 sec

mne/externals/FieldTrip.py, mne/realtime/fieldtrip_client.py
Tried to run `ftclient_rt_compute_psd` example on TRIUX system, and getting:
```
File "/home/jussi/projects/mne-python/mne/io/pick.py", line 301, in pick_types
kind = info['chs'][k]['kind']
KeyError: 'kind'
```
Looking at the code, I discovered that 'kind' is not written for TRIUX sys channels which causes example to fail. Fixed here.
(Maybe the if..elif should also raise an exception for unknown channel types to make it safer).
=> fix sys channel in fieldtrip client

doc/python_reference.rst, doc/whats_new.rst, mne/connectivity/tests/test_spectral.py, mne/decoding/transformer.py, mne/filter.py, mne/io/fiff/tests/test_raw_fiff.py, mne/preprocessing/ecg.py, mne/preprocessing/eog.py, mne/preprocessing/ica.py, mne/tests/test_filter.py, mne/viz/__init__.py, mne/viz/misc.py, mne/viz/tests/test_misc.py, tutorials/plot_background_filtering.py, tutorials/plot_brainstorm_auditory.py
Can't merge until #3622 is in.
This deprecates `band_stop_filter`, `band_pass_filter`, `low_pass_filter`, and `high_pass_filter` in favor of `filter_data` (one way to do things) but it's easy to undo the deprecation if that's preferred.
Still need to do some docstrings and eliminate some uses of newly deprecated functions, but the basic plotting functions are getting there.
Closes #3625.
=> MRG: plot_filter

mne/gui/tests/test_kit2fiff_gui.py, mne/gui/tests/test_marker_gui.py, mne/utils.py
Now it should include msg why actually skipping, e.g.
```
SKIP: Test test_kit2fiff_model skipped, requires mayavi. Got exception (No module named pyface.tvtk_scene)
``` 
Closes #3645
=> ENH+BF: skip two tests requiring mayavi, and include into SkipTest caught exception

mne/realtime/fieldtrip_client.py
I was testing the realtime client and got an error from `_guess_measurement_info` when it could not parse CHPI* channels that were sent (from a file) to the FieldTrip buffer. (The code does not write the 'kind' field for unknown channel types). I already had the same problem with TRIUX sys channels.
I propose this small fix that would simply skip updating `info['chs']` if it cannot comprehend the channel type. That should make it more future proof.
=> [MRG+1]: skip updating meas info on unknown channel type

mne/coreg.py, mne/gui/_fiducials_gui.py
I noticed that after just running `$ mne make_scalp_surfaces` I did not have the standard head-bem.fif. Before this PR that was how subjects were discovered by the GUI. Now the heads from `$ mne make_scalp_surfaces` will also be discovered, and displaying the head shape will be consistent.
=> [MRG+1] FIX coreg-gui:  find head shapes

mne/gui/_coreg_gui.py, mne/gui/_fiducials_gui.py, mne/gui/_file_traits.py, mne/gui/_kit2fiff_gui.py, mne/gui/_marker_gui.py, mne/gui/_viewer.py, mne/gui/tests/test_coreg_gui.py, mne/gui/tests/test_fiducials_gui.py, mne/gui/tests/test_file_traits.py, mne/gui/tests/test_kit2fiff_gui.py, mne/gui/tests/test_marker_gui.py, mne/tests/test_docstring_parameters.py, mne/utils.py, setup.cfg
WIP following up on https://github.com/mne-tools/mne-python/pull/3383
=> [MRG+1] move trait import out of `try` block

mne/chpi.py
I wanted to get HPI freqs from an Evoked where only MEG* channels were present using `_get_hpi_info`.
It failed, since in this case `pick_channels` returns an empty list trying to pick SYS201 and then the code tries to index it.
I added a check for nonempty list.
=> do not index empty list in _get_hpi_info

mne/channels/channels.py
Before:
```
test_icarename.py:8: RuntimeWarning: The unit for channel ICA 002 has changed from NA to V.
raw.set_channel_types(mapping);
The unit for channel ICA 002 has changed from NA to V.
test_icarename.py:8: RuntimeWarning: The unit for channel ICA 005 has changed from NA to V.
raw.set_channel_types(mapping);
The unit for channel ICA 005 has changed from NA to V.
test_icarename.py:8: RuntimeWarning: The unit for channel ICA 001 has changed from NA to V.
raw.set_channel_types(mapping);
The unit for channel ICA 001 has changed from NA to V.
test_icarename.py:8: RuntimeWarning: The unit for channel ICA 003 has changed from NA to V.
raw.set_channel_types(mapping);
The unit for channel ICA 003 has changed from NA to V.
test_icarename.py:8: RuntimeWarning: The unit for channel ICA 004 has …
```
=> cleanup warnings for _set_chan_type

mne/channels/montage.py, mne/channels/tests/test_montage.py
#3613 breaks .elp reading by doing a transpose at the wrong time. This fixes it.
@Eric89GXL
(sorry for the mess, I'm not used to having upstream push access ...)
Closes #3684
=> [MRG+1] fix elp reading

mne/io/fiff/tests/test_raw_fiff.py, mne/io/meas_info.py, mne/tests/test_surface.py
Dicts have no guaranteed order, so the `_is_equal_dict` using a `zip` of `.items()` was unsafe. This uses `object_diff`, which uses a more careful algorithm.
FYI @jaeilepp the CI failure from #3685 was random (as in unpredictable), but it was also real (as in not safely ignored). It made a test fail in #3707, for example. This should fix it, though.
=> MRG: Fix info equiv check

mne/tests/test_utils.py, mne/utils.py
This is a hopefully tiny PR to add iterable functionality to progressbars. The reason for it is that I often used `tqdm` for my own progress bars, but when developing with MNE need to remove those instances from the code. Since it's common to iterate through a list / tuple / whatever and simply increment the progress by "1" on every iteration, I added an `__iter__` method that would let you do something like:
```
for ii in pbar(list_of_datasets):
...
```
and it'd automatically increment by 1 on each loop.
The only real change is that `ProgressBar` would now accept either an `int` as input, or an `iterable`.
LMK
=> adding iterable support for progressbars

doc/whats_new.rst, mne/io/meas_info.py, mne/io/tests/test_meas_info.py
`anonymized()` throw me an error on some edf files whose file_id and meas_id fields where missing
=> FIX: anonymize info when missing fields

mne/io/kit/kit.py
For UMD files from system ID 52 reference channels seem to be labeled differently. Is it worth adding another small raw file for the tests?
The actual Fix is lines 608-15, everything below is just refactoring I did while debugging and could be reverted.
CC @teonbrooks
=> FIX:  KIT reference channels

mne/io/kit/kit.py, mne/io/kit/tests/test_kit.py
Small fix for the KIT reader. If stim was not coerced to an array that lead to problems later on.
=> [MRG] FIX RawKIT:  stim=list with stim_code='channel'

mne/viz/evoked.py
``plot_white`` used to warn about missing EEG reference even though it was there. This happened because the projs list was emptied, and under the hood ``plot_white`` calls ``prepare_noise_cov``, which throws the warning.
Also some cleaning.
=> Small fixes to plot_white.

doc/whats_new.rst, mne/event.py, mne/realtime/epochs.py, mne/realtime/tests/test_mockclient.py
Taking over https://github.com/mne-tools/mne-python/pull/3696
Closes https://github.com/mne-tools/mne-python/pull/3696 and https://github.com/mne-tools/mne-python/issues/3695
cc @odingod and @LauriParkkonen. Let me know if this works for you guys. Tests pass on my box.
=> MRG Handle triggers split between buffers

mne/channels/channels.py, mne/io/reference.py
I often use `progressbar.ProgressBar` to track progress in long-running analysis script. However, `set_eeg_reference` is verbose (without verbose argument) - which breaks the progressbar into separate lines ( 😞 ). I think there should be a verbose argument in these functions.
TODO:
=> ENH: verbose arg in set_eeg_reference

mne/epochs.py
Adds warnings and readable errors to clarify how to use epochs.average() in the case of epochs object generated from `ica.get_sources`
as discussed in issue #3647 
@jona-sassenhagen @agramfort
=> ENH: Update docstrings in epochs.average() to clarify function with ICA channels

.travis.yml
With the latest `PySurfer` release we shouldn't need to install IPython anymore. If this works I'll merge.
=> FIX: Remove IPython

doc/whats_new.rst, mne/viz/_3d.py, mne/viz/__init__.py, mne/viz/tests/test_3d.py, tutorials/plot_ecog.py
Hey all - this a quick extension of @Eric89GXL's recent ecog plotting tutorial. We had discussed including a few functions in the example to show how you could create a snapshot of the current view for ecog plotting. In this PR, I'm adding these functions to the `_viz3d` module and added a `snapshot_montage` function for doing this automatically (and extended the example to show it).
I can delete those functions and just put the code in the example if people would prefer, but wanted to give an idea of what the code would look like if we just added the functionality. LMK what folks think.
=> adding 3d to 2d snapshot for ecog plotting

doc/whats_new.rst, mne/io/proj.py, mne/io/reference.py, mne/io/tests/test_reference.py
There was a check in place that explicitly disallows moving from a custom reference to an average reference. Upon consideration, I cannot think of any reason why this should be disallowed. When cleaning EEG data (marking bad channels, etc.) it is quite common to first use a custom reference and when the data is clean, move to an average reference.
This PR removes the check and allows re-referencing to an average reference.
=> [MRG+1]: Allow re-referencing to average reference

examples/visualization/plot_channel_epochs_image.py, mne/viz/epochs.py
A labmate of mine was trying to use the epochs image plotting and found this bug when trying to overlay times on an image plot:
I looked into the code and I'm pretty sure it's because there is some non-OOP matplotlib code in the `plot_epochs_image` function that is causing the line plot to show on the wrong axis. This just tries to make that fix and on my computer it fixes the problem.
I also added one line to the example so that this functionality is shown, in the hope that if something breaks in the future it will be easier to catch (since it seems that testing for matplotlib plots is tricky). LMK if people want it done differently. Here's the new output plot:
Note: I could do something like `epochs.times[np.argmax(data, axis=1)` to choose times according to the maximal amplitude of …
=> fixing epochs image bug

examples/time_frequency/plot_time_frequency_simulated.py, mne/channels/channels.py, mne/decoding/tests/test_time_gen.py, mne/io/pick.py, mne/tests/test_source_estimate.py, mne/time_frequency/tfr.py, mne/utils.py, setup.cfg, tutorials/plot_dipole_fit.py, tutorials/plot_python_intro.py, tutorials/plot_stats_spatio_temporal_cluster_sensors.py
I think there is something wrong with how sklearn handles deprecations. I couldn't find a better way to make it work on every platform.
EDIT: In the end, I think my setup was somehow wrong. Now it is cleaner than in the beginning.
=> Fix to sklearn imports.

doc/whats_new.rst, mne/io/eeglab/eeglab.py, mne/io/eeglab/tests/test_eeglab.py
fixes #3786
currently I'm setting this manually - this may be not be the best way to do this, but passing `preload_at_end` to _BaseEpochs constructor does not work in this case - the data are already preloaded and passed to the constructor while `preload_at_end` asserts that `_data` is None.
Let me know if there is better way to do this - but it seems to work well currently.
=> FIX: set _bad_dropped to True after constructing epochs data from eeglab file

doc/whats_new.rst, mne/time_frequency/tests/test_tfr.py, mne/time_frequency/tfr.py
Closes https://github.com/mne-tools/mne-python/issues/3799
Maybe this should be backported.
=> [MRG] Fix to tfr colorbar.

doc/whats_new.rst, mne/channels/channels.py, mne/channels/montage.py, mne/channels/tests/test_montage.py, mne/io/meas_info.py, mne/io/tests/test_meas_info.py, mne/io/write.py, mne/transforms.py, mne/viz/montage.py
Some minor fixes and refactoring of `Montage`/`DigMontage`, their associated reading functions, and docs.
Functionally a change is to allow reading of `.mat` output files from Polhemus FastTrak systems. Bugfix is that if `dev_head_t=False` in `read_dig_montage`, then `inst.set_montage(montage)` will *not* set the `inst.info['dev_head_t']`. In `master` it sets it to identity, which is probably not what we want.
Sound okay @teonbrooks?
=> MRG: Fixes for montage

doc/whats_new.rst, mne/viz/evoked.py, mne/viz/tests/test_topomap.py, mne/viz/topomap.py
Closes https://github.com/mne-tools/mne-python/issues/3795
The colorbars are so small by default, that I had to make the tick labels a bit smaller.
=> [MRG+1] Contour levels to colorbar.

doc/whats_new.rst, mne/io/ctf/ctf.py
=> Pass first samples of individual files when reading multi-file CTF data.

mne/viz/decoding.py
I was looking through the code for `plot_gat_matrix` and I saw this inconsistency in naming. Feel free to ignore this PR if you consider it too nitpicky ;)
=> Fix names for train/test arrays in plot_gat_matrix

doc/whats_new.rst, mne/bem.py, mne/cov.py, mne/dipole.py, mne/epochs.py, mne/forward/_compute_forward.py, mne/io/artemis123/artemis123.py, mne/io/base.py, mne/io/pick.py, mne/io/tests/test_pick.py, mne/minimum_norm/inverse.py, mne/preprocessing/eog.py, mne/preprocessing/ica.py, mne/preprocessing/maxwell.py, mne/preprocessing/stim.py, mne/preprocessing/tests/test_maxwell.py, mne/simulation/raw.py, mne/stats/cluster_level.py, mne/tests/test_cov.py, mne/utils.py, mne/viz/evoked.py
A few fixes in this one:
1. Fixed improper use of `pick_channels` in `maxwell_filter`. It doesn't respect the order of `include` so order must be determined separately.
2. Added a few notes where `pick_channels` behavior could (silently) cause us problems, but hopefully not.
3. Unified plurality in strings with new helper `_pl`.
4. Fixed improper `info['chs][n]['cal'] = 0.` in Artemis123.
5. Fixed `fix_stim_artifact` interpolating all channels instead of just the data channels.
=> MRG: Minor fixes to picking

mne/fixes.py, mne/time_frequency/psd.py
Breaking up #3820 into smaller steps.  
a better way than #3822 -almost too simple ;)
This makes `psd_welch` use scipy's `spectral` instead of `welch`. `spectral` is used with the defaults used in welch here, but the windows are not averaged over - allowing for further steps outlined in #3820
I also removed `_compute_psd` because it was not used anywhere.
=> [MRG+1] spectrogram instead of welch

mne/gui/_coreg_gui.py, mne/gui/tests/test_coreg_gui.py
This provides a better error message in cases like #3844
```
$ mne coreg -s Donald
File "/Users/christian/Code/mne-python/mne/commands/mne_coreg.py", line 49, in <module>
run()
File "/Users/christian/Code/mne-python/mne/commands/mne_coreg.py", line 43, in run
guess_mri_subject=options.guess_mri_subject)
File "/Users/christian/Code/mne-python/mne/gui/__init__.py", line 70, in coregistration
gui = CoregFrame(inst, subject, subjects_dir, guess_mri_subject)
File "/Users/christian/Code/mne-python/mne/gui/_coreg_gui.py", line 1264, in __init__
raise ValueError(msg)
ValueError: Donald is not a valid subject. No subjects were found in 
subjects_dir=/Applications/freesurfer/subjects. Make sure all MRI subjects have 
head shape files (run $ mne …
```
=> [MRG] DOC coreg-GUI:  error message for invalid subject

mne/io/proj.py, mne/tests/test_proj.py
This makes it so that we don't get warnings about subselected channels from EEG average ref proj (they work fine) like:
```
Projection vector "Average EEG reference" has magnitude 0.12 (should be unity), applying projector with 53/60 of the original channels available may be dangerous, consider recomputing and adding projection vectors for channels that are eventually used. If this is intentional, consider using info.normalize_proj()
```
=> MRG: Only warn for non-eeg-avg proj

mne/epochs.py, mne/tests/test_epochs.py
Fix the check for overlapping events. They are only a problem if offending events are actually selected by `event_id`.
=> MRG: Fix epoch check

mne/channels/tests/test_montage.py, mne/io/meas_info.py
Sometimes the files can be written out with more columns than just X,Y,Z, this makes it possible to read them (with a warning).
=> MRG: Fix ELP reading

mne/decoding/search_light.py, mne/decoding/tests/test_search_light.py
Fixes error when scoring='roc_auc' and y is not in [0, 1]:
Should be ultimately solved in scikit-learn/scikit-learn#6874
Replaces #3717, Closes #3697
=> MRG: roc_auc when y not in [0, 1]

doc/whats_new.rst, mne/decoding/tests/test_time_gen.py, mne/decoding/time_gen.py
I hadn't realized that some sklearn cv were not partitions, i.e. a given test sample may be predicted by different folds. 
IIUC, this is not supported by sklearn cross_val_predict. e.g. `cross_val_predict(clf, X, y, cv=ShuffleSplit()`
The previous behavior of mne.decoding.gat was to store the last prediction of each test (i.e. it just overwrite each prediction. Here we raise an explicit error if the user wants a cross-validation with a non partition cv.
Once again, we see the limit of internally handling the CV... 
@teonbrooks you're not going to be happy. 
closes https://github.com/mne-tools/mne-python/issues/3624
=> MRG: non partition cv in gat/decoding

doc/whats_new.rst, mne/viz/topo.py
Should fix #3871. I went through all mne-python's own related callback functions and seems they can all handle both axes object or pyplot coming.
=> MRG+1: Fix _plot_topo_onpick (#3871)

mne/cov.py, mne/io/pick.py, mne/tests/test_cov.py
This is some private function refactoring that cleans up our code a bit in case we need to use `scalings` other places. For example it is necessary for https://github.com/mne-tools/mne-sandbox/pull/25.
=> MRG: Generalize cov and pick functions

doc/whats_new.rst, mne/channels/montage.py, mne/channels/tests/test_montage.py
When a montage defines a position for electrode FP1 and the channel name in the data is Fp1, that should be good enough. This crops up from time to time when defaulting back on the `standard_1005` montage.
=> [MRG+1] Match channels in case insensitive manner when applying montage

doc/whats_new.rst, mne/io/eeglab/eeglab.py
See https://github.com/mne-tools/mne-python/issues/2672#issuecomment-273058747
I've never really used the EEGLAB files so I'm not sure if the fix is the right one. I simply cast the int to a string. @jona-sassenhagen @jasmainak
=> [MRG +1] Allow int eventtype in eeglab epoch reader.

doc/whats_new.rst, mne/label.py, mne/tests/test_label.py
Change to test whether all values in a label are non-zero.  If they are, set them instead to ones.  This should allow label.center-of-mass to return the centroid for structural labels like those read from read_labels_from_annot.  Should also allow simulate_sparse_stc to work as expected with these labels when location='center' (rather than the default 'random').
=> MRG+1: Change label COM for issue #3906

doc/whats_new.rst, mne/time_frequency/tfr.py, mne/viz/tests/test_topo.py, mne/viz/topo.py, tutorials/plot_sensors_time_frequency.py
fixes #3847
This is not finished API-wise. The way it works currently is that there is an `imtype` arg (temporary name - any ideas?) that allows `'normal'` or `'nonuniform'` and thus changes the plotting artist to be NonUniformImage.
I make it dependent on a kwarg because:
* NonUniformImage is a little less flexible - does have only two interpolation options for example ('none' and 'bilinear')
* I did not check it but it may be slower
* having a kwarg opens the door to adding `'logy'` option (next PR maybe - if you think that would be useful, see the last image)
A quick example:
* I used following `freqs`:
* The first image is with `imtype='normal'` and therefore has incorrect y axis tick labels (alpha desync is in 10 Hz), the second one is with `imtype='nonuniform'` and has correct y …
=> MRG+1: nonuniform image option in tfr plot

mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py
Closes https://github.com/mne-tools/mne-python/issues/3883
I couldn't find a reason we make a copy of the instance and drop a part of the channels as it seems to be handled elsewhere. This required the data to be preloaded. There's also check for this [here](https://github.com/mne-tools/mne-python/blob/master/mne/preprocessing/ica.py#L611).
Hopefully the tests will catch it if something broke.
=> [MRG+1] Remove copy from find_bads_exg.

doc/whats_new.rst, mne/io/cnt/cnt.py
.cnt files used by NeuroScan systems support different ways of encoding events (perhaps these reflect old and new versions of the file format). MNE currently only supports types 1 and 2. This PR adds supports for the newer type 3 events.
Closes #3882
=> [MRG] Add support for event_type=3 when reading CNT data

mne/decoding/search_light.py, mne/decoding/tests/test_search_light.py
Fix serious error introduced in #3502 when n_jobs > 1
(otherwise the X is split in weird ways, and the scores get completely weird)
SearchLight is still private, and not used by TimeDecoding, so no consequence.
=> MRG: search light n_jobs wrong split

mne/commands/mne_coreg.py, mne/gui/__init__.py, mne/gui/_coreg_gui.py, mne/gui/_file_traits.py, mne/gui/_viewer.py, mne/gui/tests/test_coreg_gui.py, mne/surface.py
This PR:
1. Adds `verbose` option to the Coreg GUI.
2. Sets surface normals for the head surface for better rendering.
3. Turns on backface culling, which fixes a problem where rotating the head 180 degrees with alpha <1 previously made the head look very strange.
4. Renames scaling params to None/Uniform/3-axis since it's a bit more descriptive.
5. Reorders loading of parameters in `CoregGUI.__init__` to avoid a bug where `mne coreg -s whomever -f inst.fif` wouldn't use `whomever` but rather the name guessed by `inst.fif`. Although you could pass `--no-guess-mri` to work around this bug, this shouldn't be necessary (if MRI is specified, it should be used)
6. Reformats some of the `Property` calls to make it easier to visually track dependencies (should help refactoring)
7. (edit) …
=> MRG: Minor enhancements to coreg

mne/viz/tests/test_raw.py, mne/viz/utils.py
Noticed that the drawn annotations don't align right when ``orig_time`` is not None. The fix gets quite involved, so I don't think I can get it working for 0.14.
=> [MRG] Disable interactive annotations when orig_time is not None.

mne/gui/_coreg_gui.py, mne/gui/_viewer.py
@Eric89GXL this fixes the MRI scaling problem with Mayavi 4.5 mentioned in https://github.com/mne-tools/mne-python/issues/3934 for me. I now get a long list of errors like the one below, but they don't seem to have a negative impact:
```
ERROR: In /Users/ilan/minonda/conda-bld/work/VTK-6.3.0/Common/ExecutionModel/vtkExecutive.cxx, line 784
vtkCompositeDataPipeline (0x7fb020cc48e0): Algorithm vtkAssignAttribute(0x7fb020cc2d60) returned failure for request: vtkInformation (0x7fb020cc2ee0)
Debug: Off
Modified Time: 1184422
Reference Count: 1
Registered Events: (none)
Request: REQUEST_DATA_OBJECT
ALGORITHM_AFTER_FORWARD: 1
FORWARD_DIRECTION: 0
```
=> FIX Coreg GUI scaling error

mne/gui/__init__.py, mne/gui/_coreg_gui.py, mne/gui/_fiducials_gui.py, mne/gui/_file_traits.py, mne/utils.py
This PR aims to make coreg use space a little bit more efficiently. IMO for things like R/A/S if people don't know them, we can provide usable tooltips (but that might not even be necessary).
Builds on #3935, so WIP until that gets merged.
Doing:
```
mne coreg -s fsaverage -f ~/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw.fif --verbose --head-opacity=0.5 --low-res-head
```
On `master` (but really #3935 to expose necessary command-line options):
This PR:
@christianbrodbeck see if you like the changes.
=> MRG: Improve coreg visual space

mne/event.py, mne/gui/_kit2fiff_gui.py, mne/io/fiff/tests/test_raw_fiff.py, mne/minimum_norm/tests/test_inverse.py, mne/viz/utils.py
FYI when using this pattern:
```
try:
...
except Exception as exp:
...
raise exp
```
it gives a better traceback just to do at the end:
```
raise
```
because then the proper/full traceback is given, instead of a traceback pointing only to the `raise exp` line (i.e., better than what we see in https://github.com/mne-tools/mne-python/issues/3945).
I already pushed https://github.com/mne-tools/mne-python/commit/f1fb89636a7086f2ecbe32e5da58b509cc770605 directly to master without realizing there were other occurrences in our code.
=> MRG+1: Fix re-raising of errors

doc/whats_new.rst, mne/io/proj.py, mne/tests/test_proj.py
Up until now I've been doing `raw.add_proj([], remove_existing=True)`, which is silly. Now we can do `raw.del_proj()`.
=> MRG: Allow del_proj to delete all projs

.gitignore, mne/preprocessing/maxwell.py
I found an old relic `_read_fine_cal` that isn't used anymore (it has been moved to `_fine_cal.py`).
=> MRG: Remove cruft

setup.py
@agramfort any reason why we use `numpy`'s `setup` instead of the one from `setuptools`? It removes a `conda` build requirement if we don't need to `import numpy`.
=> ENH: Just use setuptools

doc/whats_new.rst, mne/filter.py, mne/simulation/raw.py, mne/simulation/tests/test_raw.py, mne/tests/test_filter.py
There was a little bug in the raw data simulation that made it so that even for `interp!='zero'`, it was doing zero-order hold interpolation. This fixes that issue, while refactoring the code to do generic point-to-point data interpolation. This led to some nice simplifications of `simulate_raw`.
=> MRG: Fix raw data simulation

mne/forward/_field_interpolation.py, mne/forward/_lead_dots.py, mne/forward/tests/test_field_interpolation.py, mne/forward/tests/test_make_forward.py
We had implemented nearest-neighbor and linear interpolation ourselves in the field interpolation code. This uses the more-standard `scipy.interpolate.interp1d` instead. In theory we could get some speedups, but testing shows it to be about the same. In any case, should help keep things more maintainable.
=> MRG: Refactor field mapping LUT to use interp1d

doc/whats_new.rst, mne/epochs.py, mne/tests/test_epochs.py
Fixes #3992
I'll add a note to whats new once CI's are green.
=> FIX: concatenate_epochs now checks for event_id correspondence

examples/visualization/plot_meg_sensors.py, mne/commands/mne_coreg.py, mne/coreg.py, mne/defaults.py, mne/gui/__init__.py, mne/gui/_coreg_gui.py, mne/gui/_fiducials_gui.py, mne/gui/_file_traits.py, mne/gui/_kit2fiff_gui.py, mne/gui/_marker_gui.py, mne/gui/_viewer.py, mne/gui/tests/test_file_traits.py, mne/surface.py, mne/utils.py, mne/viz/_3d.py, tutorials/plot_visualize_evoked.py
This PR:
1. Moves toward unified treatment of colors and sizes between `coreg` and `mne.viz.plot_trans` by using our standard `mne.defaults.DEFAULTS`.
2. Enables plotting of EEG electrodes in `mne coreg` (first step toward #3700)
3. Refactors not to use Traits `Color` since it's actually not as easy as just using `Tuple` to store a color.
4. Modifies `plot_trans` to use cylinders for EEG sensors and source space dipoles, since both have an orientation.
5. Adds "Terrain"-style interactivity. I'm not sure how / if we can add this as a command-line option.
6. Enables `Load Trans` even when MRI fiducials are not present. For some reason this does not actually transform the points, though (?). We'll want to fix that -- you shouldn't be required to have MRI fiducials to use a trans, or even to …
=> MRG +1: Add EEG electrodes to coreg

doc/whats_new.rst, mne/datasets/utils.py, mne/io/bti/__init__.py, mne/io/bti/bti.py, mne/io/bti/read.py, mne/io/bti/tests/test_bti.py
@dengemann this touches some of your code from 2013 (!) that apparently has a bug. I guess these lines weren't covered or ever used before this :(
I am trying to read some BTi data, I think from MAGNES2500. I hit this bug where `d` was used instead of `n`, but after fixing it I hit a bug when it tries to read the next "block", so I suspect there is something wrong with these 2500-specific lines.
Do you have some MAGNES2500 data that you were using to test/develop originally? What did you use to figure out these lines?
Closes #2170.
=> MRG: Fix BTi reading for Magnes2500

doc/python_reference.rst, doc/whats_new.rst, examples/decoding/decoding_rsa.py, examples/decoding/plot_decoding_csp_eeg.py, examples/decoding/plot_decoding_csp_space.py, examples/decoding/plot_decoding_time_generalization_conditions.py, examples/decoding/plot_decoding_xdawn_eeg.py, examples/decoding/plot_ems_filtering.py, examples/decoding/plot_linear_model_patterns.py, mne/decoding/__init__.py, mne/decoding/base.py, mne/decoding/tests/test_base.py
After a couple of iterations, I believe the best way to deal with the extraction and plotting of spatial filters and spatial patterns is to i) ensure that we use the LinearModel class at the end of our pipeline and ii) use a function that can extract and inverse transform these coefficients.
This API allows a full sklearn compatibility, and avoid adding additional complex attributes to `SearchLight` and `GeneralizationLight` (filters_, inverse_filters, inverse_patterns etc)
```python
clf = make_pipeline(Vectorizer(), StandardScaler(), LinearModel(LogisticRegression()))
clf.fit(X, y)
coef = get_coef(clf, 'filters_', inverse_transform=True)
evoked = EvokedArray(coef, epochs.info, tmin=epochs.tmin)
```
Features:
@trachelr @agramfort @teonbrooks @jona-sassenhagen @choldgraf 
- closes #3424
- …
=> MRG+1: get patterns coefs with example

mne/coreg.py, mne/gui/__init__.py, mne/gui/_coreg_gui.py, mne/gui/_fiducials_gui.py, mne/gui/tests/test_coreg_gui.py, mne/utils.py
This adds the option to skip labels and include *.annot files when scaling a brain. Also includes a small layout fix (marked on the screenshot). I wonder whether *.annot files could be linked rather than copied to be more efficient (but there are other files that we just copy during scaling so for now this is more consistent and might be safer)
CC @Eric89GXL
=> MRG+1: Coreg-GUI: option to skip label

mne/annotations.py, mne/datasets/utils.py, mne/io/fiff/raw.py, mne/io/fiff/tests/test_raw_fiff.py
@bmaess pointed out that Neuromag allows starting and stopping recordings within a single file, e.g.:
It's nice that we already have these skips in place. Ideally we could do things like `raw.filter(...)` and have it know to treat these separately, but for now let's leave that for a future enhancement.
@agramfort mentioned as a first-order fix we could add these sections to `raw.annotations`. I've implemented that, with `BAD` in the name. This way, if we make further enhancements like `raw.filter` or other functions being annotation-aware, we get these enhancements for free. In the meantime then @bmaess can begrudgingly iterate over the good sections as necessary to get sections filtered :)
It looks like this:
Sound reasonable? If so @jaeilepp can you have a look? I'm probably not doing …
=> ENH: Deal with acquisition skips

examples/preprocessing/plot_rereference_eeg.py, mne/io/reference.py, mne/io/tests/test_reference.py
To make (re-)referencing of the EEG a bit more intuitive, this PR changes the following:
- Moving from an average to a custom reference completely removes the average reference projection from the `info['projs']` list. A message is printed when this happens.
- When setting an average reference on data that has been preloaded, the projection is automatically applied.
- The referencing example has been updated to re-reference the same data, instead of making copies of the original un-referenced data. This emphasizes that it is possible to freely move from one referencing  scheme to another.
Fixes #3998 #3981
=> [MRG+2] Make EEG (re-)referencing more intuitive

doc/python_reference.rst, doc/whats_new.rst, mne/decoding/time_frequency.py, mne/decoding/transformer.py, mne/minimum_norm/tests/test_time_frequency.py, mne/time_frequency/__init__.py, mne/time_frequency/_stockwell.py, mne/time_frequency/multitaper.py, mne/time_frequency/psd.py, mne/time_frequency/tests/test_psd.py, mne/time_frequency/tests/test_tfr.py, mne/time_frequency/tfr.py
Partial fix to https://github.com/mne-tools/mne-python/issues/3668
To avoid naming conflicts, I added `array` to the new public function names. So the new public functions are ``psd_array_multitaper`` and ``psd_array_welch``. LMK if there are others that need to be made public.
I'm not entirely sure where the overlap in ``tfr`` and ``multitapers`` is. Maybe there is some overlap in creating the tapers, but changing it seems dangerous. I'll let someone else take a stab at it.
=> [MRG+1] Make time-freq functions on arrays public.

mne/tests/test_utils.py
This is failing for some reason on py3 builds. It's just calling ``sys.getsizeof``.
=> Fix object_size test.

doc/whats_new.rst, mne/io/array/tests/test_array.py, mne/time_frequency/psd.py, mne/time_frequency/tests/test_psd.py
Fixes #3621 
by adding `padding` kwarg to `psd_welch`.
I'll add an entry to whats_new once comments are resolved and CIs green.
=> [MRG+2] ENH: padding kwarg for psd_welch

mne/gui/_kit2fiff_gui.py, mne/gui/_marker_gui.py
When multiple wildcards are separated by `;` on Windows no files show at all. Making them separate lists items is not ideal but I don't know how multiple wildcards can be combined in one filter...
=> [MRG] FIX kit2fiff-gui wildcards on Windows

mne/coreg.py, mne/tests/test_coreg.py, mne/transforms.py
@jona-sassenhagen the function is `mne.coreg.coregister_fiducials`. It currently has a scale parameter to use it with fsaverage, but this does not lead to satisfactory results and should be removed before merge.
The PR also contains some other small modifications. 
- Allow `viz.plot_trans` to plot fiducials
- Allow scaling MRI without label files
=> [MRG] Coregistration

mne/channels/channels.py, mne/channels/interpolation.py, mne/evoked.py, mne/filter.py, mne/io/proj.py, mne/io/reference.py, mne/io/tests/test_reference.py, mne/preprocessing/stim.py, mne/stats/regression.py, mne/time_frequency/psd.py, mne/time_frequency/tfr.py, mne/utils.py
Some simplifications from adding `evoked.preload = True` and wrapping `evoked._data` to `evoked.data`, same for `AverageTFR` and `EpochsTFR`.
There are probably other examples in the code, but this at least gets the ball rolling.
=> MRG+1: MAINT: Unify treatement of _data

mne/bem.py, mne/coreg.py, mne/source_space.py, mne/surface.py
The original purpose was to fix a `surf['nn']` normalization in `mne/coreg.py`, but then I added some unification of norm calculations. Some of the `linalg.norm` calls (which is the same speed as `np.sqrt(np.sum(...))` for large-ish arrays) should save memory allocations, as should the `np.einsum` calls.
=> MRG: Unify some norms and math

Makefile, mne/bem.py, mne/channels/channels.py, mne/connectivity/spectral.py, mne/coreg.py, mne/forward/forward.py, mne/gui/_coreg_gui.py, mne/inverse_sparse/mxne_inverse.py, mne/preprocessing/ica.py, mne/preprocessing/maxwell.py, mne/stats/permutations.py, mne/tests/test_docstring_parameters.py, mne/time_frequency/multitaper.py, mne/utils.py, mne/viz/epochs.py, mne/viz/utils.py, setup.cfg
We have some failures on `master` because `pydocstyle` became more stringent. This fixes them.
WIP because `pydocstyle` also now supports the `numpy` standard, so I want to see how difficult it will be to implement those fixes.
=> MRG: Fixes for docstyle

doc/whats_new.rst, mne/io/ctf/info.py, mne/io/ctf/tests/test_ctf.py
Closes https://github.com/mne-tools/mne-python/issues/3921.
Since the constants are assigned differently in CTF, the problem was that the ids were not converted to FIFF constants. See if you agree with me.
=> [MRG+1] Fix to CTF reader cardinals.

examples/decoding/plot_decoding_spatio_temporal_source.py, examples/time_frequency/plot_source_space_time_frequency.py, mne/surface.py
Was getting a floating point indexing error. Hold off merging for a sec - it seems like there are a few other errors along these lines in the codebase. LMK if just wrapping stuff in `int(` is an OK solution. The problem is that since Python 3 returns a float if you do, e.g., `10 / 2`, then if you use this as an index it errors.
=> doc: fixing python 3 bug in decoding example

mne/io/pick.py, mne/viz/evoked.py
Fixes #3963 
to allow use 'misc' channels in plot_compare_evokeds. I replace _DATA_CH_TYPES_SPLIT (defined as ['mag', 'grad', 'eeg', 'seeg', 'ecog', 'hbo', 'hbr'] [see here](https://github.com/mne-tools/mne-python/blob/master/mne/io/pick.py#L715)) with the same valid types defined in [_plot_evoked](https://github.com/mne-tools/mne-python/blob/master/mne/viz/evoked.py#L200).
=> MRG: Fix plot_compare_evokeds to support 'misc' channel type

Makefile
Codespell used `.py` for a while but shouldn't need it now. This should fix it.
=> FIX: Fix codespell executable

mne/commands/mne_kit2fiff.py, mne/gui/_kit2fiff_gui.py, mne/gui/_marker_gui.py
Turns out Ubuntu has the same problem with wildcards as Windows (cf. https://github.com/mne-tools/mne-python/pull/4013)
CC @ellenlau
=> [MRG+1] FIX kit2fiff GIU for Ubuntu

doc/whats_new.rst, mne/io/base.py, mne/io/fiff/tests/test_raw_fiff.py, mne/io/tests/test_raw.py, mne/tests/test_annotations.py
With this the boundaries of raw objects get annotated as 'BAD boundary' when ``concatenate_raw`` gets called. I wonder if this should be always done or if there should be a param.
=> [MRG+1] Boundary annotations.

mne/channels/channels.py, mne/io/reference.py
I noticed that the method version of ``set_eeg_reference`` was outdated. Similar name with the function prevents using ``copy_function_doc_to_method_doc`` decorator.
=> [MRG] Fix to eeg_reference docs.

doc/whats_new.rst, mne/channels/montage.py, mne/channels/tests/test_montage.py
I realized that a recent pull request I made to add in functionality for reading in EGI digitization files did not appropriately scale the digitization coordinate units. This merge would fix that scaling issue. I am really sorry for the oversight on my part and that this wasn't fixed before the 0.14 release.
=> MRG+1: Fix scaling for EGI digitization coordinates

mne/viz/evoked.py
plot_compare_evokeds somehow sets the background to transparent. I don't know why I originally did this, but I don't see a benefit right now and we got a complaint (because it doesn't play well with dark backgrounds). This removes the offending line.
@kambysese
closes #4091
=> BUG/MINOR: remove transparent background for plot_compare_evoked

mne/source_estimate.py
I'm having a weird use case for which I need to load in 2413 source estimate objects. While waiting for it to load, I looked at the source code and found a simple way to make the loading roughly twice as fast. Reading an stc is probably almost never a bottleneck, but hey, it's a small change *shrug*.
Seeking to the end of the file can be a costly operation on some file systems, especially when reading from a network mount. Since all bytes of the file are read during this function anyway, it makes more sense to
just read everything into a buffer instead of doing file seeks.
=> [MRG] Optimize read_source_estimate function

mne/viz/evoked.py
plot_compare_evoked currently fails when the input keys are not str: 1. the keys' .split method is called, 2. they are sorted. I fear this is unavoidable and here it simply raises an error if the keys are not str.
(Keys are of a format similar to epochs event_id with "/" tags.)
=> MINOR/FIX plot_comp_ev keys must be str

examples/time_frequency/plot_time_frequency_global_field_power.py
This is using some old school methods in new school ways to explore spectral temporal evolution.
The (latest) output looks like this:
cc @Eric89GXL @agramfort @jona-sassenhagen
=> [MRG] VIZ/DOC/ENH: add time frequency gfp example

examples/decoding/README.txt, examples/io/plot_read_epochs.py, tutorials/plot_receptive_field.py
This fixes a section header that I missed in the last PR. Also it looks like the docs didn't build the new tutorial HTML. I'm not sure why but it sounds like maybe it's because of the circle cache? Maybe @Eric89GXL has an idea for that one?
=> [MRG] renaming section header and updating link

mne/cov.py, mne/tests/test_chpi.py
I was getting warnings about an avg eeg ref proj during `mne.chpi.filter_chpi`, which only operates on MEG channels. This fixes our `cov` code so that it only warns about EEG ref when EEG channels are picked.
=> MRG: Dont warn about EEG avg proj during filter_chpi

doc/whats_new.rst, mne/connectivity/tests/test_spectral.py, mne/decoding/transformer.py, mne/filter.py, mne/io/array/tests/test_array.py, mne/io/base.py, mne/io/fiff/tests/test_raw_fiff.py, mne/io/pick.py, mne/preprocessing/ecg.py, mne/preprocessing/eog.py, mne/preprocessing/ica.py, mne/preprocessing/ssp.py, mne/preprocessing/tests/test_eeglab_infomax.py, mne/preprocessing/tests/test_ica.py, mne/preprocessing/tests/test_ssp.py, mne/tests/test_filter.py, tutorials/plot_background_filtering.py, tutorials/plot_brainstorm_auditory.py, tutorials/plot_ica_from_raw.py
Closes #4045.
~~WIP because it needs to:~~
This also fixes a bug where `ref_meg` channels were not being filtered by default in `raw.filter`.
=> MRG: Better filtering

doc/whats_new.rst, mne/epochs.py, mne/tests/test_epochs.py
In concatenate_epochs, relative position of events are not conserved and replaced with arbitrary position (`events[:, 0] = np.arange(len(events)))`).
This will lead to problems when we apply operations relying on event position (e.g. Xdawn).
This PR fix this problem by maintaining relative position of events and adding an offset, arbitrarily set to to the position of the last event + tmax + 10s.
=> [MRG+2] keep relative position of events in concatenate_epochs

doc/whats_new.rst, mne/preprocessing/eog.py, mne/preprocessing/tests/test_eog.py
Closes https://github.com/mne-tools/mne-python/issues/4165
I first tried setting the bad segments to zeros, but the edges along with the filtering caused false positives to every edge of an annotation.
This simply concatenates the good data, finds the blinks from that and maps the sample numbers to the original. See if this is not too hacky for you.
It only finds one false positive with the gist in https://github.com/mne-tools/mne-python/issues/4165. That's because the drift isn't entirely covered with an annotation. Should I add a param for using this or should it be always on?
=> [MRG] Remove annotated segments in find_eog_events.

doc/whats_new.rst, examples/io/plot_objects_from_arrays.py, mne/io/base.py, mne/io/fiff/raw.py, mne/io/tests/test_raw.py
Closes https://github.com/mne-tools/mne-python/issues/4164
Now the writer checks if the annotations are empty and doesn't try to write it in that case. It was previously trying to set empty annotations to None, but this is probably more appropriate.
=> [MRG+1] Fix writing of raws with empty annotations.

mne/io/edf/edf.py, mne/io/edf/tests/test_edf.py
Took me a while to debug this. Rejecting channels with edf was failing if n_records is inferred from file size.
=> Fix to edf with reject.

mne/io/egi/egi.py
It fixes the bug introduced by #4079 which prevents reading EGI data when no triggers are present.
=> Fix for EGI RS data

mne/chpi.py, mne/datasets/utils.py, mne/io/artemis123/artemis123.py, mne/io/artemis123/tests/test_artemis123.py, mne/io/artemis123/utils.py, mne/simulation/raw.py, mne/simulation/tests/test_raw.py, mne/tests/test_chpi.py, mne/viz/_3d.py
This is an initial stage to get artemis data into a form that can be used with existing cHPI code. Essentially it provides some methods to do basic HPI fitting without digitization or initialization (coming from the scanner).
Next steps are to generate HPI_results structures to facilitate cHPI in a manner similar to what is being used for elekta data and provide better support for edge cases (multiple HPIs, no digitization, in non canonical ordering etc)
=> MRG+1: HPI support for Artemis123

mne/viz/epochs.py
``__getitem__`` of epochs makes a copy slowing plotting down. This uses the preloaded data if available. The improvement isn't quite as dramatic as I hoped, but should make a difference with big datasets.
=> [MRG+1] Speed up epochs.plot.

doc/python_reference.rst, doc/whats_new.rst, examples/decoding/plot_receptive_field.py, mne/decoding/__init__.py, mne/decoding/receptive_field.py, mne/decoding/tests/test_receptive_field.py, mne/decoding/time_delaying_ridge.py, mne/filter.py, mne/utils.py, tutorials/plot_receptive_field.py
Here you go @agramfort.
In addition to `tutorials/plot_receptive_field.py` and `examples/plot_receptive_field.py`, I've also been using [this gist](https://gist.github.com/Eric89GXL/12724580917210db37ed2ef125156b93).
=> MRG+1: Use frequency domain for xc/ac

doc/python_reference.rst, doc/whats_new.rst, mne/io/__init__.py, mne/io/eeglab/__init__.py, mne/io/eeglab/eeglab.py, mne/io/eeglab/tests/test_eeglab.py
Fix #3938
@timmidee @jasmainak
=> [MRG+1] Make read_eeglab_events public

mne/viz/tests/test_ica.py, mne/viz/tests/test_topo.py, mne/viz/tests/test_topomap.py, mne/viz/topomap.py
Because topomap calls are a major aspect of our tests, this is essentially trying to pass `{"res": 8, "contours": 0, "sensors": False}` to as many topomap calls as possible.
The bad companion to #4224
=> WIP speed up topomap tests

mne/io/proj.py, mne/tests/test_proj.py
Newer style Neuromag projectors can have all 306 channels even if only grad or mag are used in the vector. This fixes the logic for checking if the projector has been depleted by bads or picking.
=> MRG: Fix projector check

doc/whats_new.rst, mne/preprocessing/ica.py
This pull request concerns #4215.
I experienced problems using the ica.apply() method for average referenced EEG data when supplying a noise covariance matrix. The issue seemed to occur in `ica._pick_sources`, specifically the line where the pre-whitening matrix is inverted, i.e., `data = fast_dot(linalg.pinv(self._pre_whitener), data)`. Due to the applied average referencing, the data was rank deficient, however, this was not recognized by (scipy.)linalg.pinv. A suggestion in #4215 was to use a higher cutoff value for singular values when determining effective rank, i.e., explicitly setting the `cond` argument.
On my system, Windows 10 64-bit running python 3.6, the default cutoff is about 2.22e-16. I tested two cases. For my own data, the singular values (as estimated by …
=> Explicit cutoff for rank estimation when inverting ica._pre_whitener

doc/manual/io.rst, mne/datasets/utils.py, mne/io/edf/edf.py, mne/io/edf/tests/test_edf.py, mne/io/edf/tests/test_gdf.py
This is an attempt to allow reading GDF files in mne. The GDF format is described in detail here:
https://arxiv.org/abs/cs/0608052
This file format is currently only supported by the [biosig toolbox](http://biosig.sourceforge.net) (which is used by fieldtrip & Co). There is an active homebrew port of the biosig toolbox (https://github.com/schloegl/homebrew-biosig). This would probably be the cleanest way to ensure long-lasting GDF support in python (especially since the format is still likely to evolve), but I wasn't able to install it on my machine, and it's macOS-only...
Some of the code was taken from @alexandrebarachant's previous attempt (see #2136, and https://github.com/alexandrebarachant/mne-python/tree/gdf) and an apparently discontinued [biosig python …
=> MRG+1: GDF support

examples/visualization/plot_evoked_topomap.py, mne/time_frequency/tfr.py, mne/viz/circle.py, mne/viz/tests/test_misc.py, mne/viz/topo.py, mne/viz/topomap.py, mne/viz/utils.py, tutorials/plot_sensors_time_frequency.py, tutorials/plot_visualize_evoked.py
This is an effort to make our topomap plotting faster interactively and in testing. cc @jona-sassenhagen can you push your changes to the tests?
Still WIP because I need to modify the picking to use `PatchCollection` (which I *think* [should be possible](https://matplotlib.org/users/event_handling.html#object-picking)) instead of iteration over `Circle` objects. @jaeilepp did you ever try this approach?
=> MRG: Faster topomaps

mne/io/reference.py, mne/io/tests/test_reference.py
This PR fixes a small bug in #4218 and proposes to add a `verbose` parameter to `set_bipolar_reference`. Indeed, in `set_bipolar_reference`, `inst.drop_channels(cathode)` raises an error if there is a non-empty intersection between the lists `anode` and `cathode` (we try to drop channels which no longer exist).
=> Fix for `set_bipolar_reference`

doc/whats_new.rst, examples/stats/plot_sensor_permutation_test.py, mne/viz/tests/test_topomap.py, mne/viz/topomap.py
This fixes two problems.
First, the `mask` wasn't working properly for paired gradiometers.
Second, we were doing `raw.info['bads'] += ` when those bads were already present in the evoked file. We have that elsewhere in tutorials so it seems overkill here anyway.
=> MRG: Fix topomap masking

doc/whats_new.rst, mne/label.py, mne/tests/test_label.py
Calling `label.fill()` raised an error if the label was empty, now it works (doesn't do anything other than return).
=> MRG: Fix for empty label fill

doc/whats_new.rst, mne/preprocessing/ica.py
This PR concerns (the first half of) #4264.
I experienced a `PermissionError` when trying to save an ICA object to disk, however, this was not the error causing the write to fail but seemed to be the result of subsequently trying to delete the file (which was being written) before having closed it. Hence, this error was raised before the 'actual' error could be raised (and also prevented manual deletion of the file).
This PR implements a change to close the file before trying to delete it.
=> Closing file before attempting to delete

mne/decoding/base.py, mne/decoding/tests/test_base.py
This allows retrieving the patterns from nested pipelines: e.g.
```python
clf = make_pipeline(
UnsupervisedSpatialFilter(PCA()),  # preprocessing on n_epochs x n_chans x n_times
SlidingEstimator(make_pipeline(
StandardScaler(),   # preprocessing on n_epochs x n_times
Ridge()))
get_coef(clf)
```
(this @kingjr writing... @Eric89GXL  or @jona-sassenhagen, could you review it?)
=> FIX: allows retrieving patterns from nested pipelines with SlidingEstimators

mne/viz/utils.py
The sensor symbols were too large and were plotted partly over the sensor names, so I decreased the symbol size and shifted the names slightly to the right (see images for before/after). It would be good if someone else tested this on a different platform.
Before:
After:
=> Adjust sensor size and sensor name positions

mne/viz/evoked.py
I noticed that the legend was not right when plotting ctf data:
I suggest we change the legend to use absolute locations instead of the layout positions.
=> [MRG] Change legend to use absolute positions.

mne/connectivity/spectral.py
I noticed that joblib hangs if the amount of epochs is divisible with the number of jobs. This results in an empty list of data and makes an infinite while loop in joblib. The sklearn version has a fix for this. 
The fix here also removes silly logging messages like ``computing connectivity for epochs 9..8``.
=> [MRG] Fix connectivity joblib hanging.

doc/whats_new.rst, mne/inverse_sparse/mxne_optim.py, mne/inverse_sparse/tests/test_mxne_optim.py
This PR addresses multiple duality gap related issue:
1) the formula used in `dgap_l21` was wrong. The dual objective computed was a lower bound
on the true value of the dual objective, and the difference goes to zero as the duality
gap tends to 0, which is why it did not cause convergence issues.
2) added a parameter `return_gap` which defaults to False in `mixed_norm_solver`,
to be able to test final values of gap (and tested in the case of bcd)
3) store the highest value of `d_obj` so far in all solvers, because nothing
guarantees that `d_obj` is increasing. Using  `highest_d_obj` provides a
better gap.
4) cosmetics : renamed all dobj and pobj to use snake_case, as both pobj and
p_obj were used.
I need guidance regarding the following points:
a) in  `iterative_mixed_norm_solver`, the …
=> [MRG]: wrong d_obj in inverse_sparse.mxne_optim.dgap_l21

doc/whats_new.rst, mne/channels/montage.py, mne/viz/montage.py, mne/viz/tests/test_montage.py
Fixes #4275. Refactor `mne.channels.montage.Montage.plot` to use `mne.viz.utils.plot_sensors`. This means that the argument `scale_factor` is currently unused since this is not implemented in that method.
=> [MRG] Use mne.viz.utils.plot_sensors in mne.channels.montage.Montage.plot

circle.yml
This should hopefully make it a little bit faster to view the artifacts, and fix the recent `doctest` failure.
=> ENH: Better CircleCI build [circle front]

mne/io/edf/edf.py, mne/io/edf/tests/test_edf.py, mne/io/edf/tests/test_gdf.py
Closes https://github.com/mne-tools/mne-python/issues/4252
The 24bit integer was not read correctly. It was also reading too much data. The documentation is available here https://arxiv.org/pdf/cs/0608052.pdf (page 9).
@robintibor can you check if this fixes your problem?
I'm not sure what the stim channel (STI 014) is recording, but it doesn't seem to be the events. I wonder if it would be best to synthesize the stim channel with the events extracted here.
=> [MRG] Fix to gdf event reading.

mne/io/meas_info.py
I think this was not intentional, when printing the info dict the values always start with a single quote, e.g.
<Info | 16 non-empty fields
bads : 'list | 0 items
buffer_size_sec : 'float | 1.0
ch_names : 'list | Fp1, AF7, AF3, F1, F3, F5, F7, FT7, FC5, ...
chs : 'list | 64 items (EEG: 64)
This PR removes these leading quotes.
=> Avoid printing a leading ' when printing info dict

mne/viz/topomap.py
In `master` using `ch_type='planar1'` or `'planar2'` wasn't working properly. This should fix it.
I don't think there is a test to update, but maybe some `assert` statement inside the code could by a sanity check. I'll look tomorrow hopefully.
=> MRG: Fix planar1/planar2 topomaps

mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py
Redo of #3169 because I'm terrible with Git.
> Currently, if you do something like
> 
> ica.find_bads_ecg(raw, "CUSTOM_ECG_NAME")
> 
> it will internally create ecg_epochs by calling create_ecg_epochs(inst). The problem with this is that if, for some reason, "CUSTOM_ECG_NAME" is not defined properly as the only ECG channel, it will pick the wrong channels, and possibly create bad ecg epochs.
> This PR should in principle be very rare (which is why it's not been discovered so far), but can happen for example with the HCP files.
> 
> This change passes the ch_name to the create_ecg_epochs call.
> 
> Still needs a test.
@dengemann do you agree that with the chance in line 944 because
> we don't return the created sources anyways. And there is no kwarg on the input side.
> ?
=> [MRG+1] ica.find_bads_ecg pass ch_name to create_ecg_epochs

examples/forward/plot_forward_sensitivity_maps.py, tutorials/plot_artifacts_correction_ica.py
I noticed that the ``ica.apply`` is never called in our ICA tutorial. Also includes a couple of fixes to dead links.
=> [MRG+1] Small fixes to ICA tutorial.

examples/decoding/plot_receptive_field.py, mne/decoding/receptive_field.py, mne/decoding/tests/test_receptive_field.py, tutorials/plot_receptive_field.py
This fixes the edge handling when using Ridge, and it also changes the API a bit.
I also put in a little API change up for discussion. The output of `predict` is now `(n_times[, n_epochs], n_outputs)` instead of what's in `master` which is `(n_times * n_epochs[, n_outputs])`. This is really the result of two changes/ideas:
1. If you pass in something with `n_epochs` dimension, you now get something back with an `n_epochs` dimension.
2. You always have the `n_outputs` dimension, even if it's a singleton. In our definition of `fit` we have `y : array, shape (n_times[, n_epochs], n_outputs)`, i.e. the output dimension is always there, so it seems like we should always have it in `predict`, too.
Not sure if this violates some standard `sklearn` terms or not. Maybe we need to add the …
=> FIX: Fix ReceptiveField edge handling

doc/whats_new.rst, mne/io/base.py, mne/tests/test_proj.py, mne/time_frequency/psd.py, mne/time_frequency/tests/test_psd.py, mne/viz/raw.py
This makes `raw.plot_psd()` respect / ignore annotations by default. Ready for review/merge from my end.
cc @wronk 
@mmagnuski you might be interested, too, since you have some PSD-related PR going IIRC.
=> MRG: Raw PSD respects annotations

doc/_templates/layout.html
This fixes our footer image in non-root pages, e.g.:
https://mne-tools.github.io/dev/auto_examples/connectivity/plot_cwt_sensor_connectivity.html#sphx-glr-auto-examples-connectivity-plot-cwt-sensor-connectivity-py
=> MRG: Fix example footer images

mne/io/brainvision/brainvision.py
rf. mailing list.
The problem was that with long channel names the divider is single space and messes the split. It would be nice if someone with more experience with brainvision files would confirm this doesn't break anything.
=> Divider in brainvision files.

mne/io/reference.py, mne/io/tests/test_reference.py
Due to faulty control-flow logic, doing `raw.set_eeg_reference(ref_channels=[])` actually computed a common-average reference. This fixes the control-flow and the botched unit test that was supposed to prevent this from happening.
closes #4352
=> [MRG] Fix referencing when ref_channels=[]

mne/decoding/tests/test_transformer.py, mne/decoding/transformer.py
This is a missing feature when we attempt to interpret the model of the following type of pipeline.
```python
clf = make_pipeline(UnsupervisedSpatialFilter(PCA()), Vectorizer(), LinearModel())
clf.fit(X=epochs.get_data(), y=epochs.events[:, 2])
patterns = get_coef(clf, 'patterns_', inverse_transform=True)
mne.EvokedArray(patterns, epochs.info).plot()
```
=> ENH: add inverse_transform method to UnsupervisedSpatialFilter

mne/viz/utils.py
The x label (where it says "Time (s)") in the raw plot figure was not shown completely. I increased the bottom border to fix this.
Before:
After:
=> [MRG] Increase bottom border in order to show the x label completely

doc/whats_new.rst, mne/io/edf/edf.py
Closes https://github.com/mne-tools/mne-python/issues/4361
This is for a special case where stim channel has higher sfreq to the rest of the channels.
=> [MRG] Don't include stim channel when inferring sfreq.

doc/python_reference.rst, doc/whats_new.rst, mne/channels/__init__.py, mne/channels/channels.py, mne/channels/layout.py, mne/channels/tests/test_channels.py, tutorials/plot_stats_spatio_temporal_cluster_sensors.py
Related to https://github.com/mne-tools/mne-python/issues/4343
The computation for gradiometers is not working yet. I'm not sure what to do with the overlap. Maybe combine them so that for 204 channels it'll return conn matrix of 102X102?
The conn matrix seems to be a bit different to the connectivity [here](https://mne-tools.github.io/dev/auto_tutorials/plot_stats_spatio_temporal_cluster_sensors.html#sphx-glr-auto-tutorials-plot-stats-spatio-temporal-cluster-sensors-py), but the end result is quite identical.
=> [MRG] Compute channel connectivity using Delaunay.

mne/decoding/base.py, mne/decoding/tests/test_base.py
This enhancement allows retrieving multiple co-linear patterns in case `Y` is multidimensional (e.g. left/right audio/visual).
While doing this, I encountered the following issue: FWIU, the Haufe's pattern trick only works when X and Y are z-scored. Consequently, I am not sure whether we should force `LinearModel` to apply such z-scoring inside (and break backward compatibility), or whether we should just warn the user (which creates possibilities of doing it wrong). I originally thought we would be fine with `StandardScaler` prior to the LinearModel, but this won't suffice for ensuring Y is centered over 0 with std of 1.
Overall, I would like to get second pair of eye o the validity of my equations.
=> MRG: Compute patterns for multiple regressors

mne/dipole.py, mne/viz/_3d.py
Some unused params were left after deprecating the mayavi plotter.
=> [MRG] Remove deprecated params from plot_dipole_locations.

mne/commands/utils.py
Fixes #4378.
I've also removed the condition to distinguish between .py and .pyc files - is this needed? I only have .py files in the command folder. If this is not needed, the other condition involving regexes could also be removed.
=> [MRG] Don't use deprecated imp module in Python versions >= 3.3

mne/viz/topomap.py
I think it would be helpful if excluded components (i.e. components that are in `ica.exclude`) were plotted differently in `ica.plot_components`. I've changed the component title to gray to distinguish them from normal ones.
IMO it would also be useful if the user could add components to the excluded list by clicking on their title. What do you think?
=> Plot title of excluded components in gray

mne/beamformer/_lcmv.py, mne/beamformer/tests/test_lcmv.py
Make `tf_lcmv` and `_lcmv_source_power` consistent with the latest changes in `lcmv`:
* `weight_norm` option (only "unit-noise-gain")
* make the passing of the noise covariance matrices and thereby whitening optional
@agramfort and @dengemann
=> adapt tf_lcmv to use weight_norm and optional whitening

tutorials/plot_artifacts_correction_filtering.py
The warning can be confusing because it really only applies in ERP analysis, where higher cutoff frequencies significantly "distort" the signal in the time domain. In other applications, this warning can be confusing, for example ICA preprocessing is usually done with a high-pass filter of 1Hz (or even 2Hz).
=> Make warning about high-pass filters more specific

doc/whats_new.rst, mne/channels/montage.py
The function `mne.viz.plot_montage` uses `kind='topomap'`, but the method `Montage.plot` uses `kind='3d'`. This is inconsistent, so I suggest to set `kind='topomap'` also for the method.
=> Change default 'kind' argument to 'topomap' (like in function)

mne/preprocessing/ica.py, tutorials/plot_artifacts_correction_ica.py
Weird bug in corrmap where the non-template figures got the template title.
I had a weird local error when testing this tutorial, let's see what Travis says.
=> MINOR: fix corrmap fig titles

tutorials/plot_artifacts_correction_filtering.py
As discussed in #4394 with @jona-sassenhagen, I changed the text in order to not imply that HP filtering is problematic _only_  for ERP/ERF analysis.
=> Refine high-pass filter warning in tutorial

doc/whats_new.rst, examples/inverse/plot_gamma_map_inverse.py, examples/inverse/plot_mixed_norm_inverse.py, examples/inverse/plot_time_frequency_mixed_norm_inverse.py, mne/inverse_sparse/__init__.py, mne/inverse_sparse/_gamma_map.py, mne/inverse_sparse/mxne_inverse.py, mne/inverse_sparse/mxne_optim.py, mne/inverse_sparse/tests/test_gamma_map.py, mne/inverse_sparse/tests/test_mxne_inverse.py, mne/viz/misc.py
This PR adds dipole output to our sparse solvers.
Visualization is currently done with `plot_dipole_locations` looping over dipoles or by giving the list of dipoles to `plot_dipole_locations`
=> MRG: use  dipole output for sparse inverse methods

doc/whats_new.rst, examples/datasets/plot_brainstorm_data.py, examples/inverse/plot_compute_mne_inverse_raw_in_label.py, examples/preprocessing/plot_rereference_eeg.py, mne/channels/channels.py, mne/io/reference.py, mne/io/tests/test_reference.py, mne/tests/test_cov.py, mne/tests/test_dipole.py, mne/tests/test_epochs.py, mne/tests/test_proj.py, tutorials/plot_artifacts_correction_rejection.py, tutorials/plot_artifacts_correction_ssp.py, tutorials/plot_compute_covariance.py, tutorials/plot_eeg_erp.py, tutorials/plot_epoching_and_averaging.py, tutorials/plot_epochs_to_data_frame.py, tutorials/plot_object_raw.py, tutorials/plot_visualize_epochs.py, tutorials/plot_visualize_raw.py
Fix #4302 and #3998.
Added new argument `projection=False` to `set_eeg_reference`.
=> [MRG] Add projection argument to set_eeg_reference

doc/whats_new.rst, mne/commands/mne_coreg.py, mne/gui/__init__.py, mne/gui/_coreg_gui.py
Addressing #4411 @agramfort 
~~Start the GUI with `mne coreg --compact`~~
It's not pretty, but it should do the job. 
It only makes the second panel scrollable, but since that is the larger one this should be fine for pretty small screens (height < 800 pixels on macOS); there seems to be a bug in traitsui in that it only allows making `View`s scrollable, not `Group`s, and since the first panel is composed of multiple views it would be more complex to build a single view for it.
=> [WIP] ENH coreg-gui:  compact view

doc/whats_new.rst, mne/channels/montage.py, mne/channels/tests/test_montage.py
This is useful to quickly get the 3D positions stored in `self.pos` converted to 2D (e.g. to create a quick topomap, which requires 2D positions).
=> [MRG] Add get_pos2d method to Montage

mne/beamformer/__init__.py, mne/beamformer/_lcmv.py, mne/beamformer/tests/test_lcmv.py
Creating two separate functions to make and apply the LCMV spatial filter (following the logic of `make_inverse_operator` and `apply_inverse`). 
This enables the application of the weights to separate data, which is needed for example when comparing conditions.
Note: examples etc. not adapted yet.
@agramfort and @dengemann
=> WIP: 2-step API for LCMV: make and apply spatial filter

mne/channels/montage.py
Fixes one issue mentioned in #4403 - the channel names had different types (`np.str_`, `str,` `np.bytes_`). This converts them all to simple str.
=> [MRG+1] Convert channel names to str

mne/time_frequency/tests/test_tfr.py, mne/time_frequency/tfr.py
Found a fixme in the code, so fixed it.
I verified that:
np.allclose(cwt(X, Ws, use_fft=True, mode='full'), cwt(X, Ws, use_fft=False, mode='full'))
@kingjr thoughts?
=> Add support for Morlet wavelets that are longer than the signal

mne/channels/channels.py
Epochs TFR as well as Average TFR object has channels on a -3 axis. Picking channels exited in a bug.
=> Fixes bug in picking channels in epochsTFR object

doc/whats_new.rst, mne/simulation/tests/test_metrics.py, mne/source_estimate.py, mne/tests/test_source_estimate.py
The `.times` attribute of `_BaseSourceEstimate` is a function of the number of time samples, `tmin` and `tstep`. It should therefore be a read-only property. Because otherwise, we make mistakes and forget to call `_update_times()` and this happens:
```python
from nose.tools import assert_equal
import mne
rng = np.random.RandomState(0)
n_verts_lh, n_verts_rh, n_times = 10, 10, 10
vertices = [np.arange(n_verts_lh), n_verts_lh + np.arange(n_verts_rh)]
data = rng.randn(n_verts_lh + n_verts_rh, n_times)
stc = mne.SourceEstimate(data, vertices=vertices, tmin=-0.1, tstep=0.1)
stc.transform(np.abs, tmin=-50, tmax=500, copy=False)
assert_equal(len(stc.times), stc.data.shape[1])
```
This PR makes `.times` a property and fixes `_BaseSourceEstimate.transform()`. From reading the …
=> [MRG+1] Make stc.times read-only

tutorials/plot_forward.py
Due to recent change in pysurfer, the forward tutorial was failing on circle.
=> [MRG] Fix to forward tutorial.

tutorials/plot_object_epochs.py, tutorials/plot_object_raw.py
For some reason the ``print_function`` doesn't seem to work on [circle](https://circleci.com/gh/mne-tools/mne-python/5245?utm_campaign=build-failed&utm_medium=email&utm_source=notification).
This should fix it.
=> [MRG] Remove sep from tutorials.

doc/whats_new.rst, mne/viz/evoked.py, mne/viz/tests/test_evoked.py
This is a bit weird. plot_compare_evokeds doesn't currently disable the y axis, even though there is a lot of code for that purpose (and it looks very nice). I forgot if I did that on purpose, or if it's just a mistake on my part?
Anyway, this is what the evoked viz tutorial looks like with this fix.
=> MRG redo truncating y axis on plot_compare_evokeds

doc/whats_new.rst, mne/decoding/search_light.py, mne/decoding/tests/test_search_light.py
such that one can do e.g.
```python
clf = SlidingEstimator(LinearModel())
clf.fit(X, y, sample_weights=np.random.rand(len(X))
```
=> ENH: allow SlidingEstimator and gat to get **fit_params at fit

mne/channels/channels.py, mne/channels/montage.py, mne/channels/tests/test_montage.py
This PR:
1. unifies how the `Montage` class exposes the fiducials
2. allows `set_montage` to set `info['dig']` for the `Montage` class, which is useful e.g. for `mne.coreg` and `fit_sphere_to_headshape`.
It's not the full overhaul we need to deal with Montage/DigMontage, but it helps some (and doesn't prevent the eventual full refactoring).
=> [MRG+1]: Allow Montage to set info['dig']

appveyor.yml
There is probably a reason we haven't been running PySurfer on AppVeyor, but let's find out.
=> FIX: Run PySurfer on AppVeyor

doc/whats_new.rst, mne/annotations.py, mne/io/base.py, mne/tests/test_annotations.py, mne/viz/utils.py, tutorials/plot_artifacts_correction_rejection.py
* Adds `skip_by_annotation` as discussed in #4353, with deprecation cycle to get people on board
* fixes a small bug with `Annotations` where the `BAD segment` wasn't actually being put in the correct spot
* changes `BAD segment` to have zero duration
* adds `EDGE segment` that is equivalent to `BAD segment`
* adds `__repr__` to `Annotations`
Closes #4353.
=> MRG+2: Make raw.filter annotation-aware

doc/whats_new.rst, mne/channels/channels.py, mne/channels/interpolation.py, mne/channels/tests/test_interpolation.py, mne/forward/_field_interpolation.py, mne/forward/tests/test_field_interpolation.py
I'm not actually sure if we want to do +1 here (which means "missing less than 0.0001") or do `max(old_val, 1)`, which means "missing at least 0.0001 but keeping at least one component". The former seemed nicer to me but is a bit bigger of a change.
Closes #4377.
=> MRG: Fix interpolation truncation

mne/io/ctf/ctf.py
The CTF data were mislabeled in the docstring
=> [MRG] fix typo

mne/decoding/base.py, mne/decoding/search_light.py, mne/decoding/tests/test_base.py
LinearModel didn't inherited from the classifier type of its base estimator, thus leading to failed detection of sklearn's `is_regressor` and `is_classifier`
=> FIX: add estimator type to LinearModel

examples/visualization/plot_roi_erpimage_by_rt.py, mne/viz/epochs.py
Sorry, I somehow missed this ...
In some configurations, the ylims of the evoked plot for epochs.plot_image are readjusted. This means the vlines have to be adjusted too, otherwise they will end up truncated. This PR fixes that.
@mmagnuski can you maybe take a quick look later? Need to do some checks first.
=> MRG: fix vlines in epochs image

mne/viz/epochs.py
Fixes bug 1 in #4232.
It simply reapplies the ylims to the erpimage. Should I add a warning ("some overlay_times exceed the data range and will not be displayed")?
=> Fix overlay_times exceeding data range in epochs image

mne/io/cnt/cnt.py
cf. mailing list.
Adding a test would require adding a small file which I don't have.
=> Ignore event_offset in cnt when no events exist.

mne/viz/epochs.py
Currently, all figures will get the same title (see [example](https://www.martinos.org/mne/dev/auto_examples/visualization/plot_roi_erpimage_by_rt.html#sphx-glr-auto-examples-visualization-plot-roi-erpimage-by-rt-py)). This fixes it.
=> [BUG, MINOR] argh another epochs image bug [MRG +1]

mne/decoding/search_light.py, mne/decoding/tests/test_search_light.py
Fix bug when using ensemble estimators with `SlidingEstimator` or `GeneralizingEstimator` caused by sklearn internal inconsistency, https://github.com/scikit-learn/scikit-learn/issues/9720
=> MRG: compatibility with bagging classifiers

doc/conf.py, doc/documentation.rst, mne/channels/channels.py, mne/decoding/receptive_field.py, mne/decoding/tests/test_receptive_field.py, mne/decoding/time_delaying_ridge.py, mne/viz/epochs.py, mne/viz/evoked.py, mne/viz/topomap.py, tutorials/plot_receptive_field.py
=> MRG: fill_value in ReceptiveField

doc/whats_new.rst, mne/source_space.py, mne/tests/test_source_space.py
This doesn't happen often. In fact, it happens so rarely we hadn't noticed yet some of the logic was broken. This PR adds a test and fixes the logic.
=> Fix morphing to original subject when two vertices map to the same target vertex

mne/stats/cluster_level.py, mne/stats/permutations.py, mne/stats/tests/test_cluster_level.py
In practice the prevention of collisions is probably a bit overkill, but this should ensure we sample without replacement. But even in the intermediate range `20 < n_samples < 64` the `rng.choice` call was a bit rough on memory usage, so this fixes that, too.
Closes #4551.
@nbara can you see if it fixes your problem?
=> MRG: Fix permutations without replacement

mne/time_frequency/tests/test_tfr.py, mne/time_frequency/tfr.py
This allows for `EpochsTFR` to contain the (linear) complex outputs from `tfr_morlet`, like you can get from `tfr_array_morlet`. Eventually this could be useful for putting through an inverse, for example. In the meantime this incremental change is ready for review/merge from my end.
=> MRG: Allow complex TFR output

mne/io/edf/edf.py
To retrieve correct event values (bits 1-16) in Biosemi Status channel, one could do masking (`events[:, 2] &= (2**16 - 1)`), but shiffting (as presented in the current note `events[:, 2] >>= 8`) does not do that. For instance:
```python
In [1]: 256 & (2**16 - 1)
Out[1]: 256
In [2]: 256 >> 8
Out[2]: 1
In [3]: 2**16 & (2**16 - 1)
Out[3]: 0
In [4]: 2**16 >> 8
Out[4]: 256
```
We use Biosemi sync with LPT, so I always mask to 255 or (2**8 - 1).
=> MRG: Fix Biosemi EDF note

mne/beamformer/_lcmv.py
Clarifying the None option for both ``weight_norm`` and ``pick_ori``. 
Thanks @jasmainak and @agramfort for pointing this out!
=> Fixing docstring for LCMV beamformer

doc/whats_new.rst, examples/time_frequency/plot_time_frequency_erds.py
Fix #4558. This example produces the following two plots:
This is already pretty OK, but there are two minor things that I'd like to change if it's not too much effort:
1. The x-axis should be in seconds.
2. The y-axis is weirdly spaced, ideally I'd like the frequency tick labels to be uniformly spaced.
Any easy ways to fix these things?
=> [MRG] Add ERDS maps to time-frequency examples

doc/whats_new.rst, mne/viz/raw.py
I think it would be useful if the event numbers were plotted (and not just encoded by color).
This would look like as follows:
Two issues:
1. There is not much space between the title and the main axes. Sometimes the event labels overlap with the title. How could this be improved?
2. Sometimes the label of an earlier event which should not be visible in the current view is shown (see attached screenshot, the event label "11" occurs in the previous page) - does anyone spot the error in my code?
=> [MRG] Plot event numbers

doc/whats_new.rst, mne/preprocessing/tests/test_xdawn.py, mne/preprocessing/xdawn.py
I hit a case where `proj` broke `Xdawn`. This should make it work for positive semidefinite instead of only positive definite matrices.
=> MRG: Error about rank-deficient inputs in Xdawn

examples/time_frequency/plot_time_frequency_erds.py, mne/time_frequency/tfr.py
Change time axis scale to seconds in `AverageTFT.plot` and `AverageTFR.plot_topo`.
=> Plot TFR x-axis in seconds instead of milliseconds

doc/whats_new.rst, examples/decoding/plot_receptive_field.py, mne/decoding/receptive_field.py, mne/decoding/tests/test_receptive_field.py, mne/decoding/time_delaying_ridge.py
This is an attempt to implement inverse coefficient computation according to [1], which has been discussed in #3884 . This is mostly useful to visualise weights for backward models (aka stimulus reconstruction).
ATM the computation is done in `ReceptiveField.fit()`, so I had to expose the data covariance `x_xt_` in `TimeDelayingRidge()`. I can compute the inverse coefficients directly inside TDR if you prefer.
These are specific points where your input would be appreciated:
Thanks in advance.
[1] | Haufe, S., Meinecke, F., Görgen, K., Dähne, S., Haynes, J.-D., Blankertz, B., & Bießmann, F. (2014). On the interpretation of weight vectors of linear models in multivariate neuroimaging. NeuroImage, 87, 96–110. doi:10.1016/j.neuroimage.2013.10.067
=> WIP: Inverse-transform ReceptiveField

examples/visualization/plot_channel_epochs_image.py, examples/visualization/plot_roi_erpimage_by_rt.py, mne/channels/layout.py, mne/viz/evoked.py, mne/viz/ica.py, mne/viz/tests/test_epochs.py, mne/viz/tests/test_evoked.py, tutorials/plot_visualize_evoked.py
```
import mne
fname = op.join(data_path, 'MEG', 'sample', 'sample_audvis-ave.fif')
evoked = mne.read_evokeds(fname, baseline=(None, 0), proj=True)
conditions = ["Left Auditory", "Right Auditory", "Left visual", "Right visual"]
evoked_dict = dict()
for condition in conditions:
evoked_dict[condition.replace(" ", "/")] = mne.read_evokeds(
fname, baseline=(None, 0), proj=True, condition=condition)
print(evoked_dict)
colors = dict(Left="Crimson", Right="CornFlowerBlue")
linestyles = dict(Auditory='-', visual='--')
picks = np.arange(20)
mne.viz.plot_compare_evokeds(evoked_dict, picks=picks, colors=colors,
show_sensors=True,
truncate_yaxis="max_ticks",
linestyles=linestyles)
```
Show what channels are plotted in …
=> VIZ, ENH: plot_compare_evokeds sensor legend

mne/commands/mne_surf2bem.py
Tiny fix to take care of error "_surfaces_to_bem() got an unexpected keyword argument 'sigma'".
=> Fix typo for sigmas in mne_surf2bem.py

examples/inverse/plot_mixed_norm_inverse.py, mne/viz/_3d.py
=> FIX: Add numbers for dipoles

doc/whats_new.rst, examples/connectivity/plot_cwt_sensor_connectivity.py, examples/visualization/plot_topo_compare_conditions.py, mne/decoding/csp.py, mne/evoked.py, mne/io/base.py, mne/tests/test_docstring_parameters.py, mne/utils.py, mne/viz/epochs.py, mne/viz/evoked.py, mne/viz/tests/test_3d.py, mne/viz/tests/test_decoding.py, mne/viz/tests/test_epochs.py, mne/viz/tests/test_montage.py, mne/viz/tests/test_raw.py, mne/viz/tests/test_topo.py, mne/viz/tests/test_topomap.py, mne/viz/tests/test_utils.py, mne/viz/topo.py, mne/viz/topomap.py, mne/viz/utils.py, tutorials/plot_epochs_to_data_frame.py
Closes #3702.
This PR:
1. Unifies `scale`->`scalings`
2. Fixes lots of warnings in tests
3. Includes a fix for `plot_topo` that was necessary for tests to pass locally (and for interactivity to work for me at all), so I slightly modified two tutorials so that CircleCI would generate them.
(One of the last big blockers for 0.15!)
=> API: Use scalings

doc/whats_new.rst, examples/decoding/plot_decoding_csp_eeg.py, examples/decoding/plot_decoding_xdawn_eeg.py, examples/io/plot_elekta_epochs.py, examples/preprocessing/plot_virtual_evoked.py, examples/realtime/plot_compute_rt_decoder.py, examples/stats/plot_sensor_permutation_test.py, examples/stats/plot_sensor_regression.py, examples/time_frequency/plot_compute_raw_data_spectrum.py, mne/decoding/csp.py, mne/decoding/transformer.py, mne/evoked.py, mne/filter.py, mne/forward/_field_interpolation.py, mne/forward/tests/test_field_interpolation.py, mne/io/base.py, mne/utils.py, tutorials/plot_brainstorm_auditory.py, tutorials/plot_stats_cluster_time_frequency_repeated_measures_anova.py
Closes #4605.
Closes #4607.
Fixes our doc builds:
- `_v` instead of `_virtual` for virtual evokeds
- fixes some linking errors in `whats_new.rst`
- fixes many deprecation warnings in examples
=> MRG: Fix examples

doc/documentation.rst, doc/whats_new.rst, examples/visualization/plot_xhemi.py, mne/source_estimate.py, mne/surface.py, mne/tests/test_surface.py
Addresses #4360 
@Eric89GXL what do you think of the API? An example is below.
The `'lh'`/`'rh'` tags allow specifying which direction to map (I don't think mirroring both hemispheres will be useful). An alternative would be that the user should specify vertices for only the required hemispheres, like `[[], rh_vertices], [lh_vertices, []]` to morph from right to left; in that case we could actually remove the reg_from and reg_to parameters if all we want to add is xhemi morphing, but this solution is less explicit than the parameters.
Concerning testing, actually testing the x-hemi registration would require adding a new registration file to the dataset. Alternatively I could just add a test loading a morph matrix for only one hemisphere.
```
import mne
sdir = …
```
=> [MRG+1] ENH:  morph between hemispheres

.travis.yml, doc/manual/channel_interpolation.rst, doc/manual/cookbook.rst, doc/manual/decoding.rst, doc/manual/preprocessing/ssp.rst, doc/manual/sample_dataset.rst, doc/tutorials/report.rst, environment.yml, mne/datasets/hf_sef/hf_sef.py
This should be nearly equivalent to what we already do, just with fewer lines and using an `environment.yml` file. This moves us toward more easily testing things like #4523 when we think Py3k might actually be ready for primetime.
=> MRG: Use environment.yml in CIs

doc/Makefile, doc/conf.py, doc/whats_new.rst, examples/connectivity/plot_mixed_source_space_connectivity.py, examples/connectivity/plot_mne_inverse_connectivity_spectrum.py, examples/connectivity/plot_mne_inverse_label_connectivity.py, examples/connectivity/plot_mne_inverse_psi_visual.py, examples/inverse/plot_compute_mne_inverse_epochs_in_label.py, examples/inverse/plot_label_from_stc.py, examples/inverse/plot_label_source_activations.py, examples/inverse/plot_mixed_source_space_inverse.py, mne/label.py, mne/stats/cluster_level.py
In `master` the `mean_flip` has an ambiguous sign because it relies on SVD (I think). This fixes the ambiguity by choosing the overall sign based on what maximally aligns with the "outward" (positive) direction of the label.
I made minor changes to the various examples that use `mean_flip` so we can see the result.
=> MRG+1: Fix mean flip sign ambiguity

doc/whats_new.rst, examples/visualization/plot_parcellation.py, mne/datasets/tests/test_datasets.py, mne/datasets/utils.py, mne/label.py
This adds the combined labels (23 per hemi) for the HCPMMP parcellation.
There is no test because downloading the (only 4MB!) parcellation can actually be pretty slow, but it is effectively tested by CircleCI (just as before).
=> MRG+1: Add reduced set of labels for HCPMMP

doc/whats_new.rst, mne/io/base.py, mne/io/fiff/tests/test_raw_fiff.py
As mentioned in the issue, `raw.first_samp` isn't being respected in the resampling of `events`. The `np.min`-call will (silently) return the `last_samp` for any events larger than the `new_length`.
Closes #4621
=> Resample events fix

doc/python_reference.rst, mne/chpi.py, mne/cov.py, mne/dipole.py, mne/minimum_norm/inverse.py, tutorials/plot_mne_dspm_source_localization.py
a first attempt to give love to cov code by simplifying code path
you can see that dipole fit and LCMV use compute_whitener while make_inverse_operator is using _get_whitener so does not use scalings and does not back project (using eigvec).
this need further thinking...
.. note:: how a lunch with @dengemann ends up :)
=> [MRG] Simplify cov code path

mne/datasets/utils.py, mne/utils.py
Fixes a bug pointed out by @kingjr where the visual 92 categories dataset wouldn't download properly. This refactors it so that all downloads (in this case, 2) are done, hashes checked, and *then* files are extracted. This is much nicer for restarting than what was done before.
@kingjr can you try it and see if it works.
This is needed for 0.15.
=> MRG: Fix dataset fetcher

mne/label.py, mne/source_estimate.py, mne/tests/test_label.py
This is useful e.g. when concatenating labels in the medial wall.
=> ENH: Add sign flipping for BiHemiLabel

doc/whats_new.rst, mne/preprocessing/ssp.py, mne/preprocessing/tests/test_ssp.py
When getting `None` as proj because all epochs are rejected, it's nice to have the option to see why (and pass the result to `plot_drop_log`).
=> MRG: Expose drop log

mne/channels/montage.py
We've recently added a topomap-like montage plot method #4276 #4399. I found another inconsistency: `mne.viz.montage.plot_montage` has `show_names=True` whereas `mne.channels.montage.Montage.plot` has `show_names=False`. This should be fixed, and a topomap without channel names doesn't make much sense for a montage plot.
=> [MRG] Change show_names to True by default in montage.plot

mne/bem.py, mne/preprocessing/maxwell.py, mne/source_space.py, mne/utils.py
This makes the messaging better for `maxwell_filter`, as well as for `run_subprocess` calls (now just `freesurfer`).
- If `verbose='info'` stdout and stderr of the process are printed
- if `verbose='warning'`, just stderr is printed
- if `verbose='error'` nothing is printed
This is most consistent with our own internal behavior. Doing `verbose=None` makes nothing get printed, `verbose='info'` gives the `logger.info` messages plus FreeSurfer output. This is much nicer when doing reconstructions. If there is an error, the `stdout` and `stderr` get printed before an error is raised.
=> MRG: Better verbosity for MF and anatomy

mne/viz/utils.py
Warnings don't have `get_message` on Py3k, so this was errantly going through the `except Exception` route.
=> MRG: Fix tight_layout for Py3k

doc/whats_new.rst, mne/beamformer/_rap_music.py, mne/beamformer/tests/test_rap_music.py
When using another set of phantom data, the threshold used to estimate the rank is not good. It makes the rank=3 which is not possible in sphere models causing wrong estimation of dipole orientation.
=> [MRG] change the threshold for the rank in RAP-MUSIC

mne/beamformer/_lcmv.py, mne/beamformer/tests/test_lcmv.py
Fixes a bug with channel selection within the ``lcmv`` functions. 
The channel selection on the data (based on a comparison to the forward model) failed in particular cases, e.g., when the data contained reference channels - as reported by @kingjr in https://github.com/mne-tools/mne-python/issues/4663 .
=> Fix data channel selection in LCMV

doc/whats_new.rst, mne/viz/tests/test_topo.py, mne/viz/topo.py
In the single channel plot that you get from `plot_evoked_topo()`, there is currently no easy way to get response amplitudes. This patch would update the matplotlib status bar according to data, like so:
=> WIP: update status bar according to data

mne/decoding/receptive_field.py, mne/decoding/tests/test_receptive_field.py
@choldgraf can you take a quick look? I think we always meant to have `rf.score(...)` return an array (according to the docstring) but it wasn't.
=> MRG: Fix ReceptiveField output

mne/viz/raw.py
When a `raw` object doesn't have a title (e.g. when creating from scratch with `mne.io.RawArray`), the window title cannot be set. If possible, this should go into 0.15...
=> [MRG] Fix browse raw error when raw has no title

tutorials/plot_epoching_and_averaging.py
In the tutorial on [Epochs and Averaging](https://martinos.org/mne/stable/auto_tutorials/plot_epoching_and_averaging.html#tut-epoching-and-averaging), there is place where a `baseline` tuple is defined, but it never gets passed into `Epochs()` on the following line. This is small fix for that.
The value used is the same as the default value, so the result doesn't actually change or anything.
=> Added unused tuple as an argument

doc/whats_new.rst, examples/preprocessing/plot_rereference_eeg.py, mne/io/reference.py, mne/io/tests/test_reference.py
`ref_channels=[]` didn't remove existing average projectors. Fixes #4382.
=> [MRG] Fix rereferencing (again)

mne/stats/cluster_level.py
If `threshold=None`, the automatically determined value should be logged.
=> [MRG] Log automatically determined cluster threshold

doc/whats_new.rst, mne/viz/raw.py, mne/viz/utils.py
Fix #4690 - this is a first try and I think a step into the right direction. When adding new annotations ('a' key), some annotation texts are still overplotted.
=> [MRG] Correctly delete previous event texts

mne/time_frequency/psd.py, mne/time_frequency/tests/test_psd.py
For 1d-arrays, `dshape` is `()`, leading to `hstack` inferring `dtype` `float`
=> FIX psd_array_welch:  1d input arrays

mne/io/edf/edf.py
Otherwise loading a GDF file results in `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 5: invalid start byte` or similar errors.
=> [MRG] Use 'latin-1' decoding for GDF header fields

doc/whats_new.rst, mne/event.py, mne/io/edf/edf.py, mne/tests/test_event.py
As discussed with @larsoner in #4340, this PR adds support for initial events to `mne.find_events` with the argument `initial_event=False`. If set to `True`, initial events are only added if the value of the stim channel(s) are non-zero. If set to `False` (default), a warning is generated if non-zero initial values in stim channel(s) are found. Finally, I'm issuing an info if an EDF file contains EDF annotations (slightly unrelated, but still kinda fits in here).
One question I have is that I'm assuming `data` in `_find_events` is one stim channel (as opposed to potentially several stim channels in `find_events`) - which is why I'm doing `data[0, 0]` to get the initial value (no idea why this array doesn't get squeezed before). Is this assumption correct?
=> [MRG] Support for initial event in mne.find_events

mne/evoked.py, mne/io/pick.py, mne/viz/epochs.py, mne/viz/evoked.py, mne/viz/tests/test_evoked.py, tutorials/plot_metadata_epochs.py, tutorials/plot_visualize_evoked.py
closes #4736 and #4526
@jona-sassenhagen @ktavabi I took over both of your PRs and simplify to refactor / simplify
please have a look
=> [MRG] Fix compare evokeds

doc/whats_new.rst
Since #4773 is a noticeable UX change we should document it in `whats_new` as well.
=> [MRG] Add whats_new for #4773

examples/stats/plot_sensor_permutation_test.py, mne/stats/permutations.py, mne/stats/tests/test_permutations.py
Fixes minor bug introduced in #4743 (0.16 cycle) with `permutation_t_test` that has broken CircleCI on `master` lately.
=> MRG: Fix permutation bug

mne/gui/_marker_gui.py
Minor new feature, a button to change the order of HPI marker points in case they were applied to the subject in the wrong order.
=> [MRG] Kit2fiff: reorder marker points

doc/whats_new.rst, mne/annotations.py, mne/tests/test_annotations.py
I thought it would be handy if I could add two `Annotations` objects like this:
```python
import mne
a = mne.Annotations([1, 2, 3], [5, 5, 8], ["a", "b", "c"])
b = mne.Annotations([11, 12, 13], [1, 2, 2], ["x", "y", "z"])
c = a + b
```
Or in-place like this:
```python
a += b
```
Currently, this can only be done in-place with a slightly more verbose syntax:
```python
a.append(b.onset, b.duration, b.description)
```
=> [MRG] Add annotations

doc/whats_new.rst, mne/io/constants.py, mne/io/meas_info.py, mne/io/tests/test_meas_info.py
Elekta's official `fiff_support` libs have included (amongst others) a tag for gantry position.
```c
#define FIFF_GANTRY_ANGLE          282    /* Tilt angle of the gantry in degrees. */
```
Presumably this is included in all subsequent DACQ versions, so practically all VectorView __and__ Triux files will have this tag set. Notably, `sample` doesn't ;)
For this PR I simply followed the tag `line_freq` down the code in `meas_info.py`, and added a new key `gantry_angle` everywhere.
BTW, it's useful to know the angle when diagnosing far-away noise sources and EAS (some directions are better compensated than others).
=> ENH add gantry angle IO to FIFF consts and meas_info

doc/whats_new.rst, mne/datasets/utils.py, mne/io/egi/egimff.py, mne/io/egi/tests/test_egi.py
Not the happiest solution, but just a workaround for the problem EGI has.
Basically the MFF container has a signal1.bin and signal2.bin. Sometimes (and that's why it did not show up before), the signal2.bin has 1 sample less than what's indicated in the header and in the signal1.bin. EGI people knows about that, but their response is "you do not use our API".
I guess they have a major problem somewhere.
This proposed fix checks to see if we reached the end of the file and we still need to read 1 sample. If that's the case, the last sample is filled with 0s.
This is the headers from signal1.bin (40 blocks like first line, the last one is shorter):
```
{'nc': 257, 'hl': 1052672, 'nsamples': 4096, 'block_size': 4210688, 'header_size': 2100, 'sfreq': 250}
{'nc': 257, 'hl': 752239, 'nsamples': …
```
=> Fix for EGI PSG signal bug

mne/decoding/base.py, mne/decoding/tests/test_base.py
Adds **kwargs to fit ala scikit-learn to make it compatible with `sample_weight`
e.g.
```python
LinearModel().fit(X, y, sample_weight=sample_weight)
```
=> ENH: Add sample weight test LinearModel

doc/whats_new.rst, mne/event.py, mne/tests/test_event.py
Fixes some corner cases of `mne.compute_raw_covariance` I found when investigating #4808.
=> MRG: Fix corner cases for mne.make_fixed_length_events

examples/connectivity/plot_mixed_source_space_connectivity.py, examples/connectivity/plot_mne_inverse_label_connectivity.py, mne/viz/circle.py
For plot_mne_inverse_label_connectivity.py this only adds the explanation and commented commands.  For plot_mixed_source_space_connectivity.py I tweaked things a bit so that plt is used even when the savefig line is commented out.
=> Add savefig to circle graphs for #4714

mne/externals/tempita/__init__.py, mne/viz/tests/test_3d.py
1. test one is somewhat obvious
2. tempita one (didn't check/submit upstream) -- would fail to "str" a unicode, which is somewhat pointless anyways if it is already a unicode, so why not to leave it as such
=> Two minor fixes I have encountered needing while building a debian package

mne/decoding/tests/test_receptive_field.py
to say the truth I am not sure if that is numpy 1.13 to blame but that is what I have deduced to pass the test across recent debian/ubuntus which do not have yet numpy 1.13
=> BF(TST): skip a test on a warning if numpy is not 1.13

mne/viz/raw.py
Before:
After:
Alternatively, we could make event lines transparent instead of pushing them to the bottom of the z order.
=> [MRG] Event lines should not overplot raw traces

doc/whats_new.rst, mne/io/pick.py
The function `get_channel_types` returns a dict with known channel types as keys and their definitions in the `info` dict as values. This PR has two benefits:
1. It is now possible to ask for a list of known channel types
2. The function `channel_type` is now more generic and much shorter (because the logic is now in the dict defined in `get_channel_types`
WDYT? I can't believe I had to use the `else` clause of a `for` loop.
=> [MRG] Add function that returns all defined channel types

doc/whats_new.rst, mne/channels/channels.py, mne/channels/montage.py, mne/io/meas_info.py
Fixes #4841.
Questions:
1. Do we care about the `set_dig` argument?
2. I'm not sure what the correct default value for `info["chs"][idx]["loc"]` is. `mne.create_info` fills this entry with `np.concatenate((np.zeros(3), np.eye(3).ravel())).astype(float)`, whereas `mne.io.read_raw_edf` seems to fill it with all zeros.
=> [WIP] Remove montages with set_montage(None)

doc/python_reference.rst, doc/whats_new.rst, mne/__init__.py, mne/annotations.py, mne/io/base.py, mne/io/fiff/raw.py, mne/tests/test_annotations.py
With this PR, `Annotations` themselves can be saved and loaded, and applied to files when necessary. This is useful e.g. when creating annotations that have expensive computation time and need to be used for multiple purposes.
=> MRG+1: Allow standalone Annotations IO

doc/whats_new.rst, mne/annotations.py, mne/io/base.py, mne/io/constants.py, mne/io/fiff/raw.py, mne/io/fiff/tests/test_raw_fiff.py, mne/io/meas_info.py, mne/io/open.py, mne/io/tag.py, mne/io/tests/test_meas_info.py, mne/io/utils.py, mne/io/write.py, mne/tests/test_annotations.py, mne/viz/raw.py, mne/viz/utils.py
This PR:
- Fixes a bug in `Annotations` when cropping to the last sample
- Fixes minor bugs in `bad_acq_skip` annotations
- Fixes `raw.filter` to respect acquisition skips
- Fixes `raw.save` to allow properly saving acquisition skips (assuming `buffer_size_sec` is conserved)
- Fixes `raw.plot(lowpass=...)` to respect boundaries the same way `raw.filter(...)` does by default
- Improves `Tag.__repr__`
- Improves `mne show_fiff` and `mne.viz.compare_fiff` visualization to include data types
- Fixes a `np.fromstring` -> `np.frombuffer` I missed earlier
And while I was fixing all this stuff I noticed a diff in a file, so I added support for reading subject height and weight.
=> MRG: Fix acquisition skips

doc/whats_new.rst, mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_maxwell.py
Fixing a bug introduced by `pick_types(meg='mag', ...)` returning channel indices that actually belong to gradiometers.
=> MRG: Fix CTF Maxwell filter bug

doc/whats_new.rst, mne/channels/layout.py, mne/channels/montage.py, mne/channels/tests/test_layout.py, mne/channels/tests/test_montage.py, mne/dipole.py, mne/io/base.py, mne/io/brainvision/brainvision.py, mne/io/cnt/cnt.py, mne/io/ctf/info.py, mne/io/ctf/tests/test_ctf.py, mne/io/eeglab/eeglab.py, mne/io/eeglab/tests/test_eeglab.py, mne/io/kit/kit.py, mne/io/meas_info.py, mne/io/tag.py, mne/source_space.py, mne/viz/circle.py, mne/viz/misc.py, mne/viz/utils.py
We should assign `np.nan` for unknown locations instead of `[0., 0., 0.]`. This PR moves us in that direction. I need to see what other internal checks this breaks, and fix them.
Closes #4855.
=> MRG: Fix loc

doc/whats_new.rst, mne/annotations.py, mne/io/base.py, mne/tests/test_annotations.py
This allows saving and reading empty annotations. It also makes it so that raw instances can have empty annotations.
This also fixes what I consider a bug -- if one does:
```
raw.annotations = Annotations(...)
raw.save(fname)
raw_read = read_raw_fif(fname)
```
it shouldn't matter what is in the `...`, they should have `isinstance(raw_read.annotations, Annotations)` after such round-trip I/O.
=> MRG: Fix annotation handling

doc/whats_new.rst, mne/report.py, mne/tests/test_report.py
Various small fixes to `Report`. The biggest is the BEM section, which looks like this on `master`:
And on this PR it's more compact and has label sizing more consistent with other sections:
=> MRG: Tweak report

mne/io/base.py
Overwriting raw file without preloading throws...
> ValueError: You cannot save data to the same file. Please use a different filename.
Noted in doc string.
=> Minor edit to base docstring.

mne/commands/mne_browse_raw.py, mne/commands/tests/test_commands.py, mne/viz/raw.py
Fixes a bug with `mne browse_raw`. Should only affect 0.16+ because that's when we did the deprecation for `order` IIRC, so no need for `whats_new.rst` update.
=> MRG: Fix mne browse_raw

.travis.yml
Disabling the OSX builds for now. They fail 90% of the time to run, install Anaconda, or finish the tests, *and* they often take hours to do so, which is tough for feedback. Maybe we'll try again in a couple of months to see if the situation has improved.
=> MRG: Fix Travis

mne/preprocessing/ica.py
This should be easier to understand. I wanted to make it clear that `noise_cov` does not influence whitening per se, which is always performed as a subsequent step. I hope that it is clear that pre-whitening equals prior to whitening.
=> Improve description of noise_cov argument

examples/inverse/plot_lcmv_beamformer_volume.py
see https://github.com/mne-tools/mne-python/issues/4875
I dropped the channel selection and used the data from both left and right auditory stimulation.
Source space activity is plotted based on peak latency in the sensor level data.
cc @kingjr @agramfort @dengemann and @sarangnemo
=> Drop channel selection from LCMV example

doc/whats_new.rst, mne/preprocessing/maxwell.py, mne/tests/test_transforms.py, mne/transforms.py
It turns out doing a naive weighted average of quaternions can be problematic, especially in cases where `q == -q`. This does a proper average.
In practice this probably isn't breaking anyone's data (much) because it the head position calculation maintains very similar quaternion representations from one time point to the next, but this should be cleaner in any case.
=> MRG: Fix computation of average quaternion

mne/minimum_norm/inverse.py, mne/minimum_norm/tests/test_inverse.py
When calling apply_inverse with `pick_ori='normal'` and a fully free inverse_operator (`loose=1`) it raises an exception because of what i think was a typo in checking the loose parameter.
The test I added is somewhat clumsy but i couldn't find a better/cleaner place to added it.
=> FIX: BUG (typo) in apply_inverse

doc/whats_new.rst, mne/channels/channels.py, mne/channels/montage.py, mne/channels/tests/test_montage.py
Which means that instead
raw.set_montage(mne.channels.read_montage("biosemi64"))
one can simply type
raw.set_montage("biosemi64")
=> [MRG] Allow montage to be a str in raw.set_montage

mne/io/ctf/eeg.py, mne/io/ctf/tests/test_ctf.py
@larsoner 
When loading digitizer points from a ctf DS file, the points are being read in in the CTF_HEAD frame however they are immediately (Line 92) transformed to the MNE_HEAD frame. so the dig structure should reflect that.
While I haven't dug through everything, the code else where (viz._3d.plot_alignment / coreg) seems to treat these points as if there are in COORD_HEAD already, ie they never try to apply info['ctf_head_t']
=> FIX: ctf dig pnts coord_frame

doc/faq.rst, doc/install_mne_python.rst
@agramfort @larsoner Here is an attempt at adding the suggestion of using the IPython magic %gui qt in Python 3 Jupyter notebooks. It wasn't clear where to put it so I added it to the Experimental Python 3.6 pulldown on the Python install page.
=> WIP: add note about %gui qt magic to python install page

doc/whats_new.rst, mne/bem.py, mne/chpi.py, mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_maxwell.py, mne/tests/test_chpi.py
Fixes a few small bugs found while working on head position correction:
1. Computation of coil location goodness of fit in the private function `_calculate_chpi_positions`.
2. Computation of high-correlation segments to avoid re-fitting.
3. Remove demean step for HPI coil fits (the model has a DC term).
4. `maxwell_filter` with `coord_frame='meg', origin=(...)` wasn't being converted properly to the head coordinate frame for recordings that have a MEG<->head transform. Fortunately this use case should be pretty rare (usually origins should be provided relative to the head location for such non-empty-room recordings). This is the only public-facing change so it's the only one in `whats_new.rst`.
@bloyl you might be interested in some of this because it touches the HPI fitting code (which …
=> MRG: Fix maxfilter and cHPI

mne/viz/topomap.py
The contours should not have the same width as the head geometry - using thinner lines separates the contours better from the head IMO.
Before:
After:
=> [MRG] Reduce linewidth of contours in plot_topomap

tutorials/plot_stats_spatio_temporal_cluster_sensors.py
I just changed the p_value for accepted clusters in the  [ spatiotemporal permutation F-test example](https://martinos.org/mne/dev/auto_tutorials/plot_stats_spatio_temporal_cluster_sensors.html) so it can actually find some clusters to plot (there is no cluster figures showing up as it currently is on the website).
=> Fixed p val in example Spatiotemporal permutation F-test

examples/decoding/plot_decoding_xdawn_eeg.py, examples/preprocessing/plot_xdawn_denoising.py, mne/cov.py, mne/decoding/csp.py, mne/decoding/tests/test_csp.py, mne/fixes.py, mne/preprocessing/xdawn.py, mne/tests/test_cov.py
I've been trying to use some decoding functions (`XDawn`, `CSP`) on rank-reduced SSS'ed MEG data. I'd like to be able to use the simple / naive `mne.cov.regularize` function for this, because it seems like I don't get consistent results from the automated regularizers (though maybe I'm just being dumb). Adding a `reg=callable` possibility seems like the easiest way, then I can do e.g.:
```
def reg(data):
raw = mne.io.RawArray(data, epochs.info)
cov = mne.compute_raw_covariance(raw, step=None)
return mne.cov.regularize(cov, raw.info)['data']
```
So this fits my use case pretty easily, and seems like a pretty simple extension.
Todo:
@kingjr @alexandrebarachant @agramfort does this seem like a reasonable addition to you? If so, I'll update all other docstrings and add some tests.
=> MRG: Unify covariance code in mne/decoding and mne/cov.py

mne/io/edf/edf.py, mne/io/edf/tests/test_edf.py
After GDF support was added, the stim channel in BDF files is not detected automatically anymore. The previous default used to be `stim_channel=-1` (the last channel), but this changed to `stim_channel='auto'`.
In EDF+ files, the TAL channel (containing annotations and therefore the stim channel) was assigned MISC - I changed this to STIM.
The whole thing is still a bit messy, mostly due to the mix of EDF/BDF/GDF. Maybe a future PR could try to disentangle these file formats better. However, my quick fix hopefully solves the most important issue, namely that automatic stim channel detection for BDF files is broken.
Fixes #4710, fixes #4757.
=> Fix stim channel detection in BDF and EDF+

.travis.yml
We should always report coverage, even on failures.
=> MRG: Always add coverage

mne/io/egi/egimff.py
only read the pns channels when they are required (i.e. in chs_to_read).
=> fix pns_idx undefined error

doc/whats_new.rst, mne/annotations.py, mne/tests/test_annotations.py
This PR adds the necessary code to be able to read Brainstorm markers (events + annotations) from a `events_*.mat` file. 
The proposed user code would be : 
```py
import mne 
from scipy import io 
raw_fname = '/Data_samples_In_MNE/sample_audvis_raw.fif'
raw = mne.io.read_raw_fif(raw_fname)
annot_fname = '/Your/Path/events_sample_audvis_raw_ASD.mat'
raw.annotations = mne.annotations.read_brainstorm_annotations(annot_fname,raw.info['meas_date']) 
```
=> [MRG][ENH] A reader for Brainstorm events

doc/faq.rst, examples/inverse/plot_mixed_norm_inverse.py, examples/inverse/plot_rap_music.py, examples/visualization/plot_sensor_noise_level.py, mne/beamformer/_rap_music.py, mne/inverse_sparse/mxne_inverse.py, mne/inverse_sparse/mxne_optim.py, tutorials/plot_dipole_orientations.py
Hello!
The DOI foundation recommends a [new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). This PR suggests that change.
Cheers :-)
=> link DOIs to preferred resolver

doc/whats_new.rst, mne/io/eeglab/eeglab.py, mne/io/eeglab/tests/test_eeglab.py
fix event latency from matlab 1-based to python 0-based.
Fixes #4944.
=> [MRG+1]: fix event sample indices read from eeglab files

mne/cov.py, mne/preprocessing/tests/test_xdawn.py, mne/preprocessing/xdawn.py
The recent unification got us 90% of the way to being able to use Xdawn with `maxwell_filter`ed data. This should get us all the way there. Fixes:
1. Update docstring of `Xdawn` itself.
2. Pass `method_params` and `info` so cov can be computed properly by auto methods, including `diagonal_fixed`, which needs to know channel types.
=> [MRG+1]: Fix Xdawn rank deficiency

doc/whats_new.rst, mne/commands/mne_coreg.py, mne/coreg.py, mne/gui/__init__.py, mne/gui/_coreg_gui.py, mne/gui/_file_traits.py, mne/gui/_viewer.py, mne/gui/tests/test_coreg_gui.py, mne/surface.py
This PR:
1. Adds a button to project EEG electrodes to the scalp in `mne coreg`.
2. Fixes a bug where `--low-res-head` didn't always use a low res head (fixed by first looking for `outer_skin.surf` if it exists; `subject-head.fif` is now second, as it can be a dense head).
3. Adds support for normals when surfaces are loaded, enabling hair growing with e.g. `outer_skin.surf` files.
4. Adds support for `~` in the `--subjects-dir` and `--trans` paths using `expanduser`.
@christianbrodbeck do you have time to look and try? Example that shows all of these changes at once:
```
mne coreg --subjects-dir=~/mne_data/MNE-sample-data/subjects -f ~/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw.fif --no-guess-mri -s sample --low-res-head --project-eeg
```
Closes #3700.
=> MRG: Add projection to surface for coreg

doc/whats_new.rst, mne/gui/_coreg_gui.py, mne/gui/_viewer.py
Even when the head is translucent, points behind it should be blocked (i.e., the *inside walls* of the head should be opaque). This makes it clearer which points are on the near side of the head when doing fits.
For example, look at the `sample` data:
```
mne coreg --subjects-dir=$HOME/mne_data/MNE-sample-data/subjects -f ~/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw.fif --no-guess-mri -s sample --high-res-head --trans=$HOME/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw-trans.fif
```
Let's scale up the MRI by a factor of 1.1 to make it clear what we're talking about -- on `master` and this PR, this is what you'd see -- all points inside the head are appropriately alpha blended with the head:
On the other hand, if scale MRI by a factor of 0.9 to shrink it, we get this on …
=> MRG: Block points behind the head

mne/viz/raw.py
Motivation: when using `matplotlib.pyplot.style.use('dark_background')` the good channel labels are all invisible.  This fixes that by using the same color for the good channel labels as for the good channel data (also more consistent with the behavior of bad / stim channels, which already match label and data colors).
cc: @jaeilepp @larsoner
=> don't force good channels' labels to black

examples/inverse/plot_vector_mne_solution.py
Fixes a minor misspelling in one of the examples.
Changed the spelling of vizualization to visualization.
=> Minor misspelling fix

doc/whats_new.rst, mne/io/brainvision/brainvision.py, mne/stats/regression.py, mne/stats/tests/test_regression.py
The use of `round()` in the `Epochs` class can lead to to slightly different answers than the default truncation used by `int()` typecast when the sampling frequency isn't a multiple of 10 (e.g. for BioSemi recordings, where the sampling rates are powers of 2). While the difference is trivial, it creates problems when e.g. combining `Evoked` objects computed from `linear_regression_raw` and `Epochs`. This makes `linear_regression_raw` behave consistently with `Epochs`.
=> change rERP calculation of times to match Epochs calculation

mne/io/edf/edf.py
Commit https://github.com/mne-tools/mne-python/commit/847347d14b858b86e5aac347a9db1bcf44b554d6#diff-825d45683d0be02fad23614151867e02 introduced a regression which I think is pretty serious. I cannot load specific files that worked OK prior to this commit. Now I get a warning introduced by this commit ("Number of records from the header does not match the file size (perhaps the recording was not stopped before exiting). Inferring from the file size."), and the resulting file size is incorrect. I can load the file just fine before this change and with other tools such as pyedflib or biosig. Although there were some edits after this commit, this issue has not been resolved.
I hope that it really is just the tiny change I made - let's see what the CIs think.
=> [MRG] Fix calculation of samples to avoid incorrect file

doc/whats_new.rst, mne/viz/evoked.py
fixes #4839, see my comments there.
=> MRG: fix topo legend placement when `show_sensors=1`

doc/python_reference.rst, mne/__init__.py, mne/label.py, mne/tests/test_label.py
@agramfort @massich @mathurinm 
This PR add the new function to produce random parcellation of the cortex. It grows a number (input parameter) of random not intersecting cortical regions which cover the whole surface. 
Here is example of use (you should change annotation file names):
```
from pyface.qt import QtGui, QtCore
%matplotlib qt
import copy
import mne
from surfer import Brain
subject_dir = sample.data_path() + '/subjects'
n_parcel = 150
hemis = [0, 1]
labels = mne.random_parcellation(subject, n_parcel, hemis, subject_dir, surface='white')
annot_fname_lh = '/user/kmaksyme/home/tmp/lh.test.annot'
mne.label.write_labels_to_annot(labels,annot_fname=annot_fname_lh,hemi='lh',overwrite=True)
annot_fname_rh = …
```
=> [MRG+1] Add function for random parcellation

examples/inverse/plot_custom_inverse_solver.py, mne/inverse_sparse/_gamma_map.py, mne/inverse_sparse/mxne_inverse.py
This PR contains two small changes. If you don't feel it's worth merging them I wouldn't blame you, but I figured I'd at least give you a heads up.
1. The [example for custom solvers](https://martinos.org/mne/stable/auto_examples/inverse/plot_custom_inverse_solver.html#sphx-glr-auto-examples-inverse-plot-custom-inverse-solver-py) contains a chunk of code around [line 100 - 104](https://github.com/mne-tools/mne-python/blob/239c83dfe0686084d1c96c945579dc8cc10e895c/examples/inverse/plot_custom_inverse_solver.py#L100-L103) with an if statement that will never be executed because the immediately previous call to [_check_loose_forward](https://github.com/mne-tools/mne-python/blob/239c83dfe0686084d1c96c945579dc8cc10e895c/mne/minimum_norm/inverse.py#L735-L765) handles the case the if statement …
=> Remove unused code path in custom solver

mne/viz/ica.py
Sometimes the function plot_ica_scores shows white bar and seems to ignore the `edgecolor='k'`option, resulting in scores not showing up (for example in the online tutorial https://martinos.org/mne/dev/auto_tutorials/plot_ica_from_raw.html, after 2.) ).
This is a simple workaround, where the color of the bar is now gray by default.
=> Workaround for a display bug in plot_ica_scores

mne/io/meas_info.py
Regarding issue #4984 .
Now it's possible to call:
```
raw.plot()
```
after exporting the data from FT in this way: http://www.fieldtriptoolbox.org/development/integrate_with_mne.
=> in io.read_meas_info we prevent highpass and lowpass from being nans

mne/gui/_file_traits.py
Small fix that should not conflict with #4971: Show appropriate error message for previously uncaught exception, for fiff files with measurement info but without digitizer data (e.g. `MNE-sample-data/MEG/sample/ernoise_raw.fif`)
=> coreg-GUI:  catch fiff files without digitizer info

mne/viz/tests/test_topomap.py, mne/viz/topomap.py
plot_topomap currently cleans the channel names, but fails to clean info['bads'], so an exception is raised when info['bads'] is non empty.
=> [MRG+1] topomap - clean channel names in info['bads'] 

mne/viz/tests/test_raw.py, mne/viz/utils.py
Also changes the default display from `BAD_` to `"BAD_"` for typing. The interaction was also weird for me when testing, this fixes it. Load any raw file and hit "a" to interactively test.
=> MRG: Annotations for MPL2.2

mne/commands/mne_freeview_bem_surfaces.py
While calling from command line `mne freeviewer_bem_surfaces` and given wrong path or no arguments, I receive error:
```
AttributeError: 'NoneType' object has no attribute 'startswith'
```
which is not very informative. This PR aims to deal with that by checking if path was specified and whether it exists.
=> Checking paths in mne_freeviewer_bem_surfaces 

mne/io/edf/edf.py
Fixes the last remaining issue in #4760.
=> [MRG] Add warning for EDF event outside the signal duration

mne/evoked.py, mne/minimum_norm/inverse.py
Currently on `master` this is what I get for an `evoked.__repr__`:
```
<Evoked  |  comment : 'vis/learn/faces/incorrect', kind : standard_error, time : [-0.100000, 0.748000], n_epochs : 22, n_channels x n_times : 306 x 213, ~7.5 MB>
```
This is too long to be displayed even on a fairly wide terminal, making it hard to find relevant information when, especially when looking at multiple `evoked` instances. This PR changes it to a more compact representation (while removing the "number of time points" information, which did not seem that useful given that the time window is already given, and it can be obtained with `evoked.data.shape[1]`):
```
<Evoked  |  'vis/learn/faces/incorrect' (SEM, N=22), [-0.1, 0.748] sec, 306 ch, ~7.5 MB>
```
I also tucked in an unrelated `_safe_svd` fix, might as …
=> MRG: More compact evoked repr

doc/whats_new.rst, examples/inverse/plot_time_frequency_mixed_norm_inverse.py, mne/inverse_sparse/mxne_inverse.py, mne/inverse_sparse/mxne_optim.py, mne/inverse_sparse/tests/test_mxne_inverse.py, mne/inverse_sparse/tests/test_mxne_optim.py
I've implemented the closed-form solution for the epsilon_inf norm (dual norm of L21 + L1), which allows us to compute alpha_max for TFMxNE in closed-form, as well as a tight scaling of residuals (current solution is only tight at optimum).
I have added one test, `test_dgapL21l1`, which currently fails as a negative dgap is returned. However, when I pick `l2_ratio = 0.5`, it passes. 
This probably means I have messed up between `alpha_space` and `alpha_time` at some point, or between `l2_ratio` and `1. - l2_ratio`
@agramfort @joewalter @yousrabk
=> [MRG] Tighter dual scaling in TFMxNE

mne/coreg.py, mne/io/meas_info.py, mne/tests/test_coreg.py
Fixes a regression introduced in #4894 where we used `sample.data_path()`, causing too much disk space usage (causing failures like this: https://travis-ci.org/mne-tools/mne-python/jobs/357552658). Also changed to fake `fs_home` as `testing.data_path()` so FreeSurfer is no longer required.
@christianbrodbeck can you take a quick look when you get a chance?
=> FIX: Use `testing` not `sample`, dont require fsaverage

doc/documentation.rst, doc/python_reference.rst, doc/whats_new.rst, examples/inverse/plot_dics_beamformer.py, examples/inverse/plot_dics_source_power.py, examples/inverse/plot_tf_dics.py, examples/time_frequency/plot_compute_csd.py, mne/beamformer/_dics.py, mne/beamformer/tests/test_dics.py, mne/time_frequency/__init__.py, mne/time_frequency/csd.py, mne/time_frequency/tests/test_csd.py, mne/viz/__init__.py, mne/viz/misc.py, mne/viz/tests/test_misc.py
This overhaul of the CSD functionality was started in #4797, but is now split off into it's own PR. In this PR, the DICS code has been left untouched, except for some minor modifications to use the new CSD objects.
The CrossSpectralDensity object has been extended. It can now contain multiple CSD matrices. Since it is a very common use case to want to compute the CSD for multiple frequency bands, the intended workflow is now:
- Compute the CSD for all desired frequencies once
- Save it to avoid recomputing this beast
- Use `csd.mean` to average across frequency bands at will
- Feed the CSD object into `dics_source_power` to obtain an STC with the desired frequency bands as the "time" dimension.
`CrossSpectralDensity` objects have a `save` method and there is now a `read_csd` function.
The …
=> [WIP] Refactor and extend cross-spectral density (CSD) functionality

mne/time_frequency/csd.py, mne/time_frequency/tests/test_csd.py
Small bug that was introduced by the refactoring of the CSD code. When calling `csd_fourier`, `csd_multitaper` or `csd_morlet` the `ch_names` field of the resulting `CrossSpectralDensity` object was not properly set. It slipped through the unit tests at the time.
=> [MRG] Fix setting CSD ch_names

doc/whats_new.rst, mne/inverse_sparse/mxne_inverse.py, mne/inverse_sparse/mxne_optim.py, mne/inverse_sparse/tests/test_mxne_optim.py, mne/time_frequency/stft.py
This is an implementation of multiple time frequency dictionary usage in TFMxNE inverse solver.
The most important addition is the creation of `_multidict_STFT_norm` which holds parameters relative to each dictionary (an array `n_steps`, an array `n_freqs`) and splits Z everytime a TF norm computation is needed. 
The parameter `shape` disappears everywhere.
I have also modified _Phi and _PhiT to handle multidict. Should I preserve retrocompatibility and handle int for `tstep` and `wsize` in these private classes ?  
I will add a test and an example on somato data (of MNE, not MIND) where hopefully there are transient bursts and multidict looks good.
Starting from @joewalter code helped me a lot so kudos to him.
@agramfort @yousrabk
=> [MRG] implementation of multidictionary for TFMxNE

environment.yml
It turns out `git+` URLs require `git`, which is not something we want (esp. for Windows users).
This is also quite a bit faster because it only pulls the relevant commit code, rather than `git clone`ing the repo then checking out a commit. Some of those `enthought` repos were big.
=> MRG: Dont require git for env

examples/visualization/plot_channel_epochs_image.py, examples/visualization/plot_roi_erpimage_by_rt.py, mne/evoked.py, mne/viz/epochs.py, mne/viz/evoked.py, mne/viz/utils.py, tutorials/plot_stats_spatio_temporal_cluster_sensors.py
1. @dengemann suggested in #2897 we use the axis divider pattern instead of plt.subplot calls. I've refactored epochs.plot_image accordingly. Besides for slightly neater code, the main benefit is that this should in principle allow 3-axis epochs image plots in a topographical layout.
2. The very appealing example for the pattern in the tutorials has been broken for a few versions now because someone forgot to turn off `show`:
http://martinos.org/mne/stable/auto_tutorials/plot_stats_spatio_temporal_cluster_sensors.html
http://martinos.org/mne/dev/auto_tutorials/plot_stats_spatio_temporal_cluster_sensors.html
This fixes it.
3. Also working on the "significant clusters" terminology ...
4. Also the example can be simplified substantially now thanks to plot_compare_evokeds
=> MRG: Axis divider in a few places

mne/viz/evoked.py, mne/viz/tests/test_evoked.py
A tiny, subtle bug in evoked.plot_image I introduced: if the extent is given as floats, the ticklabels can be wrong.
=> WIP: [MINOR, BUG] Extent bug in evoked_image

doc/manual/cookbook.rst, doc/whats_new.rst, mne/filter.py, mne/io/base.py, mne/viz/epochs.py, mne/viz/evoked.py, mne/viz/ica.py, mne/viz/misc.py, mne/viz/raw.py, mne/viz/topo.py, tutorials/plot_artifacts_correction_filtering.py, tutorials/plot_artifacts_correction_ica.py, tutorials/plot_artifacts_correction_rejection.py, tutorials/plot_artifacts_correction_ssp.py, tutorials/plot_artifacts_detection.py, tutorials/plot_background_filtering.py, tutorials/plot_visualize_raw.py, tutorials/plot_whitened.py
Closes #4534.
This PR:
- Unifies axis labeling to "Time (s)" form from others like "time [sec]". Turns out there were a lot of places we already used the former standard so the changeset wasn't so bad.
- Unifies handling of unit naming in ICA property plots to fit with e.g. `raw.plot_psd()`.
- Unifies `sphx_glr_*`-based linking rather than custom `tut_` ones to make things more standard.
=> MRG: Unify axis labeling

doc/whats_new.rst, mne/cov.py, mne/defaults.py, mne/simulation/raw.py, mne/simulation/tests/test_raw.py, mne/tests/test_cov.py
Modified `make_ad_hoc_cov` so that it accepts a dictionary of standard deviations as input.
Related to issue #5058
=> MRG: Modify make_ad_hoc_cov to accept dict as input

mne/evoked.py
Including the hint to the appropriate file ending to the docstring of save definition. Matches to https://github.com/stfnrpplngr/mne-python/blob/master/mne/epochs.py
=> Update docstring for save definition in evoked.py

mne/io/edf/edf.py
This PR suggests to exclude all identically named channels, if any, when the `exclude` option is used in `read_raw_edf`.
This would be useful for reading all EDF files in the CHB-MIT EEG database where some EDFs files contain dummy channels called "-".
https://github.com/mne-tools/mne-python/issues/5072#issuecomment-378006689
Closes #5072.
=> MRG: Add all channels named 'A' to exclusion list if exclude = ['A']

doc/whats_new.rst, mne/viz/evoked.py, mne/viz/raw.py, mne/viz/tests/test_raw.py
Closes #5046.
Using the snippet from #5046:
```
import mne
fname = data_path + "/MEG/sample/sample_audvis_raw.fif"
raw = mne.io.read_raw_fif(fname)
picks = mne.pick_types(raw.info, meg=True, eeg=False, stim=False)
raw.plot_psd(picks=picks, average=False)
```
We now get this instead of an error:
=> MRG: Fix picks for raw.plot_psd

mne/tests/test_utils.py, mne/utils.py
Closes #4796.
I can't reproduce this locally. Maybe it is NumPy version dependent. We'll see if the CIs agree there is no bug :)
=> MRG: Fix hash

mne/tests/test_utils.py
Closes #4192.
Not really a critical test but it takes almost no time, so why not.
=> MRG: Add test

environment.yml
Following discussion in #5012, Anaconda should be caught up to `pip` in terms of Qt5 and VTK. The CIs should let us know!
=> ENH: Use VTK and Qt from Anaconda [circle full]

tutorials/plot_forward.py
simple typo which broke the link in the online doc
=> fix typo in doc

mne/channels/channels.py, mne/channels/interpolation.py, mne/channels/tests/test_interpolation.py, mne/decoding/csp.py, mne/io/ctf/tests/test_ctf.py, mne/io/fiff/tests/test_raw_fiff.py, mne/io/reference.py, mne/io/tests/test_reference.py, mne/preprocessing/tests/test_ica.py, mne/realtime/tests/test_fieldtrip_client.py, mne/time_frequency/tests/test_multitaper.py, mne/viz/evoked.py, mne/viz/misc.py, mne/viz/tests/test_ica.py, mne/viz/tests/test_topomap.py, tutorials/plot_visualize_evoked.py
Looking through our Travis logs it's annoying to scroll back through pages of warnings. This should get rid of them at least on the modern `environment.yml` builds.
=> MRG: Capture a bunch of warnings

mne/beamformer/_lcmv.py, mne/beamformer/tests/test_lcmv.py
I wanted to see how hard it would be to do #5067, and based on the nice factoring of code done by @britta-wstnr and @wmvanvliet it was only +59/-21 with a test and documentation!
It's still up for discussion if this makes sense, but I think that any time we allow `pick_ori=None` to mean "pool orientations by norm", we should also (eventually) allow `pick_ori='vector'`.
Closes #5067.
=> MRG+1: Add vector output for LCMV

doc/conf.py, mne/beamformer/_lcmv.py, mne/decoding/base.py, mne/decoding/csp.py, mne/decoding/ems.py, mne/decoding/receptive_field.py, mne/decoding/search_light.py, mne/decoding/transformer.py, mne/io/base.py, mne/preprocessing/ica.py, mne/preprocessing/xdawn.py, mne/utils.py
Closes #5118
So far it looks locally like the double-backtics are no longer necessary on `var_` names in `Attributes` sections. We'll see if CircleCI agrees.
I still need to fix the CSS width problem.
=> MRG: Remove double-backticks

mne/beamformer/_compute_beamformer.py, mne/beamformer/_dics.py, mne/beamformer/_lcmv.py, mne/beamformer/_rap_music.py, mne/beamformer/tests/test_lcmv.py
First iteration for https://github.com/mne-tools/mne-python/issues/5109 to unify ``lcmv`` and ``dics`` (and ``rap_music``).
This PR moves shared helper functions from ``lcmv`` to ``_compute_beamformer``.
Still to do in a following PR: refactor shared beamformer computation code and store it in ``_compute_beamformer`` as well.
cc @larsoner
=> Refactoring beamformer code

mne/epochs.py
Updates `epochs` repr to be hopefully a bit nicer.
`master`:
```
<Epochs  |  n_events : 320 (good & bad), tmin : -0.19979521315838786 (s), tmax : 0.49948803289596966 (s), baseline : (None, 0), ~3.7 MB, data not loaded,
'auditory/left': 72, 'auditory/right': 73, 'button': 16, 'smiley': 15, 'visual/left': 73, 'visual/right': 71>
<Epochs  |  n_events : 72 (good & bad), tmin : -0.19979521315838786 (s), tmax : 0.49948803289596966 (s), baseline : (None, 0), ~3.7 MB, data not loaded>
```
On this PR:
```
<Epochs  |   320 events (good & bad), -0.199795 - 0.499488 sec, baseline [None, 0], ~3.7 MB, data not loaded,
'auditory/left': 72
'auditory/right': 73
'button': 16
'smiley': 15
'visual/left': 73
'visual/right': 71>
<Epochs  |   72 events (good & bad), -0.199795 - 0.499488 sec, baseline [None, 0], …
```
=> MRG+1: Better epochs repr

mne/time_frequency/csd.py, mne/time_frequency/tests/test_csd.py
The `csd_morlet` and `csd_array_morlet` functions mistakingly have `None` as a default value for the `frequencies` parameter. This parameter is not optional, leaving it at `None` will raise an error.
=> MRG+1: The frequencies parameter of csd_morlet is not optional

doc/whats_new.rst, mne/preprocessing/ecg.py, mne/preprocessing/tests/test_ecg.py, mne/preprocessing/tests/test_xdawn.py, mne/preprocessing/xdawn.py, mne/viz/misc.py
Fixes:
1. bug with Xdawn where non-data-channels broke things
2. `create_ecg_epochs` where `picks=None` plus `keep_ecg=False` would not work.
3. minor PEP8 problem with `mne/viz/misc.py`
4. updates some tests to `pytest` (someday we will eliminate `nose`!)
=> MRG: Fix minor bugs with Xdawn and create_ecg_epochs

doc/whats_new.rst, mne/evoked.py, mne/tests/test_source_estimate.py
The `.get_peak()` method of `SourceEstimate` and `VolumeSourceEstimate` objects failed if there is only a single time point. This is for example common when computing DICS power maps.
=> [MRG] Fix SourceEstimate.get_peak() method

mne/preprocessing/ssp.py, mne/preprocessing/tests/test_ssp.py
Closes #5124 
When computing ssp projection operators, include the meg_ref channels for data objects that include compensation channels (i.e CTF data), otherwise creating epochs raises an exception.
=> FIX: CTF Projector comp

mne/fixes.py, mne/preprocessing/ctps_.py
@agramfort @larsoner @pravsripad : as requested the numerical accuracy is now ensured by using scipy.misc.logsumexp. I have separated this pull request from the ica_start_stop issue as this is a different problem here.
=> ENH: improving CTPS precision by using scipy.misc.logsumexp

doc/whats_new.rst, mne/bem.py
Using `mne flash_bem --noflash30` which eventually calls `convert_flash_mris` fails because the `glob.glob` list result is not correctly inserted in the `cmd` list. This fixes it.
I don't see a way to add a test because this relies on `freesurfer` calls.
=> MRG: Fix --noflash30

doc/whats_new.rst, mne/io/base.py, mne/minimum_norm/_eloreta.py, mne/minimum_norm/tests/test_inverse.py, mne/minimum_norm/time_frequency.py
Fixes 3 minor problems:
1. eLORETA had threshold issues if `inv` was saved and loaded (threshes were for `float64` but I/O roundtrip makes them `float32`; also neg eigenvalues should be treated as zero)
2. `base.py` change should fix the issue brought up on the mailing list about coercing a filename `None` to unicode
3. Use `hann` instead of `hanning` as it's deprecated in `scipy`
=> MRG: Minor fixes

mne/minimum_norm/_eloreta.py, mne/minimum_norm/tests/test_inverse.py
One more corner-case fix for eLORETA on sphere model after saving `inv` to disk. Pretty straightforward (needed `single`-type `rcond` in two places rather than one), now with assertion of zero localization bias.
I'll merge and backport once the CIs come back happy.
=> MRG: Fix eLORETA sphere model (more)

mne/io/fiff/tests/test_raw_fiff.py
I think we had a numerical-precision-unlucky bug show up on AppVeyor, this will hopefully fix it.
=> MRG: Fix appveyor test

mne/externals/pymatreader/__init__.py, mne/externals/pymatreader/pymatreader.py
As agreed with @larsoner, this PR adds the pymatreader package. It is going to be used by EEGLab and FieldTrip reader functions in the future.
=> Add pymatreader as external package

mne/io/meas_info.py, mne/io/tests/test_meas_info.py
Tentative solution to #5200.
@larsoner this seems to me the less invasive way to proceed. 
I was wondering, which other fields of the info structure should be treated like this?
`comps`, `dig`, `events`, `proc_history`, `meas_data` are lists as well but I'm not sure which should be allowed to be different in the infos to be merged.
=> WIP: Avoid info['hpi_meas'] and info['hpi_results'] duplication in _merge_info

doc/whats_new.rst, mne/minimum_norm/tests/test_inverse.py, mne/source_estimate.py
This is the change I had to make to get vector volume source estimates. Should add a test.
CC: @agramfort @larsoner
=> [MRG] VolSourceEstimate:  allow vector data

doc/whats_new.rst, mne/io/fiff/tests/test_raw_fiff.py, mne/io/proj.py, mne/tests/test_cov.py, mne/tests/test_proj.py, mne/tests/test_source_estimate.py
Whenever `inst.apply_proj()` was called it would add an average EEG ref proj even if one was not present. This fixes it. We'll see if it breaks any test -- if so it probably means we need some `set_eeg_reference`.
Also allows negative indexing for projectors in `del_proj`.
Ready for merge. Tests pass locally so the CIs should also be happy.
=> MRG: Fix bug with apply_proj

environment.yml
6.0.0 for traitsui and pyface are out, let's see if this works. Also trying traits 4.6.0, but that might be too old and I'll have to revert that commit.
=> MRG: Use stable versions

mne/filter.py, mne/tests/test_filter.py
This PR is part of a bunch of issues around the reporting of filters, see #5226 .
Addressing the comment by @larsoner:
> mne.filter.create_filter will create the filter and give these log messages. You can pass it a dummy data array. Actually we should proably make data=None a possibility, meaning "skip length checks/warnings".
=> allow data=None in filter.create_filter

doc/whats_new.rst, mne/forward/_make_forward.py, mne/simulation/raw.py, mne/simulation/tests/test_raw.py
Takes care of parts of #5058, namely point 3 (implemented) and point 2 (just document an equivalent way to do it for advanced users).
Also fixes a small bug where a sphere model with no radius (only origin) would cause a problem because `bem.radius is None`.
@ngayraud can you see if this simplifies your use case?
=> MRG: Allow passing a precomputed forward

examples/inverse/plot_vector_mne_solution.py, mne/source_estimate.py, mne/viz/_3d.py, mne/viz/tests/test_3d.py
Closes #5236.
Fixes some errant changes in `colormap` defaults. Should be backported.
=> MRG: Fix vector colormap

mne/viz/epochs.py, mne/viz/tests/test_epochs.py
closes #5240
Eventually, `epochs.plot_image` should be able to handle y axis inversion for the ERP, but I don't have the capacity to handle it right now.
=> [MRG, Minor] Disallow invert_y input to epochs.plot_image

mne/stats/parametric.py
The function f_mway_rm() has a parameter alpha, which is not needed or used by the function. This fix removes the parameter.
=> MRG: Deprecate unneeded and unused alpha parameter from f_mway_rm().

doc/python_reference.rst, doc/whats_new.rst, mne/evoked.py, mne/viz/evoked.py, mne/viz/tests/test_evoked.py, tutorials/plot_stats_cluster_erp.py
And the last one for `evoked.plot_image` from #5170
Adds a group_by option to evoked.plot_image that allows feeding a dict to `axes`. I.e., for making a channel selection with `make_1020_selection`.
=> MRG: group_by to evoked.plot_image

doc/whats_new.rst, examples/realtime/ftclient_rt_average.py, examples/realtime/ftclient_rt_compute_psd.py, examples/realtime/plot_compute_rt_decoder.py, examples/realtime/rt_feedback_client.py, examples/realtime/rt_feedback_server.py, mne/epochs.py, mne/realtime/epochs.py, mne/realtime/fieldtrip_client.py, mne/realtime/mockclient.py, mne/realtime/tests/test_fieldtrip_client.py, mne/realtime/tests/test_mockclient.py
Fixes #5191: Make sure the epochs invariants hold  for ``RtEpochs``.
I'm not completely happy with the ``_get_data()`` method since it relies on the "online iteration and blocking" over epochs rather than just returning the data received so far (which I would prefer, but didn't implement for compability).  I had to move the check for the timeout since otherwise iteration is typically only possible once (depending on the ``isi_max``).
The inherited implementation of _get_item was broken (but is called by ``save``).
=> MRG: Fix RtEpochs to support saving

mne/io/edf/edf.py
Improves style of one bit of code, and adds an additional check that turns a downstream error (cals equal zero) into a warning so you can still read the file. This was encountered on a SMA EEG file converted to EDF format using EEGLAB+BioSig. No test because this is such a weird corner case.
@cbrnr do you have time to look?
=> MRG: Better EDF range checks

mne/io/brainvision/brainvision.py
=> [MRG] Raise NotImplementedError for vectorized Brainvision ASCII data file

doc/whats_new.rst, mne/io/brainvision/brainvision.py, mne/io/brainvision/tests/test_brainvision.py
=> Fixes #5284: converts 1-indexed BrainVision offsets into 0-indexed mne offsets

mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py, mne/utils.py
closes #5265.
The problem arises because the ica object inherits the `info` of the object used to fit it with supplied 'picks' applied. however to avoid making a copy of time domain data the picks are never applied to the supplied object. This causes a discrepancy between the channels in `ica.info` and `raw.info` (or `epoch.info`) and the check fails.
I modified the `_check_compensation_grade` to accept channel names so the infos of both objects are mapped to the same channels before computing `compensation_grade`.
one case not tested is a ctf/eeg test where compensation can be applied. Are there any datasets like that which we could include in the test data?
=> Fix check compensation on ica with EEG

doc/whats_new.rst, mne/minimum_norm/inverse.py, mne/minimum_norm/tests/test_snr.py, mne/viz/evoked.py
Fixes two bugs:
1. `mne.minimum_norm.estimate_snr` was not properly utilizing the effective number of channels, which made the inverse-based SNR estimates bad for data processed with SSS.
2. `mne.viz.plot_snr_estimate` was not subtracting one from the GFP, doing so makes it match MNE-C's output. I imagine this is done to make it relate more readily to the SNR estimated from the data, but maybe we should add one to it instead?
On `master` this is what sample and some random SSS'ed data I have look like:
And on this PR:
And in MNE-C:
=> MRG: Fix SNR estimation and plotting

doc/python_reference.rst, doc/whats_new.rst, examples/inverse/plot_lcmv_beamformer_volume.py, mne/beamformer/_dics.py, mne/beamformer/_lcmv.py, mne/minimum_norm/inverse.py, mne/source_estimate.py, mne/source_space.py, mne/tests/test_source_estimate.py, mne/tests/test_source_space.py
closes #5224 
to debug
```
import mne
from mne import setup_volume_source_space
from mne import make_forward_solution
from mne.minimum_norm import make_inverse_operator, apply_inverse
from nilearn.plotting import plot_stat_map
from nilearn.image import index_img
data_dir = op.join(data_path, 'MEG', subject)
bem_dir = op.join(subjects_dir, subject, 'bem')
fname_aseg = op.join(subjects_dir, subject, 'mri', 'aseg.mgz')
fname_model = op.join(bem_dir, '%s-5120-bem.fif' % subject)
fname_bem = op.join(bem_dir, '%s-5120-bem-sol.fif' % subject)
fname_evoked = data_dir + '/sample_audvis-ave.fif'
fname_trans = data_dir + …
```
=> MRG : better detect type of src for making an stc

mne/io/brainvision/brainvision.py, mne/io/brainvision/tests/data/test_nV.vhdr, mne/io/brainvision/tests/test_brainvision.py
The BrainVision export in Analyser exports EEG data in nanovolts.
Currently, these EEG channels get interpreted as MISC channels so the import fails. This PR adds nV as possible unit.
=> Add nanovolts to allowed units in brainvision files

doc/whats_new.rst, mne/channels/interpolation.py, mne/channels/tests/test_interpolation.py
attempt to closes #5292
@larsoner @bloyl I need you help here.
to replicate the error run:
`pytest mne/channels/tests/test_interpolation.py -k test_interpolation_ctf_comp`
basically what happens is that doing `info_to = pick_info(inst.info, picks_bad)` here https://github.com/mne-tools/mne-python/blob/master/mne/channels/interpolation.py#L190
breaks as it wants to pick the info for just one data channel without the compensation channels.
help very much welcome.
cc @Heneark
=> attempt to fix interpolation of bad MEG sensors with applied compensation

doc/whats_new.rst, mne/io/meas_info.py, mne/io/tests/test_meas_info.py
Closes #5320.
@ckiefer0 can you see if this fixes your problem?
@agramfort in the long run we should get rid of `info['buffer_size_sec']`, it is really a property of the Raw instance and not stored in `FIFFB_MEAS_INFO` block anyway.
=> MRG: Fix add_channels behavior

mne/channels/channels.py, mne/io/reference.py
Apparently, we never really did a proper deprecation cycle for the `projection=True` argument. We mention it in the docstring, but didn't issue a warning. The default argument has changed to `False` in 0.16, so I guess the scaffolding can be removed.
=> Remove unused code after deprecation in set_eeg_reference

doc/whats_new.rst, mne/viz/evoked.py, mne/viz/tests/test_topo.py
evoked.plot_joint is a figure-level function. There is no easy way around this. But currently, we make it unnecessarily hard to embed if with other figures, by checking for axes keywords for the dict args. This removes that check, and allows manually forwarding axes. Thus, composite images are possible.
However, this is rather complicated to use ...
Not sure about it to be honest. I use it locally, but it might not be useful for others due to the complexity.
=> MRG allow passing axes to evoked.plot_joint

doc/whats_new.rst, mne/io/array/array.py, mne/io/artemis123/artemis123.py, mne/io/base.py, mne/io/brainvision/brainvision.py, mne/io/bti/bti.py, mne/io/cnt/cnt.py, mne/io/ctf/ctf.py, mne/io/ctf/tests/test_ctf.py, mne/io/edf/edf.py, mne/io/eeglab/eeglab.py, mne/io/egi/egi.py, mne/io/egi/egimff.py, mne/io/eximia/eximia.py, mne/io/fiff/raw.py, mne/io/fiff/tests/test_raw_fiff.py, mne/io/kit/kit.py, mne/io/meas_info.py, mne/io/nicolet/nicolet.py, mne/io/tests/test_meas_info.py, mne/io/tests/test_raw.py, mne/simulation/tests/test_raw.py, mne/tests/test_chpi.py, mne/tests/test_epochs.py, mne/tests/test_evoked.py
This bugfix moves `info['buffer_size_sec']` to `raw.buffer_size_sec`:
1. It is not actually a property of meas info so it's a misnomer
2. There is no FIFF constant for it so our nice info<->FIFF relationship is broken
3. Cleans up our code
4. Should help prevent problems like #5287
I think this is a bigfix, and the hard rename should have limited impact on end-users -- I don't expect them to have used this.
=> MRG: Rename buffer_size_sec

mne/forward/forward.py, mne/forward/tests/test_make_forward.py
Using surface source spaces plus a discrete source space and going to surface orientation didn't work before, now it does.
=> MRG: Fix fwd with surf + discrete

doc/conf.py, mne/tests/test_utils.py, mne/utils.py, tutorials/plot_background_filtering.py
Fixes doc links when `verbose` decorator is used.
Closes #5290.
=> MRG: Fix linkcode

doc/whats_new.rst, mne/io/brainvision/brainvision.py, mne/io/brainvision/tests/data/test_old_layout_latin1_software_filter.vmrk, mne/io/brainvision/tests/data/testv2.vmrk, mne/io/brainvision/tests/test_brainvision.py, mne/io/meas_info.py
fixes #5357 
Note that I made some convenient changes to the test files that do not influence the other tests but allow us to test this new function without having to clutter more additional test files into `/tests/data`
=> read meas_date from BrainVision vmrk

mne/proj.py
Give `compute_proj_evoked` the same options as `compute_proj_epochs`. Test seems unnecessary because `None`, the backward-compatible new default, is already tested.
=> MRG: Add desc_prefix to compute_proj_evoked

doc/known_projects.inc, doc/whats_new.rst, mne/annotations.py, mne/externals/pymatreader/pymatreader.py, mne/io/eeglab/eeglab.py, mne/io/eeglab/tests/test_eeglab.py
I have changed the code to use `read_mat`. So far I noticed that I needed `uint16_codec` to be exposed to `read_mat`, which I added. Now all the `.mat` reading versions work. However, there are failures in the `.h5` versions of the files, indicating a likely problem with `read_mat`'s conversion.
@thht since the problems are with the `h5`-to-dict conversion, do you have time to take a quick look? It wasn't obvious from the traceback or `pymatreader` code what changes would be necessary to make it work.
=> MRG+1: Use read_mat for eeglab

mne/utils.py, mne/viz/evoked.py, mne/viz/tests/test_evoked.py
Trying to plot data with NaNs included can result in some pretty weird output. This raises a `ValueError` at a hopefully sufficiently early time point.
=> MRG Evoked plots should error nicely on NaN input

mne/beamformer/tests/test_lcmv.py, mne/io/proj.py, mne/tests/test_proj.py, mne/viz/tests/test_epochs.py
While working on #5409 I realized `test_lcmv.py` had a bug where it was projecting out three components from data with three channels. This seems like errant behavior that we should catch.
=> MRG: Do not allow projection of all components

doc/faq.rst
The FAQ page was not found by the search engine when looking for "FAQ", because it did not contain this abbreviation.
=> Added "FAQ" to the headline for SEO

doc/configure_git.rst
The command "cd mne-python" is listed twice but can only be executed once.
=> Removed redundant command in git guide.

mne/io/brainvision/tests/test_brainvision.py
Merging a PR after the warnings PR without re-running it led to errors on `master`. This should fix them.
=> FIX: Fix for BrainVision warnings

doc/whats_new.rst, mne/io/brainvision/brainvision.py, mne/io/brainvision/tests/test_brainvision.py
fixes #5420 
TL;DR: We now by default parse events that are stimuli `S###` or responses `R###`, covering the bulk of events in BrainVision files. All other events have to be specified using `event_id`.
-----------------------
The changes to the tests were much more minimal than I expected. Basically I:
1. added `'0  1': 1` to the `event_id` so that the *optic event* in our test files gets parsed (before this bugfix it was wrongly parsed by default)
2. added the `event_id` argument to a `read_raw_brainvision` call where previously the `event_id` was apparently forgotten.
Next to that, I noticed yet another bug that we did not know of before, look at this code:
https://github.com/mne-tools/mne-python/blob/62ecf9e482bf84a7f58c5fefff766336068f8bce/mne/io/brainvision/brainvision.py#L316-L332 …
=> Fix event parsing brainvision

doc/whats_new.rst, mne/cuda.py, mne/filter.py, mne/tests/test_filter.py
This PR, by using `np.fft.rfft` for filtering and resampling:
- Reduces memory slightly
- Should speed up filtering a little bit
- Fixes some minor bugs with `resample(..., window=<non-boxcar>)`
Only reason it's not MRG is that I am not on a CUDA machine currently so can't see if that passes (though it should). @jona-sassenhagen if you are on a CUDA machine can you run `pytest mne/tests/test_filter.py` and let me know if it passes for you?
=> MRG: Lower mem usage rfft

mne/stats/regression.py, mne/stats/tests/test_regression.py
Since .15, linear_regression_raw warns if a custom solver is passed. This can probably be removed for .17.
=> MINOR, WIP remove warning for custom solvers in rERP

doc/manual/cookbook.rst, doc/python_reference.rst, doc/whats_new.rst, examples/visualization/make_report.py, mne/report.py, mne/tests/test_report.py, mne/viz/_3d.py, mne/viz/raw.py
Closes #5237.
Also shifts our docs from `mne.report` namespace to the root namespace as `mne.Report` already lives there.
Copying the truncated testing raw file to desktop and doing:
```
import mne
report = mne.Report(raw_psd=True)
report.parse_folder('/Users/larsoner/Desktop')
report.save('/Users/larsoner/Desktop/report.html')
```
I get:
@jona-sassenhagen happy?
=> MRG: Add raw PSD to parse_folder

mne/io/brainvision/brainvision.py, mne/io/brainvision/tests/data/testv2.vmrk, mne/io/brainvision/tests/test_brainvision.py
fixes #5441 
- Now reading 'S###' as the format of BrainVision Recorder and '###' as the format of PyCorder.
- Adjusted docstrings and warning message
- In the warning message, the dropped markers are now printed as they are (i.e., no potentially crucial whitespace is being dropped)
To Do:
=> [MRG] fix brainvision markers

.circleci/config.yml, doc/advanced_setup.rst, doc/contributing.rst, doc/faq.rst, doc/install_mne_python.rst, environment.yml
1. Multiple users have complained about the Cython warnings. This should get rid of those.
2. I don't think we need to have the doc-building deps in there by default, since that's really a dev thing, and devs can easily install those deps. (Unit test stuff is still nice for users who submit bug reports.)
3. I think we can do PySurfer on standard `pip` instead of from `master` nowadays.
4. There were some tweaks and tips proposed in #5390 that are included here.
5. We have `Issue` templates on GitHub now, so no need to duplicate instructions in our own docs.
Closes #5390.
=> MRG: Fewer warnings during install

mne/io/kit/kit.py
updating the kit docstring to reflect that you can load the data with `stim=None` and no synthetic channel will be generated. this ability was already caked in, just making it explicit
=> update docstring for kit system

doc/whats_new.rst, mne/preprocessing/eog.py, mne/preprocessing/tests/test_eog.py
Found that find_eog_events() and thus create_eog_epochs() weren't detecting many EOG events, despite seeing them in data.  The function used on the backend - peak_finder() - can take a threshold as argument, added option for user to pass a threshold to the function.  Initial testing found better detection of blinks.  
Perhaps more necessary in EEG recordings.
=> [MRG+2] Added threshold option for find_eog_events() and create_eog_epochs()

doc/whats_new.rst, examples/decoding/plot_decoding_time_generalization_conditions.py, mne/decoding/search_light.py, mne/parallel.py, mne/stats/cluster_level.py, mne/tests/test_utils.py, mne/utils.py, tutorials/plot_sensors_decoding.py, tutorials/plot_stats_cluster_spatio_temporal.py
This PR fixes a problem with the ProgressBar during clustering where numbers can jump down in addition to going up. It does this by using one of two new modes:
1. "Easy" mode: if you do `parallel_func` without `array_split`, you can now do `parallel_func(..., total=10)` and it will automatically update as each dispatched job finishes.
2. Because "easy" mode won't be useful with `array_split` jobs, I added a mode to `ProgressBar` (along with helper `array_split_idx`) that uses memmapping to allow each job to write to a shared array when it finishes its work. Whenever a given pickled version of `ProgressBar` gets updated, it will `.sum()` this array and use this to update the progress to `stdout`, thereby ensuring monotonicaly increasing updates.
It also:
1. adds a `verbose_bool='auto'` to …
=> MRG: Improve ProgressBar in parallel processing

.circleci/config.yml, examples/visualization/plot_parcellation.py
Should make CircleCI green on `master` again.
We should really release a new PySurfer. But in the meantime, this should work.
=> MRG: CircleCI

README.rst, doc/advanced_setup.rst, doc/install_mne_python.rst, doc/known_projects.inc, doc/python_reference.rst, doc/whats_new.rst, mne/beamformer/_lcmv.py, mne/cuda.py, mne/decoding/transformer.py, mne/filter.py, mne/io/base.py, mne/preprocessing/ssp.py, mne/tests/test_docstring_parameters.py, mne/tests/test_filter.py, mne/utils.py, setup.cfg
It turns out using `cupy`:
1. Simplifies things: one module to install (cupy) instead of two (pycuda, skcuda)
2. NumPy-like operations requires less branching (see +/- of equivalent-output code of this PR: +69, -142)
3. Is slightly faster (10%) in filtering/resampling than old code
4. Is more future compatible (e.g., using for `ReceptiveField` should be easier)
So I think in this release we should probably support just `cupy`. I don't think the burden is so high on users, as it was very easy to install on my system (easier than `pycuda` for example). I don't think it's a great idea to support both for a release because it will be a lot more work and complications in our code base, but we can do it if absolutely necessary.
Todo:
Closes #5439.
=> MRG: Use cupy instead of pycuda+skcuda

examples/time_frequency/plot_time_frequency_simulated.py
We should probably show the original simulated data time series before showing a bunch of TFRs.
=> MRG: Add time series to example

mne/minimum_norm/tests/test_inverse.py, setup.cfg
pytest 3.8 is more sensitive about warnings. This should fix them (the new ignores are due to imported / bundled libs).
=> FIX: Pytest 3.8 fixes

doc/whats_new.rst, mne/epochs.py, mne/tests/test_epochs.py
Fixes #5495.
In `mne.concatenate_epochs()`, when adding an offset to each iteration of epochs, don't update the offset with itself, as this leads to an overflow with large numbers of epochs.
=> Prevent overflow in concatenate epochs

doc/whats_new.rst, mne/report.py
When adding custom figures with `mne.Report.add_slider_to_section`, the `section` parameter is erroneously used in the sidebar to refer to the image. This should be the `title` parameter.
=> Fix title of sliders added to Report

doc/whats_new.rst, mne/bem.py, mne/epochs.py, mne/externals/decorator.py, mne/forward/_compute_forward.py, mne/forward/_field_interpolation.py, mne/forward/_make_forward.py, mne/io/constants.py, mne/io/ctf/tests/test_ctf.py, mne/io/fiff/tests/test_raw_fiff.py, mne/io/tag.py, mne/io/tests/test_constants.py, mne/io/write.py, mne/preprocessing/maxwell.py, mne/utils.py
This test should pass.
@agramfort look at `XXX` in the code to see the inconsistencies identified. I will email the MEGIN folks about this, and open a PR to `fiff-constants` to fix them.
WIP until we can make some or all of the `XXX` below go away.
=> MRG: Test constant consistency

doc/whats_new.rst, mne/io/base.py, mne/io/fiff/tests/test_raw_fiff.py
Fixes https://github.com/mne-tools/mne-bids/issues/17
This adds `split_naming` arg to the save method to make BIDS-compatible files
=> [MRG] ADD split_naming arg to save to make BIDS-compatible files

doc/python_reference.rst, doc/whats_new.rst, mne/__init__.py, mne/report.py, mne/tests/test_report.py
This allows you to save `mne.Report` objects in such a way that they can be read back later. This in turn allows you to incrementally add figures to a `Report` object across scripts.
The `mne.open_report` function either reads a `Report` if the file exists, or creates a new one if it doesn't. This mimics the behavior of the build-in Python `open` function. You can use it
like this:
report = mne.open_report('report.h5')
report.add_figures_to_section(...)
report.save('report.html')  # by default, it saves the report back to 'report.h5'
You can also use it as a context manager:
with mne.open_report('report.h5') as report:
report.add_figures_to_section(...)
closes #5501
=> [MRG] Add open/save to HDF5 ability to mne.Report

doc/whats_new.rst, examples/realtime/ftclient_rt_average.py, mne/epochs.py, mne/realtime/client.py, mne/realtime/epochs.py, mne/realtime/fieldtrip_client.py, mne/realtime/tests/test_fieldtrip_client.py, mne/realtime/tests/test_mockclient.py
Fixes #5449 and fixes #5450.
* Initializes ``self._current`` in ``Epochs``. I also added some notes that the iteration state for an ``Epochs`` object is shared between the different methods (something I stumbled over a while ago).
* remove call no non-existing ``stop`` method of ``Thread`` (there do not seem to be tests or examples that use ``RtClient``!?)
* while at it, I added a verbose decorator to ``RtEpochs.next()`` to be able to turn off the "Waiting for epoch i" messages
=> MRG: Initialize self._current in Epochs

doc/whats_new.rst, mne/gui/_coreg_gui.py
Fixes #5491 
The dialog box asking to save the fiducials file didn't open when trying to save a -trans file with a scaled MRI, which caused the saving procedure to fail. This fixes the problem.
=> FIX: fix save fiducials in mne coreg with scaled MRI (#5491)

mne/epochs.py, mne/tests/test_epochs.py
This PR adds the dtype of the `events` array to the error message in `Epochs`. This is meant to make the error message a bit clearer when `events` is not actually an array. See #4936 for the case where `events` is an array when using `mne.find_events`, but becomes a tuple if `mne.find_events` is blindly replaced by `mne.annotations.events_from_annotations`.
=> [MRG+2] adding events dtype to Epochs error message

mne/gui/_backend.py
This fixes the case where no backend is imported by `pyface`. Currently it later tries to call `warning(...)` when `warning is None`. There is no good way to test for this in the test suite that I can think of.
=> MRG: Fix backend warning

examples/inverse/plot_lcmv_beamformer_volume.py, mne/source_estimate.py, mne/viz/_3d.py, mne/viz/tests/test_3d.py
This does the refactoring to make `_limits_to_control_points` handle one- and two-sided colormaps more gracefully. Should wait until #5329 is in, then some minor tweaks to the vol plotter will be necessary. But at least with this commit I can now do:
```
import mne
subjects_dir = data_path + '/subjects'
if not op.isfile('temp-lh.stc'):
evoked = mne.read_evokeds(data_path + '/MEG/sample/sample_audvis-ave.fif',
'Left Auditory', baseline=(None, 0))
inv = mne.minimum_norm.read_inverse_operator(
data_path + '/MEG/sample/sample_audvis-meg-oct-6-meg-fixed-inv.fif')
mne.minimum_norm.apply_inverse(evoked, inv).save('temp')
stc = mne.read_source_estimate('temp')
stc.plot('sample', subjects_dir=subjects_dir, colormap='coolwarm', …
```
=> [MRG+1] Improve support for divergent colormaps

mne/bem.py
When symlinking BEM surfaces to watershed or flash results, relative paths should be used instead of absolute ones.
The way to test is try running `mne watershed_bem` on some subject and see that within the `bem` directory `*.surf` symlinks to `watershed/*` as opposed to `/whatever/annoying/full/path/subject/bem/watershed/*`.
=> MRG: Use relative paths for BEM surfaces

mne/viz/utils.py
avoid a crash observed when running #5548
```
import mne
data_path = op.join(mne.datasets.sample.data_path(), 'MEG', 'sample')
raw = mne.io.read_raw_fif(op.join(data_path, 'sample_audvis_raw.fif'),
preload=True)
raw.set_eeg_reference('average', projection=True) # set EEG average reference
raw.plot(butterfly=True, group_by='position')
raw.plot_sensors(kind='3d', ch_type='mag', ch_groups='position')
```
=> avoid attriute error

mne/commands/mne_coreg.py
On `gitter` people are experiencing what seem to be VTK-related errors. This should help us debug them in the future.
=> ENH: Use faulthandler in coreg gui

mne/beamformer/_compute_beamformer.py, mne/beamformer/tests/test_lcmv.py
This fixes a bug in the LCMV beamformer code:
Fix weight normalization when `pick_ori='normal', weight_norm='unit_noise_gain'`. The existing implementation has a bug where the weights were first normalized to have unit length *before* picking the normal direction. Instead, the weights should be normalized to unit length *after* picking the orientation.
=> [MRG+1] Fix weight normalization for LCMV beamformer

doc/whats_new.rst, mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_maxwell.py
Currently `maxwell_filter` (and tSSS in particular) does not deal nicely with acquisition skips. This makes it process them properly.
=> MRG: Fix maxwell_filter with data skips

mne/io/bti/bti.py, mne/io/bti/tests/test_bti.py
This is to fix the issue reported by Joshua Bear that occurs when nans are found in the device to head transform. The patch enables reading the files that Joshua shared with us.
cc @agramfort
=> fix nans in bti dev head t when presen

mne/io/brainvision/tests/test_brainvision.py
fixes #5571 
To @palday, @teonbrooks do you need the `xxxxx.vmrk`?
To @agramfort, I guess that testing `channels` was enough.
=> [MRG] [TST] MNT remove unused variables

doc/manual/c_reference.rst, mne/io/artemis123/artemis123.py, mne/io/base.py, mne/io/fiff/tests/test_raw_fiff.py, mne/io/utils.py
this fixes the order of arguments in the filename construction for BIDS files. essentially, it looks to see if the filename string has the specific modality, it pops it off to infix the part argument then adds the modality as a suffix to the filename.
=> [MRG] fix naming parsing for bids files

mne/io/eeglab/tests/test_eeglab.py, mne/tests/test_utils.py, mne/utils.py
This PR adds `mne.utils.filter_out_warnings` to remove warnings from a warning record, when using `pytest.warns`.
The main problem is that by construction, `@pytest.mark.filterwarnings` and `pytest.warns` cannot be used together since `pytest.warns` overwrites all the filters to not miss any potential warning. (see https://github.com/pytest-dev/pytest/issues/4011)
This PR would allow to simplify #4936 in the following manner:
```diff
@requires_h5py
@testing.requires_testing_data
-@pytest.mark.filterwarnings('ignore:Function read_events_eeglab is deprecated')
@pytest.mark.parametrize('fnames', [raw_mat_fnames, raw_h5_fnames])
def test_io_set_raw(fnames, tmpdir):
"""Test importing EEGLAB .set files."""
@@ -84,8 +83,6 @@ def test_io_set_raw(fnames, tmpdir):
event_id=event_id)
raw4 = …
```
=> [MRG] improve ignore deprecation warnings

doc/manual/io.rst
With BrainVision being one of the recommended formats in EEG-BIDS, I wanted to update the information on the file format here in the MNE-Python documentation.
It also links to an MNE-BIDS example, which is soon to be merged: https://github.com/mne-tools/mne-bids/pull/104/
=> [doc] add background info and links for BrainVision file format

doc/tutorials/report.rst, doc/whats_new.rst, mne/report.py, mne/tests/test_report.py
This is the final piece to fully address #5501 
PR #5505 allows you to open a previously saved `Report` object and add new figures to it. The intended use case is to have different analysis script write figures to the same report and have one HTML file that collects them all.
This PR adds the ability to overwrite a figure if it already existed in the report. The idea is that, when you re-run a script, you don't want to end up with copies of the same figure in the report. So now, all functions that add a figure to a `Report` object have gotten a `replace` parameter (defaults to `False`). 
Internally, all figures are already given a unique `fname` property that is a combination of the caption and section of the figure (and filename, if the figure was generated from a file). So, when …
=> [MRG] Allow overwriting figures in a report

mne/morph.py, mne/tests/test_morph.py
fixes #5224
_interpolate_data in morph.py was only taking into account the first label.
now it's looping properly over all src label.
let me know if you see a way to test this.
@poojaprabhu9 please confirm if this fixes your problem.
=> [MRG+1] fix morph of volume source space made of more than 1 label

doc/whats_new.rst, mne/epochs.py, mne/io/base.py, mne/io/write.py, mne/tests/test_epochs.py
Enables saving hilbert transformed data which has datatype `complex64` not `float64`.
=> MRG+1: Save hilbert transformed epochs containing complex numbers

mne/io/tests/test_constants.py
This PR:
1. Ensures that we have a complete replication of the FIF definitions in `constants.py` (hooray!)
2. Ensures that all entries in `enum(coil)` in the FIF definitions have corresponding entries in `coil_def.dat`. Currently there are 15 exceptions in a list.
=> MRG: Finalize constant consistency test

doc/whats_new.rst, mne/io/edf/edf.py, mne/io/edf/tests/test_edf.py
I'm working on creating events from annotations for EDF files in #5574.
I'm trying to read annotations, and I had troubles with different things. Anyway, covering `_read_annot` might help. 
Can anyone see what am I doing wrong on this test? Sure the problem is that the regex does not pick up anything. But what I'm not sure is if the problem is the code or the test.
Thx.
ping (based on blame): @teonbrooks, @larsoner, @agramfort
=> [MRG] fix _read_annot + dreprecate it

doc/whats_new.rst, mne/beamformer/_compute_beamformer.py, mne/channels/interpolation.py, mne/cov.py, mne/forward/_make_forward.py, mne/forward/forward.py, mne/io/ctf/tests/test_ctf.py, mne/io/meas_info.py, mne/io/pick.py, mne/io/tests/test_meas_info.py, mne/io/tests/test_pick.py, mne/minimum_norm/inverse.py, mne/preprocessing/ica.py, mne/viz/tests/test_topomap.py
This is converts the RuntimeError that was raised when removing channels that were needed for applied compensation matrices to a Warning.
this is an initial PR in response to issue: #5342
If there are any other PRs that were made to skip this issue please add it to this list.
PRs to check
Closes #5384.
=> [MRG] Warn when removing channels needed to compensation matrices.

doc/whats_new.rst, mne/io/base.py, mne/io/edf/edf.py, mne/io/edf/tests/test_gdf.py, mne/io/meas_info.py, mne/io/tests/test_raw.py
Closes #5604.
Also fixes a bug where our slicing logic in `base.py` was not safe for when `raw[:n_ch + 1]` was done. It was exposed by adding `_test_raw_reader` to `test_gdf.py`, where there were only 17 channels but `_test_raw_reader` looked at `raw[:20]`. Now it works like Python slicing where this still gives all 17 channels, but does not throw an error.
=> MRG: Fix GDF

mne/viz/raw.py, mne/viz/utils.py
Fixes #4771.
This (re)activates the vertical green line, which can be used to mark a specific position in time.
Current problems:
1. When right-clicking on a trace, both the green line is moved and the channel corresponding to the trace is marked as bad. Only the green line should be moved.
2. The green text indicating the current position of the line is too close to the x axis labels - is there any way to move the text more to the left?
@larsoner I think you are familiar with the plotting code, could you take a look? I'm not sure if what I did is OK or just an ugly hack - I'll ask specific question in code comments.
=> [MRG+1] Bring back the green line

mne/chpi.py, mne/data/coil_def_Elekta.dat, mne/forward/_make_forward.py, mne/io/constants.py, mne/io/tests/test_constants.py, mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_maxwell.py
This PR:
1. Removes the unnecessary `X` and `Y` point mag coil defs by using a simple rotation of the local coordinate system combined with the standard `Z` point mag def.
2. Simplifies the coil def machinery by making use of the new `use_coil_def`.
3. Makes it so that `maxwell_filter` uses the same coil defs as the rest of MNE. In some of the tests we still use `use_coil_def(elekta_def_fname)` just to cross-check high compat when using identical defs; in others, we don't bother (to check that processing is working properly with MNE defs). Some of the "check vs. MaxFilter" test tolerances thus needed to be lowered, but critically none of the shielding / data quality ones did, telling us that things are still working.
No need for `whats_new.rst` update as this should be transparent to …
=> MRG: Simpler coil defs

doc/whats_new.rst, mne/minimum_norm/inverse.py, mne/minimum_norm/tests/test_inverse.py
This PR adds checking that compensation grade of data matches that of forward. If it's not the case, it's probably a (fairly easily correctable) error on the part of the user.
@bloyl do you agree?
=> MRG: Add check for comps in inv

mne/epochs.py
Fixes #5282
A small change to allow control of `add_offset` from the `concatenate_epochs` function. Before was available only in the `_concatenate_epochs` function. I also added the documentation for the change to the `concatenate_epochs` docstring.
P.S. I have recreated the PR in order to fix the commit message
=> exposed add_offset control in concatenate_epochs

doc/install_mne_python.rst, mne/utils.py
This PR
1. Fixes a minor bug with our OSX install instructions
2. Improves our `mne.sys_info()` to give the PyQt5 version, where relevant. This can help debug OSX problems.
=> MRG: Better Qt info

Makefile, mne/realtime/tests/test_fieldtrip_client.py, mne/report.py, mne/tests/test_import_nesting.py, mne/tests/test_report.py
Fixes a regression caused by #5531 because `add_bem_to_section` was not covered by any test. It was added back in 0.9 so maybe our standards were more lax then :)
Also adds a test that `pyplot` imports are properly nested in tests.
=> MRG: Fix report BEM

mne/commands/mne_browse_raw.py
Example: Fixes #5656 (@agramfort suggestion)
Done the same as before but for filterchpi
=> Removed "=True" in command line options

doc/whats_new.rst, mne/epochs.py, mne/tests/test_epochs.py
This adds the shift_time method to the Epochs class as discussed in #5642.
Relevant unit tests were added, flake8 and pydocstyle are happy.
Please review.
=> MRG: Add shift_time method to Epochs
