- doc/python_reference.rst
- doc/whats_new.rst
- mne/io/__init__.py
- mne/io/edf/__init__.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/edf/tests/test_gdf.py
> Rename get_edf_events to find_edf_events

- doc/whats_new.rst
- mne/cuda.py
- mne/epochs.py
- mne/evoked.py
- mne/filter.py
- mne/io/base.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
- mne/tests/test_filter.py
Closes #4314.
@jjnurminen can you see if this is the behavior you wanted / would expect?
> MRG: Allow filtering Evoked and Epochs, add pad arg

- tutorials/plot_brainstorm_phantom_ctf.py
- tutorials/plot_brainstorm_phantom_elekta.py
> [MRG] nicer phantom tutorials

- mne/gui/_file_traits.py
Display a proper error message in cases like #4589
> [MRG+1] Coreg-GUI: Error message for FIFF file without cardinal points

- mne/stats/cluster_level.py
- mne/stats/tests/test_cluster_level.py
would this be enough @agramfort or @larsoner ? I'm not sure why yvonne ran into this problem with a dense array but at least this would ensure a sparse one...
> forcing connectivity to be scipy sparse

- circle.yml
- doc/documentation.rst
- examples/connectivity/plot_mne_inverse_psi_visual.py
- examples/datasets/plot_brainstorm_data.py
- examples/datasets/plot_megsim_data_single_trial.py
- examples/datasets/plot_spm_faces_dataset.py
- examples/decoding/plot_decoding_csp_eeg.py
- examples/decoding/plot_decoding_csp_timefreq.py
- examples/decoding/plot_decoding_spoc_CMC.py
- examples/decoding/plot_ems_filtering.py
- examples/decoding/plot_receptive_field.py
- mne/datasets/brainstorm/bst_auditory.py
- mne/datasets/brainstorm/bst_phantom_ctf.py
- mne/datasets/brainstorm/bst_phantom_elekta.py
- mne/datasets/brainstorm/bst_raw.py
- mne/datasets/brainstorm/bst_resting.py
- mne/datasets/utils.py
- mne/utils.py
WIP because I need to update some hashes, we need to finish uploading files, and I need to make sure the `brainstorm` dataset changes actually work.
> MRG: Move datasets

- mne/viz/montage.py
- mne/viz/tests/test_montage.py
> [MRG] Do not plot duplicate labels in montage

- mne/decoding/tests/test_receptive_field.py
- mne/evoked.py
- mne/forward/tests/test_field_interpolation.py
- mne/tests/test_import_nesting.py
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
Closes #4599.
@smgutstein can you verify this makes tests pass for you? (There was a difference in warning text based on SciPy version.)
> MRG: Fix warning check

- .travis.yml
- mne/datasets/utils.py
- mne/tests/test_bem.py
Should move us toward #4570 (and #4570).
> MAINT: Simplify split

- circle.yml
- mne/viz/_3d.py
- tutorials/plot_mne_dspm_source_localization.py
Should clean up our examples that use PySurfer.
> MRG: Use new verbose argument

- mne/viz/evoked.py
Otherwise `import mne` imports `matplotlib.colors`.
> [MRG] Nest matplotlib import

- doc/whats_new.rst
- mne/channels/tests/test_montage.py
- mne/gui/_coreg_gui.py
- mne/gui/_file_traits.py
- mne/io/meas_info.py
- mne/viz/_3d.py
Closes #4589.
@kingjr can you see if it fixes your CTF coreg problem?
> MRG: Fix CTF fiducials

- appveyor.yml
- environment.yml
Last I recall this env doesn't work on CircleCI or AppVeyor, but I want to double check.
> FIX: AppVeyor environment.yml

- doc/whats_new.rst
- examples/datasets/plot_spm_faces_dataset.py
- examples/forward/plot_forward_sensitivity_maps.py
- examples/forward/plot_source_space_morphing.py
- examples/inverse/plot_covariance_whitening_dspm.py
- examples/inverse/plot_custom_inverse_solver.py
- examples/inverse/plot_gamma_map_inverse.py
- examples/inverse/plot_mixed_norm_inverse.py
- examples/inverse/plot_mixed_source_space_inverse.py
- examples/inverse/plot_time_frequency_mixed_norm_inverse.py
- examples/simulation/plot_simulate_evoked_data.py
- mne/beamformer/_lcmv.py
- mne/datasets/utils.py
- mne/forward/forward.py
- mne/inverse_sparse/_gamma_map.py
- mne/inverse_sparse/mxne_inverse.py
- mne/inverse_sparse/tests/test_gamma_map.py
- mne/inverse_sparse/tests/test_mxne_inverse.py
- mne/io/pick.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
- mne/simulation/evoked.py
Closes #4604.
@agramfort @joewalter feel free to have a look.
> MRG: Deprecate loose=None

- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_lcmv.py
> Fix issue with complex eigenspectrum in LCMV

- circle.yml
- doc/whats_new.rst
- examples/time_frequency/plot_time_frequency_global_field_power.py
- tutorials/plot_receptive_field.py
Let's see if this works. If it does, I'll also want to run it without cache to see if that passes.
> MRG: Fix circle

- examples/inverse/plot_rap_music.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
This should hopefully fix CircleCI (again).
> FIX: Fix mpl version check

- mne/cov.py
- mne/tests/test_cov.py
Here I replace the nested class definitions with proper subclassing and delegation. Once Travis is happy I'll update whatsnew.
@larsoner @agramfort
> [FIX/MAINT] fix #2497 and #4140 n_jobs in cov

- .gitignore
This is what the .ignore plugin for PyCharm does - nice 😄 !
> [MRG] Remove duplicate entry

- mne/channels/channels.py
Fix #4631. Let me check if the function links in the HTML docs work.
> [MRG] Clarify the docstrings of read_ch_connectivity and find_ch_connectivity

- mne/channels/channels.py
- mne/io/reference.py
I thought we could be a bit more verbose here...
> [MRG] Mention that bad channels are excluded for average reference

- mne/gui/_kit2fiff_gui.py
- mne/io/kit/constants.py
- mne/io/kit/kit.py
WIP addressing #4634 
I hard coded the parameters for NY, @kingjr can you verify that it reads the file you need correctly?
> [MRG]:  re-enable reading of legacy KIT files

- mne/viz/utils.py
Closing a figure created with `mne.channels.Montage.plot` resulted in an AttributeError. I hope that nothing else is affected by these changes, but the CIs will tell...
> [MRG] Fix lasso AttributeError e.g. for plot_montage

- examples/time_frequency/plot_time_frequency_global_field_power.py
- mne/stats/permutations.py
- mne/stats/tests/test_permutations.py
cc @jona-sassenhagen n_bootstraps was not used. This completely went under our radar ...
> FIX: wrong size specification in bootstrap

- examples/decoding/decoding_rsa.py
Removed plot that brought up warnings in decoding_rsa example.
closes #4577
> [MERGE] Removed plot from decoding_rsa example

- mne/io/meas_info.py
> Fix when there is no us information in mea_date date info value of raw object

- .travis.yml
- environment.yml
I suspect the caching is what's breaking our CI builds. I'm going to try removing it to see if it fixes things.
> FIX: Fix OSX

- doc/whats_new.rst
- mne/cov.py
- mne/evoked.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/proc_history.py
- mne/io/tests/test_proc_history.py
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
- tutorials/plot_compute_covariance.py
Last package of covariance hacking for 0.15. 
Low rank computation + refined SSS rank handling moved to 0.16.
cc @larsoner
> [MRG] viz + tutorial changes + rank API

- examples/realtime/rt_feedback_server.py
- mne/beamformer/tests/test_lcmv.py
- mne/channels/channels.py
- mne/commands/tests/test_commands.py
- mne/cov.py
- mne/decoding/tests/test_base.py
- mne/forward/tests/test_forward.py
- mne/gui/_file_traits.py
- mne/io/artemis123/tests/test_artemis123.py
- mne/io/base.py
- mne/io/kit/kit.py
- mne/stats/permutations.py
- mne/stats/tests/test_regression.py
- mne/tests/test_docstring_parameters.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
- mne/tests/test_label.py
- mne/tests/test_proj.py
- mne/tests/test_report.py
- mne/time_frequency/tests/test_multitaper.py
- mne/viz/epochs.py
- mne/viz/tests/test_3d.py
- mne/viz/tests/test_decoding.py
- mne/viz/tests/test_raw.py
- mne/viz/tests/test_topo.py
- mne/viz/topo.py
- pytest.ini
- setup.cfg
trying to remove all the warnings in tests
> Fix warnings

- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
- mne/viz/topomap.py
See #4649
@larsoner , I've picked a hopefully less invasive way of going about it.
Still, eventually missing channel positions should become NaNs.
Closes #4649
> Allow plotting Cz

- circle.yml
- doc/_templates/navbar.html
This adds more links in the docs dropdown, and changes the placement.
> MRG: More links

- mne/gui/_kit2fiff_gui.py
- mne/io/artemis123/artemis123.py
- mne/io/kit/coreg.py
- mne/misc.py
- mne/realtime/client.py
- mne/realtime/fieldtrip_client.py
- mne/realtime/tests/test_fieldtrip_client.py
- mne/tests/test_label.py
- mne/time_frequency/multitaper.py
- mne/viz/epochs.py
- setup.cfg
> Ignore E722 (bare except) and fix E741 (ambiguous variable names)

- mne/filter.py
- mne/tests/test_filter.py
Closes #4693.
@ktavabi can you see if this fixes your problem?
> MRG: Fix filter design

- doc/whats_new.rst
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
- tutorials/plot_forward.py
Closes #4694.
@drammock can you see if this works for you?
> MRG: Add plotting of dense head

- tutorials/plot_python_intro.py
Fix some typos and use clearer language.
Any ideas how to include that long NumPy for MATLAB users link without rendering the `# noqa` tag in the HTML page?
> [MRG] Improve Python intro

- mne/epochs.py
- mne/evoked.py
- mne/io/fiff/raw.py
> Add attribute times to the docstring of Raw, Epochs and Evocked.

- doc/whats_new.rst
- mne/viz/tests/test_topo.py
- mne/viz/topo.py
Shows the channel name in the status bar for topo plots. 
Closes #4673
> MRG: show channel name on mouse hover

- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
- tutorials/plot_source_alignment.py
Fixes a regression that was introduced in #4705 that CircleCI caught.
> MRG: Fix plot_alignment

- mne/gui/_viewer.py
- mne/gui/tests/test_coreg_gui.py
- mne/gui/tests/test_kit2fiff_gui.py
Closes #4695.
@ktavabi can you see if this fixes things for you?
> MRG: Fix for old mayavi

- doc/whats_new.rst
- mne/evoked.py
- mne/source_estimate.py
- mne/tests/test_evoked.py
> [MRG] return peak amp in get_peak()

- doc/whats_new.rst
- mne/viz/_3d.py
> ENH: allow user-created mlab.Figure in plot_alignment

- mne/epochs.py
- mne/event.py
Closes #4712.
@jjnurminen can you see if this fixes your problem?
> MRG: Fix event dtype for Windows

- mne/viz/utils.py
> [MRG] Fix AttributeError when closing the annotation window

- doc/whats_new.rst
- mne/baseline.py
- mne/epochs.py
- mne/minimum_norm/time_frequency.py
- mne/tests/test_epochs.py
- mne/time_frequency/tfr.py
Closes #4726.
I also corrected the docstring for `mode` because it was a bit misleading about the calculations.
> MRG: Dont make copies when baselining

- doc/whats_new.rst
- mne/stats/cluster_level.py
- mne/stats/tests/test_cluster_level.py
> [MRG] Fix threshold must be monotonic condition

- mne/io/edf/edf.py
> Set correct default stim_channel arg

- mne/cov.py
> DOC in cov estimation code

- doc/whats_new.rst
- mne/bem.py
- mne/forward/tests/test_make_forward.py
- mne/source_space.py
- mne/tests/test_bem.py
- mne/tests/test_source_space.py
- mne/transforms.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
- tutorials/plot_source_alignment.py
WIP because I need to 
Closes #4723.
> MRG: Add colors to sphere ConductorModel

- examples/stats/plot_sensor_regression.py
With the new dataset and the metadata, we can now provide a simpler example for the linear_regression function.
@TalLinzen @teonbrooks
> MRG Simpler regression example

- README.rst
Synced with the description from the homepage
> [MRG] Cleanup readme

- tutorials/plot_artifacts_correction_ica.py
A recent commit breaks Travis due to an 80c line.
> [Minor, fix] fix pep8 in ica tutorial

- mne/viz/raw.py
- mne/viz/utils.py
Fixes #4770.
I'd like to add an explanation to the docstring - any idea for a short sentence (currently everything I come up with is too convoluted and no one would understand what I mean)?
> [MRG] Add horizontal scrolling in smaller steps

- mne/bem.py
- mne/epochs.py
- mne/io/bti/bti.py
- mne/io/bti/read.py
- mne/io/ctf/ctf.py
- mne/io/tag.py
- mne/io/tree.py
- mne/io/write.py
- mne/realtime/client.py
- mne/source_space.py
- mne/viz/misc.py
On latest `numpy` dev I get a lot of warnings about `fromstring` saying we should use `frombuffer`. I've converted some of our uses but not all.
> MRG: Use frombuffer

- doc/whats_new.rst
- mne/viz/_3d.py
Code could be simplified further, bit verbose now, but perhaps best left so (assuming bots agree!)
Closes #4783
> check for -head.fif in plot_alignment

- .travis.yml
- README.rst
- mne/decoding/tests/test_transformer.py
- mne/preprocessing/ica.py
> [MRG+1] Require sklearn >= 0.18

- doc/whats_new.rst
- mne/time_frequency/psd.py
- mne/viz/tests/test_raw.py
> [MRG] Fix raw.plot_psd reject_by_annotation=False

- examples/decoding/plot_decoding_spoc_CMC.py
- mne/datasets/utils.py
This should hopefully fix some of the common CircleCI timeouts.
> MRG: Fix path for CMC

- mne/viz/raw.py
> [MRG] Make traces in raw.plot_psd less transparent

- mne/preprocessing/ica.py
I think it would be very useful if the time for ICA fitting was logged.
> [MRG] Log elapsed time for ICA fitting

- .travis.yml
The discussion of the error is here:
https://github.com/travis-ci/travis-ci/issues/8703
I used the solution propsed there as seen [here](https://github.com/touist/touist/commit/5d7a327043e26a0ecc0a04f0fd040899dec6f63f) or [here](https://github.com/Valloric/YouCompleteMe/pull/2840/files)
Let's see if that works!
> MRG FIX: trying to fix Travis osx error

- doc/whats_new.rst
- examples/preprocessing/plot_movement_compensation.py
- mne/chpi.py
- mne/tests/test_utils.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
This updates our `plot_head_positions` function to make it more usable for diagnostic plotting.
> MRG: Add multiple pos and sensors

- mne/preprocessing/ica.py
- mne/preprocessing/infomax_.py
Some minor cosmetic fixes in ICA-related log messages.
> [MRG] Streamline ICA-related log messages

- doc/whats_new.rst
- mne/io/proc_history.py
- mne/io/tag.py
- mne/io/tests/test_meas_info.py
- mne/io/write.py
- mne/preprocessing/tests/test_maxwell.py
Takeover of #4501.
When writing a test I found out we had a bug with CSC writing where it was written transposed (yikes!).
> MRG: Fix CSC bug

- doc/whats_new.rst
- mne/epochs.py
- mne/tests/test_epochs.py
> FIX : Fix bug in mne.Epochs when passing events as list with event_id=None

- examples/preprocessing/plot_metadata_query.py
- mne/epochs.py
- mne/tests/test_epochs.py
- tutorials/plot_metadata_epochs.py
Closes #4820.
Closes #4821.
Closes #4823.
@kingjr can you confirm everything works as you expect now?
> MRG: Fix metadata

- doc/whats_new.rst
- mne/decoding/search_light.py
- mne/decoding/tests/test_base.py
- mne/decoding/tests/test_search_light.py
> fix _estimator_type for cross_valmultiscore

- mne/viz/utils.py
> Seeg eeg seperated in butterfly plot

- mne/epochs.py
- mne/preprocessing/tests/test_ica.py
Fixes ICA failures I get with latest `sklearn` dev related to not having enough samples for the given `n_components`.
> MRG: Fix ICA

- mne/epochs.py
- mne/tests/test_epochs.py
A little fix to use a more robust / standard `int` check-and-convert.
> MRG: Fix int check

- mne/io/eeglab/tests/test_eeglab.py
- mne/minimum_norm/tests/test_inverse.py
- mne/source_space.py
- mne/utils.py
Should fix AppVeyor, will merge assuming it passes.
> MRG: Fix info

- doc/whats_new.rst
- mne/bem.py
- mne/commands/mne_make_scalp_surfaces.py
Closes #4873.
@ktavabi can you see if this fixes your problem? Run with `-i` or `--allow-incomplete`.
> MRG: Allow skipping topology check

- circle.yml
- doc/python_reference.rst
- doc/whats_new.rst
- examples/preprocessing/plot_otp.py
- mne/io/meas_info.py
- mne/preprocessing/__init__.py
- mne/preprocessing/otp.py
- mne/preprocessing/tests/test_otp.py
- mne/preprocessing/utils.py
- tutorials/plot_brainstorm_phantom_ctf.py
- tutorials/plot_brainstorm_phantom_elekta.py
Finally adds the [OTP algorithm](https://dx.doi.org/10.1109/TBME.2017.2734641), useful for denoising HF responses, (some) bad channel repair, and raw data browsing.
> MRG: Add oversampled temporal projection

- doc/whats_new.rst
- mne/preprocessing/ica.py
This results in consistent random states across different arguments (and also it seems to be faster). See our discussion in #4856.
> Replace randomized PCA with full PCA

- mne/preprocessing/ica.py
This is some additional cleanup for the `ica` module. I think I now understand the line
self.unmixing_matrix_ /= np.sqrt(exp_var[sel])[None, :]
toward the end of the `_fit` method. It undoes the whitening, which is already performed with the PCA transform (and we don't want to do it twice). Is this correct? If so, I will add a comment to clarify.
> Remove conditions related to RandomizedPCA

- mne/event.py
- mne/realtime/epochs.py
Fix for verbosity control in realtime epochs, as discussed in #4898.
> fix verbosity control for event detection in realtime epochs

- mne/annotations.py
> [MRG] DOC fix missing unit onannotations onset

- mne/defaults.py
> [MRG] Adjust sEEG plotting

- mne/coreg.py
- mne/source_space.py
- mne/tests/test_coreg.py
> [MRG] scale_source_space(): add support for vol source spaces

- mne/datasets/utils.py
- tutorials/plot_phantom_4DBTi.py
The dataset was missing from the `_download_all_example_data` which led to this failure:
https://circleci.com/gh/mne-tools/mne-python/6890?utm_campaign=build-failed&utm_medium=email&utm_source=notification
This should fix it.
> MRG: Fix all download

- mne/viz/epochs.py
Fixes the problem with `b''` labels in `epochs.plot` butterfly mode mentioned in #4799.
> MRG: Fix labels

- examples/visualization/plot_3d_to_2d.py
- mne/channels/montage.py
- tutorials/plot_ecog.py
This is the requested pull request to update the docs for channels.Montage and channels.DigMontage to specify that coordinates are given in meters. I have also added a comment to the plot_ecog demo stating that electrode coordinates are given in meters
> WIP: Coords

- doc/whats_new.rst
- mne/viz/ica.py
- mne/viz/tests/test_ica.py
- mne/viz/topomap.py
- mne/viz/utils.py
@cbrnr 
This is already contains title interactivity (was easy once @larsoner suggested using `ax.title`). Check if that works for you. We can consider whether gray is visible enough, but I think it is ok.
[WIP] because I'll add a test once you approve how it works in general.
edit: closes #4792
> [MRG] ENH+FIX: select excluded components by clicking on the ic title

- doc/whats_new.rst
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
More tweaks from working with head positions.
> MRG: Add axes options to `plot_head_positions`

- mne/datasets/utils.py
> update testing to add bst annot file

- .travis.yml
- mne/inverse_sparse/mxne_optim.py
- mne/io/eeglab/tests/test_eeglab.py
> [MRG] Fix eeglab test

- mne/cov.py
- mne/tests/test_cov.py
- tutorials/plot_compute_covariance.py
Fix a little bug introduced by #4808, with test to ensure we hit that code path in the future.
> MRG: Fix cov

- mne/report.py
SVG output was broken on Py3k. Tiny fix, will merge once CIs come back happy.
> MRG: Fix SVG output on Py3k

- examples/visualization/plot_channel_epochs_image.py
- examples/visualization/plot_roi_erpimage_by_rt.py
- mne/viz/utils.py
- tutorials/plot_visualize_evoked.py
I don't know why I originally put that line there?
Can we test what it outputs to the screen? I can't think of a test.
closes #4948
> MRG+1, MINOR fix float xtick labels in plot_compare_evoked

- mne/source_estimate.py
- mne/tests/test_source_estimate.py
- tutorials/plot_stats_cluster_spatio_temporal.py
- tutorials/plot_stats_cluster_spatio_temporal_2samp.py
- tutorials/plot_stats_cluster_spatio_temporal_repeated_measures_anova.py
Closes #4643.
@wmvanvliet feel free to have a look, this should do what we talked about earlier to get rid of `grade_to_tris`.
> MRG: Better tutorials using connectivity

- doc/documentation.rst
- doc/whats_new.rst
- examples/inverse/plot_covariance_whitening_dspm.py
- examples/io/plot_read_evoked.py
- examples/visualization/plot_evoked_whitening.py
- mne/cov.py
- mne/defaults.py
- mne/epochs.py
- mne/event.py
- mne/evoked.py
- mne/io/base.py
- mne/io/pick.py
- mne/io/proc_history.py
- mne/viz/epochs.py
- mne/viz/evoked.py
- mne/viz/ica.py
- mne/viz/raw.py
- mne/viz/tests/test_epochs.py
- mne/viz/tests/test_evoked.py
- mne/viz/tests/test_raw.py
- mne/viz/tests/test_topo.py
- mne/viz/topo.py
- mne/viz/utils.py
- tutorials/plot_compute_covariance.py
- tutorials/plot_visualize_raw.py
- tutorials/plot_whitened.py
Need to:
Will post CircleCI result once it comes up.
Closes #3926.
> MRG: Add whitening to plots

- mne/io/base.py
> fixed link to gist in resample method doc

- mne/dipole.py
- mne/tests/test_dipole.py
- tutorials/plot_dipole_fit.py
Should make CircleCI happy again after a recent small regression.
> MRG: Fix DipoleFixed plotting

- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- mne/utils.py
> MINOR use _check_preload to check preload in ica

- doc/whats_new.rst
- mne/forward/_compute_forward.py
- mne/forward/tests/test_make_forward.py
> Fix comp fwd ctf bads

- examples/inverse/plot_mixed_norm_inverse.py
if `n_mxne_iter` is > 1, then the algo is not MxNE but irMxNE. 
The old plot title was confusing.
> [MRG] Fix plot title in MxNE example

- doc/whats_new.rst
- mne/inverse_sparse/mxne_inverse.py
- mne/inverse_sparse/mxne_optim.py
This addresses the issue in #5030
> [MRG] Deprecating True/False log_objective

- doc/manual/io.rst
- mne/decoding/tests/test_transformer.py
- mne/decoding/transformer.py
ENH: better error msg in decoding.scaler. Closes #5022
> MINOR: Specify err msg scaler

- examples/time_frequency/plot_time_frequency_erds.py
- mne/time_frequency/tfr.py
- mne/viz/topo.py
> [MRG] Add mask parameter to TFR plot

- mne/inverse_sparse/mxne_inverse.py
- mne/inverse_sparse/mxne_optim.py
> [MRG] Fix dgap freq

- mne/time_frequency/multitaper.py
> FIX: Force int type

- .gitignore
- doc/whats_new.rst
- mne/channels/channels.py
- mne/io/ctf/ctf.py
- mne/io/ctf/tests/test_ctf.py
clean_names function was added to the SetChannelsMixin.
> #4207 ENH: streamline processing CTF files

- .circleci/config.yml
- .travis.yml
- doc/advanced_setup.rst
- doc/documentation.rst
- doc/install_mne_python.rst
- doc/manual/datasets_index.rst
- doc/whats_new.rst
- environment.yml
- mne/io/eximia/eximia.py
- mne/utils.py
- tutorials/plot_compute_covariance.py
Let's see how the CIs like this.
> MRG: Use VTK8 and Qt 5.9+

- examples/inverse/plot_mixed_source_space_inverse.py
- examples/time_frequency/plot_time_frequency_erds.py
- mne/time_frequency/tests/test_tfr.py
- mne/viz/topo.py
Fixes one example broken on modern MPL, and another that we missed testing properly (@jona-sassenhagen I think?).
> MRG: Fix broken examples

- mne/time_frequency/tfr.py
- mne/viz/utils.py
- tutorials/plot_sensors_time_frequency.py
- tutorials/plot_visualize_evoked.py
Two small-ish viz bugs in joint plots.
Closes #5060
> MRG: Fix viz stuff (minor)

- doc/whats_new.rst
- mne/channels/interpolation.py
- mne/channels/tests/test_interpolation.py
closes https://github.com/mne-tools/mne-python/issues/5047
> FIX interpolation code

- doc/manual/decoding.rst
- doc/whats_new.rst
- examples/decoding/plot_linear_model_patterns.py
- mne/time_frequency/csd.py
- mne/time_frequency/multitaper.py
- mne/time_frequency/psd.py
- tutorials/plot_sensors_decoding.py
Fixes a bunch of little problems with our docs.
Closes #5005.
> MRG: Doc fixes

- mne/io/egi/egimff.py
Closes #4689.
Seems overkill to add a test file for this one.
> MRG: Fix EGIMFF var

- doc/whats_new.rst
- mne/channels/channels.py
- mne/io/ctf/tests/test_ctf.py
Implements the fix discussed in https://github.com/mne-tools/mne-python/issues/4241#issuecomment-299203201.
Closes #4241.
@jona-sassenhagen can you see if it makes sense for your data?
> MRG: Fix CTF picking

- mne/io/base.py
> DOC: Docstring [ci skip]

- doc/whats_new.rst
- mne/viz/evoked.py
- mne/viz/raw.py
- tutorials/plot_visualize_evoked.py
Closes #4484.
@jona-sassenhagen I don't think it looks so pretty:
How should I make it nicer?
> MRG: Append nave to evoked.plot

- doc/whats_new.rst
- mne/epochs.py
- mne/tests/test_epochs.py
> MRG: Fix split saving

- doc/whats_new.rst
- mne/annotations.py
- mne/io/base.py
- mne/io/fiff/raw.py
- mne/tests/test_annotations.py
> MRG: FIX time offset bug in raw.crop for Annotations

- mne/chpi.py
- mne/tests/test_chpi.py
This is in need of a regression test and more importantly some other CTF users who have some cHPI data to evaluate it.
> WIP: extract head position pos from CTF data

- doc/whats_new.rst
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
- mne/io/write.py
- mne/preprocessing/maxwell.py
closes https://github.com/mne-tools/mne-python/issues/4949
> MRG: Don't guess date when writing info

- mne/utils.py
> MRG: Fix progressbar for tiny terminals

- mne/viz/misc.py
Small enhancement to `plot_csd`. Now it indicates units, if available:
Also does the subplots a bit more elegantly.
> [MRG] Make plot_csd indicate units properly, if available

- doc/documentation.rst
- doc/manual/source_localization/inverse.rst
- doc/python_reference.rst
- doc/whats_new.rst
- examples/connectivity/plot_mixed_source_space_connectivity.py
- mne/defaults.py
- mne/forward/forward.py
- mne/minimum_norm/_eloreta.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/psf_ctf.py
- mne/minimum_norm/tests/test_inverse.py
- mne/minimum_norm/time_frequency.py
- mne/source_estimate.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
- tutorials/plot_dipole_orientations.py
- tutorials/plot_introduction.py
- tutorials/plot_mne_dspm_source_localization.py
- tutorials/plot_mne_solutions.py
- tutorials/plot_stats_cluster_1samp_test_time_frequency.py
- tutorials/plot_stats_cluster_spatio_temporal.py
- tutorials/plot_stats_cluster_spatio_temporal_2samp.py
- tutorials/plot_stats_cluster_spatio_temporal_repeated_measures_anova.py
- tutorials/plot_stats_cluster_time_frequency_repeated_measures_anova.py
- tutorials/plot_stats_spatio_temporal_cluster_sensors.py
Closes #4963.
Also includes some fixes/unifications for 3 plotting I hit while testing.
Todo:
> MRG: Add eLORETA

- mne/io/edf/edf.py
@cbrnr to tackle #1766 I first want to refactor the EDF reader to hold a "sel" of the channels to be used. Can you see if this breaks anything with your set of EDF data files? Tests are passing at least.
> MRG: Refactor EDF channel picking

- doc/python_reference.rst
- doc/whats_new.rst
- mne/stats/cluster_level.py
- mne/stats/tests/test_permutations.py
- mne/tests/test_docstring_parameters.py
Closes #4959.
@dengemann can you see if this works for your purposes?
> MRG: Allow connectivity=False

- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
> [MRG] Improve ICA docstring

- mne/viz/evoked.py
- mne/viz/utils.py
Dumb bug where a `None` would show up in the title.
Closes #5149
> [MRG+1][MINOR]: plot_compare_evoked title bug

- mne/annotations.py
- mne/cov.py
- mne/dipole.py
- mne/epochs.py
- mne/event.py
- mne/evoked.py
- mne/forward/forward.py
- mne/minimum_norm/inverse.py
- mne/preprocessing/ica.py
- mne/proj.py
- mne/source_space.py
- mne/time_frequency/tfr.py
- mne/transforms.py
> [MRG] Add _ to valid file names

- doc/documentation.rst
- tutorials/plot_stats_cluster_erp.py
I'm proposing an example for ERP ROI plotting (a topic which comes up ever so often). It also shows how to run and display typical stats on ERP data.
Arguably,
Closes #2268
Better than #2602
Solves what remains of #2693
> MRG: Evoked stat example

- doc/whats_new.rst
- mne/coreg.py
- mne/datasets/utils.py
- mne/source_space.py
- mne/tests/test_coreg.py
- mne/tests/test_transforms.py
- mne/transforms.py
~~This should work once https://github.com/nipy/nibabel/issues/619 is sorted out.~~
@christianbrodbeck does this look good to you assuming I can work out the `nibabel` bug and thus get tests to pass?
> MRG: Add talairach.xfm and MRI scaling to coreg

- mne/channels/channels.py
- mne/commands/mne_compute_proj_ecg.py
- mne/commands/mne_compute_proj_eog.py
- mne/preprocessing/ecg.py
- mne/preprocessing/eog.py
- mne/preprocessing/ssp.py
- mne/preprocessing/tests/test_ecg.py
- mne/preprocessing/tests/test_ssp.py
- mne/preprocessing/utils.py
> [MRG+1] Add deprecation cycle for `average` parameter in compute_proj_exg

- mne/gui/_viewer.py
Closes #5152.
@jshanna100 can you see if this fixes the problem for you?
> MRG: Fix ordering

- mne/channels/channels.py
- mne/cov.py
- mne/forward/_make_forward.py
- mne/forward/forward.py
- mne/forward/tests/test_make_forward.py
- mne/io/meas_info.py
- mne/io/pick.py
- mne/io/tests/test_meas_info.py
- mne/io/tests/test_pick.py
- mne/minimum_norm/inverse.py
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- mne/realtime/fieldtrip_client.py
- mne/tests/test_cov.py
- mne/utils.py
- mne/viz/topomap.py
@larsoner, take a look at this.
The main difference from what we discussed is that I removed the check_comp flags, as that mechanism seemed like something that could start to be abused and would lead to headaches later.
Closes #5127
> MRG+1: check info against compensation chans

- mne/io/egi/egi.py
A sneaky bug reportd by @SherazKhan that can prevent reading certain files.
cc @agramfort @larsoner @massich
> FIX: fix int/float bug

- doc/_templates/navbar.html
Need to add to Wiki (I did step 1, step 2 is this PR):
1. In `mne-tools.github.io`, manually do:
```
mkdir 0.18
mv 0.17/index.html 0.18/index.html
rmdir 0.17
cp -a stable 0.17
git add -a 0.17/*
```
2. Update `doc/_templates/navbar.html` to add an entry
> FIX: Fix navbar

- .travis.yml
- doc/conf.py
- doc/documentation.rst
- doc/install_mne_python.rst
- doc/manual/time_frequency.rst
- doc/whats_new.rst
- mne/beamformer/_dics.py
- tutorials/plot_dics.py
- tutorials/plot_sensors_time_frequency.py
I expect this to break AppVeyor, let's see. If it does we can do something special there. I'll test locally with a Windows VM to see if it works for users.
> MRG: PyQt5.10

- mne/time_frequency/csd.py
- mne/time_frequency/tests/test_csd.py
Found a small bug in my CSD code.
> Fix setting csd.tmin/csd.tmax for csd_morlet

- doc/advanced_setup.rst
> DOC: Fix indentation for proper formatting of code block

- doc/whats_new.rst
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
> [MRG] support np.array as ica.exclude attribute

- mne/channels/channels.py
- mne/channels/tests/test_interpolation.py
- mne/externals/h5io/_h5io.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
- mne/tests/test_epochs.py
- mne/utils.py
- mne/viz/evoked.py
- mne/viz/ica.py
- mne/viz/tests/test_evoked.py
- mne/viz/tests/test_ica.py
For some reason, I've decided to refactor a bunch of stuff.
> MRG: refactor stuff

- mne/annotations.py
- mne/channels/channels.py
- mne/channels/tests/test_channels.py
- mne/decoding/receptive_field.py
- mne/decoding/search_light.py
- mne/decoding/tests/test_receptive_field.py
- mne/epochs.py
- mne/evoked.py
- mne/filter.py
- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/meas_info.py
- mne/io/reference.py
- mne/preprocessing/ica.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
- mne/tests/test_utils.py
- mne/time_frequency/__init__.py
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
- mne/utils.py
- mne/viz/evoked.py
> MRG More cleanup/refactoring

- ignore_words.txt
- mne/forward/forward.py
- mne/preprocessing/tests/test_eeglab_infomax.py
- mne/time_frequency/_stockwell.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
- tutorials/plot_background_filtering.py
- tutorials/plot_dipole_fit.py
Some spelling fixes and removing deprecated unnecessary `curv` argument for `surfer.Brain`.
> MRG: Spelling and newer PySurfer

- examples/stats/plot_sensor_regression.py
- examples/time_frequency/plot_time_frequency_erds.py
- mne/time_frequency/tfr.py
- mne/viz/evoked.py
- mne/viz/topo.py
- mne/viz/utils.py
> MRG: Refactor evoked and tfr image plot mask to share code

- mne/viz/evoked.py
- mne/viz/raw.py
> [MRG] fix time_unit in evoked plots

- README.rst
- mne/tests/test_import_nesting.py
- mne/viz/topo.py
Closes #5248.
Not doing the `install_requires` for now. We can wait until `sklearn` does it :)
> MRG: Weak dep on mpl

- mne/viz/epochs.py
> [MRG] fix overlaping subplots in evoked histograms

- doc/whats_new.rst
- mne/filter.py
- mne/tests/test_filter.py
> [MRG+1] Fix IIR filtering

- README.rst
- doc/_static/reset-syntax.css
- doc/conf.py
- doc/install_mne_python.rst
- doc/whats_new.rst
- environment.yml
- environment2.yml
> [MRG+1] Add notes for Python 3 transition

- examples/visualization/plot_roi_erpimage_by_rt.py
- mne/channels/__init__.py
- mne/channels/channels.py
- mne/channels/montage.py
- mne/channels/tests/test_channels.py
- tutorials/plot_stats_cluster_erp.py
See #5170
Add a helper function that takes an info instance or list of 10/20 format channel names, and returns a dictionary mapping from ROI names to picks.
> [MRG] Add helper for 10/20 ROI mapping

- mne/evoked.py
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
- tutorials/plot_stats_cluster_erp.py
Addresses another point in #5170
~Todo: tests~
> MRG: automatic plotting of channel names in evoked.plot_image

- mne/bem.py
- mne/channels/channels.py
- mne/io/array/array.py
- mne/io/meas_info.py
- mne/io/pick.py
- mne/utils.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
> WIP _validate_type(info, "info")

- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/data/test.vmrk
- mne/io/brainvision/tests/test_brainvision.py
- mne/io/utils.py
> MRG Min duration for stim channel synthesis = 1

- mne/source_estimate.py
- mne/tests/test_source_space.py
@agramfort we missed a source space type
> MRG: Fix for discrete

- .circleci/config.yml
Let's see if this works ...
I think PyQt5's latest release broke our build
> FIX circle CI

- .circleci/config.yml
Let's see if this fixes CircleCI for good.
> Add PyQt5-sip (required for PyQt5 >= 5.11)

- .circleci/config.yml
> ENH: Try newer Qt [circle front]

- doc/links.inc
- doc/tutorial_links.inc
- tutorials/plot_background_statistics.py
I'm currently reading the background doc, and although this is an excellent introduction there are some minor tweaks that could make it even better.
I've done everything up to the non-parametric section, which I will tackle in another commit.
> [MRG+1] Clarify statistics background

- doc/whats_new.rst
- mne/beamformer/_compute_beamformer.py
- mne/beamformer/tests/test_lcmv.py
See: https://gist.github.com/Heneark/a183a24218302831860efc86c84c1950
and https://github.com/mne-tools/mne-python/issues/5292#issuecomment-404176118
cc @Heneark
> WIP : fix CTF lcmv due to comps

- .travis.yml
- mne/io/bti/bti.py
- mne/io/bti/tests/test_bti.py
- mne/preprocessing/tests/test_ica.py
- mne/tests/common.py
Just speeding up a few tests that were listed as slow in #5251
> ENH: Speed up a couple of tests

- mne/io/artemis123/artemis123.py
- mne/io/bti/bti.py
To make @agramfort happy. Also I noticed we were missing one.
> MRG: Verbose

- mne/externals/pymatreader/pymatreader.py
this fixes a bug that was discovered by @larsoner that prevented the proper loading of EEGLAB set files.
> updated external pymatreader to version 0.0.9.

- doc/whats_new.rst
- mne/bem.py
- mne/tests/test_bem.py
We had a bug in our sphere model fitting. It's now fixed. While I was at it I vectorized the code so that it is much faster now.
> MRG: Fix sphere model fitting

- doc/whats_new.rst
- mne/epochs.py
- mne/tests/test_epochs.py
Closes #5346.
@stfnrpplngr can you see if this fixes your problem?
> MRG: Fix resizing

- doc/whats_new.rst
- mne/io/pick.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
> MRG: Fix check for avg ref

- mne/beamformer/_compute_beamformer.py
- mne/beamformer/_dics.py
- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_dics.py
- mne/beamformer/tests/test_lcmv.py
- mne/minimum_norm/inverse.py
- mne/source_estimate.py
Refers to https://github.com/mne-tools/mne-python/issues/5224 and https://github.com/mne-tools/mne-python/pull/5231 .
Use ``src`` as input to  ``_make_stc`` in ``_lcmv`` and ``_dics``.
@agramfort are these all that all the changes required here?
> Use src to create stc in beamformer code

- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
@massich it should fix your CI failure.
> fix CTF MNE/dSPM due to comps

- doc/whats_new.rst
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/data/test.vmrk
- mne/io/brainvision/tests/test_brainvision.py
> Add support for offsets for arbitrary BrainVision marker types 

- mne/minimum_norm/psf_ctf.py
> bug overwritting params in _get_matrix_from_inverse_operator for PSF/CTF

- tutorials/plot_object_epochs.py
> MRG Epoch selection example

- .gitignore
Just a tiny update to the .gitignore
> MINOR: ignore emacs temp files

- mne/datasets/utils.py
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
fixes #5333
cc @Kstoffer can you check if I did not forget anything?
> [MRG] fix for neuroone brain vision files

- mne/cuda.py
- mne/tests/test_filter.py
> Fix resample output trimming bug

- doc/whats_new.rst
- mne/decoding/search_light.py
- mne/decoding/tests/test_search_light.py
> FIX : cross_val_predict with SlidingEstimator using predict_proba

- mne/viz/ica.py
> MRG fix order of plot_ica_properties for <py36

- mne/commands/mne_flash_bem.py
> [MRG][DOC] fix mne_flash_bem ussage 

- mne/viz/evoked.py
very small documentation addition to #5376
> MRG add doc

- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/data/testv2.vmrk
- mne/io/brainvision/tests/test_brainvision.py
> bug fix #5356 scan for BrainVision sections using ^ and $

- doc/documentation.rst
- mne/io/eeglab/eeglab.py
- mne/io/eeglab/tests/test_eeglab.py
> MRG Round eeglab latencies

- mne/beamformer/tests/test_dics.py
- mne/beamformer/tests/test_lcmv.py
- mne/channels/tests/test_interpolation.py
- mne/channels/tests/test_montage.py
- mne/decoding/tests/test_transformer.py
- mne/io/ctf/tests/test_ctf.py
- mne/io/edf/tests/test_edf.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/kit/tests/test_kit.py
- mne/io/tests/test_raw.py
- mne/io/tests/test_reference.py
- mne/preprocessing/tests/test_ica.py
This PR address some of the comments in #5409 that le let for latter.
@larsoner merge is you are happy
> [MRG] Be more precise about warnings (round 2)

- doc/whats_new.rst
- examples/inverse/plot_custom_inverse_solver.py
- mne/viz/_3d.py
- mne/viz/evoked.py
- mne/viz/misc.py
- mne/viz/tests/test_utils.py
- mne/viz/topo.py
- mne/viz/utils.py
> [MRG] use mpl default color cycle

- doc/whats_new.rst
- mne/beamformer/_compute_beamformer.py
- mne/beamformer/_dics.py
- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_dics.py
Second iteration for https://github.com/mne-tools/mne-python/issues/5109 to unify ``_lcmv`` and ``_dics``, also compare https://github.com/mne-tools/mne-python/pull/5134.
This PR will unify the shared code of ``_lcmv`` and ``_dics`` in a ``_compute_beamformer`` function.
This is still very much work in progress.
Once the new code is set up and generates identical results as the original implementations, we can start discussing further enhancements/unification of the code. I will ping people when I got so far.
cc @larsoner
> [MRG] Refactoring beamformer code, part II

- mne/io/base.py
- mne/tests/test_epochs.py
- mne/transforms.py
Is there a policy about the imports??
> [MRG] Either use copy.deepcopy or from copy import deepcopy but not both

- doc/conf.py
- doc/documentation.rst
- doc/glossary.rst
A glossary of MNE terms.
closes #5275
> WIP: Glossary

- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
> FIX: Fix MPL bug

- doc/documentation.rst
- doc/glossary.rst
- doc/manual/cookbook.rst
- doc/whats_new.rst
- tutorials/plot_background_freesurfer.py
- tutorials/plot_object_source_estimate.py
taking progressively pieces from source morph project.
> [MRG+1] add plot_object_source_estimate.py to documentation

- .circleci/config.yml
CircleCI has broken again. Time to try to fix it.
> FIX: Try no more workarounds

- doc/whats_new.rst
- mne/dipole.py
- mne/tests/test_dipole.py
- tutorials/plot_brainstorm_phantom_ctf.py
- tutorials/plot_brainstorm_phantom_elekta.py
Fixes the return type of `Evoked`, which was a bug (should never have been `ndarray`).
> MRG: Return residual as Evoked

- doc/whats_new.rst
- mne/cov.py
- mne/inverse_sparse/mxne_inverse.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
- tutorials/plot_mne_dspm_source_localization.py
> MRG: Add return_residual to minimum_norm

- doc/manual/cookbook.rst
- examples/inverse/plot_mixed_norm_inverse.py
- examples/inverse/plot_morph_surface_stc.py
- examples/inverse/plot_morph_volume_stc.py
- examples/visualization/plot_xhemi.py
- mne/inverse_sparse/mxne_inverse.py
- mne/inverse_sparse/tests/test_mxne_inverse.py
- mne/label.py
- mne/morph.py
- mne/source_estimate.py
- mne/tests/test_morph.py
- mne/tests/test_source_space.py
- tutorials/plot_mne_dspm_source_localization.py
- tutorials/plot_stats_cluster_spatio_temporal.py
- tutorials/plot_stats_cluster_spatio_temporal_2samp.py
- tutorials/plot_stats_cluster_spatio_temporal_repeated_measures_anova.py
attempt to fix circle + raise discussion on API.
> [MRG] fix circle, add subject attr in make_stc_from_dipoles and put src as 1st param

- examples/time_frequency/plot_compute_source_psd_epochs.py
- mne/decoding/csp.py
- mne/io/egi/egimff.py
- mne/minimum_norm/time_frequency.py
- mne/tests/test_epochs.py
- mne/tests/test_report.py
- mne/time_frequency/multitaper.py
- mne/utils.py
Modernizing the source epochs PSD function and example a bit.
> MRG: Cleaner source psd

- mne/io/eeglab/eeglab.py
- mne/io/eeglab/tests/test_eeglab.py
> [MRG] Save appropriate filename for EEGLAB standalone .set files

- doc/whats_new.rst
[contribution guidelines](https://martinos.org/mne/stable/contributing.html)
Example: Fixes #1234.
> [MRG] typo

- doc/sphinxext/cited_mne.py
- doc/sphinxext/ipython_console_highlighting.py
Should fix Circle failures about bad escape sequences.
> FIX: Fix escapes [circle front]

- doc/whats_new.rst
- mne/io/base.py
- mne/io/tests/test_raw.py
Fixes #5523 
This PR is required for #4936
> [MRG] ENH: modify time_as_index to allow arbitrary origin

- mne/commands/tests/test_commands.py
- mne/viz/misc.py
This should fix failures in `master` introduced by MPL 3.
> MRG: Matplotlib changes

- .travis.yml
Let's see if this fixes that pesky Travis no6 run.
> FIX: OpenBLAS

- tutorials/plot_mne_dspm_source_localization.py
Fixes the event code naming in our main tutorial.
> MRG+1: Event code

- examples/decoding/plot_decoding_time_generalization_conditions.py
- examples/decoding/plot_linear_model_patterns.py
- mne/decoding/base.py
- mne/decoding/tests/test_base.py
- mne/decoding/tests/test_ems.py
- mne/decoding/tests/test_search_light.py
- tutorials/plot_sensors_decoding.py
fix CI broken due to new sklearn 0.20
> fix for new sklearn 0.20

- bin/mne
- mne/commands/mne_flash_bem.py
> Fix couple of PEP8 errors.

- mne/io/tests/test_raw.py
> [MRG] Re-wording the parametrization of test_time_as_index_ref

- README.rst
- doc/documentation.rst
- examples/inverse/plot_lcmv_beamformer_volume.py
- mne/source_estimate.py
- mne/viz/_3d.py
- tutorials/plot_mne_dspm_source_localization.py
- tutorials/plot_visualize_stc.py
This is just to declare my intent ...
I'll finish the PR tomorrow
> [MRG] stc plotting tutorial

- doc/manual/c_reference.rst
- mne/channels/layout.py
- mne/io/artemis123/artemis123.py
Just spelling.
Noticed these going over #5575.
Errrr ... I think I created this on the main repo? I used the web interface ...
> MINOR: spelling

- environment.yml
- mne/io/constants.py
- mne/io/tests/test_constants.py
This hopefully fixes the CIs. Also syncs our constants tests with `fiff-constants`.
> MRG: Fix CIs

- doc/whats_new.rst
- mne/io/egi/egimff.py
> MRG: Fix egimff

- doc/whats_new.rst
- mne/channels/channels.py
- mne/channels/interpolation.py
- mne/channels/tests/test_interpolation.py
- mne/forward/_field_interpolation.py
> MRG: Expose origin parameter

- doc/whats_new.rst
- mne/channels/channels.py
- mne/io/fiff/tests/test_raw_fiff.py
Closes #5382.
@alexrockhill can you see if it fixes your issue?
> MRG: Resize memmap when adding channels

- doc/whats_new.rst
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
- mne/tests/test_chpi.py
- mne/tests/test_utils.py
- mne/utils.py
Closes #5592.
@cbrnr can you verify it fixes your issue?
The changes in `test_maxwell.py` are from when I started to modify the file to accommodate these changes before I realized there was a simpler solution (monkey-patching the `catch_logging` handler), but the changes ended up being nice anyway so I decided to leave them in.
> MRG: Only output one warning

- doc/python_reference.rst
- doc/whats_new.rst
- examples/inverse/plot_dics_source_power.py
- examples/inverse/plot_lcmv_beamformer.py
- examples/inverse/plot_lcmv_beamformer_volume.py
- mne/beamformer/__init__.py
- mne/beamformer/_compute_beamformer.py
- mne/beamformer/_dics.py
- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_dics.py
- mne/beamformer/tests/test_lcmv.py
- mne/utils.py
- tutorials/plot_dics.py
Closes #4957.
cc @wmvanvliet @britta-wstnr (and @kingjr since you opened the original issue)
> MRG: Add I/O and repr to beamformers

- doc/whats_new.rst
- mne/epochs.py
- mne/filter.py
- mne/tests/test_epochs.py
Closes #5614.
@alexrockhill can you verify this fixes your issue?
I also replaced `_TempDir` calls with pytest `tmpdir` fixture, something that I think we can do gradually as we find them.
> MRG: Fix filtering check

- mne/annotations.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/edf/tests/test_gdf.py
> [WIP] [ENH] add events from annotations for EDF files

- mne/channels/layout.py
- mne/utils.py
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
> MRg Fix ERP sensor legend plotting

- mne/viz/tests/test_topomap.py
> MRG: Bad regex

- mne/commands/mne_browse_raw.py
Fixes #5655 .
Changed the call to the add_option of the parser to set a flag to true instead of value
> Modified the call to browse_raw parameters to accept --preload param

- mne/forward/forward.py
- mne/viz/_3d.py
- tutorials/plot_background_filtering.py
- tutorials/plot_background_statistics.py
> MRG: Fix flake

- mne/epochs.py
- mne/filter.py
- mne/tests/test_epochs.py
> MRG: Make epochs.times read only

- doc/install_mne_c.rst
> DOC: Update commands

- doc/whats_new.rst
- ignore_words.txt
- mne/channels/montage.py
- mne/viz/tests/test_montage.py
- mne/viz/utils.py
Eventually will fix what #5675 works around. This fixes that failure but introduces another. I see how to fix it but won't have time for a few hours.
So @massich it's probably not worth merging #5675
> MRG: Fix plot_montage

- appveyor.yml
Let's see if this fixes AppVeyor.
> FIX: AppVeyor

- mne/io/tests/test_constants.py
Just tracking trivial updates from `fiff-constants`. Will merge once CIs come back happy.
> MRG: Update constant test

- mne/datasets/brainstorm/bst_auditory.py
- mne/datasets/brainstorm/bst_phantom_ctf.py
- mne/datasets/brainstorm/bst_phantom_elekta.py
- mne/datasets/brainstorm/bst_raw.py
- mne/datasets/brainstorm/bst_resting.py
- mne/datasets/mtrf/__init__.py
- mne/datasets/tests/test_datasets.py
- mne/datasets/utils.py
Closes #5624.
Probably not perfect but it seems to work for the ones I have on my system. You can see locally with:
```
pytest -s mne/datatsets
```
It should print the "have" status for a bunch of datasets.
> MRG: Fix dataset check [ci skip]

- doc/whats_new.rst
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
- mne/minimum_norm/time_frequency.py
> MRG: Fix check for prepared

- tutorials/plot_object_annotations.py
Follow-up on the last annotations tutorial, some clarifications, sometimes slightly different wording. See if you agree.
> DOC: small fixes to the annotations tutoiral

- examples/connectivity/plot_mixed_source_space_connectivity.py
- examples/inverse/plot_mixed_source_space_inverse.py
- mne/utils.py
- tutorials/plot_brainstorm_phantom_elekta.py
CircleCI timed out, this should make the elekta example slightly faster.
Fixes a small bug where ProgressBar shouldn't have printed.
Tweaks wording @agramfort asked for in #5707.
> MRG: Faster example

- .circleci/config.yml
Let's see if this makes CircleCI go faster.
> FIX: Tweak cores [skip appveyor] [skip travis] [circle full]

- Makefile
- README.rst
Found with
python setup.py check --restructuredtext
And added to the Travis run, as now it's in `make pep`.
> MRG: Check README.rst

- .circleci/config.yml
- doc/_templates/navbar.html
- mne/__init__.py
This PR requires https://github.com/mne-tools/mne-tools.github.io/pull/13
> [RELEASE][DOC] Archive 0.16 and add 0.17 to navigation bar

- doc/whats_new.rst
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
Following conversation with @sarangnemo today, I thought I can attack a few low hanging fruits from #5457
> [MRG] ENH: navigate time with keyboard in plot_volume_source_estimates

- mne/inverse_sparse/mxne_optim.py
`sklearn` rejected my PR so this is how we can easily work around the problem.
> MRG: Fix for sklearn

- mne/beamformer/_compute_beamformer.py
[contribution guidelines](https://martinos.org/mne/stable/contributing.html)
Example: Fixes #1234.
> Array equal

- .travis.yml
- conftest.py
- mne/event.py
- mne/tests/test_docstring_parameters.py
- mne/utils.py
- requirements.txt
- setup.cfg
Should get tests passing on 3.7, and enable one of our Travis runs to use 3.7.
> MRG: Minor fixes for 3.7

- .travis.yml
- mne/externals/pymatreader/utils.py
- mne/preprocessing/tests/test_ica.py
- requirements.txt
Before #5827, maint branch should be green.
> [WIP] make maint/0.17 CI green

- setup.cfg
Alternative fix for 3.7 due to likely wheel build async.
> FIX: Fix for bad import

- mne/io/ctf/info.py
> strip for ctf date header

- conftest.py
- mne/gui/tests/test_coreg_gui.py
- mne/report.py
- setup.cfg
Just a few minor things I noticed in #5806 that could be cleaned up.
> MRG: Minor testing fixes

- doc/conf.py
- doc/manual/datasets_index.rst
- examples/visualization/plot_channel_epochs_image.py
- tutorials/plot_python_intro.py
- tutorials/plot_sensors_decoding.py
Just some minor tweaks to fix `make linkcheck`:
https://circleci.com/gh/mne-tools/mne-python/11092
> MRG: Fix links

- mne/utils/numerics.py
> fix #5909 with np.int64 in object_diff

- doc/_static/style.css
Should fix the problem @drammock had.
> MRG: FIX: CSS

- .circleci/config.yml
- requirements.txt
Hopefully this fixes CIs. 5.12 was released 8 hours ago so it's a good candidate for causing our problems.
> FIX: Dont run 5.12

- mne/viz/epochs.py
- mne/viz/tests/test_epochs.py
> FIX : #5906 epochs plot index error

- doc/whats_new.rst
- mne/annotations.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/tests/test_raw.py
- mne/tests/test_annotations.py
- mne/utils/testing.py
- mne/viz/raw.py
- mne/viz/utils.py
Closes #5854.
Would be good to merge #5895 first, which contains some `Annotations`-related tweaks and new tests.
> MRG+1: Keep annotations sorted

- .circleci/config.yml
Let's see if we can simplify CircleCI.
> MAINT: Do not patch Qt

- .circleci/config.yml
- .travis.yml
- doc/conf.py
- examples/inverse/plot_morph_volume_stc.py
- requirements.txt
Next step is to see why 5.12 breaks on CircleCI, since SSH access is available there. Then hopefully we can use it to fix Travis.
> MRG: Allow Qt 5.12 and use `pip` on CircleCI

- examples/visualization/plot_3d_to_2d.py
- ignore_words.txt
- mne/viz/evoked.py
- tutorials/plot_artifacts_correction_ssp.py
- tutorials/plot_ecog.py
CircleCI is failing on master due to #5932 and this (using generator in `vstack`).
> BUG: Fix vstack on CircleCI

- doc/whats_new.rst
- mne/io/edf/edf.py
> [MRG] Use latin-1 encoding for some EDF header fields

- examples/inverse/plot_covariance_whitening_dspm.py
- examples/inverse/plot_lcmv_beamformer_volume.py
- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_lcmv.py
- mne/preprocessing/tests/test_ica.py
- mne/preprocessing/tests/test_maxwell.py
- mne/rank.py
- mne/tests/test_cov.py
- mne/tests/test_rank.py
Todo:
The second one is not straightforward, so I'll probably tackle it Monday.
> MRG: Fix CircleCI

- examples/inverse/plot_custom_inverse_solver.py
- examples/simulation/plot_simulate_raw_data.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
- mne/simulation/raw.py
- mne/simulation/tests/test_raw.py
Fixes two failures [on CircleCI in master](https://circleci.com/gh/mne-tools/mne-python/11491).
> BUG: Fix bugs with picking

- mne/datasets/sleep_physionet/_utils.py
- mne/datasets/sleep_physionet/age.py
- mne/datasets/sleep_physionet/temazepam.py
- tutorials/plot_sleep.py
> Fix: physionet url

- LICENSE.txt
- README.rst
> [MRG]License Update

- .gitignore
- .travis.yml
- azure-pipelines.yml
- conftest.py
- environment.yml
- mne/inverse_sparse/tests/test_mxne_inverse.py
- mne/tests/test_epochs.py
- mne/utils/testing.py
- requirements.txt
- setup.cfg
> MRG: Azure

- .circleci/config.yml
- .gitignore
- doc/conf.py
- setup.cfg
Let's see if https://github.com/sphinx-gallery/sphinx-gallery/pull/454 makes things better for us.
> MRG: Use JUnit on CircleCI

- azure-pipelines.yml
Use the same MNE_FORCE_SERIAL we have on AppVeyor to avoid things like https://github.com/mne-tools/mne-python/pull/6013/checks?check_run_id=72063902
> FIX: Serial

- mne/datasets/utils.py
Fix #5826 - let's see if everything still works with this change.
> [MRG] Remove onerror handler for shutil.rmtree

- mne/externals/decorator.py
- mne/forward/_make_forward.py
- mne/inverse_sparse/mxne_optim.py
- mne/viz/backends/renderer.py
- tutorials/plot_background_filtering.py
- tutorials/plot_dipole_orientations.py
> MRG: LGTM fixes

- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- mne/utils/check.py
> corrmap better error when instances have different channels

- azure-pipelines.yml
- examples/inverse/plot_dics_source_power.py
Should fix the failing example.
> BUG: Multiple ch types is an error

- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
> Require sklearn only for FastICA

- doc/whats_new.rst
- mne/io/egi/egimff.py
- mne/io/egi/tests/test_egi.py
closes #6031
ok for you @petergrey75 ?
> Fix mff crop no preload

- mne/io/constants.py
- mne/io/tests/test_constants.py
Update from https://github.com/mne-tools/fiff-constants/pull/18
> MAINT: Update constants

- setup.py
> Add install requires

- mne/viz/topo.py
- mne/viz/utils.py
- setup.cfg
closes #6101
- allows secondary figure popup when clicking in `epochs.plot_topo_image`, even if user hasn't set `plt.ion()`
- in `raw.plot_psd_topo`, avoids `TypeError: can only concatenate list (not "NoneType") to list` when clicking on a thumbnail sensor plot
- in popup figures spawned by `raw.plot_psd_topo` clicking:
- avoids `TypeError: 'NoneType' object is not subscriptable` error on mouseover of axes area
- fixes x axis label
> MRG+1: interactivity in raw.plot_psd_topo() and epochs.plot_topo_image()

- mne/bem.py
Provide a more helpful hint about how to deal with custom BEM surfaces. From the mailing list.
> DOC: Better err msg for ico

- tutorials/plot_object_raw.py
Tiny fix for problem in tutorial I discovered during workshop
> FIX len(raw) is not n_channels

- tutorials/plot_introduction.py
- tutorials/plot_object_epochs.py
> MINOR Fix warnings in two docs introduced in #6108

- examples/connectivity/plot_mne_inverse_envelope_correlation.py
- mne/connectivity/utils.py
thershold was super misleading. I thought it means a threshold value of connectivity entries but it's actually a percentage of edges to keep. Also I made the default 0.2 as 1 makes little sense (all degrees would be n_nodes).
cc @dengemann @larsoner
> rename threshold to threshold_percent

- mne/connectivity/envelope.py
- mne/connectivity/tests/test_envelope.py
- mne/epochs.py
- mne/utils/__init__.py
- mne/utils/check.py
- add callable option to combine
- make mean the default and not median
still todo is be able to disable the orthogonalization
> WIP: change API of envelope_correlation

- mne/report.py
- mne/tests/test_report.py
> MRG: Better type check for report

- environment.yml
> fix for #6144

- .travis.yml
- azure-pipelines.yml
Following #6145 and #6120 (related to https://github.com/labstreaminglayer/liblsl-Python/issues/6) I think our LSL code is currently untested. This should hopefully restore testing to the platforms.
@teonbrooks can you look and take over / push commits until it works?
> MRG: Restore LSL tests

- environment.yml
- mne/datasets/sleep_physionet/_utils.py
- mne/datasets/sleep_physionet/tests/test_physionet.py
> fix skip pandas 0.24

- mne/viz/evoked.py
- mne/viz/topo.py
- mne/viz/utils.py
> [MINOR] Remove unnecessary picks in _plot_masked_image

- doc/contributing.rst
Fixes #6180.
This commit adds additional explanation to the contributing guide.
> MRG: additional explanation to the contributing guide.

- mne/annotations.py
- mne/tests/test_annotations.py
> DOC: make sure you get a warning when reading onsets which are not timestamps

- mne/channels/layout.py
- mne/viz/topomap.py
closes #6030
as we don't have an Info to pick by types.
> fix doc on plot_layout

- mne/realtime/lsl_client.py
[contribution guidelines](https://martinos.org/mne/stable/contributing.html)
Example: Fixes #1234.
> Comment use of keywords in pylsl.resolve_byprop.

- doc/manual/migrating.rst
> MRG: [MINOR, DOCS] Add newer plot functions to Migrating from EEGLAB

- mne/viz/evoked.py
Like #6186, but for time series.
> MRG: Refactor ts plotter

- examples/preprocessing/plot_eog_artifact_histogram.py
- mne/decoding/ems.py
- mne/epochs.py
- mne/realtime/epochs.py
- mne/tests/test_epochs.py
- mne/time_frequency/psd.py
- mne/viz/epochs.py
- mne/viz/tests/test_epochs.py
- tutorials/plot_sleep.py
Closes #6171
What about an exclude param (for exclude="bads")?
> MRG: Picks argument to epochs.get_data 

- doc/whats_new.rst
- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
- mne/tests/test_source_estimate.py
- tutorials/plot_epochs_to_data_frame.py
This simplifies the use of regression models that expect the long format but also makes it easy to process the data in R and ggplot.
Todo:
cc @JoseAlanis @jona-sassenhagen
> [MRG]: add long format option to ToDataFrameMixin

- mne/annotations.py
- mne/tests/test_annotations.py
fixes test for annotations from CSV that use floats as onsets
> fix annotations test

- azure-pipelines.yml
> MAINT: Fix Azure

- mne/beamformer/_rap_music.py
- mne/beamformer/tests/test_rap_music.py
Circle [showed](https://circleci.com/gh/mne-tools/mne-python/12603) that #6042 introduced a bug with RAP-MUSIC picking. This fixes the issue and adds a regression test.
> MRG: Fix RAP-MUSIC with picks

- mne/evoked.py
- tutorials/plot_eeg_erp.py
- tutorials/plot_introduction.py
> [MRG] +1 FIX documentation of combine_evoked

- mne/decoding/base.py
> cross_val_multiscore docstring more explicit

- mne/utils/docs.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/_vtki.py
Improvement to docs decorator, no need to provide base classes as parameters.
Implemented during 2019 MNE Sprint
> Decorator improvement

- doc/whats_new.rst
This PR only updates the changelog in "What's new".
> update changelog [ci skip]

- tutorials/plot_epochs_to_data_frame.py
Before merging let's think of other places where we might want to add the link.
> DOC/ENH: Ladd link to MNE-R

- doc/python_reference.rst
- doc/whats_new.rst
- examples/simulation/plot_source_simulator.py
- mne/simulation/__init__.py
- mne/simulation/source.py
- mne/simulation/tests/test_source.py
Squashed version of #6212. Should be rebase+merged (or standard merged) instead of squash+merged so that commit authors retain credit/blame.
> MRG: Add SourceSimulator class

- examples/realtime/plot_rt_feedback_server.py
- mne/realtime/mock_lsl_stream.py
- mne/realtime/tests/test_lsl_client.py
allows the stream to loop if it reaches the end of the file
> [MRG] ENH: make the stream loop when the raw file is at the end

- mne/utils/_bunch.py
- mne/utils/tests/test_bunch.py
> [MRG] Fix pickling of NamedInt and NamedFloat

- mne/time_frequency/psd.py
> DOC: small fix in docstring of psd_welch

- doc/whats_new.rst
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
> [MRG] small ICA bug fixes for #5967 - 2nd try

- mne/datasets/utils.py
> Update MNE testing data version

- setup.cfg
Should fix https://travis-ci.org/mne-tools/mne-python/jobs/531442276 etc.
> MRG, MAINT: Register pytest markers

- mne/time_frequency/tfr.py
> MINOR, VIZ Remove superficial bracket from tfr image plot title

- mne/datasets/tests/test_datasets.py
- mne/datasets/utils.py
This first commit should pass on Linux and fail on Windows. Then I'll push a commit that should pass on both.
Closes #6292.
> FIX: TDD on datasets

- doc/whats_new.rst
- mne/fixes.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
Adds a "Toggle all" option that I've been longing for since the days of MNE-C:
> MRG, ENH: Add toggle all proj option

- README.rst
- azure-pipelines.yml
- conftest.py
- doc/whats_new.rst
- environment.yml
- mne/viz/_3d.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/_utils.py
- mne/viz/backends/renderer.py
- mne/viz/backends/tests/_utils.py
- mne/viz/backends/tests/test_renderer.py
- mne/viz/tests/test_3d.py
- requirements.txt
> MRG, MAINT: Migrate VTKi -> PyVista

- examples/inverse/plot_dics_source_power.py
The old DICS example was done on the mne-sample dataset, but DICS is demonstrated better on data that has clear oscillatory activity. This PR changes the example to apply DICS to the "somato" data to localize the ERS in the beta band.
> MRG: Improve DICS example

- mne/viz/misc.py
> MRG, DOC: better docs / error msgs for plot_events

- doc/whats_new.rst
- mne/gui/_viewer.py
- mne/gui/tests/test_coreg_gui.py
Seeing if we can make some progress on #5728, first by modifying the test infrastructure we use.
> MRG, FIX: Modernize coreg tests

- mne/forward/_make_forward.py
- mne/forward/tests/test_make_forward.py
- mne/tests/test_bem.py
- mne/transforms.py
> MRG, DOC: Better forward error message

- mne/cov.py
> MRG, BUG: Avoid sklearn deprecation warning

- doc/documentation.rst
- doc/whats_new.rst
- examples/simulation/plot_simulated_raw_data_using_subject_anatomy.py
This pull request replaces #6256.
> WIP: Add example to simulate raw data using subject anatomy

- tutorials/intro/plot_introduction.py
> FIX: use filtered raw to reduce memory in overview tut

- doc/conf.py
- mne/decoding/transformer.py
- mne/filter.py
- mne/fixes.py
- mne/io/base.py
- mne/io/bti/bti.py
- mne/io/egi/egi.py
- mne/io/egi/egimff.py
- mne/tests/test_filter.py
- mne/utils/docs.py
- mne/viz/misc.py
- tutorials/discussions/plot_background_filtering.py
Report filter params.
~~WIP because I want to add `freqz`-based tests that actually check the -6 and -12 dB points.~~
Closes #5226.
> MRG, ENH: Add clearer filter characteristics

- doc/whats_new.rst
- mne/annotations.py
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
- mne/io/edf/tests/test_edf.py
- mne/tests/test_annotations.py
- mne/tests/test_docstring_parameters.py
> MRG: Brainvision events_from_annotations

- .circleci/config.yml
- mne/datasets/sleep_physionet/__init__.py
- mne/datasets/utils.py
- tutorials/sample-datasets/plot_sleep.py
3b75010ffdffabf1146f7ca7700e51f93bba3ac6 fixed part of this problem, but I realized we should also update `.circle/config.yaml`. :(
> MRG, ENH: Add to list of downloads

- .circleci/config.yml
- environment.yml
- examples/decoding/plot_receptive_field_mtrf.py
- ignore_words.txt
- mne/label.py
- requirements.txt
Updates the `mayavi` version and hopefully ensures that CircleCI actually uses a newer one.
> MRG, ENH: Bump mayavi, be better about CircleCI updates

- .circleci/config.yml
- doc/_templates/navbar.html
- mne/__init__.py
This PR requires https://github.com/mne-tools/mne-tools.github.io/pull/15
> [RELEASE][DOC] Archive 0.17 and add 0.18 to navigation bar

- examples/visualization/plot_roi_erpimage_by_rt.py
- mne/io/brainvision/brainvision.py
- mne/io/cnt/cnt.py
- mne/io/cnt/tests/test_cnt.py
- mne/io/eeglab/eeglab.py
- mne/io/eeglab/tests/test_eeglab.py
Should hopefully fix Travis, Azure, and CircleCI (full).
> MRG, MAINT: More deprecations

- .travis.yml
- azure-pipelines.yml
- setup.cfg
While setting up mne-realtime I realized we had a few minor bugs in our CI config. This simplifies and fixes them.
> MRG, MAINT: Codecov on pip req run

- mne/event.py
- mne/tests/test_event.py
- mne/utils/config.py
> Better find_events message if no stim channel is found

- doc/whats_new.rst
- mne/evoked.py
- mne/io/constants.py
- mne/tests/test_evoked.py
Closes #6359.
@jjnurminen can you confirm it fixes your problem?
> MRG, BUG: Fix handling of aspect

- doc/install/pre_install.rst
- doc/links.inc
- mne/io/meas_info.py
- fix outdated link to BIDS specification
- correct rst link syntax
- add new link to BIDS in the docs, when it is first mentioned
> DOC: Fix/add links to BIDS

- doc/whats_new.rst
- mne/inverse_sparse/mxne_inverse.py
- mne/inverse_sparse/tests/test_mxne_inverse.py
> MRG, FIX: weights_min in mixed_norm

- doc/install/mne_python.rst
- doc/sphinxext/sphinx_bootstrap_divs/__init__.py
> MRG, ENH: Add some troubleshooting to install docs

- .circleci/config.yml
- examples/datasets/load_limo_dataset.py
- examples/datasets/plot_limo_data.py
- mne/datasets/__init__.py
- mne/datasets/limo/__init__.py
- mne/datasets/limo/limo.py
Closes #6075 
Add example code to load single subject data from the LIMO dataset, creating an MNE epochs structure and computing the evoked response for experimental conditions.
> MRG[+1]: adds limo dataset example code

- .gitignore
- mne/beamformer/_compute_beamformer.py
- mne/beamformer/tests/test_lcmv.py
I noticed that `make_lcmv` does not output anything even though it spends some time computing values. This gives some minimal status updates.
> MRG, DOC: Add logging to beamformer

- mne/annotations.py
- mne/tests/test_annotations.py
> Fix error when checking annotations with negative timestamps

- doc/install/mne_python.rst
cf https://github.com/mne-tools/mne-python/pull/6393/
> DOC FIX: add warning about shell

- mne/datasets/limo/limo.py
Hey guys, 
I'm adding the remaining URLs to the limo fetcher to provide support for the whole LIMO dataset.
In the original PR we only allowed the download of two subjects.
Best,
José
> add urls to limo fetcher

- doc/tutorials/report.rst
- doc/whats_new.rst
- mne/io/base.py
- mne/io/fiff/raw.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/utils/tests/test_check.py
needed for #6414 
related to #4950
> BIDS compliance: allow raw fif files to end on `_meg.fif`

- doc/whats_new.rst
- mne/preprocessing/tests/test_ica.py
- mne/viz/epochs.py
- mne/viz/ica.py
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
See below.
~~Eventually this can probably be extended to work for butterfly plots, but the overlay of grad+mag there might be a problem. (We could actually add one at the top and bottom in this case, but for now it's not implemented.)~~
~~Also at some point we might want to use the number formatting that #6210 fixed/used.~~
> MRG, ENH: Add scale bars to raw.plot

- examples/preprocessing/plot_eog_artifact_histogram.py
- tutorials/misc/plot_sensor_locations.py
Fixes the failures here:
https://circleci.com/gh/mne-tools/mne-python/13597?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification
> MRG, BUG: Fix warnings in examples

- doc/documentation.rst
- doc/glossary.rst
- tutorials/source-modeling/plot_background_freesurfer.py
spotted while browsing through the docs.
some evidence:
> [minor] formatting fixes

- doc/install/contributing.rst
- doc/python_reference.rst
> DOC: add deprecation section to contributing guide

- doc/whats_new.rst
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
> fix vectorview 122 with plot_compare_evoked

- doc/install/freesurfer.rst
- tutorials/raw/plot_object_raw.py
Fixes linking:
https://circleci.com/gh/mne-tools/mne-python/13646?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification
cc @drammock in case you do more of these in the future
> MRG, DOC: Links

- Makefile
- doc/tutorials/report.rst
Should fix the `circle` error in `master` running `make test-doc`.
> MRG, FIX: test-doc [circle front]

- mne/viz/raw.py
- mne/viz/tests/test_raw.py
> [backport #6429] MAINT: Add params to raw.plot figure

- doc/whats_new.rst
- mne/datasets/tests/test_datasets.py
- mne/report.py
Backport #6434 (the fix part of #6433)
> MRG, FIX: Fix report segfault

- doc/whats_new.rst
- mne/preprocessing/tests/test_ica.py
- mne/viz/raw.py
- mne/viz/utils.py
> MRG+1: Add remove_dc argument to _compute_scalings

- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
Follow-up for #6403 where the BEM solution is provided instead of the BEM model surfaces. No need for `whats_new` update as it's in #6403.
> MRG, ENH: Allow homog with head

- examples/io/plot_read_proj.py
- tutorials/preprocessing/plot_artifacts_correction_rejection.py
- tutorials/raw/README.txt
- tutorials/raw/plot_visualize_raw.py
also updates a couple of links to that tutorial.
> DOC: update "visualizing raw" tutorial

- mne/io/egi/egi.py
Fixes 2 alerts detected by LGTM in [this discussion](https://github.com/mne-tools/mne-python/pull/6464#discussion_r295256929).
> MRG, FIX: Fix EGI

- tutorials/intro/README.txt
- tutorials/intro/plot_introduction.py
- tutorials/intro/plot_projectors_intro.py
- tutorials/raw/plot_annotating_raw.py
- tutorials/raw/plot_object_raw.py
- tutorials/raw/plot_visualize_raw.py
Also:
- resolves several TODOs in other tutorials that were waiting for cross-refs to this one
- updates the README of the intro section to better reflect the content of the tutorials in there
> MRG, DOC: adds "projectors overview" tutorial

- doc/whats_new.rst
- mne/io/fieldtrip/tests/helpers.py
- mne/io/reference.py
- mne/io/tests/test_reference.py
Closes #6454.
@kdoelling1919 can you confirm this at least prevents the dangerous behavior you observed?
> MRG, BUG: Avoid referencing all data

- tutorials/intro/plot_projectors_intro.py
Fixes https://circleci.com/gh/mne-tools/mne-python/13861
cc @drammock
> MRG, DOC: Fix links

- mne/connectivity/spectral.py
- mne/cuda.py
- mne/decoding/tests/test_receptive_field.py
- mne/filter.py
- mne/fixes.py
- mne/tests/test_epochs.py
- mne/time_frequency/csd.py
- mne/time_frequency/multitaper.py
Now that the scipy.fft namespace exists:
https://github.com/scipy/scipy/pull/10238
We should use it.
> MRG, ENH: Prefer scipy.fft.rfft

- mne/dipole.py
- mne/viz/_3d.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/renderer.py
- tutorials/misc/plot_ecog.py
- tutorials/misc/plot_sensor_locations.py
- tutorials/sample-datasets/plot_brainstorm_phantom_elekta.py
- tutorials/sample-datasets/plot_phantom_4DBTi.py
- tutorials/simulation/plot_dics.py
- tutorials/simulation/plot_point_spread.py
- tutorials/source-modeling/plot_dipole_orientations.py
- tutorials/source-modeling/plot_forward.py
- tutorials/source-modeling/plot_source_alignment.py
cc @GuillaumeFavelier 
remaining ones are related to plotting of dipoles
> [WIP] remove mlab from tutorials

- doc/whats_new.rst
- mne/viz/utils.py
As pointed out by #6500, the changes done in #6451 broke average plotting when area_mode="range." This fixes that, and also sets linewidth=0.5, and passes along the line_alpha parameter to plot.
> BUG: area_mode="range" in viz._plot_psd is wrong.

- mne/channels/montage.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
should be merged and rebased after #6511
> use set_montage in edf reader

- mne/channels/tests/test_montage.py
- mne/io/brainvision/tests/test_brainvision.py
- mne/io/cnt/tests/test_cnt.py
- mne/io/edf/tests/test_edf.py
- mne/io/eeglab/tests/test_eeglab.py
- mne/io/egi/tests/test_egi.py
- mne/io/nicolet/tests/test_nicolet.py
This PR refactors into a single test all the testing introduced by the following PRs:
#6511, #6513, #6497, #6496, #6480, #6469, #6471, #6476
> MNT, TST: refactor read_raw_FOO set_montage test

- mne/io/eeglab/tests/test_eeglab.py
So far this PR rewrites an existing test to discuss which is the desired behaviour
> MNT, TST: clarify existing behavior of set_montage / __init__ montage

- doc/carousel.inc
> MRG, DOC: fix carousel links

- mne/viz/epochs.py
> [MRG] Use int labels on epochs.plot x axis

- examples/visualization/plot_roi_erpimage_by_rt.py
- mne/viz/epochs.py
- tutorials/epochs/plot_metadata_epochs.py
- tutorials/epochs/plot_visualize_epochs.py
- tutorials/intro/plot_10_overview.py
- tutorials/stats-sensor-space/plot_stats_spatio_temporal_cluster_sensors.py
- Fixes doc build errors arising from recent deprecations related to montage and epochs/evoked plotting functions.
- Fixes a bug in `plot_epochs_image` where an input dict was not deepcopied, and thus the global variable was getting modified.
> Fix tutorial deprecations

- doc/_static/style.css
- doc/conf.py
- doc/sphinxext/sphinx_bootstrap_divs/__init__.py
- doc/sphinxext/sphinx_bootstrap_divs/bootstrap_divs.css
- doc/sphinxext/sphinx_bootstrap_divs/bootstrap_divs.js
- environment.yml
- mne/conftest.py
- mne/epochs.py
- requirements.txt
Backports #6540 (instructions only) #6393 #6372
Builds `html_dev-noplot` locally without error, hopefully the CIs come back green, we merge, and the CircleCI full build comes back green, but I doubt it!
> MAINT: Backport installation instructions

- mne/channels/channels.py
> FIX: add FIFF unit 'CEL' to mapping

- tutorials/epochs/plot_visualize_epochs.py
> reduce memory footprint

- mne/viz/backends/_pyvista.py
- mne/viz/backends/tests/_utils.py
Fixes #6576 by catching the deprecation warnings.
> FIX,VIZ: Fix DeprecationWarning in pyvista backend

- tutorials/preprocessing/plot_10_preprocessing_overview.py
Minor changes based on comments from @dengemann after tutorial was already merged.
> DOC: tweaks to preprocessing overview tutorial

- mne/io/base.py
closes #6583 (I think)
cc @bdyetton 
can you check if it works for you?
> FIX : EDF reading with long names that are the same for the first 15c

- azure-pipelines.yml
- environment.yml
Testing CIs hoping to reproduce the `LinkError` found in #6270 and #6551 on Azure for the `Windows Python37-64bit-full-conda` build.
> TST: Testing CIs for LinkError on Azure

- doc/whats_new.rst
- mne/io/edf/edf.py
> FIX: unit mV in EDF reader

- mne/bem.py
- mne/commands/mne_make_scalp_surfaces.py
> improve error message make_scalp_surfaces

- doc/whats_new.rst
- mne/preprocessing/ica.py
- mne/viz/ica.py
- mne/viz/tests/test_ica.py
- tutorials/preprocessing/plot_40_artifact_correction_ica.py
- tutorials/preprocessing/plot_45_ica_from_raw.py
> MRG: Fix side effects in ica.plot_sources

- doc/whats_new.rst
- mne/viz/epochs.py
- mne/viz/ica.py
Closes #6615.
@jshanna100 can you confirm this fixes your problem?
> MRG, BUG: Fix scaling of sources

- doc/whats_new.rst
- mne/annotations.py
- mne/tests/test_annotations.py
> FIX: set_annotations when meas_date is prior to 1970

- doc/whats_new.rst
- mne/annotations.py
- mne/tests/test_annotations.py
- tutorials/raw/plot_30_annotate_raw.py
Fix regression introduced in #6628
> FIX: set_annotation regression introduced in #6628

- mne/source_estimate.py
This PR refactors _make_stc in order to simplify #6609
> MNT: refactor _make_stc

- mne/viz/epochs.py
- mne/viz/tests/test_epochs.py
Closes #6632.
Can test with:
```
import mne
path =  mne.datasets.sample.data_path()
raw = mne.io.Raw(path + '/MEG/sample/sample_audvis_raw.fif')
events = mne.read_events(path + "/MEG/sample/sample_audvis_raw-eve.fif")
epo = mne.Epochs(raw, events)
epo.plot()
```
@jshanna100 can you see if this fixes your problem?
> BUG: Fix numbering regression

- doc/links.inc
- tutorials/discussions/plot_background_statistics.py
I found this information useful, probably worth adding to the stats tutorial about clustering.
> DOC: Add link to discussion of cluster effect size

- .circleci/config.yml
- examples/time_frequency/plot_source_power_spectrum_opm.py
- examples/time_frequency/plot_time_frequency_global_field_power.py
- tutorials/epochs/plot_visualize_epochs.py
- tutorials/raw/plot_40_visualize_raw.py
There was a failure on CircleCI for `plot_visualize_epochs.py`. This PR fixes it.
WIP because I'm running it with https://github.com/sphinx-gallery/sphinx-gallery/pull/523 which will show the memory usage of all examples. Maybe there are others we should fix.
> MRG, MAINT: Reduce memory

- doc/glossary.rst
- examples/preprocessing/plot_movement_compensation.py
- mne/preprocessing/maxwell.py
- tutorials/preprocessing/plot_60_maxwell_filtering_sss.py
> MRG, DOC: update SSS / Maxfilter tutorial

- tutorials/preprocessing/plot_10_preprocessing_overview.py
incorporate missed feedback from Denis (plot_joint)
> MRG, DOC: tweak preprocessing overview tutorial

- doc/whats_new.rst
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
- tutorials/raw/plot_40_visualize_raw.py
Fixes the squared, and also fixes a bug where the same ylabel was used for all axes.
Closes #6662.
> MRG, FIX: Fix PSD labels

- doc/whats_new.rst
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/datasets/utils.py
superseding  #6402 for BrainVision CapTrak digitization format
this is adding the functionality to read `.bvct` files, which is an XML format for digitized sensor positions used by the CapTrak device by Brain Products.
This will need the mne-testing-data dataset to be updated: https://github.com/mne-tools/mne-testing-data/pull/49
**references**
- The device on the [manufacturers website](https://pressrelease.brainproducts.com/captrak/)
- The fieldtrip Wiki entry that I made for it: [see here](http://www.fieldtriptoolbox.org/faq/how_are_the_different_head_and_mri_coordinate_systems_defined/#details-of-the-captrack-coordinate-system)
<details><summary> Example BVCT file </summary>
```
<?xml version="1.0"?>
<BrainVisionCapTrakFileV1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" …
```
> MRG, ENH: Add digitization format BrainVision CapTrak BVCT

- doc/conf.py
> fix dipy intersphinx; closes #6671

- doc/whats_new.rst
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/open.py
- mne/utils/__init__.py
- mne/utils/misc.py
Closes #6657. cc @hoechenberger
> MRG, ENH: Better support for str-like objects

- doc/whats_new.rst
- mne/dipole.py
- mne/epochs.py
- mne/evoked.py
- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/simulation/tests/test_raw.py
- mne/source_estimate.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
- mne/time_frequency/tfr.py
- mne/utils/docs.py
- mne/utils/numerics.py
Closes #6652.
I stopped adding tests after doing Raw/Epochs/Evoked because they should be general enough to catch the others (SourceEstimate, AverageTFR, Dipole).
> MRG, ENH: Add include_tmax to cropping methods

- mne/utils/progressbar.py
Much smoother `MB/s` updates (by scaling the exponential filter coefficent to target a 1 sec time constant), speed verified by monitoring network activity with gnome system monitor. Now will say `unknown` instead of `100.0%` when the file size is wacky.
You can test locally with (which will re-download 1.5GB):
```
python -uic "import mne; mne.datasets.sample.data_path(force_update=True, verbose=True)"
```
Closes #5948.
> MRG, FIX: More accurate and stable progress bar

- .github/ISSUE_TEMPLATE/glossary.md
adds new issue template for missing glossary items
> adds issue template for glossary

- mne/stats/cluster_level.py
- mne/stats/tests/test_cluster_level.py
Closes #6675. cc @hoechenberger 
Along the way also modernizes some existing raises checks.
> MRG, DOC: Better error message for connectivity problems

- doc/python_reference.rst
- mne/channels/__init__.py
- mne/channels/_dig_montage_utils.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
> ENH: Add read_dig_montage_brainvision

- doc/changes/latest.inc
- mne/channels/_dig_montage_utils.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/gui/_file_traits.py
- mne/gui/tests/test_file_traits.py
- mne/viz/tests/test_montage.py
> Deprecate parts of read_dig_montage

- mne/epochs.py
> [Minor] Tiny cleanup from Sebastian's work on nonunique events

- doc/changes/latest.inc
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
> Fix bdf slice

- tutorials/intro/plot_40_projectors_background.py
- tutorials/preprocessing/plot_50_artifact_correction_ssp.py
- tutorials/raw/plot_40_visualize_raw.py
This overhauls / expands the "artifact repair with SSP" tutorial.  @larsoner @agramfort who would be a good reviewer for this content?
Note: there are a few `TODO` comments in the tutorial source code with questions that I couldn't find answers to. The tutorial is written so that it reads fine right now, so adding answers to those questions is not necessarily a blocker (though I think it would improve the tutorial).
> MRG, DOC: artifact repair with SSP tutorial

- examples/visualization/plot_eeg_on_scalp.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
- tutorials/source-modeling/plot_dipole_orientations.py
- tutorials/source-modeling/plot_source_alignment.py
Follow-up to #6715 that fixes the other underlying bug (rather than working around it by passing a str).
> MRG, FIX: Fix trans check

- doc/changes/latest.inc
- doc/python_reference.rst
- mne/_digitization/__init__.py
- mne/_digitization/_utils.py
- mne/_digitization/base.py
- mne/channels/__init__.py
- mne/channels/_dig_montage_utils.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/io/kit/tests/test_kit.py
- mne/tests/test_docstring_parameters.py
~nothing else.~
this PR is part of #6461
> ENH: Add read_dig_montage_polhemus

- .circleci/config.yml
- mne/datasets/utils.py
[Recent CircleCI failure](https://circleci.com/gh/mne-tools/mne-python/15181) shows that `_download_all_example_data` needed to be updated.
@drammock can you think of any other examples you've changed recently that would require other updates?
> MRG, ENH: Update downloader

- .travis.yml
Travis is failing because of a SSL cert, but it should fail sooner (during download). Let's get that first, then fix Travis.
> MAINT: Refactor travis

- doc/changes/latest.inc
- doc/conf.py
- doc/python_reference.rst
- examples/visualization/plot_publication_figure.py
- mne/utils/docs.py
- mne/viz/_3d.py
- mne/viz/__init__.py
- mne/viz/tests/test_3d.py
Closes #5830.
@drammock feel free to take over, just wanted to put some of my tweaks down somewhere.
> MRG, ENH: Publication tweaking example

- mne/forward/_make_forward.py
NumPy got pickier about not being able to convert some values, so only ask it to convert the relevant ones.
Should fix things like https://travis-ci.org/mne-tools/mne-python/jobs/584820182
> MAINT: Update coil def reading for newer NumPy

- doc/links.inc
- doc/overview/design_philosophy.rst
- examples/inverse/plot_dics_source_power.py
- tutorials/preprocessing/plot_40_artifact_correction_ica.py
A workaround for #6770 until someone corrects the dataset itself.
> FIX: Hotfix for somato dataset

- tutorials/source-modeling/plot_forward.py
> [DOC] fix typo 'source-based' -> 'surface-based'

- .travis.yml
> Travis CI: The sudo tag is deprecated in Travis

- .circleci/config.yml
> MRG, FIX: Circle downloads

- mne/commands/mne_browse_raw.py
- mne/commands/mne_coreg.py
- mne/commands/mne_make_scalp_surfaces.py
- mne/commands/mne_report.py
- mne/commands/mne_watershed_bem.py
- mne/commands/utils.py
Useful for new commands like #6749
> MRG, MAINT: Unify --verbose

- doc/changes/latest.inc
- mne/preprocessing/_peak_finder.py
- mne/report.py
- mne/viz/misc.py
- tutorials/source-modeling/plot_compute_covariance.py
Don't think we need to add a test given that the code paths should be checked by existing ones. Touched a tutorial so we could see an example output.
Also updated `_peak_finder.py` to log a bit more info, useful for debugging.
> MRG, ENH: Add rank lines to plot_cov

- examples/decoding/plot_receptive_field_mtrf.py
- examples/visualization/plot_3d_to_2d.py
- examples/visualization/plot_roi_erpimage_by_rt.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/io/meas_info.py
- tutorials/misc/plot_ecog.py
- tutorials/misc/plot_sensor_locations.py
- tutorials/preprocessing/plot_40_artifact_correction_ica.py
- tutorials/simulation/plot_creating_data_structures.py
- tutorials/source-modeling/plot_eeg_no_mri.py
From `git grep read_montage` I suspect that the examples modified here will fail now that #6765 is in. I hopefully fixed two of the three but left the last one with mismatched channel names for you @massich since I'm not sure what the plan was for this case.
> WIP: Fix broken examples

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/io/bti/bti.py
@joshbear @ebeich can you 1) see if this works on your data and 2) check that you're happy with the name and URL I put in `whats_new.rst` (based on 2 minutes of Google investigation)? I just cherry-picked your commits and updated `whats_new.rst`. It would be nice to have some test data for these use cases but might be overkill for this corner case.
Closes #6048.
Closes #6033.
Closes #6032.
> MRG, FIX: BTi reading bugs

- examples/datasets/plot_limo_data.py
- mne/channels/_standard_montage_utils.py
- mne/channels/montage.py
- mne/datasets/limo/limo.py
Fixes https://circleci.com/gh/mne-tools/mne-python/15483 by making it so that we preserve the channel order for our standard montages.
> MRG, ENH: Fix CircleCI

- doc/install/contributing.rst
Inspired by a conversation with @olafhauk on gitter.
@drammock feel free to merge if you're happy.
> MRG, ENH: Add suggestion to work through an example

- doc/changes/latest.inc
- mne/source_estimate.py
- mne/tests/test_source_estimate.py
> MRG, BUG: Fix behavior with stc.in_label

- mne/io/eeglab/eeglab.py
> fix eeglab nested EEG structure

- doc/changes/latest.inc
- examples/connectivity/plot_mixed_source_space_connectivity.py
- examples/inverse/plot_mixed_source_space_inverse.py
- mne/beamformer/_compute_beamformer.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
- mne/minimum_norm/time_frequency.py
- mne/source_estimate.py
- mne/tests/test_source_estimate.py
- mne/utils/__init__.py
- mne/utils/check.py
Closes #6803.
Didn't change any examples just tried to touch the ones that were likely to be affected.
> MRG, BUG: Raise error on normal for wrong src.kind

- doc/changes/latest.inc
- mne/filter.py
- mne/io/pick.py
- mne/tests/test_filter.py
> MRG, BUG: Filter instances with no data channels

- .circleci/config.yml
- doc/changes/latest.inc
- doc/whats_new.rst
- mne/__init__.py
Update circle to track `maint/0.19`
Bump 0.20.dev0
> [release] MNT: track maint/0.19 add whatsnew for 0.20

- mne/tests/test_import_nesting.py
- mne/utils/misc.py
Clean up our import nesting test and add other optional dependencies to the list. For @GuillaumeFavelier and #6731
> MAINT: Update nesting check

- mne/source_space.py
> Changed "MNI" to "MRI RAS"

- mne/utils/docs.py
Fixed h_freq documentation for mne.filter.filter_data
https://mne.tools/dev/generated/mne.filter.filter_data.html
> fixed h_freq documentation

- mne/epochs.py
- mne/tests/test_epochs.py
@larsoner is this what you were envisioning?
> MRG +1: better error when events is tuple (closes #6455)

- tutorials/preprocessing/plot_30_filtering_resampling.py
Would benefit from a close read from @agramfort @robertoostenveld and @larsoner, especially the resampling section.
> DOC: update filtering & resampling tutorial

- doc/conf.py
- examples/preprocessing/plot_run_ica.py
Should fix https://app.circleci.com/jobs/github/mne-tools/mne-python/15807
> MAINT: Fix Circle

- tutorials/preprocessing/plot_40_artifact_correction_ica.py
> FIX: fix baseline correction for EOG and ECG

- doc/changes/latest.inc
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
> Fix slash tfrs io

- doc/changes/latest.inc
- doc/changes/names.inc
- examples/connectivity/plot_mne_inverse_label_connectivity.py
- mne/connectivity/spectral.py
- mne/connectivity/tests/test_spectral.py
ENH: #6851
Implements the corrected imaginary PLV  (ciPLV)
> ENH: Corrected imaginary PLV #6851

- mne/viz/epochs.py
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
> FIX: Error plot psd fmax

- doc/glossary.rst
@larsoner this one is yours to review since you merged #6883 without my comments being addressed :)
> DOC: Glossary tweaks

- tutorials/preprocessing/plot_45_projectors_background.py
> FIX: Rendering [skip travis]

- doc/changes/latest.inc
- mne/channels/montage.py
- mne/io/brainvision/tests/data/test.hpts
> fix reading of cardinals in .htps files

- doc/glossary.rst
@jasmainak Can you review?
Thanks.
> DOC: adds noise covariance to glossary

- doc/changes/latest.inc
- mne/io/proj.py
- mne/utils/docs.py
- mne/viz/topomap.py
- tutorials/preprocessing/plot_50_artifact_correction_ssp.py
- tutorials/raw/plot_40_visualize_raw.py
- Unifies the API between `mne.viz.plot_projs_topomap` and the instance methods `{raw, epochs, evoked}.plot_projs_topomap`
- Allows `mne.viz.plot_projs_topomap` to accept *both* a Layout and an Info. If both are provided, the Layout is used.
cc @larsoner
> MRG, API: Unify plot projs topomap API

- doc/_templates/layout.html
with help from @NataKozh (thanks!)
> DOC: Fix broken website footer links

- doc/_templates/layout.html
backporting website footer fix
> DOC: Backport website footer link fixes

- doc/links.inc
- tutorials/preprocessing/plot_60_maxwell_filtering_sss.py
Fixes https://app.circleci.com/jobs/github/mne-tools/mne-python/16110
> DOC: Links

- doc/changes/latest.inc
- mne/evoked.py
- mne/tests/test_evoked.py
Fixes a `nave` regression introduced by #6492
> FIX: Fix nave regression

- doc/changes/latest.inc
- doc/python_reference.rst
- mne/channels/__init__.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/datasets/utils.py
- mne/io/_digitization.py
- mne/source_space.py
- mne/transforms.py
- mne/utils/check.py
- mne/utils/docs.py
- mne/viz/_3d.py
- mne/viz/utils.py
- tutorials/source-modeling/plot_eeg_mri_coords.py
Closes #3877.
~~Example is a bit complicated because we have to fake the dataset using `sample`.~~
> MRG, ENH: Add example of how to deal with EEG in MRI voxels

- mne/epochs.py
- mne/viz/epochs.py
- mne/viz/ica.py
- mne/viz/tests/test_epochs.py
> ENH: Add epochs_color argument to epochs.plot

- doc/changes/latest.inc
- examples/decoding/plot_decoding_csp_timefreq.py
- mne/decoding/tests/test_time_frequency.py
- mne/fixes.py
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
- mne/utils/check.py
- tutorials/stats-source-space/plot_stats_cluster_time_frequency_repeated_measures_anova.py
Fixed issue of not updating new sampling frequency when data is downsampled
cc @larsoner 
closes #6884
> FIX: updates sfreq if decimated 

- doc/changes/latest.inc
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
Closes #6836.
@nugenta can you see if this gives you a more informative error now?
> MRG, FIX: Corrmap check

- mne/preprocessing/tests/test_xdawn.py
- mne/utils/__init__.py
- mne/utils/_testing.py
- mne/utils/check.py
- mne/utils/config.py
Work around Azure failure due to likely MKL update bug.
> MAINT: Work around MKL+Windows bug

- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- tutorials/preprocessing/plot_40_artifact_correction_ica.py
Follow-up to #6900 to fix https://app.circleci.com/jobs/github/mne-tools/mne-python/16246/tests -- fix the problem and add unit test that would have caught it.
> MRG, FIX: More complete test

- tutorials/source-modeling/plot_dipole_fit.py
> DOC add reference for dipole fit

- .circleci/config.yml
testing the fix suggested by the pip devs
> test pip fix on Circle

- .travis.yml
- mne/io/curry/curry.py
- mne/io/curry/tests/test_curry.py
> MAINT: Fix Travis for latest ci-helpers

- .travis.yml
- mne/io/curry/curry.py
- mne/io/curry/tests/test_curry.py
> MRG, MAINT: Fix Travis for latest ci-helpers

- mne/externals/tempita/__init__.py
- mne/report.py
- mne/utils/_bunch.py
- mne/viz/utils.py
Some minor changes to make MNE work with Python 3.8 and latest numpy/scipy/matplotlib.
> MRG, FIX: Fixes for 3.8

- mne/io/nirx/tests/test_nirx.py
- mne/viz/evoked.py
- mne/viz/ica.py
- mne/viz/tests/test_epochs.py
- mne/viz/tests/test_ica.py
- mne/viz/utils.py
Follow-up to #6976 and #6981 to add ~~a test~~ two tests. Turns out when things are degenerate there are some other minor things that need to be fixed/skipped.
> MRG, MAINT: Add tests

- doc/changes/latest.inc
- mne/viz/misc.py
- mne/viz/tests/test_misc.py
- tutorials/source-modeling/plot_forward.py
Supersedes #6990.
@kingjr can you confirm that this fixes your problem?
@drammock can you see if the explanatory text is clear enough?
> MRG, BUG: Fix plot_bem source points

- mne/preprocessing/_beer_lambert_law.py
A small idea I had for DRY/shorter code looking at #6975. @rob-luke do you also prefer it? I find it a little bit cleaner.
> MRG, STY: A few tweaks

- mne/defaults.py
Change the color of hbo to red. It is traditional in fnirs literature for hbo to be red and hbr to be blue.
> WIP: Change default colors for fNIRS

- doc/changes/latest.inc
- doc/conf.py
- doc/python_reference.rst
- examples/inverse/plot_resolution_metrics.py
- examples/inverse/plot_resolution_metrics_eegmeg.py
- mne/minimum_norm/__init__.py
- mne/minimum_norm/resolution_metrics.py
- mne/minimum_norm/spatial_resolution.py
- mne/minimum_norm/tests/test_resolution_metrics.py
to be merged after resolution matrix PR
> MRG, ENH: Resolution metrics

- doc/install/contributing.rst
tiny tweak to the install docs pointed out by @prateekj117 in #3985
> DOC: specify conda-forge when necessary

- mne/inverse_sparse/_gamma_map.py
- mne/inverse_sparse/mxne_inverse.py
- mne/inverse_sparse/tests/test_mxne_inverse.py
Follow-up for #7043 including a relevant test and better parameter check
> [MRG] Bug fix for #7043

- doc/changes/latest.inc
- mne/time_frequency/psd.py
- mne/time_frequency/tests/test_psd.py
Fixes #7024.
If this works, I'll add a test.
> [MRG] Ignore NaNs when averaging spectrograms

- doc/changes/latest.inc
- mne/chpi.py
- mne/io/artemis123/artemis123.py
- mne/io/artemis123/tests/test_artemis123.py
Just a couple of small bug fixes for artemis123 support.
> Fix: Minor changes/fixes to artemis123 support

- doc/install/mne_python.rst
> DOC: add instructions for installing on headless server

- doc/install/pre_install.rst
> DOC: Add pyprep [skip travis] [skip azp]

- mne/minimum_norm/inverse.py
Fixes #7058
Logger displays "Explained variance unknown" when using eLORETA instead of an incorrect number.
> add "Explained variance unknown" in logger for eLORETA

- azure-pipelines.yml
- bin/mne
- doc/install/mne_python.rst
- mne/gui/_backend.py
- mne/gui/_kit2fiff_gui.py
- mne/gui/_marker_gui.py
- mne/utils/__init__.py
- mne/utils/check.py
- mne/utils/config.py
- setup.py
1. Check PyQt5 version on `sys_info` and all GUI calls, warn if on OSX and Qt<5.10 (as this is problematic), cc @alexrockhill as he had this problem
2. Modernize related compat checks in `mne/gui`
3. Add notes to installation about `which` on Linux -> `where` on Windows
4. Fix quotes in suggested command so that it works on Windows (and still on Linux/macOS)
5. Just verify that `mne` is accessible as a command-line option on Windows machines (tested on Azure)
Closes #7075
Closes #7062
> MAINT: Fix a few install issues

- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
This PR fixes the bug raising `ValueError`. The initial commit mitigates the issue.
Closes #7083
> [MRG] Fix plot_vector_source_estimates

- doc/changes/latest.inc
- mne/utils/misc.py
Closes #7080
@christian-oreilly can you see if this solves your problem?
> MRG, BUG: Fix running subprocesses in Jupyter notebooks

- mne/epochs.py
- mne/io/fiff/raw.py
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
- mne/preprocessing/ica.py
First step hopefully in our grand plan.
Closes #7071
Closes #7067
> MAINT: Ensure that meas_date=None round-trips if `anonymize_info` is used

- tutorials/epochs/plot_10_epochs_overview.py
closes #7099
(or rather, supercedes it)
> reduce memory footprint of Epoching tutorial

- .github/ISSUE_TEMPLATE/bug_report.md
- CONTRIBUTING.rst
- doc/_static/diagrams/git_setup.dot
- doc/install/contributing.rst
- doc/install/mne_python.rst
- doc/links.inc
- doc/overview/faq.rst
closes #6898 
This PR also updates the FAQ on filing new bugs, and the bug report issue template.
cc @mohdsherif @jasmainak @massich
> MRG, DOC: Update contrib guide

- mne/utils/misc.py
I'm experiencing deadlocks (probably due to #7086), which apparently is to be expected for programs that produce a lot of output:
https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait
This uses a highly rated suggestion from StackOverflow to avoid this problem:
https://stackoverflow.com/questions/375427/non-blocking-read-on-a-subprocess-pipe-in-python#4896288
Locally it fixes the problem for me.
> FIX: Avoid deadlocking

- doc/glossary.rst
- doc/overview/matlab.rst
- ignore_words.txt
- mne/chpi.py
- mne/commands/mne_bti2fiff.py
- mne/inverse_sparse/mxne_inverse.py
- mne/inverse_sparse/mxne_optim.py
- mne/io/bti/bti.py
- mne/io/eeglab/tests/test_eeglab.py
- mne/source_space.py
- mne/stats/permutations.py
- mne/viz/misc.py
- mne/viz/utils.py
- tutorials/raw/plot_40_visualize_raw.py
Some fixes from latest `codespell`.
> DOC: Spelling

- .circleci/config.yml
- .travis.yml
- azure-pipelines.yml
- doc/changes/latest.inc
- doc/install/mne_python.rst
- doc/overview/faq.rst
- mne/commands/mne_sys_info.py
- mne/commands/tests/test_commands.py
I realized that having a `mne sys_info` command could simplify some of our docs.
> ENH: Add mne sys_info command

- mne/rank.py
> better info message during rank computation

- mne/beamformer/tests/test_lcmv.py
Hopefully fixes https://travis-ci.org/mne-tools/mne-python/jobs/620756170
> FIX: Fix for old build

- doc/changes/latest.inc
- doc/python_reference.rst
- mne/chpi.py
- mne/tests/test_chpi.py
@bloyl has been using this for a couple years with success and @AdoNunes needs it for some preprocessing stuff (#7096). Seems reasonable to make it public in this release cycle.
> MRG, MAINT: Make calculate_head_pos_ctf public

- doc/conf.py
- examples/visualization/plot_channel_epochs_image.py
Should hopefully fix https://circleci.com/api/v1.1/project/github/mne-tools/mne-python/17060/output/115/0?file=true
> MRG, FIX: Fix sklearn import

- mne/channels/montage.py
- mne/channels/tests/test_montage.py
`master` port of #7118, which had to go in a different place.
> MRG, FIX: Allow unknown when setting montage

- mne/annotations.py
- mne/channels/channels.py
- mne/decoding/base.py
- mne/decoding/csp.py
- mne/decoding/ems.py
- mne/decoding/mixin.py
- mne/decoding/search_light.py
- mne/decoding/time_frequency.py
- mne/decoding/transformer.py
- mne/dipole.py
- mne/epochs.py
- mne/event.py
- mne/evoked.py
- mne/filter.py
- mne/io/base.py
- mne/io/proj.py
- mne/label.py
- mne/morph.py
- mne/preprocessing/ica.py
- mne/report.py
- mne/simulation/source.py
- mne/source_estimate.py
- mne/source_space.py
- mne/tests/test_docstring_parameters.py
- mne/time_frequency/csd.py
- mne/time_frequency/tfr.py
- mne/viz/utils.py
Let's see the error in CIs, then fix. Locally I see 636 errors (!).
> MRG, DOC: Fix class docstring errors

- azure-pipelines.yml
- environment.yml
- mne/annotations.py
- mne/tests/test_annotations.py
required by BIDS.
See https://github.com/mne-tools/mne-bids/pull/326
> allow nan durations in annot

- azure-pipelines.yml
- environment.yml
> MAINT: Unpin

- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
- setup.cfg
required by https://github.com/mne-tools/mne-study-template/pull/63
> WIP: issue with dates on write not on read

- doc/changes/latest.inc
- mne/viz/utils.py
- tutorials/epochs/plot_20_visualize_epochs.py
closes #7136 
Not sure if this is robust enough to handle all use cases...  @larsoner are sensor coords ever going to be in some other space besides `dev` or `head`?  If so maybe I need a trans dict that maps from the `info['chs'][n]['coord_frame']` integer to the appropriate transform in each case.
> MRG, FIX: apply transform before plotting sensors in 3D

- examples/inverse/plot_time_frequency_mixed_norm_inverse.py
- mne/viz/_brain/_brain.py
This PR fixes the `views` parameter passed to the camera.
Closes part of #7143
> FIX: brain add_label views parameter with pyvista

- doc/changes/latest.inc
- mne/evoked.py
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
Add support for NIRS types to `animate_topomap`.
I am not happy with the test I have added. See below. Suggestions welcomed.
> MRG: Add NIRS support to animate topomap

- doc/conf.py
- examples/inverse/plot_lcmv_beamformer_volume.py
Should fix https://circleci.com/gh/mne-tools/mne-python/17238
> MAINT: Work around nilearn deprecation

- mne/simulation/tests/test_raw.py
> MAINT: Fix hang

- doc/changes/latest.inc
- mne/viz/evoked.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
> MRG: Fix notebook xscale log raw psd #6968

- mne/decoding/base.py
- mne/fixes.py
Follow-up of https://github.com/mne-tools/mne-python/pull/7153#issuecomment-570589674, this PR tests how the CIs behave especially Travis and Azure with Python 3.7
> TST: Check sklearn ImportError of _index_param_value

- mne/viz/utils.py
closes #6481 
why this is needed is a mystery
cc @drammock
> fix 6481 with colorbars in groupby

- doc/changes/latest.inc
- mne/epochs.py
- mne/viz/epochs.py
closes #6250
cc @jona-sassenhagen
> MRG: Add copy param to iter_evoked

- doc/changes/latest.inc
- mne/channels/channels.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/utils/docs.py
> MRG, ENH: Add match_case=False option

- .travis.yml
- doc/install/mne_python.rst
- requirements.txt
This PR is a follow up of https://github.com/mne-tools/mne-python/pull/7172#issuecomment-571076181 and try to reproduce the issue on Travis with `PyQt5 5.14.1`.
> TST: Check PyQt5 AttributeError on version 5.14.1

- doc/changes/latest.inc
- mne/channels/tests/test_montage.py
- mne/forward/tests/test_make_forward.py
- mne/io/array/tests/test_array.py
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
- mne/viz/montage.py
> MRG, API: Deprecate montage in create_info

- doc/conf.py
This PR tests how Circle reacts when `OFF_SCREEN=False`.
> TST: Build the doc on Circle with offscreen=False

- doc/changes/latest.inc
- examples/decoding/plot_receptive_field_mtrf.py
- examples/visualization/plot_3d_to_2d.py
- mne/channels/channels.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/datasets/limo/limo.py
- mne/forward/tests/test_make_forward.py
- mne/io/eeglab/eeglab.py
- mne/io/meas_info.py
Add `info.set_montage` and fix failures on CircleCI in `master`.
> MRG, API: Add info.set_montage

- doc/_static/style.css
- tutorials/intro/plot_10_overview.py
A variant of what I think is the behavior requested by @agramfort in #7174.
> MRG, DOC: Clearer MNE links

- examples/visualization/plot_montage.py
- tutorials/misc/plot_ecog.py
- tutorials/simulation/plot_creating_data_structures.py
Should fix https://circleci.com/gh/mne-tools/mne-python/17435
> FIX: Fix deprecation uses in examples

- mne/bem.py
> MAINT: Drop `requires_freesurfer` arg from `bem._prepare_env()'

- doc/changes/latest.inc
- mne/viz/epochs.py
- mne/viz/tests/test_epochs.py
> FIX: Fix figure creation

- mne/datasets/utils.py
- mne/io/edf/tests/test_edf.py
This adds a test for the changes in #7190.
> Add test for BDF file with multiple annotation channels

- doc/_includes/bem_model.rst
- doc/changes/latest.inc
- doc/changes/names.inc
- mne/bem.py
Fixes #7216
Modify the brainmask default value in `mne.bem.make_watershed_bem` and the corresponding part in the document.
> MRG, FIX, DOC: modify brainmask default value

- doc/changes/latest.inc
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
> FIX: Fix plot_topomap with bads

- mne/preprocessing/ica.py
MINOR: This should facilitate finding the function to read saved ICA objects back into MNE
> DOC: add see-also link to ica.save, pointing to read_ica

- doc/changes/latest.inc
- mne/datasets/utils.py
- mne/dipole.py
- mne/tests/test_dipole.py
- setup.cfg
Read (and write) `.bdip` files produced by Xfit and MNE-C.
> MRG, ENH: Read binary dipoles (bdip)

- mne/gui/_coreg_gui.py
Fix minor typo in gui/_coreg_gui.py
> MRG, DOC: fix typo in gui/_coreg_gui.py

- doc/conf.py
- doc/overview/index.rst
- doc/overview/roadmap.rst
- doc/sphinxext/gh_substitutions.py
This does not have to be an exhaustive list for now, but it would be nice to have. It will give us some guidelines, and for things like GSoC we might be able to say "look at the roadmap list".
I plan to add more tomorrow (and link to issues, etc.), but if people have immediate ideas feel free to comment.
> MRG, MAINT: Add a roadmap

- doc/changes/latest.inc
- mne/io/cnt/cnt.py
closes #7248
@quocdat32461997 can you have a look and test? I tried comparing the data with EEGLAB but I get here 101 events while EEGLAB gives me 100 (it skips the last one).
> MRG fix for CNTEventType1 that don't have Latency

- doc/changes/latest.inc
- mne/io/curry/curry.py
- mne/io/eeglab/eeglab.py
- mne/io/eeglab/tests/test_eeglab.py
- mne/io/utils.py
> cleanup deprecation of montage setting in read_epochs_eeglab

- doc/changes/latest.inc
- doc/python_reference.rst
- mne/preprocessing/__init__.py
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
Fixes #6917.
Adding a function to import ica from EEGLAB .set files.
Todo:
> MRG, ENH: Adding a function to import EEGLAB ICA.

- examples/simulation/plot_simulate_evoked_data.py
- mne/viz/_3d.py
- mne/viz/backends/renderer.py
Should fix a bug where `_Renderer` is not in the namespace yet because no 3D backend has been imported yet. @GuillaumeFavelier can you look and merge if you're happy? Should fix our failure in `master`:
https://circleci.com/gh/mne-tools/mne-python/17755
> MRG, FIX: Fix bug with no init

- doc/changes/latest.inc
- mne/epochs.py
- mne/tests/test_epochs.py
- mne/utils/mixin.py
- tutorials/epochs/plot_10_epochs_overview.py
Hopefully addresses https://github.com/braindecode/braindecode/issues/62
> MRG, ENH: Add item to epochs.get_data

- mne/viz/epochs.py
- mne/viz/ica.py
- mne/viz/topo.py
- mne/viz/topomap.py
- mne/viz/utils.py
A few more updates for latest MPL deprecations.
> MRG, MAINT: Update picker usage

- mne/viz/_brain/surface.py
No need to use `nibabel` for these things.
> MRG, MAINT: Use internal reading functions

- doc/changes/latest.inc
- mne/conftest.py
- mne/externals/h5io/_h5io.py
- mne/gui/tests/test_coreg_gui.py
- mne/gui/tests/test_file_traits.py
- mne/gui/tests/test_kit2fiff_gui.py
- mne/gui/tests/test_marker_gui.py
- mne/time_frequency/tests/test_tfr.py
closes #7283
@larsoner any suggested way to fix this?
> MRG, FIX: HDF5 datetime bug

- doc/changes/latest.inc
- mne/io/meas_info.py
- mne/tests/test_docstring_parameters.py
- mne/time_frequency/tests/test_tfr.py
> MRG, FIX: Fix reading transforms

- mne/io/nirx/nirx.py
- mne/io/nirx/tests/test_nirx.py
Closes #7313
No need for `latest.inc` update because `read_raw_nirx` is a new function in 0.20
> MRG, FIX: Fix encoding bug

- mne/stats/cluster_level.py
- tutorials/stats-source-space/plot_stats_cluster_spatio_temporal_repeated_measures_anova.py
Just a quick fix in the stat tutorial as a colleague had trouble with the ``stat_fun`` throwing a cryptic error if one used A*B in the ANOVA function.
> DOC: improve stats tutorial documentation

- doc/changes/latest.inc
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
eLORETA couldn't be applied to labels.
I am not familiar with eLoreta, so someone who is needs to check this but it does make `_assemble_kernel` self consistent.
> FIX: eloreta labels

- .travis.yml
- doc/changes/latest.inc
- doc/python_reference.rst
- mne/bem.py
- mne/source_space.py
- mne/surface.py
- mne/tests/test_bem.py
- mne/tests/test_source_space.py
- mne/tests/test_surface.py
- mne/utils/__init__.py
- mne/utils/_testing.py
- mne/utils/check.py
Closes #7259
@christian-oreilly can you see how well `method='sphere'` works once you have a suitable (not broken, no holes, etc.) high-res mesh?
> MRG, ENH: Add sphere method to decimate_surface

- doc/overview/migrating.rst
- mne/preprocessing/ica.py
- tutorials/preprocessing/plot_40_artifact_correction_ica.py
Closes #7310.
Explicitly state which `preprocessing.ICA` parameters to set to achieve "EEGLAB-like" behavior in MNE. This should make transitioning from EEGLAB to MNE-Python much smoother.
> DOC: Help users transitioning from EEGLAB's runica()

- mne/viz/_3d.py
Document more clearly what these options mean.
> MRG, DOC: Clearer EEG doc

- mne/chpi.py
- mne/simulation/tests/test_raw.py
- mne/tests/test_chpi.py
- mne/viz/misc.py
- mne/viz/tests/test_misc.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
We were multiplying by 100 when we shouldn't have.
WIP because I should:
This will help ensure we are doing something reasonable.
> MRG, FIX: Fix bug with cHPI err calculation

- mne/io/constants.py
- mne/io/tests/test_constants.py
> MRG, MAINT: Update constant def

- .travis.yml
https://github.com/numpy/numpy/issues/15580 has taken longer to resolve than expected, let's work around it. I'm subscribed to the issue so I'll remove these lines once it's fixed upstream
> MAINT: Skip slow tests on pre build for now

- doc/_includes/inverse.rst
- doc/changes/latest.inc
- mne/defaults.py
- mne/fixes.py
- mne/minimum_norm/_eloreta.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
- mne/utils/__init__.py
- mne/utils/docs.py
- mne/utils/linalg.py
- tutorials/source-modeling/plot_mne_dspm_source_localization.py
- tutorials/source-modeling/plot_mne_solutions.py
Finally worked out the math for eLORETA:
1. Updated docs
2. Got the units to nAm
3. Fixed the variance explained calculation
4. Fixed the residual calculation
> MRG, FIX: Fix eLORETA units

- doc/overview/roadmap.rst
@cbrnr let me know if you know of others. I'm just adding the link you mentioned on the mailing list to https://mne.tools/dev/overview/roadmap.html#access-to-open-eeg-meg-databases (which we'll also use for a GSoC list)
> MRG, DOC: Link to another dataset

- mne/evoked.py
> fix redundant docstring

- mne/bem.py
- mne/commands/tests/test_commands.py
- mne/conftest.py
- mne/preprocessing/tests/test_scalp_coupling_index.py
- mne/utils/check.py
- mne/utils/tests/test_check.py
Should take care of an issue on the mailing list.
~~Not worth adding a test since the `watershed_bem` tests already take ages to run. But locally files without proper read permissions give the error in the comment.~~
> MRG, MAINT: Add permission check

- doc/changes/latest.inc
- doc/changes/names.inc
- examples/decoding/plot_decoding_csp_eeg.py
- examples/decoding/plot_decoding_csp_timefreq.py
- examples/time_frequency/plot_time_frequency_erds.py
- mne/datasets/eegbci/eegbci.py
- tutorials/preprocessing/plot_40_artifact_correction_ica.py
- tutorials/source-modeling/plot_eeg_no_mri.py
> FIX: Update EEGMI_URL

- examples/time_frequency/plot_compute_raw_data_spectrum.py
> MRG, FIX: Fix example [skip travis]

- mne/beamformer/tests/test_dics.py
Useful for #7401 and other beamformer testing because it generalizes the test to multiple source space vertices / labels. It should help test that things get generally better even if some get better and some get worse.
Ready for review/merge from my end @britta-wstnr @wmvanvliet @agramfort . This is a pretty straightforward (if you like pytest :) ) extension of what we have currently, plus cleanups of some `TODO`s in the code, which is nice.
I say we merge this then rebase #7401 so we can more clearly see what happens there based on how many tolerances go up versus down (or if we need to introduce new tolerances).
> MRG, MAINT: Parametrize test idx

- mne/channels/montage.py
addresses my request via mne mailing list (2020.03.03)
specify that head_size parameter for `def read_custom_montage` and `def make_standard_montage` expects a radius
-
> Update documentations in montage.py

- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
@agramfort - see if this works for you (it does for me).
fixes #7404 #7406
> FIX: topomap with grad ignored sphere and used layout (#7404)

- tutorials/discussions/plot_background_filtering.py
Fixes a CircleCI failure in master.
> MRG, FIX: Minimum phase import

- mne/preprocessing/maxwell.py
Small docstring improvement for `mne.preprocessing.find_bad_channels_maxwell()`.
> DOC: Fix docstring

- examples/inverse/plot_dics_source_power.py
- examples/inverse/plot_evoked_ers_source_power.py
- examples/inverse/plot_lcmv_beamformer_volume.py
> DOC: Fix typo

- azure-pipelines.yml
Relevant reading
https://github.com/numpy/numpy/pull/15747
https://github.com/scipy/scipy/pull/11671
https://status.dev.azure.com/_event/179641421
> FIX: Escape strings

- doc/changes/latest.inc
- mne/epochs.py
- mne/evoked.py
- mne/forward/__init__.py
- mne/forward/_field_interpolation.py
- mne/forward/tests/test_field_interpolation.py
Combine mags and grads for epochs, similarly to what is done for evokeds in as_type.
> MRG: add as_type for epochs, corresponding to issue #7365

- examples/connectivity/plot_mne_inverse_envelope_correlation.py
- examples/connectivity/plot_mne_inverse_psi_visual.py
- examples/forward/plot_forward_sensitivity_maps.py
- mne/viz/_brain/_brain.py
This PR fixes the recent issues with Circle. For short, `_interpolate_data()` now uses `_time_interp_funcs`
Reference: https://github.com/mne-tools/mne-python/pull/7257#discussion_r393315334
> Use _time_interp_funcs in _interpolate_data

- examples/visualization/plot_evoked_arrowmap.py
- mne/viz/topomap.py
> fix scale in plot_arrowmap

- doc/changes/latest.inc
- examples/visualization/plot_evoked_topomap.py
- mne/evoked.py
- mne/viz/_3d.py
- mne/viz/ica.py
- mne/viz/misc.py
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
- mne/viz/utils.py
Implements #7442 
Adds `nrows` and `ncols` parameter to `plot_evoked_topomap` to allow multiline evoked topomaps plots.
This is the result with `ncols=10` and `nrows='auto'`:
> Multiline evoked topomap plot

- doc/changes/latest.inc
Corresponding PR was already merged in #7451.
> Add whatsnew entry for improved Info repr

- mne/bem.py
- mne/tests/test_bem.py
> MRG, FIX: Fix logging of distances

- .mailmap
WIP, still waiting to hear back from a couple users, see https://github.com/mne-tools/mne-python/issues/7385#issuecomment-601307892
> WIP: update mailmap

- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
- tutorials/preprocessing/plot_60_maxwell_filtering_sss.py
@hoechenberger feel free to try.
Should be in 0.20 to make it within-cycle API change.
> MRG, ENH: Return flats with find_bad_channels_maxwell

- mne/forward/tests/test_make_forward.py
- mne/inverse_sparse/tests/test_mxne_optim.py
- mne/io/eeglab/tests/test_eeglab.py
- mne/tests/test_dipole.py
- mne/viz/tests/test_3d.py
Speed up OSX on Travis by skipping a few more, using "slow-ish" in the wording so it's easier to `git grep` later if it speeds back up.
> MRG, MAINT: Skip more on OSX

- .circleci/config.yml
- README.rst
- azure-pipelines.yml
- doc/install/advanced.rst
- environment.yml
- requirements.txt
Should hopefully fix the CircleCI and Travis errors.
> MRG, MAINT: Use direct GitHub links

- doc/changes/latest.inc
- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_lcmv.py
- mne/utils/check.py
@britta-wstnr feel free to try on your data
> MRG, FIX: Fix bug with rank checking in lcmv

- mne/viz/_3d.py
Part of #7060 to see if we can replicate the `test_report.py` error.
Has stubs with `if True` to facilitate future code, but can still be merged I think.
> MRG, ENH: Use uniform scale factor

- mne/utils/__init__.py
- mne/utils/numerics.py
- mne/utils/tests/test_numerics.py
- mne/viz/_brain/_timeviewer.py
Allow color reuse during picking with `_TimeViewer`. It's an item of #7162.
Probably worth adding to 0.20
> MRG, ENH: Allow color reuse in clicking

- mne/utils/docs.py
Requested in #7455
Okay for you @mmagnuski ?
> MRG, DOC: Add note about head radius [ci skip]

- tutorials/preprocessing/plot_70_fnirs_processing.py
Fix grammar and writing in the fNIRS example
> WIP: Fixed grammar in example

- doc/changes/latest.inc
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/data/test_units.vhdr
- mne/io/brainvision/tests/test_brainvision.py
> MRG: Add mV support to BrainVision reader

- mne/viz/_brain/_timeviewer.py
Closes #7544.
@GuillaumeFavelier can you look?
> MRG, FIX: Fix interaction with one time in macOS

- doc/install/advanced.rst
- doc/overview/get_help.rst
> MRG, DOC: macOS VTK troubleshooting & improvements to get_help page

- doc/changes/latest.inc
- mne/forward/_make_forward.py
- mne/forward/tests/test_forward.py
- mne/forward/tests/test_make_forward.py
- mne/source_space.py
> MRG, FIX: Fix make_forward_dipole completion

- doc/changes/latest.inc
- mne/minimum_norm/__init__.py
- mne/minimum_norm/_eloreta.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
- mne/minimum_norm/tests/test_time_frequency.py
- mne/minimum_norm/time_frequency.py
Fixes a problem mentioned on the listserv.
Closes #7540
> MRG, FIX: Fix eLORETA in TF-inverses

- mne/io/egi/general.py
- mne/io/egi/tests/test_egi.py
> MRG, ENH: Better error message when EEG data is missing

- mne/viz/_3d.py
Small changes to `plot_dipole_locations()`.
> DOC: Fix typo & small improvement

- doc/changes/latest.inc
- mne/epochs.py
- mne/io/tag.py
- mne/tests/test_epochs.py
Fixes a bug pointed out on the mailing list.
> MRG, FIX: Fix read_epochs w/complex data, preload=False

- Makefile
- azure-pipelines.yml
- mne/preprocessing/tests/test_artifact_detection.py
Small tweak to our CI to find more spelling errors.
> ENH: Update spelling check

- mne/io/meas_info.py
Closes #7575 
@drammock feel free to review and merge if you're happy.
> MRG, DOC: Document anonymization better

- .travis.yml
- doc/install/mne_python.rst
- environment.yml
Apparently conda supports platform selectors (?) so let's use those instead.
> MRG, DOC: Simplify Darwin installation

- examples/datasets/plot_brainstorm_data.py
- examples/decoding/plot_linear_model_patterns.py
- examples/inverse/plot_covariance_whitening_dspm.py
- examples/time_frequency/plot_source_power_spectrum_opm.py
Reduces memory usage and run times of a few of our worst offenders. @drammock feel free to review/merge if you're happy.
> MRG, MAINT: Improve memory usage

- mne/channels/montage.py
- mne/io/_digitization.py
Clarifies behavior of `read_dig_polhemus_isotrak`, and also simplifies a few bits of code in dig. I started trying to refactor it but stopped. I'll open a separate issue about that.
> MRG, DOC: Update doc of read_dig_polhemus_isotrak

- mne/surface.py
- requirements.txt
I can replicate the problem seen on Travis locally and will file an upstream bug soon. In the meantime let's keep CIs green
https://travis-ci.org/github/mne-tools/mne-python/jobs/676241896
> MRG, FIX: Fix typing for numba

- mne/beamformer/_compute_beamformer.py
Previously, the numerator of the beamformer filter calculation (which doubles as part of the denominator as well) got computed before the lead field rank was reduced, resulting in two lead fields being present in the final filter computation.
This PR fixes this.
CC @larsoner, @wmvanvliet
> Make sure leadfield rank reduction happens before filter calculation

- mne/beamformer/_compute_beamformer.py
This was always meant to be temporary to facilitate diffs. Now seems to be a good time to get rid of it from talking to @britta-wstnr 
Just removes the context manager and unindents one level
> MRG, MAINT: Remove noop

- mne/viz/_brain/_brain.py
- mne/viz/backends/_pyvista.py
This PR fixes the part of https://github.com/mne-tools/mne-python/issues/7599 about overlapping surfaces.
> WIP: Resolve coincident topology in _Brain

- doc/changes/latest.inc
- mne/stats/cluster_level.py
- mne/stats/tests/test_cluster_level.py
> MRG, FIX: Fix nan handling in TFCE

- doc/changes/latest.inc
- mne/beamformer/tests/test_external.py
- mne/beamformer/tests/test_lcmv.py
- mne/epochs.py
- mne/tests/test_epochs.py
- mne/viz/tests/test_ica.py
Closes #7628.
@SebastianSpeer @algrmur feel free to try it to see if it fixes your problem, but it should (test fails on `master` and passes on this PR).
> MRG, FIX: Fix baseline crop removal

- mne/stats/cluster_level.py
docstring improvement spurred by [this question](https://mail.nmr.mgh.harvard.edu/pipermail/mne_analysis/2020-April/006756.html) on the MNE-Analyze mailing list.
> DOC: better permutation cluster docstring

- mne/_ola.py
- mne/tests/test_ola.py
Takes just the overlap-add improvements from #7609 so that these can be merged and #7609 rebased.
> MRG, MAINT: Better OLA tests

- examples/connectivity/plot_mne_inverse_envelope_correlation_volume.py
- mne/source_estimate.py
Hotfix for examples that broke due to recent changes. I'll add better unit tests in follow-up PRs in the coming days since I'm working on this code anyway. In the meantime this should get CircleCI green.
> FIX: Fix examples

- doc/_includes/dig_formats.rst
- doc/changes/0.19.inc
- doc/changes/latest.inc
- doc/python_reference.rst
- mne/channels/__init__.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
> deprecate captraCK in favor of captraK (correct spelling)

- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
Standardises the checks for different types in plot_alignment
> WIP: Standardise argument checks for plot_alignment

- doc/changes/latest.inc
- mne/io/pick.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
closes #7631 
New test fails on master and passes on this PR
> MRG, FIX: allow explicit non-data picks

- mne/channels/channels.py
- mne/io/fiff/tests/test_raw_fiff.py
Closes #7669.
@nschawor this allows your code snippet to run for me. Can you try it?
No need for `latest.inc` update as it's a within-release fix.
> MRG, FIX: Fix read lims

- mne/viz/_brain/tests/test_brain.py
This PR is a follow-up to https://github.com/mne-tools/mne-python/pull/7665 and port the fix to the tests in `_Brain`.
> Update _Brain tests for VTK9

- tutorials/preprocessing/plot_20_rejecting_bad_data.py
Tiny fix to tutorial page as reported by a colleague
> DOC: tiny fix to tutorial

- .circleci/config.yml
- .travis.yml
Bumps up to 3.8 on CircleCI and Travis because the vtk9.0.0.rc3 wheels are available.
Let's see if the CIs are happy with it!
> MRG, ENH: Move up to 3.8

- doc/changes/latest.inc
- mne/channels/channels.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/utils/docs.py
> MRG, ENH: Add DigMontage.rename_channels

- mne/utils/docs.py
> fix doc typo - IIR upper bound twice

- .circleci/config.yml
- .travis.yml
- MANIFEST.in
- azure-pipelines.yml
- mne/commands/tests/test_commands.py
- mne/utils/config.py
- tools/get_minimal_commands.sh
As discussed in the flash bem issues/PRs, it would be good to have a run that actually executes our ultraslow tests. This PR adds one to Azure.
> MAINT: Add ultraslow run

- .circleci/config.yml
cf https://circleci.com/gh/mne-tools/mne-python/19816?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification
> missing dep for linkcheck

- tutorials/preprocessing/plot_70_fnirs_processing.py
- tutorials/source-modeling/plot_dipole_fit.py
Fixes [two examples broken](https://app.circleci.com/pipelines/github/mne-tools/mne-python/1399/workflows/4c7592b6-c121-4992-bc1a-1ab3d80d3ddc/jobs/19812/steps) by #7706.
> MRG, FIX: Fixes for examples

- Makefile
> FIX: Check manifest update [ci skip]

- doc/index.rst
> Minor MNE description improvement

- doc/changes/latest.inc
- mne/evoked.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
Fixes a problem found by @drammock working with complex Evoked data where the variance explained computation / message would give a warning, which made it clear it was doing something wrong.
> MRG, FIX: Fix for complex

- doc/changes/latest.inc
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
Closes #7741
@SophieHerbst can you see if it fixes your issue?
> MRG, FIX: Fix exact match in find_bad_channels_maxwell

- doc/changes/latest.inc
- mne/datasets/tests/test_datasets.py
- mne/datasets/utils.py
- mne/label.py
Needed to create HCPMMP1_combined volumetric atlas in addition to HCPMMP1 volumetric atlas for `fsaverage` requested in https://github.com/mne-tools/mne-python/pull/7639#issuecomment-625722019
> MRG, FIX: Fix bug with write_labels_to_annot

- mne/source_estimate.py
- mne/tests/test_source_estimate.py
Fixes reading STCs written with old versions of MNE.
> MRG, FIX: Backward compat read for vol stc

- doc/index.rst
Most recent NIH support was missing
> MRG, FIX: Update NIH support

- doc/conf.py
- examples/visualization/plot_evoked_topomap.py
- mne/viz/topomap.py
Let's see if we can get SG animations working. Might be nice for putting back the animation in #7768.
> MRG, ENH: Test matplotlib animation support

- examples/stats/plot_cluster_stats_evoked.py
- examples/time_frequency/plot_time_frequency_erds.py
- tutorials/discussions/plot_background_statistics.py
- tutorials/stats-sensor-space/plot_stats_cluster_1samp_test_time_frequency.py
- tutorials/stats-sensor-space/plot_stats_cluster_time_frequency.py
- tutorials/stats-source-space/plot_stats_cluster_time_frequency_repeated_measures_anova.py
because I broke it.  Forgot to update examples/tutorials after API change.
> FIX: circle

- doc/overview/roadmap.rst
WIP because I'm waiting to hear back on an email to the Kymata Atlas people.
> MAINT: fixes for linkcheck

- doc/install/mne_python.rst
- doc/install/pre_install.rst
- environment.yml
closes #7788 
- removes spyder from our environment file
- adds docs section on installing IDEs
- small clarification to pre-install docs
> MRG, MAINT, DOC: Remove spyder

- doc/changes/latest.inc
- mne/externals/pymatreader/pymatreader.py
- mne/externals/pymatreader/utils.py
- mne/io/eeglab/tests/test_eeglab.py
pymatreader received an update. it now works correctly with complex numbers and a few crashes were fixed.
> [MRG] update to pymatreader 0.0.23

- README.rst
Fix Zenodo bade & MNE logo in readme, use SVG bagde for Travis.
> Fix Readme badges

- doc/changes/latest.inc
- mne/channels/channels.py
- mne/io/fiff/tests/test_raw_fiff.py
Closes #7816 at least the meas_date parts of it.
@hoechenberger
> Allow set_meas_date(None)

- doc/install/mne_c.rst
- tutorials/io/plot_20_reading_eeg_data.py
fixes a couple more dead links from weekly linkcheck
> fix linkcheck again

- doc/install/mne_python.rst
> DOC: add troubleshooting message about installing OpenGL

- doc/changes/latest.inc
- mne/evoked.py
- mne/report.py
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
1. Add charset spec to `Report` so that unicode characters actually render (on master they are messed up)
2. Add `axes` arg to `plot_evoked_white`
3. Modernize some `evoked.plot_white` tests
4. Actually test the multi-cov case of `plot_evoked_white` (previously only used in examples)
> MRG, ENH: Add axes to plot_evoked_white

- doc/changes/latest.inc
- mne/io/meas_info.py
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
Closes #7849
@virvw can you see if this fixes your problem?
> MRG, FIX: Fix reading of old TFRs

- doc/changes/latest.inc
- mne/epochs.py
- mne/tests/test_epochs.py
Closes #7854.
@listenzcc can you see if it fixes your problem?
> MRG, FIX: Fix subtract_evoked with decim

- mne/datasets/utils.py
> MRG, MAINT: update 4DBTi dataset version and hash

- tutorials/evoked/plot_10_evoked_overview.py
updates the tutorial guidance regarding combine_evoked and inverse imaging.
> fix evoked nave → inverse guidance

- tutorials/evoked/plot_10_evoked_overview.py
> remove "and and" [ci skip]

- doc/changes/latest.inc
- mne/io/ctf/info.py
- mne/io/egi/egi.py
- mne/io/egi/events.py
- mne/io/meas_info.py
- mne/io/tests/test_raw.py
- mne/tests/test_bem.py
@bloyl can you see if this fixes your problem?
> MRG, FIX: Ensure Info H5-writeable

- mne/fixes.py
- mne/viz/backends/_notebook.py
> try to fix nullcontext

- mne/time_frequency/csd.py
> fix typos in docstrings for TF

- tutorials/stats-sensor-space/plot_stats_cluster_erp.py
> do not forget to pass adjacency

- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
Add a `get_picked_points()` function to the `_Brain` object and updates the feature overview table.
It's an item of #7162 
Related to #7959
> MRG: Add get_picked_points() to _Brain

- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/base_renderer.py
- mne/viz/backends/tests/test_renderer.py
This PR adds the `remove_labels()` function to the `_Brain` object and updates the feature overview table.
**ToDo**
It's an item of #7162 
Related to #7959
> MRG: Add remove_labels to _Brain

- mne/viz/misc.py
- mne/viz/tests/test_misc.py
- tutorials/source-modeling/plot_forward.py
Within release bugfix for bug introduced by #7763
Thanks for catching this @nordme, feel free to try with your data, hopefully it's fixed on this branch
> MRG, BUG: Fix missing source space points

- doc/conf.py
- doc/install/advanced.rst
- doc/install/mne_python.rst
- doc/install/pre_install.rst
@larsoner not sure if I did the cherry-pick correctly; the diff ended up including some changes that weren't from #7971 ... but I *think* that's actually what we want in this case?
> backport new environment file and install instructions

- doc/changes/latest.inc
- mne/time_frequency/_stockwell.py
- mne/time_frequency/tests/test_stockwell.py
Fixes an issue from the mailing list.
> MRG, FIX: Fix stockwell checks

- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
> MRG, MAINT: Better error message for mismatch

- mne/source_space.py
- mne/tests/test_source_space.py
Closes #8004
@susamerz can you see if this fixes your problem? Thanks for the nice reproducible case BTW, it made fixing and adding a test for this much easier!
> MRG, BUG: Fix warning

- doc/changes/latest.inc
- mne/report.py
- mne/tests/test_report.py
- tutorials/misc/plot_report.py
This is still WIP and depends on #7990. So will need to be rebased after #7990 has been merged.
> MRG: Add SSP projectors to Report

- server_environment.yml
Should fix our notebook failures. I could reproduce the problem locally, and things work fine on 6.1.6
> MRG, MAINT: Fix notebook testing

- mne/viz/epochs.py
- mne/viz/evoked.py
- mne/viz/raw.py
- mne/viz/utils.py
Uses the now-preferred method of setting a window title.
> MRG, MAINT: Work around matplotlib deprecation

- mne/conftest.py
- mne/viz/_brain/_timeviewer.py
- mne/viz/_brain/tests/test_brain.py
Non-scraping-related parts of #7927, which is on hold until we figure out how to avoid memory problems.
> MRG, BUG: Fix legend bgcolor and Travis macOS

- mne/viz/_brain/_timeviewer.py
This PR updates the import logic of `FileDialog` with the changes of `pyvista 0.25`
> FIX: Import FileDialog from PyVista

- server_environment.yml
This PR fixes the failures with the notebook job on Azure.
> MNT: Notebook testing

- examples/visualization/plot_evoked_arrowmap.py
- mne/viz/topomap.py
> VIZ, BUG: delay plt_show until after quiver

- .travis.yml
- azure-pipelines.yml
- mne/tests/test_docstring_parameters.py
- requirements_testing.txt
Let's see if we can get more information about where things are crashing.
> WIP, MAINT: Fix Azure python pre failures

- mne/viz/_brain/_timeviewer.py
Same problem as #8049 existed in _timeviewer
@GuillaumeFavelier
> FIX: smooth_mat logic in _timeviewer

- .travis.yml
- azure-pipelines.yml
- mne/commands/tests/test_commands.py
- mne/io/brainvision/brainvision.py
- mne/io/meas_info.py
- mne/utils/__init__.py
- mne/utils/_logging.py
- mne/utils/_testing.py
- mne/utils/config.py
- mne/utils/misc.py
- mne/utils/tests/test_config.py
- mne/utils/tests/test_logging.py
- mne/viz/topo.py
- setup.cfg
Clean up ResourceWarning in our codebase.
> MRG, MAINT: Clean up resource use

- doc/changes/latest.inc
- examples/inverse/plot_mixed_source_space_inverse.py
- mne/conftest.py
- mne/forward/forward.py
- mne/inverse_sparse/_gamma_map.py
- mne/inverse_sparse/mxne_inverse.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
- mne/source_estimate.py
- mne/utils/docs.py
> MRG, ENH: Add loose-as-dict for mixed source spaces

- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
> Make ICA.find_bads_* kwarg values more consistent

- mne/io/fieldtrip/fieldtrip.py
- mne/io/fieldtrip/tests/test_fieldtrip.py
- mne/io/fieldtrip/utils.py
Closes #8071.
@acquayefrank can you see if this helps with your error at all?
> BUG: Better float checking for FT

- doc/changes/latest.inc
Fix small glitch introduced by #8073
> DOC: Fix latest.inc

- mne/viz/raw.py
- mne/viz/tests/test_raw.py
Fix a bug with raw plotting where going to the end and back (when the number of displayed channels changes) caused an error. Introduced by #7811 within-release so no `latest.inc` update.
> MRG, FIX: Fix bug with raw scrolling

- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
Would have saved some pain in #8093
> MAINT: Better checks for inverse functions

- mne/viz/topomap.py
While attempting to find possible memory problems described in #8032 (couldn't find any obvious problems there), I did some minor docstring improvements to `plot_arrowmap()`
> DOC: minor docstring improvements

- doc/changes/latest.inc
- doc/conf.py
- doc/python_reference.rst
- doc/references.bib
- mne/epochs.py
- mne/evoked.py
- mne/externals/doccer.py
- mne/preprocessing/__init__.py
- mne/preprocessing/_regress.py
- mne/preprocessing/ecg.py
- mne/preprocessing/eog.py
- mne/preprocessing/tests/test_regress.py
- mne/tests/test_docstring_parameters.py
- mne/utils/docs.py
- mne/viz/utils.py
- tutorials/preprocessing/plot_35_artifact_correction_regression.py
Takeover of #7637. cc @kylemath @cbrnr I tried to rework the API a bit to make it more general, and to allow fitting the coefficients on one segment of data and applying them to another. Let me know what you think.
Closes #7637
Closes #7636
> MRG, ENH: Add preprocessing regression

- mne/viz/_3d.py
- mne/viz/_brain/_timeviewer.py
This PR links the colorbar controls in `_LinkViewer` and adds a `colorbar` parameter to `link_brains()`.
> MRG: Link colorbar controls in _LinkViewer

- doc/changes/latest.inc
- mne/fixes.py
- mne/morph.py
- mne/tests/test_morph.py
> MRG, BUG: Fix complex vol morph

- mne/source_space.py
- mne/tests/test_source_space.py
Using volumetric label extraction with HCPMMP1_combined (following https://github.com/mne-tools/mne-python/pull/7639#issuecomment-625907891) we run into a problem with `_get_lut` not reading long names. This fixes it.
I'm not 100% sure if FreeSurfer officially supports such long names, but at least `freeview` displays the names correctly when viewed with:
```
$ freeview -v HCPMMP1_combined+aseg.mgz:colormap=lut:lut=HCPMMP1_combinedColorLUT.txt
```
Within-release bugfix of custom LUT reading, so no need for `latest.inc` update.
> MRG, BUG: Fix long name parsing

- mne/viz/ica.py
- Fix docstrings
- Fix handling of `title` kwarg
> [MRG] Fixes to _plot_ica_overlay_evoked()

- doc/changes/latest.inc
- doc/references.bib
- examples/preprocessing/plot_rereference_eeg.py
- mne/channels/channels.py
- mne/io/reference.py
- mne/io/tests/test_reference.py
- mne/utils/docs.py
Closes #7973
@sappelhoff can you try it and see if it looks correct? Based on the math I think it should be, but based on the output it looks quite different from other referencing schemes.
If it's incorrect, it would be great if we could get a gain matrix and REST-ed data from FieldTrip or some other software with a working implementation, and compare to their results.
Todo:
> MRG, ENH: Add REST

- mne/io/pick.py
> Remove meg=True from _pick_data_or_ica

- doc/changes/latest.inc
- doc/changes/names.inc
- doc/install/contributing.rst
Extends #8027.
- Added GNU-Make-Installation for Windows
- Git-Installation for Windows more clear
- Fixed small typo in "running the tests"
> DOC: GNU-Make on Windows

- doc/changes/latest.inc
- mne/report.py
- mne/tests/test_report.py
> FIX : allow Path in parse_folder

- .travis.yml
- azure-pipelines.yml
- environment.yml
- requirements.txt
Mayavi 4.7.2 is out with VTK9 support:
https://pypi.org/project/mayavi/#history
And NumPy has a regression introduced around August 11th
> MRG, MAINT: Tweak CI versions

- doc/changes/latest.inc
- mne/channels/_standard_montage_utils.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/preprocessing/_csd.py
- mne/preprocessing/tests/test_csd.py
- mne/viz/montage.py
Fix a few small bugs before release. Pooled together because the changes are all pretty small and hopefully easy to understand, so I figured I'd try to save some CI cycles. Can split back out if necessary.
Closes #8025
Closes #7859
Closes #7452
> MRG, BUG: Fix montage plotting, deduplication, and preload check

- doc/changes/latest.inc
- mne/epochs.py
- mne/tests/test_epochs.py
> MRG, ENH: Better memory efficiency

- doc/changes/latest.inc
- mne/bem.py
- mne/tests/test_bem.py
> MRG, ENH: Allow writing BEM in H5 format

- mne/channels/montage.py
- mne/channels/tests/test_montage.py
> MRG, ENH: Add message

- mne/viz/topomap.py
- tutorials/preprocessing/plot_40_artifact_correction_ica.py
Hello friends, long time no see :)
Just a quick PR. @drammock does this look correct to you?
> MRG, DOC: fix ica tutorial
