mne-tools/mne-python

- environment.yml
- mne/gui/_coreg_gui.py
- mne/gui/_viewer.py
- mne/viz/_3d.py
This PR:
- Adresses #5375 for graphics renderers (Intel, MESA, ...) that do not properly do Z-buffer based rendering (argh) by making it so the fiducials (and other items) are visible, even though they still aren't rendered perfectly.
- Improves Mayavi rendering by using full-screen anti-aliasing by default.
@bloyl can you see if it makes `mne coreg` usable for you with Intel/MESA rendering?
```
$ 
mne coreg -d ~/mne_data/MNE-sample-data/subjects -s sample --fif ~/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw.fif
```
After runinng this and clicking "Fit Fid." on `master` this is what I get with `llvmpipe` (MESA software) rendering:
And on this PR:
And on this PR (or `master`, approximately) with proper NVIDIA rendering:
So it's not perfect -- points that should be occluded by the …
> MRG: Improve OpenGL compat

- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
fixes #5669 
If we want to read the testing data like `raw=mne.io.read_raw_brainvision('Analyzer_nV_Export.vhdr')`,
we get this output and warning message:
> Extracting parameters from Analyzer_nV_Export.vhdr...
Setting channel info structure...
Used Annotations descriptions: []
<ipython-input-11-cddac3454f0f>:1: RuntimeWarning: 1 annotation(s) will be dropped, such as ['Trigger/Trigger#2']. Consider using ``regexp`` to ignore annotations that do not follow a specific pattern.
raw=mne.io.read_raw_brainvision('Analyzer_nV_Export.vhdr')
This is not helpful, because `mne.io.read_raw_brainvision` does not have a `regexp` parameter (was this inserted through/because of `mne.annotation.events_from_annotations`?).
I changed it so that the warning message now refers the user to the `event_id` …
> [MRG+2] BrainVision warning message should refer to parameter

- doc/whats_new.rst
- examples/io/plot_read_proj.py
- mne/viz/tests/test_utils.py
- mne/viz/topomap.py
- mne/viz/utils.py
- tutorials/plot_artifacts_correction_ssp.py
- tutorials/plot_visualize_raw.py
Some projections do not plot properly. When executing the following lines, the data of the first projection gets substituted by a vector of zeros (see figure)
```py
import mne
FNAME= '/home/sik/Dropbox/mne-python/issues-pr-data/5641_proj_vectors/passive_raw.fif'
raw_fname = data_path + '/MEG/sample/sample_audvis_filt-0-40_raw.fif'
raw = mne.io.read_raw_fif(FNAME, preload=True)
p1 = raw.info['projs'][0]
p1.plot_topomap()
raw_2 = mne.io.read_raw_fif(raw_fname, preload=True)
p2 = raw_2.info['projs'][0]
p2.plot_topomap()
```
Please find the data in [this dropbox folder](https://www.dropbox.com/sh/8e07r7a22rzwv34/AAC5pVEPfl7Q-9ccJPW6oUKZa?dl=0)
> [MRG+1] BUG: projection vectors

- mne/channels/tests/test_interpolation.py
- mne/cov.py
- mne/epochs.py
- mne/forward/_compute_forward.py
- mne/forward/tests/test_make_forward.py
- mne/io/array/tests/test_array.py
- mne/io/meas_info.py
- mne/io/open.py
- mne/io/pick.py
- mne/io/tag.py
- mne/io/tests/test_pick.py
- mne/surface.py
- mne/tests/test_coreg.py
- mne/tests/test_source_estimate.py
- mne/tests/test_surface.py
- mne/viz/_3d.py
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
- mne/viz/tests/test_topo.py
- requirements.txt
This should speed up our tests a bit. I noticed some were going over 40 minutes and thus flirting with the Travis test limit.
Big speed gains were realized by changing code used by `setup_source_space` to much more efficiently compute the neighboring triangles for each vertex.
Minor speed gains in forward computation came from different vectorization forms.
> MRG: Speed up tests

- doc/Makefile
- doc/install_mne_c.rst
including setup for zsh and how to get free matlab runtime distribution
doc/Makefile: add "first_target:" as the first makefile target to build
target html_dev-noplot by default when typing "make" with no args.
[contribution guidelines](https://martinos.org/mne/stable/contributing.html) …
> doc/install_mne_c.rst: Update setup setion and add some more detail

- mne/io/edf/edf.py
Fixes #5685.
This changes ch_offsets variable to an array of int64 (instead of int32) which prevents int overflow on Windows while reading big data files.
> Updating EDF reader to prevent int overflow on Windows

- doc/manual/matlab.rst
- mne/io/constants.py
- mne/io/proj.py
- mne/io/reference.py
- mne/io/tests/test_constants.py
- mne/preprocessing/maxwell.py
Fixes various problems with our constants found in #5481. The biggest one was that we were not checking to make sure we had all the constants. We do not, but this makes explicit which ones we don't, and also adds some that we are  missing.
> MRG: Fix constants

- doc/conf.py
- doc/tutorial_links.inc
- mne/stats/cluster_level.py
- mne/viz/topomap.py
- tutorials/plot_background_statistics.py
- tutorials/plot_stats_cluster_spatio_temporal.py
- tutorials/plot_stats_cluster_spatio_temporal_2samp.py
- tutorials/plot_stats_cluster_spatio_temporal_repeated_measures_anova.py
- tutorials/plot_stats_cluster_time_frequency.py
I've fixed plotting in three stats examples with weird percentiles. Eventually I'll fix the wording pointed out by @jona-sassenhagen 
Closes #5636.
> MRG: Fix stats examples and wording

- doc/whats_new.rst
- examples/inverse/plot_lcmv_beamformer.py
- examples/inverse/plot_lcmv_beamformer_volume.py
- examples/inverse/plot_tf_dics.py
- examples/inverse/plot_tf_lcmv.py
- mne/beamformer/_compute_beamformer.py
- mne/beamformer/_dics.py
- mne/beamformer/_lcmv.py
- mne/beamformer/_rap_music.py
- mne/beamformer/tests/test_dics.py
- mne/beamformer/tests/test_lcmv.py
- mne/cov.py
- mne/tests/test_utils.py
- mne/utils.py
- tutorials/plot_dics.py
This PR gives the `_create_beamformer` another refactoring pass to unify the LCMV and DICS flow. 
Bugs fixed:
- LCMV beamformer when `pick_ori='normal', weight_norm='unit_noise_gain'`. The existing implementation has a bug where the weights were first normalized to have unit length *before* picking the normal direction. Instead, the weights should be normalized to unit length *after* picking the orientation, as is the case when `pick_ori='max-power'`.
- DICS beamformer when `inversion='single', pick_ori='max-power', weight_norm='unit_noise_gain'`. The computation of the power (in order to pick the orientation with max power) was bugged.
- DICS beamformer when `inversion='matrix', pick_ori='max-power', weight_norm='unit_noise_gain'`. In this case, a computational shortcut is performed, but …
> [MRG] More work on the beamformer code

- mne/preprocessing/ica.py
One more attempt to make the docstring of ICA more explicit, especially as to the three different `*_components_*` parameters.
Also fixing wrong shape specifications of the attributes `pca_components_` and `pca_explained_variance_`.
Expanding on #5114, in reference to #4856.
V.s.; in detail:
* Adding a (first attempt of an) introduction about pre-ICA PCA, also referencing the warning about dimensionality reduction mentioned e.g. [here](https://github.com/mne-tools/mne-python/issues/4856#issuecomment-377194869).
!! The formulation about the whitening needs to be reviewed, I am not sure, if this is correct! See below.
* Referencing the most important methods which make use of the various attributes and parameters, especially thereby trying to be more explicit in which steps the various …
> WIP: Improve ica docstring, the second

- .travis.yml
- environment.yml
- requirements.txt
Since pytest 3.10 came out, pytest-sugar is broken:
https://github.com/Frozenball/pytest-sugar/pull/160
For now let's not bother installing it. Once they fix the bug and cut a new version we can add it back. (Seems better than the alternative, namely to pin pytest < 3.10.)
> MRG: Remove pytest-sugar

- doc/python_reference.rst
- doc/whats_new.rst
- mne/annotations.py
- mne/io/__init__.py
- mne/io/brainvision/__init__.py
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/eeglab/__init__.py
- mne/io/eeglab/eeglab.py
- mne/io/eeglab/tests/test_eeglab.py
- mne/io/fiff/raw.py
- mne/tests/test_annotations.py
Fixes #5670 
Things to do:
```rst - Add function :func:`mne.io.read_annotations_eeglab` to allow loading annotations from EEGLAB files, by `Alex Gramfort`_` ```
> [MRG+1] Unify read annotations

- doc/whats_new.rst
- examples/decoding/plot_decoding_spoc_CMC.py
- mne/cov.py
- mne/tests/test_cov.py
This fixes a bug discovered in the SPoC MNE example: https://mne-tools.github.io/dev/auto_examples/decoding/plot_decoding_spoc_CMC.html
where the Predicted EMG is not in the same scale than True EMG.
After investigation, it was due to a missing rescaling of the data in _compute_covariance_auto.
This bug did not affect the usage of mne.compute_covariance because that function does a copy internally. 
This is the output of this example after bug correction:
cc @agramfort @dengemann @kingjr @alexandrebarachant 
It should be ready for review
> [FIX] Repair scaling of data in _compute_covariance_auto

- doc/documentation.rst
- doc/manual/datasets_index.rst
- doc/whats_new.rst
- examples/datasets/plot_opm_rest_data.py
- mne/minimum_norm/time_frequency.py
Follow-up of #5514.
Closes #5510.
Implements the Brainstorm pipeline for resting state data. Looks good and seems robust to me on VectorView and OPM data.
Marked WIP pending verification from @bloyl that it looks similar in Brainstorm and/or that @dengemann can replicate on mne-hcp data. @ktavabi has reported that it works for some of his VectorView data.
> [MRG+1]: Add VectorView and OPM rest example

- tutorials/plot_info.py
This is just a quick fix of a single line in the documentation.
The point is that `mne.pick_types` has the default of `meg=True`, so we have to set `meg=False` to pick only EEG channels.
> quick fix doc

- doc/documentation.rst
- doc/glossary.rst
- doc/whats_new.rst
- mne/annotations.py
- mne/tests/test_annotations.py
- tutorials/plot_events_and_annotations.py
- tutorials/plot_object_annotations.py
From the whish list in #5201 it mainly addresses point 4.
> [MRG] Add events/annotations tutorial

- doc/whats_new.rst
- examples/inverse/plot_covariance_whitening_dspm.py
- examples/inverse/plot_lcmv_beamformer.py
- examples/visualization/plot_evoked_whitening.py
- mne/beamformer/tests/test_lcmv.py
- mne/beamformer/tests/test_rap_music.py
- mne/cov.py
- mne/decoding/csp.py
- mne/decoding/tests/test_csp.py
- mne/inverse_sparse/tests/test_gamma_map.py
- mne/io/pick.py
- mne/preprocessing/xdawn.py
- mne/simulation/tests/test_evoked.py
- mne/tests/test_cov.py
- mne/tests/test_proj.py
- tutorials/plot_brainstorm_phantom_elekta.py
- tutorials/plot_compute_covariance.py
- tutorials/plot_whitened.py
We currently do covariance regularization on the full rank data. Thus rank-deficient covariance matrices become full rank. This PR changes it so that regularization is done in the lower-dimensional space, then projected back out, which should preserve the original rank.
This probably has some small impact on full-rank MEG data (e.g., 306 channels with a handful of projs) but the impact is magnified by Maxwell filtering due to the larger rank reduction.
Updated examples (930bee9):
- [PR](https://10142-1301584-gh.circle-artifacts.com/0/html/auto_examples/inverse/plot_covariance_whitening_dspm.html) - [master](http://mne-tools.github.io/dev/auto_examples/inverse/plot_covariance_whitening_dspm.html)
- [PR](https://10142-1301584-gh.circle-artifacts.com/0/html/auto_examples/inverse/plot_lcmv_bea …
> MRG: Do regularization in PCA space

- doc/conf.py
- doc/whats_new.rst
- mne/annotations.py
- mne/io/base.py
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/eeglab/eeglab.py
- mne/io/eeglab/tests/test_eeglab.py
- mne/io/utils.py
- mne/utils.py
Stim channel is synthesized by:
> [MRG+1] Deprecate stim channel synthesis

- doc/python_reference.rst
- doc/whats_new.rst
- examples/visualization/plot_parcellation.py
- mne/datasets/__init__.py
- mne/datasets/tests/test_datasets.py
- mne/datasets/utils.py
This adds the 448 aparc atlas from @SherazKhan 2018 NIMG paper.
Ready for review / input [tests are missing].
I've updated our plot parcellations example to also show this parcellation
@larsoner @agramfort
> ENH: add aparc_sub parcellation

- doc/conf.py
- doc/tutorials/philosophy.rst
- tutorials/plot_creating_data_structures.py
- tutorials/plot_epoching_and_averaging.py
- tutorials/plot_info.py
- tutorials/plot_object_raw.py
- tutorials/plot_point_spread.py
Gets rid of a missing EEG ref warning, plus a ref to `RawFIF` that should be `Raw` (the former is an alias for the latter). I also modernized some linking methods while I was in there.
> MRG: No warning in example

- mne/viz/raw.py
This wasn't even valid LaTeX code.
Before:
After:
> Don't italicize Hz in PSD y-label

- mne/viz/ica.py
This adds a histogram right next to the epochs variance plot. I think it makes it a bit more readable and perhaps easier to interpret for the inexperienced.
I also like that it breaks the false and confusing symmetry between the top right axes' x axis and the bottom right axes' x axis.
@mmagnuski
> MRG [VIZ, MINOR] Histogram for epochs variance in ica_plot_properties

- .travis.yml
- appveyor.yml
- doc/sphinxext/gen_commands.py
- doc/whats_new.rst
- mne/bem.py
- mne/channels/tests/test_interpolation.py
- mne/commands/mne_flash_bem.py
- mne/commands/tests/test_commands.py
- mne/inverse_sparse/tests/test_mxne_inverse.py
- mne/inverse_sparse/tests/test_mxne_optim.py
- mne/io/artemis123/tests/test_artemis123.py
- mne/io/eeglab/tests/test_eeglab.py
- mne/tests/test_coreg.py
- mne/tests/test_epochs.py
- mne/tests/test_import_nesting.py
- mne/tests/test_source_space.py
- requirements.txt
- setup.cfg
Based on the suggestion of @massich I:
1. added `pytest-timeout`.
2. set the default a bit stringent to 30 to make sure we don't slow our test suite too much accidentally (new tests, bad changes). If it ends up giving too many false positives we can relax it later, but from what I've seen the CIs are pretty reliable in terms of timing.
3. added exceptions for tests that the Travis and Appveyor logs suggested needed them
4. split up the `interpolation` tests for MEG and EEG (nicer factorization, also less likely to time out)
5. ran the `ultraslowtest` tests locally, added reasonable timeout exceptions for them
6. fixed some bigs with `make_flash_bem`, and also converted them to using full paths instead of `os.chdir` and the like (which is less clean)
Small coverage hit likely due to …
> MRG: Add timeout

- mne/cov.py
- mne/forward/_make_forward.py
- mne/utils.py
Turns out that `contextlib.contextmanager` will raise any errors at the `yield` point, so things need to be wrapped in a `try/finally` if they are always supposed to be executed.
> MRG: Fix contextmanager use

- doc/whats_new.rst
- mne/epochs.py
- mne/tests/test_epochs.py
It seems that something is missing. This is my guess to fix the following error:
```python
evoked = epochs.average(method='median')
File "/home/cmmoenne/.local/share/virtualenvs/worksenv-d02f98b0/lib/python3.6/site-packages/mne/epochs.py", line 875, in average
return self._compute_aggregate(picks=picks, mode=method)
File "/home/cmmoenne/.local/share/virtualenvs/worksenv-d02f98b0/lib/python3.6/site-packages/mne/epochs.py", line 922, in _compute_aggregate
", got %s (type %s)." % (mode, type(mode)))
ValueError: mode must be mean, median, std, or callable, got median (type <class 'str'>).
```
...but, I do not know. Perhaps is something different.
> MRG: added missing median keyword for method parameter in epochs average

- doc/manual/io.rst
I created a small (gist)[https://gist.github.com/skjerns/bc660ef59dca0dbd53f00ed38c42f6be] for exporting EDF or BDF files as suggested in #5755 and integrated it into the IO documentation.
> Added link to gist to save/export EDF files

- mne/commands/tests/test_commands.py
- mne/tests/test_coreg.py
- mne/viz/tests/test_3d.py
For some reason `test_scale_mri_xfm` is very slow on OSX. By marking it slow, it will be skipped there. I left the timeout as 60 because IIRC it was a bit slow on Linux, too.
Feel free to merge if CIs come back happy so that PRs can be green again
> MRG: Fix OSX test

- .circleci/config.yml
- .travis.yml
- appveyor.yml
- environment.yml
- requirements.txt
Closes #5779.
First commit just to see if we can replicate #5779. After that, fix it.
Replicated: https://ci.appveyor.com/project/mne-tools/mne-python/builds/20931971
> MRG: --only-binary dipy

- doc/whats_new.rst
- mne/io/reference.py
- mne/io/tests/test_reference.py
I messed up the original pull request while trying to squash the commits (sorry!) :'(
Short description of the bug: `set_bipolar reference` try to remove a list of repeated channels when producing all the bipolar references of a dataset. Also, does not take into account channels of cathode list when performing in-place operations.
In this new pull, I added the requested changes, including a test, and also I updated whats new file.
Note that the current implementation of set_bipolar_reference fail in both, generating all the bipolar combinations and with repeated channels in the anode and cathode lists.
Closes #5780
Closes #5772
> MRG+1: fix for set_bipolar_reference

- examples/decoding/plot_decoding_csp_eeg.py
- examples/decoding/plot_decoding_csp_timefreq.py
- examples/time_frequency/plot_time_frequency_erds.py
Fixes a few examples broken by https://github.com/mne-tools/mne-python/pull/5741
> MRG: Fix broken examples

- tutorials/plot_object_evoked.py
This adds a few lines to the evoked object tutorial to show how to extract and plot the SD across channels, as discussed in #4002 
I'm trying to close old issues :)
Closes #4002
> [MINOR] Add evoked GFP to tutorials

- doc/whats_new.rst
- examples/visualization/plot_evoked_topomap.py
- mne/evoked.py
- mne/fixes.py
- mne/viz/evoked.py
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
- tutorials/plot_visualize_evoked.py
Implements the extra points layout for topo interpolation discussed in #5315 
It may eliminate the issues raised in #5315 but it might be suboptimal in some standard cases. For example this is a frontal theta topography before this PR:
and this is after:
I must say I prefer the "before" topo in this case (the "after" looks like a laughing cyclops in a party hat). Probably the extra points are too close to channels. I'll check that later. Also - masking using convex hull (but slightly less extended than here) might make it better.
> [MRG] ENH: alternative layout of extra points in interpolation

- doc/whats_new.rst
- mne/annotations.py
- mne/tests/test_annotations.py
This PR adds a parameter to `events_from_annotation` so that if this parameter
None, events correspond to the annotation onsets (as was happening until nos).
But if not, events_from_annotations returns as many events as they fit within
the annotation duration spaced according to this new parameter (right now is
called `chunk_duraiton` but we should discuss it before merging).
This PR needs to go in before #5718 
---
Things that are not in this PR (it will be done in subsequent PRs):
- allow slicing of Annotations
- update the documentation of events and annotations
> [MRG] Get multiple spaced events from single annotation

- mne/externals/pymatreader/utils.py
- mne/tests/test_source_space.py
```
Results (1268.35s):
926 passed
3 failed
- mne/io/eeglab/tests/test_eeglab.py:56 test_io_set_raw[fnames1]
- mne/io/eeglab/tests/test_eeglab.py:259 test_eeglab_annotations[/home/travis/mne_data/MNE-testing-data/EEGLAB/test_raw_h5.set]
- mne/io/eeglab/tests/test_eeglab.py:259 test_eeglab_annotations[/home/travis/mne_data/MNE-testing-data/EEGLAB/test_raw_onefile_h5.set]
18 skipped
2 deselected
The command "py.test -m "${CONDITION}" ${OPTION} ${USE_DIRS} --cov=mne;" exited with 1.
```
> MRG: Fix errors in master

- doc/whats_new.rst
- mne/io/base.py
- mne/viz/raw.py
- mne/viz/utils.py
When plotting a `raw** file that has less channels than  20 channels
the visualization does not look proper.
This PR fixes it to get this:
> [MRG] VIZ: change n_chanels default if there are less chanels

- MANIFEST.in
- conftest.py
- mne/channels/tests/test_layout.py
- mne/commands/tests/test_commands.py
- mne/coreg.py
- mne/inverse_sparse/mxne_optim.py
- mne/io/array/tests/test_array.py
- mne/io/eeglab/tests/test_eeglab.py
- mne/preprocessing/tests/test_ica.py
- mne/realtime/tests/test_fieldtrip_client.py
- mne/realtime/tests/test_mockclient.py
- mne/tests/test_bem.py
- mne/tests/test_dipole.py
- mne/tests/test_epochs.py
- mne/tests/test_import_nesting.py
- mne/tests/test_report.py
- mne/time_frequency/tests/test_tfr.py
- mne/viz/tests/test_3d.py
- mne/viz/tests/test_circle.py
- mne/viz/tests/test_epochs.py
- mne/viz/tests/test_evoked.py
- mne/viz/tests/test_ica.py
- mne/viz/tests/test_misc.py
- mne/viz/tests/test_montage.py
- mne/viz/tests/test_raw.py
- mne/viz/tests/test_topo.py
- mne/viz/tests/test_topomap.py
- mne/viz/tests/test_utils.py
- setup.cfg
Since SciPy 1.2.0 just came out and NumPy 1.16.0 is in RC status, I updated all my libs locally and hunted down errors. This PR thus (in three separate commits):
1. Fixes a bug with how we warm-started a `sklearn` var (we shouldn't ever set `clf.coefs_ = None`, sklearn can't handle this anymore). I also fixed PEP8 errors while in the file.
2. Works around an obscure `scipy.io.savemat` bug when subselecting fields from a structured array in `test_eeglab.py`. I also fixed PEP8 errors while in the file.
3. Unifies how we deal with `matplotlib` tests. I noticed mine had been horribly slow for some time. Turns out it's because I added `interactive=True` to my `matplotlibrc`. We now use a package-wide `pytest` fixture to set `matplotlib` params. This allows us to stop nesting our `plt` imports …
> MRG: Fix bleeding-edge library bugs

- mne/externals/pymatreader/utils.py
Fixes possible warnings because of h5py deprecation of `object.value` access.
This is basically a follow up to #5809. Although it is already closed, one extra occurrence of the deprecated code was still in the codebase.
> Update pymatreader to version 0.0.18.1.

- mne/channels/montage.py
- mne/utils.py
In Python 3.7, `from collections import Iterable` is deprecated, it should be `from collections.abc import Iterable` from now on.
> Fix import of Iterable

- tutorials/plot_eeg_erp.py
Before there was some sort of index, as a quote.
Now using context (has links to the sections etc..)
> [MRG] FIX/DOC: use sphinx contents to list content

- doc/whats_new.rst
- mne/annotations.py
- mne/tests/test_annotations.py
- tutorials/plot_object_annotations.py
Based on [python 3 doc](https://docs.python.org/3/reference/datamodel.html#object.__getitem__) indexing with
the wrong type should raise `TypeError` not `IndexError`. Then the entire function gets much more simpler:
``` python
def __getitem__(self, key):
"""Propagate indexing and slicing to the underlying numpy structure."""
return (self.onset[key], self.duration[key], self.description[key])
```
About the current solution: 
* (pros) I like the idea that we are raising the right 
* (cons) the code has 5 branches
> [MRG] Add support for indexing/slicing Annotations objects

- doc/python_reference.rst
- doc/whats_new.rst
- mne/__init__.py
- mne/event.py
- mne/fixes.py
- mne/label.py
- mne/source_estimate.py
- mne/tests/test_event.py
- mne/tests/test_label.py
These are a set of three changes that make it easier to work with label data, eventually for #5389.
1. Add `overlap` option to `make_fixed_length_events`.
2. Add `labels_to_stc` that allows you to map one-value-per-label back to a STC. This is useful when chaining `apply_inverse_epochs` and `extract_label_time_courses`, and pumping the result into some function.
3. Add `morph_labels` to morph a set of non-overlapping labels from one subject to another. This is useful when dealing with the parcellations that we have only for `fsaverage`, such as `HCPMMP1` and now `aparc_sub`. It should be better than doing `labels = [label.morph(...) for label in labels]` because the latter will create labels that overlap at the edges. I just used the nearest-neighbor from the morph-maps to do the …
> MRG: Add helper functions for label data

- doc/whats_new.rst
- mne/viz/raw.py
- mne/viz/tests/test_topo.py
- mne/viz/topo.py
Closes #5766 
Since matplotlib can already overlay data on different x grids, this should an easy fix. Or maybe I'm missing something... let's see.
> MRG: handle different time vecs in plot_evoked_topo()

- mne/io/base.py
- mne/io/tests/test_raw.py
I think it would be useful if `get_data` mentioned the number of rejected samples (if `reject_by_annotation` is "omit" or `"nan"`. Here's a sample message when getting data from a signal with 120000 samples with 1100 samples marked by bad annotations with `reject_by_annotation` is "omit"`:
```
Omitting 1100 of 120000 (0.92%) samples, retaining 118900 (99.08%) samples.
```
And here is the message when `reject_by_annotation` is "nan":
```
Setting 1100 of 120000 (0.92%) samples to NaN, retaining 118900 (99.08%) samples.
```
I'd like to add a test - where should I put it (I didn't find a test for `raw.get_data` at all)?
> [MRG] Log number of rejected samples in raw.get_data

- .travis.yml
- MANIFEST.in
- conftest.py
- mne/tests/test_docstring_parameters.py
- setup.cfg
Let's see if things pass on `maint/0.17`, too.
> ENH: Bump maint Travis to 3.7

- doc/whats_new.rst
- mne/commands/mne_coreg.py
- mne/gui/__init__.py
- mne/gui/_coreg_gui.py
- mne/utils.py
#5666 was a step forward for people with bad graphics cards but a step back for ones with good graphics cards. This adds an option to properly render points for people whose OpenGL support is good enough (i.e., not using software rendering). On `master` you see points in the back can appear at the front:
On this PR, depth peeling fixes it:
> MRG: Fix coreg rendering bugs on modern graphics cards

- doc/whats_new.rst
- mne/io/base.py
- mne/io/fiff/raw.py
- mne/io/tests/test_raw.py
Fix #5839, #5555 
This PR fixes the fact that `raw_A.append(raw_B)` ignores `meas_date` and
supposes that the buffers of `raw_A` and `raw_B` where captured one right
after the other.
> [MRG][Fix] Concatenate raw objects with annotations

- .travis.yml
- appveyor.yml
- environment.yml
CircleCI linkcheck had an error
https://circleci.com/gh/mne-tools/mne-python/10878
And AppVeyor has been failing. Let's see if VTK from `pip` makes AppVeyor happy.
> FIX: Use pip for vtk

- doc/whats_new.rst
- mne/beamformer/_compute_beamformer.py
- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_lcmv.py
make_lcmv and make_dics were computing filters on full meg data even in the presence of bads which caused a crash when applied to data with bad channels as proj matrix was suddenly different.
cc @britta-wstnr @wmvanvliet
> [MRG] Fix bf proj with bads

- mne/io/edf/edf.py
fixes #5864
A regression in plot_sleep.py due to #5841
in the original code, comparison with `None` was working
```diff
-                        if ci == stim_channel:
+                        if ci in stim_channel:
```
in the new code, if `stim_channel` is `None` the conditional breaks.
It should had been:
```diff
-                        if ci == stim_channel:
+                        if stim_channel is not None and ci in stim_channel:
```
I think we should not need a test for that. I checked all other comparions, 
and they would never run into a `None` `stim_channel`.
The tutorial works as expected
``` shell
In [1]: %run tutorials/plot_sleep.py
/home/sik/miniconda3/envs/mne/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: …
```
> [Hot fix] circle ci

- doc/whats_new.rst
- mne/simulation/raw.py
- mne/simulation/tests/test_raw.py
Adds support for passing `info` and `duration` instead of `raw` to `simulate_raw`.
Also removed a bunch of `use_cps=True` deprecation cruft from the tests.
> MRG: Add support for Info-as-Raw

- doc/whats_new.rst
- mne/io/base.py
- mne/io/tests/test_apply_function.py
See issue #5860.
This adds an argument `channel_wise` to `mne.io.Raw.apply_function()`. If `channel_wise` is True (default), the function is applied on each channel individually; if it is False, then the whole data array is passed to the function at once.
Questions:
1) Should we raise an error or display a warning if `channel_wise` is False and `n_jobs` is not 1?
2) I added a few lines to the existing test `test_apply_function_verbosity`. Would it better to create a separate test function?
> [MRG] Adding `channel_wise` argument to `Raw.apply_function`

- MANIFEST.in
- doc/whats_new.rst
- mne/datasets/sleep_physionet/tests/test_physionet.py
- mne/io/edf/_utils.py
- mne/io/edf/edf.py
- mne/io/edf/gdf_encodes.txt
- mne/io/edf/tests/test_edf.py
- mne/io/edf/tests/test_gdf.py
- setup.py
The snipped in #5863 now returns this:
``` shell
<Annotations  |  595 segments : 32766 (9), 276 (1), 277 (1)..., orig_time : 2005-01-19 12:00:00>
(595, 3)
{'32766': 1, '276': 2, '277': 3, '1072': 4, '768': 5, '783': 6, '1023': 7}
(595, 3)
{'GDF event A': 768, 'GDF event B': 783, 'GDF event C': 1072, 'GDF event D': 276, 'GDF event E': 277, 'GDF event F': 32766, 'GDF event G': 1023}
```
I'm not sure if the ids, are stored somewhere in the meatadata (ie: `4242` meaning something like `Start recording`)
fixes #5863
> [MRG][FIX] Fix GDF returning all annotations with same description

- doc/python_reference.rst
- doc/whats_new.rst
- mne/simulation/__init__.py
- mne/simulation/evoked.py
- mne/simulation/tests/test_evoked.py
- mne/tests/test_docstring_parameters.py
One part of what we need for https://github.com/mne-tools/mne-python/issues/5058#issuecomment-377500991
> MRG: Add add_noise to simulation

- .circleci/config.yml
- .travis.yml
- appveyor.yml
- doc/conf.py
- environment.yml
- setup.cfg
I noticed that 3.7 is the default now on the Anaconda site. Let's see if tests pass on OSX and Windows now. If so we can update our install instructions.
I might also try to fix the Windows bug here, we'll see.
> ENH: 3.7 for conda

- doc/_static/style.css
- doc/install_mne_python.rst
- environment.yml
- mne/simulation/raw.py
- tutorials/plot_object_source_estimate.py
Take care of a number of paper cuts:
1. Change OSX instructions to use explicit `curl --remote-name ` instead of `curl -O`
2. Set CSS style of console separators in Pygments highlighting to be non-selectable, so copy-paste is easier. This is not done for Python because we have the `>>>` on the right to hide the separators.
3. Update entries in example outputs to reflect Python 3.7.
4. Update mayavi pin in environment.yml.
5. Fix a couple of minor bugs with linking:
```
/home/larsoner/python/mne-python/doc/auto_tutorials/plot_object_source_estimate.rst:26: WARNING: py:obj reference target not found: src
/home/larsoner/python/mne-python/mne/simulation/raw.py:docstring of mne.simulation.simulate_raw:88: WARNING: py:obj reference target not found: src
```
Closes #5884
> MRG: Fix instruction copy-paste

- doc/manual/io.rst
Fixes [#4059.](https://github.com/mne-tools/mne-python/issues/4059)
Adds information on BioSemi BDF-Files in the documentation, suggesting to chose a reference channel upon import to avoid losing signal.
New passage summarises info from BioSemi [FAQs](https://www.biosemi.com/faq/cms&drl.htm)
> WIP: adds to bdf file documentation

- doc/whats_new.rst
- mne/annotations.py
- mne/commands/mne_clean_eog_ecg.py
- mne/epochs.py
- mne/filter.py
- mne/io/array/array.py
- mne/io/base.py
- mne/preprocessing/ecg.py
- mne/preprocessing/ssp.py
- mne/preprocessing/tests/test_ecg.py
- mne/tests/test_annotations.py
1. Adds `reject_by_annotation` to `find_ecg_events`.
2. Internally passes the `reject_by_annotation` value from `create_ecg_epochs` to `find_ecg_events` (I consider it a bug that this wasn't done, given that it is done in `create_eog_epochs` -> `find_eog_events`).
3. Fixes bugs with `_annotations_starts_stops(..., invert=True)` to properly give contiguous segments
> MRG: Add reject_by_annotation to find_ecg_events

- mne/tests/test_coreg.py
We have been seeing too many of these lately:
https://travis-ci.org/mne-tools/mne-python/jobs/488680214
This commit skips `test_scale_mri` on Travis-OSX to avoid it.
> FIX: test_scale_mri too slow on Travis OSX

- doc/whats_new.rst
- mne/channels/channels.py
- mne/io/pick.py
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- mne/viz/topomap.py
I recently had some success removing a pattern of intermittent external noise using ICA decompositions of the reference channel array in a 4D MEG system. The procedure went as follows:
1) Use ICA to decompose the MEG reference channels into components. I used n_components=0.99, which generally yielded one or two components.
2) Decompose the MEG data channels into components.
3) Use preprocessing.ICA.scores_sources to get pearsonr for each individual reference component against the data channel components.
4) Eliminate data channel components that have a z-transformed pearsonr with reference component beyond a threshold.
MNE as it currently stands does not allow ICA decomposition of reference channels. The suggested changes are a first step in providing this functionality. They allow the …
> MRG+1: ENH: functionality for doing ICA on MEG reference channels

- mne/datasets/utils.py
- mne/utils/config.py
- mne/utils/tests/test_fetching.py
When using `pytest-xdist` locally with `-n 2` to spawn multiple jobs, I got lots of errors because during test collection each `testing.data_path(download=False)` was trying to read/write the `mne-python.json` file simultaneously. We should really only write it if necessary, i.e. if the config value in the file does not match the new one. This PR adds that behavior.
Also fixes a small problem with `test_fetch_file` I was hitting.
This is such a minor change that shouldn't really affect end users that I don't think it's worth a `whats_new.rst` update.
> FIX: Only write when necessary

- doc/whats_new.rst
- mne/epochs.py
- mne/io/constants.py
- mne/io/tests/test_constants.py
- mne/tests/test_epochs.py
This PR:
1. Adds reject parameters to epochs I/O.
2. Reorganizes our epochs I/O test to be less monolithic. I'll highlight the four lines I actually added that are relevant to (1). The rest are indentation changes (and a few copy-paste lines), so the diff looks big but it's not bad.
RFC instead of MRG because this will require an update of `fiff-constants` for the new param `FIFF_MNE_EPOCHS_REJECT_FLAT=3802`. Once that's done, the entry in `_tag_ignore_names` in `test_constants.py` can be removed.
Needs:
Closes #5891.
> FIX: Save and load reject params

- doc/advanced_setup.rst
- doc/contributing.rst
- doc/documentation.rst
- doc/getting_started.rst
- doc/git_links.inc
- doc/index.rst
- doc/install_freesurfer.rst
- doc/install_mne_c.rst
- doc/install_mne_python.rst
- doc/manual/c_reference.rst
- doc/pre_install.rst
- doc/this_project.inc
This is the first in a series of PRs to improve the documentation.  This PR targets the installation/setup docs.  Highlights:
- converts the Install landing page to a full TOC of all the install pages
- adds a "before you install" page to guide new users about which tools they need and an overview of what each tool does.
- adds a dedicated page on freesurfer installation.
- adds "next" links to the bottom of the main installation pages.  (for now I've avoided trying to hack the sphinx-bootstrap theme to generate these automatically, like the [sphinx-readthedocs theme](https://sphinx-rtd-theme.readthedocs.io/en/latest/) does, but I'm open to that possibility if there's general support for it.)
- attempts to avoid "MNE" in favor of explicit reference to "MNE-C", "MNE-python", or "the MNE …
> MRG+2: Revise install docs

- doc/whats_new.rst
- mne/epochs.py
- mne/tests/test_epochs.py
- mne/utils/mixin.py
Fixes a nasty `Epochs` bug where using `Epochs(..., preload=True)` followed by `epochs.drop_bad(...)` causes the data and selection to be incorrect. Things were broken in #4827, so have been broken since the 0.16.0 release.
> MRG: Fix sel

- .circleci/config.yml
- doc/conf.py
- doc/documentation.rst
- doc/python_reference.rst
- doc/whats_new.rst
- examples/connectivity/plot_mne_inverse_envelope_correlation.py
- examples/inverse/plot_label_source_activations.py
- mne/connectivity/__init__.py
- mne/connectivity/envelope.py
- mne/connectivity/tests/test_envelope.py
- mne/connectivity/tests/test_utils.py
- mne/connectivity/utils.py
- mne/datasets/utils.py
- mne/io/ctf_comp.py
- mne/source_estimate.py
- mne/tests/test_source_estimate.py
- mne/utils/check.py
Adds orthogonal envelope correlation code. Still needs:
Closes #5389.
Next PR:
Also cleans up a flake8 error in `test_source_estimate.py`, a docstring in `source_estimate.py`, and simplifies `plot_label_source_activations.py`. (I changed these while adding a new `mode` to `extract_label_time_course` which I eventually did not need, but they're nice things to have anyway.
> [MRG] ENH: Add orthogonal power envelope correlation

- mne/io/pick.py
- mne/preprocessing/ica.py
- mne/viz/tests/test_ica.py
- tutorials/plot_artifacts_correction_ica.py
- tutorials/plot_ica_from_raw.py
A `int` vs `np.int` bug snuck through #4511, this adds a test and updates a ref in the process to trigger CircleCI on the example that [was failing](https://circleci.com/gh/mne-tools/mne-python/11299).
> BUG: Fix picks when "info" is int-like

- doc/whats_new.rst
- mne/beamformer/_compute_beamformer.py
- mne/beamformer/tests/test_lcmv.py
Closes #5928.
@britta-wstnr can you see if the fix looks reasonable and it fixes your problem?
> BUG: Fix beamformer bug with full rank and reg=0.

- doc/whats_new.rst
- mne/io/edf/_utils.py
- mne/io/edf/edf.py
Closes #5933.
We should backport this before releasing 0.17.1.
> BUG: Add CR-LF hash

- mne/beamformer/_compute_beamformer.py
- mne/beamformer/_dics.py
- mne/beamformer/_lcmv.py
- mne/beamformer/_rap_music.py
- mne/beamformer/tests/test_lcmv.py
- mne/utils/__init__.py
- mne/utils/check.py
- mne/utils/tests/test_check.py
Moved some of the channel picking facility to ``utils``: 
``_check_info_inv`` (formerly ``_compute_beamformer._setup_picks``) picks channels based on the data / noise cov matrix and forward model, taking into account channels marked as bad in ``info`` and reference channels.
Next step for this PR is to write tests for this function.
Two additional functionalities have been added: check for compensation and dropping ref channels  during computation of spatial filter (will comment in code to mark those).
ping @agramfort
To Do:
> MRG+1: ENH: refactor beamformer channel picks with utils

- doc/conf.py
- doc/python_reference.rst
- doc/whats_new.rst
- mne/__init__.py
- mne/beamformer/_compute_beamformer.py
- mne/beamformer/_dics.py
- mne/beamformer/_lcmv.py
- mne/cov.py
- mne/decoding/csp.py
- mne/io/base.py
- mne/io/meas_info.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
- mne/preprocessing/tests/test_ica.py
- mne/preprocessing/tests/test_maxwell.py
- mne/preprocessing/tests/test_xdawn.py
- mne/rank.py
- mne/tests/test_cov.py
- mne/tests/test_rank.py
- mne/time_frequency/ar.py
- mne/utils/__init__.py
- mne/utils/check.py
- mne/utils/docs.py
- mne/utils/numerics.py
- mne/viz/evoked.py
- mne/viz/utils.py
the idea is to rely on this single function to compute rank of data / cov
> MRG: add new compute_rank function

- mne/io/fieldtrip/tests/test_fieldtrip.py
Fixes errors on `master` with the newest `pytest` release.
> FIX: match not message

- mne/chpi.py
This PR consists of exactly one character of code, which had to be removed from the matching pattern in order to match CTF headloc channels of data loaded with the `clean_names` option set to `True`. See comment in #4088.
> [FIX] Fix channel-picking in _calculate_head_pos_ctf

- doc/whats_new.rst
- mne/channels/channels.py
- mne/channels/tests/test_channels.py
- mne/io/reference.py
This allows to provide a string argument (the channel name) if only a single channel should be dropped.
> [MRG] Allow str argument in raw.drop_channels

- mne/viz/_3d.py
- mne/viz/backends/_pysurfer_mayavi.py
- tutorials/plot_visualize_evoked.py
Fixes #5970.
Fix the rendering bug of `mne/viz/plot_evoked_field()`
Remove the useless default `(0.7, 0.7, 0.7)` color and allow adding scalars on surfaces.
> Fix rendering bug of plot_evoked_field()

- doc/whats_new.rst
- mne/preprocessing/ssp.py
- mne/proj.py
- mne/rank.py
- mne/tests/test_proj.py
- mne/tests/test_rank.py
It's probably not great that `N` projectors reduce the rank by `N` for non-SSS'ed data, but generally by `< N` (often `0`) for SSS'ed data. In other words, once SSS makes mag and grad correlated, computing SSP projectors for them separately might not make sense.
This PR adds support for `sss='separate'` (default, current `master` behavior) and `'joint'` for SSS'ed data. I didn't do anything special about the scaling between mag+grad, but I *think* it shouldn't matter because of the correlation structure in the data.
@agramfort @dengemann WDYT? You can look at the test I added at the bottom of the diff to see how this should work, or recreated here in fuller form in case you want to try it:
```
import mne
raw = mne.io.read_raw_fif(data_path + …
```
> MRG: Add joint projection for SSS

- doc/whats_new.rst
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
- mne/viz/tests/test_topo.py
- mne/viz/utils.py
Fixes a bug found on the mailing list, and another one found while fixing that one.
Also separates a test in `plot_topo.py` along the way. I originally thought the problem with `plot_joint`, but it wasn't, but the tiny refactoring I did was still useful.
Closes #5972.
> MRG: Fix plot_compare_evokeds with tmin >= 0

- doc/glossary.rst
- doc/whats_new.rst
- mne/simulation/tests/test_raw.py
- mne/source_space.py
- mne/tests/test_source_space.py
- tutorials/plot_forward.py
Here are a few disturbing facts about the setup_volume_source_space.
`mne.setup_volume_source_space(subject, subjects_dir=subjects_dir)` returns by default a discrete source space that cannot be use for morphing. Even if i have a BEM computed form the T1 MRI if I pass the `bem=bem` parameter I get a discrete source space :( To have a volume source space which I assume is what most users want I need to type mri='T1.mgz'.
Illustration:
```
In [2]: src = mne.setup_volume_source_space(subject, subjects_dir=subjects_dir, bem=bem)
In [3]: src
Out[3]: <SourceSpaces: [<discrete, n_used=10376, coordinate_frame=MRI (surface RAS)>]>
In [4]: src = mne.setup_volume_source_space(subject, subjects_dir=subjects_dir, mri='T1.mgz')
In [5]: src.kind
Out[5]: 'volume'
In [6]: src
Out[6]: <SourceSpaces: …
```
> [MRG] allow to pass a BEM as an instance not just as a string

- doc/python_reference.rst
- doc/whats_new.rst
- mne/__init__.py
- mne/morph.py
- mne/source_estimate.py
- mne/tests/test_morph.py
- mne/tests/test_source_estimate.py
- mne/viz/tests/test_3d.py
I've run into tricky problems accidentally passing vector data `(n, 3, t)` to SourceEstimate. This implements `data` size checks for our classes.
> MRG: Better shape checks for SourceEstimate

- doc/whats_new.rst
- examples/preprocessing/plot_ica_comparison.py
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- tutorials/plot_artifacts_correction_ica.py
- tutorials/plot_ica_from_raw.py
Picard has a new `extended` argument ([which will hopefully be on PyPI soon](https://github.com/pierreablin/picard/issues/16)), but MNE currently does not allow this argument in the `fit_params` dict. I have removed this check.
On a related note, is there a specific reason why some Picard arguments are explicitly set although they are identical to the defaults (`ortho` and `fun`)? Also, why does MNE set `tol` to `1e-5` instead of using the default of `1e-7`?
@pierreablin WDYT?
> [MRG] Deprecate extended-infomax method

- mne/io/pick.py
Fixes #5977 
Many numpy functions return `int64`.
The picks-routine should accept all kind of ints
instead of
```Python
array.dtype!=np.int
```
I implemented
```Python
array.dtype.kind not in ['i', 'u']
```
which checks for any kind of integer
> [pick.py] changed checking for int to include int64

- mne/simulation/source.py
- mne/simulation/tests/test_source.py
```simulate_sparse_stc ```  throws an assertion error when   ```n_dipoles > len(labels) ```.
It should generate   ```min(n_dipoles, len(labels))  ``` dipoles.
Fixes #5953
> [ENH] ensure simulate_sparse_stc throws error when n_dipoles > len(labels)

- mne/time_frequency/tfr.py
When ```db=True```, tfr.plot_joint multiplies by 10. The info for the funtion states, however, that it multiplies by 20.
Or did I misunderstand something?..
> Fix docstr db in tfr.plot_joint

- mne/chpi.py
maxwell.axwell_filter and epochs.average_movements expect the time in the position matrix to be relative to 0 (start of recording), not relative to .first_sample. See post in #4088.
This PR adds `raw._first_time` to the time vector calculated in `mne.chpi._calculate_head_pos_ctf`.
> Add raw._first_time to time vec in chpi._calculate_head_pos_ctf

- mne/preprocessing/ica.py
- mne/viz/topomap.py
This PR adds (almost) all args of plot_ica_properties also to plot_ica_components to be passed through. This allows the properties plots, which can be interactively opened by clicking on a component to be configured in the call to ica.plot_components.
Maybe can be discussed in #5967?
> ENH: Pass plotting args from ica.plot_properties to ica.plot_components

- conftest.py
- doc/conf.py
- doc/whats_new.rst
- mne/beamformer/tests/test_lcmv.py
- mne/defaults.py
- mne/forward/forward.py
- mne/inverse_sparse/_gamma_map.py
- mne/inverse_sparse/mxne_inverse.py
- mne/inverse_sparse/tests/test_gamma_map.py
- mne/inverse_sparse/tests/test_mxne_inverse.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
- mne/utils/__init__.py
- mne/utils/check.py
- mne/utils/docs.py
Okay @agramfort I had to change a tolerance for one gamma_map test. All other tests should be passing except `mne/inverse_sparse/tests/test_mxne_inverse.py:test_mxne_inverse_standard`:
```
>       assert stc_prox.vertices[1][0] in label.vertices
E       IndexError: index 0 is out of bounds for axis 0 with size 0
```
*Then* the `loose_method='sum'` should change to `loose_method='svd'`, but this will break the sphere test. (The orientation only matches to 0.89, not 0.99, and the dipole fit is not 1.7mm away but 30mm :( ).
I'm out of my depth working on the MxNE stuff, so hopefully you find some hacking time soon.
Todo:
Next PR:
- rework `compute_depth_prior` to operate on `forward`
> MRG: Unify _prepare_gain

- doc/conf.py
- doc/sphinxext/gen_commands.py
- mne/utils/__init__.py
- mne/utils/numerics.py
This PR:
This is useful when combined with https://github.com/sphinx-gallery/sphinx-gallery/pull/448, you can see this when running `make html_dev-noplot` twice in a row:
```
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
```
This makes incremental doc building much simpler.
> MRG: Make doc build env static

- mne/viz/epochs.py
See discussion [here](https://github.com/autoreject/autoreject/pull/130#discussion_r260618474) with @agramfort 
Basically list look up is slower than dictionary lookup. So we should not use `keys()`
> FIX: don't use .keys when looking up dict

- doc/whats_new.rst
- examples/inverse/plot_custom_inverse_solver.py
- mne/forward/forward.py
- mne/forward/tests/test_forward.py
- mne/inverse_sparse/_gamma_map.py
- mne/inverse_sparse/mxne_inverse.py
- mne/io/pick.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
This PR should not change any outputs, but internally it:
These are important for #5881, and are hopefully the last steps we need (along with #5979) before having easy, unified, drop-in lead-field normalization across all solvers (!).
Ready for review/merge from my end @agramfort
> MRG: Clean up and unify _prepare_forward

- mne/beamformer/_lcmv.py
Example: Fixes #5945
checks that `weight_norm : 'unit-noise-gain' | 'nai' | None`
@jaaval now this snipped errors with a meaningful error
``` python
import mne
from mne.beamformer import make_lcmv
raw_fname = data_path + '/MEG/sample/sample_audvis_raw.fif'
event_fname = data_path + '/MEG/sample/sample_audvis_raw-eve.fif'
fname_fwd = data_path + '/MEG/sample/sample_audvis-meg-eeg-oct-6-fwd.fif'
label_name = 'Aud-lh'
fname_label = data_path + '/MEG/sample/labels/%s.label' % label_name
subjects_dir = data_path + '/subjects'
event_id, tmin, tmax = 1, -0.2, 0.5
raw = mne.io.read_raw_fif(raw_fname, preload=True)
raw.info['bads'] = ['MEG 2443', 'EEG 053']  # 2 bads channels
events = mne.read_events(event_fname)
picks = …
```
> FIX: check weight_norm parameter

- examples/connectivity/plot_mixed_source_space_connectivity.py
- examples/inverse/plot_mixed_source_space_inverse.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
Fixes a regression introduced by #5999 when `fixed=False` and `loose='auto'`.
> ENH: Fix regressions in master

- examples/inverse/plot_custom_inverse_solver.py
- mne/viz/backends/_pysurfer_mayavi.py
Fixes #5985.
Add the missing `cone` mode to the `quiver3d` function in the default pysurfer/mayavi 3d backend.
> Add cone mode to quiver3d

- .gitignore
I started to use a virtualenv for my MNE-Python dev env, which I put into `.venv` inside the project folder. I don't know how and where others use venvs (I'd be interested, let me know), but if possible it would be nice to include this in `.gitignore`.
> Add .venv folder to .gitignore

- examples/inverse/plot_custom_inverse_solver.py
The regularization term had no dependence on the scale of the whitened gain matrix, so when #5947 added the `trace_GRGT` scaling to the `source_cov` it broke the solver by effectively over-regularizing. This makes the solver invariant to scale and restores the right hemi sources.
FWIW the solution depends quite a bit on the particular regularization value.
> MRG: Fix custom inverse solver

- azure-pipelines.yml
- doc/whats_new.rst
- examples/decoding/plot_decoding_spoc_CMC.py
- mne/channels/channels.py
- mne/cov.py
- mne/io/array/array.py
- mne/io/array/tests/test_array.py
- mne/io/fieldtrip/tests/test_fieldtrip.py
- mne/io/pick.py
- mne/io/tests/test_pick.py
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- mne/preprocessing/tests/test_xdawn.py
- mne/rank.py
- mne/tests/test_rank.py
- mne/utils/__init__.py
- mne/utils/misc.py
- mne/utils/testing.py
- mne/viz/utils.py
On my machine:
- On 0656d8eef747ecb0d86631c18675feba3ab1fcae, the commit before the (noticed) regression, the example took 54s.
- On `master` it takes 232s.
- On this PR it takes 15s.
The big slowdown culprits:
- `mne.cov._compute_auto_covariance` constructed a `RawArray`, and it gets called ~700x by the example code. This exposed:
- `mne.utils._get_argvalues` used a slow method of inspection
- Needlessly copying `info` on instantiation of `RawArray`
- inefficiencies in `mne.cov._smart_eigh` where it can and should short-cut when `rank='full'`
- `mne.io.pick` used a very slow method for `_picks_by_type`, which:
- traversed the entire `info['chs']` array multiple times using `pick_types`, where...
- `pick_types` used a `switch`-like branching based on channel types
- there has been a …
> MRG: Much faster picking

- mne/externals/pymatreader/utils.py
This PR updates pymatreader to the latest version. The only (but important) change is that the uint64 datatype of matlab used to be handled as a character. This created problems when reading some FieldTrip structures.
> [MRG] Update pymatreader to version 0.0.19.

- doc/whats_new.rst
- mne/datasets/utils.py
- mne/io/eeglab/eeglab.py
- mne/io/eeglab/tests/test_eeglab.py
EEGLAB stores event durations in samples, so we need to convert that to seconds.
> Duration must also be in seconds for loading EEGLAB files

- examples/inverse/plot_lcmv_beamformer.py
- examples/inverse/plot_lcmv_beamformer_volume.py
- mne/beamformer/_compute_beamformer.py
- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_dics.py
- mne/beamformer/tests/test_lcmv.py
- mne/utils/check.py
Follow-up to #5947. This first step modifies LCMV to make it easier to eventually use `_prepare_forward`, specifically by:
Let's see if tests still pass. They do locally.
One potential problem I foresee is that `make_ad_hoc_cov` should be fine with projections, but will create problems with data that has been rank-reduced with SSS when `noise_cov=None` is used. However, this should be exceedingly rare since most SSS'ed data is Neuromag, which has two sensor types. To cover this, we'd need some way to project our `make_ad_hoc_cov` into the same data subspace as `data_cov`, which actually would be pretty straightforward given `_smart_eigh` gives us that projection already and it's used in the `cov` code. We can wait to deal with this until we hit a use case. But I'm assuming YAGNI for now. …
> MRG: Simplify LCMV whitening

- azure-pipelines.yml
The 3.5 Azure build has been failing in `master`. Let's see if just bumping to 3.6 is enough to get it working.
> MAINT: Bump azure [skip travis] [skip appveyor]

- .travis.yml
Should help us stay ahead of the curve on finding bugs. Follows what `pandas` does to get preleases (they just found a `sparse` matrix construction bug via this process).
> MRG: Use prelease of NumPy and SciPy in a build

- examples/connectivity/plot_mne_inverse_envelope_correlation.py
- mne/connectivity/envelope.py
- mne/minimum_norm/inverse.py
- Uses `return_generator=True` for hopefully some memory savings in the example
- Adds `verbose` kwarg which is useful in generator mode to see the progress
- Adds count to the epoch processing output
- Cleans up the checking of orientations in `apply_inverse_epochs` a tiny bit
> MRG: Use gen for STCs in envelope correlation example

- doc/whats_new.rst
- mne/annotations.py
- mne/io/cnt/_utils.py
- mne/io/cnt/cnt.py
- mne/io/cnt/tests/test_cnt.py
- mne/io/fieldtrip/tests/helpers.py
- mne/io/utils.py
In this PR:
This needs to go before #6025
> Add Annotations to CNT  + add code to deprecate stim_channel

- doc/whats_new.rst
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
This PR adds the option to change the value of `remove_dc` in `mne.io.Raw.plot` so users can change this on the fly by pressing the 'd' key.
> Allow toggling of DC removal in Raw.plot

- mne/datasets/sleep_physionet/tests/test_physionet.py
- mne/utils/fetching.py
- mne/utils/tests/test_fetching.py
Our old handling of `resume` failures was buggy, and I'm not convinced we need it anyway given that modern servers should handle resume requests. This simplifies our code and hopefully will make our tests a bit more robust.
> MRG: Simplify file retrieval

- doc/whats_new.rst
- mne/commands/mne_browse_raw.py
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
This PR:
- Adds FIR filtering (using MNE defaults) when browsing, since sometimes the IIR filtering does not provide sufficient attenuation
- Fixes a bug where filtering wasn't actually applied at all
> MRG: Add FIR filtering to raw.plot and fix filtering bug

- doc/whats_new.rst
- mne/viz/utils.py
This PR re-enables the vertical green line when you left-click inside the plot. I've disabled marking bad channels by clicking on a trace, because this never worked reliably. Instead, bad channels can (still) be marked by clicking on the label. Right-clicking inside the plot hides the green line.
> Re-enable vertical green line in raw.plot

- doc/whats_new.rst
- mne/bem.py
- mne/commands/mne_flash_bem.py
Fixes a bug where flash30 images would not be converted.
Also turns `verbose` on since people will presumably always want it on.
> FIX: Fix mne flash_bem

- doc/whats_new.rst
- mne/io/cnt/cnt.py
Tested locally like this:
```py
@pytest.mark.parametrize(
'fname',
[
op.join(data_path(download=False), 'CNT', 'scan41_short.cnt'),
op.join(confidential_path, 'BoyoAEpic1_16bit.cnt'),
op.join(confidential_path, 'cont_67chan_resp_32bit.cnt'),
op.join(confidential_path, 'SampleCNTFile_16bit.cnt'),
],
ids=op.basename
)
def test_events_and_annotations_are_the_same(fname, recwarn):
"""This test is meant to inspect int16-int32 issues"""
raw_cnt = mne.io.read_raw_cnt(fname, montage=None, stim_channel=True)
events = mne.find_events(raw_cnt)
events_id_without_0 = {str(x): x for x in (set(events[:, 2]))}
annot_events, events_id = mne.events_from_annotations(
raw_cnt, event_id=events_id_without_0)
np.testing.assert_array_equal(events[:, 0], annot_events[:, 0])
```
This is the trace comparing master …
> FIX: CNT 32bits annotations

- doc/whats_new.rst
- mne/io/cnt/cnt.py
> FIX: Montage Index error when importing CNT files

- mne/viz/raw.py
Annotation descriptions are hard to read in `raw.plot`:
This PR puts descriptions at the top and uses the corresponding annotation color:
> Put annotation descriptions at top and use individual color

- doc/_static/style.css
- doc/whats_new.rst
- mne/bem.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
The `.tri` files appear to already have the affine applied to them, so attaching it in the metadata causes it to reapplied. Using `master` on one MR I get:
And on this PR I get:
Confirmed everything should now be okay with `plot_alignment`:
Also contains a small CSS tweak to work with https://github.com/ryan-roemer/sphinx-bootstrap-theme/pull/193, and a couple of minor usability tweaks/shortcuts for `plot_alignment`.
> MRG: flash bem orientation

- doc/whats_new.rst
- mne/report.py
Chrome asks me if I want to translate my `Report` output pages. The default should probably be the default language used by MNE (en-us) since all of our captions, etc. use this language.
> BUG: Dont set Report language to fr

- azure-pipelines.yml
Apparently `skip azp` [should work now](https://developercommunity.visualstudio.com/idea/420289/add-support-ci-skip-and-azure-skip-to-azure-pipeli.html?childToView=503497#comment-503497). Either way our custom step did not work so we should remove it.
> ENH: Get rid of custom condition [skip azp] [skip travis] [skip circle]

- doc/configure_git.rst
- doc/git_links.inc
For now, just a search and replace trunk -> master.
Closes #5646
> In our GitHub contributor guide, replace references to trunk with master

- doc/whats_new.rst
- mne/decoding/receptive_field.py
- mne/decoding/tests/test_receptive_field.py
- tutorials/plot_receptive_field.py
The current RF version can make successive fits crash because of different length in feature_names
```python
from numpy.random import randn
from mne.decoding import ReceptiveField
rf = ReceptiveField(0, 10, 1., estimator=1e-3)
n_times = 100
Y = randn(n_times, 1)
rf.fit(randn(n_times, 2), Y)
rf.fit(randn(n_times, 3), Y)
```
Sklearn API does not change parameter variables at fitting. `feature_names` is currently modified at fitting if it is `None`, as it needs the number of features. 
Here is a quick fix
> FIX: Receptive field feature_name does not comply with sklearn API

- doc/whats_new.rst
- mne/io/base.py
- mne/tests/test_annotations.py
For consistency, whenever you call `set_annotations`, the resulting `raw.annotations` should have its `orig_time` set to match that of `raw`. See added test, which fails in `master` because previously calling it with `None` would have `orig_time=None`.
> MRG: set_annotations orig_time

- doc/python_reference.rst
- doc/whats_new.rst
- mne/annotations.py
- mne/filter.py
- mne/preprocessing/__init__.py
- mne/preprocessing/flat.py
- mne/preprocessing/tests/test_flat.py
- mne/utils/__init__.py
- mne/utils/numerics.py
- mne/utils/progressbar.py
I got some data that, due to being recorded right after a helium fill, tended to hit the ADC rails, e.g.:
With this PR I get:
```
Marking 0.56% of time points (11 segments) and 2/160 channels bad: ['MEG 142', 'MEG 155']
```
And you can see both modes of operation present in the result:
> MRG: Add mne.preprocessing.mark_flat

- mne/label.py
- mne/tests/test_label.py
On `master` doing `read_labels_from_annot('fsaverage', 'HCPMMP1.combined')` gives an impenetrable wall of text:
> OSError: No such file Anatomy/fsaverage/label/lh.HCPMMP1.combined.annot, candidate parcellations in that directory: lh.PALS_B12_Lobes.annot, rh.aparc.annot, rh.aparc.a2009s.annot, rh.PALS_B12_Visuotopic.annot, rh.HCPMMP1.annot, rh.aparc_sub.annot, rh.PALS_B12_Brodmann.annot, lh.aparc.a2009s.annot, lh.PALS_B12_Brodmann.annot, rh.PALS_B12_Lobes.annot, lh.oasis.chubs.annot, lh.aparc_sub.annot, lh.Yeo2011_17Networks_N1000.annot, lh.HCPMMP1.annot, lh.PALS_B12_OrbitoFrontal.annot, lh.Yeo2011_7Networks_N1000.annot, lh.aparc.a2005s.annot, lh.HCPMMP1_combined.annot, rh.Yeo2011_17Networks_N1000.annot, rh.PALS_B12_OrbitoFrontal.annot, rh.aparc.a2005s.annot, rh.HCPMMP1_combined.annot, …
> MRG: Better error message

- mne/beamformer/_dics.py
- mne/connectivity/effective.py
- mne/connectivity/spectral.py
- mne/decoding/transformer.py
- mne/forward/forward.py
- mne/minimum_norm/time_frequency.py
- mne/preprocessing/flat.py
- mne/source_estimate.py
- mne/tests/test_docstring_parameters.py
- mne/time_frequency/csd.py
- mne/time_frequency/multitaper.py
- mne/time_frequency/psd.py
- mne/utils/docs.py
- mne/viz/epochs.py
Closes #6102.
Also shortens a few very long param descriptions, which should help readability.
I thought about adding the `mt_*` params to the `docdict` but figured we can do it later if we need to, since there weren't too many of them (and the text has been stable for years).
> MRG: Percent signs, regression test

- doc/_static/style.css
- doc/sphinxext/gen_commands.py
- mne/commands/mne_browse_raw.py
- mne/commands/mne_bti2fiff.py
- mne/commands/mne_clean_eog_ecg.py
- mne/commands/mne_compare_fiff.py
- mne/commands/mne_compute_proj_ecg.py
- mne/commands/mne_compute_proj_eog.py
- mne/commands/mne_coreg.py
- mne/commands/mne_flash_bem.py
- mne/commands/mne_freeview_bem_surfaces.py
- mne/commands/mne_kit2fiff.py
- mne/commands/mne_make_scalp_surfaces.py
- mne/commands/mne_maxfilter.py
- mne/commands/mne_report.py
- mne/commands/mne_show_fiff.py
- mne/commands/mne_show_info.py
- mne/commands/mne_surf2bem.py
- mne/commands/mne_watershed_bem.py
I find it not so easy to read our [command-line docs](http://mne-tools.github.io/dev/generated/commands.html#mne-flash-bem):
Basically I tried to compromise between:
1. Compactness
2. Readability
3. Our API doc style/sections
4. What's standard in command-line utils, which is:
```console
larsoner@bunk:~/python/mne-python/doc$ grep --help
Usage: grep [OPTION]... PATTERN [FILE]...
Search for PATTERN in each FILE.
Example: grep -i 'hello world' menu.h main.c
Pattern selection and interpretation:
-E, --extended-regexp     PATTERN is an extended regular expression
-F, --fixed-strings       PATTERN is a set of newline-separated strings
-G, --basic-regexp        PATTERN is a basic regular expression (default)
-P, --perl-regexp         PATTERN is a Perl regular expression
...
```
This is the …
> DOC: Cleaner command line doc

- mne/channels/montage.py
Channel names read from .loc, .locs, and .eloc files were truncated to 4 character strings ("S4" numpy dtype).  Using `dtype=str` lets numpy determine the required string length.
-------
_PR description edited after amending.  Original message follows_
Channel names read from .loc, .locs, and .eloc files were truncated to 4 character strings ("S4" numpy dtype).  Increasing to "S8" for consistency with other formats.
Fixes #6090
I considered making the dtype longer (perhaps as long as `S256`) to allow for more flexibility, but I didn't want to break consistency with channel names from other formats.  I could make the change for the other formats as well, but I don't know much about the formats to know if there are any limitations the parser should account for.  I also wonder whether …
> FIX: Use 8-char string for channel names from .locs (#6090)

- doc/git_links.inc
- mne/viz/circle.py
Takes care of two broken links found by our weekly `linkcheck`:
https://circleci.com/gh/mne-tools/mne-python/12041?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification
I couldn't find a newer version of Nicolas Rougier's example, so I removed it. (Hopefully the remaining attribution is enough.)
> BUG: Fix broken links

- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
The more efficient version of #6080.
It was even trickier than I realized, since boolean indices do not broadcast, but proper integer indices do, so first we convert with `np.where` then use broadcasting rules to achieve the desired result.
@DiGyt can you take a look?
I also converted some of our old `assert_equal` to simpler/more explicit `assert ` or `assert_array_equal` statements.
> ENH: Make only one copy during crop

- mne/utils/config.py
To run mne in the browser using Pyodide (cPython + WebAssembly), we need to replace the `import multiprocessing` in `config.py` with a try statement within the `sys_config` function. Multiprocessing is not currently support in WebAssembly, which is why `multiprocessing` isn't packaged in the Pyodide build.
Is there way to have this backported to `0.17`? The build process for pyodide uses pypi and i've managed to get it to build for `0.17.1` (https://github.com/iodide-project/pyodide/pull/372)
> [MRG] Change multiprocessing import to a try statement

- doc/_templates/autosummary/class.rst
We have the SG backrefs for functions but not classes. This fixes that oversight.
> DOC: Include examples for classes

- doc/whats_new.rst
- mne/epochs.py
- mne/realtime/tests/test_mockclient.py
- mne/tests/test_epochs.py
- mne/tests/test_report.py
Fixes #5627
I added an `overwrite` parameter to `epochs.save`, similar to that in `raw.save`.
I set the default to be `overwrite=False`, for consistency with `raw.save`. This changes the behavior of `epochs.save`. Is this correct or should I add a deprecation warning?
I had to add `overwrite=True` as an argument to `epochs.save` in a number of unit tests, so that the behavior would be consistent with previous versions of `epochs.save`. Please also let me know if this is appropriate.
> ENH: Added overwrite parameter to epochs.save

- doc/whats_new.rst
- mne/cuda.py
Fixes #6130
both `r_z_pad` and `l_z_pad` were using only  `n_pad[0]`; I've changed `r_z_pad` so that it takes `n_pad[1]`
>  n_pad[1] is included in r_z_pad  #6130

- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
fixes #6121. Now it works:  
I can add a test tomorrow.
Another possibility to fix is that `title` different from None rarely would make sense if user passes the exes himself. The simplest solution would be to default to `title=None` when axes are passed.
> FIX for #6121: when user passed axes to plot_joint they shouldn't be modified (the axes, not the user)

- .gitignore
- doc/whats_new.rst
- mne/source_space.py
- mne/surface.py
- mne/tests/test_source_space.py
- mne/utils/__init__.py
- mne/utils/_testing.py
Adds an algorithm to `mne.setup_source_space` that MNE-C had that we did not that uses approximate distance-based vertex choosing:
```
import mne
src = mne.setup_source_space('sample', 7, add_dist=True, n_jobs=2, verbose=True)
for ii in range(2):
src[ii]['dist'].data = 1 - src[ii]['dist'].data
min_dists = 1000 * np.concatenate([
1 - src[0]['dist'].max(axis=1).data, 1 - src[1]['dist'].max(axis=1).data])
plt.hist(min_dists, 100)
```
Gave:
```
Subject      = sample
Surface      = white
Approximate spacing 7 mm
1. Creating the source space...
Loading /mnt/bakraid/data/structurals/sample/surf/lh.white...
Mapping lh sample -> spacing (7) ...
Triangle neighbors and vertex normals...
Vertex neighbors...
Decimating...
loaded lh.white 3567/155407 …
```
> ENH: Add distance-based source space setup

- mne/label.py
- mne/tests/test_label.py
I often want to combine labels using `sum`, this PR at least makes it so that instead of having to do:
```
label = sum(labels, mne.Label([], hemi='lh', subject='fsaverage'))
```
I can now do it a tiny bit more easily:
```
label = sum(labels, mne.Label(hemi='lh', subject='fsaverage'))
```
I could fairly easily get rid of the `subject` requirement (I think?) by being more permissive about `subject=None` in our label-addition code, but that doesn't seem worth the risk. Allowing `hemi=None` would probably be brittle and require a lot more code logistics, so probably not worth it, either.
> MRG: Default Label to empty vertex list

- mne/report.py
- mne/tests/test_report.py
When adding sliders to an HTML `Report`, the entry made in the menu on the left took the section name, instead of the title of the figure:
This PR fixes this.
> Use title of slider in HTML report menu

- doc/whats_new.rst
- mne/proj.py
- mne/tests/test_proj.py
Makes `duration=None` and `duration=1.` (default) equivalent when possible. Bugs:
1. `baseline=None` should have been used in Epochs constructor
2. `proj=False` should have been used in Epochs constructor
3. `tmax=duration - 1. / sfreq` should have been used in Epochs constructor
4. More careful handling of `duration` for non-integer sample rates
> MRG: Fix inconsistencies with compute_proj_raw

- doc/python_reference.rst
- doc/whats_new.rst
- mne/event.py
- mne/tests/test_event.py
I added this option so that I can call `shift_time_events` in this manner:
```diff
- events = mne.event.shift_time_events( events, ids=np.unique(events[:,2]),  tshift=trigger_offset,  tshift, sfreq=raw.info['sfreq'])
+ events = mne.event.shift_time_events( events, ids='all',  tshift=trigger_offset,  tshift, sfreq=raw.info['sfreq'])
```
> ENH: Add the ids='all'  as an option for mne.event.shift_time_events

- mne/viz/evoked.py
- mne/viz/utils.py
This PR:
- uses `logger.info` instead of `warn` when truncating long titles
- when `mne.viz.plot_compare_evokeds(..., picks='grad')` (or any `picks` that is a single channel type), sets title to the channel type instead of listing out (and truncating) channel names.
> MRG+1: better title in plot_compare_evokeds (closes #6165)

- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/data/test_bad_date.vhdr
- mne/io/brainvision/tests/data/test_bad_date.vmrk
- mne/io/brainvision/tests/test_brainvision.py
Fixes #6054 
Changes:
- Removing a superfluous  conditional check that is already handled shortly afterwards 
- Introducing a test case that reproduces the error described by @petergrey75 in #6054 
- Inserting a try-except clause in `_str_to_meas_date` to fix the error
> MRG: Fix BrainVision date error

- mne/viz/evoked.py
Closes #6199
This code works for me with this PR:
```
import os
import mne
sample_data_ave_file = os.path.join(sample_data_folder, 'MEG', 'sample',
'sample_audvis-ave.fif')
evokeds = mne.read_evokeds(sample_data_ave_file, baseline=[None, 0])
mne.viz.plot_compare_evokeds(evokeds)
```
@drammock
> MRG + 1: Lazy figures for plot_compare_evokeds

- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_lcmv.py
- mne/utils/check.py
This makes sure the right ``picks`` are used when creating an ad-hoc noise covariance matrix in the beamformer computation. 
If no noise covariance matrix is supplied to ``make_lcmv``, an ad-hoc noise covariance matrix is computed. This computation did not take channel selections into account, i.e., the output noise covariance matrix had the wrong dimensions.
@larsoner
> MRG: Beamformer: compute ad-hoc noise cov with right dimensions

- conftest.py
- doc/_static/style.css
- doc/python_reference.rst
- doc/whats_new.rst
- examples/simulation/plot_simulate_raw_data.py
- mne/datasets/testing/__init__.py
- mne/datasets/testing/_testing.py
- mne/filter.py
- mne/forward/_field_interpolation.py
- mne/forward/forward.py
- mne/io/base.py
- mne/label.py
- mne/simulation/__init__.py
- mne/simulation/evoked.py
- mne/simulation/raw.py
- mne/simulation/tests/test_raw.py
- mne/source_estimate.py
- mne/source_space.py
- mne/tests/test_chpi.py
- mne/utils/docs.py
- tutorials/plot_dics.py
Todo list:
Current monolithic API:
```
raw_sim = simulate_raw(raw, stc, trans, src, bem, cov='simple', blink=False, ecg=False, chpi=False, head_pos=None, mindist=1.0, interp='cos2', iir_filter=None, n_jobs=1, random_state=None, use_cps=True, forward=None, duration=None, verbose=None)
```
New API, treating `simulate_` functions as "smart apply_forward with head position support":
```
raw_sim = simulate_raw(raw, stc, trans, src, bem, chpi=False, head_pos=None, mindist=1.0, interp='cos2', n_jobs=1, use_cps=True, forward=None, verbose=None)
raw_sim = add_ecg(raw_sim, head_pos=None, random_state=None, verbose=None)
raw_sim = add_eog(raw_sim, random_state=None, verbose=None)
raw_sim = add_noise(raw_sim, noise_cov)
```
No example update to use the `iterable` support since it will probably make …
> MRG+1: Add iterable support to simulate_raw

- mne/viz/epochs.py
This is to make it easier to handle the unification of topo plotters and single sensor plotters.
@drammock
> MRG: refactor internals for epochs image plot

- doc/whats_new.rst
- mne/cuda.py
- mne/decoding/receptive_field.py
- mne/decoding/tests/test_receptive_field.py
- mne/decoding/time_delaying_ridge.py
- mne/utils/progressbar.py
Depends on #5452.
I can get some reasonable gains:
```
Running  2 in, -150 - 250 ms; 1.0 min epochs; 10000.0 Hz; 60 epochs
n_out= 2 n_jobs=   1: 0.81 min
n_out= 2 n_jobs=cuda: 0.69 min
n_out=60 n_jobs=   1: 4.28 min
n_out=60 n_jobs=cuda: 1.33 min
```
Using [this gist](https://gist.github.com/larsoner/c58127bc466e8e8b7ce38af9f6ab825f).
~~The remaining time seems to be consumed mostly by the special treatment that we need to give edge samples. One way to fix it is to add an arg `edge_treatment='correct' | 'trim'` that will just trim the invalid values of the FFT-based cross-correlation instead of correcting them. Basically this would mean if you pass 1.4 sec of data and estimate a -0.2 to 0.2 TRF, it will only use 1 sec of the data to do this. Essentially a wider crop / epoching of your …
> MRG: Speed up RF fitting with CuPy

- mne/viz/utils.py
closes #6219 
```py
import os
import mne
raw = mne.io.read_raw_fif(sample_data_raw_file, verbose=False)
raw.crop(10).load_data().pick_types(meg=False, eeg=True).plot(butterfly=True)
```
(same code as above)
```py
import os
import mne
raw = mne.io.read_raw_fif(sample_data_raw_file, verbose=False)
raw.crop(10).load_data().plot(butterfly=True)
```
```py
import os
import mne
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', …
```
> MRG: avoid empty misc row in raw butterfly plots

- mne/epochs.py
- mne/viz/tests/test_topo.py
- mne/viz/topo.py
closes #6112 
color limits on `epochs.plot_topo_image()` are messed up. Example code:
```py
import os
import mne
raw = mne.io.read_raw_fif(sample_data_raw_file, verbose=False)
event_dict = {'auditory/left': 1, 'auditory/right': 2, 'visual/left': 3,
'visual/right': 4, 'face': 5, 'button': 32}
raw.info['bads'].append('EEG 007')
reject_criteria = dict(mag=4e-12, grad=4e-10, eeg=150e-6, eog=250e-6)
epochs = mne.Epochs(raw, events, event_id=event_dict, reject=reject_criteria,
preload=True)
epochs.plot_topo_image(sigma=0.5)
```
> FIX: proper channel-type-specific vmin/vmax in topo image plots

- setup.cfg
Adds to the `ignores` list for `pytest`. I have accidentally done `$ pytest` (alone) in the `mne-python` directory and it's brutal because `pytest` tries to collect tests in `examples/` and `tutorials/`. This explicitly removes those so this will not happen. Now `pytest mne` is practically the same thing as `pytest`.
As a side effect it makes VSCode automated test discovery not make the same mistake...
cc @drammock feel free to try VSCode test discovery on this branch. (Do not try it on master unless you want your laptop to become a heater.)
> MRG: Be explicit about exclusions

- doc/whats_new.rst
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
Before this fix, attempting to access a vhdr file with associated vmrk would give the following error:
```
~mne-python/mne/io/brainvision/brainvision.py in _read_annotations_brainvision(fname, sfreq)
257         The annotations present in the file.
258     """
--> 259     onset, duration, description, date_str = _read_vmrk(fname)
260     orig_time = _str_to_meas_date(date_str)
261 
ValueError: not enough values to unpack (expected 4, got 0)
```
Presumably because there were no annotations. Now the code skips attempting to retrieve annotations when there are none.
> [MRG+1] Fixed error when there are no annotations in vmrk file

- mne/viz/tests/test_epochs.py
#6210 introduced a warning that comes from deep within matplotlib; this silences it.
> ignore mpl warning

- doc/whats_new.rst
- mne/channels/interpolation.py
- mne/channels/tests/test_interpolation.py
Replaces #5966 due to problems with git history there.
> [FIX] Exclude ref_meg for channel interpolation of CTF data 2nd try

- mne/beamformer/_compute_beamformer.py
- mne/beamformer/tests/test_dics.py
The case when `inversion='single', pick_ori='max-power', weight_norm='ai'` was not caught by the if-statements in `_compute_beamformer`.
> MRG+1: Fix weight_norm='nai' on DICS

- mne/tests/test_cov.py
Our `master` branch is failing on the NumPy+SciPy prelease run (3.7):
https://travis-ci.org/mne-tools/mne-python/jobs/525233956
I'm checking to see if a little tolerance bump fixes things. Either way, we might have something to look into, especially since SciPy has changed the default tolerances for pinv/pinv2/pinvh, and maybe other functions.
> MRG: Cov tolerances

- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
This is a one-character fix for inst.resample, when also resampling events.
The ceiling-check of the max. index of the resampled events was missing a -1, so e.g. cropping to the same data-segment between two events before and and again after resampling resulted in an error.
> FIX resampling events indices

- mne/filter.py
Fixes some small docstring errors in the filter.py file. 
As I was looking through `filter.py`, I realized there were some small mistakes in the docstrings of a couple functions (for examples, `sfreq` being described as `Fs` in the docstring), so I figured I could make a quick fix on those.
> DOC: Fix some docstrings in filter.py

- doc/whats_new.rst
- mne/viz/utils.py
During reshaping of the axes channel data got dispersed.
Fixes #6226.
Axes need to be swapped to ensure correct reshaping according to channel attributions.
> Fix _compute_scalings() for autoscale

- doc/conf.py
- doc/documentation.rst
- doc/whats_new.rst
- examples/connectivity/plot_mne_inverse_envelope_correlation_volume.py
- mne/connectivity/envelope.py
- mne/epochs.py
- mne/evoked.py
- mne/filter.py
- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/minimum_norm/inverse.py
- mne/parallel.py
- mne/source_estimate.py
- mne/tests/test_docstring_parameters.py
- mne/tests/test_evoked.py
- mne/utils/numerics.py
- mne/viz/_3d.py
Related to #6109 (cc @jhouck), this shows one way to use envelope correlations with a free-ori source space using `lcmv` beamforming. FWIW you can do the same thing with a surface source space if you want. In that case you get to use labels, which is nice. We don't currently have a good way of label-combining our volumetric source spaces, which is unfortunate.
I am working on a [correlation measure](https://gist.github.com/larsoner/17be3f92ae8cc7ed08bdf90f98ca60f0) that is rotation + scale invariant to deal with correlating two arrays, each of shape `(3, n_times)` so that you could in prinicple use `VectorSourceEstimate`s, but so far it does not give as nice parietal network results when I actually use it in `envelope_correlation`.
While working on this I found a few more things that …
> MRG: envcorr for free ori source spaces

- doc/python_reference.rst
- doc/whats_new.rst
- mne/beamformer/__init__.py
- mne/beamformer/_compute_beamformer.py
- mne/beamformer/_dics.py
- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_external.py
This allows to apply the LCMV spatial filter to the covariance matrix to obtain a power estimate (not time-resolved).
In the process, we refactored ``apply_dics_csd`` with @wmvanvliet to have one function ``_compute_power``, since the operations for LCMV and DICS are similar.
A test against FieldTrip is to follow, output converges.
Closes #5229
> MRG: Power estimate for LCMV: apply_lcmv_cov

- mne/annotations.py
- mne/tests/test_annotations.py
Closes #6258
Could also allow additional argument - `min_chunk_duration` (a bit shorter than `chunk_duration` by default for example 85%).
But in its current shape it seems to be simple enough. I could add warnings if some annotations cannot generate events due to chunk_size being too long.
> MRG: fix annot->events chunk size

- doc/git_links.inc
- doc/install_mne_c.rst
Also moves any links that are not actually shared by other files back into the page source (instead of in `git_links.inc` or similar).
> MRG, DOC: MNE-C install on macOS; closes #5961

- doc/whats_new.rst
- mne/dipole.py
- tutorials/sample-datasets/plot_brainstorm_phantom_elekta.py
The sign flips in our Elekta example always bothered me:
http://mne-tools.github.io/dev/auto_tutorials/sample-datasets/plot_brainstorm_phantom_elekta.html#sphx-glr-auto-tutorials-sample-datasets-plot-brainstorm-phantom-elekta-py
Turns out that `get_phantom_dipoles` had the orientations of some dipoles wrong by 180 degrees. This fixes it. It also removes `maxwell_filter` from the example to save a tiny bit of memory, since this example has been crashing CircleCI lately.
> MRG, FIX: Fix dipole orientations

- mne/decoding/receptive_field.py
- mne/decoding/tests/test_receptive_field.py
Tiny fix to a variable name typo in an error message. Then modernized the `receptive_field` tests while I was in there.
> MRG, FIX: Fix error message for ReceptiveField

- azure-pipelines.yml
Now that https://github.com/astropy/ci-helpers/pull/390 is in, we can switch back to `astropy`'s version.
> MRG, MAINT: Update Azure

- doc/conf.py
- doc/whats_new.rst
- mne/io/fiff/raw.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/open.py
- mne/io/tag.py
- mne/io/tests/test_raw.py
Closes #5867.
@arokem is it easy for you to test what you wanted to do in #5867? The caveat is that you must use `preload=True` or `preload='/some/memmap/filename'`.
> MRG, ENH: Allow reading file-like objects

- MANIFEST.in
- mne/conftest.py
- setup.cfg
Inspired by https://github.com/scipy/scipy/pull/10178, I realized there is a nice way to unify where we keep all of our global `pytest` options. We can remove them from `setup.cfg` and put them in `conftest.py` (and move that to `mne/` instead of the root directory).
Should be useful for maintenance purposes, but let's make sure it does not break anything.
> MRG, MAINT: Move conftest

- doc/conf.py
- mne/cov.py
- tutorials/sample-datasets/plot_brainstorm_phantom_elekta.py
- tutorials/sample-datasets/plot_sleep.py
- Tweaks the brainstorm phantom Elekta dataset example to use ~500 MB less memory. The tradeoff is that we no longer filter / preprocess in any way. I think this is fine, especially since it takes the loc bias just from 2.0 mm to 2.6 mm. The memory bottleneck is now in `epochs.get_data()[..., time_slice]` in `cov` code, which could be solved by adding `tmin/tmax` to `epochs.get_data` but this is actually quite complicated due to our internal implementation of `epochs._get_data` doing many things. But hopefully it's good enough for now.
- Simplified a tiny bit the sleep tutorial while unsuccessfully looking for memory savings there.
- Added an explicit garbage collection during our between-example resets to hopefully help keep memory usage as low as possible.
> MRG, ENH: Lower mem usage

- mne/forward/_make_forward.py
- mne/utils/_testing.py
- mne/utils/misc.py
- mne/viz/backends/renderer.py
- mne/viz/utils.py
Follow-up to #5775 to fix `contextlib.contextmanager` use to use `try/finally` pattern, because I can't seem to internalize that I need to use it in the first place.
> MRG, BUG: Fix contextmanager use

- mne/conftest.py
- mne/tests/test_epochs.py
- setup.cfg
I noticed locally that the `pytest` `addopts` entry was not working with `pytest_configure`. This is perhas a `pytest` bug, or maybe it's not since it has probably already parsed the options before it calls our `conftest.py`. There might be a way to set these in `pytest_configure`, but for now let's restore it in `setup.cfg` so things work properly.
Also split a slow `epochs` test that was causing spurious Azure failures, and modernized a few of the `pytest.raises` checks there.
> MRG, FIX: Restore working "addopts", epochs test

- doc/whats_new.rst
- mne/preprocessing/flat.py
- mne/preprocessing/tests/test_flat.py
- mne/tests/test_annotations.py
Onsets were calculated relative to the first sample and not to the `raw.info['meas_date']`.
Fixes #6295.
I shifted the onsets by `raw.first_samp / raw.info['sfreq']` to the right so that their timing is relative to  `raw.info['meas_date']`.
> MRG: shifted onsets of annotations created by mark_flats

- mne/tests/test_annotations.py
It occurred to me that it might be nice to have a specific regression test for #5908.
@massich might be good to have while working on #5857
> MAINT: Extra test for annotations

- doc/whats_new.rst
- mne/io/fiff/raw.py
- mne/io/fiff/tests/test_raw_fiff.py
split save and reload a FIF file fails due to Annotations
Fixes #5856
> [MRG] FIX: save-load split FIF round trip

- doc/glossary.rst
- doc/manual/datasets_index.rst
- doc/manual/io.rst
- tutorials/intro/plot_introduction.py
- tutorials/time-freq/plot_sensors_time_frequency.py
This overhauls `tutorials/intro/plot_introduction.py` ([this one](https://mne-tools.github.io/dev/auto_tutorials/intro/plot_introduction.html#sphx-glr-auto-tutorials-intro-plot-introduction-py)).  The goal is to keep this as the "high-level overview" first tutorial that all new users would read before moving on to more specific tutorials or tutorial sequences germane to their particular interests / use cases.
- Changes to `doc/glossary.rst`, `doc/manual/io.rst` and `doc/manual/datasets_index.rst` are to make those entries/sections easier to cross-reference
- this PR does *not* establish fixed order of tutorials (that will be done in a separate PR after all revisions of tutorials in the "intro" section are done)
> MRG, DOC: overhaul intro tutorial

- doc/contributing.rst
#5857 timeline shows that azure ignored the `[ci skip]` tag in 4a5c543 commit. 
@larsoner feel free to take over if you know how to fix it? (otherwise, I'll do it after release)
@drammock do you think we should add a description of the tags. Feel free to push in this PR to reword anything you like.
> MAINT, FIX: [ci skip] tag is ignored by azure.

- doc/whats_new.rst
- mne/defaults.py
- mne/preprocessing/tests/test_ica.py
- mne/viz/_3d.py
- mne/viz/epochs.py
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
- mne/viz/tests/test_utils.py
- mne/viz/topo.py
- mne/viz/utils.py
Closes #6271.
Tested on `master` by adding `ica.get_sources(raw).plot()` on line 90 of `plot_artifacts_correction_ica.py` which looks like:
And on this PR:
> MRG, ENH: Auto-scale misc channels by default

- mne/io/edf/edf.py
Should fix failures on `master` with NumPy dev. Doing `np.maximum(x, 1, out=x)` should be effectively the same as  `np.clip(x, 1, np.inf, out=x)` (because the `np.inf` shouldn't actually clip), slightly more efficient, and avoid the casting warning.
> MRG, FIX: Clipping on uint32 dtype

- logo/generate_mne_logos.py
I wanted to create a bigger MNE logo for an upcoming workshop. These changes were needed to get it to run with latest `matplotlib` where `bivariate_normal` is gone. FYI here is the output I came up with after tweaking `dpi=600`, `delta=0.01`, and `tagline_offset_fudge = [0.4, -100]` (the lower right N is a tiny bit cut off but it's good enough for me):
Thanks again to @drammock for scripting this so it was easy to make a higher-res PNG!
> MRG, MAINT: Update logo code

- mne/io/pick.py
- mne/viz/epochs.py
- mne/viz/tests/test_epochs.py
the info message `No picks and no groupby, showing the first five channels ...` is incorrectly shown when the `picks` parameter to `epochs.plot_info()` is a (list of) channel *names* (the message should only happen when `picks` is a channel type or list of channel types).
on current master, this (wrongly) generates the info message; after this PR it does not:
```python
from mne.viz.tests.test_epochs import _get_epochs
epochs = _get_epochs().load_data()
epochs.plot_image(picks='MEG 1332')
```
after this PR, the message is still (correctly) generated for:
```python
epochs.plot_image(picks='mag')
```
> MRG, FIX: avoid spurious "showing first five" message

- examples/datasets/plot_hf_sef_data.py
- mne/datasets/hf_sef/hf_sef.py
Should be the last thing we need for 0.18. Get `hf_sef` to work again even though Zenodo is down, so that CircleCI can build properly again. Can't move the `raw` dataset because I don't have the files, but all that CircleCI needs is the evoked anyway.
> MRG, FIX: Move hf_sef dataset

- doc/whats_new.rst
- examples/decoding/plot_decoding_csp_eeg.py
- examples/decoding/plot_decoding_csp_timefreq.py
- examples/time_frequency/plot_time_frequency_erds.py
- mne/annotations.py
- mne/io/brainvision/tests/test_brainvision.py
- mne/tests/test_annotations.py
The "arbitrary integer assignment" change we made broke the EEGBCI example. There probably always should have been an `event_id` to prevent the assignments from being arbitrary, this fixes it.
> MRG, FIX: Remove BAD and EDGE from events

- doc/conf.py
- doc/whats_new.rst
- examples/realtime/plot_compute_rt_average.py
- examples/realtime/plot_compute_rt_decoder.py
- examples/realtime/plot_ftclient_rt_average.py
- examples/realtime/plot_ftclient_rt_compute_psd.py
- examples/realtime/plot_lslclient_rt.py
- examples/realtime/plot_rt_feedback_server.py
- examples/realtime/rt_feedback_client.py
- mne/conftest.py
- mne/realtime/client.py
- mne/realtime/epochs.py
- mne/realtime/fieldtrip_client.py
- mne/realtime/lsl_client.py
- mne/realtime/mock_lsl_stream.py
- mne/realtime/mockclient.py
- mne/realtime/stim_server_client.py
We would like to deprecate the realtime module object this release cycle so that they can be removed in the next. this PR attempts to do so.
> MAINT: deprecate mne.realtime

- mne/channels/channels.py
- mne/channels/tests/test_channels.py
I have a use case where I have a set of channel names which I want to drop. It would be nice if I could directly pass the set to `raw.drop_channels`, which I have implemented in this PR.
> [MRG] Allow iterable in drop_channels

- mne/annotations.py
- mne/io/brainvision/brainvision.py
- mne/tests/test_annotations.py
- mne/utils/__init__.py
- mne/utils/misc.py
Things I wanted to ask in #6326 but I didn't have the chance. 
It avoids returning `lambda: None` + adds a test in case `event_id='random string'`. What I did not got away with is a form to not pass `raw` to `_check_event_id`. (which can be big and so on). @larsoner can you see a way? Maybe defining the function within or braking it again in two functions which we end up at the same place as we started.
Anyways, feel free to push in the branch or close
> STY: prefer _DefaultEventParser to _Counter

- .circleci/config.yml
- doc/_static/style.css
- doc/conf.py
- doc/documentation.rst
- doc/sphinxext/sphinx_bootstrap_divs/__init__.py
- doc/sphinxext/sphinx_bootstrap_divs/bootstrap_divs.css
- doc/sphinxext/sphinx_bootstrap_divs/bootstrap_divs.js
I went to implement `panel`-style clickables to tackle #6365, and got a bit tired of how the raw HTML calls in our doc made things difficult to do and difficult to read. So I made a `sphinx_bootstrap_divs` package that bundles this stuff into `.. collapse::` and `.. details::` directives:
https://github.com/larsoner/sphinx-bootstrap-divs
If people agree that this is a useful change, I can push 1.0 to `pypi` and I'll add the requirement to the dev docs. Also maybe this should be hosted by `mne-tools` and not on my personal repo...
> ENH: Simpler syntax

- examples/simulation/plot_simulated_raw_data_using_subject_anatomy.py
The changes included in this PR are proposed in the discussion
of PR #6256 and #6261.
This PR changes the simulation of source time courses in the example for
simulating raw data using subject anatomy. Initially, sine wave was used for
source time courses and it was the same for each of the 4 simulation conditions.
In this PR, a new function is added which enables to generate source activity for
evoked responses, parametrized by latency and duration. Stcs are simulated for
a single condition at the time.
> ENH: Include more realistic simulations to example for simulating raw data using subject anatomy

- mne/__init__.py
- mne/inverse_sparse/mxne_inverse.py
- mne/tests/test_docstring_parameters.py
We missed `from . import inverse_sparse` so you cannot currently do:
```
import mne
mne.inverse_sparse.mixed_norm(...)
```
> MRG, FIX: Imports

- mne/commands/mne_browse_raw.py
- mne/source_estimate.py
Minor fix to set the same expected `clipping` arg in `mne_browse_raw` help message as that of `raw.plot()` docstring. Along with additional _NB_ in `extract_label_time_course` as per @larsoner.
> Minor fixes to docs

- mne/commands/mne_browse_raw.py
I often try to and want to do:
```
mne browse_raw <filename>
```
This makes sense because positional arguments are often used for obligatory variables, which `raw` is here. This PR allows for this syntax, but still supports the existing one:
```
mne browse_raw --raw <filename>
```
> MRG, ENH: Allow passing raw as arg

- .gitignore
- doc/whats_new.rst
- mne/viz/utils.py
Closes #6367.
@cbrnr can you see if this fixes things for you? In case you're curious, I found it just by creating a MacOSX figure and inspecting `fig.canvas._` properties (actually I looked right at `fig.canvas._d`-tab-tab and got lucky that the MacOSX private propetry `_device_scale` started with the same letter as the Qt5Agg one `_dpi_ratio`).
Upstream report https://github.com/matplotlib/matplotlib/issues/14405
> MRG, BUG: Fix MacOSX backend HiDPI scaling

- LICENSE.txt
Fixes our license to be compliant with the somewhat strict `Licensee` parsing [used by GitHub](https://developer.github.com/v3/licenses/). For example after this PR we should see at the top of the page the same thing you see here:
https://github.com/scipy/scipy/blob/master/LICENSE.txt
Tested with the following Ruby script, inspired from a recent SciPy PR:
```
require "licensee"
mne = Licensee.project("mne-python")
print mne.license.name
print "\n"
print mne.matched_file.filename
print "\n\n"
```
Which now says:
```
BSD 3-Clause "New" or "Revised" License
LICENSE.txt
```
Instead of on `master`:
```
Other
LICENSE.txt
```
> MRG, MAINT: Fix license

- mne/time_frequency/tests/test_tfr.py
- mne/viz/tests/test_topomap.py
- requirements.txt
Closes #6397.
If this does not work with the newly released 4.6.1, I'll add another `!=` in there to get things green. Eventually we can investigate why things are not working but it would be good to get CIs back in the meantime.
> MAINT: Fix pytest

- .mailmap
- doc/whats_new.rst
- mne/io/eeglab/eeglab.py
Fixed error with: 
epochs = mne.read_epochs_eeglab(epochs_fname) 
when attempting to load preprocessed eeg data from eeglab
```py
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-3bb48e976843> in <module>
----> 1 epochs = mne.read_epochs_eeglab(epochs_fname)
~/Documents/administrative/training/MNE-python/mne-python/mne/io/eeglab/eeglab.py in read_epochs_eeglab(input_fname, events, event_id, montage, eog, verbose, uint16_codec)
244     epochs = EpochsEEGLAB(input_fname=input_fname, events=events, eog=eog,
245                           event_id=event_id, montage=montage, verbose=verbose,
--> 246                           uint16_codec=uint16_codec)
247     return epochs
248 …
```
> FIX: read_epochs_eeglab for floats

- doc/manual/datasets_index.rst
- examples/datasets/plot_hf_sef_data.py
- examples/inverse/plot_dics_source_power.py
- examples/time_frequency/plot_time_frequency_global_field_power.py
- tutorials/sample-datasets/plot_phantom_4DBTi.py
The [somato](http://martinos.org/mne/stable/manual/datasets_index.html?#somatosensory) dataset shipped with `mne.datasets` is used in more examples than the docs show. In this PR I am adding the missing links.
These links are already correct in the API documentation ([here](http://martinos.org/mne/stable/generated/mne.datasets.somato.data_path.html?highlight=somato#mne.datasets.somato.data_path))
Now they should also be correct in the datasets documentation page.
> link examples to somato dataset

- doc/whats_new.rst
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
There were a few times during the workshop last week that I wanted to do `plot_alignment` with a one-layer BEM but also the head surface. It allows seeing if the coreg is any good. This PR enables it.
> MRG, ENH: Allow showing head surf with 1-layer BEM

- mne/io/proj.py
- mne/tests/test_proj.py
`make_projector` should always return `ndarray` for `U`.
> MRG, BUG: empty should return ndarray

- mne/conftest.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/renderer.py
- mne/viz/backends/tests/test_renderer.py
- mne/viz/tests/test_3d.py
While looking at #6403 I realized our 3D backend code / testing infrastructure could be simplified:
1. `yield mne.viz.renderer` instead of plain `yield` to give us access to the renderer functionality directly (no need for most `import` statements in tests anymore)
2. Rename `backends_3d` to `renderer` to reflect what the fixture will actually yield
3. DRY code for importing by using a dict lookup and `importlib` call rather than duplicated functions in conditional branches`from ._whatever import ...`
4. Add a private `_close_all()` function to each module that will close all open figures (this was used a lot in the 3D code)
Currently only `mayavi` supports (4) but we should inquire with `pyvista` if there is a way to keep track. If not, we might want to have a way of tracking …
> MRG, MAINT: DRY code

- doc/documentation.rst
- doc/whats_new.rst
- examples/time_frequency/plot_source_power_spectrum.py
- examples/time_frequency/plot_source_power_spectrum_opm.py
- mne/decoding/transformer.py
- mne/minimum_norm/time_frequency.py
- mne/time_frequency/multitaper.py
- tutorials/sample-datasets/plot_sleep.py
Yesterday I wanted to show a colleague our source PSD normalization, but it was difficult to find. This re-tittles and moves it to a more appropriate location with better title keywords.
Also I changed "power spectrum density" (PSD) to be the more standard (AFAIK) "power spectral density".
@drammock feel free to merge if you're happy
> MRG, DOC: Better org of source PSD

- mne/io/pick.py
- mne/viz/tests/test_epochs.py
Takes care of when a user uses the default `picks=None` but this results in no picks being found.
Closes #6379.
No need for `whats_new.rst` update I think since it's just a more explicit error message.
> MRG, ENH: Better error message for bad choice of picks

- mne/utils/misc.py
Doing `subprocess.Popen.wait` when using `PIPE` mode can cause deadlocks:
https://docs.python.org/3.7/library/subprocess.html#subprocess.Popen.wait
This avoids the problem in `run_subprocess` by calling `communicate`.
> MRG, FIX: Dont wait when piping

- mne/conftest.py
- requirements.txt
Closes #6424.
Not sure why this was needed, @massich feel free to chime in. In the meantime maybe the CIs will tell us.
> MRG, MAINT: remove matplotlib version pin

- doc/whats_new.rst
- mne/viz/epochs.py
- mne/viz/tests/test_epochs.py
As seen below `_convert_psds` expects the psds to be of shape `(n_channels, n_freqs)`
https://github.com/mne-tools/mne-python/blob/a2c75903d4471587582bc2715985dc82eff9ac12/mne/viz/raw.py#L641-L642
However in plot `plot_epochs_psd` we were passing in an `(n_epochs, n_channels, n_freqs)` array which was causing the flat channel error checking to be wrong.
> FIX - plot_psd_epochs

- doc/whats_new.rst
- mne/source_estimate.py
- mne/tests/test_source_estimate.py
Fixes broken reading of VolVectorSourceEstimate H5 files. I guess I'm the first one to `read_source_estimate` a `VolVectorSourceEstimate`!
> MRG, FIX: VolVectorSourceEstimate read

- mne/viz/raw.py
- mne/viz/tests/test_raw.py
Fixes #6425. This allows manipulating keybinds after the raw plot has been created, which is useful e.g. if you want to remove the Escape shortcut to close the window.
> Add params to raw.plot figure

- doc/whats_new.rst
- mne/annotations.py
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
This PR fixes this (see discussion in #6326):
```py
raw = read_raw_brainvision(...)
raw.save(fname)
raw_read = read_raw_fif(fname)
events_from_annotations(raw_read, event_id='auto') == events_from_annotations(raw, event_id='auto') # now they are equal!!
```
> FIX: allow raw_fif to parse brainvision events

- mne/realtime/mock_lsl_stream.py
I accidentally re-introduced the multiprocessing top-level import that causes problems when trying to use mne-python with webassembly. this corrects the issue.
> [backport] add try statement to multiprocessing import

- doc/whats_new.rst
- mne/source_space.py
- mne/surface.py
- mne/tests/test_source_space.py
I used `oct-4` or `ico-4` and got a cryptic error message about not finding a BEM surface. This fixes it by explicitly checking that the int we get is >=0 for ico and >=1 for oct.
> MRG, DOC: Better error message for bad spacing

- mne/datasets/tests/test_datasets.py
Speeds up the `megsim` dataset test a bit by faking the file download. We can trust the Circle full build to check (less frequently, e.g. every day or so rather than on every PR) that the data are downloaded properly. In the meantime this should at least get Travis and Azure green.
> MRG, MAINT: Faster, simpler megsim test

- doc/whats_new.rst
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
Fixes #5907. Currently, I had to set the modifier key to 'v', because 'shift' or 'control' don't work. @larsoner I think I don't even need to manually check for key press and release events as you suggested, because a [`MouseEvent`](https://matplotlib.org/api/backend_bases_api.html#matplotlib.backend_bases.MouseEvent) also has a `key` attribute (seems to be new).
WDYT? Do you have any idea why it doesn't work with shift? Also, I really would like to have the snapping behavior mapped to the modifier (I received some feedback from people telling me the snapping is really strange, they just want to create annotations wherever they click - and I agree).
> Modifier key has to be pressed for snapping to annotations

- doc/manual/source_localization/forward.rst
Correction of some spelling mistakes found in forward.rst file ("The forward solution").
Suggestion: It could be useful to add somewhere which constant corresponds to which coordinate frame (or at least the link https://github.com/mne-tools/mne-python/blob/master/mne/io/constants.py ).
> DOC: Spelling mistakes in forward.rst

- doc/manual/preprocessing/ica.rst
None :disappointed: 
Updates the ICA documentation to use RST math mode rather than LaTeX style `$`'s
A really small suggested correction. Thanks for a great library !
> Update ica doc to use RST math mode

- mne/viz/_brain/_brain.py
Fix a bug reported by @larsoner in this [discussion](https://github.com/mne-tools/mne-python/pull/6460#issuecomment-503552094) about the `_Brain` object.
Before:
After:
As a side note, a minor visual artifact may be visible at the first frame.
> MRG, FIX: Fix default camera settings for _Brain object

- mne/channels/montage.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
1 - `RawEDF` is always called with `montage=None`
2 - ensure `self.set_montage(montage)` is called at the end of __init__
> EDF: use set_montage at the end of the __init__

- doc/manual/datasets_index.rst
- doc/whats_new.rst
- ignore_words.txt
- mne/epochs.py
- mne/evoked.py
- mne/filter.py
- mne/io/base.py
- mne/tests/test_docstring_parameters.py
- mne/tests/test_evoked.py
- mne/tests/test_import_nesting.py
Closes #6468.
Took this opportunity to unify `mne.filter.FilterMixin.filter` with `mne.io.BaseRaw.filter` to reduce code dup, too. This led to removing `HilbertMixin`, which was really only created because we couldn't previously put it in `FilterMixin` because the latter was only used for Epochs/Evoked -- in this PR it's also used in BaseRaw, which is nice.
The one method that has not been unified is `raw.resample`, mostly because it does a lot of extra/different stuff because of concatenation and events handling.
Also contains a fix for a spelling error, and a future compatible fix for check for `scipy.fft` module (lands in SciPy `master` very soon) nesting.
> MRG, BUG: Set info["lowpass"] when resampling

- mne/io/cnt/cnt.py
- mne/io/cnt/tests/test_cnt.py
1 - `RawCNT` is always called with `montage=None`
2 - ensure `self.set_montage(montage)` is called at the end of __init__
> cnt: use set_montage at the end of the __init__

- doc/whats_new.rst
- mne/io/base.py
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
- mne/utils/__init__.py
- mne/utils/numerics.py
- mne/utils/tests/test_numerics.py
1 - `RawBrainVision` is always called with `montage=None`
2 - ensure `self.set_montage(montage)` is called at the end of __init__
> brainvision: use set_montage at the end of the __init__

- doc/whats_new.rst
- mne/channels/channels.py
- mne/io/eeglab/eeglab.py
- mne/io/eeglab/tests/test_eeglab.py
1 - `RawEEGLAB` is always called with `montage=None`
2 - ensure `self.set_montage(montage)` is called at the end of __init__
> EEGLAB: use set_montage at the end of the __init__

- doc/whats_new.rst
- mne/channels/channels.py
- mne/io/fieldtrip/tests/helpers.py
- mne/io/reference.py
- mne/io/tests/test_reference.py
Following discussion in #6478 to add ch_type parameter which can specify which data-type to apply the reference to. 
If ch_type is 'auto,' it searches first for eeg, ecog and then seeg channels. Whichever it finds first, it selects that channel type to apply the reference to.
> ENH: Add ecog functionality to set_eeg_reference.

- doc/python_reference.rst
- mne/__init__.py
- mne/io/pick.py
- tutorials/intro/plot_info.py
also exposes `mne.io.pick.channel_type` and `mne.io.pick.channel_indices_by_type` in the main `mne` namespace, adds them to the `python_reference`, and makes minor fixes to their docstrings.
Note: I'm not married to the that namespace location for `channel_type` and `channel_indices_by_type`, I just chose it because that's where most of the other functions in `mne.io.pick` get exposed.
> MRG, DOC: update tutorial for Info object

- mne/viz/_brain/tests/test_brain.py
Fixes a bug introduced in #6475 that is breaking Travis in #6489.
FYI @GuillaumeFavelier in tests we should always use the `testing` dataset and decorate tests that need the testing data with `@testing.requires_testing_data`, see changeset here.
> MRG, BUG: Use testing instead of sample

- mne/channels/montage.py
- mne/io/eeglab/eeglab.py
- mne/io/eeglab/tests/test_eeglab.py
Right now in master, setting the `ch['cal']` when reading eeglab is driven by `montage`.
(either because `read_raw_eeglab(.. , montage=something)` or because the eeglab file has location information.
If none of the two are preset, the calibration is not set to `1e-6`:
```py
[print(ch['ch_name'], ch['kind'], ch['cal']) for ch in info['chs']]
F3 2 (FIFFV_EEG_CH) 1.0
unknown 2 (FIFFV_EEG_CH) 1.0
FPz 2 (FIFFV_EEG_CH) 1.0
```
I'm not sure this is correct, I think eeglab reader should always set the calibration.
Or at least set the calibratoin for EEG channels.
in this PR:
```py
[print(ch['ch_name'], ch['kind'], ch['cal']) for ch in info['chs']]
F3 2 (FIFFV_EEG_CH) 1e-06
unknown 2 (FIFFV_EEG_CH) 1e-06
FPz 2 (FIFFV_EEG_CH) 1e-06
```
ofcourse this breaks the tests.
WDYT @jasmainak?
Shall we adapt …
> FIX: EEGLAB calibration / remove montage

- mne/io/nicolet/nicolet.py
- mne/io/nicolet/tests/test_nicolet.py
1 - RawNicolet is always called with montage=None
2 - ensure self.set_montage(montage) is called at the end of init
> NICOLET: use set_montage at the end of the __init__

- mne/datasets/utils.py
- bumped the testing data releases version to '0.67'
- set the new hash according to `$ md5sum mne-testing-data-0.67.tar.gz`
> Set new version and hash for mne-testing-data

- doc/whats_new.rst
- mne/evoked.py
- mne/tests/test_evoked.py
`Evoked.decimate()` fails to update the `.first` and `.last` attributes. I stumbled across the error when trying to save and then load a decimated `Evoked` object. This PR fixes it and extends the unit test to check these things.
> FIX: `Evoked.decimate` is not updating `.first` and `.last`

- mne/viz/tests/test_3d.py
Following @agramfort [advice(comment)](https://github.com/mne-tools/mne-python/pull/6505#issuecomment-506404576), this PR adds simple testing of the '3d' `mode` (`sphere` or `arrow`) of the `plot_dipole_locations()` function.
> MRG: Add a test for 3d mode of plot_dipole_locations

- doc/whats_new.rst
- mne/epochs.py
- mne/tests/test_epochs.py
In the light of https://github.com/mne-tools/mne-python/pull/6291 which enabled to read `mne.io.fiff.raw.Raw` FIF object from file-like object, the hereby PR aims at extending this feature to `mne.epochs.EpochsFIF` object (cf. issue https://github.com/mne-tools/mne-python/issues/6009).
> ENH: Allow reading file-like objects for EpochsFIF

- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
- tutorials/source-modeling/plot_dipole_orientations.py
This PR is a follow-up of [#6483(comment)](https://github.com/mne-tools/mne-python/pull/6483#issuecomment-505806289). It introduces a new parameter `fwd` for `plot_alignment()` allowing the plotting of the dipole orientations. The script `plot_dipole_orientations.py` is slightly different now.
This is what I obtain locally:
Compared to initially:
*The rendering may differ on Circle, I have some transparency issues to fix on my personal mayavi config.*
> MRG: Refactor last mlab out of tutorial

- mne/io/egi/egi.py
- mne/io/egi/egimff.py
- mne/io/egi/tests/test_egi.py
let me know what you think @massich 
feel free to take over.
once you remove the last call to _check_update_montage
please remove this function from the code base.
> use set_montage for mff and egi

- examples/inverse/plot_read_inverse.py
This PR improves the focus of the camera of the `plot_read_inverse-py` example.
Before:
After:
> Improve camera focus of plot_read_inverse

- mne/viz/_3d.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/_utils.py
- mne/viz/backends/base_renderer.py
- mne/viz/backends/tests/test_renderer.py
Fixes part of #6518.
This PR adds the missing `tube()` function to the pyvista 3d backend and updates the tests accordingly.
> Add tube() to pyvista 3d backend

- doc/install/pre_install.rst
per discussion on MNE_Analysis email list, this adds a list of "side-packages" to the installation docs.
> DOC: add list of side-packages

- mne/viz/_3d.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/base_renderer.py
- mne/viz/backends/tests/test_renderer.py
Fixes part of #6518.
This PR adds the missing `scalarbar()` function to the pyvista 3d backend.
> MRG: Add scalarbar() and text3d() to pyvista 3d backend

- mne/io/eeglab/tests/test_eeglab.py
We run some non-parametrized code several times just because the code
is inside a parametrized test
> MNT: Avoid non-parametrized testing inside parametrized test

- mne/beamformer/tests/test_lcmv.py
- mne/connectivity/tests/test_spectral.py
- mne/decoding/tests/test_transformer.py
- mne/epochs.py
- mne/filter.py
- mne/fixes.py
- mne/inverse_sparse/tests/test_mxne_inverse.py
- mne/io/edf/edf.py
- mne/simulation/evoked.py
- mne/simulation/raw.py
- mne/simulation/source.py
- mne/simulation/tests/test_evoked.py
- mne/simulation/tests/test_raw.py
- mne/simulation/tests/test_source.py
- mne/source_estimate.py
- mne/stats/cluster_level.py
- mne/stats/tests/test_cluster_level.py
- mne/stats/tests/test_permutations.py
- mne/tests/test_epochs.py
- mne/tests/test_filter.py
- mne/tests/test_source_estimate.py
- mne/time_frequency/csd.py
- mne/time_frequency/stft.py
- mne/time_frequency/tests/test_psd.py
- mne/time_frequency/tfr.py
- mne/utils/check.py
- mne/utils/numerics.py
- mne/utils/tests/test_check.py
- tutorials/discussions/plot_background_filtering.py
joblib and SciPy's FFT do not get along:
https://github.com/joblib/joblib/issues/906
For now set `n_jobs=1` in the tests to make things green again, and make our dtype check a bit stricter/consistent (only allow np.float64 in resampling and filtering). Once joblib or SciPy are fixed we can put `n_jobs=2` in a test somewhere.
> MRG, ENH: Add real datatype check, avoid joblib for now

- doc/whats_new.rst
- mne/simulation/source.py
- mne/simulation/tests/test_source.py
To simulate an stc from label the function `estimate_stc` uses the intersection between label vertices and source space. However, if label contains only one or few vertices (for example only the center of mass of a region) the intersection can be empty. This possibility is not currently taken into account which may result in  outputting empty stcs.
I added the code which returns a source even if the intersection is empty. For a moment I just select the source from source space whose index is the nearest (from right) to the label vertices.
> [MRG+1]fix bug in estimate_stc

- doc/whats_new.rst
- mne/evoked.py
- mne/tests/test_evoked.py
Per offline discussion w/ @agramfort @larsoner @jasmainak and @jona-sassenhagen. Needs input:
- here when `weights='equal'` the weights are all `1` (previously `1/N`). `combine_tfr` still uses the `1/N` convention; should it be changed too? `mne.grand_average` uses both `combine_evoked` and `combine_tfr` internally, so it might be good if they worked the same way? 
- Regardless of whether we change the behavior of `combine_tfr`, the new behavior of `combine_evoked(..., weights='equal')` is not really consistent with the intuitive meaning of "grand average" (it's really a "grand sum" now). Should `mne.grand_average` be changed to effectively undo this change to `combine_evoked` (by passing pre-computed weights, or by dividing the data afterwards)?
> MRG, FIX: make combine_evoked consistent with Matti's manual

- mne/io/artemis123/artemis123.py
- mne/io/brainvision/brainvision.py
- mne/io/bti/bti.py
- mne/io/cnt/cnt.py
- mne/io/ctf/ctf.py
- mne/io/edf/edf.py
- mne/io/eeglab/eeglab.py
- mne/io/egi/egi.py
- mne/io/egi/egimff.py
- mne/io/eximia/eximia.py
- mne/io/fiff/raw.py
- mne/io/kit/kit.py
- mne/io/nicolet/nicolet.py
- mne/utils/docs.py
As mentioned in PR #6272,
This PR will change the "preload" documentation in all relevant io read_raw_xy and RawXY docstrings to be read from utils/docs.py::docdict instead of being written out each time.
The following "preload" docstrings were not replaced for various reasons. Please give a short note whether any of them should be replaced additionally:
- (array, fieldtrip): No preload option
- brainvision: String not equal/ not sure if equivalent
`preload : bool
If True, all data are loaded at initialization.
If False, data are not read until save.`
- eximia: String not equal/ not sure if equivalent
`preload : bool
If True, all data are loaded at initialization.`
- eeglab::read_raw_eeglab: Additional information after preload string:
`[...]Note that preload=False will be effective only …
> replaced preload in IO

- CONTRIBUTING.rst
The link to our contributing guide in `CONTRIBUTING.rst` doesn't work anymore. I've changed it to https://mne-tools.github.io/stable/install/contributing.html, but this link will not work until we release 0.19 (https://mne-tools.github.io/dev/install/contributing.html does work now).
> Update link to contributing guide

- mne/viz/epochs.py
- mne/viz/raw.py
`raw.plot` already shows the name in the window title, so I think `epochs.plot` should be consistent. This PR moves the name from the axis to the window title.
Before:
After:
> [MRG] Show epoch name in window title instead of axis

- doc/whats_new.rst
- mne/io/cnt/_utils.py
- mne/io/cnt/cnt.py
> FIX: reading large CNT files (more than 2Gb files)

- mne/preprocessing/ecg.py
- mne/preprocessing/eog.py
closes #6562 
I ended up taking a middle-road approach: hardcoding `verbose=False` where the user has no control over filter params, but leaving things as-is for filters where the params are passed through from the calling function. Now a call to `create_ecg_epochs` will spit out only one set of filter params instead of two (yes for the initial filtering step, but not for the call to `qrs_detector`). Passing `verbose=False` to `create_ecg_epochs` will of course suppress both filter param messages (as well as all the other ones like "reconstructing ECG from gradiometers" etc). 
Similar changes were made for EOG (only show filter param messages for the filters that users can control).
> suppress filter param messages when not user-specifiable

- mne/tests/test_filter.py
Isolates and restores the test that was failing in #6536, which should succeed now that SciPy's bug has been fixed and (presumably) the prerelease wheel updated.
> MRG, MAINT: Restore n_jobs test

- mne/viz/tests/test_3d.py
Fixes #6566 by marking `test_plot_alignment()` as `slowtest`.
> FIX: Mark test_plot_alignment as slowtest

- mne/commands/utils.py
I expose the `prog_prefix` and `version` parameters for `get_optparser`. I need this for mne-bids: https://github.com/mne-tools/mne-bids/pull/225
it does not affect MNE-Python beyond making it more versatile / ready to use in other packages and modules.
Example:
in mne-bids I can now call:
```Python
from mne.commands.utils import get_optparser
import mne_bids
v = mne_bids.__version__
parser = get_optparser(__file__, usage=None, prog_prefix='mne_bids', version=v):
```
which will give me a parser that is aware of mne_bids' version and use the correct "prog" param (instead of `mne.__version__` as version and `mne` as prog_prefix)
For MNE-Python, nothing will change
> make mne's optParser more adaptable

- doc/whats_new.rst
- mne/io/brainvision/brainvision.py
Reference, [mailling list issue](https://mail.nmr.mgh.harvard.edu/pipermail//mne_analysis/2019-July/005992.html)
The regexp for BrainVision did not catch negative numbers in the slot that is responsible for telling us to which channels an event refers to.
see the regexp example: https://regex101.com/r/sDiTVs/2
the string to match is taken from the Demo files as shared in the mailing thread. The regexp is taken from here: https://github.com/mne-tools/mne-python/blob/7d27ad33bdfaa59465e45c620c8bb864adc7375f/mne/io/brainvision/brainvision.py#L466
This fix will repair this behavior. Although it is unclear, why in the BrainVision files there was a negative number. The numbers in that slot should be positive integers (=channel indices) ... or 0 (=event relates to ALL channels) --> what could a …
> FIX: match date_str in vmrk also when chn ref is negative

- doc/whats_new.rst
- mne/viz/_3d.py
Allows control over the dipole and highlight colors by actually passing `color` when in `orthoview` mode so you can do things like this (normally would be yellow spheres with red lines):
In theory you can control the `highlight_color` by tinkering with `ax.findobj` but it's kind of a pain to do so (multiple types of objects, etc.), so I allowed setting that, too.
> MRG, ENH: Pass colors to orthoview dipole loc plotter

- mne/defaults.py
- mne/io/pick.py
- mne/viz/tests/test_epochs.py
With an update to MNE 18, epochs plotting for ctf data (with ref channels) was failing.
I assume this was introduced in #6210 or #6320.
This PR at least gets through plotting and adds tests. Although I don't know if there was another plan for ref channels. @stfnrpplngr and @larsoner please let me know what you think.
Additional issues,
picks option is ignored (at least on butterfly plots)
ica.plot_sources(epochs) doesn't have a scaling option and the default scaling is too small, at least using my datasets.
> [MRG][FIX] fix epochs.plot for ctf data

- mne/viz/ica.py
Before this PR:
After this PR:
> fix ICA.plot_scores() barplot xlims

- doc/manual/datasets_index.rst
- mne/datasets/__init__.py
- tutorials/intro/plot_10_overview.py
- tutorials/raw/plot_10_raw_overview.py
Main motivation for these changes is that when the docstring link in `mne.datasets.__init__.py` gets rendered by autodoc in `doc/python_reference.rst`, it ends up making a self-referential link.  Now it is a link to a different, more useful page (the datasets overview page). Also:
- changes a couple crossrefs targeting `datasets_index.rst` from `:doc:` to `:ref:` style
- updates the `datasets_index.rst` page title
- moves the sidebar in `datasets_index.rst` so it doesn't crash with the TOC
> DOC: better dataset crossrefs; move sidebar; better dataset page title

- Makefile
- doc/conftest.py
We moved `conftest.py` into `mne` which is nice, but it made it so that it was not used in `doctests` because this is called with a variant of `pytest doc/`. This fixes it by writing a little wrapper within `doc/`.
> BUG: Restore conftest to doctests

- doc/whats_new.rst
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
- mne/transforms.py
This is related to my search of:
- what the magical factor of "85" means in the [montage reading code](https://github.com/mne-tools/mne-python/blob/d75bce15717ee4cbf2abbdb5c6e5148959000a91/mne/channels/montage.py#L331)
- what the difference between "BVCT" and "BVEF" files is
- related to #6402, where @alexrockhill wants to introduce BVCT files
Long story short:
- **BVCT** = BrainVision CapTrack ... a digitization device: We get xyz coords in mm for the coordsystem bounded between LPA, RPA, and Nasion
- this can be used as a proper DigMontage
- **BVEF** = BrainVision Electrode File ... the format that Brain Products uses in their "BrainVision Analyzer" software ... coords in mm for coordsystem between T7 and T8, Oz and Fpz, and that plane and Cz (see pics below)
- this is **usually** based …
> doc magical 85 factor (=radius of head in mm), improve bvef handling

- .coveragerc
- mne/beamformer/_compute_beamformer.py
- mne/beamformer/_lcmv.py
- mne/chpi.py
- mne/cov.py
- mne/dipole.py
- mne/fixes.py
- mne/forward/_compute_forward.py
- mne/forward/forward.py
- mne/inverse_sparse/mxne_optim.py
- mne/io/pick.py
- mne/minimum_norm/_eloreta.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
- mne/surface.py
- mne/utils/__init__.py
- mne/utils/_logging.py
- mne/utils/linalg.py
- mne/utils/numerics.py
In profiling, a full 1/3 of the time in `linalg.svd` is spent in `_compute_lwork`, which is wasteful if we are going to do `svd` on data that is always the same shape (or at most some shape).
So far I've sped up HPI coil fitting a bit using this technique. I plan to try it with LCMV, too, since there are a bunch of pseudo-inverses done there with `pinv2` (which internally calls `svd`). I'll probably refactor into our own `_repeated_svd` for this purpose.
It also speeds things up by using `gemm`, `gemv`, and `dot` directly rather than calling `np.dot` and dealing with the overhead, similar to #6220.
> MRG, ENH: Optimize using low-level BLAS/LAPACK

- doc/whats_new.rst
- mne/report.py
- mne/tests/test_report.py
You can open HTML reports with a context manager, e.g.:
```python
with mne.open_report('report.h5') as report:
```
When I implemented this, in my ignorance about how to properly implement context managers, I made `mne.Report.__exit__` return `self`. Returning truthy values causes the context manager to suppress all exceptions within the context block! `mne.Report.__exit__` should not return anything.
> [FIX] Make report context manager stop swallowing exceptions

- doc/whats_new.rst
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
Fixes an issue with the way `date_str` was handled.
Sometimes it could be `None`, but we would rather have it a string always ... and if undefined, let it be one of `['', '0', '00000000000000000000']`
While fixing this, I also noticed that we are not strict enough with checking what we read in as a recording date - So this is a preemptive bugfix as well:
- before reading a recording time, we make sure that it is present at all (the `len==5` on line 212)
> [MRG] FIX: always handle BrainVision recording date as string

- doc/whats_new.rst
- mne/io/edf/edf.py
- mne/io/edf/tests/test_gdf.py
Fix #6601.
This makes two things:
- The 'Unknown' description is replaced by 'Undefined(number)' where number is the number in the gdf event table. This avoids collapsing all 'Unknown' events under the same tag and allows to keep event identity.
- The global variable  GDF_EVENTS_LUT becomes a RawGDF static member. This at least allows the user to add its own events to the table before reading a file.
Example:
mne.io.edf.edf.RawGDF.GDF_EVENTS_LUT[198] = 'Non Target'
mne.io.edf.edf.RawGDF.GDF_EVENTS_LUT[190] = 'Target'
signal = mne.io.read_raw_edf('datafile.gdf',preload=True)
vents = mne.events_from_annotations(signal)
Used Annotations descriptions: ['Non Target', 'Target', 'Undefined(0)', 'Undefined(181)', 'Undefined(182)', 'Undefined(183)', 'Undefined(184)', 'Undefined(187)', …
> ENH: make GDF unknown events codes visible

- mne/minimum_norm/inverse.py
Small docu update regarding `apply_inverse`'s behavior when using `pick_ori=None` in conjunction with a fixed source space.
> [DOC] apply_inverse docu update

- .gitignore
- README.rst
- doc/conf.py
- doc/install/mne_python.rst
- doc/whats_new.rst
- environment.yml
- mne/fixes.py
- mne/forward/_compute_forward.py
- mne/surface.py
- mne/tests/test_surface.py
- mne/utils/config.py
- requirements.txt
Speed up morph map generation ~~4x~~ ~10x using `numba` and changes to `_compute_nearest` calls. This code:
```
import time
import mne
subjects_dir = mne.datasets.sample.data_path() + '/subjects'
mne.surface._make_morph_map('sample', 'fsaverage', xhemi=False,
subjects_dir=subjects_dir)
```
- On `master` takes ~18 sec
- After refactoring to be a tiny bit faster takes 17 sec (what people will get without `numba` installed)
- On first run with numba takes ~~6~~ ~5 sec (includes compilation time)
- On subsequent runs takes ~~2.5~~ ~1.7 sec (no longer needs to compile)
> MRG, ENH: Speed up morph map creation

- examples/connectivity/plot_mixed_source_space_connectivity.py
- mne/forward/_compute_forward.py
- mne/minimum_norm/inverse.py
- tutorials/preprocessing/plot_10_preprocessing_overview.py
Should fix failures on CircleCI due to memory by bringing them < 1.5GB:
1. https://circleci.com/gh/mne-tools/mne-python/14549
`master`:
PR: 
2. https://circleci.com/gh/mne-tools/mne-python/14556
`master`
PR:
Changes in forward looping logic didn't seem to have much effect on speed, but did improve memory quite a bit.
> MAINT: Reduce memory usage in examples

- doc/_static/reset-syntax.css
Fixes the bug with background overlapping pointed out in https://github.com/mne-tools/mne-python/pull/6596#issuecomment-518530219
@drammock feel free to merge if you're happy. Feel free to try it / cherry-pick it on top of your commit 945ec94 if you want to see if it fixes things
> MRG, BUG: Fix CSS backgrounds for sidebars [skip travis] [skip azp]

- doc/python_reference.rst
- examples/time_frequency/plot_time_frequency_global_field_power.py
- mne/stats/__init__.py
- mne/stats/permutations.py
- mne/stats/tests/test_permutations.py
fixes https://github.com/mne-tools/mne-python/pull/6414#issuecomment-517267800
Earlier it came up that we are using a private function in our [example](https://mne.tools/dev/auto_examples/time_frequency/plot_time_frequency_global_field_power.html?highlight=global%20field%20power), look for `_bootstrap_ci`
The idea was to make it public (and potentially wrap it).
> make bootstrap ci public

- doc/conf.py
This enables a recent sphinx-gallery feature that suppresses the `sphinx_gallery_thumbnail_number` comments in the rendered tutorials.
> suppress sphinx-gallery thumbnail comments in output

- doc/whats_new.rst
- mne/beamformer/tests/test_dics.py
- mne/beamformer/tests/test_lcmv.py
- mne/decoding/tests/test_transformer.py
- mne/epochs.py
- mne/io/tests/test_compensator.py
- mne/io/tests/test_meas_info.py
- mne/minimum_norm/time_frequency.py
- mne/tests/test_epochs.py
Closes #6616
Raise an exception when using the default value of `baseline=(None, 0)` with `tmin=0` in `Epochs`. The result would be one-sample baseline which is not desired in most cases. One should use `baseline=(0, 0)` if this is desired.
> FIX: Raise exception for default value of baseline and `tmin=0` in `Epochs`

- mne/utils/mixin.py
fixes https://github.com/mne-tools/mne-study-template/pull/40#issuecomment-518913104
cc @jasmainak 
New error message:
```Python
444     return use_keys
KeyError: 'Event "asd" is not in Epochs. Event_ids must be one of "button, deviant, standard"'
```
> ENH: improve error msg if key error in epochs[key]

- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
fixes https://github.com/mne-tools/mne-study-template/pull/41#issuecomment-518920458
cc @jasmainak 
Previous error triggered in `np.hstack`:
```
ValueError: need at least one array to concatenate
```
New error message triggered earlier, in `_fit_epochs`:
```
RuntimeError: Tried to fit ICA with epochs, but none were found: epochs.events is "[]".
```
> ENH: improve error message when trying to fit an ICA on empty epochs

- mne/morph.py
I think `dipy.imaffine.transform_centers_of_mass` last param requires the `mri_from_affine` not the `mri_to_affine`, here simply called `affine` .
@agramfort
> FIX: morph volumetric

- mne/minimum_norm/_eloreta.py
- mne/utils/linalg.py
While playing with numba I found a few ways to speed up the eLORETA computations 10-20%.
> MRG, ENH: Speed up eLORETA

- .coveragerc
- mne/fixes.py
- mne/stats/cluster_level.py
- mne/stats/tests/test_cluster_level.py
- mne/surface.py
- tutorials/stats-sensor-space/plot_stats_cluster_1samp_test_time_frequency.py
- tutorials/stats-sensor-space/plot_stats_cluster_erp.py
- tutorials/stats-sensor-space/plot_stats_cluster_time_frequency.py
- tutorials/stats-sensor-space/plot_stats_spatio_temporal_cluster_sensors.py
- tutorials/stats-source-space/plot_stats_cluster_spatio_temporal.py
- tutorials/stats-source-space/plot_stats_cluster_spatio_temporal_2samp.py
- tutorials/stats-source-space/plot_stats_cluster_spatio_temporal_repeated_measures_anova.py
- tutorials/stats-source-space/plot_stats_cluster_time_frequency_repeated_measures_anova.py
This code snippet:
```
import time
import mne
src_fname = (mne.datasets.sample.data_path() +
'/subjects/fsaverage/bem/fsaverage-ico-5-src.fif')
X = np.random.RandomState(0).randn(8, 5, 20484) * 0.1
src = mne.read_source_spaces(src_fname)
connectivity = mne.spatial_src_connectivity(src)
mne.stats.spatio_temporal_cluster_1samp_test(
X, connectivity=connectivity, n_jobs=1, buffer_size=None, verbose=True,
max_step=1)
```
on `master` takes 16.7 sec, on this PR it takes 4.5 sec.
Changing `max_step=2` then on `master` it takes 23.1 sec, on this PR it takes 6.1 sec.
So `numba` gets us a ~4x speedup in time-consuming code. ~~I don't love the code dup, but both paths should be tested for correctness by Travis.~~ On systems with numba, both …
> MRG, ENH: Speed up clustering using numba

- doc/whats_new.rst
- mne/bem.py
- mne/commands/mne_coreg.py
- mne/commands/mne_report.py
- mne/commands/mne_watershed_bem.py
closes #6667
This PR for `mne watershed_bem`:
1. Adds control over the `-T1` option (which was otherwise always tied to our `--gcaatlas` option)
2. Adds control over where the brainmasked output ends up.
3. Allows passing `-v orig.mgz` instead of just `-v orig` (be more lenient)
4. Works with newer Freesurfer (the `gcaatlas` option assumed that a file from an older FS version was there, this finds whichever is newest even though there will probably only ever be one)
This is because for some subjects I've wanted to do:
```
mri_watershed -useSRAS -brain_atlas $FREESURFER_HOME/average/RB_all_withskull_2016-05-10.vc700.gca transforms/talairach_with_skull.lta -surf ../bem/watershed/SUBJECT -h 39 orig.mgz brainmask.mgz
```
In MNE we can just do now:
```
mne watershed_bem -s SUBJECT -v orig.mgz …
```
> MRG, ENH: Add options to mne watershed_bem

- doc/whats_new.rst
- mne/coreg.py
- mne/tests/test_coreg.py
I am working with some subjects (infants) for which surface reconstructions are not very well defined and volumetric analyses are done. Basically `recon-all -autorecon1` is done (one step at a time with manual intervention to fix the transformations), then volumetric analysis can be carried out as usual. But `mne coreg` in `master` has some checks during surrogate scaling that prevent this
It turns out the only surface files that were actually being checked were the `lh.curv`/`rh.curv` ones (since all others were only added to the list if they existed), which wasn't very useful anyway. So that has been eliminated.
> MRG, ENH: Add support for scaling volumetric subjects

- .circleci/artifact_path
- .circleci/config.yml
Should enable a [little GitHub app](https://github.com/apps/circleci-artifacts-redirector) that [I made](https://github.com/larsoner/circleci-artifacts-redirector) to give a quicker link to the built docs.
> MRG, ENH: Add CircleCI redirection

- mne/viz/utils.py
Fixes #6637. The following example correctly produces the PSD for all channels supplied in `picks`:
```
import mne
raw_fname = data_path + '/MEG/sample/sample_audvis_raw.fif'
raw = mne.io.read_raw_fif(raw_fname, preload=True)
raw.drop_channels(raw.info["ch_names"][:315])
raw.drop_channels(raw.info["ch_names"][4:])
raw.info["bads"] = ['EEG 003', 'EEG 004']
raw.plot_psd(spatial_colors=False, picks=range(4))  # plot all 4 channels
```
The default behavior is still to exclude bad channels, that is
```
raw.plot_psd(spatial_colors=False)
raw.plot_psd(spatial_colors=False, picks="all")
````
generate PSDs only for the 2 good channels just like before.
However, I don't know what's the deal with `spatial_colors=True`, which only plots 3 …
> [MRG] Do not exclude bads if channel indices are supplied

- bin/mne
- doc/install/contributing.rst
- mne/__main__.py
- mne/commands/mne_browse_raw.py
- mne/commands/mne_bti2fiff.py
- mne/commands/mne_clean_eog_ecg.py
- mne/commands/mne_compare_fiff.py
- mne/commands/mne_compute_proj_ecg.py
- mne/commands/mne_coreg.py
- mne/commands/mne_flash_bem.py
- mne/commands/mne_freeview_bem_surfaces.py
- mne/commands/mne_kit2fiff.py
- mne/commands/mne_make_scalp_surfaces.py
- mne/commands/mne_maxfilter.py
- mne/commands/mne_report.py
- mne/commands/mne_show_fiff.py
- mne/commands/mne_show_info.py
- mne/commands/mne_surf2bem.py
- mne/commands/mne_watershed_bem.py
- mne/commands/utils.py
- mne/utils/__init__.py
- mne/utils/_testing.py
I wanted to be able to debug after a `mne` command failed, such as:
```
mne watershed_bem -o -s fsaverage --verbose
```
This PR enables `python -m mne ...` to do the same things as `mne ...`. For example I can do (to debug after running):
```
python -uim mne watershed_bem -o -s fsaverage --verbose
```
The key is the addition of the `mne/__main__.py` file, the rest is cleanups and unifications related to that.
> MRG, ENH: Make `mne` runnable

- mne/report.py
uses `os.getcwd()` instead of `os.path.dirname(__file__)` as the default directory for reports. This brings behavior in line with what the docs say will happen.
> BUG: Fix mne.Report default directory

- mne/bem.py
- mne/conftest.py
- mne/fixes.py
- mne/forward/forward.py
- mne/forward/tests/test_forward.py
- mne/forward/tests/test_make_forward.py
- mne/io/base.py
- mne/io/fiff/raw.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/write.py
- mne/minimum_norm/tests/test_inverse.py
- mne/source_estimate.py
- mne/source_space.py
- mne/surface.py
- mne/tests/test_bem.py
- mne/tests/test_cov.py
- mne/tests/test_source_estimate.py
- mne/tests/test_source_space.py
- mne/tests/test_surface.py
- mne/utils/check.py
- mne/utils/misc.py
- mne/utils/tests/test_check.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
Closes #6699.
- Unifies `preload`-as-`str` handling in `io/base.py`
- Adds `path-like` to `_validate_types`
- Makes `_validate_types` support nested `str` options (e.g. `(None, 'path-like')`)
- Modernizes a number of `tmpdir` uses (@massich you should be happy :) )
> MRG, ENH: Support path-like objects

- doc/changes/latest.inc
- mne/source_space.py
Closes #5123.
This was a fun one! @agramfort your original example with `pos=2.` is a bit crazy, it creates 342079. So I tested it with `pos=5.`, which took 36 sec on master:
<details>
```
import time
from mne import setup_volume_source_space
data_dir = op.join(data_path, 'MEG', subject)
bem_dir = op.join(subjects_dir, subject, 'bem')
fname_aseg = op.join(subjects_dir, subject, 'mri', 'aseg.mgz')
fname_model = op.join(bem_dir, '%s-5120-bem.fif' % subject)
labels_vol = ['Left-Hippocampus',
'Right-Hippocampus']
def test():
hippocampus = setup_volume_source_space(
subject,
mri=fname_aseg,
pos=5.0,
bem=fname_model, …
```
> MRG, ENH: Speed up src filtering and vol label src creation

- mne/viz/epochs.py
- mne/viz/ica.py
- mne/viz/raw.py
- mne/viz/utils.py
- tutorials/preprocessing/plot_15_handling_bad_channels.py
> MRG, ENH: make subplots_adjust work with {raw,epochs}.plot() and ica.plot_sources()

- tutorials/preprocessing/plot_55_setting_eeg_reference.py
This is ready for review but should probably wait until a solution to #6647 is merged in.
> MRG, DOC: add EEG referencing tutorial

- mne/source_space.py
- mne/transforms.py
- mne/utils/__init__.py
- mne/utils/check.py
- mne/utils/tests/test_check.py
Completes #6699, #6701.
`mne.make_forward_solution()` now also accepts `path-like` objects for the `trans` and `src` parameters. This was the last function in my workflow (#6699) that hadn't been fixed via #6701.
- <strike>I introduced the local variable `path_like` to help keep the new `try ... except` blocks as small as possible.
- This PR currently doesn't add any additional tests. I'm not sure if that would be necessary – and how exactly to design them. If you would prefer to have tests, I'd appreciate advice.</strike >
- Also, not sure if I should add a `whats_new` entry,  as this PR more or less just complements #6701.
cc @larsoner
> ENH: Support path-like objects in mne.make_forward_solution()

- doc/changes/latest.inc
- mne/epochs.py
- mne/tests/test_epochs.py
> [MRG] Handle events with non-unique event time samples

- mne/viz/topomap.py
Tiny change to add labels to each ICA corrmap match (so it's easier to tell which subject(s) had no match or multiple matches)
Before this PR:
After this PR:
> MRG, VIZ: add titles to corrmap matches

- doc/conf.py
- doc/manual/c_reference.rst
- doc/manual/source_localization/morph_stc.rst
Fixes broken links exposed by https://circleci.com/gh/mne-tools/mne-python/15052
Got rid of three links to http://www.sourcesignal.com/formats_probe.html because it has been removed, I couldn't find the new version, and it didn't seem totally necessary.
> MRG, FIX: Fix doc links

- mne/viz/ica.py
Fixes #6718. In addition to bringing back the yticks and labels, I've removed the space before the colon in the title, and " (index)" from the x axis label (because "segment" is sufficient).
Here's what it looks like after the changes:
I'd also like to change the horizontal position of the y axis label for the ERP/ERF - the "AU" label is too far to the left and should be closer to the actual axis. Anyone know how to do that quickly? Otherwise, this is ready to merge.
> [MRG] Bring back yticks for ICA properties

- mne/parallel.py
Closes #6284.
@jhouck can you see if it fixes your problem? Based on your problem description, in theory this code snippet should trigger the problem, but it didn't for me on 64-bit Linux so it's probably OS/sys dependent:
```
import time
import mne
src_fname = (mne.datasets.sample.data_path() +
'/subjects/fsaverage/bem/fsaverage-ico-5-src.fif')
X = np.random.RandomState(0).randn(33, 545, 20484) * 0.1
src = mne.read_source_spaces(src_fname)
connectivity = mne.spatial_src_connectivity(src)
mne.stats.spatio_temporal_cluster_1samp_test(
X, connectivity=connectivity, n_jobs=2, buffer_size=None, verbose=True,
max_step=1)
```
> MRG, DOC: Document failure mode better

- doc/changes/latest.inc
- mne/dipole.py
- mne/gui/_coreg_gui.py
- mne/gui/_viewer.py
- mne/simulation/raw.py
- mne/source_space.py
- mne/surface.py
I realized that the slow parts of `mne coreg` are:
1. Nearest-neighbor computations. This is now sped up by doing all computations in the MRI coordinate frame. This is much faster because the distance tree (KDTree, BallTree) only needs to be built once per subject (unless MRI scaling is used), rather than every time the `head_mri_t` changes.
2. Inside-the-surface computations. Recently calculations for `setup_source_space` were sped up by using a sphere + Delaunay computation to only check questionable points. This PR changes that to be a class (since it really has a "state", which is the surface being checked against) named `_CheckInside`, and uses it in `source_space.py` and the GUI code.
Along the way I also moved the `_points_outside_surface` helper from `source_space.py` to …
> MRG, ENH: Speed up mne coreg

- doc/changes/latest.inc
- mne/commands/mne_browse_raw.py
- mne/io/base.py
- mne/transforms.py
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
Use more stable high-order filtering in `raw.plot`, and add `--verbose` option to `mne browse_raw` so that this command works (and reports filter info):
```
mne browse_raw clouds_2ae/raw_fif/clouds_2ae_01_raw.fif --allowmaxshield --lowpass 30 --highpass 1 --filtorder 8 --verbose
...
Setting up band-pass filter from 1 - 30 Hz
IIR filter parameters
---------------------
Butterworth bandpass zero-phase (two-pass forward and reverse) non-causal filter:
- Filter order 32 (effective, after forward-backward)
- Cutoffs at 1.00, 30.00 Hz: -6.02, -6.02 dB
```
(yes I know this filter is a bit crazy, but it still should not break things)
> MRG, ENH: Use sosfiltfilt in raw plotting

- mne/viz/epochs.py
This forces `epochs.plot_image` to always return the list of figures in a deterministic order.
(discussed on Gitter a few weeks ago, w/ @agramfort giving the go-ahead)
> MRG: impose deterministic order of epochs image plots

- doc/changes/latest.inc
- doc/python_reference.rst
- mne/conftest.py
- mne/coreg.py
- mne/datasets/utils.py
- mne/gui/_fiducials_gui.py
- mne/gui/_file_traits.py
- mne/gui/tests/test_coreg_gui.py
- mne/gui/tests/test_fiducials_gui.py
- mne/io/tests/test_what.py
- mne/io/what.py
- mne/tests/test_coreg.py
Taking over parts of #6693.
Todo:
On `master`:
```
mne coreg -d ~/mne_data/MNE-sample-data/subjects -s sample -f ~/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw.fif
```
Produces:
On this PR:
cc @jhouck
> MRG, ENH: MNI Fiducials in `mne coreg`

- doc/changes/0.15.inc
- mne/simulation/evoked.py
- mne/utils/docs.py
> MAINT: Update link to RandomState

- doc/install/advanced.rst
- doc/install/contributing.rst
- brings docs in line with new practice of installing into `base`
- makes contributor docs more explicit about creating new env first when setting up dev environment
> DOC: better explanations of conda env names in install docs

- doc/install/contributing.rst
Follow-up to #6747 which had a missing colon (causing failed console formatting) and a paragraph that I missed editing.
> DOC: lingering conda env name fixes

- .travis.yml
- Makefile
- setup.py
On `master` I see this warning:
```
warning: Check: This command has been deprecated. Use `twine check` instead: https://packaging.python.org/guides/making-a-pypi-friendly-readme#validating-restructuredtext-markup
```
Following their advice we now build the `dist/` and check it, eventually seeing:
```
twine check dist/*
Checking distribution dist/mne-0.19.dev0-py3-none-any.whl: Passed
Checking distribution dist/mne-0.19.dev0.tar.gz: Passed
```
> MAINT: Update README check

- doc/changes/latest.inc
- doc/python_reference.rst
- examples/visualization/plot_montage.py
- mne/_digitization/_utils.py
- mne/channels/__init__.py
- mne/channels/_dig_montage_utils.py
- mne/channels/_standard_montage_utils.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/channels/tests/test_standard_montage.py
- mne/viz/_3d.py
This works on #6461, It finds a way to create DigMontages from standard montage kind.
```py
def read_standard_montage(kind: str) -> DigMontage
```
This could either be a new `read_standard_montage` or reuse `read_montage`.
> MRG+1, ENH: Allow creating DigMontage for standard montages

- doc/changes/latest.inc
- doc/conf.py
- examples/inverse/plot_lcmv_beamformer_volume.py
- mne/conftest.py
- mne/fixes.py
- mne/morph.py
- mne/source_estimate.py
- mne/source_space.py
- mne/tests/test_morph.py
- mne/tests/test_source_estimate.py
- mne/transforms.py
- mne/utils/__init__.py
- mne/utils/_logging.py
- mne/utils/check.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
When using `VolSourceEstimate.plot()` I found myself wanting a way to specify the initial time and initial position. This PR thus:
My particular use case involved replicating a figure someone sent me with `initial_time=0.2` and `initial_pos=(-0.04, -0.034, -0.002)` and now I can script it to give:
Not ready for merge because there is some bug with indexing the morphed STC.
> MRG: Add initial arguments to vol viz

- doc/changes/latest.inc
- doc/python_reference.rst
- mne/cuda.py
- mne/utils/config.py
Allows the following
```console
(mnedev) drmccloy@colchuck:/opt/mne-python$ git checkout -b expose-cupy-device drammock/expose-cupy-device 
Branch 'expose-cupy-device' set up to track remote branch 'expose-cupy-device' from 'drammock'.
Switched to a new branch 'expose-cupy-device'
(mnedev) drmccloy@colchuck:/opt/mne-python$ python -c "import mne; mne.cuda.init_cuda(verbose=True)"
Now using CUDA device 0
Enabling CUDA with 1.79 GB available memory
(mnedev) drmccloy@colchuck:/opt/mne-python$ MNE_CUDA_DEVICE=1 python -c "import mne; mne.cuda.init_cuda(verbose=True)"
Now using CUDA device 1
Enabling CUDA with 11.09 GB available memory
(mnedev) drmccloy@colchuck:/opt/mne-python$ python -c "import mne; mne.cuda.init_cuda(verbose=True)"
Now using CUDA device 0
Enabling CUDA with 1.79 GB …
```
> MRG, ENH: Expose CuPy device selection

- MANIFEST.in
- Makefile
Running on `master` (with the `-q` in the right place) we see a lot of warning outputs:
```
$ make wheel_quiet
```
<details>
```
warning: no files found matching 'mne/datasets' under directory 'mne'
warning: no files found matching 'mne/io/edf/gdf_encodes.txt'
warning: no previously-included files matching '*' found under directory 'examples/MNE-sample-data'
warning: no previously-included files matching '*' found under directory 'examples/MNE-testing-data'
warning: no previously-included files matching '*' found under directory 'examples/MNE-spm-face'
warning: no previously-included files matching '*' found under directory 'examples/MNE-somato-data'
warning: no previously-included files found matching 'Makefile'
warning: no previously-included files found matching '.coveragerc'
warning: …
```
> MRG, MAINT: Clean up manifest

- .travis.yml
Just a workaround for these errors in `master` until conda/travis/joblib updates (not sure whose fault it is) to fix them:
https://travis-ci.org/mne-tools/mne-python/jobs/586892855
Haven't tried to isolate the problem but basically all `n_jobs > 1` tests fail on one build.
> MAINT: Work around conda/joblib bug

- doc/changes/latest.inc
- mne/channels/_dig_montage_utils.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
fixes #6788
However I'm not sure that this is the right call. It does not
make sense that a single montage has 2 reference points.
And atleast in our test file we have 'GND' and 'REF' in the 
same file. Which also seems to be the case 
in https://github.com/mne-tools/mne-python/blob/master/mne/io/brainvision/tests/data/test.hpts
as reported https://github.com/mne-tools/mne-python/pull/6764#issuecomment-533206722
cc: @sappelhoff, @agramfort
> FIX: Add brainvision captrack ref channels when set_montage

- mne/datasets/utils.py
- mne/io/bti/tests/test_bti.py
Adds a smoke test using the data from @ebeich. Probably should have been part of #6300, but it's good that it works with no modifications!
> MRG, MAINT: Add test for gh-6300

- mne/channels/montage.py
- mne/channels/tests/test_montage.py
Fixes two bugs:
1. `np.loadtxt` for old NumPy, use `genfromtxt` instead
2. `read_dig_hpts` was reading HPI as EXTRA, properly read now
3. Changes `thing.__repr__` to cleaner `repr(thing)` in sereval places
Fixes failure in [master](https://travis-ci.org/mne-tools/mne-python/jobs/588562557) due to me merging too fast...
> MRG, FIX: Fix bug with read_dig_hpts

- doc/_static/style.css
@agramfort complained about See Also entries being blue on blue:
https://mne.tools/dev/generated/mne.channels.read_dig_hpts.html
This stylizes them the same way as `.. note::` sections by changing the CSS def from `.note` to `.alert-info` (which our `.. note::` also gets as a CSS class; `.. note::` gets `.note .alert-info`, whereas `See Also` gets `.admonition .alert-info`).
> MRG, STY: Style "See Also" the same way as .. note::

- mne/forward/tests/test_make_forward.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/meas_info.py
Reverts a change in the last week that made `info['dev_head_t'] = None` for EEG-only data (really anything using `create_info`). We can discuss if this is correct or not in #6814, but the safe thing to do for 0.19 is to revert it and set it to `Transform('meg', 'head', np.eye(4))`.
> MRG, MAINT: Revert dev_head_t as None

- .circleci/config.yml
- doc/_templates/navbar.html
- doc/changes/0.19.inc
- doc/whats_new.rst
- mne/__init__.py
Following the Wiki, this PR:
- updates whats new from current to 0.19
- updates navbar
This PR requires (https://github.com/mne-tools/mne-tools.github.io/pull/18)
> [release][DOC] Bump mne version to 0.19 and update navbar

- doc/_templates/navbar.html
Still this does not explain why stable does not point to 0.19
> FIX: 0.18 url

- doc/changes/0.15.inc
- doc/changes/0.18.inc
- doc/python_reference.rst
- mne/io/__init__.py
- mne/io/edf/__init__.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
Will merge when green, then backport since this was supposed to be part of 0.19.
Closes #6829
> MRG, API: Remove find_edf_events

- doc/conf.py
- doc/contributing.html
- doc/documentation.html
- doc/getting_started.html
- doc/install_mne_python.html
Add redirects for common errors (including those returned by "install mne-python", "contribute to mne-python" on google!).
Along with the `.htaccess` changes on MGH this should hopefully fix URL problems.
> MAINT: Redirects

- mne/beamformer/tests/test_dics.py
- mne/forward/forward.py
- mne/inverse_sparse/mxne_inverse.py
- mne/minimum_norm/inverse.py
- mne/morph.py
- mne/simulation/source.py
- mne/source_space.py
- mne/tests/test_morph.py
- mne/viz/_3d.py
Changes this:
```
larsoner@bunk:~/python/mne-python$ python -c "import mne; print(mne.read_source_spaces('/home/larsoner/mne_data/MNE-sample-data/subjects/sample/bem/sample-oct-6-src.fif'))"
```
> <SourceSpaces: [<surface (lh), n_vertices=155407, n_used=4098, coordinate_frame=MRI (surface RAS)>, <surface (rh), n_vertices=156866, n_used=4098, coordinate_frame=MRI (surface RAS)>]>
Into this (moving `coord frame` to the end since it's shared/constant, adding `subject`):
> <SourceSpaces: [<surface (lh), n_vertices=155407, n_used=4098>, <surface (rh), n_vertices=156866, n_used=4098>] MRI (surface RAS) coords, subject 'sample'>
And along the way DRYs our use of `src[0]['subject_his_id']` by adding a convenience `@property` to `SourceSpaces`. Maybe it should be public (?), but for now I left as …
> MAINT: DRY code for src subject and better src __repr__

- doc/glossary.rst
Added definition of beamformer to the glossary
@drammock
> added definition of beamformer to the glossary

- doc/glossary.rst
Added "minimum-norm estimate to the glossary"
@drammock
> DOC: glossary for minimum-norm estimate

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/epochs.py
- mne/tests/test_epochs.py
Example: Fixes #6842 
selection and drop_log should have been included in the _handle_event_repeated function. 
There are now two more input. I also added these new inputs to the tests_epochs.py. It still need to be fixed. 
CC: @agramfort please take over ...
> #6842: mne.Epochs with event_repeated parameter throws RuntimeError

- doc/changes/latest.inc
- examples/datasets/plot_opm_data.py
- examples/decoding/plot_decoding_time_generalization_conditions.py
- mne/beamformer/tests/test_rap_music.py
- mne/evoked.py
the epochs test pass locally, let's see if there are other tests that fail now :)
cc @agramfort @robertoostenveld
@larsoner the rationale here is that a factor of 2.5 is based on MNE-C filter defaults, which had steeper rolloffs than the current MNE-Python default, so 3 is safer (and easier to remember / work with as a rule of thumb in tutorials, etc)
> More conservative decim warning

- doc/glossary.rst
- examples/inverse/plot_compute_mne_inverse_raw_in_label.py
- examples/preprocessing/plot_head_positions.py
Added a brief definition of eLORETA and sLORETA, added links to the inverse operator, HPI and Digitization definitions.
> glossary update: esLORETA definition and links

- doc/changes/latest.inc
- examples/inverse/plot_lcmv_beamformer_volume.py
- examples/inverse/plot_morph_volume_stc.py
- mne/datasets/_fsaverage/base.py
- mne/datasets/_fsaverage/bem.txt
- mne/morph.py
- mne/source_estimate.py
- mne/source_space.py
- mne/tests/test_morph.py
Closes #6265.
Pushing now just to make sure everything is still green after initial refactoring that shouldn't change functionality.
> MRG, ENH: Add `src_to` argument to `SourceMorph`

- tutorials/preprocessing/plot_30_filtering_resampling.py
This is my review of #6872 
There is one section that needs further attention: it writes "and the data resampled from 600 Hz to 200 Hz gets automatically lowpass filtered at 100 Hz"
Should it not automatically be filtered at 67 Hz?
The subsequent figure also  does not show the effect of the anti-aliasing filter, which suggests that the anti-aliasing filter was indeed at 100 Hz or higher (or absent). That is not sufficient, it should be at 1/3*200=67.
> DOC: improved some parts of the filtering and resampling tutorial

- tutorials/misc/plot_modifying_data_inplace.py
The 'amplitude' parameter does not exist, must be 'envelope' instead.
> Invalid 'amplitude' parameter for apply_hilbert().

- doc/changes/latest.inc
- mne/channels/channels.py
- mne/tests/test_epochs.py
Following up on a discussion on Gitter a couple months ago, this adds a method `get_channel_types` to Raw, Epochs, and Evoked objects (by attaching the method to the `ContainsMixin`).
cc @jasmainak @cbrnr @larsoner @agramfort
> ENH: Add channel types mixin

- doc/changes/latest.inc
- mne/channels/layout.py
- mne/channels/tests/test_layout.py
Example: Fixes #6891.
When no corresponding KIT layout is built in generate one automatically (previously raised an error).
Leaves open the possibility to add manually built layout for any system later.
> ENH _find_kit_layout():  add fallback on automatic layout

- doc/glossary.rst
> Added dSPM

- doc/changes/latest.inc
- mne/epochs.py
- mne/viz/epochs.py
- mne/viz/ica.py
- mne/viz/tests/test_epochs.py
- mne/viz/utils.py
closes #6737 
just started by copying over changes from autoreject. Will iterate tomorrow
> MRG: allow users to annotate epochs with colors

- doc/changes/latest.inc
- mne/preprocessing/ica.py
> Fix infomax

- mne/morph.py
Finally managed to sort out the `ravel`/`reshape`s in the volume morph code and simplified them.
> MRG, MAINT: Simplify code for vol ravel

- doc/changes/latest.inc
- mne/channels/channels.py
- mne/commands/mne_anonymize.py
- mne/commands/tests/test_commands.py
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
- mne/tests/test_report.py
This modifies the way we were anonymizing meas_info objects to mainly permit time shifting dates.
It also adds an executable for anonymizing raw fif files from the command line.
The goal was to match the current plans in mne_cpp (https://github.com/mne-tools/mne-cpp/pull/393) which is still under development. hence the [WIP] tag.
closes  #6844 and #4982
@LorenzE
> ENH: Basic anonymization

- mne/preprocessing/_optical_density.py
- mne/preprocessing/tests/test_optical_density.py
Import order error as noted by @agramfort [here](https://github.com/mne-tools/mne-python/pull/6827#pullrequestreview-297848958)
Changes the order of imports from general to local
> FIX: Import order in optical density code

- doc/changes/latest.inc
- mne/io/proj.py
- mne/utils/docs.py
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
- tutorials/preprocessing/plot_50_artifact_correction_ssp.py
Allows plotting multiple projector topomaps with jointly-determined colorbar limits.  API is:
- `vlim='joint'`: within a given channel type, vlims will all be the same, determined by the pooled data for all projectors of that channel type
- `vlim=(None, None)`: vlims determined separately for every projector (default, current behavior)
- `vlim=(None, 0.4)` vmax will be the same (0.4) for all topoplots, but vmin will be data-dependent
- `vlim=(-0.3, None)` vmin will be the same (-0.3) for all topoplots, but vmax will be data-dependent
> ENH, API: joint clims for proj topomaps; unify API with Projector.plot_topomap

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/forward/forward.py
- mne/source_estimate.py
- mne/tests/test_source_estimate.py
- mne/utils/__init__.py
- mne/utils/check.py
Adds tests and credits that should have been part of #6908.
> MRG, FIX: Add tests for estimate_snr

- doc/overview/faq.rst
Added in the FAQ the solution to the annoying bug in Mac were running in an IDE such as Spyder or PyCharm commands take very long to execute. 
The issue is solved by changing the system defaults or by installing the appnope module and importing it each time a new console is created. 
closes ##6935
> Added FAQ solution on slow python closes ##6935

- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
- tutorials/intro/plot_10_overview.py
- tutorials/time-freq/plot_sensors_time_frequency.py
Follow-up to #6907 to take care of https://app.circleci.com/jobs/github/mne-tools/mne-python/16176/tests
But actually looking deeper at the code, I think we introduced a regression in #6907. Our docs say:
> If `int`, returns tfr[..., ::decim]
In other words, we compute the TFR *then* decimate. It might actually be reasonable to allow freqs above Nyquist-after-decimation here depending on how many cycles wide the wavelets are, for example. 
But in any case, the freqs are currently computed for the wrong sample rate. I'll need to add a regression test for this, since this would have created an errant `decim`-fold change in the frequency locations.
> MRG, FIX: Compute kernels at proper sample rate

- doc/changes/latest.inc
- mne/preprocessing/flat.py
- mne/preprocessing/tests/test_flat.py
Pretty straightforward fix. Without it, `intervalrecording` gives 306 bad channels. MaxFilter also detects that there should be 21 flat channels.
> MRG, FIX: mark_flat should ignore skips

- doc/changes/0.19.inc
- mne/viz/utils.py
* Update .gitignore
* Change of extent for proper plotting
* Update latest.inc
* Update mne/viz/utils.py
Co-Authored-By: Eric Larson <larson.eric.d@gmail.com>
* Update mne/viz/utils.py
Co-Authored-By: Eric Larson <larson.eric.d@gmail.com>
* Remove first definition of time_lims
* FIX: Conditional
convincing, etc. or more likely the reviewers are …
> FIX: Aligning frequency bins to y-axis (#6930)

- doc/changes/latest.inc
- mne/transforms.py
I updated the latest.inc @agramfort requested. 
Also:
There was no documentation on the coordinate frame in class transform.
I added the notes as follows:
```
Notes
------
Valid coordinate systems are 'meg','mri','mri_voxel','head','mri_tal','ras'
'fs_tal','ctf_head','ctf_meg','unknown'
```
information to select options "to" and "fro" 
ready to review for @agramfort and @larsoner
> updated latest.inc and documentation of coordinate in transofrm.py

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
N/A
Previously edf(+) loading was incorrectly reporting that high and low pass filtering was always 0 due to the regex never actually capturing the number.
Example `prefiltering` …
> FIX: edf(+) no longer misses prefiltering

- mne/viz/evoked.py
closes #6943 
also fixes:
- the behavior of the `show_names` param, which was supposed to be showing channel indices when `picks=None` but was showing channel names (which led to a mismatch between the yaxis label "channel (index)" and the ticklabels)
- the overplotting of the same yticklabel several times in some cases (e.g., the test case with only 2 channels)
- clarifies slightly the `show_names` docstring
There is plenty of room for further improvement here, for example aligning the x ticks with the center of the imshow columns, but that will be rather involved and should be done in a separate PR.
> Fix ytick regression

- .circleci/config.yml
see if this makes the circle build failures go away. (not optimistic...)
> try to fix circle [skip travis]

- mne/io/base.py
I was using the `raw.load_bad_channels()` method for the first time earlier this week.
This PR improves the docstring so that users know what input file to provide.
> MINOR, DOC: clarify expected format of input file in docstr

- environment.yml
- requirements.txt
This PR updates the package requirements for the pyvista 3d backend. Panel is no longer required as work on notebook integration is under heavy development at the moment.
> [MRG] Use latest version 0.22.4 of pyvista instead of master

- tutorials/io/plot_20_reading_eeg_data.py
based on the comment in #6963, seems the link was easy to miss. This might help.
> DOC: make gist link two words so it's easier to see

- doc/_static/style.css
- doc/conf.py
1. Switches `numpydoc` to use `numpydoc_attributes_as_param_list = True` like in `sklearn` ([requested](https://github.com/mne-tools/mne-python/pull/6938#issuecomment-543051254) by @agramfort)
2. Sets `capture_repr` to make it so the recent SG PR does not change our behavior
3. Tweaks our param list style to look more like `sklearn`
@drammock point (3) is about aesthetic judgment so I'll let you take over and keep / discard / modify as you see fit.
> DOC: Clearer attribute style

- doc/conf.py
- mne/preprocessing/maxwell.py
- tutorials/preprocessing/plot_60_maxwell_filtering_sss.py
Fixes our weekly error that looks like this
https://app.circleci.com/jobs/github/mne-tools/mne-python/16321
By just ignoring it. The link is fine but the Python check for it fails. See for example https://github.com/sphinx-doc/sphinx/issues/5051. Also unifies how we link to these articles in two different places.
> MRG, MAINT: Fix linkcheck error

- environment.yml
- examples/visualization/plot_publication_figure.py
- mne/viz/backends/_pyvista.py
- requirements.txt
This is a fastfix for the broken cropping in `examples/visualization/plot_publication_figure`.
> [MRG] Fix borders on pyvista backend

- mne/viz/ica.py
- mne/viz/utils.py
When plotting ICA component properties, one of the things that gets plotted is the component PSD. This uses the helper function `_convert_psds` that performs a check on the presense of zeros in the
PSD. When zeros are detected, a warning is printed. To construct the warning message string, it is assumed that the first dimension of the `psds` array contains channels. However, in the case of `ica.plot_properties`, the first dimensions contains epochs. Hence, the construction of the warning message string fails with an index out of bounds error.
This PR adds a flag to the `_convert_psds` helper function to inform it that the first dimension of the `psds` array contains epochs rather than channels.
> Fix ica.plot_properties with bad data

- doc/changes/latest.inc
- mne/epochs.py
- mne/evoked.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
Makes `mne.Epochs.shift_time` and `mne.Evoked.shift_time` return the modified `Epochs` or `Evoked` instance (instead of `None`).
> MRG, FIX: make shift_time return self

- mne/datasets/hf_sef/hf_sef.py
Update HF-SEF dataset to a new version (with updated trans) located on zenodo.org.
> MRG: switch HF-SEF to v1.1 on zenodo

- doc/changes/latest.inc
- mne/channels/channels.py
- mne/channels/interpolation.py
- mne/channels/tests/test_interpolation.py
Looking at our `interpolation` code:
1. The `origin` was never passed during MEG interpolation.
2. The `origin` was never used during EEG interpolation, despite the fact that it uses a spherical spline expansion.
3. The EEG interpolation estimated an origin using `_fit_sphere` that depended on the points actually being interpolated (which doesn't make much sense, we should be able to trust our dig/channel locs even for these bad channels, otherwise interp will not work)
This code fixes these bugs by:
1. Passing `origin` to the MEG functions
2. Subtracting `origin` from the EEG channel positions before computing the splines
3. Changing the default from `(0., 0., 0.04)` to `'auto'`, which uses a digitization-based head fit (as we do elsewhere, e.g. `maxwell_filter`)
Tests updated to show …
> MRG, BUG: Fix interpolation origin bugs

- mne/channels/channels.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
Enables `raw.plot_psd()` to work with `fnirs_od`, `hbo`, and `hbr` types.
This script demonstrates the changes work. Where can I update a test for this?
```python
import mne
fname_nirx_15_0 = op.join(mne.datasets.testing.data_path(download=False),  'NIRx', 'nirx_15_0_recording')
raw = mne.io.read_raw_nirx(fname_nirx_15_0, preload=True); 
raw.plot_psd();
raw = mne.preprocessing.optical_density(raw)
raw.plot_psd();
raw = mne.preprocessing.beer_lambert_law(raw)
raw.plot_psd();
raw = raw.filter(None, 0.7, h_trans_bandwidth = 0.2)
raw.plot_psd();
raw.plot_psd(average=True);
```
> WIP: Allow raw.plot_psd() on fnirs_od and hbo/hbr data

- mne/forward/forward.py
- mne/io/constants.py
- mne/io/meas_info.py
- mne/io/reference.py
- mne/io/tests/test_constants.py
- mne/io/tests/test_reference.py
Eventually I can roll back the constants tests once we get https://github.com/mne-tools/fiff-constants/pull/23 in. In the meantime we can merge this if it looks reasonable to folks so that #6910 can use it.
As @agramfort pointed out, our inverse checks just look at effectively `bool(info['custom_ref_applied'])`, so we should still be good there.
> MRG, ENH: Add support for CSD as custom reference type

- doc/_static/style.css
- mne/bem.py
1. Make it clear what the radii/conductivities in `make_sphere_model` stand for.
2. Fix [this wrong code block color in the Note](https://mne.tools/dev/install/mne_c.html#system-requirements) using CSS.
I think the CSS fix is right. Not sure why the `pre` lines (removed here) were introduced in #6812, but they do not seem necessary to make the `See Also` sections render properly.
> MRG, DOC: Better styling and message

- mne/source_estimate.py
Just a tiny tweak to improve and clarify the docstring of SourceEstimate object.
> DOC: clarify docstring for stc object

- doc/changes/latest.inc
- mne/annotations.py
- mne/tests/test_annotations.py
closes #7012
If saved annotation.txt is empty, when reading it it crashes, as it expects to get the onset, duration and description. 
Added a try and except ValueError. It does not crash, just gives a warning.
> FIX:no error if txt annotation empty 

- doc/changes/latest.inc
- mne/dipole.py
- mne/epochs.py
- mne/evoked.py
- mne/filter.py
- mne/forward/forward.py
- mne/tests/test_dipole.py
- mne/tests/test_evoked.py
- mne/utils/__init__.py
- mne/utils/mixin.py
- allow `Epochs.shift_time` and `Evoked.shift_time` to shift time by amounts that are not integer-multiples of the sampling period
- refactor so the same code is used for both classes
cc @jjnurminen @larsoner @agramfort
> MRG, FIX: allow arbitrary offset for {Epochs,Evoked}.shift_time

- .travis.yml
- azure-pipelines.yml
Trying to:
1. Load balance -- Azure backs up less than Trivis, and
2. Make style checks easier to parse.
This moves the style checks to Azure, in separate steps so they should hopefully show up nicely in separate statuses/prompts.
> MAINT: Migrate style checks to Azure

- mne/conftest.py
Should fix a problem with latest `matplotlib` hitting a SyntaxWarning.
> MAINT: Fix CIs

- doc/changes/latest.inc
- mne/inverse_sparse/mxne_inverse.py
Currently the `tol` parameter of `mixed_norm` and `tf_mixed_norm` solvers is used "raw": tol=1e-8 means that the solver will stop if a duality gap below 1e-8 is reached.
However IMO the duality gap should be compared against the primal objective (1e-8 is not a good precision if the optimal primal is around 1e-7, while it may be too precise if the optimal primal is 1000).
A good heuristic is that the primal is of the order of (M ** 2)/sum()  (which is the value of the primal at 0).
I propose to rescale `tol` by ||M||^2. This is done by scikit-learn for the Lasso and MultitaskLasso:
https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/linear_model/_cd_fast.pyx#L161
https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/linear_model/_cd_fast.pyx#L700
The examples don't …
> [MRG] ENH Make tolerance easier to set in sparse inverse solvers

- mne/viz/tests/test_3d.py
This small PR updates some missed 3d tests with the `renderer` fixture.
The only test in `test_3d.py` which only `requires_mayavi` is `test_plot_vec_source_estimates`. This one is the next in my list.
> Update 3d tests with renderer fixture

- doc/python_reference.rst
- mne/io/nirx/tests/test_nirx.py
- mne/preprocessing/__init__.py
- mne/preprocessing/_beer_lambert_law.py
- tutorials/preprocessing/plot_70_fnirs_processing.py
Addresses #7034 
Changes the `_short_channels` function to a public `short_channels()` function and updates tests and tutorial.
> MRG: Make short channel function public

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
Fixes issue related to https://github.com/mne-tools/mne-bids/pull/280. 
Windows throws an error when datetime.fromtimestamp is less than 0. This is the case for dates before 1970 Jan 1. I suspect that the way mne.io.meas_info._stamp_to_dt uses datetime.fromtimestamp will fail on a Windows OS. I am not by a windows machine and so cannot confirm but if the tests for windows fail, then I will fix it by using datetime.fromtimestamp(0) and then adding the argument that was being passed to fromtimestamp to timedelta. Basically, instead of reading from a timestamp, the number that was to be read from a timestamp will be used to move the time back stamp number of seconds.
> [BUG] testing reading old data

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/beamformer/_compute_beamformer.py
- mne/fixes.py
- mne/utils/__init__.py
- mne/utils/linalg.py
Alternative version of #6763 designed to minimize code differences / maximize diff readability. @dmalt, @britta-wstnr, @wmvanvliet feel free to have a look. I think it ended up pretty readable.
`pytest mne/beamformer/` on `master` takes 33 sec, on this PR it's 26 sec, so pretty nice gains considering the testing overhead.
I have a `_noop_indentation_context` manager in there just to keep the indentation the same so the diff is more readable. Hopefully this makes it easy enough to see how each line was translated from an operation on a single source to operating on all sources simultaneously. Once everyone is happy about the diff, then I can remove that context manager before merge.
> ENH: Vectorize beamformer computation

- examples/inverse/plot_resolution_metrics.py
- examples/inverse/plot_resolution_metrics_eegmeg.py
- mne/minimum_norm/resolution_matrix.py
CircleCI died running `plot_resolution_matrices.py` because memory usage was too high. This takes it from over 2GB to under 1.75 GB.
> MRG, MAINT: Reduce memory usage

- doc/changes/latest.inc
- mne/viz/_3d.py
- tutorials/source-modeling/plot_mne_dspm_source_localization.py
> MRG, ENH: Fix plot_vector_source_estimates

- mne/decoding/base.py
- mne/decoding/search_light.py
- mne/decoding/tests/test_base.py
- mne/fixes.py
- mne/inverse_sparse/mxne_optim.py
- mne/stats/tests/test_regression.py
`sklearn` master has deprecated importing from submodules things that can be imported from higher level ones. Also they emit a warning when `random_state` is passed with `shuffle=False`, since it has no effect.
> MRG, MAINT: Updates for sklearn deprecations

- mne/io/matrix.py
- mne/io/open.py
- mne/io/tag.py
- mne/source_space.py
It turns out that our old `read_big` (#342) workaround has some overhead. Removing it in this PR takes the time to `read_forward_solution` down from 0.14 to 0.11 sec. So hopefully some speedups across the board for FIF I/O.
The workaround / bug is from 7 years ago, so I'm hoping that several new Python versions later it has been fixed. We'll see based on how the Azure builds do.
> MRG, ENH: Speed up I/O

- mne/minimum_norm/_eloreta.py
- mne/utils/__init__.py
- mne/utils/linalg.py
Following the patterns of #7032, this speeds up eLORETA testing a bit by using `np.linalg` vectorization. The slowest test of `pytest mne/minimum_norm/tests/ -k eLORETA` drops from 0.98 sec to 0.92 sec. Not huge, but the code is also simpler this way, so why not.
And after #7032 we can drop the `_repeated_pinv2` function entirely.
> MRG, ENH: Speed up eloreta by vectorizing

- environment.yml
Let's see if everything works without this workaround. Probably things have been fixed in the last year to take care of whatever it was we were working around. See #7013 for related discussion.
Closes #7013.
> MRG, MAINT: Remove testpath requirement

- mne/conftest.py
Work around [this warning](https://travis-ci.org/mne-tools/mne-python/jobs/609869541):
```
E       DeprecationWarning: scipy.gradient is deprecated and will be removed in SciPy 2.0.0, use numpy.gradient instead
```
Until dipy pushes a release with https://github.com/nipy/dipy/pull/1994
> MAINT: Ignore warning for dipy

- doc/changes/latest.inc
- mne/inverse_sparse/_gamma_map.py
- mne/inverse_sparse/mxne_inverse.py
- mne/inverse_sparse/tests/test_gamma_map.py
- mne/inverse_sparse/tests/test_mxne_inverse.py
- mne/utils/__init__.py
- mne/utils/_testing.py
- mne/utils/docs.py
Minor adaptation that allows to return vector source estimates from the `gamma_map()` function. To be consistent with the MNE functions I used `pick_ori` as parameter (rather than a boolean argument for vectors).
> ENH gamma_map():  allow returning vector source estimates

- doc/changes/latest.inc
- mne/channels/channels.py
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
Correctly set `annotations.orig_time` from `meas_date`.
Thanks @alexrockhill for noticing it. should help with https://github.com/mne-tools/mne-bids/pull/280
@alexrockhill can you see if it solves your issue?
> FIX: anonymize annotations

- examples/inverse/plot_lcmv_beamformer.py
- examples/inverse/plot_lcmv_beamformer_volume.py
When computing covariance matrices to feed into the `make_lcmv` beamformer, you want to set `method='empirical'`, because the beamformer code will take care of any regularization needs. Applying regularization before will make the covariance matrix full rank, bypassing the clever rank estimation routines of the beamformer.
This PR changes the LCMV example `method='shrunk'` -> `method='empirical'`. In case of the example data, not much changes in the resulting figure.
> Use empirical covariance matrices for beamformer example

- mne/preprocessing/maxwell.py
Doc fix for `sss_basis*` functions
Closes #7065
> MRG, DOC: SSS origin is in meters

- mne/io/nirx/nirx.py
- mne/io/nirx/tests/test_nirx.py
- mne/preprocessing/nirs/_beer_lambert_law.py
Addresses issue #7057
Change the way NIRS light frequency is encoded as [suggested by @larsoner](https://github.com/mne-tools/mne-python/pull/6674#issuecomment-546908907)
> MRG: Change way NIRS frequency is encoded

- mne/io/base.py
- mne/viz/ica.py
- mne/viz/raw.py
- mne/viz/utils.py
Adds "use_scalebars" as a boolean parameter into plot() and plot_raw().
Example: Fixes #7068 
Added a boolean parameter to allow programmatic on/off of the unit scale bars.
> FIX: Adding use_scalebars as a parameter.

- doc/changes/latest.inc
- mne/channels/channels.py
- mne/channels/tests/test_channels.py
- mne/cov.py
- mne/forward/forward.py
- mne/forward/tests/test_forward.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/meas_info.py
- mne/io/pick.py
- mne/io/tests/test_meas_info.py
- mne/io/tests/test_pick.py
- mne/tests/test_cov.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
- mne/time_frequency/csd.py
- mne/time_frequency/tests/test_csd.py
- mne/time_frequency/tests/test_tfr.py
- mne/utils/numerics.py
In the process of adding support for DICS whitening (#7021), I now find myself with an `Info`, two CSD matrices and a forward model, all of which need to have exactly the same channels defined in the same order for the computations to work. This is a common theme throughout our codebase and currently, we have a smattering of private helper functions everywhere that deal with equalizing channels one way or another.
However, we also have `mne.channels.equalize_channels`, which job it is to, given a list of instances, equalize the channels amongst them. In this PR, I've extended its capabilities to:
1. Also deal with `Info`, `Forward`, `Covariance` and `CrossSpectralDensity`
2. Also re-order the channels to make sure the channel orders are the same.
To accomplish this, I had to give our …
> [WIP] Make equalize_channels capable of operating on Forward, Covariance and CrossSpectralDensity

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/decoding/base.py
- mne/decoding/tests/test_base.py
Fixes #7027 .
This PR adds the support of `GridSearchCV` for `LinearModel`. I also ran the decoding/tests/test_base.py and got the 3 passed.
> ENH: Adding support of GridSearchCV for mne.decoding.LinearModel

- doc/changes/latest.inc
- mne/io/ctf/ctf.py
- mne/io/ctf/info.py
- mne/io/ctf/markers.py
- mne/io/ctf/tests/test_ctf.py
BUG: CTF IO never sets the meas_date.
I've checked on my data that the newly set meas_date is correct, at least to the day.
```
In [2]: raw = mne.io.read_raw_ctf('nnnn_20190724_01.ds')                                                                       
In [3]: mne.io.meas_info._stamp_to_dt(raw.info['meas_date'])                                                                                        
Out[3]: datetime.datetime(2019, 7, 24, 7, 55, tzinfo=datetime.timezone.utc)
```
I'm counting on existing annotations testing to be complete.
> BUG: CTF - set meas_date

- tutorials/preprocessing/plot_10_preprocessing_overview.py
minor tweaks to the preprocessing overview tutorial:
- small extra text explaining why image plots look blocky (few epochs)
- apply baseline when extracting artifact epochs
- picks a nicer thumbnail image
> MRG, DOC: tutorial tweaks

- azure-pipelines.yml
- mne/conftest.py
- mne/decoding/tests/test_base.py
- mne/epochs.py
- mne/label.py
- mne/tests/test_epochs.py
- mne/viz/tests/test_3d.py
- mne/viz/topomap.py
3.8 is still missing a few deps on PyPi (vtk, mayavi, PySurfer, pyvista, numexpr, python-picard, numba, dipy) but we can test most of them. The 3D viz will be held up by VTK 9's release (first to release 3.8 wheels, even though I was able to build and use 8.2 locally) which they have scheduled for [Q1 2020](https://github.com/KitwareMedical/VTKPythonPackage/issues/39).
Better not to wait this long to get 3.8 testing going, so this gets the process started.
> MAINT: Test on 3.8

- doc/changes/0.19.inc
- doc/conf.py
- examples/visualization/plot_channel_epochs_image.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/conftest.py
Closes #7114.
For backward compat, we should allow setting montages with `coord_frame='unknown'` if not all fids are present. Now we do so with a warning.
> MRG, FIX: Allow unknown when setting montage

- mne/viz/epochs.py
- mne/viz/misc.py
- mne/viz/tests/test_misc.py
- tutorials/epochs/plot_20_visualize_epochs.py
closes #7101 , which turned out not to have been a bug after all.  I was doing something like:
```python
epochs['face'].plot(..., event_colors=dict(buttonpress='red'))
```
in order to control the color of buttonpress events in a plot of "face" epochs.  The two problems with this:
1. `epochs['face']` drops all the other entries in `epochs.event_id` except for `{'face': 5}`, so the message that `"buttonpress" is in the color dict but not in events or event_id` is technically correct. However:
2. the error message implies that passing `event_colors=dict(face='blue')` should work, which it does not (on current master) because the color handling only accepts event integers as valid keys for the color dict.
This PR refactors `_handle_event_colors` to accept either valid event integers, or valid …
> ENH: refactor _handle_event_colors

- doc/changes/latest.inc
- mne/stats/cluster_level.py
- tutorials/stats-source-space/plot_stats_cluster_spatio_temporal.py
- tutorials/stats-source-space/plot_stats_cluster_spatio_temporal_2samp.py
- tutorials/stats-source-space/plot_stats_cluster_spatio_temporal_repeated_measures_anova.py
there was a hard-coded `1e3` multiplication in `summarize_clusters_stc` that was cancelling out the effect of the default `tstep=1e-3` (which is probably why nobody noticed).  Passing any other value of `tstep` leads to really weird results; this should fix it.
> MRG, FIX: scaling in summarize_clusters_stc

- doc/changes/latest.inc
- mne/annotations.py
- mne/channels/channels.py
- mne/commands/tests/test_commands.py
- mne/forward/forward.py
- mne/io/__init__.py
- mne/io/base.py
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
- mne/io/bti/bti.py
- mne/io/ctf/info.py
- mne/io/ctf/markers.py
- mne/io/ctf/tests/test_ctf.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_gdf.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/kit/kit.py
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
- mne/io/tests/test_raw.py
- mne/report.py
- mne/simulation/evoked.py
- mne/tests/test_annotations.py
- mne/tests/test_epochs.py
- mne/utils/__init__.py
- mne/utils/_testing.py
- mne/utils/numerics.py
- mne/viz/tests/test_raw.py
- tutorials/raw/plot_30_annotate_raw.py
~~Closes #7116.~~
~~First step, replicate the failure (hopefully). It passes locally on Linux but hopefully Azure shows the issue.~~
> MRG, ENH: Use datetime objects for meas_date

- doc/changes/latest.inc
- mne/coreg.py
- mne/label.py
- mne/source_space.py
- mne/tests/test_coreg.py
- mne/tests/test_label.py
- mne/tests/test_source_space.py
1. Add `label.restrict`, the opposite of `label.fill`
2. Add `dist_limit=0.` to allow using faster `dijkstra` calculation in SciPy 1.3+ to only calculate patch information
3. Remove errant statement in docs of `n_jobs` parameter of `add_dist` and `dist_limit` about parallelization depends on the number of source spaces (it parallelizes over `vertno` actually).
4. ~~EDIT: Add test infrastructure workarounds for nilearn using deprecated sklearn stuff hitting us due to sklearn 0.22 release~~
> MRG, ENH: Add Label.restrict and faster patch info

- doc/changes/latest.inc
- mne/epochs.py
- mne/viz/epochs.py
- tutorials/epochs/plot_20_visualize_epochs.py
as discussed in #7111, this adds an `event_id` parameter to `epochs.plot()` so that if users are passing in `events` that aren't part of `epochs.events`, they can specify event colors by name instead of by integer.
It also allows user-specified event colors for the t=0 event to override the (default) transparent green vertical line at t=0.  On this PR:
```python
catch_trials_and_buttonpresses = mne.pick_events(events, include=[5, 32])
epochs['face'].plot(events=catch_trials_and_buttonpresses, event_id=event_dict,
event_colors=dict(buttonpress='red', face='blue'))
```
yields this:
If no events are specified, or if the events passed to `plot()` don't include the event at t=0, the default line is still drawn (though it's been moved to zorder=0 to lie behind the traces instead of on top of …
> VIZ, ENH: Add event dict to epochs plot signature

- doc/changes/latest.inc
- examples/decoding/plot_decoding_xdawn_eeg.py
- examples/preprocessing/plot_xdawn_denoising.py
- mne/preprocessing/tests/test_xdawn.py
- mne/preprocessing/xdawn.py
This removes the incorrect transpose when saving the obtained filters/patterns in the ``Xdawn`` instance. 
Fixes  #7127
I also ran the ``plot_decoding_xdawn_eeg`` example with the ``pyriemann`` implementation of ``Xdawn``, which yielded a bit better accuracies (0.88 for pyriemann vs 0.86 for this PR with the MNE implementation). This might be due to different covariance calculations/regularization. The estimated patterns look similar.
> Remove incorrect transpose when selecting xDAWN filters

- doc/changes/latest.inc
- mne/chpi.py
- mne/fixes.py
- mne/forward/_compute_forward.py
- mne/surface.py
- mne/transforms.py
- mne/utils/_testing.py
- mne/utils/config.py
This forward code takes 24 sec on master and 17 sec on this PR:
<details>
```
import time
import mne
subjects_dir = data_path + '/subjects'
bem = subjects_dir + '/sample/bem/sample-5120-5120-5120-bem-sol.fif'
raw_fname = data_path + '/MEG/sample/sample_audvis_raw.fif'
trans = data_path + '/MEG/sample/sample_audvis_raw-trans.fif'
src = mne.setup_source_space(subject, spacing='oct6',
subjects_dir=subjects_dir, add_dist='patch')
def test():
mne.make_forward_solution(raw_fname, trans=trans, src=src, bem=bem,
verbose=True)
if __name__ == '__main__':
test()
```
</details>
This cHPI fitting code takes 3.5 sec on master and 2.6 sec on this PR:
<details>
```
import time
import …
```
> MRG, ENH: Speed up forward computations with Numba

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/bem.py
Fixes #7139.
Make `mne.bem.make_watershed_bem` write correct surfaces inside bem directory.
- Before fix
```
.
├── brain
├── inner_skull
├── outer_skin
└── outer_skull
```
- After fix
```
bem
└── watershed
├── sample_brain_surface
├── sample_inner_skull_surface
├── sample_outer_skin_surface
└── sample_outer_skull_surface
```
Details are in #7139.
> MRG, FIX: Make mne.bem.make_watershed_bem write correct surfaces inside bem directory

- examples/inverse/plot_time_frequency_mixed_norm_inverse.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/base_renderer.py
- mne/viz/backends/tests/test_renderer.py
This PR adds support for the `borders` parameter in the `add_label()` function of the `_Brain` object.
Closes part of #7143
> Add support for borders in add_label

- doc/changes/latest.inc
- mne/channels/_standard_montage_utils.py
- mne/channels/tests/test_montage.py
I had trouble reading a BESA spherical `elp` file using `channels.read_custom_montage()`, as the fiducials were treated as sensor channels. This PR adds special handling for the fiducials.
> BF/ENH: Make _read_elp_besa() respect fiducial points

- mne/tests/test_transforms.py
- mne/transforms.py
Cleans up some quat math to help with #7096. Also fixes a small corner case bug with `_angle_from_quats` (which so far we've just used in status updates, so probably not worth a whats_new update).
> MRG, MAINT: Cleaner quaternion math

- environment.yml
- mne/viz/backends/_pyvista.py
- requirements.txt
This PR updates the package requirements for the pyvista 3d backend.
> MRG: Use latest version 0.23.0 of pyvista instead of master

- .travis.yml
- azure-pipelines.yml
In local testing the `--tb=auto` with `--show-locals` is nice, but on CIs it makes navigating the failure logs pretty miserable. So on CIs we now do `--tb=short`, so instead of a single failure looking like this (175 lines for the whole thing):
<details>
```
omar:mne-python larsoner$ pytest mne/minimum_norm/tests/test_inverse.py -k apply_inverse_operator
Test session starts (platform: darwin, Python 3.7.3, pytest 5.2.0, pytest-sugar 0.9.2)
rootdir: /Users/larsoner/python/mne-python, inifile: setup.cfg
plugins: astropy-header-0.1.1, arraydiff-0.3, sugar-0.9.2, remotedata-0.3.2, timeout-1.3.3, openfiles-0.4.0, mock-1.11.0, cov-2.7.1, doctestplus-0.5.0
collecting ... 
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― test_apply_inverse_operator[testing_data] …
```
> MRG, MAINT: Make CI tracebacks easier to read

- .circleci/config.yml
- doc/_static/reset-syntax.css
- doc/_static/style.css
- doc/_templates/layout.html
- tutorials/intro/plot_10_overview.py
Proof of concept for https://github.com/sphinx-gallery/sphinx-gallery/pull/581. It makes MNE links in code blocks bold, and leaves the other ones (Python, Matplotlib, etc.) as the standard weight.
It also removes `reset-syntax.css` in favor of just having our CSS all in `style.css`.
~~WIP until the SG PR is merged, then I'll remove the `circleci` changes.~~
> MRG, DOC: Improve styling using classes

- mne/annotations.py
Hopefully addresses an issue that came up on the mailing list, about how to handle raw formats that encode integer events as strings.
> DOC: add notes section to events_from_annotations docstring

- doc/changes/latest.inc
- doc/python_reference.rst
- mne/__init__.py
- mne/annotations.py
- mne/tests/test_annotations.py
This adds a new function that creates annotations from an event array. 
Fixes issue raised in #6125.
> MRG: Add annotations_from_events

- mne/viz/_brain/_timeviewer.py
This PR uses the new [text widget](https://docs.pyvista.org/plotting/plotting.html?pyvista.BasePlotter.add_text_slider_widget#pyvista.BasePlotter.add_text_slider_widget) introduced recently in PyVista and avoid the creation of a custom slider.
This is refactoring, the features won't change.
It's an item of https://github.com/mne-tools/mne-python/issues/7162
> MRG: Use a text slider widget

- mne/viz/backends/_pyvista.py
This PR fixes the bug with the `dorsal` view making the brain disappear (reported in https://github.com/mne-tools/mne-python/pull/7153#issuecomment-568735444).
This patch is strongly inspired by [mayavi](https://github.com/enthought/mayavi/blob/master/mayavi/tools/camera.py#L312-L318).
> MRG: Correct camera view_up when necessary

- mne/viz/_brain/_timeviewer.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/_brain/utils.py
This PR adds support for 'nearest' interpolation when the number of `smoothing_steps=0`.
Example with `plot_visualize_stc.py`:
smoothing_steps=0 | smoothing_steps=1 | smoothing_steps=10
------------------------|--------------------------|---------------------------
> MRG: Add support for smoothing_steps=0

- mne/viz/_brain/_brain.py
- mne/viz/_brain/_timeviewer.py
- mne/viz/_brain/colormap.py
- mne/viz/_brain/tests/test_brain.py
This PR furthers the discussion around the control over the end points of the colorbar in `_TimeViewer` and offers a prototype that 'snaps back' the value when they reach the limits (idea coming from @agramfort).
Here is an animation:
what do you think @larsoner ? It's an alternative for the bumping of the values.
---
**ToDo**
> MRG: Bump colorbar control points

- doc/changes/latest.inc
- mne/io/edf/edf.py
Fixes #7189.
It would be good to check that both the data and annotations are read correctly. There are 463 annotations, which seems to be correct even though SigViewer only reports 30 (but I think this is because SigViewer only uses the first annotation channel and ignores the rest).
> Support multiple TAL channels in BDF reader

- mne/bem.py
`bem.make_watershed_bem()` calls `_prepare_env()`, which returns a tuple of 3 values; of those, 2 are currently assigned to variables. However, the second one, `mri_dir`, is then overwritten again just a few lines further down without ever getting used:
https://github.com/mne-tools/mne-python/blob/9d512217cf367f0b71d69602c91839dfd96298cf/mne/bem.py#L1093-L1101
This PR drops the first, unused assignment of `mri_dir`.
> RF: Ignore `mri_dir` returned by `bem._prepare_env()`

- mne/bem.py
Remove code duplication as pointed out in https://github.com/mne-tools/mne-python/pull/7196#issuecomment-573450321
Instead of discarding two of the three return values of `_prepare_env()` and then re-creating them from scratch, these return values are now kept and used.
> MAINT: Remove code duplication

- .circleci/config.yml
- .travis.yml
Want this to fail on CircleCI so that I can then try an interactive SSH session and iteratively install packages to see what's actually needed rather than getting all of `qt5-default`.
> MAINT: Simplify CI installation of PyQt5 dependencies

- mne/viz/backends/_pyvista.py
This is follow-up of https://github.com/pyvista/pyvista/pull/529#issuecomment-574076243 and disables depth peeling by default. It can still be enabled locally if needed depending on the use cases.
> Disable depth peeling by default

- mne/io/eeglab/eeglab.py
- mne/io/eeglab/tests/test_eeglab.py
Fixes #7192
When `EEG.data` file name is wrong (the file is not present) an additional check is performed: set file name is used replacing ".set" with ".fdt". This is a common problem when set files are renamed in the operating system and not via eeglab (which also changes `EEG.data`).
> Eeglab reader: look for fdt if EEG.data file name is wrong

- mne/viz/_brain/_brain.py
- mne/viz/_brain/_timeviewer.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/backends/_pyvista.py
This PR adds basic support for brain/time playback in `_TimeViewer`. It's still a work in progress since for now only a simple call to `set_time_point()` is done every second with an increment of `playback_speed`. I had to modify the UI as well to make room for this new slider. Playback is started/stopped with the shortcut `t`.
**ToDo**
---
**Screenshot**
**Animation**
*(`t` is pressed twice to start and stop the playback)*
> MRG: Add support for playback in time_viewer

- mne/viz/_brain/_brain.py
- mne/viz/_brain/_timeviewer.py
- mne/viz/_brain/tests/test_brain.py
This PR starts the work on `hemi=split`. Let's go incrementally on this one. For now I put all the controls on the first view.
Using `plot_visualize_stc.py` with `hemi=split`:
The zoom between the views is not linked, that would be nice to have I think.
**ToDo**
> MRG: Add support for hemi=split in time_viewer

- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/_timeviewer.py
- mne/viz/_brain/tests/test_brain.py
This PR adds support for `auto_scaling` to `_TimeViewer`. It can be enabled by pressing the shortcut `t`. This is still a prototype and I was wondering what would be the best UX actually:
1) Is it more like a 'auto-mode' *(toggle event)*:
* Pressing 'auto-scaling' enables 'auto-mode'
* During playback, the scaling is updated at each step
* If the user modifies the `clim`  values given automatically, they snap back to the detected values
2) Or more like 'help me find a good start' *(action event)*:
* Pressing 'auto-scaling' changes the values
* During playback, the current values are used, no auto-scaling is done
* If the user modifies `clim`, it will be updated accordingly
> MRG: Add support for auto_scaling in time_viewer

- mne/viz/_brain/_brain.py
After merging #7219, the API to fetch hemi data has changed in `_Brain`. The result is that although the values for the `auto-scaling` are correct, the colorbar is not changed. This PR updates the old method used in `update_auto_scaling()`.
Before | PR
----------|------
> FIX: Fix actor getting fetched from hemi data

- doc/changes/latest.inc
- mne/evoked.py
- mne/io/proj.py
- mne/utils/docs.py
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
Continuation of [topomap extrapolation pull request](GH-5754).
This adds a `border` argument to `mne.viz.plot_topomap` that allows to change the values set to extrapolation points. The default is zero, just as before, but `'mean'` allows to extrapolate to mean of channels that are neighbours to given extrapolation point. See the example below:
(I know, I will have to fix the channel positions after the recent changes to plot_topomap channel position handling)
`border='mean'` is especially useful when plotting log-power (and setting `vmin`, `vmax`):
This is a draft at this point, but feel free to comment.
> MRG+1, ENH: add border argument for topomap extrapolation

- doc/changes/latest.inc
- examples/visualization/plot_montage.py
- mne/channels/_standard_montage_utils.py
- mne/channels/montage.py
There was a bug in the standard montage reader that read easycap-M1 even when `easycap-M10` was specified.
While investigating I also noticed that the `DigMontage.plot` default parameters don't agree with the documentation, below I changed the default parameters to match the docs (since the docs do agree with the default parameters of `plot_montage()`).
> [MRG] FIX: read easycap-M10 montage

- mne/viz/backends/_pyvista.py
This PR delegates the notebook environment detection to the 3d backend instead of using unreliable internal routine `_check_notebook()`.
Fixes https://github.com/mne-tools/mne-python/issues/7239.
> Delegate notebook detection to PyVista

- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
This PR delays `_check_hemi()` to allow the user to pass `label=filepath`.
Closes #7234
> Allow label=filepath in add_label for _Brain

- mne/viz/_brain/_timeviewer.py
This PR fixes the support of `hemi=both` for the `_TimeViewer`. I also ported the patch from #7227.
Closes #7250
> FIX: Add support for hemi=both in _TimeViewer

- mne/viz/_3d.py
This PR follows https://github.com/mne-tools/mne-python/issues/7250#issuecomment-578122285 and updates the documentation of `hemi` in `plot_source_estimates()` (which in turn will affect `stc.plot()`). Hopefully it's clearer now.
It's an item of https://github.com/mne-tools/mne-python/issues/7162
> MRG: Update stc.plot documentation about hemi

- doc/changes/latest.inc
- mne/beamformer/_compute_beamformer.py
- mne/beamformer/_dics.py
- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_dics.py
- mne/beamformer/tests/test_lcmv.py
- mne/utils/docs.py
Closes #5880.
@agramfort `reduce_rank=True` was still only implemented for `pick_ori == 'max_power' and weight_norm is not None`. This adds support for the other modes, plus a sanity check on the gain matrix directly rather than relying on `linalg` functions to fail.
@britta-wstnr @wmvanvliet it would be good if you could take a look.
> MRG, ENH: Extend reduce_rank=True support and better deficiency check

- examples/visualization/plot_evoked_topomap.py
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
@larsoner
That was the tiny bug that caused sphere not being of requested radius. The `sphere` variable was not passed to `_find_topomap_coords`.
Now it looks a bit better:
but the extrapolation is still not correct. I will check in a while, maybethe `sphere` is not passed also to some extrapolation functions?
> FIX: fix sphere radius in topomap

- doc/changes/latest.inc
- mne/decoding/search_light.py
- mne/decoding/tests/test_search_light.py
As of https://github.com/scikit-learn/scikit-learn/pull/15274 it should be possible (and correct?) to be able to use `roc_auc` with multiclass problems, provided you use `ovo` scoring.
@agramfort let me know if this is incorrect, or if it's still not advisable. I am somewhat naively using `roc_auc_ovo_weighted` for my multiclass one-vs-rest classification...
> MRG, ENH: Allow using multiclass roc_auc

- mne/viz/evoked.py
- mne/viz/topomap.py
Fixes a `picker` deprecation and that there is no need to pass `cmap` because it's part of `im`.
> MRG, MAINT: Fixes for matplotlib deprecations

- mne/viz/_brain/_brain.py
- mne/viz/_brain/_timeviewer.py
This PR updates the slider time label instead of the default time actor. It improves consistency so now the size of the time label scales with the window size.
**Known issue**
> MRG: Update time slider label

- mne/viz/_brain/tests/test_brain.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/renderer.py
- mne/viz/tests/test_3d.py
This PR prevents setting `pyvista.OFF_SCREEN` globally (*i.e.* in tests, ... etc) by managing a renderer `MNE_3D_OFF_SCREEN` variable instead.
Also, before #7266, the [tests were done offscreen by default](https://github.com/mne-tools/mne-python/pull/7266/files#diff-7d015438f1f32b2f4c28f713c2e3e7b1L130) with `_use_test_3d_backend()` so this PR fixes this.
This variable is still set globally in `_testing_context()` (this one restores the original value) and in the `doc` which is fine by me.
> MRG: Refactor OFF_SCREEN variable

- doc/changes/latest.inc
- mne/channels/channels.py
- mne/channels/tests/test_channels.py
We should return `self` from these methods as usual.
> MRG, BUG: Return self from methods

- mne/conftest.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/renderer.py
- mne/viz/tests/test_3d.py
@GuillaumeFavelier I think that in theory this should be equivalent to what is in `master` but cleaner because it uses a `contextmanager`.
> MRG, MAINT: Use context manager for tests

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/viz/topomap.py
When plotting the topography of a TFR, planar gradiometers were automatically being combined using the RMS of both sensors. However, since TFRs are not sensitive to the direction of a dipole, this behavior is unexpected. Furthermore, this makes it impossible to see "negative" power when comparing the difference between two conditions. After computing power / TFRs, planar gradiometers should be combined by taking the mean, not the RMS.
This commit changes topoplots to combine planar grads using mean, not RMS, for TFR and PSD.
This page explains a similar analysis in Fieldtrip: http://www.fieldtriptoolbox.org/example/combineplanar_pipelineorder/
> Bugfix: Combline planar grads for TFR with mean, not RMS

- mne/surface.py
- mne/viz/_brain/surface.py
this PR fixes the `load_curvature()` function of the `_Brain` object.
`master` | PR
----------|-------
> FIX,VIZ: Update read_curvature

- doc/changes/latest.inc
- mne/gui/_coreg_gui.py
- mne/gui/_marker_gui.py
- mne/gui/_viewer.py
- mne/gui/tests/test_coreg_gui.py
Closes #7254
@zuxfoucault can you confirm this fixes your problem?
The fix I came up with with was just to set `_nearest_calc_default` to actually use the processed points. The `ArrayOrNone` changes are just to help us ensure that we don't use values before we should, and thankfully they do not break anything at least in local testing.
> MRG, FIX: Fix bug with update

- examples/inverse/plot_lcmv_beamformer_volume.py
- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/colormap.py
- mne/viz/tests/test_3d.py
- tutorials/source-modeling/plot_mne_dspm_source_localization.py
- tutorials/source-modeling/plot_visualize_stc.py
- tutorials/stats-source-space/plot_stats_cluster_spatio_temporal.py
Refactors `_limits_to_control_points` into a new, slightly simpler `_process_clim` that should round-trip correctly. It now just takes `clim, colormap, transparent, data, allow_pos_lims` and returns a dict with keys`'clim', 'colormap', 'transparent'`. `data` is only used with `clim='auto'` and `kind='percent'`, and `allow_pos_lims` should be fixed for a given plot type (always `True` except for vector source estimates IIRC). I touched a few examples that use `stc.plot` to see if they look okay.
@GuillaumeFavelier there is probably lots of refactoring to be done at the `_Brain` end, e.g.:
- it looks like there is some duplicated `fmin/fmid/fmax` handling for example
- in principle we should not need to require `fmin < fmid` but just `fmin <= fmid` (see `XXX` in the code)
- you can probably …
> MRG, MAINT: Refactor clim handling

- mne/viz/_brain/_brain.py
- mne/viz/backends/renderer.py
- mne/viz/backends/tests/test_renderer.py
This PR changes the API of renderer so that the private `_reload_backend()` only reloads the given backend and `get_3d_backend()` always returns a valid backend name (to avoid getting  `None` for example). It also limits the amount of backend reloads to the bare minimum:
scenario |`master` | PR
----------|---------------|-------
example.py | Using mayavi 3d backend.<br>Using mayavi 3d backend. | Using mayavi 3d backend.
with `use_3d_backend('pyvista')` | Using pyvista 3d backend.<br>Using pyvista 3d backend.<br>Using mayavi 3d backend.<br>Using mayavi 3d backend. | Using mayavi 3d backend.<br>Using pyvista 3d backend.<br>Using mayavi 3d backend.
with `set_3d_backend('pyvista')` | Using pyvista 3d backend.<br>Using pyvista 3d backend. | Using pyvista 3d backend.
with …
> Refactor reload_backend()

- doc/changes/latest.inc
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
Currently doing `epochs.plot_sensors(kind='select')` and lasso-selecting some channels leads to selected channels not being clearly distinguishable:
I've added changes to edgecolors with lasso selection to make the channels more visible:
> [MRG] ENH: better sel channels visibility

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/epochs.py
- mne/viz/epochs.py
- mne/viz/tests/test_epochs.py
Makes epochs.plot() start at 0 instead of 1 (issue #7260). 
Note: a bug with spyder (#6528) prevents me from testing what happens after closing the interactive plot. I checked that the indices returned for manually selected epochs start with 0, too. 
Closes #7260
> MRG, FIX: make labels in epochs.plot start at 0, fixes issue #7260

- doc/changes/latest.inc
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
When testing code for `border='auto'` PR (as previously discussed with @larsoner, BTW I'll submit it soon) I found a small funny bug:
in `plot_topomap` with 3 channels extrapolations points were sometimes placed inadequately (red: original points, green: extrapolation points:
This was because all n_channels==3 cases were treated as colinear (this, in turn, was a quick hack for Delaunay needing more than 3 points to work) even when the 3 channels were not colinear. This incorrect placement of extrapolation points can lead to `border='mean'` not working because some extrapolation points may no longer have any original points as neighbours (only other extrapolation points). Now extrapolation points too close to original points are removed in `n_channels==3` case and the `border='mean'` error …
> [MRG+1] FIX: extra points placement when 3 channels

- doc/changes/latest.inc
- doc/overview/roadmap.rst
- mne/dipole.py
- mne/tests/test_dipole.py
- Adds `rank` argument to control rank when using whitening in dipole fitting
- I realized a link to #4859 was missing from the roadmap so I snuck it in here
> MRG, ENH: Add rank to fit_dipole

- mne/forward/forward.py
- mne/io/ctf/trans.py
- mne/io/curry/curry.py
- mne/io/curry/tests/test_curry.py
- mne/surface.py
- mne/tests/test_docstring_parameters.py
- mne/tests/test_surface.py
- mne/utils/check.py
Our curry reader currently does not populate `info['chs'][ii]['loc']`, `info['dig']`, or `info['dev_head_t']` properly. 
@DiGyt did you try to do any source localization, `plot_sensors`, etc. with the curry reader?
1000 nAm current phantom results have 2.1 mm error, 99%+ GOF:
Todo:
Closes #7300
> MRG, FIX: Fix curry reader

- mne/viz/_brain/_timeviewer.py
- mne/viz/utils.py
This PR adds a `matplotlib` figure to display help. The shortcut is `h`:
Closes https://github.com/mne-tools/mne-python/issues/7268
> WIP: Add help window to the _TimeViewer

- doc/changes/latest.inc
- mne/epochs.py
- mne/evoked.py
- mne/io/base.py
- mne/io/edf/tests/test_edf.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/source_estimate.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
- mne/tests/test_source_estimate.py
- mne/utils/__init__.py
- mne/utils/check.py
- mne/utils/dataframe.py
- mne/utils/docs.py
closes #7179 
cc @jona-sassenhagen @dengemann @choldgraf @larsoner @agramfort
> MRG, FIX, ENH: overhaul to_data_frame method

- environment.yml
- mne/viz/_brain/_timeviewer.py
- requirements.txt
This PR updates the package requirements for the pyvista 3d backend.
> Use latest version 0.23.1 of pyvista instead of master

- mne/preprocessing/tests/test_scalp_coupling_index.py
Fixes issue raised in #7180 .
This test was intermittently failing see #7180 
The test was assuming that random noise would be correlated less than 0.5, but sometimes by chance this happens.
> MRG, FIX: Fix scalp coupling index test that intermittently failed

- mne/conftest.py
This PR tries to reproduce recent Travis failure on https://github.com/mne-tools/mne-python/pull/7247:
```
DeprecationWarning: 'TraitTuple' trait handler has been deprecated. Use Tuple instead.
```
Reference:
https://travis-ci.org/mne-tools/mne-python/jobs/650433990?utm_medium=notification&utm_source=github_status
> TST: Deprecation warning: 'TraitTuple'

- mne/epochs.py
- mne/evoked.py
- mne/io/base.py
- mne/source_estimate.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
- mne/utils/__init__.py
- mne/utils/dataframe.py
- mne/utils/docs.py
This PR adds a proper deprecation cycle to the API changes in #7206 
It also restores parameter order to more closely match what it used to be, to minimize downstream code breakage with positional argument passing.
> API: properly deprecate changes in to_data_frame

- doc/changes/latest.inc
- mne/preprocessing/ica.py
- mne/preprocessing/infomax_.py
- mne/preprocessing/tests/test_infomax.py
Add `return_n_iter` kwarg to `infomax()`
Allows retrieval of the number of iterations performed. If `False` (default), only the ICA weights are returned. If `True`, returns a tuple `(weights, n_iter)`.
Previous behavior of `infomax()` is not altered.
> Add return_n_iter kwarg to infomax()

- .circleci/config.yml
- .travis.yml
- azure-pipelines.yml
- mne/forward/forward.py
- mne/minimum_norm/tests/test_inverse.py
- mne/surface.py
I noticed in https://travis-ci.org/mne-tools/mne-python/jobs/650978029?utm_medium=notification&utm_source=github_status that a lot of time was spent in:
```
115.44s call     mne/inverse_sparse/tests/test_mxne_inverse.py::test_mxne_inverse_standard
```
Profiling suggests that about half the time was spent in `convert_forward_solution`, and a lot of that was in `_normal_orth`, so this might be a speed regression due to #7290.
In any case, this PR takes that test from 23 sec to 14 sec on my system. Timings for `mne/tests/test_chpi.py` don't change, so the n-dim generalization that this makes use of seems to be not so painful for the single vector case.
> MRG, ENH: Speed up convert_forward_solution

- doc/changes/latest.inc
- mne/datasets/utils.py
- mne/io/fieldtrip/fieldtrip.py
- mne/io/fieldtrip/tests/test_fieldtrip.py
- mne/io/fieldtrip/utils.py
Fixes #7293 
This PR fixes two bugs found when investigating #7293:
1. The error message returned when the data structure is a cell array was not intuitive.
2. When a channel was not present in the `info` object but in the loaded evoked data, the function would crash.
> [MRG] Fix handling of cell arrays and loading of evoked mat files when channels are not in info

- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/chpi.py
- mne/coreg.py
- mne/inverse_sparse/tests/test_mxne_inverse.py
- mne/io/ctf/trans.py
- mne/preprocessing/tests/test_xdawn.py
- mne/source_estimate.py
- mne/tests/test_transforms.py
- mne/transforms.py
- mne/utils/tests/test_numerics.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
When implementing the cHPI changes, I noticed some places that our use of matched-point fitting could be improved. Specifically:
1. `mne coreg` uses matched point fitting in ICP. This now routes the code to use the analytical solution when possible.
2. This required implementing `_quat_to_euler` and `_euler_to_quat` from standard formulas.
3. Implementing the `mne coreg` caused me to look back at the ICP ref, then the original ref for the analytical transform, and realize that 1) it can include weights, and 2) it can compute a uniform scale factor, too. So I implemented those, which expanded the use cases for `mne coreg`.
4. `mne.io.ctf` computed some transforms using its own matched point code, and also its own RAS-to-head. These now use transforms from `mne.transforms` instead.
So there …
> MRG, MAINT: Refactor and unify matched-point fitting

- doc/changes/latest.inc
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
The changes in this PR enable the user to retrieve the number of completed ICA iterations via `ICA.n_iter_` after `ICA.fit()` has been called. <strike>Currently only works with FastICA and Picard (will always be `None` for Infomax)</strike>
> Expose number of ICA iterations as ICA.n_iter_

- mne/viz/backends/_pyvista.py
This PR is a follow-up of https://github.com/mne-tools/mne-python/pull/7330#issuecomment-587441394 and disables completely depth peeling in the pyvista 3d backend without doing any window testing.
> WIP: Disable depth peeling with rcparams

- doc/changes/latest.inc
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- Fixes: `ICA.fit_params` used not to be written to disk on `ICA.save()`
- Optimizes: `ica_init` used to be written to disk twice
> BF: Write ICA.fit_params to disk on ICA.save()

- doc/changes/latest.inc
- mne/viz/misc.py
- mne/viz/tests/test_misc.py
- tutorials/intro/plot_10_overview.py
On `master` when you provide `event_id` to `plot_events` you get:
But then if you omit `event_id` you lose event count information:
This PR makes it so that this information is restored:
The other option (instead of having a legend) would be to just print the counts to the right of each row, but this seems more consistent with the `event_id` case (we'd probably want to change that to also have the counts to the right, then why have the legend at all, etc.).
This PR also fixes the ordering of the legend to match the top-to-bottom ordering of the actual events themselves.
> MRG, ENH: Always show event counts

- tutorials/preprocessing/plot_40_artifact_correction_ica.py
This fixes a doc rendering issue for narrow screens in the ICA tutorial, introduced by #7331. Before this PR:
After this PR:
> DOC: fix sidebar clash in ICA tutorial

- doc/changes/latest.inc
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
<strike>Removes the `mne.preprocessing.ica.run_ica()` function. All it does it instantiate an `ICA` object and then run an artifact detection. However, the same can be achieved by using `ICA.detect_artifacts()`.</strike>
Deprecates `mne.preprocessing.ica.run_ica()` in favor of `ICA.detect_artifacts()`
> Deprecate run_ica()

- mne/preprocessing/nirs/__init__.py
- mne/preprocessing/nirs/nirs.py
- mne/preprocessing/tests/test_nirs.py
FNIRS channels that had been marked as bad were not being converted. I think all channels should be converted to the final hbo/hbr, then the downstream processing can choose what to do with bad channels.
Adds two internal function for checking that nirs channel labelling of bads is consistent. And nother function that spreads bad marking to ensure it is consistent.
> WIP: Use all channels in fnirs conversion. Don't exclude bads

- doc/_includes/channel_interpolation.rst
- doc/_includes/inverse.rst
- doc/_includes/ssp.rst
- doc/overview/implementation.rst
- doc/overview/matlab.rst
- doc/references.bib
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
~~Working on making eLORETA have units nAm.~~
~~Along the way~~ Writing out some of the inverse derivations and adding equation links so that they are hopefully easier to follow.
~~This does not work, mostly opening PR so that @agramfort can look at where I've messed up the math :)~~
> MRG, DOC: Inverse math

- azure-pipelines.yml
- mne/viz/tests/test_3d.py
Every PR is red because of Azure. I'm going to try:
1. Skipping the `plot_vector_source_estimates` test since it seems to show up in [the tracebacks](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=5634&view=logs&j=b195a6e3-7484-5943-e627-0b35c27605d6&t=6dcb3581-08d4-5e76-74f2-6edaf20ff912&l=257).
2. Removing `mayavi` and `PySurfer` from the Azure builds.
I hope that (1) is enough because (2) is drastic, but we should get Azure green for most PRs and work on fixing this annoying bug separately.
> MAINT: Disable problematic test on Azure

- mne/viz/backends/renderer.py
- mne/viz/tests/test_3d.py
Okay I remember why I went with `_get_renderer` (which was removed in #7292). @GuillaumeFavelier this code snippet:
```
import mne
mne.viz.create_3d_figure((800, 600))
```
gives:
```
File "/Users/larsoner/Desktop/bug.py", line 2, in <module>
mne.viz.create_3d_figure((800, 600))
File "/Users/larsoner/python/mne-python/mne/viz/backends/renderer.py", line 245, in create_3d_figure
renderer = _Renderer(fig=handle, size=size, bgcolor=bgcolor)  # noqa: F821
NameError: name '_Renderer' is not defined
```
We don't hit this in tests (and CircleCI) probably because by the time we call a `create_3d_figure` we have already done a `stc.plot` or something else that would have loaded a backend (or tried to load the given backend in a `pytest` way).
The simplest fix is …
> MRG, BUG: _Renderer not found

- mne/viz/_brain/_timeviewer.py
This PR removes the `Tools` menu in the `_TimeViewer` interface as suggested in https://github.com/mne-tools/mne-python/pull/7247#issuecomment-589599734
The removed menu presented options for default picking in PyVista which are not compatible with https://github.com/mne-tools/mne-python/pull/7247 and can be misleading (https://github.com/mne-tools/mne-python/pull/7247#issuecomment-588279423 and https://github.com/mne-tools/mne-python/pull/7247#issuecomment-587833079)
> Remove Tools menu in _TimeViewer

- mne/viz/circle.py
- mne/viz/utils.py
Just some minor tweaks to the documentation based on feedback I got here from colleagues.
It seems there is a bit of inconsistency as to what kind of colormap arguments some functions accept. Might be worthwhile for someone to follow up on this and make sure colormap takes both `str` and `colors.LinearSegmentedColormap` everywhere. In this function, it just seems to be a documentation issue though
> DOC: tweaks to colormap documentation

- mne/stats/cluster_level.py
- mne/stats/tests/test_cluster_level.py
Cleans up some error messages related to `stat_fun`. IIRC someone had a problem with this on the mailing list, and at some point I forgot to put a `return val` in my custom `stat_fun` and got a weird error about `None`.
No need for `latest.inc` update because this just makes error messages better.
> MRG, BUG: Cleaner error messages about stat_fun

- mne/viz/_brain/_timeviewer.py
This PR fixes the default time value for `_TimeViewer`. The diff is very short, a connection with the slider was missing.
Closes #7379 
> Fix initial_time in _TimeViewer

- mne/utils/fetching.py
- mne/utils/tests/test_fetching.py
In maybe 10% of PRs we get sporadic failures downloading the test data or in `test_constants.py` [of the form](https://travis-ci.org/mne-tools/mne-python/jobs/657984986):
```
RuntimeError: URL could not be parsed properly (total size 1030996061 != file size 1)
```
I could replicate it locally by running `pytest mne/io/tests/test_constants.py` a lot (like 10-20 times) -- I'd see the failure every once in a while.
This has to do with our not handling `chunked` data protocol properly. The chunked protocol causes the `headers['Content-Length']` to be None/missing, which we currently treat as a file size of `1` but then later don't handle properly. We can and should still read data even if we don't know the total size rather than fail out. This PR simplifies a lot of the logic in our …
> MRG, FIX: Fix fetching bugs

- mne/viz/_brain/_timeviewer.py
This PR fixes the overlap of the sliders when `hemi=both`. 
> Fix orientation slider when hemi=both

- doc/changes/latest.inc
- doc/glossary.rst
- doc/overview/roadmap.rst
- doc/python_reference.rst
- examples/inverse/plot_evoked_ers_source_power.py
- examples/inverse/plot_mne_cov_power.py
- mne/inverse_sparse/_gamma_map.py
- mne/inverse_sparse/mxne_inverse.py
- mne/minimum_norm/__init__.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
- mne/utils/docs.py
Here we go: a candidate for a future ```apply_inverse_cov``` function that gets us source power by projecting the data covariance.
Feel free to edit!
cc @larsoner @britta-wstnr @wmvanvliet
> MRG/ENH: apply_inverse_cov

- tutorials/source-modeling/plot_forward.py
- tutorials/source-modeling/plot_mne_dspm_source_localization.py
@drammock okay for you? It turns out that the `np.eye(n_sources)` was causing ~500 MB of mem usage (`8192 ** 2 * 8 = 536870912`) so just making a comment about it should fix our recent CircleCI failures, as in local testing it goes from ~2100 MB in `master` down to ~1500 MB in this PR.
> MRG, MAINT: Decrease memory usage of plot_forward.py

- mne/viz/_brain/_timeviewer.py
- mne/viz/_brain/tests/test_brain.py
This PR adds a shortcut `c` to clear all traces, the help window is also updated.
Here is an animation with `show_traces='separate'`:
> Add clear_points in _TimeViewer

- mne/preprocessing/maxwell.py
> DOC: Fix typo

- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
This PR fixes the window title of `_TimeViewer`. The diff is very short, the `title` parameter was not passed to `_get_renderer()`.
> Fix window name in _TimeViewer

- mne/viz/_brain/_brain.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/base_renderer.py
- mne/viz/backends/tests/test_renderer.py
This PR fixes the `focalpoint` issue when `hemi='both'` in _TimeViewer. It should be placed between the hemispheres.
`master`  | PR
------------|------
> MRG: Add reset_camera() primitive in _Renderer

- mne/preprocessing/bads.py
- mne/preprocessing/ica.py
- mne/tests/test_docstring_parameters.py
This function appears never to have been meant to be public, let's explicitly make it private.
I'm not entirely sure we even need to bother with a deprecation cycle here but I'm putting it in to be safe. I didn't add a `latest.inc` update, though, as it seems unnecessary in this case, but I can add it if others disagree.
> MRG, API: Remove function meant to be private

- environment.yml
Anaconda now has a newer VTK (8.2) than pip (8.1.2), so let's use it. It's possible that this might fix some depth buffer problems for people -- @bloyl you had an issue open about this #7107, it's possible 8.2 already fixes the problem if you feel like trying it.
> MRG, MAINT: Use VTK 8.2

- doc/changes/latest.inc
- doc/python_reference.rst
- mne/annotations.py
- mne/filter.py
- mne/preprocessing/__init__.py
- mne/preprocessing/flat.py
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
- mne/utils/docs.py
- tutorials/preprocessing/plot_60_maxwell_filtering_sss.py
At the sprint @olafhauk mentioned that not having `-autobad` support was what he was missing in his Python pipeline. This adds support for it.
> MRG, ENH: Add autobad detection like MF

- mne/viz/_brain/_brain.py
- mne/viz/backends/_pyvista.py
This PR follows https://github.com/mne-tools/mne-python/pull/7382 and unifies the behaviour of the `title` parameter of `_Brain`.
It's of course still possible to add a title string label with `set_3d_title()`.
> MRG: Set _Brain window title

- doc/changes/latest.inc
- mne/evoked.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
- Some places we have the param named `figure` and others `fig`, `fig` seemed the most appropriate/consistent here.
- The OSX tests have been timing out a lot recently, so I marked a couple of the [very slow ones](https://travis-ci.org/mne-tools/mne-python/jobs/658602912) so that they don't run there anymore.
- Adds a `float` to the `np.array` in our clim-processing code, which can help catch silly errors earlier with clearer messages.
> MRG, ENH: Add fig kwarg to `plot_evoked_field`

- doc/_static/style.css
- doc/_templates/layout.html
Allows long API titles like `mne.minimum_norm.source_induced_power` to wrap.
A [better solution](https://stackoverflow.com/questions/23107990/word-wrap-on-non-alphabetical-character) would be to change `autosummary` to put each `X.`/`Y.` of `X.Y.Z` in a separate `span`, then you can make it break on the periods. But this is a lot more work for a marginal benefit.
> MRG, STY: Allow wrapping long API lines in HTML

- doc/changes/latest.inc
- mne/stats/multi_comp.py
- mne/stats/tests/test_multi_comp.py
Fixes GH-7354.
Clips p-values produced by Bonferroni correction at 1.0
> Ensure corrected p-values are always <= 1.0

- doc/changes/latest.inc
- mne/viz/tests/conftest.py
- mne/viz/tests/test_topo.py
- mne/viz/tests/test_topomap.py
- mne/viz/topo.py
- tutorials/preprocessing/plot_70_fnirs_processing.py
Adding general NIRS support #7057 
Allows plotting of evoked topo map for nirs data
> MRG: Add nirs support to plot_evoked_topo

- doc/changes/latest.inc
- mne/beamformer/_compute_beamformer.py
As discussed in https://github.com/mne-tools/mne-python/pull/7168, the option `reduce_rank=True` does not behave as one might expect:
The code is actually not implementing lead field rank reduction but reducing the rank of the denominator of the beamformer formula.
This PR fixes this, and completely swaps the old rank reduction for the lead field one.
Tests are left to fail for first round, so we can see what will change with this in place.
> FIX: Fix rank reduction for beamformers

- doc/conf.py
Workaround for PyVista scraping. @GuillaumeFavelier feel free to look and decide if it needs a backport (not sure what the PyVista scraper duplication status is). All I really did was add the `if plotter in seen_plotters:` check and accumulation and it appears to fix things.
Alternative to #7398
Closes #7398
Closes #7228
> MRG, MAINT: Work around PyVista rendering bug

- doc/conf.py
- mne/source_estimate.py
- mne/utils/docs.py
gives (hopefully) better explanation for the various `mode` options; converts func & method to use docdict along the way.
> DOC: improve docstring for extract_label_time_course

- doc/changes/latest.inc
- mne/annotations.py
- mne/conftest.py
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
- mne/utils/check.py
Closes #7415.
Also modernizes the BV tests a bit.
@tvanasse feel free to test to see if it fixes your problem. Locally this now works for me:
```Python
import mne
file = mne.io.read_raw_brainvision('Scan_2_EPI_MB.vhdr')
custom_montage = mne.channels.read_custom_montage('BC-MR-32-X3.bvef')
```
> MRG, FIX: Fix BrainVision reader headers

- mne/channels/layout.py
- mne/datasets/utils.py
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
Alternative approach to #7410 as suggested by @larsoner 
If nirs channels are too close for the topoplot to represent then those channels are combined by taking the mean.
Initial attempt. No tests yet, just looking for feedback to see if I am on the right path. But this works on my data.
> MRG: Take mean of nirs channels that are too close for topoplot

- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
Fixes #7421.
I wanted to include a test, so I checked if an existing EDF file has a `LP: 0Hz` entry in its header. Indeed, it seems like `test_edf_stim_resamp.edf` does have this entry, but I get
```
RuntimeWarning: 24 channel names are too long, have been truncated to 15 characters:
['EEG LDAMT_01-REF', 'EEG LDAMT_02-REF', 'EEG LDAMT_03-REF', 'EEG LDAMT_04-REF', 'EEG LDAMT_05-REF', 'EEG LDAMT_06-REF', 'EEG LDAMT_07-REF', 'EEG LDAMT_08-REF', 'EEG LDPMT_01-REF', 'EEG LDPMT_02-REF', 'EEG LDPMT_03-REF', 'EEG LDPMT_04-REF', 'EEG LDPMT_05-REF', 'EEG LDPMT_06-REF', 'EEG LDPMT_07-REF', 'EEG LDPMT_08-REF', 'EEG RDAMT_01-REF', 'EEG RDAMT_02-REF', 'EEG RDAMT_03-REF', 'EEG RDAMT_04-REF', 'EEG RDAMT_05-REF', 'EEG RDAMT_06-REF', 'EEG RDAMT_07-REF', 'EEG RDAMT_08-REF']
```
Which means that I get a …
> Fix EDF lowpass filter value of 0Hz

- mne/viz/raw.py
It is hard to see the location of the currently visible time segment in the overview bar (x scroll bar), so I increased the line width.
Before:
After:
> Make current time window more obvious

- .travis.yml
- environment.yml
- requirements.txt
This PR skips `pytest 5.4.0` because of the issues with `pytest-sugar`.
Closes https://github.com/mne-tools/mne-python/issues/7437
> MNT: Exclude pytest 5.4.0

- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
closes #7426 
Also removes `u"` at beginning of docstrings in the edited file.
It turns out that `pysurfer.Brain` doesn't really check size at all:
https://github.com/nipy/PySurfer/blob/master/surfer/viz.py#L557-L561
So I just did what seemed sensible to me.
> handle _Brain size gracefully with pyvista

- mne/annotations.py
- mne/tests/test_annotations.py
Fixes #7429.
Before (94 characters):
```
<Annotations  |  14 segments : a (1), b (1), c (1)..., orig_time : 2013-11-04 14:35:26.150000>
```
After (76 characters):
```
<Annotations | 14 segments: a (1), b (1), c (1), d (1), e (1), f (1), g ...>
```
> Shorten repr of Annotations if necessary

- .travis.yml
- environment.yml
- requirements.txt
Pytest 5.4.1 is out and we didn't exclude it (still not working).
> Don't use pytest 5.4

- mne/annotations.py
- mne/io/base.py
- mne/io/tests/test_raw.py
- mne/tests/test_annotations.py
Just like #7441 did for `Annotations`, this PR makes the repr of `Raw` objects a bit shorter.
Before (93 characters):
```
<RawEDF  |  S001R04.edf, n_channels x n_times : 64 x 20000 (125.0 sec), ~9.9 MB, data loaded>
```
After (68 characters):
```
<RawEDF  |  S001R04.edf, 64 x 20000 (125.0 s), ~9.9 MB, data loaded>
```
> [MRG] Shorter raw repr

- mne/preprocessing/maxwell.py
- mne/preprocessing/otp.py
- mne/preprocessing/tests/test_maxwell.py
- mne/preprocessing/utils.py
- mne/viz/raw.py
- tutorials/preprocessing/plot_60_maxwell_filtering_sss.py
Moves the filtering step out of `find_bad_channels_maxwell`. This makes our outputs differ from MaxFilter a bit more, but:
1. It is better in principle (and practice) to filter all the data, then process in chunks, rather than filter each chunk independently (more edge artifacts)
2. By moving the filtering out of the function, it allows the user to choose the filtering tradeoffs
3. Based on inspecting the results with @hoechenberger , it seems like we do at least as well on this PR as we do in `master`
This PR also make a couple of tweaks found while working on this:
1. Improves `verbose=True` and `verbose='debug'` output messaging
2. Cleans up how `raw.plot` filtering triages FIR vs IIR to match what `mne/filter.py` does (leads to better `padlen` in `raw.plot`)
3. Cleans up unused var in …
> WIP, FIX: Offload filtering step for find_bad_channels_maxwell

- mne/viz/_brain/_brain.py
- mne/viz/_brain/_timeviewer.py
This PR adds a vertical line to indicate the current time on the `matplotlib` canvas.
I also did quite the refactor there as `_TimeViewer.__init__` was getting too long.
> MRG: Link _TimeViewer time slider with vertical time line

- mne/externals/decorator.py
- mne/filter.py
- mne/forward/forward.py
- mne/inverse_sparse/mxne_inverse.py
- mne/io/base.py
- mne/io/cnt/cnt.py
- mne/io/ctf/ctf.py
- mne/io/edf/edf.py
- mne/io/kit/kit.py
- mne/minimum_norm/spatial_resolution.py
- mne/preprocessing/ica.py
- mne/source_space.py
- mne/utils/__init__.py
- mne/utils/_logging.py
- mne/utils/config.py
- mne/utils/misc.py
- mne/utils/tests/test_config.py
- mne/utils/tests/test_logging.py
Simplifies our `verbose` wrapping a little bit. Checked that `import mne` times are unchaged. Achieves a couple of things:
1. Cleans up tracebacks by removing one level of depth.
<details>
master
```
larsoner@bunk:~/Desktop/richard$ python -ui find_bads.py 
^CTraceback (most recent call last):
File "find_bads.py", line 21, in <module>
test()
File "find_bads.py", line 14, in test
bads = mne.preprocessing.find_bad_channels_maxwell(
File "</home/larsoner/python/mne-python/mne/externals/decorator.py:decorator-gen-373>", line 2, in find_bad_channels_maxwell
File "/home/larsoner/python/mne-python/mne/utils/_logging.py", line 89, in wrapper
return function(*args, **kwargs)
File "/home/larsoner/python/mne-python/mne/preprocessing/maxwell.py", line 1901, in 
find_bad_channels_maxwell …
```
> MRG, ENH: Better introspection for optimization

- doc/changes/latest.inc
- mne/io/fiff/raw.py
- mne/io/fiff/tests/test_raw_fiff.py
In `mne/io/fiff/raw.py` we iterate over tags to figure out which ones to read. This will slow down as you access data later and later in the file, so a better strategy is to construct arrays of starts/stops and then figure out which tags to read based on that (a simple `searchsorted` or even `np.where` will yield the answers). 
First step is then to refactor the reading function to "reformat raw_extras to be a dict of list/ndarray rather than list of dict (faster access)", which is done here. Hopefully all is green and we can move on to the speedup part.
At least `pytest mne/io` works locally...
This should in the end be pretty straightforward so we can get it into 0.20.
Closes #7436
> MRG, ENH: Raw data reading refactor

- mne/viz/tests/test_3d.py
This short PR follows the tests on https://github.com/mne-tools/mne-python/pull/7294 and modifies `test_mixed_sources_plot_surface` to use the `renderer` fixture. I also removed `garbage_collect` according to https://github.com/mne-tools/mne-python/pull/7294#discussion_r391942199 advice
> MRG: Use the renderer fixture in test_mixed_sources_plot_surface

- doc/changes/latest.inc
- mne/utils/numerics.py
- mne/utils/tests/test_numerics.py
Required for mne-tools/mne-study-template#57
Raises when an empty sequence was passed, and emits a warning when a sequence of length 1 was passed.
Previous behavior was to always assert a length >1.
This is required to implement mne-tools/mne-study-template#57
> ENH: Small mne.grand_average() changes

- doc/changes/latest.inc
- mne/chpi.py
- mne/tests/test_chpi.py
In principle we should be able to run `filter_chpi` to remove line frequencies even if cHPI is off. This is useful for example when processing files in batches where some have cHPI on/enabled and others don't.
> MRG, ENH: Allow just line freq filtering

- doc/changes/latest.inc
- mne/channels/layout.py
- mne/evoked.py
- mne/tests/test_evoked.py
- mne/time_frequency/tfr.py
- mne/viz/evoked.py
- mne/viz/ica.py
- mne/viz/tests/conftest.py
- mne/viz/tests/test_topo.py
- mne/viz/tests/test_topomap.py
- mne/viz/topo.py
- mne/viz/topomap.py
Ongoing fNIRS improvements for #7057 
Adds support for plotting Ica components.
> MRG: Add nirs support to ICA topoplot

- mne/epochs.py
- mne/io/array/array.py
- mne/io/proc_history.py
- mne/preprocessing/_fine_cal.py
- mne/preprocessing/maxwell.py
- mne/preprocessing/otp.py
- mne/preprocessing/tests/test_maxwell.py
- mne/preprocessing/utils.py
- mne/viz/raw.py
- tutorials/preprocessing/plot_60_maxwell_filtering_sss.py
Moves the filtering step out of `find_bad_channels_maxwell`. This makes our outputs differ from MaxFilter a bit more, but:
1. It is better in principle (and practice) to filter all the data, then process in chunks, rather than filter each chunk independently (more edge artifacts)
2. By moving the filtering out of the function, it allows the user to choose the filtering tradeoffs
3. Based on inspecting the results with @hoechenberger , it seems like we do at least as well on this PR as we do in `master`
This PR also make a couple of tweaks found while working on this:
1. Improves `verbose=True` and `verbose='debug'` output messaging
2. Cleans up how `raw.plot` filtering triages FIR vs IIR to match what `mne/filter.py` does (leads to better `padlen` in `raw.plot`)
3. Cleans up unused var in …
> MRG, FIX: Offload filtering step for find_bad_channels_maxwell

- mne/io/brainvision/tests/test_brainvision.py
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
Like #7441 (shorter `Annotations` repr) and #7443 (shorter `Raw` repr), this PR creates a much shorter `Info` repr. I really do think that printing all empty fields is not useful and makes it much harder to find information contained in the `Info` dict, so I only display non-empty values. I also consider empty lists as empty so they are not included in the repr. Furthermore, I don't need to see the types explicitly, this is mostly clear from the value (and why would I need to know that in the first place).
Before:
```
<Info | 16 non-empty fields
bads : list | 0 items
ch_names : list | Fc5., Fc3., Fc1., Fcz., Fc2., Fc4., Fc6., C5.., C3.., ...
chs : list | 64 items (EEG: 64)
comps : list | 0 items
custom_ref_applied : NamedInt | 0 (FIFFV_MNE_CUSTOM_REF_OFF)
dev_head_t : Transform | 3 items …
```
> Shorter Info repr

- examples/connectivity/plot_mne_inverse_envelope_correlation.py
- examples/connectivity/plot_mne_inverse_psi_visual.py
- examples/forward/plot_forward_sensitivity_maps.py
- mne/utils/docs.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/_timeviewer.py
An attempt to recover some commits from the rolled-back #7257. In theory this should fix CircleCI in `master`. Tests pass locally, let's see if the CIs agree. This refactors `_brain` to make several improvements:
1. `smoothing_matrix` is only used in one place
2. time interpolation is only constructed once (in one place) and reused
3. singleton dimensions are hopefully handled properly
@GuillaumeFavelier if things are green I think we should merge this, then maybe bring back the rest of #7257 ?
> MRG, FIX: Fix for singleton and efficiency

- doc/changes/latest.inc
- mne/stats/tests/test_cluster_level.py
- mne/utils/docs.py
Since we've bumped the minimum sklearn to 0.19.1, there should be no need to try/except importing from `scikits.learn` anymore.
> MRG: purge old scikits.learn imports

- doc/python_reference.rst
- mne/stats/cluster_level.py
- mne/utils/docs.py
In preparation for addressing #7463, this cleans up the docstrings for the 4 public-facing clustering functions:
- `mne.stats.permutation_cluster_test`
- `mne.stats.permutation_cluster_1samp_test`
- `mne.stats.spatio_temporal_cluster_test`
- `mne.stats.spatio_temporal_cluster_1samp_test`
remaining tasks:
> MRG, DOC: Clustering docstrings and connectivity=None

- mne/io/_digitization.py
- mne/io/cnt/cnt.py
- mne/io/fieldtrip/utils.py
- mne/io/meas_info.py
- mne/io/proj.py
- mne/io/tests/test_meas_info.py
Sometimes I find that `info.copy()` is a significant bottleneck in some operations. It turns out this can be avoided if we leverage knowledge of our internal structures and object mutability by overridding a few `__deepcopy__` defs:
1. three entries in `info` (`chs`, `ch_names`, `hpi_meas`), plus two others that affect it:
2. `DigPoint` (hence `info['dig']`)
3. `Projection` (hence `info['projs']`)
This code:
```Jupyter
import mne
fname = mne.datasets.testing.data_path() + '/SSS/test_move_anon_raw.fif'
info = mne.io.read_info(fname)
%timeit info.copy()
```
on master (top) and this PR (bottom; ~10x faster) gives:
```
6.08 ms ± 333 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
580 µs ± 2.57 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
Switching to …
> MRG, ENH: Speed up info copy

- examples/preprocessing/plot_rereference_eeg.py
- mne/channels/channels.py
- mne/io/fieldtrip/tests/helpers.py
- mne/io/reference.py
- mne/utils/docs.py
- tutorials/evoked/plot_eeg_erp.py
- tutorials/io/plot_20_reading_eeg_data.py
- tutorials/preprocessing/plot_55_setting_eeg_reference.py
closes #7471 
These are the files I could catch that did still assume MNE-Python to auto apply an average ref projection. Also, the docstr of `set_eeg_reference` was still assuming that.
I wasn't sure with `tutorials/preprocessing/plot_55_setting_eeg_reference.py` --> see my inline "todo" comment there marked with `XXX`
PS: What was the PR that removed the auto average ref behavior of MNE?
> MRG: [DOC] MNE does no longer auto apply average ref

- mne/viz/_brain/_timeviewer.py
This PR improves the memory footprint of `_TimeViewer` by decreasing the reference count and solving reference cycles.
This is the comparison between `master` (black curve) and this PR (blue curve) using the following script with `mprof`:
```py
import os
import mne
import pyvista
sample_dir = os.path.join(data_path, 'MEG', 'sample')
subjects_dir = os.path.join(data_path, 'subjects')
fname_stc = os.path.join(sample_dir, 'sample_audvis-meg')
stc = mne.read_source_estimate(fname_stc, subject='sample')
initial_time = 0.1
mne.viz.set_3d_backend('pyvista')
for j in range(5):
for i in range(5):
brain = stc.plot(subjects_dir=subjects_dir, initial_time=initial_time,
clim=dict(kind='value', pos_lims=[3, 6, 9]),
hemi='lh', …
```
> MRG: Improve memory footprint of _TimeViewer

- mne/conftest.py
- mne/utils/tests/test_numerics.py
Just removing some version cruft we no longer need because our minimum is 0.19. Also adding one more ignore needed for latest dev `pandas` with `statsmodels` importing something deprecated
> MRG, FIX: Remove cruft

- mne/annotations.py
`mne.Annotations` can handle `duration` being a float or array with only a single element. Add this info to the docstring.
This use case is already covered by the existing tests.
> DOC: Annotations class accepts float as duration param

- mne/channels/channels.py
- mne/dipole.py
- mne/evoked.py
- mne/io/pick.py
- mne/io/tests/test_pick.py
- mne/preprocessing/ica.py
- mne/tests/test_rank.py
- mne/time_frequency/tfr.py
- mne/viz/epochs.py
- mne/viz/evoked.py
- mne/viz/ica.py
- mne/viz/topo.py
- mne/viz/topomap.py
- mne/viz/utils.py
- tutorials/intro/plot_30_info.py
This PR tries to clean up / standardize how channel types are found in the code base.
- the instance methods `<raw/epochs/evoked>.get_channel_types()` now internally use the existing `_get_channel_types` function instead of a pared-down reimplementation of it.  Accordingly, they also now have method parameters `picks=None, unique=False, only_data_chs=False`.
- Various places in the codebase have been switched from list comprehensions like `[channel_type(info, x) for x in range(info['nchans'])]` to simply call the `_get_channel_types(info)` or `_get_channel_types(info, picks)`. A few more complicated list comprehensions have been left alone, as they are simpler as-is than they would have been if changed to use the `_get_channel_types` function.
- the instance method …
> MRG, MAINT: standardize the way we get channel types

- mne/preprocessing/nirs/_scalp_coupling_index.py
- mne/preprocessing/tests/test_scalp_coupling_index.py
General fNIRS tweaks #7057 
The previous check for the signal type was never reached as previous functions would fail. Moved check forward and added tests.
Caught this one because I was going through the code coverage trying to hit 100%
> MRG: Test SCI correctly checks file type at start of function

- mne/datasets/utils.py
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
Fixes GH-7492.
Currently, FIF files that have an invalid birthday or measurement date set cannot be read, as an exception is raised (see #7492). This PR catches the exception, skips the entry (effectively adding it as `None` to the `info` dict), and emits a warning. This way, users can at least load the data, even though the metadata may then be partially incomplete.
Tested with the problematic Cam-CAN data mentioned in #7492.
I need advise on how to best come up with a test for this.
> BF: Allow reading of FIF files with incorrect date

- doc/changes/latest.inc
includes the "what's new" entries that were omitted from #7486
> update what's new [skip travis][skip azp]

- mne/preprocessing/nirs/nirs.py
- mne/preprocessing/tests/test_beer_lambert_law.py
General fNIRS tweaking #7057 
Added test to ensure that NIRS data is stored as paired wavelength data. Noticed that if an odd number of channels existed that the check failed.
> MRG: Test warnings if NIRS channels are not correctly ordered

- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/tests/test_raw.py
- mne/utils/check.py
- mne/utils/tests/test_check.py
Be more permissive of True/False in `read_raw_edf`, but also more strict in `_validate_types` since passing a `bool` to act as an `int` is much more likely to cause unexpected behaviors than expected ones (and easily worked around with `int(my_bool)` if people actually want to provide an int).
No need for `latest.inc` update I think since this is mostly an internal change (except maybe for being more permissive, but I'm not sure that's even worth advertising).
Closes #7485
> MRG, MAINT: Better checks for int-ness

- doc/install/mne_python.rst
Closes #7449.
Point picking breakage appears not to be our problem or even Mayavi's, but rather at the VTK level. Probably VTK 8.2 is not compatible with PyQt5 >= 5.14, so we'll need to wait for the VTK9 update to try again (and to get a full 3.8 CI running).
> MRG, FIX: Update installation instructions

- mne/preprocessing/nirs/nirs.py
- mne/preprocessing/tests/test_beer_lambert_law.py
General fNIRS tweaks #7057.
In #7064 the NIRS light frequency was moved from being stored in the channel name to being stored in `info['chs'][ii]['loc'][9]`. However, the frequency is still stored in the channel name for ease of reading, plotting, and because MNE throws an error if two channels have the same name. 
This PR adds a check that the light frequency stored in the `ch_name` and in `loc` match. And adds tests.
People shouldn't mess with the channel names and this is specified in the docs already. https://github.com/mne-tools/mne-python/blob/master/tutorials/io/plot_30_reading_fnirs_data.py#L26
> MRG: Add test that NIRS naming matches stored frequency

- mne/viz/_brain/_timeviewer.py
- mne/viz/backends/_pyvista.py
This PR checks the minimum version requirement for pyvista at runtime.
> Check pyvista version in _TimeViewer

- doc/changes/latest.inc
- mne/report.py
- mne/tests/test_report.py
Fixes #7493 
`mne.Report.parse_folder` used to ignore `meg.fif` raw files although in the documentation example
[Getting started with mne.Report](https://mne.tools/dev/auto_tutorials/misc/plot_report.html#sphx-glr-auto-tutorials-misc-plot-report-py) `_meg.fif` is listed within the supported formats.
This PR fixes file fetching in `report.py` so it actually loads `meg.fif`.
> MRG, FIX: Add support for BIDS-style raw files to reports

- mne/viz/_brain/_timeviewer.py
It occurs to me that I never asked for feedbacks for the slider style, I just went with what I found practical but apparently the current design has some limitations. For example, since the slider tube is very thin it's easy to miss it and rotate the brain instead (reported in https://github.com/mne-tools/mne-python/pull/7247#issuecomment-583536539 and offline by @hoechenberger). This PR tries to address that by changing the style of the slider (and by doing so, modify it's hitbox).
I suggest 2 styles of sliders. In both styles I removed the end cap. In style 1, I increased the tube width but the overall style stays similar. The style 2 is a bit extreme but fixes the original issue quite easily.
<details>
```py
import os
import mne
data_path = …
```
> MRG: Change _TimeViewer slider style

- doc/changes/latest.inc
- mne/io/pick.py
- mne/morph.py
- mne/tests/test_morph.py
Splits off the `nearest` refactoring from #7060 into a proper PR, and adds it as an option to `compute_source_morph`.
I looked briefly for an example to update, but I couldn't find an obvious candidate and not sure it's worth it for this small update.
> MRG, ENH: Add smooth="nearest" support

- mne/preprocessing/ica.py
"principle component" => "principal components"
> DOC: Fixes a typo in ICA docstring

- examples/forward/plot_source_space_morphing.py
- mne/utils/check.py
- mne/utils/docs.py
- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/_timeviewer.py
Alternative to #7518.
I think we should show the (incorrectly-named) `_TimeViewer` even if there is a single time point because it shows useful controls like clim, view, etc. (and others if we add them later). This hides the playback speed and time slider as well.
> MRG, FIX: Fix single time point

- mne/conftest.py
- mne/report.py
- mne/viz/_brain/_brain.py
- mne/viz/backends/renderer.py
- mne/viz/backends/tests/test_renderer.py
- mne/viz/tests/test_3d.py
When working on https://github.com/mne-tools/mne-bids/pull/376, which effectively turns all warnings into errors that make our unit tests fail, I discovered that `mne.viz.backends.renderer`
would always produce this odd warning:
```python
<frozen importlib._bootstrap>:1072: in _calc___package__
???
E   ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
globals    = {'__name__': 'mne.viz.backends.renderer'}
package    = None
spec       = None
```
I found out that this is related to using `importlib.__import__()` for loading the required backend module. I have now switched the relevant code to `importlib.load_module()`, which makes
the warning disappear at least locally (Python 3.8, macOS).
> RF: Change viz backend loading

- doc/carousel.inc
- doc/index.rst
We probably shouldn't have the example buttons on the landing page anymore, they are outdated and point people to `examples` pages which are not the best place to get started. People should follow the "overview" to figure out where to go, which hopefully will be clear enough just being at the top.
Also fixed a bug with an ~~link and~~ image.
> MRG, MAINT: Remove outdated buttons, update image

- .circleci/config.yml
In this case, sphinx prerelease (3.0.0b1 is on PyPi now).
Setting to WIP just until 0.20 is out
> MRG, MAINT: Use preleases to catch bugs early

- mne/cov.py
A quick support request from @virvw made it obvious to me that `mne.compute_raw_covariance` is currently not so easy to discover as it should be; users were trying to use `mne.compute_covariance` for empty-room data (and, consequently, running into trouble),
without realizing that `compute_raw_covariance` was readily available. This commit adds a clearly-visible note to the docstring to help guide users better.
> DOC: Make compute_raw_covariance easier to find

- doc/changes/latest.inc
- mne/preprocessing/nirs/_scalp_coupling_index.py
The filter parameters for scalp coupling index were being passed incorrectly to the downstream function.
> MRG: Fix bug in scalp coupling index.

- tutorials/preprocessing/plot_70_fnirs_processing.py
General NIRS tweaks #7057 
Pick a NIRS specific figure for the thumbnail.
> MRG: Pick canonical NIRS response figure for gallery thumbnail 

- doc/changes/0.20.inc
tiny fix to the `whats_new` page for 0.20:
- @bloyl's name was failing to link in one case because it followed directly after a comma (lacked a leading space)
- tiny grammar tweak
> MRG, DOC: cosmetic changes to what's new for 0.20

- mne/chpi.py
- mne/utils/progressbar.py
In testing ([this gist](https://gist.github.com/larsoner/c56b2521925273094208f33aa1e5cff1) and also long, slow clustering operations) this seems to be a better smoothing param. Turns out that `smoothing=0.9` was doing almost nothing. Using `smoothing=0.05` gives much smoother time remaining and ops/sec estimates.
@drammock I think you mentioned that the PB updates were a bit erratic, can you see if this fixes it for you?
> MRG, ENH: Better progressbar smoothing

- mne/conftest.py
- mne/decoding/tests/test_receptive_field.py
- mne/dipole.py
- mne/event.py
- mne/externals/h5io/_h5io.py
- mne/fixes.py
- mne/forward/_lead_dots.py
- mne/io/tag.py
- mne/io/write.py
- mne/source_estimate.py
- mne/surface.py
- mne/utils/numerics.py
NumPy has deprecated `tostring` so let's use `tobytes`.
This is a simple search-and-replace plus removing a few lines in `test_receptive_field` that needlessly read `raw` data.
> MRG, FIX: Use tobytes instead of tostring

- mne/viz/topomap.py
I slightly changed the docstrings of the `vmin` and `vmax` parameters of `plot_evoked_topomap()`, and hope they are easier to understand now.
> DOC: (Hopefully) small clarification to plot_evoked_topomap() docstring

- .travis.yml
- azure-pipelines.yml
- requirements.txt
Hopefully fixes failures like https://travis-ci.org/github/mne-tools/mne-python/jobs/670600607
The world is just not ready for PyQt 5.14
> MRG, FIX: Fix for PyQt5 5.14.2

- doc/changes/latest.inc
- mne/dipole.py
- mne/utils/docs.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
Allow to specify a custom figure title when plotting `Dipole` locations via `Dipole.plot_locations()` or `viz.plot_dipole_locations()`.
> ENH: Custom figure title when plotting Dipole locations

- mne/channels/channels.py
I skipped CI because this change is so minor.
> DOC: fix link in docstr [skip ci]

- doc/changes/latest.inc
- doc/python_reference.rst
- doc/references.bib
- examples/preprocessing/plot_fnirs_artifact_removal.py
- mne/preprocessing/nirs/__init__.py
- mne/preprocessing/nirs/_temporal_derivative_distribution_repair.py
- mne/preprocessing/tests/test_temporal_derivative_distribution_repair.py
- tutorials/preprocessing/plot_70_fnirs_processing.py
As discussed in #7057 
Adds temporal derivative distribution repair (TDDR) technique.  
Adds new example showing how to apply nirs artefact correction (with plan to expand as new methods are implemented).
I have taken the code directly from the author with permission.
I have kept the code as close to the original from the author as possible, and then used a wrapper function. I did this as the code was very nice. Also if the upstream version changes it is then easier to move the changes here.
> WIP: Add temporal derivative distribution repair algorithm

- doc/changes/latest.inc
- mne/channels/channels.py
- mne/channels/interpolation.py
- mne/channels/tests/test_interpolation.py
- mne/preprocessing/nirs/nirs.py
Ongoing fNIRS improvements #7057 
Adds the most basic type of "fixing" of bad channels, simply replaces them by the closest good channel.
Maybe interpolation isn't the right word for what I wrote, but it seemed inline with previous functions. And I would like to expand to something smarter like actual interpolation
> MRG: Add interpolation for NIRS signals

- doc/changes/latest.inc
- mne/filter.py
- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
Relaxes the requirement that data be preloaded before resampling. Should help on low-memory machines. Probably worth doing early in 0.21 rather than before cutting 0.20, hence the WIP.
Todo:
> MRG, ENH: Dont require preload for raw resample

- doc/changes/latest.inc
- mne/parallel.py
This fails on master, and passes on this PR:
```python
import mne
mne.parallel.check_n_jobs(np.int64(6))
```
strangely, I was definitely passing in a plain `int`, not a numpy type, so `n_jobs` must have been recast somewhere in between my call to `mne.time_frequency.psd_multitaper` and the eventual check.  If it's important to dig in and figure out where/why that happened, LMK.
I didn't see a file `mne/tests/test_parallel.py`... do we not test the parallel capabilities?
> MRG, FIX: parallel n_jobs check

- doc/changes/latest.inc
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
Fixes a bug where "Toggle all" did not actually toggle all projectors. Test fails on `master` and passes on this PR.
> MRG, FIX: Fix toggle all

- mne/viz/_brain/_timeviewer.py
This PR fixes the issue with picking in `_TimeViewer` when the mouse wheel event is the first mouse button interaction.
Closes https://github.com/mne-tools/mne-python/issues/7534
> MRG: Fix mouse wheel event in _TimeViewer

- examples/visualization/plot_publication_figure.py
- mne/viz/backends/_pyvista.py
This PR fixes the last part of https://github.com/mne-tools/mne-python/issues/7526 about the figures still registered after `close()`. It's also a way more aggressive closing so I started Circle on this one.
Closes https://github.com/mne-tools/mne-python/issues/7526
> WIP: Deregister plotter from the figure list in close()

- mne/viz/backends/_pyvista.py
This small PR disables the default camera toolbars which are not compatible with `_TimeViewer`. Its features are either unused or duplicated.
This simplifies the window design overall.
`master` | PR
------------|-----
> MRG: Remove toolbars in PyVista plotter

- tutorials/source-modeling/plot_eeg_mri_coords.py
Fixes a typo in the "EEG source localization given electrode locations on an MRI" tutorial and corrects the transformation matrix going from milli-meters to meters.
> DOC: Fixes in tutorial

- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/_timeviewer.py
- mne/viz/backends/_pyvista.py
**TL:DR**: `_TimeViewer` is displayed only once, when the UI is ready.
The default plotter of the pyvista backend is interactive as soon as it opens that's why one can notice every piece of the interface being added when `time_viewer=True` resulting in the jerkiness mentioned by @hoechenberger in https://github.com/mne-tools/mne-python/pull/7572#issuecomment-610382365 and @jasmainak in https://github.com/mne-tools/mne-python/pull/7247#issuecomment-587833079.
This PR fixes this behaviour by showing the `_TimeViewer` only when when it's ready (once every GUI element is set up). To achieve that I have to make `_Brain` aware that `time_viewer` is set. So I introduced the `show` parameter.
This way, the behaviour of `_Brain` is more consistent with all the basic `_3d.py` primitives and the …
> Rework _Brain show

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/io/edf/edf.py
WIth regards to  #7124 .
While importing a GDF 2.x file with
```python
from mne import io
io.read_raw_gdf(fname, preload=True)
```
we encountered the following error:
```python
Extracting EDF parameters from /home/svea/Desktop/mne_examples/sample_data/B0103T.gdf...
GDF file detected
File "/home/svea/Desktop/mne_examples/online_linear_demo.py", line 17, in <module>
raw = io.read_raw_gdf(raw_fname, preload=True)
File "/home/svea/Desktop/mne_examples/venv/lib/python3.7/site-packages/mne/io/edf/edf.py", line 1327, in read_raw_gdf
verbose=verbose)
File "<decorator-gen-164>", line 21, in __init__
File "/home/svea/Desktop/mne_examples/venv/lib/python3.7/site-packages/mne/io/edf/edf.py", line 189, in __init__
exclude, preload)
File …
```
> MRG, FIX: Datetime call in gdf 2.x age calculation

- tutorials/intro/plot_20_events_from_raw.py
- tutorials/preprocessing/plot_60_maxwell_filtering_sss.py
- tutorials/raw/plot_20_event_arrays.py
This PR follows https://github.com/mne-tools/mne-python/pull/7574#issuecomment-612106164 and tries to reproduce the warnings.
> TST: Check Circle

- mne/viz/_brain/_timeviewer.py
Thanks to https://github.com/mne-tools/mne-python/pull/7589 we can now drastically simplify the way we manage the shortcuts in `_TimeViewer`. This PR also improves stability because we don't rely on the `keyPressEvent` callback anymore and flexibility because we use `QAction` instead of a `dict` for the bindings. It's also easier to maintain because the shortcuts are set in one place.
> MRG: Refactor _TimeViewer shortcuts

- mne/datasets/utils.py
- mne/io/egi/egimff.py
- mne/io/egi/events.py
- mne/io/egi/general.py
- mne/io/egi/tests/test_egi.py
I implemented fixes mostly blind based on how I thought the format worked, let's see if it's correct.
@Lx37 @rhancockn @mmagnuski @christian-oreilly @ViridianForge 
1. You have reported problems/tried fixes, can you see if the branch from this PR (`larsoner:egi`) works with your data?
2. If you have ideas about how MFF works internally, please also review at the changes!
@rhancockn it would be nice to add more rigorous tests for the data you added to the testing dataset. For example, if in some other EGI browser software you can pick out some specific event number + times that we could hard code in the test then `assert_array_equal` in the test, that would help. Currently I just check the number of events, and I have no idea if it's actually correct, it's just the count I got once I had …
> MRG, FIX: Fix reading EGI data with pauses

- mne/viz/_brain/_timeviewer.py
This PR fixes the play/pause button behaviour in `_TimeViewer`. It is now updated correctly when it reaches the last timestep.
Closes https://github.com/mne-tools/mne-python/issues/7611
> WIP: Fix play/pause button in _TimeViewer

- azure-pipelines.yml
- doc/changes/latest.inc
- mne/commands/mne_setup_forward_model.py
- mne/commands/mne_setup_source_space.py
- mne/commands/tests/test_commands.py
1. Make `mne_setup_forward_model` compute and save the BEM solution (clearly nobody has really been using this command-line tool...)
2. Try to speed up Azure with `MKL_NUM_THREADS: 1`, can compare to [this run](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=6549&view=logs&j=b195a6e3-7484-5943-e627-0b35c27605d6&t=6dcb3581-08d4-5e76-74f2-6edaf20ff912) (0:46:23) to check
3. Speed up BEM test by computing the `--homog` rather than 3-layer
4. Speed up a test that takes ~180sec on Azure and ~77 sec locally, now takes ~2 sec locally (by not adding source space distances)
> MRG, FIX: Fix mne_setup_forward_model

- doc/changes/latest.inc
- examples/inverse/plot_vector_mne_solution.py
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
- mne/source_estimate.py
- mne/tests/test_source_estimate.py
- mne/utils/docs.py
One advantage of `plot_vector_source_estimates` is that the arrows + glass brain represent the true geometry of the source space better than an inflated view. It would be nice to be able to use this function, even if you are working with fixed orientations. This PR enables `pick_ori='vector'` with fixed-orientation inverses.
> MRG, ENH: Allow pick_ori="vector" with fixed ori inv

- mne/preprocessing/maxwell.py
Highlight the recommendation to low-pass filter the data before running `find_bach_channels_maxwell()`.
> DOC: Highlight lowpass filter recommendation in find_bad_channels_maxwell()

- doc/changes/latest.inc
- mne/utils/config.py
- mne/utils/tests/test_config.py
Fixes #7622
Allows to pass<strike> arbitrary</strike> `path-like` values to `set_config` <strike>as long as they're `None` or can be cast into a string. No further type checking is performed.</strike>
<strike>Also this PR includes a small fix to the `config` test suite, as one of the tests was expecting a `TypeError`, while in fact a `RuntimeWarning` is raised.</strike>
> ENH: Allow path-like values passed to set_config

- doc/changes/latest.inc
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
Why the data are `nan` is another issue, but at least `raw.plot` should not die with a cryptic message. We could perhaps also add a warning, this PR will make it so the user sees something like this, which pretty clearly indicates a problem (so maybe it's enough already):
> MRG, FIX: Fix labeling for broken raw

- mne/viz/_brain/_timeviewer.py
I realized that since #7612 has been merged, Circle reaches timeout after `plot_visualize_stc`. I can't reproduce locally so I decided to investigate in here.
> FIX: Circle timeout after plot_visualize_stc

- doc/changes/latest.inc
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
Takes care of a bug where you could get during EDF reads:
```
E       ValueError: invalid literal for int() with base 10: '36096\x00\x00\x00'
```
Stripping the null bytes fixes the issue.
> MRG, FIX: Fix bug when EDF has null bytes

- doc/changes/latest.inc
- mne/report.py
- mne/tests/test_report.py
I noticed that you can't toggle the BEM using the buttons at the top of the report because the class is not set properly. This fixes that, and also makes the section naming consistent (always "bem" instead of sometimes "bem" and sometimes "mri".
> MRG, FIX: Report BEM toggling

- doc/changes/latest.inc
- doc/python_reference.rst
- mne/epochs.py
- mne/utils/docs.py
- mne/viz/tests/test_epochs.py
- mne/viz/topomap.py
- tutorials/epochs/plot_20_visualize_epochs.py
> ENH: psd topomap improvements

- doc/changes/latest.inc
- examples/time_frequency/plot_source_power_spectrum_opm.py
- examples/visualization/plot_evoked_topomap.py
- mne/defaults.py
- mne/evoked.py
- mne/io/proj.py
- mne/utils/docs.py
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
Probably a better solution than #7602.
WIP because:
Closes #7601
Closes #7602
> MRG, BUG: Use auto extrap and mean borders

- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
Looking through the code, noticed that we should tweaking some of our `maxwell_filter` tests to use more modern `pytest` syntax, and use `_validate_type` as well.
Will merge once CIs are happy since this is a pretty straightforward maintenance thing.
> MRG, MAINT: Modernize maxwell_filter tests

- doc/changes/latest.inc
- examples/inverse/plot_label_source_activations.py
- mne/source_estimate.py
- mne/tests/test_source_estimate.py
- mne/utils/docs.py
Helpful when working in free or even loose orientation because you can extract the vector source activations, and then take the norm (or do PCA, a Hotelling test, etc.) rather than having to take the norm or just the normal component.
Eventually I see this as being especially useful with volumetric source models with free orientation, so it lays the groundwork for #6155 to be useful.
> MRG, ENH: Add label extraction for vector source estimates

- doc/changes/latest.inc
- mne/source_space.py
- mne/tests/test_morph.py
- mne/tests/test_source_space.py
The old code for subselecting volumes based on `volume_label` used `_compute_nearest`, which is fine if you use *the entire set of volume grid voxels* and see if what you're closest to matches the desired ID.
However, it used `_compute_nearest` with the *voxels matching the given ID*, and then checked to make sure that the source space `rr` were within some distance of these nearest neighbors based on the voxel spacing. This is problematic for two reasons:
1. Non-uniform `zooms` could break this, but in practice they are probably always the same. More importantly...
2. Checking the distance from the source space point its the nearest voxel center effectively forms a sphere in 3D space around each voxel center. Geometrically, at the boundaries of the sub-volume this forms a "bumpy surface" …
> MRG, FIX: Use nearest in grid in setup_volume_source_space

- doc/changes/latest.inc
- mne/commands/mne_browse_raw.py
- mne/io/base.py
- mne/viz/__init__.py
- mne/viz/raw.py
This improves our clipping to use `matplotlib` to cut off values rather than using `np.nan`. This is better because `np.nan` can cause the entire trace to be removed, this will cause it to still exist but just be invisible outside the appropriate "box".
Also proposes changing the default `clipping=None` to `clipping=1.5`, but this is certainly up for debate. WIP because we need to run some examples and decide, and it should go in 0.21.
Todo:
Some related discussion in #7521
> MRG, ENH: Allow float clipping

- doc/changes/latest.inc
- mne/bem.py
- mne/commands/tests/test_commands.py
Fixes #7570.
In v20, the RAS coordinates of the surfaces created by `mne.bem.make_water_shed_bem` were wrong (refer to #7570 for details). This PR fixes the problem and adds tests to `mne/commands/test_commands/test_watershed_bem` to check the RAS coordinates of the watershed BEM surfaces.
The bug was found thanks to @mh105, replicated by @larsoner.
> FIX: Fix RAS coordinates in watershed bem surfaces

- mne/viz/_3d.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/tests/test_3d.py
- tutorials/preprocessing/plot_70_fnirs_processing.py
Discussed in #7057 and https://github.com/mne-tools/mne-nirs/issues/59
Add option to plot line between source detector pairs in `plot_alignment` .
This PR originally contained code to plot data over the head, but this has been moved to MNE-NIRS
> MRG: Plot NIRS data between source and detector

- mne/viz/_brain/_timeviewer.py
This PR fixes the part of #7599 about the cell vertex indexing issue during cell picking.
> MRG: Fix cell vertex ids in _TimeViewer

- doc/changes/latest.inc
- mne/viz/misc.py
- mne/viz/tests/test_misc.py
#7654
Add `plot` keyword to allow choice of filter properties to plot.  
Add `axes` keyword.
Order of plots is not as specified by the user, not in fixed order as before
> MRG: Add plot and axes option to plot_filter

- .circleci/config.yml
- .travis.yml
- azure-pipelines.yml
- doc/install/mne_python.rst
- environment.yml
- mne/utils/config.py
- requirements.txt
1. Use `pytest-xdist` with `-n 1` which runs jobs in a subprocess, thereby hopefully making it easier to tell what killed a test (#7673)
2. Update `sys_info` to report the PyQt5 version directly rather than as part of the `mayavi` entry.
Now I get:
```
$ mne sys_info
Platform:      Linux-5.4.0-26-generic-x86_64-with-glibc2.29
Python:        3.8.2 (default, Mar 13 2020, 10:14:16)  [GCC 9.3.0]
Executable:    /home/larsoner/.local/bin/python
CPU:           x86_64: 8 cores
Memory:        62.8 GB
mne:           0.21.dev0
numpy:         1.19.0.dev0+ad5d58c {blas=openblas, lapack=openblas}
scipy:         1.5.0.dev0+b8f50ef
matplotlib:    3.2.1.post1626+g537a8c905 {backend=Qt5Agg}
sklearn:       0.23.dev0
numba:         0.50.0dev0+109.g1f9d82fc8
nibabel:       2.5.1+159.gddf26830
cupy: …
```
> MAINT: Use xdist and better sys_info

- doc/overview/roadmap.rst
- mne/io/base.py
- mne/utils/docs.py
Closes #6380
We already have `str` support in `append `, just need to document it in `concatenate_raws` that calls `append` internally. That issue also mentions making `concatenate_epochs` allow a `str` but I think this would require extensive refactoring of our `Epochs` class, and hopefully is YAGNI knowing that this is available.
Also updates a link from our roadmap to GitHub.
> MRG, DOC: Properly document str option to concatenate_raws

- mne/io/meas_info.py
Adds "ambidextrous" to `Info` docstring.
As is defined in `io.constants` already.
> DOC: Add "ambidextrous" to docstring

- doc/changes/latest.inc
- doc/python_reference.rst
- mne/stats/__init__.py
- mne/stats/cluster_level.py
- mne/stats/parametric.py
- mne/stats/tests/test_cluster_level.py
- mne/stats/tests/test_parametric.py
Closes #7684.
@fleurgaudfernau can you try it?
Also adds `ttest_ind_no_p` like we have `ttest_1samp_no_p` because I've needed it / coded it before, and it was helpful for the test for TFCE to be able to use it.
> MRG, BUG, ENH: Fix sign and add ttest_ind_no_p

- .travis.yml
- mne/conftest.py
- mne/filter.py
- mne/preprocessing/_peak_finder.py
- mne/utils/_logging.py
- mne/utils/check.py
- mne/utils/tests/test_logging.py
- mne/viz/tests/test_ica.py
#7689 for `master`.
1. Fix several doctests
2. Relax `pytest.warns` check in ICA plotting -- it's not critical and clearly not reliable since we already did the same for `raw` plotting
3. Ensure no tests change the `verbose` level
4. Run one Travis run with `MNE_LOGGING_LEVEL=INFO` instead of `MNE_LOGGING_LEVEL=WARNING`
I considered using the `autouse` pytest fixture to use the `use_log_level` context manager, but decided against it since I think it's better to explicitly test behavior with multiple values of MNE_LOGGING_LEVEL, which is easily accomplished by using different Travis runs.
Will merge this and #7689 once CIs are happy, hopefully today but maybe tomorrow, then cut a 0.20.2 to facilitate Fedora packaging
> MRG, FIX: patch doctest

- mne/time_frequency/multitaper.py
This is a tiny fix to internal multitaper code. It shouldn't affect anything that uses the public API; these are changes I needed to make to use some of the private multitaper functions in my analysis pipeline, to allow using the private functions with both epochs and evoked objects. Should be fully backward-compatible, and should make future expansion of the multitaper API slightly easier.
(for those interested, in an SSVEP experiment I needed to keep the complex values --- which meant keeping the separate spectral estimates from each taper --- so that later I could hopefully get some phase-cancelling noise reduction in the non-carrier / non-oddball frequency bins).
> safer indexing/slicing in internal multitaper code

- doc/changes/latest.inc
- doc/python_reference.rst
- mne/__init__.py
- mne/conftest.py
- mne/dipole.py
- mne/forward/tests/test_make_forward.py
- mne/source_estimate.py
- mne/source_space.py
- mne/tests/test_morph.py
- mne/tests/test_source_estimate.py
- mne/tests/test_source_space.py
- mne/transforms.py
- mne/utils/docs.py
- tutorials/source-modeling/plot_visualize_stc.py
Adds volume label support to `extract_label_time_course`. Requires #7597 (and follow-up PRs).
Next PRs:
- Ensure all source estimate types work with SourceMorph (#7564)
- Update docs about `src` in SourceMorph (#7007)
Closes #6155.
> MRG, ENH: Add volumetric atlas support

- examples/inverse/plot_vector_mne_solution.py
- mne/source_estimate.py
- mne/tests/test_source_estimate.py
Fixes an error with `get_peak` made when refactoring in the atlas PR (showed up in CircleCI), and finally add more comprehensive tests so that `get_peak` is more robust.
> MRG, FIX: Fix bug with get_peak

- mne/bem.py
- mne/commands/tests/test_commands.py
- mne/datasets/sample/__init__.py
- mne/datasets/sample/sample.py
- mne/datasets/utils.py
- mne/tests/test_bem.py
- mne/tests/test_docstring_parameters.py
Enhance tests as stated in #7661.
Merge `mne/tests/test_bem.py::test_make_flash_bem` to `mne/commands/test_commands.py::test_flash_bem` to reduce test time.
Testing data would be more compact (does not need `COR*` files) and efficient (use resampled `T1.mgz` to save time) using the current test.
Testing dataset should be updated if this PR is accepted, or the test may fail.
> MRG, ENH: Remove redundant tests on make_flash_bem

- .circleci/config.yml
- mne/datasets/utils.py
In #7704 I removed a `SUBJECTS_DIR` env var in `.circleci/config.yml` to ensure it's always set properly in examples. This led to a CircleCI failure:
https://app.circleci.com/pipelines/github/mne-tools/mne-python/1377/workflows/28bc8b26-4c73-4c33-ae3b-1dd76b7f1d20/jobs/19789/steps
This should fix it by passing a path when doing `fetch_hcpmmp_parcellation`.
> MRG, FIX: Fix path

- doc/changes/latest.inc
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
- mne/viz/utils.py
closes #7595 
Setup for testing:
```python
from mne import read_evokeds
path = sample.data_path()
fname = path + '/MEG/sample/sample_audvis-ave.fif'
condition = 'Left Auditory'
evoked = read_evokeds(fname, condition=condition, baseline=(None, 0))
times = np.linspace(0, 0.5, 7)
```
```python
evoked.plot_topomap(times='interactive')
```
```python
evoked.plot_topomap(times='interactive', colorbar=False)
```
```
IndexError: index 2 is out of bounds for GridSpec with size 2
```
```python
evoked.plot_topomap(times=times)
```
```python
evoked.plot_topomap(times=times, colorbar=False)
```
```python
evoked.plot_topomap(times=times, ncols=3, nrows='auto')
```
```python
evoked.plot_topomap(times=times, ncols=3, …
```
> MRG, FIX, VIZ: refactor plot_evoked_topomap

- mne/epochs.py
- mne/evoked.py
tiny typo fix `Arraw` -> `Array`
> DOC: tiny typo fix [ci skip]

- doc/changes/latest.inc
- mne/morph.py
- mne/tests/test_morph.py
See `latest.inc`, basically only the first volume label would be interpolated when morphing a source space with multiple subvolumes and using `mri_resolution=True`.
This was found while working toward fixing #7564, so this has a bunch of stubs where support for `'mixed'` will eventually need to be added (it actually doesn't look so bad!).
> MRG, FIX: Fix volume morph with multiple labels

- mne/viz/_brain/tests/test_brain.py
- mne/viz/backends/_pysurfer_mayavi.py
This PR follows https://github.com/mne-tools/mne-python/pull/7701#issuecomment-623471954 idea and tries to decrease the number of calls to `_Brain.__init__()` which seems costly. Hopefully this will reduce testing time especially on macOS.
> MRG: Speedup testing of _Brain

- mne/source_estimate.py
- mne/tests/test_source_estimate.py
following offline discussion with @larsoner, this raises a `ValueError` (instead of warning) when attempting to save an STC containing complex-valued data in the FIFF format.
> Raise error if saving complex-valued STC as FIFF

- doc/changes/latest.inc
- mne/io/nirx/nirx.py
- mne/io/nirx/tests/test_nirx.py
https://github.com/cbrnr/mnelab/issues/144#issuecomment-623066162
Allows user to pass the path to a NIRX header file to load data, rather than passing the path to the directory.
This was suggested as a way to easily add data loading to MNELAB (see comment above).
> MRG: Add ability to load NIRX data by passing path to header file

- doc/changes/latest.inc
- mne/decoding/transformer.py
- mne/epochs.py
- mne/io/base.py
- mne/io/write.py
- mne/tests/test_epochs.py
> MRG, FIX: Fix epochs split size

- doc/_templates/autosummary/class.rst
- doc/_templates/autosummary/function.rst
- doc/conf.py
- examples/inverse/plot_morph_surface_stc.py
- mne/morph.py
- tutorials/source-modeling/plot_mne_dspm_source_localization.py
Mostly for @drammock during tutorial development. Allows linking directly to the SG mini-galleries for a given function/class/method. Cross-ref https://github.com/sphinx-gallery/sphinx-gallery/issues/496
Also speeds up one tutorial by removing some redundant calculations that are better explored in another tutorial.
@drammock feel free to review and merge if you're happy
> MRG, MAINT: Add links to mini-galleries

- README.rst
- codecov.yml
Adds PyPi and conda-forge download count badges to our readme, and tweaks `codecov` a bit so that 1) it doesn't comment (these aren't so useful) and 2) hopefully has fewer false alarms about problematic coverage.
> MAINT: Add badges and tweak codecov

- mne/viz/utils.py
- tutorials/raw/plot_40_visualize_raw.py
Closes #7738
Do not plot lines on the edges of PSD areas
> Remove area edge lines in average PSD plots

- mne/viz/backends/renderer.py
- mne/viz/backends/tests/test_renderer.py
This builds upon #7688.
On `master`, I observed the following behavior on a machine without a working 3D backend:
MWE:
```python
import mne
print(mne.viz.get_3d_backend())
print(mne.viz.get_3d_backend())
```
`master`:
```
None
pyvista
```
Reason is that when probing for usable backends, `MNE_3D_BACKEND` is being set _before the probing is carried out_, so when it fails, the variable has already been changed, and is not reset to its previous state. df2e395 fixes the behavior and only changes `MNE_3D_BACKEND` is probing the 3D backend was successful:
```
None
None
```
<strike>I also realized that `viz.get_3d_backend()` can be simplified much more: since `MNE_3D_BACKEND` should always contain the currently used backend, `get_3d_backend()` can simply return this value. There's no need to …
> BF: Improvements to viz.get_3d_backend()

- doc/changes/latest.inc
- mne/viz/ica.py
- mne/viz/tests/test_ica.py
- tutorials/preprocessing/plot_40_artifact_correction_ica.py
When calling `ica.plot_sources(raw)` annotations were not displayed.
This PR mimics what is done in `raw.plot` so they are displayed. I'm not sure what the best way to provide a test is. Maybe I should modifiy the tutorial to have an annotation?
Thoughts?
> Ica annotations

- doc/changes/latest.inc
- mne/preprocessing/artifact_detection.py
- mne/preprocessing/tests/test_artifact_detection.py
`mne.preprocessing.annotate_movement` computes HPI displacements from an average position. Bad data segments (in `raw.annotations`) where meant to be excluded from this averaging. However there is a bug in computing the weights for averaging
Basically the weights (`seg_good`) are defined from `pos` which has different time samples from `raw`. So the onsets/durations of the bad annotations do line up with the indices of the `seg_good` array.
This PR uses `compute_average_dev_head_t` to compute an average transform (ignoring bad segments) and uses that to compute the average HPI locations.
Additionally, I'd like to propose adding a flag `use_raw_head_trans` (or similarly named) that if set would use `raw.info['dev_head_t']` as opposed to `compute_average_dev_head_t`. The default would be …
> MRG: Motion Annotation

- Makefile
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
Fixes #7615. This re-enables setting `raise_if_subset` to `False` in 0.20.
> Montage subset hotfix

- doc/changes/latest.inc
- mne/source_space.py
- mne/viz/misc.py
- mne/viz/tests/test_misc.py
Closes #7221.
@christian-oreilly can you try it with your MRIs that are in non-standard orientation? I was able to check that the FreeSurfer-standard ones look okay, but don't have good MRIs to test for non-standard orientations. If you don't have them I could maybe resample these and regenerate BEMs but that sounds like too much work :)
This actually makes our code simpler and easier to read I think, which is nice.
> MRG, FIX: Fix MRI orientations

- mne/inverse_sparse/tests/test_gamma_map.py
All PRs are currently failing due to a `gamma_map` test being too strict about distances:
https://travis-ci.org/github/mne-tools/mne-python/jobs/685787842
This one is only off by 3.6 mm so here we just bump the tol. I cannot reproduce locally so we'll have to see what the CIs say.
It's not clear to me what this is due to, possibly some version bump in mkl ... ?
> MAINT: Bump tol for gamma map test

- doc/changes/latest.inc
- examples/visualization/plot_make_report.py
- mne/report.py
- mne/tests/test_report.py
- mne/viz/_3d.py
- mne/viz/misc.py
- tutorials/source-modeling/plot_forward.py
Should fix the bug mentioned in #7725. @christian-oreilly can you try it with your out-of-standard-ori MRI? I don't have any to test with but in principle I think this should work...
This PR also:
1. Should ensure that we always (by default) proceed through slices in L-to-R, P-to-A, and I-to-S order (previously it depended on the order in of the MRI).
2. Adds orientation markers to the edges of the plots by default (can be disabled with `show_orientations=False`)
3. Points out that there is a redundant and probably also wrong (for non-conform'ed MRIs) function `mne.viz._3d._plot_mri_contours` that we should really refactor with the `mne.viz.misc._plot_mri_contours` -- the function names match and there is a lot of similar code so it's unfortunate that we ended up with two copies, …
> MRG, FIX: Fixes for BEM contours

- mne/viz/raw.py
This just removes the title "Ch." of the vertical (channel) scroll bar. I think it looks cleaner without the title, which can also interfere with annotations/events. It should also be pretty clear even without the title what that scrollbar is.
I also wanted to change the `hsel_patch` to a uniformly transparent filled rect. Currently, this rectangle (which indicates the current position in the scroll bar) has a darker border which isn't really necessary. However, unless someone has an idea how to achieve this (the patch should still extend over the upper and lower scrollbar boundaries) I think it is probably not possible (https://stackoverflow.com/questions/53803531/matplotlib-circle-patch-with-alpha-produces-overlap-of-edge-and-facecolor).
> Minor plot_raw aes improvement

- doc/changes/latest.inc
- mne/io/nirx/nirx.py
Closes #7744
@rob-luke this code only takes 1 sec now, no idea how long it takes on `master` because I lost patience waiting after 30 seconds or so:
```Python
import time
import mne
fnirs_data_folder = mne.datasets.fnirs_motor.data_path()
fnirs_raw_dir = fnirs_data_folder + '/Participant-1'
raw = mne.io.read_raw_nirx(fnirs_raw_dir)
raw.save('/dev/null', verbose='error')
```
> MRG, ENH: Speed up NIRx read without preload

- mne/io/meas_info.py
Make it clearer that people (including devs) shouldn't generally add new stuff to `info`.
> MRG, DOC: Notes about info

- doc/changes/latest.inc
- mne/rank.py
- mne/tests/test_rank.py
- mne/utils/docs.py
Digging through our code, I was a bit surprised to see that the `tol` we apply in `compute_rank` is an absolute one on the singular values (computed after whatever normalization/scaling you have selected). I've added a `tol_kind` option that allows treating this as a relative tolerance.
Another option would be to leave `tol` and add `rtol`, but that's weird because `tol='auto'` (and `tol='float32'`) already only behave as a relative tolerance, because they do the same thing that `pinv` does (scale relative to the max singular val).
Testing with some local MaxFiltered data suggests that it's more robust and flexible than using an absolute ``tol``. I also was able to add it to the dense `test_rank.py` tests without too many modifications/attempts to find a good value, which I can't say …
> MRG, ENH: Add tol_kind option

- mne/stats/parametric.py
- fixes typo "estate" -> "estimate"
- fixes the default value of sigma in `ttest_ind_no_p` to match `ttest_1samp_no_p` (within-cycle change, so no deprecation needed)
- converts hat-adjustment citation in `ttest_1samp_no_p` to use `:footcite:` format.
- adds hat-adjustment citation to `ttest_ind_no_p`
- general docstring improvement of `ttest_ind_no_p`
> DOC: docstring fixes

- .circleci/config.yml
- .travis.yml
- azure-pipelines.yml
- mne/cov.py
- mne/preprocessing/tests/test_xdawn.py
- mne/viz/tests/test_3d.py
Hopefully this now allows our 3.8 on Azure to have VTK!
> MAINT: Clean up VTK and add to pre on Azure

- doc/changes/latest.inc
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/utils.py
- tutorials/io/plot_20_reading_eeg_data.py
> [MRG] split_naming='bids' changes from _part-%d to _split-%d

- doc/changes/latest.inc
- mne/preprocessing/ica.py
> FIX: Correct a bug in find_bads_eog

- doc/changes/latest.inc
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
Closes #7760.
@bloyl can you check to see if it solves your problem? Currently it finds three ref channels bad, no idea if that's sensible. If not, might be worth doing `ignore_ref=True`. Also, it would be good to know in general whether or not this function works for your datasets now that it won't just error out on you :) But we should merge this PR either way as it fixes a clear bug, if it does not work well for your data we might be able to fix it in another PR.
> MRG, FIX: Fix find_bad_channels_maxwell indexing

- .circleci/config.yml
- doc/_templates/autosummary/class.rst
- doc/_templates/autosummary/function.rst
- doc/conf.py
Also modernizes our inclusion of backrefs, and considates CircleCI `apt-get` to a single line.
> MRG, MAINT: Smaller PNGs during doc build

- doc/_static/style.css
- doc/_templates/layout.html
closes #7782 
- adds a call to `versionwarning.js` to the layout template
- styles the links in the resulting devbar
WIP until we iron out the style-related questions in [mne-tools.github.io#20](https://github.com/mne-tools/mne-tools.github.io/pull/20)
> MRG: warning banner for old versions of docs

- mne/stats/cluster_level.py
Minor refactoring to speed up permutation tests. This PR brings about 1~2% speedup (best case 5%).
```python
import time
from mne.stats import permutation_cluster_1samp_test
def large_samples_perm(n_perm=100, n_space=100, n_time=100):
noise_level = 20
n_time_1 = n_time
n_time_2 = n_time
normfactor = np.hanning(20).sum()
rng = np.random.RandomState(42)
condition1_1d = rng.randn(n_time_1, n_space) * noise_level
for c in condition1_1d:
c[:] = np.convolve(c, np.hanning(20), mode="same") / normfactor
pseudoekp = 10 * np.hanning(round(n_space / 2))[None, :]
condition1_1d[:, round(n_space / 2):] += pseudoekp
thresh_tfce = dict(start=0, step=0.2)
permutation_cluster_1samp_test(condition1_1d, threshold=thresh_tfce,
n_permutations=n_perm, tail=0, seed=1,
buffer_size=None)
``` …
> MRG, ENH: Minor speedup of permutation tests

- doc/changes/latest.inc
- doc/python_reference.rst
- examples/preprocessing/plot_fnirs_artifact_removal.py
- mne/preprocessing/nirs/__init__.py
- mne/preprocessing/nirs/_tddr.py
- mne/preprocessing/tests/test_temporal_derivative_distribution_repair.py
- mne/tests/test_docstring_parameters.py
Fixes #7798. I've also made the docstring of the internal `_TDDR` function more Pythonic.
> Alias temporal_derivative_distribution_repair to tddr

- mne/conftest.py
- mne/viz/_3d.py
- mne/viz/epochs.py
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
Latest `matplotlib` complains if `set_x/yticklabels(...)` count does not match the number of ticks, which is reasonable. This PR makes it so that we set them consistently, and tests now pass on my machine other than some issue with `annotations`, which I plan to also fix in this PR (hence the WIP).
> MRG, FIX: Fix tick labeling

- doc/changes/latest.inc
- mne/viz/ica.py
tmin wasn't being passed to the newly constructed epochs object. This is fine if your epochs start at tmin=0, but it displays erroneously if tmin != 0
> [MRG] BUGFIX: new epochs doesn't inherit tmin

- doc/changes/latest.inc
- doc/python_reference.rst
- mne/io/__init__.py
- mne/io/_read_raw.py
- mne/io/tests/test_raw.py
- mne/io/tests/test_read_raw.py
Fixes #7769.
This PR adds `mne.io.read_raw`, which is "just" a wrapper for specific readers. Based on the file extension, the wrapper dispatches known specific readers (and raises an error for unknown file types). I've included a suggested file type in the error message if the user tried to open a wrong file from formats consisting of multiple files (e.g. the BrainVision format has `.eeg`, `.vmrk`, and `.vhdr` files, of which only the last can be opened).
This is a first suggestion, please comment. We should also add a test - any suggestions what the test should do? I thought that we'd use `read_raw` to load each supported file type, and probably also an unsupported one.
> Add wrapper read_raw for specific read_raw_xxx readers

- mne/beamformer/_compute_beamformer.py
- mne/bem.py
- mne/cov.py
- mne/decoding/receptive_field.py
- mne/dipole.py
- mne/epochs.py
- mne/evoked.py
- mne/io/proj.py
- mne/io/tag.py
- mne/label.py
- mne/morph.py
- mne/preprocessing/ica.py
- mne/source_estimate.py
- mne/time_frequency/csd.py
- mne/time_frequency/tests/test_csd.py
- mne/time_frequency/tfr.py
- mne/transforms.py
This PR changes `  |  ` (double spaces) to ` | ` (single spaces) in various reprs to make them consistent with the recently changed reprs for `Annotation`, `Info`, and `Raw`.
> Remove double spaces in reprs

- doc/changes/latest.inc
- examples/inverse/plot_snr_estimate.py
- mne/minimum_norm/inverse.py
- mne/viz/evoked.py
Makes it clearer what the lines correspond to:
> MRG, ENH: Add estimation method legend

- mne/io/meas_info.py
Fixes #7818. @hoechenberger @larsoner @agramfort OK with you?
> Clearer info docstring

- mne/io/tests/test_meas_info.py
Help for #7823
@cbrnr it turns out that there is only one planar grad coil type, then the `ch_name` is used to differentiate one from the other (they are named `MEGXXX2` and `MEGXXX3` by the system). So the behavior in your PR is okay, just confusing because you managed to make one of them end in `2` and the other not. Eventually we should add a note that picking this way only works when names are native / unchanged, but really this is a pretty deep corner case.
> MRG, MAINT: Show how picks work for planars

- doc/changes/latest.inc
- examples/preprocessing/plot_run_ica.py
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- tutorials/preprocessing/plot_40_artifact_correction_ica.py
Implementation in #7815 
After a deprecation cycle, TODO part will replace the current default value 0.25.
If that's ok, I will update `latest.inc`
> MRG, ENH: Automatically compute threshold for CTPS ECG detection

- doc/install/pre_install.rst
Added reference to package [sesameeg](https://pybees.github.io/sesameeg/) into section [install](https://mne.tools/stable/install/pre_install.html) of the documentation.
> DOC: added reference to sesameeg package

- MANIFEST.in
- setup.py
cc @GuillaumeFavelier otherwise icons submodule is missing for people who do python setup.py install
> add icons to source dist

- doc/changes/latest.inc
- examples/preprocessing/plot_find_ref_artifacts.py
- mne/preprocessing/ica.py
- mne/viz/ica.py
- mne/viz/tests/test_ica.py
In playing with the recent ica ref channels artifact rejection (#7810), I'd sometimes have 4-5 score plots in one column, which I couldn't see.
This PR adds a parameter ('n_col') to 'ica_plot_scores' to use a grid with multiple columns.
There is a question about the following from the test.
```ica.plot_scores([0.3, 0.2], axhline=[0.1, -0.1], labels='ecg')```
it fails on this PR and is currently commented out.
On master it passed but did not make a plot, because:
```
if labels == 'ecg':
labels = [label for label in ica.labels_ if label.startswith('ecg/')]
```
returned `labels = []` and nothing was plotted.
I don't know enough about the ica labeling so someone should advice what the correct behavior is and how to test it.
> MRG, ENH: Support n_col keyword in ica.plot_score

- doc/changes/latest.inc
- mne/source_estimate.py
- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/_timeviewer.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/base_renderer.py
This PR adds support for the `foreground` parameter in `_Brain`. This parameter influences the color of the labels displayed (scalar bar label, time label and slider title and label).
Following the example given in https://github.com/mne-tools/mne-python/issues/7842#issue-626271633, this is what I obtain now:
time_viewer=False | time_viewer=True
---|---
Closes https://github.com/mne-tools/mne-python/issues/7842
It's an item of https://github.com/mne-tools/mne-python/issues/7162
> MRG: Add support for foreground in _Brain

- .circleci/config.yml
- examples/decoding/plot_linear_model_patterns.py
- examples/decoding/plot_receptive_field_mtrf.py
- mne/decoding/base.py
- tutorials/machine-learning/plot_sensors_decoding.py
@SherazKhan asked if we had an example of projecting decoder coefficients to source space yet and I didn't think we did. This adds it to the decoding tutorial, and cleans up some refs to use the new footbib magic.
> MRG, ENH: Add example of projection to source space

- doc/changes/latest.inc
- mne/epochs.py
- mne/tests/test_epochs.py
Addresses the first part of #7732
@kingjr can you try it?
> MRG, FIX: Fix bug with metadata and event_repeated

- doc/changes/latest.inc
- examples/inverse/plot_morph_surface_stc.py
- mne/morph.py
- mne/source_estimate.py
- mne/tests/test_morph.py
Closes #7564.
Closes #7007.
@fleurgaudfernau can you see if it works for your use case? For example this code now runs fine:
<details>
<summary>Starter code</summary>
```Python
import mne
data_path = mne.datasets.testing.data_path()
data_dir = op.join(data_path, 'MEG', subject)
bem_dir = op.join(subjects_dir, subject, 'bem')
fname_src = op.join(bem_dir, 'sample-oct-4-src.fif')
fname_aseg = op.join(subjects_dir, subject, 'mri', 'aseg.mgz')
labels_vol = ['Left-Cerebellum-Cortex', 'Right-Cerebellum-Cortex']
src = mne.setup_source_space(subject, spacing='oct4',
add_dist=False, subjects_dir=subjects_dir)
src += mne.setup_volume_source_space(
subject, mri=fname_aseg, pos=10.0, …
```
> MRG, ENH: Add mixed source estimate support to compute_source_morph

- doc/changes/latest.inc
- mne/datasets/testing/_testing.py
- mne/io/fiff/raw.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/tag.py
Closes #7844
With these changes, I can read the file and get the warning:
```
RuntimeWarning: FIF raw buffer could not be read, acquisition error likely: 10000 samples set to zero
```
After some effort messing with bytes in our testing files, I couldn't make a test that actually hits this warning (breaking the tag always broke the `'nent'` for our files). But I did write a consistency test that works for all of our files, and emits the warnings if we add the problematic file to the list of files to test.
> MRG, ENH: Allow reading broken file

- doc/changes/latest.inc
- examples/preprocessing/plot_movement_compensation.py
- mne/epochs.py
I realized that we didn't have an example of evoked movement compensation in our docs. This adds one to the end of the simulation. It also fixes a tiny bug with the weight calculation. In testing it doesn't actually affect the values, but worth doing anyway.
> MRG, DOC: Add evoked movecomp to example

- doc/references.bib
- environment.yml
- mne/datasets/utils.py
- requirements.txt
fixes a 404 link, and converts the docstring to use `footcite` while we're at it.
> DOC: update link to glasser supplementary info; convert to footbib

- mne/beamformer/tests/test_external.py
- mne/conftest.py
- mne/datasets/utils.py
- mne/gui/_coreg_gui.py
- mne/gui/_viewer.py
- mne/tests/test_defaults.py
Keep things green:
1. Update `conftest.py` to deal with new traitsui deprecations that aren't in our code
2. Update some imports for latest traits/traitsui
3. Update testing dataset that is part of #7656 but not ready to be merged, needs to be updated for things like #7863 to further update the dataset
4. Adds SI unit test for `defaults` (showing it's currently wrong for CSD)
> MRG, MAINT: Update dataset and add constant test

- doc/changes/latest.inc
- mne/io/pick.py
- mne/io/tests/test_pick.py
Fixes a bug with `plot_psd` that was introduced by #7486. Basically the order in `picks` was not preserved, which was required by `plot_raw_psd` when there are multiple channel types.
Closes #7837
> MRG, FIX: Fix get_channel_types

- mne/datasets/utils.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
> FIX : EDF+ Annotation Timestamps missing sub-second accuracy

- doc/changes/latest.inc
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
> MRG, ENH: Better error messages for ICA

- doc/changes/latest.inc
- examples/inverse/plot_mixed_source_space_inverse.py
- mne/forward/tests/test_make_forward.py
- mne/source_space.py
- mne/tests/test_source_space.py
Closes #7886.
@susamerz can you see if this takes care of your use case? It allows only filling in the nearest neighbor voxel to the actual source space points for both surfaces and volumes.
I didn't add it to an example because it doesn't look good with the native `nilearn` plotters because it's so sparse...
> MRG, ENH: Add mri_resolution="sparse"
