- doc/_templates/layout.html
- doc/conf.py
- doc/index.rst
closes #7885 
also updates dipy intersphinx redirect to current release (problem still exists), and removes a spurious dash in the CZI entry of the funders box.
> Website contents

- mne/io/ctf/info.py
- mne/io/egi/egi.py
- mne/io/egi/events.py
- mne/io/meas_info.py
- mne/io/tests/test_raw.py
- mne/tests/test_bem.py
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
Just want to make sure all is green on these before pushing.
> MAINT: Backports

- mne/channels/layout.py
Example: Fixes #7893.
Fix ` _auto_topomap_coords docstring` doctring.
> Fix _auto_topomap_coords docstring.

- environment.yml
- requirements.txt
This PR follows https://github.com/mne-tools/mne-python/pull/7791#issuecomment-643749902 and is a step forward towards full migration to `pyvista 0.25` (work in progress in https://github.com/mne-tools/mne-python/pull/7791) while (hopefully) making the CIs green on `master`
> MRG: Pin pyvista to 0.24.3

- mne/io/nirx/nirx.py
- mne/io/nirx/tests/test_nirx.py
Fixes #7894. @Swy7ch noted that the NIRX file reader checks for a dat file, but it is not used.
Instead of failing if the `.dat` is missing this now throws a warning to the user that the file structure has been modified from what the measurement machine saved.
We have had some discussion about what the correct behaviour is. See the above linked issue for discussion.
> MRG: Warn if NIRX directory structure has been modified from original format

- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
- tutorials/preprocessing/plot_60_maxwell_filtering_sss.py
Inspired by https://github.com/mne-tools/mne-study-template/issues/118#issuecomment-630847578, I have added a new parameter `return_scores` to `preprocessing.find_bad_channels_maxwell()`.
If True, we will now return a dictionary with alle the scores, limits, and corresponding channel names and types. 
<strike>
- the edges of the time windows analyzed
- the corresponding evaluation of a channel being flat in this window
- the corresponding evaluation of a channel being noisy in this window
I currently refer to the latter two values as "scores", but actually they are just boolean values. So the returned ndarrays `scores_flat` and `scores_noisy` only contain True and False for each channels in all evaluated time segments. Wonder if there's a better name we could use?
</strike>
I first wanted …
> Allow find_bad_channels_maxwell() to return scores

- Makefile
- ignore_words.txt
Codespell recently added a `usage` dictionary to move toward #7901. This just has us use it, with an exception for `master` for now (no other changes needed for our codebase).
> MRG, MAINT: Check usage

- doc/changes/latest.inc
- doc/changes/names.inc
- doc/overview/faq.rst
- tutorials/source-modeling/plot_fix_bem_in_blender.py
Some updates to the Blender tutorial (#7824) to properly give credit to @ezemikulan. Also updates the link in our FAQ regarding manually fixing BEM meshes.
> Proper attribution for Blender tutorial

- .travis.yml
- azure-pipelines.yml
- mne/beamformer/tests/test_lcmv.py
- mne/channels/tests/test_interpolation.py
- mne/channels/tests/test_montage.py
- mne/inverse_sparse/tests/test_mxne_optim.py
- mne/io/__init__.py
- mne/io/_digitization.py
- mne/io/brainvision/brainvision.py
- mne/io/bti/bti.py
- mne/io/ctf/info.py
- mne/io/edf/edf.py
- mne/io/eeglab/tests/test_eeglab.py
- mne/io/egi/egi.py
- mne/io/egi/egimff.py
- mne/io/fieldtrip/tests/test_fieldtrip.py
- mne/io/kit/kit.py
- mne/io/meas_info.py
- mne/io/tests/test_raw.py
- mne/io/utils.py
- mne/simulation/tests/test_raw.py
- mne/tests/test_chpi.py
- mne/tests/test_surface.py
- mne/viz/tests/test_3d.py
- mne/viz/tests/test_ica.py
Speeds up the H5 info round-trip test by changing some list of dict to dict of array and back (saves 9 sec locally in the BTi test because there are >3k dig points). Eventually we can make use of this in things that use `write_hdf5` if we find that they are slow in practice. I looked and currently TFR seems to be the only place this might be useful but the implementation was not going to be trivial because we support writing lots at once, but we can revisit it later if need be.
Tightens up our use of types to be more consistent across readers (it makes `object_diff` happy but should be a good idea in general).
Also marks a couple more tests as slow that keep showing up in macOS like:
https://travis-ci.org/github/mne-tools/mne-python/jobs/697952162#L3269
> MRG, FIX: Speed up I/O tests, mark some slow

- .circleci/config.yml
- .travis.yml
- azure-pipelines.yml
- environment.yml
- requirements.txt
- tutorials/machine-learning/plot_sensors_decoding.py
Hopefully expose the failure sooner.
> WIP: Fix Travis

- doc/changes/latest.inc
- mne/epochs.py
- mne/evoked.py
- mne/tests/test_epochs.py
Actually check that they have compatible info by reusing the epochs-info-checking function before trying to write them to disk (which can otherwise create problems later with cryptic errors when you try to read them).
> MRG, ENH: Better error message for incompatible Evoked objects

- doc/changes/latest.inc
- examples/inverse/plot_morph_volume_stc.py
- mne/datasets/utils.py
- mne/morph.py
- mne/source_estimate.py
- mne/tests/test_morph.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
- tutorials/source-modeling/plot_beamformer_lcmv.py
We had a bug where `src_to` did not work when the MRI and RAS coordinate frames were not identical. Fortunately they are for fsaverage (hopefully by far the most common destination subject), unfortunately I have never seen them be identical for any other FreeSurfer subject (hopefully a rare destination use case).
WIP because ~~using non-fsaverage subjects is still not totally satisfactory (though they at least now are more reasonable instead of all zero), want to see if there is anything to fix or if it's just a parameter problem at my end.~~ :
> MRG, BUG: Fix bug with volume morph and subject_to!="fsaverage"

- mne/io/nirx/nirx.py
- mne/io/nirx/tests/test_nirx.py
@cbrnr confirmed in #7894 that the NIRX format for saving data is not consistent across devices. I have only added test data for the NIRScout device I have access too. The function now throws a warning if used with an untested device.
Next step is to improve the reader function to work with these alternative formats. But this warning seems prudent until someone with access to these devices adds reader support.
Closes #7913
> WIP: Warn if untested NIRX device

- doc/changes/latest.inc
- examples/inverse/plot_vector_mne_solution.py
- mne/minimum_norm/tests/test_inverse.py
- mne/source_estimate.py
- mne/tests/test_source_estimate.py
- mne/utils/check.py
Useful for:
1. Converting `pick_ori='vector'` solutions to max-power-ori solutions
2. Eventually for `unit-noise-gain` vector beamformers we'll want to do this (probably)
In the beamformer PR, we can also check to see the extent to which `pick_ori='max-power'` agrees with `pick_ori='vector'` followed by `stc.project_onto()`.
> MRG, ENH: Add method to project onto max power ori

- mne/viz/_brain/_timeviewer.py
This PR updates the background and foreground colors of the internal matplotlib figure depending on the palette chosen for `_Brain`.
background="white" | background="black" (default)
----|-----
> MRG: TimeViewer matplotlib figure color

- mne/tests/test_cov.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/_notebook.py
- mne/viz/_brain/_timeviewer.py
This PR adds a controller to the `notebook` backend to set the number of smoothing steps when `time_viewer=True`.
**Issue**
The rendering cell is broken because of the text given by `logger` I think (the name of the backend and the number of iterations for smoothing).
It's part of #7162.
> MRG: Add smoothing controller to TimeViewer for the notebook backend

- doc/python_reference.rst
- mne/surface.py
- mne/tests/test_docstring_parameters.py
> MAINT: Add mne.surface to docstring tests

- .circleci/config.yml
- .travis.yml
- environment.yml
- requirements.txt
VTK 9.0.1 plus Linux wheels are up on PyPi. Unfortunately rendering still appears to be broken on OSX. But in the meantime we should be able to get rid of the `-f vtk.org` stuff.
> MRG, MAINT: Simpler VTK

- doc/changes/latest.inc
- mne/channels/channels.py
- mne/chpi.py
- mne/epochs.py
- mne/io/meas_info.py
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
> MRG, ENH: Automatically fix magnetometers when maxwell filtering

- mne/channels/channels.py
- mne/channels/layout.py
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
closes #7933 
The approach in 1b9ff53 works, in that it yields a correct topo layout for the CSD-transformed EEG data. However, it breaks 3 tests in `mne/viz/tests/test_topo.py` so it's probably not an approach worth keeping.  Other possible approaches:
- add a new return value (`has_eeg_csd_coils`?) to `mne.channels.channels._get_ch_info` rather than hacking it to return `True` for `has_eeg_coils` when only CSD channels are present.
- in `mne.channels.layout.make_eeg_layout`, use a boolean `allow_csd` parameter instead of a `ch_types=['eeg', 'csd']` parameter; and make `eeg=True` always the case in the call to `pick_types` therein.
I'm not very familiar with this part of the codebase, so any suggestions are welcome.
> MRG, VIZ, BUG: handle CSD channel type when topo plotting

- doc/changes/latest.inc
- mne/viz/_brain/_brain.py
- mne/viz/_brain/_timeviewer.py
Fixes the bug with glyph colormap not being updated, tested with:
<details>
```
import mne
sample_dir = op.join(data_path, 'MEG', 'sample')
inv = mne.minimum_norm.read_inverse_operator(op.join(
sample_dir, 'sample_audvis-meg-oct-6-meg-inv.fif'))
evoked = mne.read_evokeds(op.join(sample_dir, 'sample_audvis-ave.fif'))[0]
evoked.apply_baseline((None, 0))
stc = mne.minimum_norm.apply_inverse(
evoked, inv, method='dSPM', verbose='debug', pick_ori='vector')  # 'vector')
initial_time = 0.1
size = (800, 400)
with mne.viz.use_3d_backend('pyvista'):
brain = stc.plot(subjects_dir=subjects_dir, initial_time=initial_time,
clim='auto', views='lat', hemi='lh',
smoothing_steps='nearest', …
```
> MRG, BUG: Fix vector scaling

- doc/install/mne_python.rst
- tutorials/sample-datasets/plot_sleep.py
fixes 2 `[local]` linkcheck errors
> fix linkcheck

- mne/beamformer/tests/test_lcmv.py
- mne/channels/tests/test_interpolation.py
- mne/tests/test_chpi.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/tests/test_3d.py
[We're very close to the 50 minute limit on macOS](https://travis-ci.org/github/mne-tools/mne-python/jobs/703573579#L3294) so mark a few more as `slowtest`.
> MAINT: Skip a few more on macOS

- doc/conf.py
- mne/conftest.py
- mne/viz/backends/_pyvista.py
Okay for you @GuillaumeFavelier ? This seems to be the right way to fix it (?) and it seems to work in a simple testing example:
```
import mne
sample_dir = op.join(data_path, 'MEG', 'sample')
inv = mne.minimum_norm.read_inverse_operator(op.join(
sample_dir, 'sample_audvis-meg-oct-6-meg-inv.fif'))
evoked = mne.read_evokeds(op.join(sample_dir, 'sample_audvis-ave.fif'))[0]
evoked.apply_baseline((None, 0))
stc = mne.minimum_norm.apply_inverse(
evoked, inv, method='dSPM', verbose='debug', pick_ori='vector')  # 'vector')
initial_time = 0.1
size = (800, 400)
with mne.viz.use_3d_backend('pyvista'):
brain = stc.plot(subjects_dir=subjects_dir, initial_time=initial_time,
clim='auto', …
```
> MRG, MAINT: Clean up VTK9 offset array

- doc/changes/latest.inc
- mne/epochs.py
- mne/tests/test_evoked.py
I ran into an issue where I created two Evokeds and their difference (via `combine_evoked()`); say, `e1`, `e2`, and `diff`.
I then wanted to write those Evokeds to a single file via `mne.write_evokeds([e1, e2, diff])`, which [failed](https://app.circleci.com/pipelines/github/mne-tools/mne-study-template/459/workflows/6ae202d0-9190-4192-bdfd-08f3e5f12fa3/jobs/477/steps) with a `ValueError`: "info['bads'] must match'". I looked into the `bads` lists and found that the order of bad channels in `diff` was different from the order in `e1` and `e2`; yet, the set of channels was identical.
While it probably would make sense to figure out where this difference comes from, it also got me thinking that an altered `bads` order shouldn't be a stopper when using `write_evokeds()`, as long as all …
> MRG+1: BUG: info['bads'] order shouldn't matter in write_evokeds()

- mne/io/nirx/nirx.py
- mne/io/nirx/tests/test_nirx.py
In the event that no triggers are sent during a recording (for example a resting state measurement) the event file is not created. This PR only tries to create annotations if the event file is present.
> MRG: Only process NIRX event files if they are present

- doc/changes/latest.inc
- mne/source_space.py
- mne/tests/test_source_estimate.py
`source_space._get_src_nn` assumed a 1-1 mapping between `stc.vertices` and `src.vertices` which broke `stc.project` if `stc` was already restricted to a label or during the forward computation. 
Closes #7932
> [MRG] fix Issue with stc.project after restricting to a label

- doc/changes/latest.inc
- mne/io/ctf/ctf.py
- mne/io/ctf/info.py
- mne/io/ctf/tests/test_ctf.py
Closes #6488 
@Yaocoo @Nichalas can you try it? @Nichalas at least with your test data I can now read it.
> MRG, BUG: Allow ref mags to have a comp grade

- doc/changes/latest.inc
- mne/epochs.py
- mne/tests/test_epochs.py
- mne/utils/mixin.py
- mne/viz/tests/test_epochs.py
Closes #7947
On `master` the snippet [here](https://github.com/mne-tools/mne-python/issues/7947#issuecomment-653166786) I get:
```
Time untouched epochs:    0:00:00.014442
Time concatenated epochs: 0:00:00.457064
```
On this PR:
```
Time untouched epochs:    0:00:00.014059
Time concatenated epochs: 0:00:00.022924
```
So it's still ~2x slower, which I guess is to be expected because `selection` does grow by 2x. This should at least be hopefully acceptable compared to the ~30x slower it is on `master`.
> MRG, ENH: Speed up epochs.copy

- doc/changes/latest.inc
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
Add multiplication and division operators to `AverageTFR`
This enables computing group grand averages from lists using `np.mean`
> mrg: Add scalar mult and div operators for AverageTFR

- doc/changes/latest.inc
- mne/epochs.py
- mne/io/base.py
- mne/tests/test_epochs.py
> [MRG] Fix reject_tmin and reject_tmax for reject_by_annotation in mne.Epochs

- mne/utils/config.py
Updates the pyvista line to (a few examples: CircleCI / Linux / macOS):
```
pyvista:       0.25.3 {pyvistaqt=0.1.1, OpenGL 3.3 (Core Profile) Mesa 18.3.6 via llvmpipe (LLVM 7.0, 256 bits)}
pyvista:       0.25.2 {pyvistaqt=0.1.0, OpenGL 4.5.0 NVIDIA 440.100 via GeForce GTX 650 Ti BOOST/PCIe/SSE2}
pyvista:       0.25.2 {pyvistaqt=0.1.1, OpenGL 4.1 INTEL-14.6.18 via Intel(R) Iris(TM) Plus Graphics OpenGL Engine}
```
Should help us debug OpenGL problems as we move to PyVista. In theory we could do something similar for Mayavi but it would require us to do our own parsing of the OpenGL info dump, which is a pain, so not worth it for now.
> MRG, ENH: Add OpenGL info to mne sys_info

- .circleci/config.yml
- .travis.yml
- azure-pipelines.yml
- doc/install/advanced.rst
- doc/install/mne_python.rst
- doc/install/pre_install.rst
- environment.yml
- requirements.txt
> MRG, DOC: update install instructions

- doc/changes/latest.inc
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
- tutorials/preprocessing/plot_60_maxwell_filtering_sss.py
The current approach to using `find_bad_channels_maxwell()` requires users to manually low-pass filter their data before passing it to the function. This is kind of cumbersome.
This PR, therefore, adds a `h_freq` kwarg that sets the cutoff frequency of an automatically-applied low-pass filter. Passing `h_freq=None` disables filtering. If the input data has already been low-pass filtered, a helpful warning is emitted.
We already have a similar API in `preprocessing.compute_proj_ecg()`, so this change makes things more consistent within the `preprocessing` module.
> Add low-pass filter to find_bad_channels_maxwell()

- mne/viz/topomap.py
- tutorials/evoked/plot_20_visualize_evoked.py
closes #7956 
When the last topomap drawn has low variance and hence no visible contour lines, only one tickmark is drawn on the colorbar, because it uses the *plotted* contours instead of the precomputed contour levels based on vmin/vmax.
https://github.com/mne-tools/mne-python/blob/2965cc3644538c97b297f131bbb46ce9f954ea6f/mne/viz/topomap.py#L1763-L1764
> VIZ, BUG: fix tickmarks in evoked topomap colorbar

- mne/preprocessing/maxwell.py
Try to make the algorithm description more accessible.
> DOC: Try to improve find_bad_channels_maxwell doc

- doc/cited.rst
Just noticed that https://mne.tools/dev/cited.html is a year plus out of date. Updating now, and added another step to the release instructions to update this at release time.
> DOC: Update estimates [skip travis]

- mne/report.py
- tutorials/misc/plot_report.py
When using `Report.parse_folder()`, including the "base directory" (i.e., folder name) in all captions's unnecessarily redundant and impairs legibility. This commit changes the behavior of `Report` such that when `parse_folder()` is used, the base directory name will be stripped from the captions.
> [MRG] Strip base directory name from Report captions when using parse_folder

- mne/report.py
- tutorials/misc/plot_report.py
improves parse of folder for report
> Report parsing

- doc/changes/latest.inc
- mne/report.py
- mne/time_frequency/psd.py
- mne/time_frequency/tests/test_psd.py
This:
```
import os
import mne
raw = mne.io.read_raw_fif(sample_data_raw_file)
raw.plot_psd()
data_path = mne.datasets.brainstorm.bst_raw.data_path()
raw_path = (data_path + '/MEG/bst_raw/' +
'subj001_somatosensory_20111109_01_AUX-f.ds')
raw = mne.io.read_raw_ctf(raw_path).load_data()
raw.plot_psd()
```
Goes from this on `master`:
To this:
@agramfort feel free to try it on https://github.com/mne-tools/mne-study-template/pull/155
> MRG, ENH: Reduce memory usage of Welch PSD

- doc/changes/latest.inc
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/proj.py
In cases where the channels that an applied projector applies to have been removed from the data (pick after apply_proj() call), it should be safe to allow users to remove the projector. Currently we disallow deletion of any "active" (applied) projectors, so this commit adds more flexibility there.
> MRG: Allow removal of active projectors if channels they applied to have meanwhile been dropped

- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
- mne/utils/docs.py
Closes #7978
@sappelhoff @larsoner @agramfort 
I have currently commented out the tests for the complex return type as they don't make sense and thus shouldn't pass.
I could remove them and just leave them as smoke tests or if anyone has a suggestion on what to regression test to I could do that. Just let me know what you think is best.
@drammock I'll admit that I don't know how all the doc linking stuff works so please let me know what needs to be changed.
> WIP: TFR Doc/test changes

- doc/changes/latest.inc
- mne/beamformer/tests/test_lcmv.py
- mne/channels/channels.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/proj.py
Pick'ing may entirely eliminate a certain channel type from the resulting object. However, the list of projectors in `info['projs']` will remain unchanged. This can lead to problems in later processing steps, where situations may arise where one is trying to apply a projector for a channel type that is not present in the data anymore.
**MWE:**
```python
import mne
raw_fname = data_path + '/MEG/sample/sample_audvis_filt-0-40_raw.fif'
raw = mne.io.read_raw_fif(raw_fname, preload=True)
raw.set_eeg_reference(projection=True)
raw.pick_types(meg=False, eeg=True)  # Drop MEG data
raw.plot_projs_topomap()
```
**With `master`:**
A problem arises because although we dropped all MEG data, the MEG projectors are still present.
```python …
```
> MRG: When picking, remove inapplicable projectors

- mne/time_frequency/tfr.py
The `save` method should have a pointer to the function used to read back the data.
> MINOR, DOC: Add See Also

- doc/changes/latest.inc
- mne/chpi.py
- mne/fixes.py
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
- mne/proj.py
- mne/tests/test_proj.py
- mne/utils/docs.py
This adds extended SSS (eSSS) support, whereby you can pass empty-room projectors to `maxwell_filter` to improve the external basis estimation.
This method should be stable enough to use on real data, just WIP because we should publish the method first. If people are curious here is a poster from Biomag 2016:
[Helle_eSSS_poster_Biomag16_160928_final.pdf](https://github.com/mne-tools/mne-python/files/3989780/Helle_eSSS_poster_Biomag16_160928_final.pdf)
> MRG, ENH: Add eSSS

- .circleci/config.yml
- doc/Makefile
- doc/changes/latest.inc
- doc/conf.py
- examples/inverse/plot_source_space_snr.py
- mne/tests/test_import_nesting.py
- mne/utils/docs.py
- mne/viz/_3d.py
- mne/viz/__init__.py
- mne/viz/_brain/__init__.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/_scraper.py
- mne/viz/_brain/_timeviewer.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/tests/test_3d.py
- requirements_testing.txt
- tutorials/source-modeling/plot_mne_dspm_source_localization.py
- tutorials/source-modeling/plot_visualize_stc.py
As @agramfort requested:
Todo:
> MRG, ENH: Scrape traces when available

- doc/changes/latest.inc
- doc/python_reference.rst
- examples/forward/plot_forward_sensitivity_maps.py
- examples/time_frequency/plot_time_frequency_simulated.py
- mne/time_frequency/tfr.py
- mne/viz/__init__.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/tests/test_utils.py
- mne/viz/topomap.py
- mne/viz/utils.py
Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/2708/workflows/e86b53b9-e443-45f8-bc27-108e24b27ad1/jobs/21253. I've wanted this function a few times before when using `pcolormesh`, so might as well make it public.
> MRG, ENH: Add mne.viz.centers_to_edges for pcolormesh

- mne/channels/channels.py
- mne/io/meas_info.py
- mne/utils/docs.py
Closes GH-7813.
Make use of the docdict and replace "date of service" with "date of acquisition". The warning mentioned in #7813 appears in the right place now (and only there). Also specifies correct return types for `.anonymize()`.
> DOC: Rework "anonymization" docstrings

- doc/changes/latest.inc
- examples/preprocessing/plot_interpolate_bad_channels.py
- mne/channels/channels.py
- mne/channels/interpolation.py
- mne/channels/tests/test_interpolation.py
- mne/defaults.py
- mne/forward/__init__.py
- mne/forward/_field_interpolation.py
- mne/forward/_lead_dots.py
- mne/viz/topomap.py
A first necessary step toward #3184 is to make it so that we can use minimum-norm mapping to go from EEG->EEG just like we do for MEG->MEG. To do this, I needed to refactor the minimum-norm mapping functions a bit, and now it's (just about) as easy to map EEG as it is MEG. This made me realize that we could easily provide MNE-based EEG channel reconstruction.
Related issues:
1. `fnirs` someday will hopefully support reconstruction schemes other than `method='nearest'` (currently the only one)
2. It's probably easy to add faster multipole-moment based interpolation for MEG [as well as EEG nowadays](https://www.researchgate.net/publication/342933701_Unified_expression_of_the_quasi-static_electromagnetic_field_Demonstration_with_MEG_and_EEG_signals)
Hence I added the API parameter …
> MRG, ENH: Add method arg to interpolate_bads

- mne/viz/_brain/_brain.py
- mne/viz/_brain/_timeviewer.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/base_renderer.py
This PR follows https://github.com/mne-tools/mne-python/pull/7927#issuecomment-658737474 and uses various solutions to decrease memory consumption:
Feel free to comment on this @larsoner
> WIP: Improve _Brain memory footprint

- doc/changes/latest.inc
- mne/io/proj.py
- mne/utils/docs.py
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
- mne/viz/tests/test_topo.py
- mne/viz/topomap.py
- tutorials/preprocessing/plot_50_artifact_correction_ssp.py
> MRG, ENH: Add proj="reconstruct" option

- environment.yml
Fixes (works around) #8040 hopefully.
> Use pyface < 7

- mne/preprocessing/ica.py
Picard can be used to obtain the same solution as with FastICA, Infomax, or extended Infomax --> and apparently (according to Picard :wink: ) converges faster.
This sounds like a win for me, so I added this to the docs. WDYT?
@larsoner @cbrnr @agramfort @mmagnuski @pierreablin 
Info taken from README: https://github.com/pierreablin/picard
Previously discussed in [gitter](https://gitter.im/mne-tools/mne-python?at=5f16ce4815e5e72fb3679875), Thanks @cbrnr for making me aware of it.
> MRG, DOC: note on using picard for same solution as other algos

- mne/viz/_brain/_brain.py
This PR fixes the way the smoothing matrix is retrieved from internal data and solves the example described in https://github.com/mne-tools/mne-python/issues/8048#issue-664151155
mayavi | pyvista
----------|-----------
Closes #8048
> FIX: smooth_mat logic in _Brain

- environment.yml
- requirements.txt
Until https://github.com/pyvista/pyvistaqt/issues/20 and https://gitlab.kitware.com/vtk/vtk/-/issues/17953 are fixed, we should pin PyQt5 < 5.14 on macOS.
> MRG, FIX: Pin PyQt5 for HiDPI bug

- doc/changes/latest.inc
- doc/conf.py
- doc/install/contributing.rst
- doc/sphinxext/gen_commands.py
- set encoding of "commands.rst.new" to 'utf8',
- do not use memory_profiler on Windows,
- add graphviz as a requirement and the conda command to install it,
- add optipng as a requirement with ways to install it on Linux/MacOS/Windows
> MRG, DOC: get docs to build on Windows

- doc/changes/latest.inc
- mne/viz/evoked.py
When passing a list of Evoked's to `viz.plot_compare_evokeds()`, previously we would assign them sequential numbers (1 … N) as labels, which is … not necessarily too helpful.
But since by default we're also storing useful information about the condition(s) making up the Evoked in `Evoked.comment`, I thought we could make use of this to create more useful labels.
So now, for example, instead of getting this:
we'll be getting this:
without having to pass a dict to `plot_compare_evokeds`.
> Better default legend in plot_compare_evokeds() for list of Evokeds

- doc/conf.py
- doc/python_reference.rst
- mne/datasets/utils.py
- mne/io/__init__.py
- mne/io/snirf/__init__.py
- mne/io/snirf/_snirf.py
- mne/io/snirf/tests/test_snirf.py
- mne/utils/check.py
- tutorials/io/plot_30_reading_fnirs_data.py
#7057 
Adds ability to read NIRS data in the SNIRF format. 
This is becoming the default file format and will become the BIDS approved format.
> MRG: Add SNIRF reader

- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
resampling a raw would convert `raw._last_samps` to a list, which would break `raw.crop` which expected an `np.array`
This bug didn't exist in the last release, so I don't feel like this needs an entry in `latest.inc`. but if you think I should I can add it.
> [MRG] Bug fix - resample would break crop

- mne/io/nirx/nirx.py
- mne/io/snirf/_snirf.py
Follows https://github.com/mne-tools/mne-nirs/pull/146/files/9e103b071bafc988f93cab543f68571ed8ae5cf2#diff-97adcb285086e704b219a0e18ede4576. I noticed I was unable to exactly recreate the channel locations as we had this hack in MNE to deal with bad channel locations stored in nirx files.
Previously "channel" locations were read from the nirx files, and these are the midpoints between light source and detector. But these weren't coded correctly for detectors that were very close to sources, so we just took the source location in that instance. Now I calculate the channel location as the midpoint between source and detector. The result is basically the same, except the result is now consistent even for short channels.
Channels aren't defined for all vendors. So it makes sense to calculate …
> MRG: Manually calculate channel location for NIRS data

- mne/utils/__init__.py
- mne/viz/_3d.py
`plot_source_estimates` and `plot_vector_source_estimates` share 90%+ of their code. This unifies the two approaches into a single `_plot_stc` function.
This will make things like #8064 much easier, as instead of making deep changes in two places, you can make them in one.
> MRG, MAINT: Unify 90% similar code

- mne/epochs.py
- mne/evoked.py
- mne/utils/docs.py
Fixes #8069 .
Fixes the docstrings of BaseEpochs and Evoked, to make the documentation consistent and correct across BaseRaw/BaseEpochs/Evoked
> Fixing inconsistent documentation crop BaseEpochs, Evoked

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/channels/channels.py
- mne/tests/test_epochs.py
Fixes #8070.
Removes keys for dropped channels from `reject` and `flat` when calling `pick_types` in `mne.channels.channels.UpdateChannelsMixin`.
Not sure if this is the right fix, but seems like this was the best way to access `reject` and `flat` when `pick_types` is called from any of `Raw`, `Evoked`, or `Epochs`.
> FIX: pick_types removes keys for dropped channels in reject, flat

- doc/changes/latest.inc
- mne/minimum_norm/inverse.py
- mne/minimum_norm/tests/test_inverse.py
`rank` was only passed to one of two functions that could compute the rank, so you could get a warning about rank deficiency even if you've explicitly set the rank.
> MRG, BUG: Avoid warning about rank when its explicit

- doc/changes/latest.inc
- mne/morph.py
- mne/source_space.py
- mne/tests/test_source_space.py
- mne/utils/_logging.py
It's nice to be able to create a volumetric source space using FreeSurfer's complete `aseg.mgz` definition, without the `Unknown` vertices, like:
```
src_to_fname = op.join(subjects_dir, 'fsaverage', 'bem',
'fsaverage-vol-5-aseg-src.fif')
aseg_fname = op.join(subjects_dir, 'fsaverage', 'mri', 'aseg.mgz')
volume_label = mne.get_volume_labels_from_aseg(aseg_fname)
volume_label.pop(volume_label.index('Unknown'))
assert len(volume_label) == 43
if not op.isfile(src_to_fname):
src_to = mne.setup_volume_source_space(
'fsaverage', 5., 'aseg.mgz', volume_label=volume_label,
subjects_dir=subjects_dir, verbose=True)
```
This creates a source space with 46 entries. A problem with this is that there is a ton of redundant information: the source `rr`, whether used or unused for a give subvol, are part …
> MRG, ENH: Add single_volume option to setup_volume_source_space

- .travis.yml
- doc/changes/latest.inc
- doc/conf.py
- examples/inverse/plot_mixed_source_space_inverse.py
- mne/conftest.py
- mne/defaults.py
- mne/source_estimate.py
- mne/utils/docs.py
- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/_timeviewer.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/_brain/view.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/base_renderer.py
- mne/viz/backends/tests/test_renderer.py
- mne/viz/tests/test_3d.py
- setup.cfg
- tutorials/source-modeling/plot_beamformer_lcmv.py
Closes #7648
@GuillaumeFavelier I think I have this at a point where I've worked out the transformations and data injection:
If you `mne.minimum_norm.write_inverse_operator('mixed-inv.fif', inverse_operator)` the inv operator from the modified `plot_mixed_source_space_inverse.py`, you can iterate with this much quicker script:
<details>
```
import mne
from mne.minimum_norm import read_inverse_operator, apply_inverse
data_dir = op.join(data_path, 'MEG', subject)
fname_evoked = data_dir + '/sample_audvis-ave.fif'
fname_cov = data_dir + '/sample_audvis-shrunk-cov.fif'
fname_trans = data_dir + '/sample_audvis_raw-trans.fif'
condition = 'Left Auditory'
evoked = …
```
> MRG, ENH: Volume rendering

- doc/changes/latest.inc
- mne/stats/cluster_level.py
Use Numba to speed up converting spatiotemporal cluster results into SourceEstimate. This PR brings about 35% speedup.
[left_auditory_vs_visual_0_to_None.npz (~148MB)](https://www.dropbox.com/s/f0rmo1wf5871reu/left_auditory_vs_visual_0_to_None.npz?dl=0)
+ Processed from the `sample` dataset, duplicated to create 7 subjects
+ Used `oct6` source space to compute source estimates then morphed to `ico5` `fsaverage`
+ Sampling rate: 600 Hz
+ Time window: 0-500 ms after stimulus onset
```python
import mne
clu_fname = 'left_auditory_vs_visual_0_to_None.npz'
tstep = 0.0016649601096532323
cluster_result = np.load(clu_fname, allow_pickle=True)
clu = (cluster_result['t_obs'], cluster_result['clusters'],
cluster_result['cluster_pv'], cluster_result['H0'])
stc_all_cluster_vis = …
```
> MRG, ENH: Use numba to speed up summarize_clusters_stc

- doc/changes/latest.inc
- doc/python_reference.rst
- mne/baseline.py
- mne/epochs.py
- mne/evoked.py
- mne/report.py
- mne/tests/test_docstring_parameters.py
- mne/tests/test_report.py
- mne/utils/docs.py
- tutorials/misc/plot_report.py
Add GFP traces to Report
- When plotting Evokeds, add a GFP trace to the sensor traces
- Also add a "GFP-only" comparison plot via `plot_compare_evokeds()`
- Slightly improves coverage of existing tests too
I tested locally with some data, but let's see how CI artifacts come back. Any feedback greatly appreciated.
> [MRG] Add GFPs to report

- mne/io/nirx/nirx.py
- mne/io/nirx/tests/test_nirx.py
- mne/io/snirf/_snirf.py
- mne/io/snirf/tests/test_snirf.py
I am adding a SNIRF writer at https://github.com/mne-tools/mne-nirs/pull/151
The SNIRF standard does not include some info that MNE has such as sex, middle name, last name (SNIRF has only SubjectID). 
To allow writing an MNE NIRS recording and reading it back without any loss, I have added non standard (but allowed) custom metadata tags to the SNIRF writer. In this PR I add reading of these extra values.
I also noticed that unknown sex was not being correctly encoded in the NIRX reader.
> MRG: Add reading of custom MNE info to SNIRF

- mne/annotations.py
- mne/channels/_standard_montage_utils.py
- mne/channels/montage.py
- mne/datasets/utils.py
- mne/io/what.py
- mne/tests/test_annotations.py
- mne/utils/mixin.py
As discussed in #8014, reverts parts of #7635: dict ordering was a CPython implementation detail in 3.6, becoming an official language feature in 3.7, so to be safe let's use OrderedDict until we require 3.7+.
> MRG, MAINT: Go back to OrderedDict

- doc/changes/latest.inc
- mne/report.py
- mne/tests/test_report.py
Fixes a problem with class naming when using `add_bem_to_section` directly instead of `render_bem=True`. Only the name on the left would be hidden by clicking the button, not the content itself.
> MRG, BUG: Fix bug with Report

- doc/conf.py
Nitpicky got more nitpicky and catches a bunch of missing `__hash__` defs. We can just ignore these because we don't want to add these methods, and also don't want to switch to different `class.rst` templates depending on whether or not a given class defines the `__hash__` method.
> MRG, MAINT: Update nitpick_ignore for sphinx

- doc/changes/latest.inc
- mne/cov.py
- mne/epochs.py
- mne/preprocessing/ecg.py
- mne/preprocessing/eog.py
- mne/preprocessing/ica.py
- mne/tests/test_epochs.py
- mne/time_frequency/psd.py
- mne/utils/docs.py
- mne/viz/ica.py
- mne/viz/raw.py
- mne/viz/tests/test_ica.py
Fix #8101 .
Because `reject_by_annotation` in `ica.fit()` defaults to `True`, reconstruction of source in `plot_properties` should take care of that or the error occurs due to the incorrect number of epochs.
**TODO**
- _Fix `ica.plot_properties`_
- _Fix `make_fixed_length_epochs`_
- _Update documentation of `reject_by_annotation` using docdict_
- _Update what's new_
After adding annotations
```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-d42215032b75> in <module>
6 
7 ica.fit(raw)
----> 8 ica.plot_properties(raw, picks=[0, 1])
~/env/mne/lib64/python3.7/site-packages/mne/preprocessing/ica.py in plot_properties(self, inst, picks, axes, dB, plot_std, …
```
> MRG, FIX: Check reject_by_annotation in ica.plot_properties

- doc/changes/latest.inc
- mne/filter.py
- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/tests/test_filter.py
- mne/utils/docs.py
- tutorials/preprocessing/plot_30_filtering_resampling.py
Closes #7577.
Based on some local testing I'm not convinced it works. But @yjmantilla @sappelhoff @mmagnuski if you want to try it just pass `filter_length='10s'` or whatever to `notch_filter`. Maybe this will make it easier for people to test against `cleanline` or other implementations, and/or push fixes.
> MRG, ENH: Use overlap-add in spectrum_fit mode

- mne/viz/backends/_pyvista.py
This PR fixes the bug with the axes in `plot_alignment()`. The visual bug happened because of a pre-processing in the PyVista `glyph()` filter that merges the coincident points. 
I'll see how to avoid this preprocessing if possible in PyVista directly.
Close #8115
> MRG: Patch quiver3d()

- mne/source_estimate.py
When using `extract_label_time_course` with volumes and `mri_resolution=True` (default) and `mode='mean'` (default), for large volumetric regions like `Left-Cerebral-White-Matter` that are part of the LUT you can end up exploding data into a high-res MRI space. If you have 10000 time points, the CSR dot product will be a crazy shape like `(100000, 10000)` and kill memory; and even if it succeeds, it then takes the mean across the first dimension (high-res voxels).
There is a nice shortcut by linearity where the upsampling matrix itself can just be averaged across vertices head of time, so that the CSR dot result is just shape `(1, 10000)`, and the downstream code then takes `np.mean(..., axis=0)` of this as a no-op.
I also made a change from `*` to `@` in the code to make it clear that …
> MRG, ENH: Speed up vol label extraction

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/evoked.py
- mne/source_estimate.py
- mne/tests/test_evoked.py
- mne/tests/test_source_estimate.py
Example: Fixes #8139 
Raises an error when complex VolSourceEstimate.data is saved to formats other .h5
Allows for _write_evokeds_ and _read_evokeds_ writing and reading complex data
I haven't changed _test_evoked.py_ since I did not know whether any of the datasets had complex data to test it on
> ENH: Better complex support for Evoked and SourceEstimate

- mne/viz/_brain/_timeviewer.py
This PR fixes the bugs with slider representation. For instance, when there is no time infos, `self.sliders['time'] = None`.
This causes failure during doc building.
> MRG, FIX: NoneType slider bug

- mne/viz/backends/renderer.py
- mne/viz/backends/tests/test_renderer.py
- tutorials/source-modeling/plot_background_freesurfer_mne.py
This PR adds the parameters `scene` and `smooth_shading` to the public function `create_3d_figure()` to make it more flexible.
Closes https://github.com/mne-tools/mne-python/issues/8154
> MRG: Add some parameters to create_3d_figure

- .github/workflows/ci.yml
- .travis.yml
- mne/beamformer/tests/test_lcmv.py
- mne/conftest.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/backends/_pyvista.py
This PR adds a new GHA workflow running on MacOS.
I use [`setup-miniconda`](https://github.com/marketplace/actions/setup-miniconda) to setup conda to avoid [a permission error on MacOS](https://github.com/actions/virtual-environments/issues/1003#issuecomment-638860704) (for more infos: https://github.com/actions/virtual-environments/issues/1003#issuecomment-638978803)
ToDo:
<details>
<summary>Archive</summary>
I run this workflow on [my `master` branch](https://github.com/GuillaumeFavelier/mne-python/actions) to test it (the easiest solution I found).
Notes:
- `$SPLIT` is not supported (yet?)
why on Travis?
```
- cd ~
- if [ "${DEPS}" != "minimal" ]; then
python -c 'import mne; mne.datasets.testing.data_path(verbose=True)';
fi;
- cd ${SRC_DIR}
```
</details>
Closes #8159
> MRG: Use GitHub Actions to replace Travis MacOS job

- mne/viz/tests/test_epochs.py
Ticking off a few of the last issues from #7057 
Turns out psd topomap already worked due to previous code changes. So I just added a test to ensure it continues working.
> MRG: Test PSD topomap works with NIRS epochs

- tutorials/sample-datasets/plot_sleep.py
In the [example for the Sleep Physionet dataset](https://mne.tools/stable/auto_tutorials/sample-datasets/plot_sleep.html), there is a large class imbalance in favour of wake (W). This is because the recordings in this dataset were collected over longer periods of time and thus there are long periods of awake time before and after the night. It is common practice in the literature to trim the beginning and end parts of the recordings of this dataset to reduce class imbalance (e.g., https://arxiv.org/abs/1703.04046, https://arxiv.org/abs/1610.01683, https://arxiv.org/abs/1710.00633).
Following discussion with @agramfort, this PR modifies the example to only keep the last 30 minutes before the first sleep event and the first 30 minutes after the last sleep event when building the training …
> MRG: Trimming Sleep Physionet recordings to avoid W imbalance

- doc/changes/latest.inc
- examples/inverse/plot_gamma_map_inverse.py
- examples/inverse/plot_mixed_norm_inverse.py
- examples/inverse/plot_time_frequency_mixed_norm_inverse.py
- mne/viz/_3d.py
- tutorials/source-modeling/plot_dipole_fit.py
> MRG, ENH: Add ori on MRI slices

- mne/viz/_brain/_brain.py
- mne/viz/backends/_pyvista.py
This PR reworks lighting in 3d viz scenes:
master | PR
---------|-------
Related to https://github.com/mne-tools/mne-python/pull/6731#issuecomment-532625434
> MRG: Improve lighting in 3D viz

- doc/changes/latest.inc
- examples/inverse/plot_time_frequency_mixed_norm_inverse.py
- mne/viz/_3d.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/_utils.py
- mne/viz/backends/tests/test_renderer.py
Closes #8192
In this PR on mayavi:
pyvista:
these look different but I think it might just be a subtle angle/perspective difference (?), here's a different angle:
@GuillaumeFavelier can you look and see if the difference is meaningful and if necessary push commits to fix it? Also might be a good idea to check the code for any other instances of `if/elif/elif` and change them to `if/elif/else` with an `assert` like I did here (preferably with a user-friendly `_check_option` so that the `assert` is just an internal sanity check).
> MRG, BUG: Fix sphere glyphs

- examples/inverse/plot_mne_cov_power.py
- mne/cov.py
- mne/externals/doccer.py
- mne/utils/docs.py
- mne/viz/misc.py
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
- mne/viz/utils.py
Closes #7384
Closes #8183
- Also adds support for `time_label=''` to avoid having the time printed.
- With a bit of squaring, we get correct units / scale factors / whitening compared to what's in `master`.
> MRG, ENH: Add cov.plot_topomap

- mne/viz/topomap.py
- tutorials/preprocessing/plot_50_artifact_correction_ssp.py
Closes #7993
This bug was in this release so no need for `latest.inc` update. You can see the problem on `master` [here](https://mne.tools/dev/auto_tutorials/preprocessing/plot_50_artifact_correction_ssp.html#repairing-ecg-artifacts-with-ssp):
> MRG, FIX: ch_type in plot_projs_topomap

- doc/changes/latest.inc
- mne/channels/tests/test_montage.py
- mne/forward/forward.py
- mne/utils/check.py
- mne/utils/docs.py
- mne/viz/misc.py
- mne/viz/tests/test_misc.py
Closes #6905
@AKMeunier @rderollepot can you see if this works for you?
Regarding being able to ignore the existing warning, you can now do `verbose='error'` if you really want to also ignore the `event 2 missing from event_id will be ignored` warnings.
> MRG, ENH: Add on_missing to plot_events

- doc/changes/latest.inc
- doc/references.bib
- examples/decoding/plot_decoding_csp_eeg.py
- examples/decoding/plot_decoding_csp_timefreq.py
- mne/decoding/csp.py
- mne/decoding/tests/test_csp.py
Resolves #8074.
1. Add new parameter to `CSP` to select  how to order components.
2. Add additional tests to make sure nothing broke.
3. (optional) Refactoring
- Moved duplicated data type check into `_check_Xy`.
- Split `.fit()` into smaller functions for improved readability.
I left the refactoring in for now because I already made it.
You may to prefer not to have these changes in order to keep the code closer to the original from pyRiemann.
Let me know :)
> CSP component order selection

- doc/changes/latest.inc
- examples/inverse/plot_vector_mne_solution.py
- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- tutorials/source-modeling/plot_visualize_stc.py
Close #7911
On `master`, auto control points for the vec STC are `[1.86911522 2.26944519 6.37046324]` and standard STC are `[ 3.95048065  4.56941314 17.72451438]`. On this PR, there are two fixes:
1. `vector_alpha` actually has an effect
2. `_process_clim` uses the `.magnitude()` data for vector mode, which makes more sense.
On this PR, this code:
<details>
```
import mne
sample_dir = op.join(data_path, 'MEG', 'sample')
inv = mne.minimum_norm.read_inverse_operator(op.join(
sample_dir, 'sample_audvis-meg-oct-6-meg-inv.fif'))
evoked = mne.read_evokeds(op.join(sample_dir, 'sample_audvis-ave.fif'))[0]
evoked.apply_baseline((None, 0))
stc = mne.minimum_norm.apply_inverse(
evoked, inv, …
```
> MRG, BUG: Fix STC limit bug

- mne/viz/backends/renderer.py
#8194 introduced changes to `mne.viz.backends._utils.VALID_3D_BACKENDS`.
Now, if `viz.backends.renderer._get_3d_backend()` cannot find a valid backend, the string formatting
doesn't work (`VALID_3D_BACKENDS` is a tuple, and we're trying to format the string with only a single `%s`.
This commit not only fixes that, but improves formatting ever so slightly.
@agramfort This is the reason why our scheduled study-template CI run failed last night.
> [MRG] BF: String formatting in exception message

- doc/changes/latest.inc
- tutorials/source-modeling/plot_source_alignment.py
Ok here is the linear algebra of how the transform happens. I think it's useful for developers but it's a bit hard to visualize without putting up some mayavi/matplotlib 3D figures with just points on them which would be far below the rest of the example quality-wise. If there is a way to plot it that looks nice, I could add that. I'm not sure if it'd be useful to print details about the scaling or anything but it does explain how I understand the transform to work. If that's helpful to have in docs then great, if this isn't good enough to be merged that would be understandable too.
Addresses https://github.com/mne-tools/mne-python/issues/7081
> [MRG, DOC] Added linear algebra of transform to doc

- examples/visualization/plot_eeglab_head_sphere.py
- mne/channels/layout.py
- mne/channels/tests/test_channels.py
- mne/viz/tests/test_raw.py
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
- tutorials/intro/plot_40_sensor_locations.py
Fixes #7341 
Currently all channels are projected to a sphere so the sphere radius does not take any effect. If we don't project to a sphere the sphere radius changes the channel positioning with respect to head outline: 
However this means that channel positions that are not spherical, like EGI (or standard_1020) do not look so good because we no longer project to sphere.
One way to circumvent this would be to project to sphere and then scale channel positions by the average channel pos radius (currently each channel is scaled by its own radius, so the channels are no longer on a sphere).
> FIX: do not project to sphere; DOC - explain how to get EEGLAB-like topoplots

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/io/edf/edf.py
Speedup the processing of the channel data in EDF+ TAL format through vectorizing the code.
This speedup tackles the time bottleneck when a RawEDF object is created.
Note: experimental results on private datasets yielded a speedup of 100-150x on EDF+C and EDF+D files of 20 - 360 MB when calling mne.io.read_raw_edf.
Author: Jeroen Van Der Donckt (IDLab Ghent University - imec)
> MAINT: vectorize _read_annotations_edf

- doc/changes/latest.inc
- mne/channels/channels.py
- mne/channels/tests/test_channels.py
- mne/io/base.py
- mne/io/brainvision/brainvision.py
- mne/io/cnt/cnt.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/edf/tests/test_gdf.py
- mne/io/egi/egimff.py
- mne/io/egi/tests/test_egi.py
- mne/io/eximia/tests/test_eximia.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/kit/kit.py
- mne/io/kit/tests/test_kit.py
- mne/io/nirx/nirx.py
- mne/io/snirf/_snirf.py
- mne/io/tests/test_raw.py
- mne/io/utils.py
I wanted to add a tiny test to #8176 to ensure `_mult_cal_one` is used properly, but I found out it's not used properly in a number of existing readers. Basically it means (I think) that for all readers for a non-preloaded `raw`:
1. For all readers, `raw.apply_proj().load_data().get_data()` was broken (fix WIP)
2. For all readers, `raw.apply_proj().pick(...)` was broken (now disallowed; we didn't allow this until this release cycle so not so bad)
3. For some readers (definitely EDF/GDF, maybe CNT, maybe BrainVision), `_mult_cal_one` was not used properly, so projectors were not applied when data were not preloaded
This sounds bad, but `(1)` hopefully isn't too common a practice, (2) is within-release and probably rare, and (3) affects formats where using projections are less common (and …
> MRG, BUG: Fix errors in IO/loading/projectors

- doc/changes/latest.inc
- mne/utils/config.py
- mne/utils/progressbar.py
- mne/utils/tests/test_progressbar.py
Closes #8096
@mmagnuski want to give it a try?
> MRG, ENH: Allow setting tqdm backend

- doc/changes/latest.inc
- environment.yml
- mne/viz/backends/_utils.py
- requirements.txt
This PR follows https://github.com/mne-tools/mne-python/pull/8116#issuecomment-688680649 and sets PyVista as the default 3d backend.
AFAIK, coreg is the last big part of the codebase still not ported to pyvista and is next in my todo list.
> MRG: Set pyvista as default 3d backend

- doc/changes/latest.inc
- mne/coreg.py
- mne/tests/test_coreg.py
- mne/viz/_brain/_brain.py
Before:
After:
Ignore the fact that the `pial` surface is messed up for this subject.
Also changes the default volume surface to `pial`
> MRG, BUG: Fix scaling for src_mri_t in coreg

- mne/io/nirx/nirx.py
- mne/io/nirx/tests/test_nirx.py
Extract measurement date and birthday for NIRX files.
The vendor software only allows saving of age as an integer. So I have taken the measurement date, subtracted the age integer from the years, and stored that as the birthday. Open to alternative suggestions.
> MRG: Extract measurement date and age for NIRX files

- doc/glossary.rst
- mne/preprocessing/ica.py
- tutorials/evoked/plot_whitened.py
> MRG, DOC: Fix ICA docstring, add whitening

- mne/io/nirx/nirx.py
in #8066 I removed a hack for calculating the position of short channels (where the source and detector are very close together). I left in some code that is doing nothing. Specific lines are [here](https://github.com/mne-tools/mne-python/pull/8066/files#diff-7c077bb43fb6aa0bdda5f6c0cdd99863L255-L257)
Removes unused code
I am surprised linting didnt pick this up, I will be more cautious in the future.
> MRG: Remove unused code

- mne/time_frequency/_stockwell.py
- mne/time_frequency/multitaper.py
- mne/time_frequency/tfr.py
Partly fixes #8215
Changed multitaper functions description which were wrongly
described as using Morlet wavelets
Also explained the connection between the functions:
tfr_multitaper vs tfr_array_multitaper
tfr_morlet vs tfr_array_morlet
tfr_stockwell vs tfr_array_stockwell
> Updated doc for time frequency analysis functions

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/chpi.py
- mne/tests/test_chpi.py
None
Optimizes window length for cHPI amplitude estimation by accounting for the line frequency and its harmonics. The change primarily helps separate higher HPI coil frequencies from nearby line harmonics, but it should also improve robustness for more standard HPI frequencies (e.g. 83 Hz).
> FIX: Improve optimization of "auto" cHPI time window

- mne/source_estimate.py
Fixes #8238.
Takes into account vertices from both hemispheres of source space object.
Not included in tests yet (as discussed before with @larsoner).
> FIX: Fix for PR #8238 _prepare_label_extraction

- mne/channels/layout.py
- mne/utils/_logging.py
- mne/utils/tests/test_logging.py
- mne/viz/topomap.py
- mne/viz/utils.py
Adapted from https://github.com/mne-tools/mne-python/pull/8100#issuecomment-690088012:
```
import mne
raw = mne.io.read_raw_kit('010409_Motor_task_coregist-export_tiny.con')
raw.info['bads'] = ['MEG 099']
mne.set_log_level('debug', add_frames=5)
raw.plot_sensors()
raw.plot_psd()
```
Produces the same plots for both now:
We were missing a `dev_head_t`. I don't see an easy way for testing this since it's buried down in our PSD plotting code.
Also adds some nice debugging scaffolding allowing tracing of `logger` calls, the script above (because of the `add_frames=5') gives the output:
<details>
```
┌channels.channels:593
├viz.utils:1694
├viz.utils:1765
└viz.topomap:669 :              Generating pos outlines with sphere [0.00746787 0.01529428 0.         0.08327344] from [-0.00426583 …
```
> MRG, BUG: Fix topomap plotting

- .coveragerc
- mne/conftest.py
- requirements_testing.txt
Hopefully should help diagnose recent [Travis timeouts](https://travis-ci.org/github/mne-tools/mne-python/jobs/726048452). For example locally:
```
$ pytest mne/utils/ mne/preprocessing/ mne/io/
...
=================================================================== slowest 20 test modules ====================================================================
74.66s total   mne/preprocessing/tests
37.59s total   mne/io/fieldtrip/tests
33.01s total   mne/io/fiff/tests
26.45s total   mne/io/eeglab/tests
12.42s total   mne/io/egi/tests
7.85s total   mne/io/tests
7.00s total   mne/io/edf/tests
6.49s total   mne/io/bti/tests
6.07s total   mne/io/ctf/tests
3.04s total   mne/io/brainvision/tests
2.82s total   mne/io/kit/tests
2.77s total   mne/io/artemis123/tests
1.86s total   mne/utils/tests …
```
> MAINT: Show test timings

- doc/_includes/forward.rst
- doc/install/mne_c.rst
- doc/overview/faq.rst
- mne/morph.py
- updates a few URLs to explicitly use https
- changes xcode url, the old one was an appstore redirect that won't even load on non-macs
> maybe improve linkcheck?

- .travis.yml
- mne/viz/backends/_pyvista.py
- mne/viz/backends/renderer.py
This PR aims at reducing the time used by PyVista 3d viz tests. This is still a work in progress.
Try:
Closes https://github.com/mne-tools/mne-python/issues/8242
> Reduce pyvista viz test time

- mne/conftest.py
- mne/viz/tests/test_3d.py
- mne/viz/tests/test_3d_mpl.py
This PR:
1. moves mpl/nilearn-based volume plotting from `mne/viz/tests/test_3d.py` to new `mne/viz/tests/test_3d_mpl.py`
2. uses 4 rather than 3 levels of path depth for summary in `pytest-harvest`
It gives us a bit more granularity when looking at our timing results:
```
$ pytest mne/viz/
...
=================================================================== slowest 20 test modules ====================================================================
88.73s total   mne/viz/tests/test_3d.py
55.27s total   mne/viz/_brain/tests/
41.67s total   mne/viz/tests/test_3d_mpl.py
38.52s total   mne/viz/tests/test_ica.py
17.48s total   mne/viz/tests/test_epochs.py
15.28s total   mne/viz/tests/test_raw.py
14.64s total   mne/viz/tests/test_topomap.py
12.63s total   mne/viz/tests/test_evoked.py
11.28s …
```
> MRG, MAINT: Move tests

- doc/changes/latest.inc
- doc/conf.py
- doc/python_reference.rst
- mne/channels/layout.py
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/coreg.py
- mne/io/_digitization.py
- mne/tests/test_docstring_parameters.py
- tutorials/misc/plot_ecog.py
Alternative to #7709.
Closes #7709.
@adam2392 I think this is a better fix -- basically we expose a way to get the transformation that is applied when doing `raw.set_montage` so it  can be used later. This way, all of the coordinate frames (head and MRI) are correct according to our definitions, when possible.
@jeschj01 this simplifies a bit / shows you what I suggested that you do on gitter. Will be useful for #8190 and other ECoG/sEEG-related stuff.
> MRG, ENH: Add compute_native_head_t

- mne/defaults.py
- mne/source_estimate.py
- mne/utils/docs.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/view.py
- mne/viz/backends/_pyvista.py
- tutorials/source-modeling/plot_beamformer_lcmv.py
1. Change some defaults so that colors are more visible/true
2. Change one class so that setting the interpolation mode actually has an effect (for `vtkImageResample`, setting to nearest neighbor for example did nothing, now it does)
3. Change `roll` param for `axial` view to correct it
`master:`
PR:
EDIT: Updated with silhouette:
> MRG, ENH: Tweak vol plot defaults

- mne/epochs.py
- mne/evoked.py
- mne/minimum_norm/inverse.py
- mne/source_space.py
- mne/viz/tests/test_evoked.py
- tutorials/source-modeling/plot_forward.py
- tutorials/source-modeling/plot_mne_solutions.py
- tutorials/source-modeling/plot_visualize_stc.py
Closes #8241
The goal is to reduce memory usage -- we'll see what CircleCI reports here vs on `master`. But some relevant test timings locally on master:
```
45.42s total   mne/minimum_norm/tests/
37.23s total   mne/tests/test_source_space.py
21.81s total   mne/forward/tests/
0.00s total   mne/forward/_make_forward.py
```
This PR:
```
47.28s total   mne/minimum_norm/tests/
37.83s total   mne/tests/test_source_space.py
20.52s total   mne/forward/tests/
0.00s total   mne/forward/_make_forward.py
```
So it looks like removing the `preload=True` from the `read_source_space` code (which was causing memory usage jumps in the hundreds of MB range) seems to be okay
> MRG, MAINT: Reduce memory usage of examples

- doc/changes/latest.inc
- doc/glossary.rst
- mne/conftest.py
- mne/minimum_norm/inverse.py
- mne/source_estimate.py
- mne/source_space.py
- mne/tests/test_source_estimate.py
- mne/tests/test_source_space.py
- mne/utils/docs.py
- tutorials/source-modeling/plot_visualize_stc.py
1. Add memory usage for SourceEstimate and SourceSpaces
2. Use native memory types for source space label info (no need to upcast to float, this requires 2x mem)
3. Add option to `prepare_inverse_operator` to avoid copying `src` as it can be hundreds of MB (this is pretty minor and I doubt users will care, mostly it helps internally with `apply_inverse`, so no `latest.inc` update)
4. Add "maximum intensity projection" to our glossary
5. Minor tweaks to `plot_visualize_stc.py` which is our latest [CircleCI failure culprit](https://app.circleci.com/pipelines/github/mne-tools/mne-python/3705/workflows/ad776bdf-33b0-4f7c-b08b-47c0c225403b/jobs/22337)
> MRG, ENH: Reduce memory usage

- doc/changes/latest.inc
- mne/evoked.py
- mne/tests/test_evoked.py
Add Evoked.tmin, Evoked.tmax properties for more consistency with Epochs.
This was originally a part of GH-8156.
> ENH: Add Evoked.tmin, Evoked.tmax

- .circleci/config.yml
- .gitignore
- doc/carousel.inc
- examples/forward/plot_left_cerebellum_volume_source.py
- examples/inverse/plot_covariance_whitening_dspm.py
- examples/inverse/plot_custom_inverse_solver.py
- examples/inverse/plot_mixed_norm_inverse.py
- examples/inverse/plot_multidict_reweighted_tfmxne.py
- examples/inverse/plot_rap_music.py
- examples/inverse/plot_vector_mne_solution.py
- examples/visualization/montage.py
- examples/visualization/plot_make_report.py
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
- tutorials/intro/plot_40_sensor_locations.py
- tutorials/misc/plot_report.py
- tutorials/source-modeling/plot_beamformer_lcmv.py
- tutorials/source-modeling/plot_compute_covariance.py
- tutorials/source-modeling/plot_dipole_fit.py
- tutorials/source-modeling/plot_forward.py
- tutorials/source-modeling/plot_mne_dspm_source_localization.py
- tutorials/source-modeling/plot_mne_solutions.py
- tutorials/source-modeling/plot_visualize_stc.py
- tutorials/stats-source-space/plot_stats_cluster_time_frequency_repeated_measures_anova.py
Another round. This time I cut down `plot_mne_dspm_source_localization` to deduplicate its content with other examples/tutorials, and removed a bunch of `verbose='error'`s that we no longer need.
> MRG, MAINT: Lower memory again

- .github/workflows/ci.yml
- doc/changes/latest.inc
1. Adds `[ci skip]` and `[skip github]` support to our GitHub CI
2. Moves new contributor lines to the top, selected by [looking at names.inc in this diff](https://github.com/mne-tools/mne-python/compare/6f34b24032d2337ea5782c724079563274b6ece7...b96a760bc133f31715fa383b0a5b5999ae9aa564)
3. Bolds new contributor names
4. Moves new contributor changes to the top of each section
5. Renames "changelog / bug / API" to "enhancements / bugs / API changes" as these are more human-readable
> MRG, STY: Highlight new contributors [skip travis]

- mne/utils/config.py
- mne/utils/tests/test_config.py
Python 3.8's `platform.platform()` automatically maps the Darwin version to the correct macOS version, which is typically what we want in `sys_info()`. Make things consistent (and more useful) across all supported Python versions by  doing this mapping manually on Python <3.8.
`master` on Py3.6:
```
In [2]: mne.sys_info()
Platform:      Darwin-19.6.0-x86_64-i386-64bit
```
`master` on Py3.8:
```
Platform:      macOS-10.15.6-x86_64-i386-64bit
```
-----------
PR branch on on Py3.6:
```
Platform:      macOS-10.15.6-x86_64-i386-64bit
```
PR branch on Py3.8:
```
Platform:      macOS-10.15.6-x86_64-i386-64bit
```
> MRG: ENH: Nicer platform string on macOS w/Python < 3.8

- doc/changes/latest.inc
- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
Fixes errors of the form:
```
mne/viz/_brain/_brain.py:564: in add_data
self.set_data_smoothing(self._data['smoothing_steps'])
mne/viz/_brain/_brain.py:1270: in set_data_smoothing
self.set_time_point(self._data['time_idx'])
mne/viz/_brain/_brain.py:1346: in set_time_point
grid.cell_arrays['values'][vertices] = values
../pyvista/pyvista/core/pyvista_ndarray.py:43: in __setitem__
super().__setitem__(key, value)
E   ValueError: shape mismatch: value array of shape (150,1) could not be broadcast to indexing result of shape (150,)
```
> MRG, FIX: Fix single handling

- doc/_static/style.css
- doc/index.rst
- doc/overview/index.rst
@rob-luke pointed out that our stable page lists 0.21.dev0 as the version on the right:
This refactors the landing page to use the `|version|` substitution. It also uses more built-in RST to render rather than quite as much `.. raw:: html` which actually makes things a bit cleaner I think (e.g., make our docs slightly better if we ever want to build latex).
> BUG: Fix version on landing page

- doc/_static/style.css
- doc/carousel.inc
- examples/inverse/plot_vector_mne_solution.py
- mne/tests/test_docstring_parameters.py
- mne/utils/docs.py
- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/_scraper.py
- mne/viz/_brain/_timeviewer.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/utils.py
- tutorials/source-modeling/plot_beamformer_lcmv.py
- tutorials/source-modeling/plot_mne_dspm_source_localization.py
- tutorials/source-modeling/plot_visualize_stc.py
Eventually it would be nice to have animations play for some of our source modeling examples. I plan to:
Not 100% sure it will work or produce movies of a reasonable size, but it would be pretty cool if it worked.
> MRG, ENH: Add brain movies to rendered examples

- mne/utils/docs.py
crossref #7206 (especially [this comment](https://github.com/mne-tools/mne-python/pull/7206#issuecomment-581697291))
The goal is to change default from `'ms'` to `None`. In this PR I'm only changing docstring, not raising a warning if the current default is passed.  I suppose I could change the default to `None` and have `None` temporarily mean `'ms'`, and add temporarily a valid argument `'s'` to get the behavior currently intended by `None`, and raise a warning if the value is `None` rather than `'s'` or `'ms'`?  But at least some people have learned that explicitly passing `None` is what they should do (e.g., #8044) so IMO raising a warning in that way would cause more confusion than it might avert.
> MRG, API: prep for to_data_frame default argument change

- mne/channels/layout.py
The `_merge_nirs_data` function is used in topo plotting and averages channels that are close together for a nicer display. After a channel is merged it is then removed from the data. If the same channel was merged twice, then it was removed twice, but the second time it was removing legitimate data. This would then mean the size of data and pos was incorrect and a nice error was thrown in the following topo function (which made it easy for met to find this bug).  Here I just ensure each channel is only removed once.
I think this is a candidate for back port. Whats involved in that?
I found this error because I am considering proposing a different distance for merging channels, but that's an enhancement and I will put in another PR. But it means others aren't likely to hit this bug unless …
> MRG: Fix bug in nirs merge data

- mne/epochs.py
- mne/utils/docs.py
I have received questions regarding the interaction between baseline correction and the `reject` parameter of `Epochs` (answer: there is none), leading me to believe that the docs could be improved.
> MRG: DOC: Better "reject" documentation

- doc/changes/latest.inc
- examples/decoding/plot_receptive_field_mtrf.py
- mne/decoding/time_delaying_ridge.py
I remembered that the edge correction was actually a painfully slow step in the Fourier method. Using Numba reduces the total example time from 7.2 to 6.1 sec on my system.
> MRG, ENH: Speed up time_delaying_ridge using Numba

- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
Some cherry-picks from #8328 
- add more validation
- fix bug if `max_pca_components` is a float
- remove redundant `max_pca_components ` argument from `ICA._fit`
- handle `max_pca_components=1.0` like `max_pca_components=None`
- make test cases more independent by avoiding side effects through repeated `ICA.apply()`'ing to the same object
> MRG: ENH, BUG: Minor ICA cleanups

- doc/changes/latest.inc
- doc/glossary.rst
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- mne/utils/tests/test_numerics.py
Closes #8325 
Closes #8308
Closes #7657
> MRG, FIX: Test round-trip, fix EEGLAB ICA

- doc/changes/latest.inc
- mne/viz/ica.py
`ICA.plot_overlay()` didn't seem to work on my system with latest Matplotlib anymore (macOS, both the default and Qt5Agg backends). I would only see black traces, instead of red and black. Debugging showed that changig the colors of lines in a figure (in this case, from black to read) that has
been `show()`n was somehow part of the problem. Now we only `show()` once all plotting operations are done (We call `plt_show(show)` at the end of the plotting function), and this now works with the default macOS and the Qt5Agg backends for me.
> MRG, BUG: Fix line color in ICA.plot_overlay

- doc/changes/latest.inc
- mne/viz/tests/test_evoked.py
- mne/viz/utils.py
We should only internally do `tight_layout(...)` calls when axes were not created using `constrained_layout=True`. Our current code gets a matplotlib warning about disabling the `constrained_layout` of the axes.
Also fixes a bug where we would raise as error instead of re-emit as a warning
> MRG, BUG: Fix handling of axes with constrained_layout=True

- doc/changes/latest.inc
- mne/epochs.py
- mne/evoked.py
- mne/utils/_logging.py
- mne/utils/docs.py
- mne/utils/tests/test_docs.py
> MRG, BUG: Force keywords for verbose in short sigs

- doc/_static/diagrams/ica.dot
- doc/changes/latest.inc
- mne/epochs.py
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- mne/utils/__init__.py
- mne/utils/docs.py
- mne/viz/ica.py
- mne/viz/tests/test_ica.py
- tutorials/preprocessing/plot_40_artifact_correction_ica.py
Todo:
Closes #8337
Closes #8342
Closes #8327
Closes #8328 
Closes #8316
Closes #8313
Closes #7727
Closes #8353
> MRG, API: Deprecate max_pca_components

- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- mne/viz/backends/_pyvista.py
This PR disables the rendering call each time a mesh is added to the scene in favour of only one call when everything is setup.
Quoting https://github.com/pyvista/pyvista/pull/935#issue-500086898:
> There are 2 main reasons for this:
> - Huge speed gain when hiding and displaying meshes.
> - It looks much more professionnal when clicking a button to see all the changes at once.
> WIP: Fix bugs in Brain

- doc/changes/latest.inc
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- mne/utils/docs.py
- mne/viz/tests/test_ica.py
- tutorials/preprocessing/plot_40_artifact_correction_ica.py
> MRG, API: Deprecate n_pca_components in init

- doc/changes/0.21.inc
@SophieHerbst got lost because after an MNE update,`mne.channels.find_ch_connectivity` and `mne.channels.read_ch_connectivity` were gone. Turns out these functions were renamerd, and this change was mentioned in the changelog indeed, but apparently not explicitly enough. Searching the docs for the function name wouldn't bring up helpful results either. This PR explicitly lists all `*connectivity` functions that have been renamed to `*adjacency` in the changelog, so it should be easier to discover these changes.
> MRG, DOC: Make clear which functions have been renamed

- doc/_static/style.css
`master`:
this PR:
Thanks @opyh for tracking this down!
> MRG, DOC: Fix API documentation rendering in Webkit

- mne/fixes.py
decovered as working on sklearn master
> fixes for new sklearn

- mne/conftest.py
- mne/defaults.py
- mne/preprocessing/tests/test_ica.py
- mne/viz/__init__.py
- mne/viz/_figure.py
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
- tutorials/raw/plot_30_annotate_raw.py
- tutorials/raw/plot_40_visualize_raw.py
This is an element of #7751. It defines new classes:
- `MNEFigParams` (a simple attribute container)
- `MNEFigure` (wrapper for `matplotlib.figure.Figure` with our params added)
- `MNEBrowseFigure` (Figure class for raw.plot, ica.plot, epochs.plot)
So far just laying down the infrastructure, none of the instance methods are actually using the new classes yet.  If anyone wants to play around with it:
```python
import os
import mne
plt.ion()
raw = mne.io.read_raw_fif(sample_data_raw_file, verbose=False)
fig = mne.viz.raw.plot_raw_alt(raw)
print(fig.mne.ax_help)  # etc
```
> MRG, VIZ, MAINT: figure class proof-of-concept

- doc/changes/latest.inc
- examples/visualization/plot_roi_erpimage_by_rt.py
- mne/viz/epochs.py
> MRG, BUG, VIZ: Fix overlay times

- doc/changes/latest.inc
- doc/python_reference.rst
- mne/__init__.py
- mne/source_estimate.py
- mne/surface.py
- mne/tests/test_source_estimate.py
- tutorials/misc/plot_ecog.py
Closes #7787.
I don't work with ECoG data so I don't know how sensible this is. @adam2392 can you see if this is something that ECoG people would be interested in? Here is what the tutorial image looks like on my machine:
Todo:
> MRG, ENH: ECoG plotting on pial

- doc/changes/latest.inc
- mne/source_estimate.py
- mne/tests/test_source_estimate.py
- mne/utils/docs.py
I started working on `labels_to_stc` for VolSourceEstimate / volumetric atlases, and I realized that we don't actually need the `trans` argument of `extract_label_time_course` because we can always easily reconstruct the `src[0]['rr']` in MRI space using the `src[0]['shape']` and `src[0]['mri_src_t']`. This deprecates `trans` in `extract_label_time_course`, though I'm half tempted just to leave it in as an argument since it doesn't hurt anything to include it and it's possible at some point in the future we might want it.
It was introduced as an argument only in 0.21, which is sad, and a fast turnaround for deprecation. So maybe we should actually backport this so that people using 0.21.1 get the warning and just remove `trans` from their code sooner.
> MRG, API: Remove trans

- doc/changes/latest.inc
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
- tutorials/misc/plot_ecog.py
- tutorials/preprocessing/plot_70_fnirs_processing.py
Fixes a bug introduced by #7747
> MRG, BUG: Fix plot_alignment

- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/backends/_pyvista.py
This PR adds a context manager to toggle interactivity during movie in Brain.
This is still a work in progress, I got some warnings in `save_movie` if the user interacts:
```
WARN| vtkInteractorStyleTrackballCamera (0x563558f5de30): no current renderer on the interactor style.
```
@larsoner this is what I tried so far
Closes https://github.com/mne-tools/mne-python/issues/8363
> MRG: Toggle interaction with context manager

- mne/io/nihon/nihon.py
related #8385 
In #8385, the user wants to read an unsupported file 'EEG-1200A V01.00'. The problem is that it first tries to read the channel labels (which in this file version are more than in the supported versions) and it raises a `IndexError`.
This fixes this issue by extending the list of channel labels as needed. Now the error is as expected:
```ValueError: Not a valid Nihon Kohden EEG file (EEG-1200A V01.00)```
Issue #8385 expects the data to be read. However, in order to have that kind of fix, more information on the internals of the data format are needed.
> Add fix to give a proper error message when an unsupported Nihon Kohden file is read.

- mne/bem.py
- mne/forward/_compute_forward.py
Just some tiny improvements to the BEM and forward code as I was reading it. The changes are self-explanatory for the most part. @larsoner let me know if this looks good to you.
> tiny cosmetic improvements to BEM code

- examples/visualization/plot_3d_to_2d.py
- mne/viz/_3d.py
- mne/viz/backends/_pyvista.py
This PR follows https://github.com/mne-tools/mne-python/pull/8379#issuecomment-714558278 and fixes at least `plot_3d_to_2d.py`
> FIX: focalpoint

- mne/viz/_brain/_brain.py
This PR fixes the issue of `stc.plot` whith `show_traces='separate'`.
> FIX: separate MPL canvas

- mne/io/reference.py
This came up on gitter: https://gitter.im/mne-tools/mne-python?at=5f92ad30c990bb1c39277c8d
When users add a previously unknown reference channel using `add_reference_channels`, the channel is initialized as a vector of zeroes. No actual re-referencing takes place, however the log messages confusingly print: 
> EEG channel type selected for re-referencing Applying a custom EEG reference
This PR suppresses that confusing log message.
> fix: do not log about re-referencing when no such thing is done

- doc/changes/latest.inc
- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
> ENH: add Brain.set_time(time_in_seconds)

- mne/viz/_brain/tests/test.ipynb
I intended to backport from `master` but this PR fixes the issue with the notebook test.
> FIX: notebook attribute name

- mne/annotations.py
- tutorials/intro/plot_20_events_from_raw.py
Added some cross-references and we're now using `annotations_from_events` in the tutorial – a function which I only came across accidentally, as it wasn't mentioned anywhere in the docs.
> DOC: Better Annotations docs

- mne/viz/_figure.py
- tutorials/intro/plot_20_events_from_raw.py
fix a bug I introduced in #7955
> MRG, BUG, VIZ: min annotation duration

- doc/changes/0.21.inc
I was confused when I looked at the website with the stable version docs, opened Whats New, and saw changes for 0.21.1. Couldn't find that release anywhere, until I realized: oh, right, it hasn't been released yet! This PR makes that clear in the changelog.
> DOC: 0.21.1 is yet to be released

- .circleci/config.yml
- .travis.yml
- azure-pipelines.yml
- mne/conftest.py
- mne/viz/_brain/tests/test_notebook.py
- mne/viz/backends/_notebook.py
- mne/viz/tests/test_3d.py
This PR adds the `brain_gc` fixture in remaining 3d viz tests.
Closes #8403 
I ran the tests locally using master versions of `pyvista` and `pyvistaqt`. Maybe some adjustments are necessary.
> MNT: use brain_gc fixture in some tests

- doc/changes/latest.inc
- mne/epochs.py
- mne/tests/test_epochs.py
In `master` and 0.21 it's possible to preload `Epochs`, apply baseline correction, and (seemingly) remove it again via `apply_baseline(None)`. This should not be allowed: removing BL correction can only happen as long as the data has not been loaded.
> [MRG] BUG: Do not allow baseline removal after preload

- doc/changes/latest.inc
- mne/channels/tests/test_layout.py
- mne/io/meas_info.py
- mne/io/reference.py
- mne/io/tests/test_meas_info.py
- mne/io/tests/test_reference.py
- mne/preprocessing/ica.py
As mentioned in #8400. Exposed bugs in `set_bipolar_reference` and `ICA` keys, so worth a backport.
> MRG, BUG: Ensure channel entries are valid

- .travis.yml
- azure-pipelines.yml
Let's see if we can remove our problematic version pinning. I can't remember why we needed it 2 months ago, but I'm sure the CIs will remind me (and I'll look back if they fail).
> CI: Allow latest numpy

- examples/visualization/plot_topo_customized.py
This is a small fix for an example by @dengemann, where labels of a subplot weren't being set correctly.
> fix setting xlabel and ylabel in example

- doc/changes/latest.inc
- mne/label.py
- mne/morph.py
- mne/tests/test_source_estimate.py
- tutorials/source-modeling/plot_visualize_stc.py
Closes #8438.
@ChristinaZhao feel free to try it with your data
> MRG, ENH: Add volumetric support to labels_to_stc

- doc/changes/latest.inc
- examples/datasets/plot_opm_data.py
- examples/preprocessing/plot_movement_detection.py
- examples/visualization/plot_eeg_on_scalp.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
- tutorials/intro/plot_40_sensor_locations.py
- tutorials/misc/plot_seeg.py
- tutorials/source-modeling/plot_eeg_no_mri.py
- tutorials/source-modeling/plot_source_alignment.py
Issue #8445
Reduce maximum alpha to be 0.75 in plot_alignment to aid viewing of electrodes inside the brain and skull (mostly sEEG). Also edits a few tutorials to see the new outputs of circleCI
The goal currently is to see how these look in the tutorial examples so that we can decide whether this is the best strategy or to use an autodetect (of whether sensors are inside the surface) method instead.
> [WIP] Add transparency to plot_alignment 

- doc/changes/latest.inc
- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/preprocessing/stim.py
@larsoner I am curious how you would approach this.
Basically currently if you use bids split naming convention even if you don't need to split it will add a _split-01 in the first file.
do we have a way to detect early if the file will be split?
> MRG, BUG: fix writing with bids naming when no split is needed.

- doc/changes/latest.inc
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
Fixes: #8451 
Adds `DigMontage.get_positions()` that would allow a full roundtrip with `make_dig_montage`. More importantly it obtains the DigMontage ch positions, coordinate frame and fiducials.
Adds a unit test. 
~~For some reason the coordinate frame changes when using the template.~~ 
~~Is it safe to say we should have `get_positions` always return things in `coord_frame=head`? If so, what's suggestion to fix the unit test with the template that transforms unknown coordframe to the head coord_frame?~~ Now obtains the original coordinate frame.
> [MRG] Getting ch positions from DigMontage via get_positions()

- mne/conftest.py
- mne/viz/tests/test_raw.py
Takes care of failures in `master` like:
https://travis-ci.org/github/mne-tools/mne-python/jobs/740934132
The real bug was just that the selection was wrong. This caused the figures not to be closed, which triggered another test to fail. So this adds a root-level `autouse=True` fixture that does `plt.close('all')` at the end of each test. In testing with no figures open `plt.close('all')` took < 1 uS, and with ~2500 tests we're adding on the order of 1 ms extra test time which is fine to have the added security of each test starting with no figures open.
> TST: Cleaner matplotlib testing

- examples/inverse/plot_label_source_activations.py
- tutorials/misc/plot_seeg.py
Closes: #8428 
Links the `plot_seeg.py` tutorial to other tutorials that will put into context how to:
1. work with BEM surfaces
2. work with different volumetric plotting options
3. work with FreeSurfer transformations and their different volumes
> [MRG] Fixing documentation for plot_seeg and adding some tutorial links.

- .travis.yml
- examples/inverse/plot_label_source_activations.py
- ignore_words.txt
- mne/beamformer/tests/test_lcmv.py
- mne/channels/tests/test_montage.py
- mne/conftest.py
- mne/inverse_sparse/tests/test_mxne_inverse.py
- mne/io/artemis123/artemis123.py
- mne/io/curry/tests/test_curry.py
- mne/io/persyst/tests/test_persyst.py
- mne/io/tests/test_meas_info.py
- mne/io/tests/test_reference.py
- mne/tests/test_chpi.py
- mne/tests/test_source_estimate.py
- mne/tests/test_source_space.py
- mne/utils/tests/test_check.py
- mne/viz/tests/conftest.py
Fixes a bug pointed out by @Aniket-Pradhan on Gitter, restores our CI config such that it should catch the problems fixed by #8474, and catch the bugs fixed here.
Locally things pass with `MNE_SKIP_TESTING_DATASET_TESTS=true` so hopefully all is green here and we can merge and backport.
> MRG, TST: Need to skip properly

- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/utils.py
following issues in mne study template as we write files called
_split-01_raw.fif 
in the derivatives folder.
> less stringent check in _construct_bids_filename (req by derivatives)

- mne/source_estimate.py
- mne/tests/test_source_estimate.py
- mne/utils/docs.py
#8232
Baseline-correction for source estimates is recommended/necessary for some processing steps. For example, for unsigned source estimates, differences in noise levels may result …
> WIP: STC baseline correction

- mne/viz/utils.py
This makes it so that the list of sensors returned by `plot_sensors(..., kind='select')` will continue to be updated by figure interactions even if `block=False`. It restores previous behavior that was broken by #7955.
> MRG, FIX: retain reference to lasso.selection without blocking

- doc/changes/latest.inc
- mne/report.py
- mne/tests/test_report.py
Better split file handling in Reports: don't "report" on any splits but the first.
cc @agramfort, wdyt?
> MRG: Better split file handling in Report.parse_folder()

- doc/changes/latest.inc
- mne/report.py
- mne/tests/test_report.py
This should fix the error on Circle
> [MRG] FIX #8486, Evoked and Epochs don't get split

- environment.yml
- requirements.txt
PyVista released `0.27.0` recently and some adjustments seem necessary to fix:
```
mne/tests/test_report.py::test_render_add_sections[pyvista] Traceback (most recent call last):
File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/pyvistaqt/plotting.py", line 699, in _close
super().close()
File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/pyvistaqt/plotting.py", line 476, in close
BasePlotter.close(self)
File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/pyvista/plotting/plotting.py", line 2739, in close
if self.iren is not None:
File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/vtkmodules/qt/QVTKRenderWindowInteractor.py", line 335, in __getattr__
raise AttributeError(self.__class__.__name__ +
AttributeError: …
```
> MNT: Pin pyvista

- doc/overview/faq.rst
- mne/epochs.py
- mne/filter.py
- mne/io/base.py
- mne/source_estimate.py
Came up in Gitter: [November 9, 2020 6:40 PM](https://gitter.im/mne-tools/mne-python?at=5fa97f0fd37a1a13d6975c37)
(@cbrnr feel free to push to this branch if you want to make this PR bigger in scope.)
For "resampling", MNE automatically applies anti-alias filters where appropriate. This small doc addition will clarify the situation for many users.
I was unsure about it personally, and tried looking into the source code ... but even from there it's not immediately obvious that anti-alias filtering is done. It seems to me like most of the magic is happening here:
I am still not sure that the filtering is truly done - but it may happen in the frequency domain code somehow.
https://github.com/mne-tools/mne-python/blob/bb16a3e6ea99024e468fa84c2ec55c344b47df7e/mne/cuda.py#L291-L340
> [DOC] add link to resampling FAQ to all resampling methods

- doc/changes/latest.inc
- doc/conf.py
- doc/install/contributing.rst
- mne/datasets/limo/limo.py
- mne/viz/_brain/_scraper.py
- tutorials/evoked/plot_eeg_erp.py
Fixes #8501
There are a few problems preventing docs from building on Windows. This PR is intended to fix them. As of now, it solves three out of four problems described in #8501.
> DOC: get docs to build on Windows

- mne/externals/pymatreader/pymatreader.py
pymatreader received a fix to properly load mat files of version 4.
> update pymatreader to version 0.0.24

- doc/changes/latest.inc
- mne/epochs.py
- mne/utils/__init__.py
- mne/utils/_testing.py
- mne/utils/docs.py
- mne/viz/__init__.py
- mne/viz/_figure.py
- mne/viz/epochs.py
- mne/viz/ica.py
- mne/viz/raw.py
- mne/viz/tests/test_epochs.py
- mne/viz/tests/test_figure.py
- mne/viz/tests/test_ica.py
- mne/viz/tests/test_raw.py
- mne/viz/tests/test_utils.py
- mne/viz/utils.py
- tutorials/epochs/plot_20_visualize_epochs.py
- tutorials/preprocessing/plot_40_artifact_correction_ica.py
- tutorials/raw/plot_40_visualize_raw.py
this is an element of #7751 
Basically working already, though needs testing and maybe some cosmetics.
> MRG, VIZ, MAINT: Use new figure class for epochs.plot and ICA.plot_sources

- mne/source_space.py
- mne/tests/test_morph.py
I am still annoyed by how slow the volumetric morphing is, so I decided to see if I could alleviate one bottleneck, namely the linear and zero-order interpolations. I never 100% understood Matti's volume interpolation code I adapted so many years ago, but based on how it works it should definitely be faster when we have lots of volumes to morph. Whether it's already the same speed as dipy and nibabel (scipy.ndimage) or faster with 1, 10, 100, or 1000 volumes remains to be determined, but I wouldn't be surprised if it were about the same speed with even just 1. It definitely will be with 1000.
In any case, to move toward being able to use the sparse matrix code I:
1. Refactored our `_add_interpolator` code to do a generic grid-to-grid interpolation
2. Added tests showing equivalences …
> MRG, MAINT: Refactor volume interpolation code

- doc/changes/latest.inc
- mne/io/edf/edf.py
- mne/io/edf/tests/test_gdf.py
Fixes #8511. It seems like we neither implemented nor tested this feature. Let's see if existing tests pass, I'm going to add a specific test next.
> Exclude GDF channels

- doc/changes/latest.inc
- mne/datasets/brainstorm/bst_auditory.py
- mne/datasets/brainstorm/bst_phantom_ctf.py
- mne/datasets/brainstorm/bst_phantom_elekta.py
- mne/datasets/brainstorm/bst_raw.py
- mne/datasets/brainstorm/bst_resting.py
- mne/datasets/utils.py
- mne/decoding/ssd.py
- mne/report.py
- mne/utils/__init__.py
- mne/utils/check.py
- mne/utils/docs.py
- mne/utils/progressbar.py
- mne/utils/tests/test_check.py
- mne/utils/tests/test_progressbar.py
- tools/circleci_download.sh
Closes #8513
@ftadel can you give this branch a shot? Marking as `backport-candidate` so that we can backport then release 0.21.2 to make things easier once we get everything working (hopefully quickly!).
> MRG, ENH: Improve MATLAB compat

- mne/conftest.py
> Don't treat IPython warning as error (fixes debugging in PyCharm)

- mne/channels/tests/test_interpolation.py
- mne/preprocessing/tests/test_xdawn.py
- mne/viz/ica.py
Forward-porting minor changes from #8496. No need for `latest.inc` updates since these are really just value tweaks for maintainability.
> MRG, BUG: Fix Xdawn check

- examples/decoding/plot_ssd_spatial_filters.py
- mne/decoding/ssd.py
- mne/decoding/tests/test_ssd.py
This PR implements a few post-merge fixes to #7070 for issues pointed out by @agramfort [cc @vpeterson]
@agramfort I put inverse_transform -> NotImplemented and propose to call it ``apply_array`` as this API works with arrays, not instances. I will personally do not have the bandwidth to implement a proper ``apply`` as far more handling of channels types will be needed. Note that CSP has got no ``apply`` method and XDawn's apply is like ICA in supporting instances.
Perhaps @vpeterson wants look into extensions in the future. For now I suggest let's focus on what necessarily has to be fixed.
> [FIX] some post-merge fixes for SSD

- doc/changes/latest.inc
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/io/_digitization.py
- mne/utils/_testing.py
As discussed with @agramfort, there is no need to have this restriction. Simultaneously makes things more DRY and removes two `# XXX` comments from our code, which is nice.
> MRG, ENH: Allow saving non-head cf in mon.save

- examples/inverse/plot_morph_volume_stc.py
- mne/morph.py
- mne/tests/test_morph.py
1. Reduce time in `examples/inverse/plot_morph_volume_stc.py`, which is a pretty representative case, when doing `precompute=True` on my machine from 5:32 to 3:23
2. Fix bug introduced by #8462 where `as_volume` did not produce the correct output shape (with unit test added)
3. Make testing of `_grid_interp` a bit more complete
I also opened a dipy issue to see if they're interested in using these techniques to get speedups at their end: https://github.com/dipy/dipy/issues/2293
> MRG, ENH: Speed up morphing

- mne/viz/utils.py
closes #7850 
- `plot_sensors` now puts title as axes title instead of `fig.suptitle`
- the on_pick callback now won't act unless the click was in the correct axes
> MRG, VIZ, FIX: plot_sensors title and interactivity

- examples/visualization/plot_eeglab_head_sphere.py
fixes example that was broken by #8536
> fix example

- .github/workflows/circle_artifacts.yml
- .github/workflows/codespell_and_flake.yml
- .github/workflows/compat_minimal.yml
- .github/workflows/compat_old.yml
- .github/workflows/linux_conda.yml
- .github/workflows/linux_pip.yml
- tools/github_actions_dependencies.sh
- tools/setup_xvfb.sh
In some of the GitHub Actions they warn that the meaning of `ubuntu-latest` will change from `18.04` to `20.04` at some point. This PR sets them explicitly to 20.04 for all but the `old` build. This really shouldn't matter for us too much since it's up to the upstream compiled libraries to work on older OSes. I hope this also fixes the 3.9-pre failures we've been getting when running `sys_info`. If it appears to, I'll probably restart that run a few times before merging to evaluate more thoroughly.
> CI: Use 20.04

- mne/channels/channels.py
- mne/channels/tests/test_channels.py
- mne/io/array/tests/test_array.py
- mne/io/edf/tests/test_edf.py
- mne/io/meas_info.py
- mne/io/pick.py
- mne/io/tests/test_pick.py
- mne/preprocessing/tests/test_ica.py
expands the entries in `get_channel_type_constants()` to include coil types and units, so they can be used in `create_info`.
> MRG, MAINT: deduplicate definition of FIFF constants

- mne/viz/tests/test_3d.py
Takes care of warnings in latest `master` of `matplotlib`:
```
mne/viz/tests/test_3d.py:538: in test_plot_dipole_mri_orthoview
ax = plt.subplot(111)
...
E   matplotlib._api.deprecation.MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
```
Also removes a few now-redendant `plt.close` calls.
> MRG, BUG: Dep warn from mpl

- doc/references.bib
we don't need DOI, URL, ePrint, and eLocationID (eLocationID link gen is broken anyway, at least for bioRXive). Better would be to fix the upstream bib style so that if DOI is present the others are suppressed, but for now this is good enough.
> MAINT: fix linkcheck

- doc/changes/latest.inc
- mne/datasets/utils.py
- mne/io/kit/constants.py
- mne/io/kit/kit.py
- mne/io/kit/tests/test_kit.py
@UrbanM simplifying your example to get rid of all of the `scalings` stuff and doing:
```
python -ic "import mne; mne.io.read_raw_kit("data.con").plot()"
```
You'll notice that the scale bar for EEG data is 40 uV. Your plot from version 0.20 had a pretty wild `400000.0 uV` scale bar which suggests things were wrong there, too (although at least they were non-zero!).
This almost certainly isn't correct, unless I got very lucky -- I need to dig into why your `exg_gains` are all zero. And if those are being read correctly as zero, what the actually correct fallback gain is to use. Can you browse these data in some KIT (or other) software and let me know what the correct voltage of some value in some EEG channel at some time is supposed to be? For example, E14 at 28.77 seconds seems to be the …
> MRG, BUG: Fix support for KIT Berlin

- doc/install/contributing.rst
- ignore_words.txt
- mne/channels/tests/test_montage.py
This small PR follows https://github.com/mne-tools/mne-python/pull/8547#issuecomment-732278372 and is an attempt to adjust to `codespell 2.0.0` released recently.
> MAINT: Adjust to codespell 2.0.0

- mne/gui/_backend.py
Fixes #8525 by setting the environment variable before launching GUIs.
> FIX:  qt5 macOS 11 compatibility

- mne/viz/epochs.py
- mne/viz/tests/test_epochs.py
This fixes missing scalebars (toggled by pressing `'s'`) on epochs plots, and adds a test that would have caught their missingness.
> VIZ, FIX: epochs.plot() scalebars missing

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/meas_info.py
- mne/tests/test_morph.py
1. Implements a variant of @a-hurst's code from #8544 (most of the PR)
2. Fixes dipy decorator (1 line)
3. Fixes str-as-int parsing from `gitter` (1 line)
4. Adds stub test with `XXX` for carrying over `edf_info['subject_info']` to `raw.info['subject_info']`, which we should probably do to the extent possible (but in another PR)
@a-hurst the one thing I didn't follow was (what is keeping this WIP from my end):
> My only other change was adding recording_info=meas_id, to the edf_info.update() call further down so the recording info gets carried over to the final Raw object.
Can you take a look, and clarify what needs to change in / be added to this PR? And let me know if you're happy with the GitHub URL I put for your name link?
@sappelhoff @cbrnr can you look to see if this makes sense in …
> MRG, BUG: Fix EDF header parsing

- tutorials/discussions/plot_background_filtering.py
- tutorials/source-modeling/plot_background_freesurfer.py
A couple of tutorials link to `sample-data` (which resolves to "Writing examples" via matplotlib intersphinx) instead of `sample-dataset`.  This fixes it, and adds a new URL to the 'fsaverage' tutorial along the way.
> DOC: fix crossrefs; add fsaverage details link

- mne/utils/docs.py
This adds a note to the docstring for most `picks` parameters, reminding users that explicitly passing a bad channel name or index will result in that bad channel being included.  It also slightly refactors the picks docdict entries to make it easier to see what is included in each, and fixes a tiny bug where a space is missing between a word and a `(`.
note that the docstrings for ICA viz functions that have picks parameters do not get this reminder, since they refer to components, not channels.
> DOC: update docstring for picks

- mne/viz/backends/_pyvista.py
- mne/viz/tests/test_3d.py
This PR adds the `brain_gc` fixture in `test_process_clim_plot` (I missed it in https://github.com/mne-tools/mne-python/pull/8427) and fixes the issues with memory:
```
_______________________________________________________________________________ ERROR at teardown of test_process_clim_plot[pyvista] _______________________________________________________________________________
mne/conftest.py:522: in brain_gc
assert len(bad) == 0, 'VTK objects linger:\n' + '\n'.join(bad)
E   AssertionError: VTK objects linger:
E     vtkXOpenGLRenderWindow
E     vtkGenericRenderWindowInteractor
E   assert 2 == 0
E     +2
E     -0
```
It's also important for https://github.com/mne-tools/mne-python/pull/8335 (that's how I discovered the issue in the first place)
> MNT: Add brain_gc fixture to test_process_clim_plot

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/decoding/csp.py
Fixes #8579.
Just add a transpose to correct the CSP filters plot.
> FIX: Transpose issue of CSP.plot_filters

- doc/overview/faq.rst
a couple of links in the FAQ are mis-formatted, this fixes them.
> DOC: fix FAQ formatting bugs

- doc/changes/latest.inc
- mne/viz/topomap.py
- tutorials/epochs/plot_20_visualize_epochs.py
failure to pass through `ch_type` was the culprit; the underlying plotting function thought everything was 'eeg'.
> MRG, FIX, VIZ: correctly triage extrapolation mask for topos based on channel type

- doc/changes/latest.inc
- mne/datasets/testing/__init__.py
- mne/datasets/testing/_testing.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
Fixes #8582. EDF/BDF/GDF files can contain invalid LP/HP filter settings (cutoff frequencies for HP can be greater than the one for LP). This PR (1) issues a warning and (2) sets HP/LP values for affected channels to `None`.
> Detect/correct invalid HP/LP settings in EDF/BDF/GDF

- doc/changes/latest.inc
- mne/preprocessing/ecg.py
- mne/preprocessing/tests/test_ecg.py
MWE:
```python
import os
import mne
mne.set_log_level('error')
raw = mne.io.read_raw_fif(sample_data_raw_file)
_, _, avg_hr = mne.preprocessing.find_ecg_events(raw=raw)
print(avg_hr)
_, _, avg_hr = mne.preprocessing.find_ecg_events(raw=raw, tstart=120)
print(avg_hr)
```
This PR:
```
61.78988748454362
63.91261368728932
```
`master`:
```
61.78988748454361
36.296157683228415
```
> MRG, BUG: find_ecg_events() didn't respect tstart when calculating average heart rate

- examples/inverse/plot_time_frequency_mixed_norm_inverse.py
- mne/viz/_3d.py
- mne/viz/_brain/tests/test_brain.py
This PR fixes hemi logic in stc.
Closes https://github.com/mne-tools/mne-python/issues/8609
> FIX: vertices

- mne/viz/evoked.py
closes #8583 
closes #8597 (supersedes)
removes `set_tight_layout` from our internal evoked plotting code. This was a problem for users who were providing their own axes to `evoked.plot()`. Also tweaks the figure margins that we set when axes are not provided, to approximate what tight_layout would have yielded.
This is a short-term fix; soon evoked plots will use our new figure classes anyway.
cc @eort
> VIZ, MAINT: remove set_tight_layout from evoked plotting code

- doc/changes/latest.inc
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/egi/egi.py
- mne/io/kit/coreg.py
- mne/io/kit/kit.py
Let's just be explicit about the encoding on disk everywhere by naming some constants for each reader.
Closes #8616
@Aniket-Pradhan can you see if this branch fixes the issues? FYI we're going to release 0.22 in the next couple of weeks if it matters for packaging purposes. so it might be worth
> MRG, BUG: Explicit read endianness

- examples/connectivity/plot_sensor_connectivity.py
- mne/viz/backends/_pyvista.py
As @BarryLiu-97 pointed out in https://github.com/mne-tools/mne-python/issues/8625#issuecomment-740486402, there is a regression in the `pyvista` 3d backend making the point labels hardly visible. This PR fixes the issue.
> FIX: point_labels

- doc/changes/latest.inc
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/gui/_kit2fiff_gui.py
- mne/io/_digitization.py
- mne/io/kit/coreg.py
- mne/io/kit/kit.py
- mne/io/tests/test_meas_info.py
- mne/utils/docs.py
- Remove `mne.io._digitization._read_dig_points` and `_set_dig_kit` in favor of `mne.io.kit.coreg._read_dig_kit` and `_set_dig_kit`. The first function just reads files based on names that typically (I'm assuming) come with KIT machines to work the same way as it did before with KIT coreg, etc. The second does transforms necessary to get in the correct coondinate system. This is similar to how things work with CTF, and makes `_digitization` cleaner. The `_kit` functions now only show up in `io/kit` and `gui/*kit*`.
- Add `on_header_missing` to `read_polhemus_fastscan` because some of our testing files and such do not produce this header, and it's possible there are files in the wild that the KIT people are using that have this feature.
Part of #7591. @christianbrodbeck can you look since …
> MRG, MAINT: Remove _read_dig_points

- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
Another little issue @GuillaumeFavelier (pretty sure I added this one...)
> MRG, BUG: Pass kwargs

- mne/minimum_norm/tests/test_resolution_matrix.py
Fixes #8635.
Tests for norm in test_resolution_matrix() now loop over multiple options (not just 'norm').
> FIX: fixed loop over norm PSF/CTF options

- doc/changes/latest.inc
- mne/defaults.py
- mne/gui/_coreg_gui.py
- mne/gui/_viewer.py
- mne/viz/_3d.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/_utils.py
- tutorials/source-modeling/plot_source_alignment.py
plot_alignment does not use the colors used in coreg. It should be consistent. This is just an example that leads to something like this:
as opposed to master:
FYI this is obtained with this script:
```
import mne
from mne.viz import set_3d_backend
from mne.viz._brain.view import views_dicts
set_3d_backend("pyvista")
raw_fname = data_path + '/MEG/sample/sample_audvis_raw.fif'
subjects_dir = data_path + '/subjects'
trans = data_path + '/MEG/sample/sample_audvis_raw-trans.fif'
info = mne.io.read_info(raw_fname)
fig = mne.viz.plot_alignment(info, trans, subject=subject, dig=True,
meg=[],
coord_frame='mri',
subjects_dir=subjects_dir,
surfaces=['head-dense']) …
```
> MRG, ENH: make plot alignment use defaults for colors

- mne/epochs.py
- mne/preprocessing/ecg.py
- mne/preprocessing/eog.py
- mne/preprocessing/ssp.py
- mne/proj.py
- mne/utils/docs.py
- mne/viz/misc.py
- tutorials/preprocessing/plot_50_artifact_correction_ssp.py
- ECG revents correspond to R wave peaks
- Ordinate label should be in singular, i.e. "Event id" instead of "Events id" – unless we want consistency with the `events_id` dict, but then it should be called "events_id"… which doesn't make too much sense to me
- improve some SSP docstrings
> MRG: Small fix to tutorial; rename plot_events ordinate label to "Event id"; improve some SSP docstrings

- examples/inverse/plot_source_space_snr.py
- examples/inverse/plot_vector_mne_solution.py
- mne/viz/_brain/_brain.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/_utils.py
- mne/viz/backends/tests/test_renderer.py
- tutorials/misc/plot_seeg.py
- tutorials/source-modeling/plot_visualize_stc.py
This PR fixes the issue following https://github.com/mne-tools/mne-python/pull/8576 about the scalar bar especially when `transparent=True`.
> FIX: scalar_bar

- doc/changes/latest.inc
- mne/viz/_figure.py
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
> VIZ, ENH: allow show/hide annotations by label

- mne/conftest.py
- mne/tests/test_coreg.py
- mne/utils/config.py
- server_environment.yml
I really just want to add `nibabel` and `nilearn` to our `server_environment` because they are needed for some viz functions, but then I noticed some other stuff, so this PR will:
1. Add `nibabel` and `nilearn`
2. Remove `vtk_dev` channel
3. Remove `defaults` channel
4. Remove the `numpy<1.19.0` pin
Hopefully it all works but if it doesn't, hopefully I can at least get (1) in there. I'll need to double-check that the env otherwise looks the same in terms of what gets installed by looking at `mne sys_info`.
> MRG, MAINT: Improve server env

- doc/conf.py
- examples/preprocessing/plot_eeg_csd.py
- requirements_doc.txt
sphinxcontrib-bibtex just released version 2.0, which includes the footnote citation code we've been using from their `develop` branch for quite a while.
> MRG, MAINT: bump sphinxcontrib-bitex version

- mne/viz/topomap.py
- mne/viz/utils.py
- tutorials/preprocessing/plot_50_artifact_correction_ssp.py
this makes it so that `plot_projs_topomap` uses the same sized head for EEG and MEG subplots within a figure (unless user passes their own axes). It's a quick fix to make the docs look nicer before release; was mentioned in #8640 
cc @hoechenberger @mmagnuski 
Not sure if there are other places in the codebase where we want to do this?
> VIZ: Fix head size

- mne/viz/backends/_notebook.py
This PR fixes an issue with the `notebook` 3d backend where the interactions do not trigger an update until a particular slider is used.
> FIX: notebook 3d backend

- doc/changes/latest.inc
- mne/time_frequency/csd.py
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
- mne/utils/progressbar.py
- mne/utils/tests/test_progressbar.py
Updates `csd_morlet` to use ProgressBar. Instead of having this output, one line per epoch plus many warnings:
```
Computing cross-spectral density from epochs...
Computing CSD matrix for epoch 1
dics.py:53: UserWarning: At least one of the wavelets is longer than the signal. Consider padding the signal or using shorter wavelets.
csd = csd_morlet(epochs, freqs, tmin=tmin, tmax=tmax, verbose=True)
Computing CSD matrix for epoch 2
dics.py:53: UserWarning: At least one of the wavelets is longer than the signal. Consider padding the signal or using shorter wavelets.
csd = csd_morlet(epochs, freqs, tmin=tmin, tmax=tmax, verbose=True)
Computing CSD matrix for epoch 3
dics.py:53: UserWarning: At least one of the wavelets is longer than the signal. Consider padding the signal or using shorter …
```
> MRG, ENH: Progressbar for csd_morlet

- doc/changes/latest.inc
- doc/changes/names.inc
- examples/connectivity/plot_mne_inverse_envelope_correlation.py
- mne/connectivity/envelope.py
- mne/connectivity/tests/test_envelope.py
Closes #8649.
@SherazKhan @dengemann can you look? This suggests the code I adapted originally has some bugs. It doesn't drastically change results or anything, in general it looks a bit cleaner now.
> MRG, BUG: Fix bugs with envcorr

- doc/changes/latest.inc
- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/colormap.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/backends/_pyvista.py
- tutorials/misc/plot_seeg.py
- tutorials/source-modeling/plot_beamformer_lcmv.py
Some simple code to plot with `hot_r` with `transparent=True` and `alpha=1.` (should yield an opaque volume where values are large) looks like this on `master`:
And on this PR it's correct:
The key was the opacity and color transfer functions both need to yield floats between 0 and 1, so we just need to divide both by 255 (ctable is `np.int8`) rather than doing whatever silly gymnastics we were doing before where the colors ranged from 0 to 255 and the alphas 0 to 1/255 (effectively).
While I was messing around with this I noticed `add_data` could not use `colormap='mne'` so I refactored our `get_cmap` calls. I also added a simple test to `test_brain` to make sure our `ctable` is correct.
@GuillaumeFavelier can you take a quick look? Not sure if this or #8335 should go in first, but I …
> MRG, BUG: Fix alpha for volumes

- doc/changes/latest.inc
- mne/io/base.py
- mne/time_frequency/psd.py
- mne/time_frequency/tests/test_psd.py
- mne/utils/docs.py
- mne/viz/_figure.py
- mne/viz/epochs.py
- mne/viz/raw.py
- mne/viz/tests/test_figure.py
> MRG, BUG, ENH: Add window option

- doc/changes/latest.inc
- mne/beamformer/_compute_beamformer.py
- mne/beamformer/_dics.py
- mne/beamformer/_lcmv.py
- mne/beamformer/tests/test_dics.py
- mne/beamformer/tests/test_lcmv.py
- mne/conftest.py
- mne/minimum_norm/tests/test_inverse.py
@wmvanvliet @britta-wstnr I am adding DICS bias tests along the lines of what we have for LCMV and minimum norm. After this PR is all good, we can add orientation tests to check the `max-power-ori` calculations.
However, it looks like `noise_csd`-based whitening is broken for DICS. I added a simple `_cov_as_csd` that just packs our data and noise cov into CSD objects, and the results should in principle match what we get for LCMV. I copied the code and limits from the LCMV tests. DICS performs within the same limits as LCMV as long as no whitening is used. Once things are whitened, things break. You can see that only the `noise_cov=False` versions of the bias tests are uncommented, except one -- the uncommented one went from the peak localization limit around 40 (meaning 40% of vertices …
> MRG, ENH: Add DICS bias tests

- doc/changes/latest.inc
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
In general the eSSS basis / projectors just need to be a superset of the good MEG channels in the data. This is particularly important when using empty-room data for an experiment with multiple runs where the runs could have different automatic (or manual) bad channels set.
> MRG, BUG: Fix bug with super versus eq in eSSS

- requirements_doc.txt
Build is failing with sphinxcontrib-bibtex version 2.1.1, which introduced big changes to how references are resolved.  Pinning to 2.0.0 for now.
> CI, MAINT: pin sphinxcontrib-bibtex

- .github/workflows/codespell_and_flake.yml
per discussion on somewhere (Slack? gitter?) this removes the check-skip job for the GitHub workflow for codespell/flake, because 
1. style violations are easy to introduce, and
2. the style check is really fast anyway so it's fine to always run it even when you want to skip other workflows.
> MRG, CI: never skip codespell/flake

- doc/changes/latest.inc
- mne/viz/_figure.py
closes #8687 
- scalebar toggle now works correctly with `macosx` backend (previously it showed, but did not hide, scalebars immediately)
- zen mode now works correctly with `macosx` backend (previously it would show/hide the scrollbars but not use the freed space)
- help dialog corrected: macOS uses `fn+→` not `⌘+→` (similar for other 3 arrow keys)
- help dialog no longer shows `F11` as a fullscreen key for macOS (it didn't work, and fullscreen is built into the OS, so we just don't show a fullscreen key now)
> MRG, VIZ: fix shortcuts and interactivity for raw.plot() with macosx backend

- doc/install/contributing.rst
some updates to our contributor guide, chiefly:
- where we diverge from the NumPy docstring standards
- how to do citations (thanks @johnsam7 for pointing out this info was missing)
- explain that MNE-Python-internal API crossrefs (i.e., not intersphinx) don't require directives
- fix name of default env (base → mne)
the rest is minor edits for readability/flow.
> MRG, DOC: update contributors guide

- .mailmap
- MANIFEST.in
- codemeta.json
- requirements.txt
- setup.py
- tools/generate_codemeta.py
Boilerplate was generated using https://codemeta.github.io/codemeta-generator/ and the things that might change (release date, release version, dependencies, and authors) are update by the new script `tools/generate_codemeta.py` which can be run at release time.
> MRG, MAINT: add codemeta

- mne/datasets/tests/test_datasets.py
- mne/datasets/utils.py
1. ~~Move the variables we change most of the times in `utils.py` to the top. In theory we could move all hashes and `?version=`s up there, but I think it actually becomes less readable to people who might need to change the values. 90% of the time we're just updating `testing` or `misc` so this seems like a nice compromise.~~
2. Detect if a dataset in ~~`_RELEASES`~~ `releases` (currently only testing and misc) is out of date based on `version.txt` and download it if necessary.
3. ~~Remove a crufty warning from when we tied dataset versions to MNE versions, we don't do this anymore AFAIK~~
This is meant to work nicely with #8695 so that when a PR updates the testing version etc. it should automatically re-download the testing dataset, overwriting the previously cached version. So …
> MRG, MAINT: Better downloading for testing and misc

- .github/workflows/compat_minimal.yml
- .github/workflows/compat_old.yml
- .github/workflows/linux_conda.yml
- .github/workflows/linux_pip.yml
- .github/workflows/macos_conda.yml
- azure-pipelines.yml
- tools/get_testing_version.sh
This PR follows https://github.com/mne-tools/mne-python/issues/8685#issuecomment-753985292 and attempts to solve the recent failures related to testing data download.
ToDo:
> MRG: Use caching in Github Actions and Azure Pipelines

- .circleci/config.yml
- mne/utils/config.py
- requirements_doc.txt
- requirements_testing.txt
- tools/circleci_download.sh
According to the [CircleCI docs](https://circleci.com/docs/2.0/caching/) it looks like the cache restore uses whichever key it finds first, treating all subsequent ones as fallbacks. So really we should restore each individually. In theory this should make our CircleCI full build faster and more reliable as it can just use the cached version rather than redownloading every time.
> MAINT: Actually use all caches

- .circleci/config.yml
Still spent a whopping 58 sec downloading data [in the latest master build](https://app.circleci.com/pipelines/github/mne-tools/mne-python/5542/workflows/ec8da970-2741-42cd-9359-f2c7ee2f5290/jobs/24386) because of several missing folders and one mis-named cache. Let's get it to zero...
> MRG, FIX: Missed a couple

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/question.md
- CONTRIBUTING.rst
- README.rst
- doc/install/advanced.rst
- doc/install/contributing.rst
- doc/install/mne_c.rst
- doc/install/mne_python.rst
- doc/install/pre_install.rst
- doc/links.inc
- doc/overview/datasets_index.rst
- doc/overview/faq.rst
- doc/overview/get_help.rst
Replace all mentions of the mailing list and Gitter with references to the new Discourse forum.
Closes #8429
> MRG, DOC: Mailing list, Gitter -> Discourse forum

- mne/rank.py
- mne/utils/docs.py
Basically, I just moved the explanation of the different "rank" settings from the Notes section up to the `rank` parameter, where I think they belong. I also added an info box, suggesting to use `rank='info'` on Maxwell-filtered data. I had discussed this with @SophieHerbst, but would appreciate feedback from @agramfort and / or @larsoner
> MRG, DOC: Make "rank" options in docs more accessible

- doc/changes/latest.inc
- mne/report.py
- mne/tests/test_report.py
- mne/viz/misc.py
- mne/viz/tests/test_topomap.py
- tools/setup_xvfb.sh
Fixes a bug where, because of the `flip_z` that occurs in the MRI orthoview rendering, subsets of the BEMs were flipped when `n_jobs != 1` (otherwise it was flipped as a whole, which was still wrong but less annoying).
> MRG, BUG: Fix Report.add_bem_to_section n_jobs != 1

- doc/changes/latest.inc
- mne/report.py
- mne/viz/_brain/mplcanvas.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/misc.py
- mne/viz/tests/test_topomap.py
- mne/viz/utils.py
- tutorials/misc/plot_report.py
1. Add `width` argument to `add_bems_to_section`, change from old default (7 inches in whatever your DPI was) to 512, thus reducing file sizes without losing any meaningful quality (2x the typical MRI resolution should be enough to see the BEM contours clearly). On my system this cuts down on the resulting report file size by a factor of 2.
2. Change CSS to have the images span 100% of the usable space (browser-upscaling)
3. Have BEM generation use Agg backend
4. DRY Agg-figure code
5. Fix bugs with `replace` being omitted in some Report functions
6. Make footer just show the date of creation, and make it sticky (informative, no need to advertise MNE nowadays I think)
7. Make header padding responsive to sizing changes. You can see the differences especially with an example like the …
> WIP: Add width argument, reduce default

- doc/changes/latest.inc
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
> FIX anon with IO round trip

- doc/install/mne_python.rst
- environment.yml
closes #8009
currently WIP because the fix doesn't actually work in my local testing; waiting to hear back from Spyder devs.
> MRG: bump spyder version

- mne/preprocessing/nirs/_beer_lambert_law.py
@rob-luke I'm trying to replicate some analysis done in HOMER and I can come pretty close when I use `beer_lambert(raw, ppf=30)` (MNE opaque, HOMER translucent):
The HOMER analysis used a partial pathlength factor of 6 mm. Any idea why I need to use `ppf=30` instead of `ppf=6` to get a  match? Does it have to do with HOMER using a "modified" Beer-Lambert law (MBLL)?
Speaking of which, I'm trying to reconcile 4.7 on page 35 of http://www.nmr.mgh.harvard.edu/DOT/resources/homer/HomER_UsersGuide_05-07-28.pdf with our code but I can't. Could you push some commits to add comments and/or point me to some docs that would allow me to put some inline code comments about the equations?
In the meantime this PR is just a cosmetic `(A.T @ B.T).T -> B @ A` change.
> WIP: Compare Beer-lambert to HOMER

- mne/forward/_compute_forward.py
I got a very cryptic error today when computing the forward:
```py
--> 270 fwd = mne.make_forward_solution(raw.info, trans_fname, src, bem)
271 inv = make_inverse_operator(raw.info, fwd, cov)
272 
<decorator-gen-302> in make_forward_solution(info, trans, src, bem, meg, eeg, mindist, ignore_ref, n_jobs, verbose)
/autofs/space/meghnn_001/users/mjas/github_repos/mne-python/mne/forward/_make_forward.py in make_forward_solution(***failed resolving arguments***)
601     ccoils = [compcoils, None]
602     infos = [meg_info, None]
--> 603     megfwd, eegfwd = _compute_forwards(rr, bem, coils, ccoils,
604                                        infos, coil_types, n_jobs)
605 
<decorator-gen-296> in _compute_forwards(rr, bem, coils_list, ccoils_list, infos, coil_types, n_jobs, verbose) …
```
> DOC: don't use single letter variable name in _compute_forward

- doc/changes/latest.inc
- mne/report.py
- mne/tests/test_report.py
- server_environment.yml
Support all non-FIFF files we can read when parsing a folder using `Report.parse_folder()`. Requested via https://mne.discourse.group/t/naming-convention-in-mne-vs-mne-bids-welcome-to-the-thunderdome/2467
> MRG: Support for non-FIFF files in Report.parse_folder

- doc/changes/latest.inc
- mne/viz/utils.py
The title is out of bounds in figures created by `plot_sensors` (including `montage.plot()`).
Before:
After:
> MRG, VIZ: Fix title position in plot_sensors

- doc/changes/latest.inc
- mne/io/_read_raw.py
- mne/io/egi/egi.py
- mne/io/egi/tests/test_egi.py
All readers should accept a `Path`.
> BUG, DOC: read_raw_egi didn't support pathlib.Path; update read_raw() docstring

- doc/glossary.rst
- examples/visualization/plot_eeglab_head_sphere.py
- tutorials/intro/plot_40_sensor_locations.py
The glossary entry was a bit misleading due to its brevity:
1. there is no limit to fiducial points (i.e., there can be more than 3)
2. LPA, RPA, and NAS are anatomical landmarks, but "fiducials" is often used as a synonymous term for that
Potential links to add:
- https://en.wikipedia.org/wiki/Fiducial_marker
- https://www.fieldtriptoolbox.org/faq/how_should_i_report_the_positions_of_the_fiducial_points_on_the_head/
- [bids disambiguation of anatomical landmarks and fiducials](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#coordinate-system-json-_coordsystemjson)
> DOC: improve glossary entry about fiducials

- mne/event.py
Small tweak to the docstring of `mne.make_fixed_length_events` to indicate that `start` and `stop` times are specified in seconds.
> [DOC] Add time unit to the docstring of make_fixed_length_events

- doc/changes/latest.inc
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
> WIP, BUG: Make plot_evoked() not plot GFP for single channel

- doc/_templates/layout.html
- doc/conf.py
Back in https://github.com/mne-tools/mne-python/pull/7532 I broke the `Last updated` tag at the bottom of the website, and it has read "Last updated on 2020-03-27." ever since. With this PR I now get "Last updated 01/25/2021, 11:32 AM EST" and each person should get the equivalent datetime in their own timezone.
> MAINT: Fix doc date

- doc/changes/latest.inc
- examples/inverse/plot_mixed_source_space_inverse.py
- mne/source_estimate.py
- mne/utils/docs.py
- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/backends/_pyvista.py
- tutorials/source-modeling/plot_beamformer_lcmv.py
- tutorials/source-modeling/plot_visualize_stc.py
This PR follows https://github.com/mne-tools/mne-python/pull/8749#issuecomment-764676327 and adds a `silhouette` parameter to `Brain.__init__()`.
master | PR
---|---
*What would be even more helpful for this kind of mesh is ambient occlusion.*
> MRG: Brain silhouette

- doc/changes/latest.inc
- doc/references.bib
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
- tutorials/evoked/plot_20_visualize_evoked.py
- tutorials/evoked/plot_eeg_erp.py
The reason for #8772 is simply that we always calculated the GFP incorrectly, i.e. without re-referencing sensor signals to average first. When doing that, I now correctly get a flat GFP (0 at all time points) for single-channel recordings:
This also means that since the introduction of this feature in 0.15 or so, our GFP plots haven't been correct in terms of absolute amplitude (which isn't too bad since it's difficult to judge the absolute amplitudes from the plot anyway)
Closes #8772, #8774
> MRG, BUG, DOC: derive GFP from average reference for EEG

- doc/changes/latest.inc
- mne/io/eeglab/eeglab.py
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- mne/utils/__init__.py
attempt to close #8755
my debug script using this branch.
```
from scipy import linalg
import mne
from mne.viz.topomap import _find_topomap_coords
ica = mne.preprocessing.read_ica_eeglab('ICAamica_MNE_test.set')
unmixing = ica.icaweights @ ica.icasphere
mixing = linalg.pinv(unmixing)
pos = _find_topomap_coords(ica.info, picks=None)
plt.close('all')
mne.viz.plot_topomap(mixing[:, 7], pos=pos)
plt.show()
```
here are the ICA topos I get using EEGLAB
It's quite different from what I get using ica.plot_components() or using mne.viz.plot_topomap manually
as above.
any idea @cbrnr ?
> MRG, BUG: fix IO or read_ica_eeglab

- doc/changes/latest.inc
- mne/commands/mne_make_scalp_surfaces.py
Currently, `overwrite` in `mne make_scalp_surfaces` is not passed to `mne.write_bem_surfaces`. Because the default of `overwrite` in `mne.write_bem_surfaces` changed to `False` now, `--overwrite` does not prevent `FileExistsError`.
For example, ```mne make_scalp_surfaces -s subject-346 -d subjects/ --force --overwrite --verbose``` gives:
```
1. Creating a dense scalp tessellation with mkheadsurf...
2. Creating subjects/subject-346/bem/subject-346-head-dense.fif ...
/home/ntubabylab/anaconda3/envs/mne/bin/mne:8: RuntimeWarning: Surface outer skin  has topological defects: 13 / 383510 vertices have fewer than three neighboring triangles [44385, 44387, 44389, 45198, 46031, 46033, 46861, 46862, 47708, 48546, 49428, 50338, 53081]
Consider using --force as an additional input parameter. …
```
> FIX: fix overwrite in make_scalp_surfaces

- doc/changes/latest.inc
- mne/commands/mne_browse_raw.py
- mne/io/_read_raw.py
- mne/io/tests/test_read_raw.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
1. Use `read_raw` rather than `read_raw_fif` in `browse_raw` to extend support to other formats
2. Add `.con` as a recognized KIT format name
3. Fix bug where `scalings='auto` would use the wrong sample range to compute auto scalings. It passed float times when it needed to pass int samples to `_read_segment`.
> MRG, ENH: Add support for other formats to browse_raw

- doc/changes/latest.inc
- mne/viz/_3d.py
Fixes #8810 .
Added the missing `from mpl_toolkits.mplot3d import Axes3`
Note that I've also modified the same import in `plot_head_positions`:
```python
from mpl_toolkits.mplot3d import axes3d  # was this
from mpl_toolkits.mplot3d import Axes3  # surely should be this?
```
I found this while searching for the actual bug, and [remembered reading this](https://stackoverflow.com/questions/11529043/axes3d-vs-axes3d-matplotlib) recently.
> FIX missing Axes3D import in viz._3d._plot_mpl_stc

- doc/changes/latest.inc
- mne/io/egi/egimff.py
- mne/io/egi/tests/test_egi.py
Partly addresses #8038
Adds digitization points to `.info` for `read_raw_egi` and `read_evokeds_mff`
> [MRG] ENH EGI MFF reader:  populate info['dig']

- doc/changes/latest.inc
- mne/gui/_file_traits.py
- mne/gui/tests/test_file_traits.py
Depends on #8789.
This adds the capability to use `*.mff` files directly as digitization source to the coregistration GUI. I started on it for verifying the result of #8789, but it could be a useful feature since it obviates the need to convert to FIFF before doing coregistration. The screen-shot is `test_egi.mff`.
> [MRG] Coregistration-GUI:  use *.mff as digitization source

- doc/changes/latest.inc
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
> fix mne.viz.plot_topomap with some missing grad in a pair

- doc/changes/latest.inc
- mne/cov.py
- mne/rank.py
- mne/tests/test_cov.py
- mne/utils/__init__.py
- mne/utils/check.py
- mne/utils/docs.py
- mne/viz/tests/test_evoked.py
Attempt to address https://mne.discourse.group/t/strange-source-activity-with-lcmv-beamformer-in-volume-source-space-empty-room-covariance/2549
@SophieHerbst @hoechenberger can you see if this warns when you try your beamforming script? If not can you send me an evoked file to use? This was my testing script since I didn't have one:
<details>
```
import mne
cov = mne.read_cov('data-cov.fif')
noise_cov = mne.read_cov('noise-cov.fif')
fwd = mne.read_forward_solution('FORWARD_ico-4_MEGonly_CEREB-fwd.fif')
info = fwd['info']
info.update(comps=[], projs=[])
filters = mne.beamformer.make_lcmv(
info, fwd, cov, noise_cov=noise_cov, rank=dict(meg=73), verbose=True)
```
</details>
And it now produces for me a nice warning, which I line-wrap here:
```
Computing rank from covariance with rank={'meg': …
```
> MRG, ENH: Add warning about bad whitener conditioning

- mne/io/edf/tests/test_edf.py
- mne/preprocessing/ica.py
- mne/utils/tests/test_testing.py
- mne/viz/_3d.py
- mne/viz/_figure.py
Fixes for a NumPy dtype promotion deprecation that happens due to `union1d`. It's easy enough to work around using sets. Despite code comments about ordering based on time, `union1d` [always returns a sorted output](https://numpy.org/doc/stable/reference/generated/numpy.union1d.html):
```
>>> np.union1d(('a', 'c', 'b', 'b'), ('d',))
array(['a', 'b', 'c', 'd'], dtype='<U1')
```
So this PR maintains this behavior (and removes the errant comment) by using `sorted` and `set` directly.
> MRG, FIX: Fix for NumPy deprecation

- doc/changes/latest.inc
- mne/epochs.py
- mne/tests/test_epochs.py
- Adjust Epochs.reject_tmin, reject_tmax for time inaccuracies due to sfreq. Fixes #8814
- Adjust Epochs.reject_tmin, reject_tmax upon cropping. Fixes #8816
> MRG, BUG: Fix Epochs.reject_tmin, reject_tmax handling upon Epochs creation & cropping

- codecov.yml
I don't like that PRs have their status set as failed even when CIs are still running. And even once all are done running, codecov reporting can be iffy. This PR sets codecov just to be informational which will make it always green. This will mean we have to manually check the coverage reports, but we already have to do that when we're interested since we can't fully trust the output.
Closes #8776
> MAINT: Dont fail on coverage

- doc/changes/latest.inc
- mne/annotations.py
- mne/viz/_figure.py
- mne/viz/tests/test_raw.py
issue raised on discourse: https://mne.discourse.group/t/annotation-editing-deletion-and-undo/2650/2
previously, right-clicking to remove an annotation would remove *all* annotation spans that overlap at the mouse position, *regardless of whether they were visible or hidden by the UI*.  Now it will remove only *visible* spans under the mouse cursor, meaning it is possible to remove only a specific span by hiding other overlapping ones first.
> FIX: only delete visible annotation spans

- doc/changes/latest.inc
- mne/baseline.py
- mne/conftest.py
- mne/epochs.py
- mne/forward/forward.py
- mne/io/base.py
- mne/io/pick.py
- mne/preprocessing/ica.py
- mne/preprocessing/realign.py
- mne/preprocessing/tests/test_ica.py
- mne/stats/tests/test_cluster_level.py
- mne/tests/test_epochs.py
- mne/tests/test_event.py
- mne/time_frequency/tfr.py
- mne/utils/__init__.py
- mne/utils/mixin.py
- mne/utils/numerics.py
- mne/utils/tests/test_numerics.py
Go back to creating `raw.times` on the fly when needed. On `master` this code:
<details>
```
import mne
mne.set_log_level("WARNING")
def read_raws(paths, preload):
import gc
out = list()
for path in paths:
out.append(mne.io.read_raw_edf(path, preload=preload))
gc.collect()
return out
paths = mne.datasets.sleep_physionet.age.fetch_data(
subjects=range(1, 20), recording=[1])
paths, _ = zip(*paths)
raws = read_raws(paths, preload=False)
```
</details>
Produces with `mprof run mem.py && mprof plot`:
On this PR it produces:
Moreover this code, which creates a ton of epochs (a variant of the case from #2126):
<details>
```
import mne
def test():
raw = mne.io.read_raw_fif(mne.datasets.sample.data_path() + '/MEG/sample/sample_audvis_raw.fif', preload=True)
n_ev = 10000
events = …
```
> MRG, ENH: Dont store raw.times

- doc/changes/latest.inc
- mne/stats/cluster_level.py
- mne/stats/tests/test_cluster_level.py
- mne/utils/docs.py
Closes #8836
New output on that example is correct:
```
Running initial clustering
Found 2 clusters
Permuting 49 times...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|  : 49/49 [00:00<00:00, 6809.61it/s]
Computing cluster p-values
Done.
[(slice(2, 4, None),), (slice(46, 49, None),)]
stat_fun(H1): min=-7.417671 max=4.199342
Running initial clustering
Found 2 clusters
Permuting 49 times...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|  : 49/49 [00:00<00:00, 8677.99it/s]
Computing cluster p-values
Done.
[(array([2, 3]),), (array([46, 47, 48]),)]
```
> MRG, FIX: output_type for clustering

- doc/changes/latest.inc
- mne/channels/channels.py
- mne/channels/tests/test_channels.py
In `main`, calling `rename_channels()` on a `Raw` instance would not
adjust `Raw._orig_units`.
While you could argue that the original units were only specified for
the original channel names, I would say that this makes the units
simply useless after channels have been renamed ;) Therefore I
consider the current behavior a bug.
This PR makes it so that if `Raw._orig_units` exists, its keys are
adjusted such that they stay in sync with the new channel names.
Discovered while working on data with @MaelysSolal
> MRG, BUG: Raw.rename_channels() should update Raw._orig_units too

- mne/viz/_3d.py
This PR hopefully helps clarify the return value of `plot_stc` as described in https://github.com/mne-tools/mne-python/issues/8850#issuecomment-776180591.
Closes #8850
> DOC: plot_stc

- doc/changes/latest.inc
- doc/python_reference.rst
- mne/__init__.py
- mne/bem.py
- mne/tests/test_bem.py
- mne/utils/docs.py
- tutorials/source-modeling/plot_fix_bem_in_blender.py
Discussed in #8825 .
~~`fix_all_defects` (all credits to @christian-oreilly , just merge the codes into MNE-Python)~~
~~`fix_all_defects`~~
~~A tutorial/example to illustrate how to fix the topological defects~~
> MRG, ENH: write_head_bem for writing head surface files

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
Fixes an issue related to #6801 in `raw.resample`.
Resampling MISC channels using `raw.resample` (mne.io.Raw.resample) by passing `stim_picks='misc'`, `stim_picks=None` or `stim_picks=stim_ch_name` was not possible.
Using:
`raw_data.resample(Fs, npad='auto', window='boxcar', stim_picks='misc', n_jobs=1, events=None, pad='reflect_limited')`
yields an error:
> File "", line 24, in resample
> File "{envpath}/lib/python3.8/site-packages/mne/io/base.py", line 1166, in resample
> if len(stim_picks) > 0:
> TypeError: len() of unsized object
Using `stim_picks=ch_names` where ch_names is a list containing the misc channel names doesn't work either:
`raw_data.resample(Fs, npad='auto', window='boxcar', stim_picks=ch_names, n_jobs=1, events=None, pad='reflect_limited')`
yields:
> File "", line 24, in …
> MRG, FIX: resampling MISC channels using raw.resample

- mne/viz/_brain/_brain.py
- mne/viz/backends/_pyvista.py
- tutorials/stats-source-space/plot_stats_cluster_spatio_temporal.py
Locally I was able to reproduce https://github.com/mne-tools/mne-python/pull/8757#issuecomment-774343270 and this small fix did the trick for me. Let's see how it is on Circle.
> FIX: paintEvent

- doc/changes/latest.inc
- mne/channels/tests/test_channels.py
- mne/io/pick.py
- tutorials/sample-datasets/plot_sleep.py
Respiratory channels contain an analog signal, monitoring the expansion of a chest strap / belt.
The signal is measured in Volts.
Scaling factors (µV, mV, V) depend on the specific amplifier system used, so we cannot provide a
sophisticated default scaling (and leave it at 1).
cc @MaelysSolal, @agramfort
> MRG: Change resp channel unit to Volts

- examples/connectivity/plot_mne_inverse_psi_visual.py
- examples/connectivity/plot_sensor_connectivity.py
- mne/connectivity/spectral.py
- mne/connectivity/tests/test_spectral.py
- mne/utils/_logging.py
Follow-up to #8839 to fix CircleCI failures
- We need to be careful about inferring times in `spectral_connectivity` because data can for example arrive in `(ndarray, SourceEstimate)` pairs and in that case we should get the times from the SourceEstimate, not the ndarray.
- if there is a mismatch, we really only need to warn about it once, not on every epoch.
- if there is a mismatch, print at least some of the arrays so that users can see the mismatch.
- when using `mne.use_log_level('warn', add_frames=3):` actually have the frames printed so you can get an output that allows you to track the lines like:
```
/home/larsoner/python/mne-python/examples/connectivity/plot_mne_inverse_psi_visual.py:95: RuntimeWarning: time scales of input time series do not match
psi, freqs, times, n_epochs, _ …
```
> MRG, BUG: Fix handling of times

- doc/changes/latest.inc
- mne/bem.py
- mne/dipole.py
- mne/surface.py
- mne/tests/test_bem.py
- mne/utils/__init__.py
- mne/utils/check.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
- tutorials/sample-datasets/plot_brainstorm_phantom_elekta.py
- tutorials/source-modeling/plot_source_alignment.py
In preparation for writing some BEM quality code, I wanted to have an `_ensure_bem_surfaces` function. This should simplify our handling of BEM surfaces, and in the process simplified `plot_alignment` by populating the `'surfs'` entry of the spherical ConductorModel dict. This ended up being a bugfix where on `main` you could do `plot_alignment(..., bem=sphere, surfaces='brain')` and have no surfaces show up if you had a 1-layer sphere model. This now raises an error because it seems like a user mistake. In the case where someone wants a FreeSurfer brain surface they can do `surfaces='pial'` explicitly if they want, but I assume this use case is rare.
> MRG, MAINT: Clean up BEM surface code

- doc/changes/latest.inc
- doc/conf.py
- mne/utils/_logging.py
The `@verbose` decorator used to "eat up" the parameters of the decorated
functions, leading to an awfully useless experience with Pylance in VS Code.
Thanks to @cbrnr's persitence, a Pylance dev pointed us to the correct
solution, which is implemented in this PR:
See https://github.com/microsoft/pylance-release/issues/346#issuecomment-777490280
> WIP, ENH: Make "verbose" decorator provide help for static type checkers like Pylance

- doc/changes/latest.inc
- mne/datasets/utils.py
- mne/io/eeglab/eeglab.py
- mne/io/eeglab/tests/test_eeglab.py
EEGLAB files may contain all fields in the root of the file instead of within an `EEG` struct. This PR adds support for this format. Fixes #8864.
> Fix EEGLAB import

- doc/changes/latest.inc
- mne/epochs.py
- mne/io/base.py
- mne/preprocessing/maxwell.py
- mne/utils/tests/test_logging.py
Closes #8872
@HanBnrd can you try it with your code?
Basically the fix is that for any methods that have `verbose`, we need to propagate `verbose` to any other method calls. We don't need to do this with functions, but we do with methods since when they are called with `verbose is None` they resort to using `self.verbose`.
> MRG, BUG: Fix verbose

- doc/changes/latest.inc
- mne/commands/mne_report.py
- mne/io/base.py
- mne/io/fiff/raw.py
- mne/report.py
- mne/utils/tests/test_check.py
- tutorials/misc/plot_report.py
When writing or loading a FIFF file with an `_meg.fif` suffix, we
don't warn. This PR adds similar behavior for the
`_eeg.fif` and `_ieeg.fif` suffixes, which are used in BIDS.
It's a tiny change, so I don't think it warrants a changelog
entry.
> MRG, ENH: Don't warn on _eeg.fif and _ieeg.fif suffixes

- doc/changes/latest.inc
- mne/channels/channels.py
- mne/channels/montage.py
- mne/channels/tests/test_channels.py
- mne/cov.py
- mne/evoked.py
- mne/forward/forward.py
- mne/io/array/tests/test_array.py
- mne/io/constants.py
- mne/io/ctf_comp.py
- mne/io/edf/tests/test_edf.py
- mne/io/egi/tests/test_egi.py
- mne/io/meas_info.py
- mne/io/proj.py
- mne/io/tag.py
- mne/io/tests/test_constants.py
- mne/io/tests/test_meas_info.py
- mne/io/tests/test_reference.py
- mne/tests/test_docstring_parameters.py
- mne/utils/docs.py
> MRG, ENH: Remove 15-char limit for FIF

- doc/_templates/layout.html
Must not be merged before https://github.com/mne-tools/mne-tools.github.io/pull/23
cc @drammock
> DOC: Drop dev version warning bar from layout template

- mne/viz/_figure.py
fix for raw.plot(): make annotations immediately visible when scrolling via click on scrubber bar
> backport #8898

- doc/changes/latest.inc
- mne/annotations.py
- mne/beamformer/_compute_beamformer.py
- mne/bem.py
- mne/channels/channels.py
- mne/dipole.py
- mne/epochs.py
- mne/forward/forward.py
- mne/io/base.py
- mne/morph.py
- mne/preprocessing/maxfilter.py
- mne/report.py
- mne/source_space.py
- mne/surface.py
- mne/tests/test_annotations.py
- mne/time_frequency/tfr.py
- mne/utils/docs.py
Closes #5507
Removes some heavy, seemingly overkill parametrization of the `test_annotations.py` where the parameters were only used in a single function for example. Also makes an `overwrite` entry in `docdict`.
Todo:
> MRG, ENH: Allow channel-specific annotations

- doc/changes/latest.inc
- mne/viz/_figure.py
- mne/viz/tests/test_raw.py
Fixes:
```
File "/home/larsoner/python/matplotlib/lib/matplotlib/cbook/__init__.py", line 256, in process
func(*args, **kwargs)
File "/home/larsoner/python/mne-python/mne/viz/_figure.py", line 662, in _keypress
self._redraw()
File "/home/larsoner/python/mne-python/mne/viz/_figure.py", line 2122, in _redraw
self._update_data()
File "/home/larsoner/python/mne-python/mne/viz/_figure.py", line 1925, in _update_data
this_data = _filtfilt(
File "/home/larsoner/python/mne-python/mne/filter.py", line 433, in _filtfilt
x, orig_shape, picks = _prep_for_filtering(x, copy, picks)
File "/home/larsoner/python/mne-python/mne/filter.py", line 272, in _prep_for_filtering
picks = _picks_to_idx(x.shape[-2], picks)
File "/home/larsoner/python/mne-python/mne/io/pick.py", …
```
> MRG, BUG: Fix bug with no picks

- doc/changes/latest.inc
- mne/chpi.py
- mne/tests/test_chpi.py
When cHPI is off, we should still return arrays of the correct dimensionality.
> MRG, BUG: Fix bug with empty dim

- doc/changes/latest.inc
- mne/viz/backends/renderer.py
Sets `QT_MAC_WANTS_LAYER=1` for STC plots via PyVista / pyvistaqt.
Was required on my system with macOS 11.2.1, Qt 5.12.9, pyqt 5.12.3 (installed from `conda-forge`)
Previous fix via #8554 didn't cover STC plots.
cc @cbrnr, @GuillaumeFavelier
> MRG, ENH: macOS 11 compatiblity for STC plots

- mne/chpi.py
- mne/preprocessing/maxwell.py
- mne/tests/test_chpi.py
I encountered this while maxfiltering 40 subjects. Some subjects failed, claiming `Head position time points must be greater than first sample offset, but found 500.0005 < 500`. A bit of a misleading error, as it was not the first time point that caused the problem, but the final time point.
When the continuous head position is fitted through `compute_chpi_amplitudes`, the first column of the result contains the times at which each fit was performed. However, these times were not necessarily aligned on the times of the original raw object, meaning some times fell in between two samples. This caused problems later on in `maxwell_filter` as a check is done whether the times are all valid, as the final timestamp can be slightly larger than the final timestamp of the raw object.
In this PR, …
> Ensure times at which chpi are fitted are valid samples

- examples/preprocessing/plot_run_ica.py
- mne/io/ctf/info.py
- mne/viz/ica.py
- mne/viz/tests/test_ica.py
```
ica.exclude = [0]
ica.plot_sources(raw, picks=[1, 2])
```
would raise an exception.
`RuntimeError: bad channel(s) ['ICA000'] marked do not exist in info`
Also fixed a typo in ctf.io
I don't think either of these have made it to release so no whats new.
closes #8966
> [MRG] Fix ica.plot_sources exception

- mne/viz/_brain/_brain.py
This PR fixes the issue with: 
```
File "/home/circleci/project/mne/viz/_brain/_brain.py", line 50, in safe_event
return fun(*args, **kwargs)
File "/home/circleci/project/mne/viz/_brain/_brain.py", line 690, in _clean
self.clear_glyphs()
File "/home/circleci/project/mne/viz/_brain/_brain.py", line 1701, in clear_glyphs
self.rms.remove()
TypeError: remove() takes exactly one argument (0 given)
```
> FIX: Brain Line2D

- mne/viz/_brain/_brain.py
- mne/viz/backends/_pyvista.py
This PR fixes the 3 light system:
PR | master
--|--
The patch is just shared to all renderers. Such a function is already implemented on pyvista master so the function `update_lighting()` will be replaced by `enable_3_lights()` in the future.
> FIX: Brain lights

- .circleci/config.yml
- .github/workflows/linux_pip.yml
- azure-pipelines.yml
- tools/azure_dependencies.sh
- tools/circleci_dependencies.sh
- tools/github_actions_dependencies.sh
Two CIs being broken has been problematic, let's avoid `--pre` on the problematic library until it's fixed (https://github.com/matplotlib/matplotlib/issues/19576).
Also makes these sorts of changes easier in the future by consolidating dependencies a tiny bit, and making it so the the CI can reflect the change using a merge (which happens automatically when building) rather than requiring a rebase, which will be nice.
> MAINT: Skip matplotlib pre for now

- azure-pipelines.yml
- tools/azure_dependencies.sh
For some unknown reason #8973 caused timeouts in the windows 3.7 conda run. This PR reverts the conda commands to be in the YAML which is a bit annoying but should at least work. Probably some bash vs powershell issue...
> MAINT: Revert conda azure change

- doc/overview/index.rst
fixes a doc link that is currently resolving (wrongly) to https://docs.python.org/3/install/index.html
> MRG, DOC: fix link to install instructions

- .circleci/config.yml
- doc/conf.py
The date changes that resolve the datetime locally are useful for end-users but bad for developers because it means that a sphinx config value changes on every run, which means that all files must be rewritten. On this PR CircleCI gets the full date, but locally we get a config var that just changes once a year, which seems like a good compromise.
> MRG, FIX: Fix rebuilding of all files

- mne/viz/_brain/_brain.py
- mne/viz/backends/_pyvista.py
This small PR should help with #8997. It refactors some `plotter` calls out of `Brain` and uses `self.figure` instead.
> MNT: 3d viewer loc and idx

- mne/viz/_brain/_brain.py
- mne/viz/backends/_abstract.py
- mne/viz/backends/_notebook.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/_qt.py
This PR disables the default menu bar created by PyVistaQt and uses the `_QtMenuBar` interface instead.
It also helps with https://github.com/mne-tools/mne-python/pull/8997
> MNT: menu_bar & status_bar

- mne/viz/epochs.py
- tutorials/epochs/plot_10_epochs_overview.py
Closes #8895.
1. Corrects the documentation of the `events` argument of `plot_epochs`.
2. Adds visualisation of event bars for the epochs plot in the tutorial.
@drammock, following the discussion in the issue, I wasn't sure if you wanted me to update the tutorial as well, I can undo it if you prefer not to.
Additionally, I noticed when plotting the epochs with events in the tutorial that some do not have events (those before events 32), I'm not sure if that's normal?
> DOC: Correct `plot_epochs` doc

- mne/gui/_file_traits.py
After #8790 opening the file dialog for dig source gives:
```
~/mne_data/MNE-sample-data/MEG/sample$ mne coreg -s sample -d ../../subjects
```
On this PR:
> BUG: Fix extension

- doc/changes/latest.inc
- mne/report.py
- tutorials/misc/plot_report.py
The slider in the reports in `main` only triggers an update callback when the dragging action has ended. This PR makes
it such that the callback is emitted during slider movement, so one doesn't have to release the mouse button to see the results.
Also enables animations for clicking action.
This PR:
https://user-images.githubusercontent.com/2046265/110623479-2f661580-819d-11eb-86df-5c38b0cd0787.mov
`main`:
https://user-images.githubusercontent.com/2046265/110623434-1c534580-819d-11eb-8889-931c228ae1d0.mov
> MRG, ENH: Slider triggers callback during dragging

- codecov.yml
It turns out you can disable the comments by pressing "a", but given how often they are false alarms and how much noise they add, I think it's better just to disable them.
> MAINT: Disable inline comments

- environment.yml
After https://github.com/conda-forge/pyface-feedstock/pull/27 we shouldn't need to avoid this version of `pyface` anymore. In fact there is no real reason to list these since the `mayavi` dependency will already pull them in. Now `environment.yml` is closer to `requirements.txt`, too, which is nice.
> MAINT: Remove pyface exclusion

- mne/conftest.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/tests/test_3d.py
This PR refactors `renderer_interactive` into two forms: one that includes mayavi (`renderer_interactive`) and makes it clear in the code that PySurfer is required, too; and another that just uses PyVista (`renderer_interactive_pyvista`). This makes it so that we don't get a bunch of unnecessary `skip` messages for tests that were never meant to be run on Mayavi/PySurfer.
This is a first step toward making it so that we can iterate over `'notebook'` as a backend type in the `renderer_interactive` tests. @GuillaumeFavelier feel free to review and merge if you and CIs are happy
> MRG, MAINT: Cleaner split, fewer skips in _brain tests

- examples/preprocessing/plot_otp.py
Fixes #8903.
Add bibtex to the example plot_otp (Plot sensor denoising using oversampled temporal projection).
> Adding bibtex in plot_otp

- examples/time_frequency/plot_time_frequency_erds.py
> DOC: citations in plot_time_frequency_erds.py

- tutorials/discussions/plot_background_statistics.py
Example: Fixes #8901.
Modified references to bibtex references in tutorials/discussions/plot_background_statistics.py
> Fixed bibtex references in plot_background_statistics

- examples/time_frequency/plot_source_power_spectrum_opm.py
DOC: #8906.
Use bibtex in plot_source_power_spectrum_opm.py.
> DOC: use bibtex in plot_source_power_spectrum_opm.py (#8906)

- mne/viz/_brain/tests/test_brain.py
It's too unreliable, at least for the sprint. Let's disable it for now.
> MAINT: Disable macOS screenshot test

- tutorials/discussions/plot_background_filtering.py
Example: Fixes #8900.
Add bibtex citations in the tutorial "Background information on filtering"
> Adding bibtex in plot_background_filtering.py

- mne/preprocessing/otp.py
closes #8926
citation year was listed as incorrect in doc, added footcite to correct reference.
> use footcite in otp.py

- doc/references.bib
- mne/minimum_norm/spatial_resolution.py
Example: Fixes #8925.
Adds footcite and footbibliography support for `resolution_metrics()` in _minimum_norm/spatial_resolution.py_.
@cmista
> DOC Bibtex fix for spatial_resolution.py

- mne/viz/ica.py
- tutorials/discussions/plot_background_statistics.py
Fixes #8987.
Fixed the documentation to say tmax = None defaults to 3s
> Ica overlay tmax documentation

- doc/references.bib
- examples/visualization/plot_channel_epochs_image.py
Fixes #8909.
add missing GramfortEtAl2010 reference in reference.bib because needed in /examples/visualization/plot_channel_epochs_image.py
> fix references in examples/visualization/plot_channel_epochs_image.py

- doc/changes/latest.inc
- mne/io/base.py
- mne/io/tests/test_raw.py
Fixes #8510.
Restrict saving options of the fif file to .fif and .fif.gz and add the test for this error raising.
> FIX saving fif file with the wrong extension

- examples/preprocessing/plot_virtual_evoked.py
Fixes #9004
- the code was split into four code blocks, so that the figures are printed in separate cells. 
- a few lines of explanation were added
> split up code cells in example

- tutorials/time-freq/plot_sensors_time_frequency.py
Fixes #8990 .
Added a note before the code snippet to let the user know that the `decim` parameter reduces the sampling rate by the defined parameter.
> DOC: Added a note to decim parameter usage in tutorial code snippet

- doc/changes/latest.inc
- mne/report.py
- mne/tests/test_report.py
Fixes #9101.
This fixes the bug appearing when calling Report().parse_folder() with n_jobs>1 by adding _projs_ to the list of pickled attributes in _get_state_params().
Solution suggested by @larsoner
> BUG: Fixing Report multiprocessing

- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/backends/_abstract.py
- mne/viz/backends/_notebook.py
- mne/viz/backends/_qt.py
- mne/viz/utils.py
This PR refactors MplCanvas so that canvas not related to `Brain` can be created. For instance, the help window:
https://user-images.githubusercontent.com/18143289/111464895-b0835680-8721-11eb-82dc-3294bc71503e.mp4
It's an item of https://github.com/mne-tools/mne-python/issues/8704
> ENH: Help button

- .gitignore
Adds `optipng.exe` to the gitignore for Windows users.
> Add optipng to gitignore

- doc/changes/latest.inc
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
Fixes #8746.
Fixed Evoked.plot_image(), incorrect clim parameter did not raise any error. Now it checks if it is a dict.
> BUG Fixed: Evoked plot image.

- tutorials/sample-datasets/plot_brainstorm_auditory.py
Example: Fixes #8939.
Convert references in tutorials/sample-datasets/plot_brainstorm_auditory.py to use footcite / footbibliography
> DOC: Use bibtex in plot_brainstorm_auditory tutorial

- tutorials/source-modeling/plot_dipole_orientations.py
Example: Fixes #9008.
Tweak the plotting params of 4 3D scenes so that brain figures don't look out-of-frame.
> DOC: Fixes brains out-of-frame in plot_dipole_orientations tutorial

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/epochs.py
- mne/tests/test_epochs.py
Fixes #8773.
Adds compatibility for the overlap parameter in the function make_fixed_length_epochs
Tests were also added to test the new feature inspired by the pre-existing ones written for make_fixed_length_events.
> Fixed length epochs overlap

- tutorials/sample-datasets/plot_brainstorm_phantom_ctf.py
Fixes issue #8940. 
Adds bibtex citation in plot_brainstorm_phantom_ctf.py.
> DOC: Fix bibtex citation in plot_brainstorm_phantom_ctf.py #8940.

- doc/changes/latest.inc
- mne/report.py
Tackles #9038.
It was suggested by @jasmainak to change report.include to a dictionary to make manipulating the items in include easier should it be necessary.
The dictionary is of type OrderedDict to maintain compatibility with Python 3.6.
> DOC: Improve documentation of Report-Class

- mne/channels/montage.py
- mne/coreg.py
- mne/source_space.py
Requested by @agramfort in https://github.com/mne-tools/mne-python/pull/9118#discussion_r596933282. It's purely a code move.
Unfortunately `mne.coreg.get_mni_fiducials` is public in the `mne.coreg` namespace:
https://mne.tools/dev/generated/mne.coreg.get_mni_fiducials.html
I'm not sure it's worth it to move its API page to a different namespace, but we could. @agramfort do you prefer we leave it, or move it to `mne.` or `mne.source_space.` or somewhere else?
> MAINT: Move function

- mne/data/html_templates.py
- mne/io/base.py
- mne/io/meas_info.py
- mne/report.py
- tutorials/intro/plot_30_info.py
Reference issue #6846.
Reuse `report.py` code in order to produce html reports within the Info class.
Here is the output of in the IPython notebook:
> ENH: add _repr_html_ method in the classes Info and BaseRaw

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/viz/epochs.py
Fixes #9108
Stops curve from extending outside of axis when interactively zooming, and shares axes between both subplots when `plot_epochs_image(evoked=True)`
Can test on `plot_epochs_image` :
```
import os
import mne
sample_data_path = mne.datasets.sample.data_path()
raw_fname = os.path.join(sample_data_path, 'MEG', 'sample', 
'sample_audvis_filt-0-40_raw.fif')
raw = mne.io.read_raw_fif(raw_fname, verbose=False)
events_fname = os.path.join(sample_data_path, 'MEG', 'sample', 
'sample_audvis_filt-0-40_raw-eve.fif')
events = mne.read_events(events_fname)
event_dict = {'auditory/left': 1, 'auditory/right': 2, 'visual/left': 3,
'visual/right': 4}
tmin, tmax = (-0.2, 0.5) 
baseline = (None, 0)     
epochs = mne.Epochs(raw, events, event_dict, tmin, tmax, proj=True,
baseline=baseline, …
```
> Fix interactive zoom in plot_epochs_image.py (evoked=True)

- mne/channels/montage.py
Example: Fixes #7093.
Add notes about valid arguments for ´coord_frame´ parameter and its use for creating custom montages.
> DOC: Add description about ´coord_frame´ parameter in mne.channels.make_dig_montage

- tutorials/epochs/plot_60_make_fixed_length_epochs.py
#9156 added a tutorial that is very memory-hungry, and CircleCI can't handle building it.  This PR reduces build time / memory consumption on my machine from 167.38 sec  / 3563.6 MB before this PR to  23.90 sec / 244.5 MB after this PR.  Along the way I tightened up the text and code in a few places.
> MAINT: reduce tutorial memory usage

- mne/source_estimate.py
Closes #8479.
- remove zero as value for `mode`
- add single as value for `mode`
- in Notes, change `weighted` to `single`
I find it a little confusing that `sum` is a valid value for that keyword, but does not appear in the code. I guess it is just the default behavior? But the default value is not specified.
> [DOC] Stc near sensors doc

- doc/changes/latest.inc
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
GH-9103 improved anonymization when `keep_his=False`; however, it would break I/O roundtrips because handedness
and sex would be set to values that aren't supported by the FIFF specs.
This PR changes the behavior such that anonymization sets `sex = 0` (unknown) and entirely removes `hand`, as FIFF
doesn't specify an "unknown" handedness.
Also adds more testing coverage for Raw & Epochs I/O roundtrip after anonymization.
cc @Falach
> BUG: Only use valid FIFF values for anonymization

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/viz/topo.py
Fixed a bug where any ylim input parameters to function ``plot_evoked_topo`` would be ignored.  Mentioned here (https://github.com/mne-tools/mne-python/issues/8714#issuecomment-801339017)
The bug arose as a result of a zip object being exhausted after being applied to the first channel inside ``_plot_topo``
Added a temporary list outside the respective for loop to mitigate the zip object from being exhausted in the first iteration .
> BUG : Fixes Bug where ylim would only be applied to the first channel in plot_evoked_topo

- mne/channels/channels.py
- mne/channels/tests/test_channels.py
- mne/io/reference.py
- mne/utils/docs.py
Fixes #8979
add_reference_channels is now also a method of Raw/Epochs/Evoked
I also implement a little test that checks mainly that the object has changed (the return value is not a copy), there are more tests already at the original function location (mne/io/reference).
Let me know if the docdict is used as you expected.
> adding add_reference_channels as a method of Raw/Epochs/Evoked

- mne/data/html_templates.py
- mne/io/base.py
- mne/io/meas_info.py
Reference issue #6846 and PR #9161
Add more information in the `_repr_html_` output.
> ENH: Extend _repr_html_ method for Raw

- mne/viz/backends/_qt.py
This small PR fixes the issue with `Brain` locale.
master | PR
--|--
> FIX: Brain locale

- doc/changes/latest.inc
- mne/io/pick.py
- mne/preprocessing/nirs/__init__.py
- mne/preprocessing/nirs/nirs.py
- mne/preprocessing/nirs/tests/test_nirs.py
I was going to implement some new features raised in an issue from #9141 but found this bug along the way. 
When trying to pick a specific fNIRS type the function was returning all fNIRS types. Now it should just return the requested type.
Once this bug is fixed I will add new functionality in a seperate PR
> MRG FIX: fNIRS picks for different types

- doc/changes/latest.inc
- mne/preprocessing/ica.py
- mne/viz/ica.py
@larsoner [suggestions](https://github.com/mne-tools/mne-python/pull/9134#issuecomment-803042712) in the PR #9134
Line profiler output for `plot_ica_properties`:
Updated function (2.14214 s): 
<details>
```
Total time: 2.14214 s
File: /mne-python/mne/viz/ica.py
Function: plot_ica_properties at line 254
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
254                                           def plot_ica_properties(ica, inst, picks=None, axes=None, dB=True,
255                                                                   plot_std=True, topomap_args=None, image_args=None,
256                                                                   psd_args=None, figsize=None, show=True, reject='auto',
257 …
```
> ENH: Speed up plot_ica_properties

- doc/changes/latest.inc
- doc/conf.py
- mne/viz/_brain/_brain.py
- mne/viz/backends/_abstract.py
- mne/viz/backends/_notebook.py
- mne/viz/backends/_qt.py
This follows PR #9126.
Add a theme-parameter to Brain with PyVista-Renderer accepting 'dark', 'light' and 'auto'. Dark-Mode depends on [qdarkstyle](https://github.com/ColinDuquesnoy/QDarkStyleSheet) and the automatic detection works with [darkdetect](https://github.com/albertosottile/darkdetect).
> Dark-mode to PyVista-Brain (pair-programmed with @GuillaumeFavelier)

- mne/preprocessing/nirs/_beer_lambert_law.py
- mne/preprocessing/nirs/nirs.py
- mne/preprocessing/nirs/tests/test_nirs.py
Preparation for #9141 
Adds checking of fNIRs channel naming structure for data after transformation to chromophore.
Previously all testing was done on the raw data or after transformation to optical density. But with possibility of people creating their own data structures without the readers I have added additional error checking for the hbo/hbr data type.
This is the last addition I have planned in preparation for #9141
> MRG: Test fnirs channel structures for chromophore data

- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/backends/_abstract.py
- mne/viz/backends/_notebook.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/_qt.py
This PR follows https://github.com/mne-tools/mne-python/pull/8997#issuecomment-802891396 and brings support for docked traces:
This is how it looks by default for me on `i3`:
And the dock widgets can be detached/resized/reattached:
*Locally, `Brain` testing works but I don't know how `macOS` CIs will react* :pray:
<details>
```py
import os
import mne
sample_dir = os.path.join(data_path, 'MEG', 'sample')
subjects_dir = os.path.join(data_path, 'subjects')
fname_stc = os.path.join(sample_dir, 'sample_audvis-meg')
stc = mne.read_source_estimate(fname_stc, subject='sample')
initial_time = 0.096
brain = stc.plot(subjects_dir=subjects_dir, initial_time=initial_time,
clim=dict(kind='value', lims=[3, 6, 9]),
surface="white",
size=600, …
```
> ENH: Traces dock widget

- mne/viz/_figure.py
- mne/viz/ica.py
closes #9110 
@larsoner [suggestion](https://github.com/mne-tools/mne-python/pull/9134#issuecomment-803042712) in the PR #9134:
- precompute epochs ICA sources only once 
Line profiler output for `_plot_ica_properties` and `_fast_plot_ica_properties`:
**Sample data**
<details>
```
<Raw | sample_audvis_raw.fif, 376 x 166800 (277.7 s), ~481.8 MB, data loaded> - sfreq = 600.614990234375
Total time: 0.539739 s
File: /mne-python/mne/viz/ica.py
Function: _plot_ica_properties at line 122
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
122                                           def _plot_ica_properties(pick, ica, inst, psds_mean, freqs, n_trials,
123 …
```
> ENH: Add fast plotting ICA properties

- doc/_static/style.css
1. fixes the too-narrow thumbnail for MNE-Reports tutorial
2. fixes the too-short thumbnail container that causes tutorial title text to get hidden below the next row's image sometimes
> STY: website fixes

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/io/edf/edf.py
This shows a warning if edf file data is given in Volts as mentioned in the issue discussions. Though it interprets the data in Volts, it informs the data about a possible problem in scaling. Fixes #9186.
> MRG: Support µV in EDF files (in addition to uV)

- mne/io/edf/edf.py
This PR explicitly uses Unicode characters to specify the different symbols for microvolt in mne.io.read_raw_edf in order to add support for the units
> add support for microvolt units

- .github/config.yml
As mentioned a while ago in https://github.com/mne-tools/mne-python/issues/8221#issuecomment-738695038,
here's an attempt to enable to "welcome bot" for this repo
https://github.com/apps/welcome
I've granted the bot the requested access rights to our repo (clicked the respective button), but I cannot verify whether this worked out properly, as I don't seem to have permissions to review access rights. 
cc @cbrnr @drammock
> Enable welcome bot

- .github/workflows/codespell_and_flake.yml
- .github/workflows/compat_minimal.yml
- .github/workflows/compat_old.yml
- .github/workflows/linux_conda.yml
- .github/workflows/linux_pip.yml
- .github/workflows/macos_conda.yml
In hope to prevent future stale CI jobs from blocking the queue again
Doesn't affect all jobs, only those where we've seen stalling
> CI: Cancel GH Actions jobs after 90 min max

- mne/preprocessing/nirs/nirs.py
- mne/preprocessing/nirs/tests/test_nirs.py
None. Just general improvements to error throwing.
It does not make sense to have a combination of certain fnirs data types in the same raw object. For example you shouldn't have optical density and oxyhemoglobin data together. This just adds a check for that.
> MRG: Check that fnirs types are not mixed

- doc/changes/latest.inc
- mne/baseline.py
- mne/dipole.py
- mne/epochs.py
- mne/evoked.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
- mne/tests/test_report.py
- tutorials/evoked/plot_10_evoked_overview.py
- tutorials/evoked/plot_20_visualize_evoked.py
> ENH: Add Evoked.baseline

- mne/annotations.py
- mne/io/artemis123/artemis123.py
- mne/io/base.py
- mne/io/boxy/boxy.py
- mne/io/ctf/ctf.py
- mne/io/ctf/tests/test_ctf.py
- mne/io/curry/curry.py
- mne/io/eeglab/eeglab.py
- mne/io/egi/egi.py
- mne/io/egi/egimff.py
- mne/io/eximia/eximia.py
- mne/io/fiff/raw.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/nedf/nedf.py
- mne/io/nihon/nihon.py
- mne/io/nirx/nirx.py
- mne/io/nirx/tests/test_nirx.py
- mne/io/persyst/persyst.py
- mne/io/snirf/_snirf.py
- mne/io/tests/test_raw.py
- mne/utils/check.py
- mne/utils/tests/test_check.py
closes #9221 
This one-line fix is almost certainly too simplistic and will probably break something, so I'm hoping for some intense scrutiny here.  Here's my understanding of the problem and solution(?):
1. `datalad` uses `git-annex` to manage large data files (`datalad` is the recommended access method for OpenNeuro, so it's really something we should support)
2. for split raw files, this poses a problem because when the first raw is loaded, we call `os.path.realpath()` on the filename, so something like `sub-01/ses-day1/meg/sub-01_ses-day1_task-AVLearn_run-01_part-01_meg.fif` becomes `/home/user/Desktop/test-datalad/ds002598/.git/annex/objects/Xz/5P/MD5E-s2146079382--dca9c1e4ee05b6b32bdcd4b5aef8c9bb.fif/MD5E-s2146079382--dca9c1e4ee05b6b32bdcd4b5aef8c9bb.fif`
3. that works fine for …
> FIX: don't use op.realpath when reading raw

- doc/_static/style.css
closes #9222 
The CSS controlling this is inherited from sphinx.  It works the same on, e.g., [the pandas site](https://pandas.pydata.org/docs/reference/api/pandas.array.html) but is less of a problem there because their default font size is one px smaller than ours, and possibly also because their preferred font is Lato instead of Source Sans Pro (I think Lato is slightly lighter / has tighter spacing). This solution fixes the problem of the colon being wrapped even with full-width windows. It does not fix the problem of `Parameters:` becoming
```
Pa
ra
me
te
rs:
```
when the window is narrowed. For that, adjustments to the theme's media breakpoints would be required, and it should really be fixed in the theme rather than overridden here.
> fix API parameter column width [skip github][skip azp]

- mne/viz/_brain/_brain.py
- mne/viz/backends/_pysurfer_mayavi.py
- tutorials/source-modeling/plot_mne_dspm_source_localization.py
Deal with the [CircleCI failures on main](https://app.circleci.com/pipelines/github/mne-tools/mne-python/7622/workflows/138e0f79-b04d-4fa3-ab02-74d4bea59ddf/jobs/26701/tests#failed-test-0) of the form:
```
File "/home/circleci/project/mne/viz/_3d.py", line 1780, in plot_source_estimates
return _plot_stc(
File "/home/circleci/project/mne/viz/_3d.py", line 1958, in _plot_stc
brain.setup_time_viewer(time_viewer=time_viewer,
File "/home/circleci/project/mne/viz/_brain/_brain.py", line 658, in setup_time_viewer
self._configure_dock()
File "/home/circleci/project/mne/viz/_brain/_brain.py", line 1111, in _configure_dock
self._configure_dock_trace_widget(name="Trace")
File "/home/circleci/project/mne/viz/_brain/_brain.py", line 1088, in …
```
> MAINT: Work around PyVista change

- .circleci/config.yml
- doc/conf.py
- doc/install/mne_c.rst
- mne/conftest.py
- mne/morph.py
- tools/circleci_dependencies.sh
- tools/github_actions_dependencies.sh
Our linkcheck is failing:
https://app.circleci.com/pipelines/github/mne-tools/mne-python/7631/workflows/6438a1dc-962b-43f2-9018-69c546ee3e4f/jobs/26711
1. Add support for `[circle linkcheck]`
2. Add support for `[circle interactive_test]` (which would have helped @drammock recently to debug a matplotlib issue)
3. Add support for `[circle skip]` and `[skip circle]` to skip our doc build step (and interactive_test and linkcheck if they aren't explicitly requested)
Makes use of CircleCI job parameters and the magic `circleci-agent step halt` to kill a job early based on commit message conditionals.
Once the CircleCI gymnastics work, I'll need to actually check the links, but in theory once CIs come back green this should be good to go.
> MAINT: Add linkcheck

- doc/changes/latest.inc
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
closes #9228 
Note that I couldn't figure out how to test this when backend is Mayavi.
> expose colorbar label parameter in plot_sensors_connectivity

- doc/changes/latest.inc
- mne/viz/evoked.py
Currently this:
```py
mne.viz.plot_compare_evokeds(evoked, combine=None, picks=picks, axes=axs)
```
compares `axes` to a string, where `axes` is a list of matplotlib axes objects, and raises this:
```
ValueError                                Traceback (most recent call last)
<ipython-input-8-e36b566cce17> in <module>
----> 1 foo = mne.viz.plot_compare_evokeds({'mean': evoked}, combine=None, picks=picks, axes=axs)
/opt/mne/python/mne/viz/evoked.py in plot_compare_evokeds(evokeds, picks, colors, linestyles, styles, cmap, vlines, ci, truncate_yaxis, truncate_xaxis, ylim, invert_y, show_sensors, legend, split_legend, axes, title, show, combine, sphere)
2252              .format(len(picks), combine))
2253     # `combine` defaults to GFP unless picked a single channel or axes='topo'
-> 2254 …
```
> fix: error when passing axes to plot_compare_evokeds

- mne/gui/tests/test_file_traits.py
- mne/io/_digitization.py
- mne/io/egi/egimff.py
- mne/io/egi/tests/test_egi.py
- mne/io/meas_info.py
@christianbrodbeck see https://github.com/mne-tools/mne-python/issues/9250, this PR fixes the behavior in `main`:
```
>>> mne.viz.plot_alignment(mne.io.read_raw_egi(mne.datasets.testing.data_path() + '/EGI/test_egi.mff').info, show_axes=True, dig=True, eeg=True, coord_frame='head')
```
To properly transform to the head coordinate frame (this PR):
No need for latest.inc update because this was added within-cycle in #8789
Closes  #9250
> BUG: Fix coordinate frame

- doc/changes/latest.inc
- mne/commands/mne_browse_raw.py
- mne/viz/_figure.py
- mne/viz/tests/test_raw.py
I prefer to browse data with projections off when looking for bad channels, and adding this `--projoff` option allows me to use a one-liner command and start immediately arrow-keying around to look for flux jumps:
```
mne browse_raw --allowmaxshield --lowpass 40 --duration 30 --projoff my_raw.fif
```
I also snuck in a fix for the matplotlib deprecations:
```
/usr/lib/python3.9/_collections_abc.py:1023: MatplotlibDeprecationWarning: 
The modification of the Axes.lines property was deprecated in Matplotlib 3.5 and will be removed two minor releases later. Use Artist.remove() instead.
del self[self.index(value)]
/usr/lib/python3.9/_collections_abc.py:1023: MatplotlibDeprecationWarning: 
The modification of the Axes.texts property was deprecated in Matplotlib 3.5 and will be removed two minor …
```
> MRG, ENH: Add projoff option

- mne/channels/interpolation.py
It looks like a recent change in MNE broke `autoreject` CIs. See here: https://github.com/autoreject/autoreject/pull/203/. Since it's still in the main branch, I propose to make a tiny fix so the CIs in autoreject become happy
> [MRG] MAINT: make exclude optional so its backwards compatible with autoreject

- doc/changes/latest.inc
- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/open.py
- mne/io/tag.py
This makes it so we at least get a nice warning about a corrupted file if the tag directory is missing. In real cases there is usually more than this and eventually we hit an error about channel information missing, but the warning now is much more informative than what we had before (something along the lines of "NoneType has no attribute pos").
I also improved an error message for raw concat incompatibility while I was messing around with some incompatible files.
> ENH: Add support for missing dir

- mne/channels/interpolation.py
- mne/preprocessing/nirs/_beer_lambert_law.py
- mne/preprocessing/nirs/_optical_density.py
- mne/preprocessing/nirs/_scalp_coupling_index.py
- mne/preprocessing/nirs/_tddr.py
- mne/preprocessing/nirs/nirs.py
- mne/preprocessing/nirs/tests/test_nirs.py
addresses https://github.com/mne-tools/mne-python/pull/9141#discussion_r610730226
Use the info field for checking NIRS metadata is stored correctly, not the raw structure.
As suggested by @HanBnrd, and this should enable usage in functions that only have access to info, like set_montage.
> MRG: Use info for checking NIRS metadata, not raw

- mne/channels/interpolation.py
- mne/preprocessing/nirs/_beer_lambert_law.py
- mne/preprocessing/nirs/_optical_density.py
- mne/preprocessing/nirs/_scalp_coupling_index.py
- mne/preprocessing/nirs/_tddr.py
- mne/preprocessing/nirs/nirs.py
- mne/preprocessing/nirs/tests/test_nirs.py
Addresses https://github.com/mne-tools/mne-python/pull/9141#discussion_r610730226.
Use the info field to get NIRS frequencies and chromophores, not the raw structure.
Extension of @rob-luke's work with #9280.
This should enable usage in functions that only have access to info, like set_montage.
> MRG: Use info to get NIRS metadata, not raw

- environment.yml
- mne/viz/_brain/_brain.py
- mne/viz/backends/_notebook.py
- requirements.txt
- tools/azure_dependencies.sh
- tools/circleci_dependencies.sh
- tools/github_actions_dependencies.sh
On the latest version, the API for `_add_observer()` and `use_ipyvtk` have been modified. This PR tries to catch up to those changes. Changes are also necessary in PyVistaQt.
Follows https://github.com/mne-tools/mne-python/pull/9010#issuecomment-816740584
> FIX: Prepare for PyVista 0.30.0

- mne/io/edf/edf.py
Fixes #9271. The example file mentioned in #9271 contains only annotations and no signals. `mne.io.read_raw_edf` throws an error later in the pipeline. At least for this example file, `record_length[0] == 0` is `True`, so I just extended the warning message there. I don't know if this catches all possible annotations-only cases, but I'd go with YAGNI for now.
> Better warning message for EDF files with annotations only

- doc/changes/latest.inc
- mne/preprocessing/eog.py
- mne/preprocessing/tests/test_eog.py
- mne/utils/docs.py
`find_eog_events()` and `create_eog_epochs()` now accept a list of channel names as a way to specify multiple EOG channels at once. Previously, one could only do that via an (undocumented!) concatenation of channel names, separated by commas, e.g. `'EEG 061,EEG 062'`.
Also reworks the docstring and adds more test cases.
> MRG, ENH: Allow to pass multiple channels to find_eog_events(), create_eog_epochs()

- doc/changes/latest.inc
- examples/connectivity/plot_mixed_source_space_connectivity.py
- examples/connectivity/plot_mne_inverse_coherence_epochs.py
- examples/connectivity/plot_mne_inverse_connectivity_spectrum.py
- examples/connectivity/plot_mne_inverse_envelope_correlation.py
- examples/connectivity/plot_mne_inverse_envelope_correlation_volume.py
- examples/connectivity/plot_mne_inverse_label_connectivity.py
- examples/connectivity/plot_mne_inverse_psi_visual.py
- mne/commands/tests/test_commands.py
- mne/io/tests/test_raw.py
- mne/label.py
- mne/minimum_norm/tests/test_inverse.py
- mne/source_estimate.py
- mne/tests/test_source_estimate.py
- mne/utils/check.py
- mne/viz/_3d.py
- tools/get_minimal_commands.sh
- tutorials/source-modeling/plot_visualize_stc.py
You should not be able to extract label time courses for `sample` using labels defined on `fsaverage`, but you can on `main`. This PR tightens up our checks.
~~I also included a temporary workaround to get things green by avoiding the PyVista regression:~~
```
python -m pip install --progress-bar off https://github.com/pyvista/pyvista/zipball/cb59a9ddfd97f5724f733bc226b41fb9ad4c9c5f
```
> MRG, BUG: Fix checking of subjects in eltc

- mne/tests/test_epochs.py
- mne/utils/mixin.py
Closes #9295
I'm not 100% sure we should support just doing `next` like this since:
```
>>> x = [1, 2]
>>> next(x)
File "<stdin>", line 1, in <module>
TypeError: 'list' object is not an iterator
>>> next(iter(x))
1
```
But I can live with the simple fix in this PR, and we used to support it, so why not if it saves some people some pain.
> BUG: Fix bug with next without iter

- doc/changes/latest.inc
- mne/evoked.py
- mne/viz/evoked.py
- mne/viz/tests/test_topo.py
- mne/viz/topo.py
Fixes #9205 .
Adds an exclude parameter to `plot_evoked_topo`.
With the added exclude parameter, ylim's calculations are no longer affected by bad channels that aren't included in the actual plot.
> MRG ENH/BUG Add exclude parameter to plot_evoked_topo

- environment.yml
- mne/viz/_brain/_brain.py
- mne/viz/backends/_notebook.py
- mne/viz/backends/_pyvista.py
- mne/viz/tests/test_3d.py
- requirements.txt
- tools/azure_dependencies.sh
- tools/circleci_dependencies.sh
- tools/github_actions_dependencies.sh
This PR brings the second wave of changes to adapt to PyVista 0.30.0 and PyVistaQt 0.3.0+
ToDo:
Follows https://github.com/mne-tools/mne-python/pull/9274
Related to https://github.com/pyvista/pyvista/pull/1257
> FIX: Prepare for PyVista 0.30.0 (part 2)

- mne/viz/_3d.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/_qt.py
- mne/viz/backends/_utils.py
- tutorials/sample-datasets/plot_phantom_4DBTi.py
- tutorials/source-modeling/plot_source_alignment.py
It seems that https://github.com/mne-tools/mne-python/pull/8852 was not enough. I'll investigate the issue thoroughly in here and come back to https://github.com/mne-tools/mne-python/pull/9010 afterwards.
Progress:
ToDo:
Related to https://github.com/mne-tools/mne-python/pull/9010#issuecomment-805002328, https://github.com/mne-tools/mne-python/pull/8828
> FIX: paintEvent/resizeEvent & update

- doc/conf.py
works around the deprecation warning. I think there's also a theme error about `'meta'` being undefined which I didn't get to today.  @larsoner feel free to push here if you want, otherwise I'll pick it up tomorrow.
> maint: ignore jinja deprecation warning

- mne/preprocessing/_csd.py
Addresses https://github.com/mne-tools/mne-python/issues/9319
> [MRG, DOC] Remove CSD average reference note

- examples/simulation/plot_simulate_evoked_data.py
- examples/visualization/plot_3d_to_2d.py
- mne/viz/backends/_qt.py
- tutorials/sample-datasets/plot_phantom_4DBTi.py
- tutorials/source-modeling/plot_source_alignment.py
This PR follows https://github.com/mne-tools/mne-python/pull/9313#issuecomment-822534247. For now, I'm trying to understand what is going on exactly.
Closes #9007
> MNT: BackgroundPlotter has no attribute named image

- doc/references.bib
- examples/io/plot_read_xdf.py
- mne/datasets/utils.py
- requirements_doc.txt
- tutorials/io/plot_20_reading_eeg_data.py
Closes #5180.
Besides tidying up and improving the docstring a bit, I have added a section on how to import XDF data.
> Add XDF to "Reading EEG data" tutorial

- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/data/test_old_layout_latin1_software_filter_longname.vhdr
- mne/io/brainvision/tests/test_brainvision.py
- mne/tests/test_line_endings.py
I've been given a bunch of brainvision files with software filter settings in the VHDR file. Loading failed because the reader seems to assume that the first column contains channel names, when in fact it looks like it contains indices:
```
S o f t w a r e  F i l t e r s
==============================
1      10               125                Off
2      10               125                Off
3      10               125                Off
...
``` 
This PR fixes that for my files. However, I noticed that none of the testing `*.vhdr` files have a `S o f t w a r e  F i l t e r s` list, they all say
```
S o f t w a r e  F i l t e r s
==============================
Disabled
```
So I don't know whether `S o f t w a r e  F i l t e r s` *always* have channel indices or whether they might …
> WIP: FIX brainvision I/O:  Software Filters section

- mne/beamformer/tests/test_dics.py
- mne/beamformer/tests/test_lcmv.py
- mne/io/fieldtrip/fieldtrip.py
- mne/io/fieldtrip/tests/test_fieldtrip.py
- mne/viz/_brain/tests/test_notebook.py
On most PRs we end up waiting for the macOS CI to finish. This is probably really because it takes 20 minutes (!) to set up the conda env, but we might as well also cut our testing time down from the 30 minutes that it currently runs there. This PR does it without sacrificing much testing by skipping some tests that are mostly redundant once we've run them on one OS, so let's let Linux do the heavy lifting and make macOS and Windows (which both `pytest -m "not slowtest"`) a bit faster.
> MAINT: Mark more tests as slow for macOS

- doc/changes/names.inc
- doc/conf.py
- doc/sphinxext/gen_names.py
Currently we don't check anyone's `names.inc` URLs but we should. This adds a little extension that outputs a `generated/_names.rst` when using the linkcheck builder.
I see some failures locally with the check so I'll push that first to make sure we see it on CIs, then I'll add another commit to fix them.
> MAINT: Check name URLs

- mne/viz/_figure.py
- mne/viz/epochs.py
- mne/viz/ica.py
- mne/viz/raw.py
closes #9276 (supersedes)
In order to get this fixed before release time, I've removed the blitting code.  This slows down vline drawing (esp. in butterfly mode, where it can take up to a few seconds) but at least now the bug is fixed.  I'll try to restore the blitting after release, when there is more time for testing.
@jasmainak can you test?
> fix epochs vlines

- doc/changes/latest.inc
- mne/io/reference.py
- mne/io/tests/test_reference.py
Fixes #8718
This improves the performance of adding a larger number (>25) of bipolar channels as suggested by @jasmainak.
EDIT: A gist to measure the speed can be found [here](https://gist.github.com/marsipu/73f10b5303599837c8f182f0ab3f9e99)
I encountered some difficulties with how to best organize the creation of the new channels with the new method and handling Info while staying conservative. I think a large part of the performance improvement comes from moving `add_channels` outside the loop as done with the last commit `29f609d2`. Before, even with the new matrix-multiplication-method the performance was much smaller with n>25.
At the moment, the new bipolar-channels are always appended (like when `drop_refs=False`) and don't take the place of the anode as in the previous …
> ENH: Speed up set_bipolar_reference

- MANIFEST.in
- azure-pipelines.yml
- requirements.txt
- requirements_doc.txt
- requirements_testing.txt
- requirements_testing_extra.txt
- tools/azure_dependencies.sh
- tools/circleci_dependencies.sh
- tools/github_actions_dependencies.sh
Inspired by #9192 I think we need a little bit more granularity in our test infrastructure, so:
1. Remove `ipytest`, it was errantly added
2. Make SG dep on the latest dev version (see https://github.com/sphinx-gallery/sphinx-gallery/issues/817#issuecomment-824925909, I think we should always use latest SG dev to catch bugs etc. -- we are good early users)
3. Split off some reqs into `requirements_testing_extra.txt`
4. Add comments to our `requirements_*` files to make it clearer why we have/need them
5. Update `azure-pipelines.yml` to include the `requirements_testing_extra.txt` installs
Overall I hope this makes things a bit more DRY and well defined. @drammock I know you've been disappointed with the structure of our requirements, can you see if you think this at least helps instead of …
> MRG, MAINT: Better split of reqs

- doc/conf.py
the bit of `conf.py` that makes the website redirects is failing on local docs rebuillds because I can't count properly.
cc @eioe
> fix local doc builds

- doc/changes/latest.inc
- mne/channels/montage.py
- mne/datasets/utils.py
- mne/io/fiff/tests/test_raw_fiff.py
- mne/io/snirf/_snirf.py
- mne/io/snirf/tests/test_snirf.py
- mne/preprocessing/nirs/__init__.py
- mne/preprocessing/nirs/nirs.py
- mne/preprocessing/nirs/tests/test_nirs.py
- mne/tests/test_report.py
- tools/get_testing_version.sh
Closes #9338 mne-tools/mne-nirs#257 #9308.
This PR enables reading of SNIRF files from the NIRx vendor and it also enables reading of SNIRF files with 2D locations from the SfNIRS team.
Support for 2D locations was enabled by setting the z coordinate to 0.
Support for NIRx was enabled by not relying on the `sourceLabels` field in SNIRF. Which was optional in the spec, so I shouldn't have expected it to be there.
People may wish to support no sensor location info, but they can do that in a future PR.
It may also be possible to do some fancy 2D to 3D conversion for data, but that would be significant work.
I wanted to use an exact copy of some code, so I turned it in to a function called `_validate_nirs_info`
Specifically validating and testing Artinis files will have to wait till someone …
> MRG: Add SNIRF support for 2D locations and NIRx files

- doc/changes/latest.inc
- mne/beamformer/_dics.py
- mne/beamformer/tests/test_dics.py
As discussed in #9215, this PR implements the deprecation of `real_filter=False` in `make_dics`. Instead of using a complex filter by default, the filter should be real-valued.
> DICS beamformer: deprecate the use of complex filter

- mne/viz/_brain/_brain.py
- mne/viz/backends/_qt.py
Closes #9336
@crsegerie can you see if this fixes your problem? 
I was able to replicate on Windows. Basically I think the problem was that after our DPI calculations, the resulting size was something like `1406.99999999` instead of `1407`, so MPL made something with only 1406 pixels instead of 1407 and this broke things. We could try tweaking our DPI calculations, but it seems safer just to output a PNG then read it back, as this has the dimensions, then make use of our smart concat function to take care of any difference in dimension.
Okay with you @GuillaumeFavelier ?
> BUG: Fix concat on Windows

- environment.yml
I've added a darkdetect  package to conda-forge, so it's now trivial to include the packages we need for dark theme selection & automated theme switching in our official conda environment – should be done anyway so our CIs "see" this. Would be cool to get this merged before we make the official 0.23 announcement.
> Add qdarkstyle, darkdetect to environment.yml

- mne/report.py
- tutorials/intro/70_report.py
Showing the head circle with sensors often simply leads to overplotting (GFP traces / sensors) and is unnecessary, as the GFP calculation employs all channels anyway.
> When plotting GFP comparison in Report, don't show sensor layout by default

- mne/data/html_templates.py
- mne/io/meas_info.py
- tutorials/preprocessing/70_fnirs_processing.py
None. But I really love these html outputs in notebooks, so cool.
Add fNIRS to the html output for raw.
I follow #9172, but am unsure how to test this change. Can we merge without a test?
If you don't want to add fNIRS channels as they are less common we could have an optional row using:
```
{{if n_fnirs > 0}}
<th>fNIRS channels</th>
<td>{{n_fnirs}}</td>
{{endif}}
```
I tested this locally and it works too, I could do the same for EOG and ECG too if you want.
> MRG: Add fNIRS to html output

- mne/stats/_adjacency.py
- mne/utils/docs.py
closes #9364 
@larsoner following up on our conversation today, this should clarify the docstring at least.  I also snuck in a code simplification, though I realized that the functionality for omitting adjacency along a particular dimension is already there, you just need to pass a matrix of zeros for that dimension.
> better docs for permutation_cluster_test

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/epochs.py
- mne/evoked.py
- mne/tests/test_epochs.py
- mne/tests/test_evoked.py
Fixes #9374 
Set `include_tmax=True` when `tmax` is larger than the epoch.
I think this cannot be sensibly done in the `_time_mask` function as we do not know whether `tmax` was set automatically or not in that function. However, I do now knot if `_time_mask` should do this kind of error handling or if it is up to the calling functions.
> FIX: make epoch cropping idempotent

- README.rst
- environment.yml
- requirements.txt
This PR follows the release of `pyvistaqt 0.4.0`. No need to pin a master commit anymore.
> MNT: Use pyvistaqt 0.4

- doc/changes/latest.inc
- mne/io/nirx/nirx.py
- mne/morph.py
- mne/source_estimate.py
- mne/tests/test_morph.py
- mne/tests/test_source_estimate.py
- mne/viz/_brain/_brain.py
I have some fNIRS collaborators who generate figures where the fNIRS electrodes are projected onto the nearest brain areas, like in ECoG:
or:
Yes, I know the units on the colorbar are painful. :) But at least it's clear it's just a proximity-based projection and not actual inverse imaging!
This PR makes this possible by:
1. Adding a `picks` argument to `stc_near_sensors` so that fNIRS electrodes (HbO usually) can be used.
2. Adding a `smoothing_steps=0` meaning "no smoothing steps at all". Even `smoothing_steps=1` makes some smooth transitions where discrete ones are really desired. This caused me to shift "nearest" to -1 in the `brain` interface, which I think is fine.
3. Adding a `mode='weighted'` argument to `stc_near_sensors` that ensures that each STC vertex value is either zero, or …
> MRG, ENH: Extend usability of stc_near_sensors

- mne/epochs.py
- mne/utils/docs.py
Clarify that these parameters apply to `Epochs.flat` also.
> MRG, DOC: Improve reject_tmin,tmax doc

- doc/conf.py
- mne/viz/backends/_pyvista.py
- tutorials/intro/10_overview.py
Will hopefully come back green to fix our [failures on main](https://app.circleci.com/pipelines/github/mne-tools/mne-python/8248/workflows/18ca6c8d-0432-4f01-b105-2dcd8343b71a/jobs/28537). This PyVista deprecation of `rcParams`->`global_params` is turning out to be a bit of a pain
> MRG, ENH: Fix doc build

- doc/overview/people.rst
very minor typo fix to make a URL in our docs work again.
> [doc, minor] fix link

- tutorials/io/30_reading_fnirs_data.py
None
Reordering and expanding the information in the fNIRS data type tutorial. As its had lots of growth lately but not much structure.
> MRG: Restructure fNIRS IO tutorial

- mne/viz/_figure.py
Example: Fixes #9413.
The error happening when changing the shown duration by pressing `End` is fixed.
I am not sure, what the problem with the flickering was which motivated this line. I assumed that redrawing the vline was the intention, so I replaced `_show_vline` directly with `_toggle_vline`.
> Fix error when reducing shown time-window while vline visible

- mne/io/egi/egimff.py
Will self-merge if everything comes back green to get `main` back to green. @ephathaway does this look like the correct fix to you? Takes care of this deprecation warning:
```
mne/io/egi/tests/test_egi.py:325: in test_io_egi_evokeds_mff
evokeds = read_evokeds_mff(egi_mff_evoked_fname)
<decorator-gen-206>:24: in read_evokeds_mff
???
mne/io/egi/egimff.py:785: in read_evokeds_mff
raise ValueError(f'{fname} is a {mff.flavor} MFF file. '
../../.local/lib/python3.9/site-packages/mffpy/cached_property.py:36: in _cached_property
ans = fn(self)
../../.local/lib/python3.9/site-packages/deprecated/classic.py:284: in wrapper_function
warnings.warn(msg, category=category, stacklevel=_routine_stacklevel)
E   DeprecationWarning: Call to deprecated function (or staticmethod) flavor. (Use ".mff_flavor" …
```
> MRG, MAINT: Updates for mffpy 6.3

- tutorials/io/30_reading_fnirs_data.py
In #9408 I made changes to the fNIRS data tutorial. @drammock made some suggestions for improvements that did not get included (https://github.com/mne-tools/mne-python/pull/9408#pullrequestreview-664550295). This PR includes these suggestions. Thanks @drammock!
> MRG: Tutorial improvements

- mne/morph.py
- mne/source_space.py
- mne/surface.py
- mne/tests/test_coreg.py
- mne/tests/test_source_space.py
- mne/utils/__init__.py
- mne/utils/numerics.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/surface.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/backends/_abstract.py
- mne/viz/backends/_pysurfer_mayavi.py
- mne/viz/backends/_pyvista.py
1) This PR reduces the amount of renderer updates. I modified the two main entry points: `__init__()` and `setup_time_viewer()`.
For now I use a context manager but if big chunks of code need to be nested maybe `enable/disable` functions are better, not sure.
I'm still trying to download 0.119 locally so testing is delayed but in the example that I use regularly, it went from 16 to 1.
2) I'll see how to reduce the amount of overlay updates next.
3) I'll also investigate why the window is so slow to setup (suggested in https://github.com/mne-tools/mne-python/pull/9407#issuecomment-844199125)
Closes https://github.com/mne-tools/mne-python/issues/8986
> MNT: Reduce number of calls to _update

- mne/tests/test_epochs.py
- mne/viz/_brain/tests/test_notebook.py
Takes the test from ~60 sec on my system to ~5 sec. I think it's due to rendering the movie.
It takes about 240 sec on CIs on `main`, let's see if it's better there, too.
> MRG, ENH: Speed up brain test

- tools/azure_dependencies.sh
- tools/github_actions_dependencies.sh
Hopefully allows fewer tests to be skipped on the `pip-pre` runs
> MRG, ENH: Test more on pre

- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
This PR fixes parameter forwarding in the `save_movie()` method and also the `Save movie...` action in the tool bar.
**ToDo:**
Closes https://github.com/mne-tools/mne-python/issues/9425
> FIX: brain save_movie

- doc/changes/latest.inc
- mne/channels/interpolation.py
- mne/channels/tests/test_interpolation.py
Enables interpolation on all fNIRS types using the new and more generic `_validate_nirs_info` function.
> MRG: Enable interpolation for all fNIRS types

- mne/fixes.py
- mne/gui/_coreg_gui.py
- mne/io/brainvision/brainvision.py
- mne/io/kit/kit.py
- mne/utils/misc.py
closes #9432
A simple PR to improve consistency in the code base: using `mne.utils.warn`, instead of different warning calls.
> [MRG] change utils.logger.warning -> utils.warn

- examples/connectivity/mne_inverse_envelope_correlation.py
- examples/connectivity/mne_inverse_envelope_correlation_volume.py
- examples/inverse/evoked_ers_source_power.py
- examples/inverse/psf_ctf_vertices.py
- examples/inverse/psf_ctf_vertices_lcmv.py
- mne/label.py
- mne/tests/test_label.py
- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
- tutorials/inverse/85_brainstorm_phantom_ctf.py
1. Fix problems with examples introduced by #9435
2. Reduce memory usage of envelope correlation examples that seem to keep killing CircleCI
3. Use more standard `_check_option` / `_validate_type` in `Brain` to give more informative messages for bad Brain args.
> MRG, MAINT: Better mem usage and errors

- doc/changes/latest.inc
- mne/io/_read_raw.py
- mne/report.py
- mne/tests/test_report.py
This is an issue as a PR, I have opened this for discussion.
Allows
```python
report = mne.Report()
report.parse_folder(path)
```
to read fNIRS files stored with the pattern `*-nirs.snirf` as defined in the draft BIDS standard https://bids-specification--802.org.readthedocs.build/en/802/04-modality-specific-files/10-functional-near-infrared-spectroscopy.html#fnirs-recording-data
It seems report is currently used with fiff files, are we open to extending it to other file types?
Allowing the file pattern above will facilitate reading files in the BIDS format. The fNIRS BIDS specification has moved from a community feedback stage to draft proposal: https://github.com/bids-standard/bids-specification/pull/802 However, its not finalised (as I am the BEP lead it is extremely unlikely this file …
> MRG: Add fnirs and snirf support to report

- doc/changes/latest.inc
- mne/io/nihon/nihon.py
- mne/io/nihon/tests/test_nihon.py
Fixes/Implements #9429.
Nihon Kohden reader was not tested using multiple datablocks (maybe due to only having continuous recordings? don't really know yet). This PR allows to read NK EEG files with multiple datablocks.
Still needs to be tested against the corresponding EDF files.  PR is WIP.
> [ENH] Add support for multiple datablocks in Nihon Kohden files

- mne/time_frequency/multitaper.py
- mne/time_frequency/psd.py
I found a couple hard-coded refs today that slipped through the code sprint...  they weren't properly linked so my regex missed them.
> fix lingering hard-coded references

- doc/changes/latest.inc
- mne/decoding/time_delaying_ridge.py
Addresses #9455 by switching `np.convolve` to `fftconvolve` from `scipy.signal`. Speeds up `predict` function.
Closes #9455
> MRG, ENH: Speed up TimeDelayingRidge.predict()

- doc/conf.py
- mne/utils/misc.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/_qt.py
- tutorials/forward/35_eeg_no_mri.py
CircleCI can't complete building because we're running out of memory (again), so I'm investigating why some things can't be cleaned up (again). Locally on this branch running some 3D examples I see that some vtkPolyData objects stick around:
<details>
```
$ PATTERN="\(35_eeg_no\|50_background_free\)" xvfb-run make html_dev-pattern-memory
...
Handler <function generate_gallery_rst at 0x7f474340db80> for event 'builder-inited' threw an exception (exception: 2 BackgroundPlotter:
dict: len=14, 3 referrers: dict/list
dict: len=14, 3 referrers: dict/list
dict: len=2, 5 referrers: dict/list
dict: len=55, 4 referrers: BackgroundPlotter/dict/list
QFrame: <PyQt5.QtWidgets.QFrame object at 0x7f4700c521f0>
method: <bound method QVTKRenderWindowInteractor.paintEvent of …
```
> WIP: Reduce memory usage in doc build

- doc/changes/latest.inc
- mne/viz/ica.py
- tutorials/preprocessing/40_artifact_correction_ica.py
For #9417
This is supposed to make the differentiation of multiple ICA-components displayed for evokeds easier by displaying them in different colors.
**Are there more ICA-Categories than EOG/ECG which would be displayed simultaneously to consider?**
In this draft I accounted for different categories by assigning a different colormap for each one.
> ENH: multiple colors for ica.plot_sources(evokeds)

- mne/io/ctf/ctf.py
- tutorials/io/60_ctf_bst_auditory.py
There is no documentation that says that the Polhemus digitization `.pos` file can be read into a `mne.ioRaw` instance via `mne.io.read_raw_ctf` when the .pos file is placed in the CTF directory. 
Fixes #9452. 
- Added this info in the Notes of `mne.io.read_raw_ctf`. 
- Added this as a note in the CTF tutorial in the following section.
https://github.com/mne-tools/mne-python/blob/c0d431acf0307a8bf92ab01995397194563f6920/tutorials/io/60_ctf_bst_auditory.py#L76-L89
> DOC: add info about reading in digitization data from CTF dir

- mne/bem.py
ETSContext is a relic from when we used Mayavi to process things. Now it's done with vtk directly:
https://github.com/mne-tools/mne-python/blob/c40056c11023ff2d57b4e7bd16904deda280880a/mne/surface.py#L1140-L1179
> MAINT: Remove unnecessary context

- mne/io/snirf/_snirf.py
- mne/io/snirf/tests/test_snirf.py
PR #9401 introduced the argument `optode_frame` to `read_raw_snirf`. This was being used to transform the coordinates of sensors, but was not being stored in `info['chs']`.  Also added a test.
> MRG: Honor optode_frame argument in read_raw_snirf 

- doc/changes/latest.inc
- mne/epochs.py
- mne/tests/test_epochs.py
> MRG, FIX: Allow multiple runs of Epochs.drop_bad() even if only using a subset of initial reject channels

- mne/datasets/_fsaverage/base.py
I passed `subjects_dir='~/foo'` and the data ended up in `~/mne_data/~/foo`, which was not nice.
> ENH: Expand ~ to home dir in fetch_fsaverage()

- doc/changes/latest.inc
- mne/viz/ica.py
This avoids overlap between axis title and suptitle.
First reported by @crsegerie at https://github.com/mne-tools/mne-bids-pipeline/issues/364
My solution feels a bit hacky but does the trick.
Demo:
```python
import mne
raw = mne.io.read_raw_fif(sample_fname, preload=True).crop(60)
ica = mne.preprocessing.ICA(n_components=0.8, method='picard')
ica.fit(raw)
ecg_epochs = mne.preprocessing.create_ecg_epochs(raw)
idx, scores = ica.find_bads_ecg(ecg_epochs)
ica.plot_scores(scores=scores, exclude=idx, labels='ecg')
```
`main`:
This PR:
> Use different subplot adjustment when plotting scores for a single channel

- mne/viz/backends/_pyvista.py
This PR fixes the error:
```
RuntimeError: Render window interactor must be initialized before processing events.
```
reported in https://github.com/mne-tools/mne-python/pull/9468#issuecomment-865685608
> FIX: Follow the changes of PyVista 0.31.2

- tools/azure_dependencies.sh
- tools/circleci_dependencies.sh
- tools/github_actions_dependencies.sh
Because they changed `master` to `main` the download URL isn't working anymore (used in our CircleCI).
> Update download URL to pyvista main branch

- doc/changes/0.23.inc
- doc/changes/latest.inc
> fix changelog [ci skip]

- doc/changes/latest.inc
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
Fixes #9466. Things to do/discuss:
- I've named the parameter `cnorm` (for "color normalization"), because I think this better describes its purpose. It also avoids a name clash with an already existing local name `norm` (which has something to do with the L2 norm, not entirely sure). However, Matplotlib calls this parameter `norm`, so if we want to mimic their naming scheme we could also call our parameter `norm` instead.
- I need to add a test.
- When passing `cnorm`, simultaneously passing `vmin` and `vmax` is deprectated, because these are already defined in the normalizer. I've implemented a pretty blunt workaround, but we could instead define a default linear normalizer with `vmin` and `vmax` and then never pass these explicitly.
> Add color normalization parameter to plot_topomap

- tools/azure_dependencies.sh
- tools/circleci_dependencies.sh
- tools/github_actions_dependencies.sh
Follows https://github.com/mne-tools/mne-python/pull/9497 and https://github.com/pyvista/pyvistaqt/pull/120, the PR updates the branch name of `pyvistaqt`.
> Update download URL to pyvistaqt main branch

- doc/changes/latest.inc
- mne/preprocessing/realign.py
@larsoner  np.polyfit was deprecated when I tried to use the realign function to sync our eeg / meg data. This is an update to use the Polynomial.fit method suggested by Numpy in the deprecation warning. Take a look and see what you think.
> use Polynomial.fit for poly fitting

- doc/changes/latest.inc
- mne/channels/channels.py
- mne/io/nirx/tests/test_nirx.py
- mne/io/snirf/_snirf.py
- mne/io/snirf/tests/test_snirf.py
See https://mne.discourse.group/t/montage-either-not-saved-in-fif-or-not-read/3356
Ensures get_montage() works with fNIRS data
* The NIRx reader already worked with get_montage, so I added a test to ensure it keeps working.
* Added info[dig] to the SNIRF reader. And added test that get_montage returns data.
I always find the digitisation stuff tricky, so please review critically (as always 😉)
> MRG: Test get_montage on fNIRS data

- azure-pipelines.yml
Hopefully fixes our ultraslow timeout, which is most likely due to VTK 9.0.2
> MAINT: Avoid VTK 9.0.2

- doc/changes/latest.inc
- doc/conf.py
- doc/mri.rst
- mne/__init__.py
- mne/datasets/utils.py
- mne/defaults.py
- mne/morph.py
- mne/tests/test_morph.py
- mne/tests/test_source_estimate.py
- mne/tests/test_transforms.py
- mne/transforms.py
- mne/utils/docs.py
- tutorials/clinical/10_ieeg_localize.py
Another version of #9515, but with fewer tests modified. The relevant ones pass locally at least.
@alexrockhill feel free to test _USE_PREALIGN=False to see if it works better now!
> MRG, ENH: Abstracted volume registration again

- doc/changes/latest.inc
- mne/preprocessing/maxwell.py
- mne/preprocessing/tests/test_maxwell.py
Just add a test that things behave how we expect for #9479, and a warning to help people. We could maybe do something smarter than just quit, but I think it makes sense to just point people to `annotate_flat` so that they can fix things there instead. With this code a variant of the minimal example from #9479 works as expected:
```
import mne
raw = mne.io.read_raw_fif('sub-1011_ses-20190430_task-vid2_meg.fif').load_data()
raw.set_channel_types(dict(EEG061='eog', EEG062='eog'))
annot, _ = mne.preprocessing.annotate_flat(raw, bad_percent=100, verbose=True)
raw.set_annotations(annot)
mne.preprocessing.find_bad_channels_maxwell(
raw, skip_by_annotation=('bad_flat',), verbose=True)
```
Closes #9479
> MRG, BUG: Deal with flats better in maxwell autobad

- doc/changes/latest.inc
- mne/preprocessing/nirs/_optical_density.py
- mne/preprocessing/nirs/_scalp_coupling_index.py
- mne/preprocessing/nirs/_tddr.py
- mne/preprocessing/nirs/tests/test_optical_density.py
- mne/preprocessing/nirs/tests/test_scalp_coupling_index.py
- mne/preprocessing/nirs/tests/test_temporal_derivative_distribution_repair.py
cc @rob-luke I think the protection against negative + zero values was not quite done safely enough
> BUG: Fix bug with optical_density

- doc/changes/latest.inc
- mne/epochs.py
- mne/io/base.py
- mne/viz/_figure.py
- mne/viz/epochs.py
- mne/viz/raw.py
- mne/viz/tests/test_figure.py
- mne/viz/topomap.py
Fixes #9441.
This adds an `exclude` parameter to `raw.plot_psd()`, which makes it possible to plot the PSD of *all* channels (including bads) using `raw.plot_psd(exclude=[])`.
Questions/To Do:
> Add exclude parameter to raw.plot_psd()

- mne/viz/raw.py
I found it rather difficult to understand the `scalings` values used in `Raw.plot()`, because the description does not include any details. @drammock please feel free to revise/improve, I'm not really happy with it but cannot think of anything better right now. I think the key point is to explicitly mention that the visualized range is actually twice the scaling value.
> Improve scalings description in Raw.plot()

- mne/annotations.py
- mne/tests/test_annotations.py
- tutorials/preprocessing/70_fnirs_processing.py
Following #9525 #9523
Demonstrate new annotation name and duration setting in a tutorial.
> MRG: Fix return type for raw.annotations.rename and add to tutorial

- doc/conf.py
We use https://sphinx-copybutton.readthedocs.io/en/latest/ in our docs. This PR makes use of sphinx-copybutton configurations to improve copying.
Namely, fields like this one:
```
$ make html
```
or like this one:
```
>>> 1+1
2
```
Will copy without the respective prompts (--> `make html` instead of `$ make html`), and can thus be directly pasted into the terminal / editor.
Examples for what will be improved:
- Python example blocks in the API docs, like here: https://mne.tools/stable/generated/mne.io.Raw.html
- Contributor docs, like here: https://mne.tools/stable/install/contributing.html#building-the-documentation
> DOC: use regexps for sphinx-copybutton

- doc/changes/latest.inc
- mne/epochs.py
- mne/tests/test_epochs.py
There was an edge case when concatenating Epochs and one (or more) of the `Epochs` objects was empty. See #9533.
fixes #9533
> [MRG] Make concatenate_epochs work with empty Epochs objects

- mne/viz/topomap.py
@drammock requested a version comment in #9541 but it exists in our minimum mpl 3.1.0 so we should just be able to use it:
https://matplotlib.org/3.1.0/api/collections_api.html?highlight=pathcollection#matplotlib.collections.PathCollection.get_edgecolors
> MAINT: Try simpler color workaround

- doc/changes/latest.inc
- mne/viz/tests/test_topomap.py
- mne/viz/topomap.py
- mne/viz/utils.py
Fixes evoked.plot_topomap when passing axes from a fig created with `constrained_layout=True`
> MRG, BUG: Fix behavior with constrained_layout=True

- doc/changes/latest.inc
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/edf/tests/test_gdf.py
- mne/time_frequency/psd.py
So far the `exclude` parameter in `read_raw_{e,b,g}df` only accepts a list of channel names to be excluded. I think it would be nice if it also accepted a regex.
> Accept regex for exclude in `read_raw_{e,b,g}df`

- doc/changes/latest.inc
- mne/io/base.py
- mne/io/egi/egimff.py
- mne/io/egi/tests/test_egi.py
On `main` the added test yields a variant of:
<details>
```
mne/io/egi/tests/test_egi.py:118: in test_egi_mff_pause_chunks
raw.save(fname_temp)
<decorator-gen-192>:24: in save
???
mne/io/base.py:1449: in save
_write_raw(fname, self, info, picks, fmt, data_type, reset_range,
mne/io/base.py:2108: in _write_raw
final_fname = _write_raw_fid(
mne/io/base.py:2197: in _write_raw_fid
data, times = raw[picks, first:last]
mne/io/base.py:773: in __getitem__
return self._getitem(item)
mne/io/base.py:780: in _getitem
data = self._read_segment(start=start, stop=stop, sel=sel,
<decorator-gen-185>:24: in _read_segment
???
mne/io/base.py:419: in _read_segment
_ReadSegmentFileProtector(self)._read_segment_file(
mne/io/base.py:2037: in _read_segment_file
return self.__raw.__class__._read_segment_file( …
```
> MRG, BUG: Fix MFF reading with skips

- doc/changes/latest.inc
- mne/channels/tests/test_interpolation.py
- mne/evoked.py
- mne/io/tests/test_reference.py
- mne/tests/test_evoked.py
- setup.cfg
fixes #9244 
working on #9553 I thought I'd give this a shot as well. Please let me know what I should add - I can add the `units` parameter here or in #9553, depending on which one gets merged earlier.
~EDIT: the tmin/tmax params from https://github.com/mne-tools/mne-python/issues/9548 could also be added here.~ better in #9556 
To Do
> Add get_data method to Evoked

- doc/changes/latest.inc
- mne/coreg.py
Head decimation can be *very* slow when the original file is highly resolved (e.g. from a laser scan) because it uses a loop.
This fixes it.
> matrix-based head decimation

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/io/snirf/_snirf.py
- mne/io/snirf/tests/test_snirf.py
Fixes #9571
Uses the 'name' field from SNIRF file stim groups as the description for Annotations rather than the index of the stim group.
This is in response to …
> [MRG, ENH] Get annotation description from snirf stim name

- tutorials/machine-learning/50_decoding.py
This adds a label to the colorbar of the generalization across time (GAT) figure in the MVPA tutorial.
> Add label to colorbar in GAT plot

- doc/changes/latest.inc
- doc/links.inc
- doc/mri.rst
- doc/visualization.rst
- mne/__init__.py
- mne/_freesurfer.py
- mne/surface.py
- mne/tests/test_freesurfer.py
- mne/tests/test_surface.py
- mne/utils/docs.py
- mne/viz/__init__.py
- mne/viz/circle.py
- mne/viz/tests/test_circle.py
- tutorials/clinical/20_seeg.py
The idea here is to find which voxels are nearby an electrode contact in order to know which surfaces to plot and for analysis.
This shares internal functions with https://github.com/mne-tools/mne-python/pull/9544/ and is a good reason to make `mne.surfaces._find_voxel_neighbors` private so that it can be used in both scenarios without confusion and user-facing function.
> [MRG, ENH] Find aseg labels near montage

- doc/overview/roadmap.rst
http://www.brainsignals.de has been dead for two weeks now:
https://app.circleci.com/pipelines/github/mne-tools/mne-python/9115/workflows/99c1d733-2635-4541-914c-08e6ff1768a4/jobs/31207
From a quick look I couldn't find a replacement URL, so I'm just removing it unless anyone else knows the correct link.
> MRG, MAINT: Remove dead link

- mne/inverse_sparse/mxne_optim.py
- mne/inverse_sparse/tests/test_mxne_optim.py
When running BCD solver, if the solver does not converge (fast enough), gap > tol. 
Yet, gap is only defined in the for scope and not in the else scope. This causes an UnboundLocalError.
Similar issue with X when carrying out debiasing.
I did a quick fix by defining the two variables in the function body. Tell me if the fix could be enhanced.
> FIX variables not defined before assignment in BCD solver

- doc/conf.py
- doc/mri.rst
- mne/surface.py
- mne/tests/test_surface.py
- mne/transforms.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
- tutorials/clinical/10_ieeg_localize.py
- tutorials/clinical/20_seeg.py
@alexrockhill I also refactored the `set_printoptions` stuff to improve `Transform.__repr__` itself, but let me know if you had that context manager in there for another reason.
Todo:
Also the `20_seeg` had an incorrect coordinate frame slip in through `plot_alignment`:
Now it looks more reasonable:
> MRG, ENH: Use discrete method

- doc/changes/latest.inc
- mne/utils/docs.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/backends/renderer.py
Fixes #9597
Fixes #9595
So it looks like `focalpoint` was already an option as a keyword argument of `view` in `mne.viz.Brain.show_view`. I thought it would be helpful to pull all the arguments out of the keyword argument to be documented and explain clearly that if a string such as 'lateral' is passed, it will take precedence as that way seems clear to me. All the arguments could also all be keyword arguments of `view` as in `mne.viz.Brain.add_volume_labels(legend=...)`, that's an easy change, doesn't make a lot of sense to do it half and half. 
The other part that is changed is that if `hemi=None` then it is assigned to volume which is already in use as for volume data/as a catchall term. I think this makes it a bit cleaner and clearer what's going on with the views, to me at least. …
> [ENH, MRG] Update show_view API

- examples/connectivity/mne_inverse_coherence_epochs.py
- examples/inverse/covariance_whitening_dspm.py
- examples/time_frequency/source_power_spectrum_opm.py
- mne/viz/_brain/_brain.py
- tutorials/clinical/20_seeg.py
- tutorials/inverse/60_visualize_stc.py
- tutorials/simulation/80_dics.py
This is in reference to #9598.
Also if there were two hemispheres but the same view, it would do the depreciation warning so I fixed that.
> [BUG, MRG] Fix tutorial + example show_view to use correct keyword args

- doc/changes/latest.inc
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
- mne/datasets/utils.py
- tutorials/clinical/10_ieeg_localize.py
- tutorials/clinical/20_seeg.py
This clarifies and I think simplifies what's going on with the coordinate transforms for the SEEG case.
I think this will be really helpful for the GUI as they will hopefully be able to follow the same steps.
> [ENH] Clarify SEEG tutorial coordinate frames

- doc/changes/latest.inc
- mne/conftest.py
- mne/forward/tests/test_make_forward.py
- mne/source_space.py
- mne/tests/test_source_space.py
I did ~~a bad thing~~ two bad things in my code, and this would have made it clear sooner rather than later (when I got `np.nan` in my forward solution).
> MRG, BUG: Catch bad input to setup_volume_source_space

- doc/changes/latest.inc
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
Users tend to pass `reject` to `ICA.fit()` even when supplying an `Epochs` object. I'm trying to make it unmistakably clear that certain params only apply to `Raw`, and even emit warnings if "raw-only" params are passed together with `Epochs`. Also merged the docstrings for `start, stop` and `reject, flat`.
cc @drammock
> MRG: Make it clearer that certain ICA.fit() params only apply to Raw

- mne/beamformer/tests/test_dics.py
- mne/beamformer/tests/test_lcmv.py
1. Improve the LCMV orientation test to test only the orientations of the subset of vertices that were correctly localized.
2. Add DICS equivalents of the LCMV tests.
@britta-wstnr I think this might help with #9215
> MRG, MAINT: Improve orientation tests for LCMV and DICS

- .github/workflows/compat_minimal.yml
- doc/changes/latest.inc
- mne/datasets/utils.py
- mne/io/artemis123/tests/test_artemis123.py
- mne/io/egi/tests/test_egi.py
- mne/io/kit/kit.py
- mne/io/kit/tests/test_kit.py
- mne/tests/test_chpi.py
- mne/viz/misc.py
- mne/viz/tests/test_misc.py
- tools/github_actions_test.sh
@Kyung-minAn can you try this with your data? It fixes the problem for me with `mne.io.read_raw_fif('010409_Motor_task_coregist-export_tiny_1s.con')`
> MRG, BUG: Fix reading KIT data with fewer HPI coils

- doc/changes/latest.inc
- mne/gui/_file_traits.py
- mne/utils/docs.py
- mne/viz/_3d.py
I wanted to run `viz.plot_alignment()` and it crashed with an exception because there were a few topological defects (as is often the case with our data).
So now, I'm passing `on_defects='warn'` to the `read_bem_surfaces()` call inside `plot_alignment()`.
At first I made this parameter user-configurable, but then I thought, `plot_alignment()` is used when the user wants to see the data they have, so I felt it's not only okay, but expected to always pass `on_defects='warn'`.
Not sure how to test this, though – maybe it's okay as-is? I can confirm that this works for me.
> MRG: Make viz.plot_alignment() continue on topological defects; make coreg display a suitable head surface even if it has topological defects

- mne/transforms.py
I thought it would be helpful to have the allowed coordinate frames for a transform. I also updated to fstring syntax while I was there so that the PR would do a bit more maintenance but that can be reverted if it's not helpful.
> [MAINT, MRG] Better transform error that prints coordinate frames

- mne/_freesurfer.py
- mne/report.py
- mne/viz/misc.py
- tutorials/forward/30_forward.py
- tutorials/intro/70_report.py
This wasn't nearly as much of a pain as I thought. This simplifies things quite a bit and has the code from developing the GUI that can now be shared in `_freesurfer.py`.
Addresses comments in #9586.
Basically, instead of this very confusing which axis to flip and order of everything, the MRI is just reoriented to RAS and everything is follows from there.
Should be easy to use this code in the GUI, good idea @larsoner.
> [MAINT, MRG] Refactor BEM code

- doc/changes/latest.inc
- mne/_freesurfer.py
- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/surface.py
- mne/viz/_brain/tests/test_brain.py
> [ENH, MRG] Add `mne.viz.Brain.add_head` method to display head

- mne/bem.py
- mne/tests/test_bem.py
- mne/utils/docs.py
This is a follow-up to #9614, where @larsoner pointed out that the `on_defects` param should support an `'ignore'` value too. I've made the required adjustments, and also search-and-replaced `on_missing : str` -> `on_missing : 'raise' | 'warn' | 'ignore'` in the entire docdict.
> MRG, DOC: Document 'ignore' on_defects value; make allowed on_missing values explicit

- mne/io/nirx/nirx.py
- mne/io/nirx/tests/test_nirx.py
None
Use the name field to populate the `subject_info['his_id']` field. This then prints nicely in the html _repr_.
When starting a recording with a nirx devices the user is presented with a GUI screen and can enter age, gender, experiment type, and name. I always this name field to enter the participant ID, like P1, P2, etc. Can we use this field to populate the his_id variable in mne? The name is a free field text input, so I guess some labs could actually enter a participant name in here, but I think its more common to enter an ID. But this is probably lab variable, so close if it seems a bad idea. I just like the nice html printing of his_id.
> WIP: Use nirx name field to populate his_id

- doc/changes/latest.inc
- mne/channels/montage.py
> [BUG, MRG] fix coordinate frame in fNIRS bug

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/io/reference.py
- mne/io/tests/test_reference.py
- mne/utils/docs.py
ENH #8991 - set_eeg_reference to multiple channel types.
The function `_get_ch_type(inst, ch_type)` now accepts both a string or a list (or tuple) of channel types. Previously, the checked channel type would be returned as a string. Now, it returns a list of channel types, e.g.
```
_get_ch_type(inst, 'auto')               -> ['eeg']
_get_ch_type(inst, 'eeg')                -> ['eeg']
_get_ch_type(inst, ['eeg'])              -> ['eeg']
_get_ch_type(inst, ['eeg', 'seeg'])      -> ['eeg',  'seeg']
```
I have checked that the function` _get_ch_type` was not used outside `mne.io.reference.py` since I changed the output type.
Syntax is compatible with python 3.5+. 
```
import mne
sample_data_dir = Path(mne.datasets.sample.data_path())
fname = sample_data_dir / 'MEG' / …
```
> ENH #8991 - set_eeg_reference to multiple channel types

- doc/changes/latest.inc
- mne/viz/_3d.py
The goal of this PR is to add support to more than 3 secs in mne.viz.plot_sparse_source_estimates . 
To make a figure, I need to pass more than 3 source estimates to plot_sparse_source_estimates. I adapted the function to support more than 3 source estimates. The bottleneck is the limited number of line styles when plotting the activation intensity.
> ENH: Add support to more than 3 stcs in mne.viz.plot_sparse_source_estimates

- mne/io/brainvision/brainvision.py
While browsing our BrainVision code I noticed a line where we were not using a reasonable default.
Brainvision tests passed locally, let's see if this breaks anything else. Otherwise I think this can be merged.
> [MRG] Use default head size for scaling potential unit radius in BrainVision

- mne/decoding/csp.py
- mne/utils/docs.py
- mne/viz/topomap.py
Second attempt to properly solve issue #9611.
Per the discussion on issue #9611, the following tutorial could be updated with an example:
https://mne.tools/stable/auto_examples/visualization/evoked_topomap.html#sphx-glr-auto-examples-visualization-evoked-topomap-py
> Improve documentation for argument `mask` and fix documentation for argument `ch_type` for topographic plots.

- doc/conf.py
#9634 broke documentation builds because it tried to parse `setup.py` to get the required python version (setup.py is not distributed with the package, so it can only be used that way in git-clone-based installations).
This uses either `importlib` (py 3.8+) or `pkg_resources` (py3.7) instead.
> MAINT, CI: fix doc build

- mne/_freesurfer.py
Fixes #9639 
Prior to this fix, the _check_mri would proceed if it found the default mri (T1.mgz).  If the default filename happened to be in the calling directory, it would be returned from the function rather than performing the expected search of the freesurfer folder.
The fix does a check to confirm that if the file is found, it is not from the current path unless a relative or absolute path is provided.  The assumption being that having a relative or absolute path to the current directory was done with some intention rather than a coincidental default setting.
It is possible that this could return a warning rather than an error.
> FIX: Remove ambiguity in local filename check

- doc/conf.py
- examples/visualization/evoked_topomap.py
- mne/decoding/csp.py
- mne/utils/docs.py
- mne/viz/topomap.py
Followup of PR #9647.
Example added using the argument `mask` to [_Plotting topographic maps of evoked data_](https://mne.tools/stable/auto_examples/visualization/evoked_topomap.html#sphx-glr-auto-examples-visualization-evoked-topomap-py). The example was created by @drammock on #9611.
Replace the docstring for `topomap_mask` with the proposition by @drammock on #9647.
Removed `.. versionadded:: 0.24.0` for argument `ch_type` in `mne.viz.plot_topomap()` introduced by b6a36089a963a97380488845491fe38e8d3b610b
> Followup #9647 - Improve documentation of the mask argument for topographic maps.

- mne/datasets/sleep_physionet/_utils.py
- mne/datasets/sleep_physionet/age.py
- mne/datasets/sleep_physionet/temazepam.py
- mne/datasets/sleep_physionet/tests/test_physionet.py
Quick fix for #9654.
This PR updates the docstrings of `mne.datasets.sleep_physionet.age.fetch_data` and `mne.datasets.sleep_physionet._utils._data_path`  to reflect the actual environment variable name for the Sleep Physionet dataset. It also clarifies that the `update_path` argument is not currently used.
> [MRG] Modifying Sleep Physionet docstrings

- doc/changes/latest.inc
- mne/viz/evoked.py
- mne/viz/tests/test_evoked.py
as reported on the forum, `plot_compare_evokeds` is failing to draw confidence bands when only one condition is passed.
https://mne.discourse.group/t/plot-compare-evokeds-from-mne-evokedarray-confidence-intervals-and-ylim/3522/3
This adds a test that fails on main and passes on this PR.
> Fix plot compare evokeds

- requirements_doc.txt
- tutorials/epochs/50_epochs_to_data_frame.py
something about seaborn 0.11.2 is making `tutorials/epochs/50_epochs_to_data_frame.py` time out.  I can reproduce locally and it happens on circle.  Nothing in the release notes points to an obvious culprit, so until someone has time to track it down, let's just avoid that version.
> MAINT: more circle fixes

- doc/conf.py
- examples/inverse/psf_ctf_label_leakage.py
- mne/viz/circle.py
Fixes: https://github.com/mne-tools/mne-python/pull/9493
Keeps circular_layout function in mne-python and updates example to use mne-connectivity.
> Removes circular_layout from connectivity deprecation

- tutorials/preprocessing/15_handling_bad_channels.py
> Fix #9675 - typo in tutorial on how to handle bad channels.

- mne/coreg.py
- mne/tests/test_coreg.py
- tools/circleci_dependencies.sh
- Allows `mne.coreg.Coregistration.set_fid_match`
- Fixes bug when `Coregistration._icp_fid_match` == `'matched'` (now looks for attribute `self._lpa` instead of `self.lpa`, which doesn't exist)
> Add setter for fiducial alignment strategy to Coregistration

- doc/changes/latest.inc
- mne/channels/montage.py
- mne/channels/tests/test_montage.py
Helps with https://github.com/mne-tools/mne-bids/pull/859.
This makes it so that it's not quite as hacky to remove fiducials to have a different coordinate frame in `info`.
> [ENH, MRG] Add remove fiducials method

- .gitignore
- mne/coreg.py
- mne/tests/test_coreg.py
- tutorials/forward/25_automated_coreg.py
Closes #9673
@drammock I realized the problem with the snippet:
```py
raw_fname = os.path.join(data_root, subject, 'raw_fif', f'{subject}_raw.fif')
info = mne.io.read_info(raw_fname)
coreg = mne.coreg.Coregistration(
info, subject=surrogate, subjects_dir=subjects_dir)
coreg.set_scale_mode('3-axis')
coreg._icp_fid_match = 'matched'
coreg.fit_icp(n_iterations=30)
mne.viz.plot_alignment(
info, coreg.trans, subject=surrogate, subjects_dir=subjects_dir,
surfaces=dict(head=0.9), dig=True, mri_fiducials=True, meg=False)
```
is that the `plot_alignment` call is made with `subject=surrogate`, but it needs to be made with `subject=surrogate_scaled`, where you have made a scaled MRI surrogate using `mne.coreg.scale_mri` ~~and then `mne.coreg.scale_bem`~~ using the `coreg._scale` (which ~~we should …
> MRG, MAINT: More complete coreg test and doc

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/decoding/tests/test_ssd.py
- mne/epochs.py
- mne/io/constants.py
- mne/io/meas_info.py
- tutorials/io/30_reading_fnirs_data.py
There are small typos in:
- mne/decoding/tests/test_ssd.py
- mne/epochs.py
- mne/io/constants.py
- mne/io/meas_info.py
- tutorials/io/30_reading_fnirs_data.py
Fixes:
- Should read `frequency` rather than `freqquency`.
- Should read `discouraged` rather than `discoraged`.
- Should read `characteristic` rather than `charactersitic`.
- Should read `acquisition` rather than `acquition`.
- Should read `occurred` rather than `ccurred`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- mne/defaults.py
- mne/utils/docs.py
Fixes https://github.com/mne-tools/mne-python/issues/9709.
I must have had some variables wrong with the number of iterations I would guess when I was testing, but with just the increase to the iterations, the registration worked without changing it.
> [BUG, MRG] Fix CT-MR registration

- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- tutorials/forward/35_eeg_no_mri.py
This PR refactors `plot_alignment()` following https://github.com/mne-tools/mne-python/pull/9689#issuecomment-911385945. It  fixes https://github.com/mne-tools/mne-python/issues/9542. It fixes #9715.
It's still work in progress.
**ToDO**
The functions should all receive an instance of `_Renderer` as first parameter and return a list of `vtkActor`s as first output.
> MRG: Refactor plot_alignment

- mne/io/tests/test_raw.py
- mne/utils/tests/test_numerics.py
Bump tolerances for some tests as pointed out by @Aniket-Pradhan . This PR is to `main` but if they pass when @Aniket-Pradhan tests the `maint/0.23` version (https://github.com/larsoner/mne-python/tree/bugfix) on Fedora, I'll merge this, backport the fix, and cut another bugfix 0.23 release.
> BUG: Fix tolerances

- doc/conf.py
- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
- tutorials/inverse/40_mne_fixed_free.py
Closes #9720
Fixes regression introduced by #9688 (specifically on [this line](https://github.com/mne-tools/mne-python/pull/9688/files#diff-4e3d2d919a60057d535ba733330d5b8338aa491d6392b3d1c4a1a3de7122e17eR1930)), adds a test that would have caught it, touches an example that is broken on `main`, and fixes a persistent `linkcheck` false alarm.
> MRG, BUG: Fix hemi

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/io/curry/curry.py
Fixes #9380 
Improves #9381 
With #9381, 'ceo' files can be imported after renaming to 'cef'. This PR adds '.ceo' extension to event file extensions.
> FIX: Read events from ceo file.

- doc/changes/latest.inc
- mne/cov.py
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
- mne/rank.py
- mne/tests/test_cov.py
- mne/tests/test_rank.py
- mne/viz/tests/test_ica.py
Fix #9716.
The marked bad channels were excluded by default in method `._compute_pre_whitener()`. However, the channel picking, excluding the bad channels IF they were not explicitly provided, is already done in `.fit` when the attribute `self.info` is defined with an info instance based on the selection of picked channels. 
I added `exclude=[]` to every pick in the if/else statement in `._compute_pre_whitener()`. 
I removed `meg=False` (default argument) and renamed `this_picks` to `picks_` to shorten the lines.
> Fix ICA raising ValueError when bad channels are explicitly passed to .fit method.

- mne/utils/_logging.py
It looks like when the verbose decorator is added, the `__globals__` are lost because they aren't added as attributes to the newly made function. This is to fix that.
> [BUG, MRG] Keep function globals

- mne/io/bti/bti.py
- mne/io/edf/edf.py
- mne/io/tests/test_raw.py
- tools/circleci_download.sh
- tutorials/clinical/60_sleep.py
- tutorials/preprocessing/40_artifact_correction_ica.py
- converts "missing channel type" warning to `logger.info`
- fixes bug where all channel `loc` fields in the info pointed to the same object in memory (so that when setting montage, all channels get the coords of whichever channel came last)
- updates sleep tutorial to reflect new channel name behavior
- fix the logic so that if user specifies `stim_channel` or `misc` args to `read_raw_edf` they don't get spurious warnings about unidentified channel types
> fix EDF reader

- MANIFEST.in
- mne/report/__init__.py
- mne/report/report.py
- mne/report/tests/test_report.py
Let's try this from another angle. This PR just moves `mne/report.py`->`mne/report/report.py` along with its accompanying paths and infrastructure. Then once that's done @hoechenberger you can easily overwrite and the diff should be more manageable.
@hoechenberger an easy way once this is merged (if we go this route) would be to:
```
git fetch upstream
git checkout main
git reset --hard upstream/main
git checkout -b report2
git checkout report mne/report/report.py mne/data/html_templates.py mne/report/__init__.py ... # all files you changed
rm mne/html/jquery.js ... # all files you deleted
git reset  # if you want to be able to see "git diff"
git commit -am 'ENH: Rework report'
git push origin -u report2
```
It'll only take a minute to enumerate the files changed and files deleted, so not …
> MAINT: Move report code

- doc/changes/latest.inc
- examples/visualization/eeg_on_scalp.py
- mne/tests/test_cov.py
- mne/utils/__init__.py
- mne/utils/check.py
- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- mne/viz/_brain/tests/test_brain.py
- mne/viz/evoked.py
- mne/viz/tests/test_3d.py
- mne/viz/topo.py
- mne/viz/utils.py
- tutorials/preprocessing/70_fnirs_processing.py
Closes #9744
1. Fixes bug introduced in #9585 (cc @alexrockhill) where fNIRS and projected EEG sensors were not scaled properly based on `units`
2. Fixes a bug where we iterated over some views twice (in the case of `hemi='both'`) when we should have just done it once -- this is fixed by iterating over `'vol'` as the hemi
3. Adds support for custom `cortex` color mappings in `mne.viz.Brain`, which is something I've wanted for a while and was necessary to restore this image from [stable](https://mne.tools/stable/auto_tutorials/preprocessing/70_fnirs_processing.html#view-location-of-sensors-over-brain-surface) while still using `mne.viz.Brain` instead of `plot_alignment`:
4. Streamlines the iteration over views by calling `.subplot` inside `_iter_views` rather than doing it manually each …
> MRG, ENH: Add cortex, fix sensors

- doc/changes/latest.inc
- doc/conf.py
- doc/mri.rst
- mne/datasets/utils.py
- mne/gui/__init__.py
- mne/gui/_ieeg_locate_gui.py
- mne/gui/tests/test_ieeg_locate_gui.py
- mne/surface.py
- mne/tests/test_surface.py
- mne/utils/_testing.py
- mne/utils/docs.py
- mne/viz/misc.py
- tutorials/clinical/10_ieeg_localize.py
Add a GUI that allows users to find their intracranial electrode montage from a CT, an MRI and the Freesurfer recon-all from it, and an `info` object that supplies the names to be found and is return with a modified montage.
Closes #9559
Very rough version, no review yet.
> [ENH, MRG] Add intracranial electrode localization GUI

- doc/changes/latest.inc
- mne/epochs.py
- mne/tests/test_epochs.py
I hit a corner case today where `epochs.equalize_event_counts()` was failing because the smallest event_id had only one epoch in it, which caused `interp1d` to error out (we already handle the edge case where it has zero).  This fixes that.
> Fix equalize event counts

- mne/export/_edf.py
- tools/azure_dependencies.sh
- tools/github_actions_dependencies.sh
Use a context manager for closing EDFlib's class -- at some point we should make an upstream PR to add `__enter__` and `__exit__` to their class. I started out by making a private function to minimize the diff, but it ended up needing so many args/kwargs, it seemed better to just indent the whole thing. So this PR does that, and other than removing all `.close()`s (which are no longer needed because the context manager should take care of it), it removes `pooch` from explicit pip installation because it's in `requirements_testing.txt` already.
> MRG, ENH: Use context manager, cleaner deps

- doc/changes/latest.inc
- mne/epochs.py
- mne/tests/test_epochs.py
Fixes #9765 
Fix a bug in concatenate which could create epochs that are not ordered chronologically.
> FIX: chronological order of concatenated epochs

- doc/changes/latest.inc
- mne/io/snirf/_snirf.py
Fixes https://github.com/mne-tools/mne-nirs/issues/393
The SNIRF specification has an optional 4th column in the 3D positions for landmarks. Previous vendor software did not use this column, and so we just took the whole array. But now the NIRx vendor appears (yet to be confirmed) that they are using this column. As such we need to address the first 3 array values not `:`.
I have a file from a user that now works with this fix. But it’s not appropriate to use as test data. 
I have emailed NIRx to ask for a test file as I dont have access to one of these machines to provide test data. But if the change doesn't break old test data, and the change makes sense relative to the specification, then I suggest we can merge without test data, and I will add it when I get my hands on a reasonable …
> MRG: FIX: Specify exact array indicies for 3D landmark positions

- doc/changes/latest.inc
- mne/epochs.py
- mne/tests/test_epochs.py
Tiny improvement fixing #9747.
I added a similar `id` argument for `make_fixed_length_epochs` as the one of `make_fixed_length_events`.
**Question:** to (more or less) match the argument order of `make_fixed_length_events`, I've placed `id` in second. 
Do you mind this type of change where user code with positional arguments might break, or do you always prefer to add new arguments to the end?
I'll change the order if needed.
> Fix 9747 - Add ID arg to make_fixed_length_epochs to change the default value 1.

- doc/changes/latest.inc
- mne/io/brainvision/brainvision.py
- mne/io/brainvision/tests/test_brainvision.py
This fixes an issue reported on the forum:
https://mne.discourse.group/t/brainvision-raw-get-data-could-not-convert-string-to-float/3730
> MRG: Fix read_raw_brainvision() handling of comma-separated data files

- doc/changes/latest.inc
- mne/datasets/utils.py
- mne/viz/_3d.py
- mne/viz/tests/test_3d.py
The "normal" coil_def for OPMs is a line (1D), which makes Qhull angry, and thus breaks plot_alignment. The "accurate" geometry is a cube, so it works better.
An alternative is to detect dimension deficiency and work around it, but even that's a pain as we'd have to deal with 2D geometry (probably `Delaunay`) and 1D geometry (probably convert to a skinny tube). However, it's easy enough just to try to use accurate if available first -- it will be in all built-in cases we have in our own `coil_def.dat`, but we keep the fallback for users supplying their own `coil_def.dat`. If we hit the really rare corner case of a custom `coil_def.dat` plus dimension-deficient geometry we can fix it later, but hopefully YAGNI
I also added a `fetch_phantom` to `_download_all_example_data` that I forgot to …
> MRG, BUG: Fix plot_alignment for OPMs

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/utils/config.py
Addresses comment in #9798 .
Adds pooch info to system report.
Note: on local machine, `mne sys_info` does not display the additional pooch info, however `python -c "import mne; mne.sys_info()` does display it. It's unclear to me if this is the desired behavior.
> [ENH] Add pooch sys info

- requirements_testing_extra.txt
See https://github.com/jupyter/nbformat/issues/232
> MAINT: Pin jsonschema to < 4 to avoid DeprecationWarning

- mne/coreg.py
- mne/gui/_coreg.py
- mne/gui/tests/test_coreg_gui.py
- mne/io/snirf/_snirf.py
- mne/tests/test_coreg.py
- mne/viz/_3d.py
Handle two issues I raised in #8833,
1) support for `info['dig']` missing some types of dig points
2) support loading from instances only containing `dig` objects.
~~still needs `latest.inc`~~ hasn't been released so no need.
> Coreg fixes

- doc/changes/latest.inc
- mne/surface.py
`get_montage_volume_labels` can enter an infinite recursion because the voxel neighbors on every step are not removed, causing it to go from one voxel to the neighbor and back. This fixes that.
> [BUG, MRG] Fix infinite recursion bug in `get_montage_volume_labels`

- azure-pipelines.yml
I think we should make OpenGL optional, and only try to use it based on a config var. But in the meantime, this will fix our PG tests after https://github.com/mne-tools/mne-qt-browser/pull/12 / 0.1.5
> MRG, FIX: Fix PG tests

- requirements_doc.txt
- tutorials/epochs/60_make_fixed_length_epochs.py
`main` failed [last night](https://app.circleci.com/pipelines/github/mne-tools/mne-python/11252/workflows/5d9bd225-bb87-4141-876d-b91e8b56d7fd/jobs/37753) because of deps, https://github.com/mne-tools/mne-connectivity/pull/52 fixes it so use that in our doc builds
> MAINT: Bump mne-connectivity

- doc/_templates/homepage.html
not sure when this crept in but due to the recent release now it's in both stable and dev sites, so I'm marking as backport candidate.
> fix missing connectivity image on homepage tile

- mne/tests/test_surface.py
Fixes https://github.com/mne-tools/mne-python/pull/9940 leftovers.
This is much more thorough and has a more realistic use-case for the algorithm (i.e. previously cube contours of integer type were used but now the intensities are more reasonably normally distributed (the problem with the cube contours is that the corners were the same intensity as the sides when they should be farther from the origin of the intensity) and are continuous floating point numbers).
> [MAINT, MRG] Better test for `mne.surface._voxel_neighbors`

- doc/changes/latest.inc
- mne/gui/_ieeg_locate_gui.py
- mne/gui/tests/test_ieeg_locate_gui.py
This adds the capability to show in yellow which voxel is a local maxima (see below). This functionality is very useful for bridged electrodes where otherwise, the intensity values would have to be looked at carefully and/or the color scale changed (which has the added detriment of making it hard to see the context outside of the electrode) in order to determine the center of intensity of the electrode contact with assurance. This coordinates nicely with our method of warping which uses voxels monotonically decreasing from the local maximum (at least until Dipy finishes their PR https://github.com/dipy/dipy/pull/2369 to make it so that points can be warped). Lastly, the maximum computation is done efficiently only whenever the radius changes and the local maxima showing is turned on (it …
> [ENH, MRG] Add local maxima button to ieeg locate GUI

- doc/changes/latest.inc
- mne/report/report.py
We shouldn't force `bbox_inches='tight'`. The effect is generally small, and if it's big, then people should fix their figures not to waste space. Here's an example of a bad effect (jumping around) on `main`:
And it's fixed on this PR (and was fine before the big refactor):
> MRG, BUG: Fix regression with report due to bbox_inches

- azure-pipelines.yml
- environment.yml
Now that there is a mne-qt-browser conda-forge package (and ipyvtklink has been up for a while) we shouldn't need `pip`
> MRG, MAINT: Use all conda-forge

- mne/gui/__init__.py
- mne/gui/_coreg.py
- mne/utils/docs.py
- mne/viz/_3d.py
This adds an `interaction` kwarg to `CoregistrationUI`. `mne.gui.coregistration()` in `main` simply ignores its `interaction` parameter and doesn't pass it to `CoregistrationUI`. This PR fixes this behavior.
Following a recent conversation with @larsoner, this also changes the default interaction style to `'terrain'`.
In the `'terrain'` interaction mode, zooming by scrolling up/down with the mouse doesn't work for me on macOS, so this needs to be fixed.
```python
import mne
mne.gui.coregistration(interaction='trackball')  # behaves like `main`
```
https://user-images.githubusercontent.com/2046265/140620892-741b4d4a-72f8-4102-a7e2-9e8f7fcc5bc2.mov
```python
import mne
mne.gui.coregistration(interaction='terrain')  # new default
``` …
> MRG: Add "interaction" param to CoregistrationUI

- mne/externals/pymatreader/pymatreader.py
- mne/externals/pymatreader/utils.py
- mne/io/eeglab/eeglab.py
- mne/minimum_norm/tests/test_inverse.py
- mne/viz/_3d.py
- mne/viz/topomap.py
- tools/github_actions_dependencies.sh
should hopefully fix the py3.9 CI error that popped up in #9972
> import fix for scipy 1.8 pre

- doc/conf.py
Related to https://github.com/dipy/dipy/issues/2483. This will keep the documentation link to `Dipy` from going out of date every release.
> [MAINT, MRG] Fix Dipy link

- doc/changes/latest.inc
- mne/epochs.py
- mne/export/_eeglab.py
- mne/export/_egimff.py
- mne/export/_export.py
- mne/export/tests/test_export.py
- mne/io/base.py
I have to do a couple of I/O roundtrips to EEGLAB, and I could use an `overwrite` argument, set to False by default, for the export methods as in `inst.save` to prevent unintentional exports.
For `inst.save`, when overwrite was added, it was first initialized to True for one version and then changed to False.
> This defaults to True in 0.18 but will change to False in 0.19.
> New in version 0.18.
If you agree with the addition of this argument, do you want to follow the same path?
> MRG: Add argument overwrite to export for raws and epochs to match save.

- mne/cuda.py
- mne/filter.py
- mne/io/base.py
- mne/utils/docs.py
Fix #9983.
I added a new entry to the docdict: `pad` replacing the previous `pad-fir` for resampling methods.
The docdict entry `pad-fir` is now created by appending to the entry `pad`.
> Fix #9983 - Typo in docstring of pad for resampling methods.

- mne/utils/check.py
Get rid of `LooseVersion` usage here.
Tiny step toward resolving #9894
> MRG: Make check_version() use _compare_version() internally

- tutorials/clinical/10_ieeg_localize.py
Just makes the capitalization match.
> [DOC, MRG] Fix ieeg localization tutorial capitalization to match other tutorials

- doc/changes/latest.inc
- mne/io/eeglab/eeglab.py
- mne/io/eeglab/tests/test_eeglab.py
Following #9989, a quick proposition to read channel types with EEGLAB reader.
In the reader, the data is read in a variable named `eeg` since EEGLAB is mostly focused on EEG datasets. However, in practice it does support more data types; and I could rename left and right this variable to e.g. `data` to make the code a bit more general if you want.
> MRG: Add support to retrieve channel type from ['chanlocs']['type'] with EEGLAB reader

- doc/changes/latest.inc
- mne/tests/test_morph.py
- mne/tests/test_transforms.py
- mne/transforms.py
- tutorials/clinical/10_ieeg_localize.py
The affine registration of the CT with the MR wasn't working optimally, alignments were slightly off, thanks for reporting @leosunpsy.
So I went back and looked and it looks like the `Dipy` method was to use the pre-alignment affines as we had at one point. I'm not sure why that wasn't working but it seems to work just fine now.
> [BUG, MRG] Revisit affine registration

- requirements_doc.txt
With https://github.com/pydata/pydata-sphinx-theme/issues/508 and the corresponding release in theory we shouldn't need the pin
> CI: Unpin Sphinx

- .github/workflows/codespell_and_flake.yml
- .github/workflows/compat_minimal.yml
- .github/workflows/compat_old.yml
- .github/workflows/linux_conda.yml
- .github/workflows/linux_pip.yml
- .github/workflows/macos_conda.yml
This just adjusts our auto-cancellation policy to include the event.ref so that pushes to `main` and `maint/0.24` don't cancel each other.
> MRG, CI: Better cancellation policy

- doc/changes/latest.inc
- mne/epochs.py
- mne/export/_egimff.py
- mne/export/_export.py
- mne/export/tests/test_export.py
- mne/io/base.py
- mne/utils/docs.py
I added a warning when exporting with unapplied projectors to all 4 export functions:
- mne.export.export_raw
- mne.export.export_epochs
- mne.export.export_evokeds
- mne.export.export_evokeds_mff
I added this warning in their docstrings:
```
.. warning::
Export does not apply projector. Unapplied projectors will be lost.
Consider using :meth:`mne.io.Raw.apply_proj` before exporting.
```
Test for warning when exporting evoked with unapplied proj is missing because I didn't have any good idea on how to add a projector to the EGI evoked instance loaded.
> MRG: Issue warning when exporting with unapplied projectors and improve docstring

- doc/changes/latest.inc
- mne/report/report.py
When calling `mne.Report.save()`, we don't want to overwrite the existing `report.fname` attribute, as it breaks this pattern (which I happen to use a lot):
```python
with open_report('report.h5') as report:
report.add_figure(fig)
report.save('report.html')  # save HTML version
```
I like to keep both an `.h5` and `.html` version of the report. Before this PR, saving to HTML will overwrite `report.fname` and hence at the end of the context it gets saved as HTML again, instead of the HDF5 file that was used when opening the report.
> MRG: Don't overwrite Report.fname upon saving

- doc/conf.py
- doc/glossary.rst
- mne/gui/__init__.py
- mne/report/report.py
- mne/surface.py
- mne/utils/docs.py
came up in https://github.com/mne-tools/mne-bids/pull/910#pullrequestreview-805508282
- Add `path-like` and `array-like` to the glossary
- Replace occurrences of `str | pathlib.Path` with `path-like`
- Replace occurences of `collection` with array-like
- <strike>Fix alias for Matplotlib's `collections` (must be plural, was singular)</strike >
> MRG: API doc & glossary improvements

- doc/changes/latest.inc
- mne/utils/config.py
- mne/utils/docs.py
- mne/viz/_figure.py
- mne/viz/raw.py
- mne/viz/tests/test_raw.py
- mne/viz/utils.py
This renames mne-qt-browser related config-variables for consistency:
MNE_BROWSE_BACKEND -> MNE_BROWSER_BACKEND
MNE_BROWSE_USE_OPENGL -> MNE_BROWSER_USE_OPENGL
~~MNE_BROWSE_RAW_SIZE -> MNE_BROWSER_SIZE~~
> MNT: mne-qt-browser config and doc

- doc/changes/latest.inc
- mne/preprocessing/ica.py
- mne/preprocessing/tests/test_ica.py
Adding a check + overwrite argument to ``ICA.save()`` to avoid overwriting existing ICAs.
> Add argument overwrite to ICA.save()

- doc/changes/latest.inc
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
I have some workflows the store source space label time courses in `Raw` instances.
The current renaming scheme (https://github.com/mne-tools/mne-python/blob/main/mne/io/meas_info.py#L110) works for most atlases but fails for `aparc_sub`, depending on the ordering of duplicated channels.
<details>
<summary>Minimal working example</summary>
```
from mne import create_info
from mne.io import write_info
ch_names = ['supramarginal_1-lh',
'supramarginal_1-rh',
'supramarginal_10-lh',
'supramarginal_2-lh',
'supramarginal_2-rh',
'supramarginal_3-lh',
'supramarginal_3-rh',
'supramarginal_4-lh',
'supramarginal_4-rh',
'supramarginal_5-lh',
'supramarginal_5-rh',
'supramarginal_6-lh',
'supramarginal_6-rh',
'supramarginal_7-lh',
'supramarginal_7-rh',
'supramarginal_8-lh',
'supramarginal_8-rh', …
```
> Robust fif channel renaming of long channels names

- doc/install/contributing.rst
- mne/conftest.py
- mne/datasets/sleep_physionet/_utils.py
- mne/viz/evoked.py
- mne/viz/misc.py
A few fixes:
1. We errantly started to override the `fname` argument in [#9742](https://github.com/mne-tools/mne-python/pull/9742/files#diff-f5e016349dc0d44312eaaff21e34539015b5355b621f200cb99910a56dcb2820R95), which manifested as `SC-subjects.xls` and `ST-subjects.xls` appearing in whatever directory the tests were being run from, which was annoying because `git status` would show them as untracked files.
2. Fixes some path problems on Sphinx 5 using `:doc:`, matplotlib ones fixed by prepending `matplotlib:` and the MNE ones (which should probably work but don't, unclear what the problem is) just worked around using `:ref:` which points to the same place effectively.
3. Fixes our usage of autouse figures. I don't think the `plt.close('all')` one was actually being used until now, so this …
> MRG, MAINT: Update testing for datasets

- mne/source_estimate.py
Fixes #9993
Rectified mistake in the description of the 'sum' option in stc_near_sensors
changed "electrode" to "sensor"
> DOC: stc_near_sensors

- mne/io/kit/kit.py
- mne/io/kit/tests/test_kit.py
The issue was raised on the discourse forum [here](https://mne.discourse.group/t/unable-to-load-data-with-mne-io-read-raw-kit/3983/2). This line is not covered by test cases.
As far as I can tell with this simple regex match `warn\(['"].*['"],.*\)`, it's the only place where this syntax for `logger.warning` was used.
> MRG: Fix warning in KIT reader

- doc/changes/latest.inc
- mne/surface.py
- mne/tests/test_surface.py
In using this code on my own data, I realized that 100 voxels is a very small amount in a 256 x 256 x 256 image and you are likely to want at least a few more for context when using `mne.get_montage_volume_labels`. I guess this could be changed to a parameter but I think it's better not to have to deal with. If it were done away with altogether though it could cause runtime issues.
> [MRG, MAINT] Fix constant

- doc/conf.py
- mne/decoding/transformer.py
- mne/time_frequency/multitaper.py
- mne/time_frequency/psd.py
- mne/utils/docs.py
- mne/viz/epochs.py
- mne/viz/topomap.py
follow-up to #10030, I realized too late that all those docstrings were identical.
@guiomar FYI, this PR does what I would have suggested you do in #10030 if I had thought of it before merging:
1. make `nitime` into a link that goes to their documentation; this is possible because both packages use `sphinx` to build their docs so we can use intersphinx to cross-link to their module
2. since all 5 instances of the `normalization` docstring entry were identical, I've abstracted them out into our `docdict` so that in future we only need to change it in one place.
> add nitime to intersphinx; deduplicate some docstrings

- tutorials/preprocessing/70_fnirs_processing.py
In #9843 I initially changed the default value of the beer lambert law, but then we had to leave it the same for a depreciation cycle. Somehow this change snuck through, this causes all the plots to have no data in the tutorial as reported at https://mne.discourse.group/t/fnirs-tutorial-does-not-display-visualization
in the coming weeks I will complete the transition to the new default. Can we back port this PR?
> Revert change to fNIRS tutorial

- mne/datasets/__init__.py
Is there any reason why only those 2 datasets `refmeg_noise` and `fnirs_motor` were left out of `__all__`?
> add refmeg_noise and fnirs_motor to __all__

- mne/preprocessing/ica.py
see https://github.com/mne-tools/mne-python/blob/main/mne/preprocessing/ica.py#L720
> decim is actually used for epochs

- doc/changes/latest.inc
- mne/utils/config.py
- requirements.txt
It appears that #9886 accidentally removed `pooch` from the `sys_info` output.
I also specify a lower version requirement for `pooch` (1.5+) after a user [reported](https://mne.discourse.group/t/issue-in-loading-data-in-overview-of-meg-eeg-with-mne-python/4042/) an issue with an outdated version on the forum.
> Add back pooch to sys_info; pin pooch min version

- doc/changes/latest.inc
- mne/beamformer/_dics.py
- mne/channels/channels.py
- mne/io/meas_info.py
- mne/io/tests/test_meas_info.py
Follow up on the discussion in #10035
> MRG: Deprecrate pick channels in info

- mne/epochs.py
- mne/utils/docs.py
In https://github.com/mne-tools/mne-realtime/pull/35 I'm discovering that our use of
```
:class:`Evoked`
```
rather than the fully qualified
```
:class:`mne.Evoked`
```
[is problematic](https://app.circleci.com/pipelines/github/mne-tools/mne-realtime/132/workflows/e419408e-f4f8-41d5-a6ad-a885b8ad600b/jobs/149) for subclasses like RtEpochs. This changes our docstrings to be more DRY but more importantly uses
```
:class:`~mne.Evoked`
```
which will render the same way as `main` but make subclasses in other modules like `mne-realtime` work properly.
Will merge once I verify by eye that things look and work the same so that https://github.com/mne-tools/mne-realtime/pull/35 can get in and we can cut a release of mne-realtime.
> MRG, MAINT: Make subclassing easier

- doc/changes/latest.inc
- mne/epochs.py
- mne/evoked.py
Closes #10042 .
Reduce the size and load of `__repr__` output/calculations. This function is called frequently in debuggers, IDEs and interactive python consoles to describe the currently available variables / objects. When handling epochs with many events, the current implementation leads to sluggish IDE performance / printing an object to console takes very long. You can still obtain the old behaviour by explicitly calling `__repr__(limit_events=None)`.
I also changed evoked to not show comments longer than 1000 chars. Evoked does not do excessive computations in `__repr__`, as such, the performance is not impacted. But the resulting output is still extremely long. You can still obtain the old behaviour by explicitly calling `__repr__(limit_comment=None)`. Additionally the whole comment …
> Limit output of __repr__ of mne.BaseEpochs and mne.Evoked to improve performance

- mne/annotations.py
- mne/io/base.py
- mne/io/fiff/raw.py
Closes #10037.
The changes add documentation about the specific behaviour of ``BAD_ACQ_SIP`` annotation in reading/writing file:
- when saving to FIF file, samples annotated ``BAD_ACQ_SKIP`` are not stored and will be loaded as 0s when reading back
- the first N samples annotated ``BAD_ACQ_SKIP`` are skipped when reading FIF file
> DOC: add bad_acq_skip annotation behaviour

- mne/utils/docs.py
A small docstring change to mention that the samples corresponding to `tmin` and `tmax` are included in the Epochs.
I got a little surprise today when 4 seconds epochs sampled at 512 Hz had 4096 samples.
Or maybe I got it all wrong :man_shrugging:
> MRG: Mention that tmin/tmax are included in the epochs

- doc/changes/latest.inc
- mne/export/tests/test_export.py
- mne/io/edf/edf.py
- mne/io/edf/tests/test_edf.py
- mne/io/nihon/tests/test_nihon.py
Fixes #10053. The current implementation was broken, because it did not check if a prefix (anything before a space) was valid. This is problematic for channel names containing spaces.
In addition, I've added a new `infer_types` parameter, which by default is `False`. I think this is the better choice, because in general EDF does not impose any structure on channel names.
To do:
> Fix EDF channel type detection

- mne/viz/_figure.py
- mne/viz/backends/_pyvista.py
- mne/viz/backends/_utils.py
- mne/viz/utils.py
- requirements.txt
- tools/github_actions_dependencies.sh
This fixes mne-tools/mne-qt-browser#23.
This centralizes the redundant initialization of a QApplication currently needed for both the pyvista and the pyqtgraph-backend and fixes the missing app-name for macOS.
For some unidentified reason, `PyQtGraphBrowser.show()` fails with a SegmentationFault if QApplication is not created with `mkQApp`. I tried around a lot but since I couldn't identify the reason, I left `mkQApp` in here for the pyqtgraph case.
> MNT: Centralize initialization of Qt-Application

- doc/changes/latest.inc
- doc/conf.py
- doc/glossary.rst
- mne/annotations.py
- mne/epochs.py
- mne/event.py
- mne/io/base.py
- mne/io/kit/kit.py
- mne/simulation/source.py
- mne/utils/docs.py
- mne/viz/misc.py
After some _stupid_ trouble to create fix length epochs by passing a numpy array of events in #10055 I think the docstring for `events : array of int, shape (n_events, 3)` could be improved a bit and made more consistent across the doc. 
I do realize now that users are not supposed to create this array manually, as I did, but instead use one of the MNE functions. Still, some details on what this array contains would be beneficial. For now, the only function with details is [`mne.find_events`](https://mne.tools/stable/generated/mne.find_events.html?highlight=find_events#mne.find_events).
I started generalizing the docstring to all entries of events I could think of. If you agree with the idea and the docstring, I'll finish this PR a bit later.
> MRG: Docstring improvement adding more details to what the events array is.

- .circleci/config.yml
- doc/conf.py
- tools/circleci_dependencies.sh
- tutorials/clinical/20_seeg.py
Now that we are paying for CircleCI builds, it would be nice to cut down our usage a bit. One way to do this is to only build `dev` and `maint/0.24` nightly, and only if they have changed. So this PR:
1. Makes it so that each build creates a `_build/html/_version.txt` that contains the SHA of the commit.
2. It quits on non-PR builds if it sees that it's not a scheduled build, unless there is a `[circle deploy]` in the commit line (hopefully we will only rarely need this, but it could come in handy around release time)
3. If it is a scheduled build, compares https://mne.tools/stable/_version.txt or https://mne.tools/dev/_version.txt (I put dummy ones in there manually for now) to the current commit number, and quits if the version numbers match.
4. Gets rid of "interactive_test", we don't …
> MAINT: Only do nightly full builds

- mne/annotations.py
This is a minor PR to fix annoying whitespace.
I noticed this because I often track annotation files in git, and a pre-commit hook changed my files to auto-remove trailing whitespace.
reading annotation txt files should be unaffected, because that whitespace is stripped anyhow: https://github.com/mne-tools/mne-python/blob/b97da4357f9ffb584eef5949c958187b3a7cc566/mne/annotations.py#L997
> fix: do not write trailing whitespace in annotations.txt

- doc/changes/latest.inc
- mne/stats/cluster_level.py
- mne/stats/tests/test_cluster_level.py
Please see the added test case for a 2D NumPy array. This fails on `main` with:
```python
-> 1205     return _permutation_cluster_test(
1206         X=[X], threshold=threshold, n_permutations=n_permutations, tail=tail,
1207         stat_fun=stat_fun, adjacency=adjacency, n_jobs=n_jobs, seed=seed,
~/Development/mne-python/mne/stats/cluster_level.py in _permutation_cluster_test(X, threshold, n_permutations, tail, stat_fun, adjacency, n_jobs, seed, max_step, exclude, step_down_p, t_power, out_type, check_disjoint, buffer_size)
929         # ndimage outputs slices or boolean masks by default
930         if out_type == 'indices':
--> 931             clusters = _cluster_mask_to_indices(clusters, t_obs.shape)
932 
933     # convert our seed to orders …
```
> MRG: Fix permutation_cluster_1samp_test for 2D data when using TFCE

- doc/changes/latest.inc
- mne/morph.py
- mne/utils/__init__.py
- mne/utils/numerics.py
- mne/utils/tests/test_numerics.py
For a long time I've wished that our `smoothing_steps` operations could be faster. Working on #10071 made me even more motiviated to do it. I found a way to do it by implementing a custom `lru_cache` mechanism that operates at the level of smoothing matrices.
`@functools.lru_cache` requires that all arguments are hashable. In theory rather than using our own LRU implementation we could maybe make a `_hashable_csr_matrix` like we have `_hashable_ndarray` and pass these lightweight wrappers to standard `@functools.lru_cache()`-decorated functions, but there is no `csr_mat.view(...)` equivalent of [ndarray.view](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.view.html), and I can't think of a clean way to override the `__hash__` and `__eq__` methods of `csr_matrix` like we do …
> MRG, ENH: Implement lru_cache for smooth_mat

- doc/changes/latest.inc
- mne/report/templates/header.html
Fixes #10046
We still have an overlap between the dropdown and the "status bar" at the bottom, but this can be addressed in a followup PR.
> MRG: Add scrollbar to report tag dropdown menu

- mne/decoding/csp.py
- mne/decoding/mixin.py
> MRG: Make y a required parameter in CSP.fit_transform()

- mne/preprocessing/ica.py
That's how I understand it (and the code looks like it in the source and when running it) ... so I thought I'd add this to the docstring to clear things up.
The relevant things happen here:
https://github.com/mne-tools/mne-python/blob/c3ff05c05c7bfcf765249f27a517803f27f48b4e/mne/preprocessing/ica.py#L1796-L1801
where `_check_exclude` does this (either union of `ica.exclude` and `exclude`, or just `ica.exclude`, if `exclude` is "n/a"):
https://github.com/mne-tools/mne-python/blob/c3ff05c05c7bfcf765249f27a517803f27f48b4e/mne/preprocessing/ica.py#L1726-L1731
`include` is handled a few lines below in `_pick_sources`:
https://github.com/mne-tools/mne-python/blob/c3ff05c05c7bfcf765249f27a517803f27f48b4e/mne/preprocessing/ica.py#L1820-L1824
i.e., all are `included` if `None` ... else the …
> doc: clarify ica.apply include and exclude params

- mne/viz/evoked.py
- mne/viz/topo.py
closes #9923 
Here are some figures to show how this changes behavior. I've made the figure facecolor gray to more clearly show its edges (for those of you who don't use GitHub dark mode 😎):
**main:**
**this PR:**
**main:**
**this PR:**
**main:**
**this PR:**
**main:**
**this PR:**
> fix plot_compare_evokeds topo legend axes placement

- doc/changes/latest.inc
- mne/viz/_mpl_figure.py
> fix trace offsets in butterfly mode

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/preprocessing/artifact_detection.py
Enhancement #10088.
The function `_annotations_from_mask` in [mne/preprocessing/artifact_detection.py](mne/preprocessing/artifact_detection.py)
is rewritten to avoid the use of any for loop, which could be very time-consuming
when the number of components is large.
This new implementation does not require any additional package.
> Fast annotation from mask

- doc/conf.py
- mne/conftest.py
- mne/cov.py
- mne/datasets/_fetch.py
- mne/datasets/sleep_physionet/_utils.py
- mne/externals/tqdm/__init__.py
- mne/io/eeglab/tests/test_eeglab.py
- mne/surface.py
- mne/tests/test_epochs.py
- mne/time_frequency/tests/test_multitaper.py
- mne/utils/_testing.py
- mne/utils/tests/test_linalg.py
- mne/viz/_brain/_scraper.py
- mne/viz/backends/_notebook.py
- mne/viz/backends/_pyvista.py
- mne/viz/misc.py
- mne/viz/utils.py
- setup.cfg
> MRG: Use fixes._compare_version for version checks everywhere

- doc/changes/latest.inc
- mne/io/base.py
- mne/utils/check.py
> Remove repeated _check_fname() calls when saving Raw

- doc/conf.py
- mne/cov.py
- mne/datasets/sleep_physionet/_utils.py
- mne/io/eeglab/tests/test_eeglab.py
- mne/surface.py
- mne/tests/test_epochs.py
- mne/time_frequency/tests/test_multitaper.py
- mne/utils/_testing.py
- mne/viz/misc.py
- mne/viz/utils.py
By looking at our [min version list](https://github.com/mne-tools/mne-python) and now (thanks to @hoechenberger 
in #10091) just being able to do `git grep _compare_version` I was able to remove a number of comparisons that are no longer necessary based on our min required versions.
> MRG, MAINT: Remove unnecessary version checks

- doc/changes/latest.inc
- doc/changes/names.inc
- mne/io/bti/bti.py
- mne/io/bti/tests/test_bti.py
This fixes #10092 at least partially. In my original issue, ``read_raw_bti()``'s ``eog_ch`` parameter was ignored. This change should allow EOG channels to now be selected with it.
> FIX: Honor read_raw_bti's eog_ch parameter

- mne/viz/_mpl_figure.py
- mne/viz/tests/test_epochs.py
- tutorials/epochs/20_visualize_epochs.py
fixes bug introduced in #10087
> Fix butterfly index

- doc/changes/latest.inc
- mne/io/base.py
- mne/io/fiff/tests/test_raw_fiff.py
I was just using this function and thought that it would be good to have it log about the updates.
I also turned a `warnings.warn` into a `logger.warn` ... however that meant I had to remove a `    with pytest.warns(RuntimeWarning, match='1 bad channel'):` from the test. Is there a way to keep this `with pytest.warns` with the `logger.info`?
Also, should `load_bad_channels` maybe return `self` (i.e., the raw instance)? Similar to `set_annotations` and many other functions?
> [MRG] ENH: add verbose param to load_bad_channels, log info

- server_environment.yml
I was giving a shot to this on one of our servers, and the pin is not needed anymore. https://github.com/jupyter/nbformat/issues/206 has been fixed.
> Remove pin on server environment

- mne/morph.py
- mne/tests/test_morph.py
After #10077 we can have this happen when `smoothing_steps=0` (meaning, "do no smoothing"):
```
mne/morph.py:248: in compute_source_morph
morph_mat = _compute_morph_matrix(
mne/morph.py:1040: in _compute_morph_matrix
morpher.append(_hemi_morph(
mne/morph.py:1077: in _hemi_morph
mm, n_missing, n_iter = _surf_upsampling_mat(vertices_from, e, smooth)
E   ValueError: too many values to unpack (expected 3)
```
This PR fixes the shortcut definition so that this doesn't happen.
> BUG: Fix bug with morph speedup

- doc/changes/latest.inc
- mne/io/nirx/tests/test_nirx.py
- mne/preprocessing/annotate_nan.py
- mne/preprocessing/artifact_detection.py
- mne/preprocessing/flat.py
- mne/preprocessing/tests/test_artifact_detection.py
- mne/preprocessing/tests/test_flat.py
closes #10060
Now all `annotate_*` functions will return annotations with a consisten `orig_time` (first thought `None` would be a good idea, ... now changing it to `raw.info["meas_date"]` for all)
~~might be worth including in 0.24.1, cc @larsoner~~
> [MRG] FIX: make all annotate_* funcs return annots with consistent orig_time

- doc/changes/latest.inc
- mne/report/report.py
- mne/utils/docs.py
- mne/viz/epochs.py
- mne/viz/raw.py
- mne/viz/utils.py
This avoids loading data from disk or performing calculations if we don't actually need to calculate `scalings` parameters.
Also adds a `scalings` parameter to `Report.add_raw()`.
Performance improvements:
```
this branch: 2.17 s ± 214 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
main:        4.07 s ± 625 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
with the following code:
```python
import mne
raw = mne.io.read_raw_fif(sample_fname, verbose=False)
raw.pick_channels(['MEG 0111', 'MEG 0112', 'EEG 001', 'ECG 001', 'STI 014'])
report = mne.Report()
%timeit report.add_raw(raw=raw, title='foo', psd=False, replace=True)
``` …
> MRG: Speed up browse figure creation if scalings are provided

- doc/changes/latest.inc
- mne/report/report.py
This drastically reduced butterfly plotting for me locally with a test dataset (8 runs of MEG), by more than 35%
(145 seconds instead of 227)
Should only go in after #10109 has been merged.
x-ref #10107
Todo:
cc @agramfort
> MRG: Omit annotations in raw butterfly plots in Report

- doc/changes/latest.inc
- mne/report/report.py
- tutorials/intro/70_report.py
Performance changes **EDIT I've updated the numbers after adding dde9732**
```
main: 12.3 s ± 294 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
pr:   6.98 s ± 429 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Because we're re-using the same figure, I could also get rid of the explicit `scalings` pre-calculation.
MWE:
```python
import mne
raw = mne.io.read_raw_fif(sample_fname, preload=True)
r = mne.Report()
%timeit r.add_raw(raw=raw, title='foo')
```
x-ref #10107
> MRG: In Report.add_raw(), re-use the existing figure when creating butterfly plots of slices

- tutorials/io/30_reading_fnirs_data.py
A user noted that we explicitly only supported NIRx NIRScout and NIRSport 1 devices https://mne.discourse.group/t/interpolation-of-bad-channels-in-fnirs-data/4100/6
However, we actually support all NIRSport devices #9401
Modified text
> Clarify which NIRx devices we support

- doc/changes/latest.inc
- mne/report/report.py
- mne/report/tests/test_report.py
The parameter `butterfly` allows users to specify how many 1-second segments to display as butterfly plots. We keep the previous default number (10 segments).
Performance implications:
@agramfort and I were struggling with the long run time on `main`, so I decided to reduce the number of plotted segments to 50% for our specific use case.
```
10 segments: 12.1 s ± 761 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
5 segments: 6.29 s ± 132 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
MWE:
```python
import mne
raw = mne.io.read_raw_fif(sample_fname, preload=True)
r = mne.Report()
%timeit r.add_raw(raw=raw, …
```
> MRG: Allow butterfly parameter of Report.add_raw() to accept number of segments to plot

- mne/gui/_coreg.py
Replaces #10081 as I struggled with the git merge.
Conversation started over in https://github.com/mne-tools/mne-nirs/issues/419 and specifically this comment from @larsoner https://github.com/mne-tools/mne-nirs/issues/419#issuecomment-985239162 
However, when I ran the coreg guy with fNIRS data no sensors were displayed.
Enables plotting of fNIRS sources and detectors in the coreg gui
> Add fNIRS support to coregistration gui

- doc/changes/latest.inc
- mne/report/report.py
- mne/report/tests/test_report.py
- mne/time_frequency/psd.py
- tutorials/intro/70_report.py
The new parameter allows users to specify which duration of the signal to use for PSD calculation. We will then pick N equally-spaced epochs such that we cover this duration (or slightly more, due to the fixed duration of invidiual epochs).
Still WIP because I haven't really tested it with "real" data yet; but with `sample`, it can already speed up things significantly if I only use 30 seconds of data; the resulting PSD figure looks pretty much unchanged. So this could be a huge gain with only minor drawbacks.
The existing defaults from `main` are not changed; if the parameter is `None`, we continue defaulting to using all epochs for PSD calculation.
Will provide some benchmark results later.
Would like to hear what you think about this approach in general (i.e., only picking a subset of …
> MRG: Make psd param of Report.add_epochs() accept floats as durations

- doc/changes/latest.inc
- mne/annotations.py
- mne/io/base.py
- mne/io/nirx/tests/test_nirx.py
- mne/preprocessing/annotate_nan.py
- mne/preprocessing/artifact_detection.py
- mne/preprocessing/flat.py
- mne/preprocessing/tests/test_annotate_nan.py
- mne/preprocessing/tests/test_artifact_detection.py
- mne/preprocessing/tests/test_flat.py
- mne/preprocessing/tests/test_maxwell.py
intended to fix the failures from https://github.com/mne-tools/mne-python/pull/10067#issuecomment-989791374
The first commit adds a line to a test, which should run ... but which will make the test fail.
The failures most likely have to do with some weird interaction between `raw._first_time` / `raw.first_samp` and the `annotations.orig_time`.
https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=17167&view=logs&j=dded70eb-633c-5c42-e995-a7f8d1f99d91&t=8394206f-a00b-5cb7-44ca-464c9d5f9e25&l=3010
I don't know yet how it could be solved, help would be appreciated.
> BUG: Time alignments between RAW and annotate_* funcs

- doc/changes/latest.inc
- mne/report/report.py
- tutorials/intro/70_report.py
The max. width of auto-generated figures is now 850 pixels. For user-supplied figures, the existing resolution is preserved.
It doesn't change processing speed on my laptop, however there's a significant impact on file size. Running the `intro/70_report.py` tutorial, the cumulated size of the generated reports is:
```
main: 51 MB
pr:   31 MB
```
so this is a reduction of 40%. The quality of the embedded figures seems only minimally worse on my screen, and definitely sufficient for a summary report.
> MRG: Limit max width of figures we auto-create in mne.Report – Reduce report file size

- mne/viz/topomap.py
Circle was broken because an upstream link changed
> Fix Circle

- doc/changes/latest.inc
- mne/report/report.py
- tutorials/intro/70_report.py
This reduces file size by about 10% (from 19 to 17 MB) on my system with the following MWE:
```python
import mne
preload=True)
evokeds = epochs.average(by_event_type=True)
r = mne.Report()
r.add_evokeds(
evokeds=evokeds,
titles=epochs.event_id.keys()
)
r.save('/tmp/report.html', overwrite=True)
```
> MRG: Reduce dimensions of Evoked topoplots in Report & limit Report figure resolution to 100 DPI

- doc/changes/latest.inc
- mne/conftest.py
- mne/surface.py
- mne/tests/test_source_estimate.py
- mne/tests/test_surface.py
- mne/transforms.py
- tutorials/clinical/10_ieeg_localize.py
Fix a bug in `compute_volume_registration` where the smoothing was the same regardless of `zooms`. The units are voxels so we should divide by the zooms to keep the effective smoothing radius. Same for the CCMetric.
> MRG, BUG: Fix smoothing and metrics for zooms

- mne/epochs.py
- mne/evoked.py
- mne/io/base.py
- mne/source_estimate.py
- mne/time_frequency/tfr.py
- mne/utils/dataframe.py
When calling `.to_data_frame` on a number of objects in a loop, the output can get quite verbose. Here I add the `verbose` decorator to the function calls where appropriate (I hope).
The logging that gets too spammy happens in `_set_pandas_dtype`.
> [MRG] ENH: add verbose param to to_data_frame methods

- doc/changes/latest.inc
- mne/report/report.py
- mne/viz/utils.py
- tutorials/intro/70_report.py
We observed that the figure created by `Report.add_trans()` was cropped. I narrowed this down to the `_ndarray_to_fig()` function, which uses `Figure.figimage()`, which seems to later interfere with our attempts to scale / adjust resolution of the figure.
My fix is to not use `Figure.figimage()` anymore, and instead add an axes that spans across the entire figure, and use `imshow()`.
With these changes, things seem to be looking good again.
It could be that this issue was introduced through #10129, but I haven't invested much time to actually verify this hypothesis.
> MRG: Fix scaling issue in Report.add_trans()

- mne/utils/docs.py
- tutorials/io/30_reading_fnirs_data.py
After reading the issue #10147 I noticed that the tutorial specified we only support NIRx files above a certain version, but the documentation for the reader did not. Also, in #9401 and #9808 we added support for data acquired with the Aurora software, so I add that to the docs too
Clarified the vendor versions that we support reading data from. The two software use different versioning schemes, so that's a bit confusing.
> Clarify supported software versions for NIRx reader

- doc/conf.py
follow-up to #10136 which passed CircleCI at the time but now fails.  Not sure if it was an upstream change or what, but this fixes it and appears not to break anything else while we're at it.
> fix matplotlib intersphinx urls

- mne/conftest.py
Fixes warnings from ~~`nibabel`~~ `nilearn`. closes #10158
> [MAINT, MRG] Update warning filter

- doc/_includes/inverse.rst
- mne/minimum_norm/inverse.py
Closes #10149
Make everything consistent by just talking about SNR of amplitudes, and correct an error in `estimate_snr`
> MRG, DOC: Clarify lambda/SNR

- mne/report/report.py
- mne/report/tests/test_report.py
If data is acquired without a headshape, the report will error during the coregistration.  The distance measurement calculation will fail because the headshape can't be evaluated.
Our lab currently does not collect a headshape, but rather uses localized fiducials with vitamin E capsules on the MRI.  Running data through the mne-bids-pipeline fails during report generation.
> FIX - allow datasets without headshape dig to be coregistered in report

- doc/install/advanced.rst
I just noticed that the advanced install was missing a `-r` in the pip install `requirements.txt` command.
> [BUG, DOC] Install missing -r

- doc/changes/latest.inc
- mne/report/report.py
This allows uers to specify which drop reasons to ignore during creation of the drop log figure.
I want to make use of this in the MNE-BIDS-Pipeline (where, for now, I'd like to not exclude **any** drop reasons from the figure; so I need a way override the current default, hence this PR)
> MRG: Add drop_log_ignore parameter to Report.add_epochs()

- doc/changes/latest.inc
- mne/epochs.py
- mne/viz/epochs.py
- absolute numbers in addition to relative numbers
- change wording from "rejected" to "removed"
- by default omit the subject name instead of printing `Unknown subj`
old:
new:
MWE:
```python
import mne
preload=True)
epochs = epochs['left']
epochs.drop(range(10))
epochs.plot_drop_log()
```
WIP:
> MRG: Include absolute numbers in drop log plot

- mne/io/edf/edf.py
This warning was about a change introduced in v0.18, so we don't need it anymore.
> Remove v0.18 warning in EDF docstring

- mne/preprocessing/ica.py
Currently, MNE throws an error when reading an ICA solution computed with either `'fastica'` or `'picard'`. However, these packages are only required for `ICA.fit()`. Therefore, this PR moves the checks from `ICA.__init__()` to `ICA.fit()`.
> Read ICA solutions without optional packages

- doc/changes/latest.inc
- mne/gui/_coreg.py
- mne/gui/tests/test_coreg_gui.py
- mne/viz/_3d.py
This PR adds a checkbox to display the helmet in the Coregistration GUI interface.
The diff is relatively short and the feature can be useful as far as I understand.
It's part of #8833
> ENH: add helmet view option in coreg

- mne/gui/_coreg.py
- mne/viz/_3d.py
This PR fixes the bug introduced in #10200 
main | PR
--|--
<details>
```py
import mne
from mne.io import read_info
fname_raw = op.join(data_path, 'MEG', subject, subject + '_audvis_raw.fif')
fname_trans = op.join(data_path, 'MEG', subject, f'{subject}_audvis_raw-trans.fif')
trans = mne.read_trans(fname_trans)
info = read_info(fname_raw)
mne.viz.plot_alignment(
info=info,
trans=trans,
subject='sample',
subjects_dir=subjects_dir,
coord_frame='meg'
)
```
</details>
> FIX: helmet

- doc/changes/latest.inc
- mne/gui/_ieeg_locate_gui.py
- mne/gui/tests/test_ieeg_locate_gui.py
In the case that the user has not run `make_scalp_surfaces` which also may happen when the recon isn't finished (i.e. trying to get the localization done soon after), if the recon is started the `talairach.xfm` file is made fairly quickly (so you can get a `trans` with the estimation) as is the T1 so the whole GUI works (other than the pial surfaces). The 3D rendered scene isn't very useful without the surfaces but the CT can quickly be made (~0.5 s) into a surface with marching cubes which can serve the same purpose as the seghead as far as orienting.
Here's what it looks like:
> [ENH, MRG] Add marching cubes CT if recon not done

- mne/utils/docs.py
I've often been annoyed by some of our more complicated docstrings (the ones *partially* shared and thus built up via f-strings) because they end up with really bad line breaks in the terminal. This adds a small function to re-flow a docstring parameter entry so that it looks right in a terminal, and applies it to (so far only one) parameter as a proof of concept.  Here's `docdict['picks_good_data_noref']` on main:
and here it is on this PR:
> add function to reflow param entries

- doc/changes/latest.inc
- mne/gui/_ieeg_locate_gui.py
- mne/gui/tests/test_ieeg_locate_gui.py
This makes it easier to visualize which electrode is which and is consistent with the surgical plans for our ieeg data which look like this: <img width="1132" alt="Screen Shot 2022-01-16 at 7 03 44 PM" src="https://user-images.githubusercontent.com/13473576/149701840-782e7dfc-f384-48bf-835a-42c51304d612.png">. 
You can test with the same script as here: https://github.com/mne-tools/mne-python/pull/10185
This is what it looks like:
A nice improvement I think!
Note, it doesn't try and do anything for ECoG grids, I think those are easy enough to disambiguate.
> [ENH, MRG] Add lines to stereo electrodes in the ieeg location GUI

- doc/changes/latest.inc
- mne/gui/_coreg.py
- mne/gui/tests/test_gui_api.py
- mne/viz/_brain/_brain.py
- mne/viz/backends/_abstract.py
- mne/viz/backends/_notebook.py
- mne/viz/backends/_qt.py
On my macOS machine:
|`main`|PR|
|-------|----|
| <img width="341" alt="Screen Shot 2022-01-19 at 12 27 40" src="https://user-images.githubusercontent.com/2046265/150121772-068a64fc-a796-45f2-b5b7-78b57d4033a3.png"> |  <img width="386" alt="Screen Shot 2022-01-19 at 12 27 08" src="https://user-images.githubusercontent.com/2046265/150121791-9395d3b4-ed33-4ff9-9e54-2a33499081ef.png"> |
> MRG: Use actual push button widgets for push buttons in Coreg UI

- mne/conftest.py
- mne/fixes.py
Fixes #10197. Do we want to move the function to a different module?
> Use packaging.version in _compare_version

- doc/changes/latest.inc
- mne/gui/__init__.py
- mne/gui/_coreg.py
- mne/gui/tests/test_coreg_gui.py
- mne/viz/_brain/_brain.py
This PR introduces the `block` parameter to start the Qt event loop and effectively hold the context. 
*This PR is what I had in mind @hoechenberger*
Related to https://github.com/mne-tools/mne-python/issues/10221
> ENH: block parameter for viz plots

- doc/changes/latest.inc
- mne/coreg.py
- mne/gui/_coreg.py
- Make `mne.coreg.Coregistration` work with BEM surfaces that have topological defects by adding `on_defects` parameters to the respective functions.
- Make `mne.gui.coregistration` work with surfaces with topological defects by default.
This fixes issues that surfaced while working with @SophieHerbst
> MRG: Make Coregistration work with topologically defective surfaces

- mne/gui/_coreg.py
- mne/gui/tests/test_gui_api.py
- mne/viz/backends/_abstract.py
- mne/viz/backends/_notebook.py
- mne/viz/backends/_qt.py
This has been extracted from #10237 to split that PR into smaller, individual ones.
> MRG: CoregistrationUI widget improvements (extracted from #10237)

- mne/gui/_coreg.py
- Use a DigMontage to construct the fiducial points before storing them on disk (instead of a custom list of dicts)
- Introduce `CoregistrationUI._save_mri_fiducials()` method in preparation for introduction of a Save button
- Fix transformation saving if file already exists
Part of the work to split #10237 into smaller chunks
> MRG: In CoregistrationUI, use DigMontage for storing fiducials, factor out fiducials saving into new method, fix trans saving (extracted from #10237)

- mne/gui/tests/test_gui_api.py
- mne/viz/backends/_abstract.py
- mne/viz/backends/_notebook.py
- mne/viz/backends/_qt.py
Factored out from #10242 to make life easier for @GuillaumeFavelier
> Allow QLabel widget text content to be selectable

- mne/html_templates/report/epochs.html.jinja
I found myself constantly having to scroll down to the drop log before even looking at the epochs metadata. I therefore figured the drop log should be rendered above the metadata.
cc @agramfort
> MRG: In Report, move epochs drop log farther up

- mne/gui/_coreg.py
These are some more changes factored out from #10242
- Pass `overwrite='read'` instead of `True` to `_check_fname()` when we only want to read a file
- More explicit message when placing MRI fiducials
- Limit dock width to 350 pixels
- Set initial directory and filter for file picker for `trans` file
> Various small CoregistrationUI improvements extracted from #10242

- mne/gui/tests/test_gui_api.py
- mne/viz/backends/_abstract.py
- mne/viz/backends/_notebook.py
- mne/viz/backends/_qt.py
This small PR is extracted from https://github.com/mne-tools/mne-python/pull/10224 :
* adds `tooltip` to the dock slider in the GUI API
* adds an `is_enabled()` function to the `_*Widget` classes
I plan to follow this one by a PR about GUI API refactoring.
> ENH: GUI API

- doc/changes/latest.inc
- mne/surface.py
This is one I'd forgotten in #10230
> MRG: Add one forgotten on_defects parameter to _get_head_surface() for an overlooked call of read_bem_surfaces()

- mne/gui/_coreg.py
This PR is extracted from #10224:
* fixes the spin box "double call"
> FIX: coreg spin box calling set_parameter twice

- mne/gui/__init__.py
- mne/gui/_coreg.py
- mne/gui/tests/test_coreg_gui.py
This PR is extracted from #10224:
* adds a slider for the head surface opacity (semi-automatic behaviour)
> ENH: coreg opacity slider

- mne/coreg.py
- mne/gui/_coreg.py
This is the last remaining bit of the #10237 rework, incorporating suggestions and feedback I've meanwhile received.
Closes #10237
I've removed the `_fiducials_file` traitlet as it's not needed anymore. I've moved its functionality to other methods.
https://user-images.githubusercontent.com/2046265/150946042-5513b999-ba82-460f-a427-49019e842037.mov
- Saving only allowed once fiducials are locked
- Reloding fiducials automatically locks fiducials
There's a bug related to the digpoints still showing even though the fiducials are unlocked. I've left an extensive comment in the source. This is probably something that needs to be solved in a separate PR unless @GuillaumeFavelier has an immediate idea? At any rate, I don't think this PR introduced this problem 😅
cc @agramfort
> MRG: Rework CoregistrationUI fiducial I/O widgets & add save button

- mne/utils/config.py
This is an issue as PR.
My immediate go-to when I have issues or help someone else is `mne.sys_info()`. Often in my case however, issues are caused by incompatibilities between various MNE sub packages (which I define as python packages hosted within the mne-tools organisation that aren't MNE-Python). I see that the sub package `mne_qt_browser` has been added to sys_info (but I guess this is because there are plans to merge it to MNE-Python in the future). And `mne_bids` was already included.
Can we add the other sub packages to the sys info output? E.g. NIRS, Connectivity, Features
I also moved `mne_bids` from developer to user dependencies, as I think its commonly used by non developers too. 
I wasn't sure if mne-bids-pipeline fitted in to this scope and should be added too? Or if its …
> Add MNE subpackages to sys_info()

- examples/README.txt
- tutorials/README.txt
This PR adds hints about how to keep plots open when running tutorial/example-scripts locally.
> DOC: Add hint about tutorials/examples with plots

- mne/gui/tests/test_gui_api.py
- mne/viz/backends/_abstract.py
- mne/viz/backends/_notebook.py
- mne/viz/backends/_qt.py
This adds `.get_tooltip()` and `.set_tooltip()` methods to Qt and notebook widgets.
At first I had added a more sophisticated handling for widgets that don't support tooltips, raising an exception; but while writing the tests, I figured that apparently all widgets we currently support in fact *do* allow for tooltips, so I'm now using some simple `assert` statements to help us prevent silent future bugs.
This should be ready to go, @GuillaumeFavelier
> MRG: Add get_tooltip(), set_tooltip() methods to GUI widgets

- mne/gui/_coreg.py
The head opacity slider wasn't updated when `CoregistrationUI._head_opacity` changed.
> MRG: In CoregistrationUI, update slider when head opacity changes

- mne/gui/_coreg.py
This makes it such that all messages we display on the status bar will also be sent to our logger (log level "info"). We had discussed adding some kind of logging system to the GUI in the past, and this here is just a very straightforward (cheap?) way to get some basic logging.
WDYT @GuillaumeFavelier @agramfort?
> MRG: Log all CoregistrationUI statusbar messages via logger.info() too

- mne/gui/_coreg.py
In `main`, translation, rotation, and scaling get reset to their defaults (all off) when (re)loading the current subject's MRI fiducials from disk.
Here, I've added a new parameter to the responsible `_reset()` method, allowing to keep the existing parameters.
Thanks @SophieHerbst for reporting!
> In CoregistrationUI, don't reset transformation & scaling to defaults when (re)loading MRI fiducials file

- doc/changes/latest.inc
- mne/datasets/config.py
- mne/io/nirx/_localized_abbr.py
- mne/io/nirx/nirx.py
- mne/io/nirx/tests/test_nirx.py
Closes #10147
Turns out that localized dates is a pain in Python, and solving it in a general way requires a lot of work and/or additional dependencies. This implements a simpler solution: use a script to make a dict of translations and try them all. It's quick to execute, and easy enough to generate the dict of translations that we need.
@mlrocca feel free to try this branch (or just wait until it's merged into `main` and try that), it should fix your bug.
@rob-luke feel free to review and merge if you're happy
> BUG: Fix bug extracting meas_date

- mne/gui/_coreg.py
This small PR extracted from #10224:
- improves the user experience with `scale_mode = 'uniform'`
- fixes the range, increment and tooltip of the coordinate spin boxes
main | PR
--|--
> ENH: coreg UI (part II)

- mne/gui/_coreg.py
- mne/gui/tests/test_coreg_gui.py
This PR adds testing of the coreg UI with the `notebook` 3d backend. It's a very basic test for now. 
The notebook app was hanging when loading `trans` locally, I'll add it to #8833:
> - [ ] the app hangs when loading trans (ipywidgets)
> MNT: test coreg UI with notebook 3d backend

- mne/utils/docs.py
The default (docstring) for the argument `extrapolate` in `mne.viz.plot_topomap` is not respected for non-MEG sensors.
https://github.com/mne-tools/mne-python/blob/7a8964a6c8277ae1e84e0a606604f1c7eadd2569/mne/viz/topomap.py#L2168-L2172
> Default in docstring for mne.viz.plot_topomap is only True for MEG sensors

- doc/glossary.rst
I read through the glossary and made some improvements (I hope).
Open questions:
1. I would capitalize the terms for aesthetic reasons.
2. We could add the Glossary to the left sidebar on our homepage. Thoughts?
> Improve glossary

- doc/changes/latest.inc
- mne/time_frequency/multitaper.py
- mne/time_frequency/tests/test_tfr.py
- mne/time_frequency/tfr.py
Fixes #8722.
Changes multitaper time-frequency to return per-taper Fourier coefficients when `output == 'complex'`. So far the coefficients were averaged across tapers which is not correct. This change should also allow users to calculate connectivity measures per taper and average across tapers (this is what we do correctly now for ITC).
Currently the output has the following shape: `(n_epochs, n_channels, n_tapers, n_freqs, n_times)`
This could be changed if you think a different output structure will work better.
To see how this PR works, you can try the script below (based on code provided by @chapochn in #8722; I will reshape this code into a test later this week):
```python
import mne.time_frequency as tfr
signal = np.zeros(1000)
signal[500:] = 1
tfr_out1 = …
```
> ENH: return complex multitaper output per taper

- mne/viz/backends/_notebook.py
This small PR adds HTML support to `notebook`'s dock labels.
main | PR
--|--
> FIX: notebook label HTML support

- doc/glossary.rst
- mne/utils/docs.py
- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
1. Improve enumeration of `views` in brain by describing them
2. Add `RAS` entry to glossary
3. Add links to methods in `Brain` comparison table
4. Remove two methods that we had in the comparison table but didn't actually have implementations for (`remove_foci` and `scale_data_colormap`)
> DOC: Improve docs of brain views

- doc/changes/latest.inc
- mne/time_frequency/multitaper.py
- mne/time_frequency/tests/test_psd.py
Continuation of my previos PR (#10281).
This time per taper results can be obtained from `psd_array_multitaper` as well.
This required adding an `output` arg to `psd_array_multitaper`, when `output='complex'` the `psd` array has tapers dimension. I also return `weights` in that case as well, but I'm not sure about this - the weights are generally marginally different from 1, so returning weights might not be needed (and it is not done in the `tfr_array_multitaper`, which does not use any weights, assuming they are all 1). However, weights might be useful at least for testing to check that we can get the same power results from complex output.
> [ENH, MRG] PSD multitaper per taper

- doc/conf.py
- doc/mri.rst
- mne/__init__.py
- mne/_freesurfer.py
- mne/tests/test_freesurfer.py
- tutorials/clinical/10_ieeg_localize.py
So in using the `Dipy` alignment code, I had been running into issues on some subjects as had others as mentioned on the discussion board. Per the issue in `Dipy` https://github.com/dipy/dipy/issues/2490 there is really no good solution for this despite several attempts. The issue with manual alignment is that it isn't that exact (in ``freeview`` you can only move in 0.5 mm increments with the sliders but you can type to any accuracy). So, I think, since this is really a situation where you want to be as exact as possible, the algorithm needs to be rerun with the manual starting point so that you don't get stuck in the local minimum.
I tried just using the aligned CT as a starting point, but, interestingly, that gives poor alignment results. I'm not quite sure why, but I'd really rather …
> [DOC, MRG] Fix CT alignment instructions

- mne/gui/_coreg.py
- mne/gui/tests/test_gui_api.py
- mne/viz/backends/_abstract.py
- mne/viz/backends/_notebook.py
- mne/viz/backends/_qt.py
This PR adds support for collapsible group boxes for the `notebook` 3d backend. Here is an example with coreg:
main | PR
--|--
*I know the main render view still appears stretched, there might be way to fix its size somehow*
It's an item of #8833
> ENH: collapsible group box

- mne/utils/config.py
Just adds some paths useful for MNE-NIRS (see https://github.com/mne-tools/mne-nirs/pull/444 and https://github.com/mne-tools/mne-nirs/blob/83ad54d018f2a3ed3e4e4ab3111a5541520dd3ae/mne_nirs/conftest.py#L14-L17 ). This makes the checking less strict than it could be by adding config vars one by one, but it makes maintenance at the MNE-Python end easier because we just use the (improved) wildcard support here to allow any `MNE_NIRS*` and `MNE_DATASETS_FNIRS*`, so we don't need a PR here any time mne-nirs wants to add a new config var.
> MAINT: Add paths for mne-nirs

- mne/viz/_mpl_figure.py
- mne/viz/raw.py
Example: Fixes #10314.
`bgcolor` argument was ignored by raw plotter.
```python
import mne
pth = op.join(mne.datasets.sample.data_path(), 'MEG', 'sample')
fname = 'sample_audvis_raw.fif'
raw = mne.io.read_raw(op.join(pth, fname))
raw.plot(bgcolor='red')
```
on main branch the `bgcolor` does not lead to any observable effects. Now it looks like this:
> FIX: set background color in raw.plot()

- mne/gui/_coreg.py
- mne/utils/config.py
- mne/viz/_3d.py
- mne/viz/_brain/_brain.py
- mne/viz/backends/_abstract.py
- mne/viz/backends/_pyvista.py
- tutorials/clinical/20_seeg.py
- tutorials/inverse/60_visualize_stc.py
- tutorials/io/30_reading_fnirs_data.py
This PR adds a 3d option to control depth peeling to address issues with X forwarding.
It is still work in progress:
- should depth peeling be enabled by default?
- should it be disabled on CircleCI?
In another PR, I plan to refactor the properties of `_PyVistaRenderer` and move them into `_Figure` where I think they should live (the `store` attribute serves this purpose).
> MNT: Depth-peeling 3d option
