mne-tools/mne-python

.travis.yml, mne/viz/backends/_pyvista.py
I investigate recent Travis failure on python 3.8.1
Relevant infos: https://github.com/mne-tools/mne-python/pull/8202#issuecomment-686089259
=> FIX: Travis failure on python3.8.1

mne/conftest.py, mne/viz/raw.py, mne/viz/tests/test_raw.py, mne/viz/utils.py
Let's see how much the CIs suffer trying to build an old PR. At least locally `pytest mne/viz/tests/test_raw.py` passes.
=> FIX: Fix bug with raw scrolling (#8089)

doc/changes/latest.inc, mne/stats/cluster_level.py, mne/stats/tests/test_cluster_level.py
=> MRG, ENH: Update summarize_clusters_stc

doc/changes/0.18.inc, doc/changes/0.20.inc, doc/changes/latest.inc, doc/python_reference.rst, mne/preprocessing/__init__.py, mne/preprocessing/flat.py, mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_flat.py
=> MRG, API: Move mark_flat->annotate_flat

mne/viz/_brain/tests/test_notebook.py
Fixes a missing requirement that was causing https://travis-ci.org/github/mne-tools/mne-python/jobs/725855317#L5660
=> MAINT: Add req for NB test

doc/changes/latest.inc, mne/io/snirf/_snirf.py
Reads measurement date and birthdate for SNIRF files.
See spec here https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#nirsimetadatatagsmeasurementdate 
Parallel writer here https://github.com/mne-tools/mne-nirs/pull/166 with check to ensure date time does vary here https://github.com/mne-tools/mne-nirs/pull/166/files#diff-97adcb285086e704b219a0e18ede4576R47-R49
=> WIP: Read measurement date and birth date from SNIRF files

doc/changes/latest.inc, mne/io/proj.py, mne/tests/test_proj.py
Closes #8250.
It's not a great idea to assign to a var that might not have been created yet, so ensure it's always there. Then if it's still `None`, infer from the channel name list. And either way, check to make sure that the length of the channel name list is consistent with the listed number of channels.
No need for `latest.inc` update I think as this just cleans up some error messages / corner cases.
=> MRG, MAINT: Better error for nchan

doc/changes/latest.inc, mne/time_frequency/tests/test_tfr.py, mne/time_frequency/tfr.py, mne/viz/topomap.py
Closes #8045
@hoechenberger feel free to test with this slightly abbreviated minimal example:
<details>
```
import mne
from mne.time_frequency import tfr_morlet
from mne.datasets import somato
data_path = somato.data_path()
subject = '01'
task = 'somato'
raw_fname = op.join(data_path, 'sub-01', 'meg', 'sub-01_task-somato_meg.fif')
raw = mne.io.read_raw_fif(raw_fname)
picks = mne.pick_types(raw.info, meg='grad', eeg=False, eog=True, stim=False)
event_id, tmin, tmax = 1, -1., 3.
baseline = (None, 0)
epochs = mne.Epochs(raw, events, event_id, tmin, tmax, picks=picks,
baseline=baseline, reject=dict(grad=4000e-13, eog=350e-6),
preload=True)
freqs = np.logspace(*np.log10([6, 35]), num=8)
n_cycles = …
```
=> MRG, BUG: Fix bugs with TFR topo(map) plotting

examples/datasets/plot_opm_data.py, examples/inverse/plot_custom_inverse_solver.py, examples/inverse/plot_mixed_norm_inverse.py, examples/inverse/plot_multidict_reweighted_tfmxne.py, examples/inverse/plot_rap_music.py, examples/visualization/plot_make_report.py
There are a bunch of `evoked.crop` errors listed here:
https://app.circleci.com/pipelines/github/mne-tools/mne-python/3695/workflows/2c19da56-702e-49db-a357-26ecab7e40ea/jobs/22327
And a timeout in an OPM example. Let's see if this at least gets those to pass.
=> MAINT: CircleCI errors

examples/inverse/plot_dics_source_power.py, examples/inverse/plot_source_space_snr.py, mne/fixes.py, mne/minimum_norm/_eloreta.py, mne/minimum_norm/inverse.py, tutorials/source-modeling/plot_beamformer_lcmv.py, tutorials/source-modeling/plot_mne_dspm_source_localization.py, tutorials/source-modeling/plot_mne_solutions.py
Lots of little memory tweaks, hopefully once green+merge CircleCI builds properly.
Closes #8008
=> MAINT: Speed up more [skip travis]

doc/changes/latest.inc, mne/baseline.py, mne/beamformer/tests/test_lcmv.py, mne/beamformer/tests/test_rap_music.py, mne/conftest.py, mne/dipole.py, mne/epochs.py, mne/evoked.py, mne/inverse_sparse/tests/test_gamma_map.py, mne/inverse_sparse/tests/test_mxne_inverse.py, mne/minimum_norm/tests/test_inverse.py, mne/report.py, mne/tests/test_dipole.py, mne/tests/test_epochs.py, mne/tests/test_evoked.py, mne/tests/test_morph.py, mne/tests/test_report.py, mne/tests/test_source_estimate.py, mne/utils/docs.py, mne/viz/tests/test_topo.py, mne/viz/tests/test_topomap.py, tutorials/evoked/plot_10_evoked_overview.py, tutorials/evoked/plot_20_visualize_evoked.py
This reverts commit 7f34517b9444a5d6c0585699a27d8c94e3840ab7.
As discussed in #8216
=> Revert #8156

mne/epochs.py, mne/evoked.py, mne/report.py, mne/utils/docs.py
Try to explain in more detail how baseline-correction is actually being performed. I have to admit I regularly have to check the code because I forget. It's embarrassing **and** inconvenient having to dig through the code. With the help of this PR, the inconvenience shall be reduced, while the embarrassment remains.
=> MRG: DOC: Explain better how baselining is performed

doc/_templates/layout.html, doc/conf.py
coming from old https://github.com/mne-tools/mne-python/commit/20816df1031603b536c65b530e6f8c848a070149
=> we don't embed twitter anymore

doc/changes/latest.inc, examples/inverse/plot_gamma_map_inverse.py, examples/inverse/plot_mixed_norm_inverse.py, mne/beamformer/_rap_music.py, mne/beamformer/tests/test_rap_music.py, mne/forward/forward.py, mne/forward/tests/test_forward.py, mne/inverse_sparse/_gamma_map.py, mne/inverse_sparse/mxne_inverse.py, mne/inverse_sparse/tests/test_gamma_map.py, mne/inverse_sparse/tests/test_mxne_inverse.py, mne/io/proj.py, mne/minimum_norm/inverse.py, mne/minimum_norm/tests/test_inverse.py
Adds explained variance logging to `mixed_norm` like we have for `apply_inverse`
Currently there is some bug where things do not match properly, hopefully will fix soon
Todo:
=> MRG, ENH: Add exp var to mxne

doc/changes/0.21.inc, mne/viz/_brain/_brain.py, mne/viz/_brain/tests/test_brain.py
=> FIX: Fix single handling (#8285)

doc/changes/latest.inc, doc/sphinxext/gh_substitutions.py, mne/io/edf/edf.py, mne/io/edf/tests/test_edf.py
=> Gracefully handle invalid EDF dates

tutorials/machine-learning/plot_sensors_decoding.py
Hopefully fixes a memory problem seen in master https://app.circleci.com/pipelines/github/mne-tools/mne-python/3783/workflows/1127d0f7-cfdc-4a0c-aa5c-95df61fa4a65/jobs/22427
No functional changes, just some `del` and modernization of refs so I'll merge and backport once CIs come back happy.
=> MRG, DOC: Improve memory

setup.py
=> Sourcerank

setup.py
* bump copyright year
* add keywords and URLs to setup
* ECog -> ECoG
Co-authored-by: Eric Larson <larson.eric.d@gmail.com>
Co-authored-by: Eric Larson <larson.eric.d@gmail.com>
=> Sourcerank (#8297)

doc/changes/latest.inc, mne/channels/tests/test_channels.py, mne/io/reference.py, mne/io/tests/test_reference.py
Closes #8300
@mmagnuski can you see if this fixes your problem?
=> MRG, BUG: Fix add_reference_channels

doc/changes/latest.inc, mne/channels/channels.py, mne/io/tests/test_compensator.py
=> MRG, BUG: Fix comp + pick without preload

doc/changes/latest.inc, mne/io/nihon/nihon.py, tutorials/io/plot_20_reading_eeg_data.py
Closes: #8319 
Adds documentation to document NK data files.
=> [MRG] Adding updated documentation for Nihon Reader

doc/references.bib, examples/inverse/plot_mne_cov_power.py, mne/cov.py, mne/minimum_norm/inverse.py
This PR adds a reference for the recently introduced `apply_inverse_cov`function.
cc @agramfort
=> DOC: add literature reference for apply_inverse_cov

mne/decoding/receptive_field.py
=> FIX doc receptive field

mne/channels/tests/test_montage.py, mne/decoding/csp.py, mne/decoding/time_frequency.py, mne/preprocessing/xdawn.py, mne/utils/check.py, mne/utils/tests/test_check.py, mne/viz/_brain/_brain.py, mne/viz/_brain/surface.py, mne/viz/backends/_pyvista.py, mne/viz/tests/test_3d.py
Fixes #8204. Instead of just returning `True` if the argument is valid, the function now returns the valid argument for further use. This can simplify some code constructs.
=> Add _check_option return value

doc/changes/latest.inc, mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py
Ensure that whatever projectors were active during `.fit` are applied during `.apply`.
=> MRG, BUG: Fix ICA with projectors

mne/preprocessing/ica.py
`master`:
```
...
Inferring max_pca_components from picks
Applying projection operator with 3 vectors
Applying projection operator with 3 vectors
Selecting by explained variance: 74 components
```
This PR:
```
...
Inferring max_pca_components from picks
Applying projection operator with 3 vectors (pre-whitener computation)
Applying projection operator with 3 vectors (pre-whitener application)
Selecting by explained variance: 74 components
```
=> ENH: Better log when applying proj during ICA

doc/references.bib, examples/connectivity/plot_cwt_sensor_connectivity.py, examples/connectivity/plot_mne_inverse_envelope_correlation.py, examples/connectivity/plot_mne_inverse_envelope_correlation_volume.py, examples/connectivity/plot_mne_inverse_psi_visual.py, examples/datasets/plot_brainstorm_data.py, examples/datasets/plot_limo_data.py, examples/decoding/decoding_rsa.py, examples/decoding/plot_decoding_csp_eeg.py, examples/decoding/plot_decoding_spoc_CMC.py, examples/decoding/plot_decoding_time_generalization_conditions.py, examples/decoding/plot_decoding_xdawn_eeg.py, examples/decoding/plot_ems_filtering.py, mne/datasets/utils.py, mne/decoding/csp.py, mne/decoding/ems.py, mne/decoding/receptive_field.py, mne/io/meas_info.py
WIP, chipping away at bibtex updates.
=> MRG,DOC: convert references to bibtex

SECURITY.md
this is related to our [community profile](https://github.com/mne-tools/mne-python/community)
=> RFC: Create SECURITY.md

doc/changes/latest.inc, mne/io/fiff/raw.py, mne/io/fiff/tests/test_raw_fiff.py, mne/utils/check.py, mne/utils/docs.py
As discussed in #8340
@eort WDYT?
=> MRG, API: Add on_split_missing to read_raw_fif

doc/changes/latest.inc, mne/minimum_norm/inverse.py
@hichamjanati can you see if it fixes your problem with MxNE?
@larsoner do you confirm it's a bug?
=> WIP : rank was not passed to compute_depth_prior

.travis.yml, README.rst, doc/changes/latest.inc, mne/datasets/sleep_physionet/tests/test_physionet.py, mne/decoding/base.py, mne/decoding/tests/test_base.py, mne/filter.py, mne/fixes.py, mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_infomax.py, mne/time_frequency/multitaper.py, mne/viz/_figure.py, mne/viz/epochs.py, mne/viz/evoked.py, mne/viz/ica.py, mne/viz/raw.py, mne/viz/tests/test_3d.py, mne/viz/tests/test_raw.py, mne/viz/tests/test_topo.py, mne/viz/utils.py
Remove some cruft by bumping minimums that will be > 2 years old by the time we next release (March 2021).
Not sure if this or #7955 should go in first (probably #7955 since the rebase there would be more painful).
=> MRG, MAINT: Bump minimums

.gitignore, doc/python_reference.rst, mne/__init__.py, mne/coreg.py, mne/source_space.py, mne/tests/test_coreg.py, mne/tests/test_source_estimate.py, mne/tests/test_source_space.py, mne/transforms.py, mne/utils/docs.py, mne/viz/_brain/_brain.py, tutorials/source-modeling/plot_background_freesurfer_mne.py
Inspired by conversations with @adam2392
=> MRG, DOC: MNI transformation

mne/viz/_brain/tests/test_brain.py, mne/viz/tests/test_3d.py
This PR follows https://github.com/mne-tools/mne-python/pull/8408#issuecomment-715338889 and updates testing accordingly.
=> ENH: Test separate MPL canvas in stc.plot

doc/changes/latest.inc, examples/inverse/plot_morph_volume_stc.py, mne/morph.py, mne/source_estimate.py, mne/tests/test_morph.py, mne/utils/docs.py
=> MRG, ENH: Linearize volume morph

doc/changes/0.21.inc, mne/io/brainvision/brainvision.py, mne/io/brainvision/tests/data/test.vhdr, mne/io/brainvision/tests/test_brainvision.py
=> [MRG] Backport #8434

doc/changes/latest.inc, mne/epochs.py, mne/io/base.py, mne/io/tests/test_write.py, mne/io/write.py, mne/tests/test_epochs.py
To keep @agramfort sane, this is #8324 without the last commit (which is orthogonal and actually fixes the issue).
=> MRG, BUG: Fix errant writing of too large int (part 1/2)

doc/changes/latest.inc, mne/epochs.py, mne/tests/test_epochs.py
=> MRG, BUG: Fix errant writing of too large int (part 2/2)

mne/viz/_figure.py, mne/viz/raw.py
=> FIX, VIZ: ensure figs appear

tutorials/machine-learning/plot_sensors_decoding.py
None
Just a small mistake in the description of the y vector.
=> mistake in the description of y in the decoding tutorial

examples/connectivity/plot_mne_inverse_envelope_correlation.py, mne/label.py, mne/tests/test_label.py, mne/tests/test_source_estimate.py
Fixes [CircleCI in master](https://app.circleci.com/pipelines/github/mne-tools/mne-python/4402/workflows/2f31922f-b7cd-4ff8-b3be-9be982975306/jobs/23110) due to a little bug introduced in #8447
=> MRG, FIX: Infer subject

mne/io/brainvision/brainvision.py
Based on https://github.com/mne-tools/mne-python/issues/8432#issuecomment-720903265
=> [MRG] Add info where certain BV headers might come from

mne/morph.py, mne/viz/_3d.py
While looking into scaling issues with the volumetric morph, I wanted to first better figure out / remember how our surface code works. I always trip over the code when I read it. This is an attempt to simplify it, hopefully it's more readable now. I removed the `dense` code path since we don't use it. Along the way I made the `mpl` STC plotting code a tiny bit more DRY.
No need for `latest.inc` or example updates because this just changes internal code bits. No need for test update because our existing tests seemed sensitive enough to errors (e.g., iterating one two many or too few times).
=> MRG, MAINT: Simplify morphing code

doc/changes/latest.inc, mne/morph.py, mne/tests/test_morph.py, mne/tests/test_source_estimate.py
=> MRG, BUG: Fix volumetric morphing treatment of zooms

doc/changes/latest.inc, mne/preprocessing/stim.py, mne/preprocessing/tests/test_stim.py
needed for one study where the stim artifact is also in the EOG channel
=> add picks param in fix_stim_artifact

doc/changes/latest.inc
As Alex suggested following #8452: "was missing a what's new entry... @olafhauk can you make a PR to get credit for this work?"
=> WIP: added credits for mne.source_estimate.apply_baseline

doc/changes/latest.inc, mne/io/reference.py, mne/io/tests/test_reference.py
@nbara feel free to try this to see if it fixes your problem
=> MRG, BUG: Fix add_reference_channels (more)

azure-pipelines.yml
attempts to fix `ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\pip-uninstall-bvshoe9u\\pip.exe'`
=> CI, MAINT: fix azure

doc/_static/style.css, doc/changes/latest.inc, doc/install/contributing.rst
Also touch two changelog entries to see what it looks like when rendered.
Closes #8436
=> [MRG] DOC: Add new changelog template to contributors' guide

mne/utils/mixin.py
@sappelhoff does this accord with the behavior you're seeing?
=> MRG, DOC: epochs getitem clarification

doc/changes/latest.inc, doc/changes/names.inc
trying again to update **latest.inc**.  Hopefully no conflict this time!
=> DOC: Update latest.inc [skip travis] [skip github]

.circleci/config.yml
Trying to use this for https://github.com/numpy/numpy/issues/17761, but really this could be useful in other scenarios where we want to be able to "rerun with SSH" and test.
=> MAINT: Add interactive test mode [skip travis] [skip github]

examples/io/plot_objects_from_arrays.py, mne/viz/_figure.py, mne/viz/epochs.py, mne/viz/tests/test_epochs.py, tutorials/evoked/plot_whitened.py
Fixes the CircleCI failures introduced by #8381
=> FIX: Circle failures

doc/changes/latest.inc, mne/preprocessing/_fine_cal.py, mne/preprocessing/tests/test_fine_cal.py
Fixes a bug where the indexing was off so the mag fine cal coefficients were wrong.
=> MRG, BUG: Fix fine cal indexing

doc/changes/0.21.inc, examples/inverse/plot_label_source_activations.py, mne/channels/tests/test_interpolation.py, mne/preprocessing/tests/test_maxwell.py, mne/preprocessing/tests/test_xdawn.py, mne/viz/ica.py
=> MRG, BUG: Fix Xdawn check

examples/forward/plot_left_cerebellum_volume_source.py, mne/source_space.py
Fixes CircleCI failures due to excessive memory consumption. Touches the example that was failing so that we can make sure it actually runs. Locally it used ~4GB before this PR and ~700MB afterward, let's see if CircleCI agrees.
=> MRG, BUG: Fix memory bug

doc/changes/latest.inc, doc/python_reference.rst, mne/epochs.py, mne/preprocessing/__init__.py, mne/preprocessing/realign.py, mne/preprocessing/tests/test_realign.py
=> MRG, ENH: Add realign_raw

mne/label.py, mne/tests/test_label.py
This small PR refactors `_read_annot` and adds `_read_annot_cands` which is useful for https://github.com/mne-tools/mne-python/pull/8335
=> MRG: Add _read_annot_cands

mne/viz/_brain/_brain.py, mne/viz/_brain/tests/test_brain.py, mne/viz/backends/_pyvista.py
This PR comes from https://github.com/mne-tools/mne-python/pull/8335 and improves `Brain`'s coverage.
=> MAINT: Improve coverage of Brain

doc/changes/latest.inc, mne/viz/evoked.py, tutorials/intro/plot_10_overview.py
=> MRG, VIZ: equal aspect ratio for inset sensor maps

doc/install/pre_install.rst
Adds MNE-NIRS to the list of MNE compatible packages in the docs.
=> WIP: Add MNE-NIRS to the list of MNE ecosystem packages

doc/changes/latest.inc, mne/viz/backends/_pyvista.py, tutorials/preprocessing/plot_70_fnirs_processing.py, tutorials/source-modeling/plot_dipole_orientations.py
This PR updates the plotter in the `set_3d_view` routine.
Closes https://github.com/mne-tools/mne-python/issues/8562
=> FIX: set_3d_view

requirements.txt
Closes #8568
Upstream bug https://bugreports.qt.io/browse/QTBUG-88688
=> MAINT: Avoid 5.15.2 on Linux

mne/utils/docs.py, mne/viz/_figure.py, mne/viz/epochs.py, mne/viz/raw.py, mne/viz/tests/test_figure.py, mne/viz/tests/test_raw.py, mne/viz/utils.py, tutorials/epochs/plot_20_visualize_epochs.py, tutorials/raw/plot_40_visualize_raw.py
=> MRG, VIZ, MAINT: use figure class for PSD plots

mne/viz/_brain/_brain.py, mne/viz/backends/_pysurfer_mayavi.py, mne/viz/backends/_pyvista.py, mne/viz/backends/base_renderer.py, mne/viz/backends/renderer.py
This PR brings back control over the camera and fixes the 'Bouncing Brain' issues:
master | PR
---|---
=> FIX: reset_camera

.github/workflows/codespell_and_flake.yml, .github/workflows/compat_minimal.yml, .github/workflows/compat_old.yml, .github/workflows/linux_conda.yml, .github/workflows/linux_pip.yml, .github/workflows/macos_conda.yml
This PR follows https://github.com/mne-tools/mne-python/issues/8518#issuecomment-729641049 and uses https://github.com/mstachniuk/ci-skip to add skipping mechanic to our GitHub Actions jobs.
Related to https://github.com/mne-tools/mne-python/issues/8518
=> MAINT: Fix skipping with GitHub Actions

azure-pipelines.yml, tools/github_actions_dependencies.sh
Shouldn't need it now that they've fixed the bug, and it's problematic now that 1.21.dev is up
=> MAINT: Remove pin

azure-pipelines.yml
=> MAINT: pip problems

mne/fixes.py
=> fix new sklearn tags

azure-pipelines.yml, mne/viz/_3d.py, mne/viz/_brain/_brain.py, mne/viz/_brain/tests/test_brain.py, tools/github_actions_dependencies.sh, tutorials/misc/plot_ecog.py
Should fix recent CircleCI failures
=> BUG: Fix handling of no data

mne/viz/_brain/tests/test_brain.py
Discussed with @GuillaumeFavelier and moved into a separate issue to fix properly later, will merge once CIs come back happy
=> MAINT: Skip bad macOS test

examples/inverse/plot_source_space_snr.py, mne/viz/_brain/_brain.py, mne/viz/_brain/callback.py, tutorials/misc/plot_seeg.py
This PR fixes the issues encountered after https://github.com/mne-tools/mne-python/pull/8576.
Closes https://github.com/mne-tools/mne-python/issues/8623
=> FIX: volume

mne/viz/_3d.py, mne/viz/_brain/tests/test_brain.py
Fixes one of the issues @GuillaumeFavelier
=> MRG, BUG: Fix number of labels

mne/minimum_norm/inverse.py, mne/minimum_norm/tests/test_inverse.py
From a conversation on gitter I realized this error message should be clearer about what actually needs to be done
=> DOC: Clearer error message

doc/changes/latest.inc, examples/preprocessing/plot_run_ica.py, examples/visualization/plot_evoked_topomap.py, mne/evoked.py, mne/preprocessing/ica.py, mne/viz/ica.py, mne/viz/tests/test_ica.py, mne/viz/tests/test_topomap.py, mne/viz/topomap.py, tutorials/preprocessing/plot_40_artifact_correction_ica.py
Closes #8634.
FYI some special-casing for MacOSX was removed because it was fixed 4 years ago in matplotlib 2 (https://github.com/matplotlib/matplotlib/pull/6178)
=> MRG, BUG: Fix passing of channel type

mne/viz/_3d.py, mne/viz/tests/test_3d.py
Closes #8642
Feel free to try it @kingjr . But you should really switch to using the PyVista backend and complain about problems there and we will fix them :)
=> MRG, BUG: Mayavi center

doc/install/advanced.rst
Based on discussion with @larsoner on slack and [here](https://github.com/mne-tools/mne-python/issues/7977#issuecomment-673748055).
=> [MRG] DOC: update MESA docs for remote rendering

doc/changes/latest.inc, mne/viz/_figure.py
=> MRG, VIZ: fix annotation redraw when changing window duration

doc/changes/latest.inc, mne/io/nicolet/nicolet.py
=> fix int/float conversion in nicolet header

doc/changes/latest.inc, mne/io/reference.py, mne/io/tests/test_reference.py
=> fix set_bipolar_reference for Epochs

requirements_doc.txt
Ideally we'd wait for the upstream PR to be merged and for a release to be made. But in the meantime we can fix the search by merging this, and update our `requirements_doc.txt` as those other steps occur.
That is assuming this actually fixes search. Current other PR builds like [this one](https://24504-1301584-gh.circle-artifacts.com/0/dev/index.html) show the issue so if this PR fixes it we should be good.
Closes #8705
=> MAINT: Fix search

doc/changes/latest.inc, mne/viz/evoked.py, mne/viz/tests/test_topo.py, mne/viz/topomap.py
closes #8733 
Not sure if this is a reasonable fix since I've never personally worked with sEEG, but based on general knowledge I'm assuming there's nothing special needed as far as combining sensor pairs?  Can someone confirm?
cc @BarryLiu97.  On this branch using your code from #8733 I get this figure:
=> MRG, VIZ, FIX: sEEG picking in _prepare_topomap_plot()

doc/changes/latest.inc, mne/report.py, mne/tests/test_report.py
This new method allows to add user-defined CSS to the report.
=> MRG, ENH: Add Report.add_custom_css

mne/bem.py
=> enforce abs path

.circleci/config.yml, CONTRIBUTING.rst, README.rst, azure-pipelines.yml, doc/_includes/forward.rst, doc/_templates/layout.html, doc/conf.py, doc/glossary.rst, doc/install/advanced.rst, doc/install/contributing.rst, doc/install/mne_python.rst, doc/links.inc, doc/overview/faq.rst, mne/tests/test_morph.py, mne/utils/docs.py, mne/utils/tests/test_fetching.py, tools/circleci_download.sh
=> Replace master -> main

doc/changes/latest.inc, doc/references.bib, mne/minimum_norm/inverse.py, mne/minimum_norm/tests/test_inverse.py, mne/utils/docs.py
=> MRG, BUG: Allow depth > 1

mne/datasets/tests/test_datasets.py, mne/datasets/utils.py
=> Better error message if configured download folder doesn't exist

mne/viz/_brain/_brain.py, mne/viz/_brain/tests/test_brain.py
This PR fixes the bug in `remove_labels()` preventing it to have any effect. I also updated the tests to avoid regression.
Closes https://github.com/mne-tools/mne-python/issues/8815
=> MRG, FIX: Brain add/remove labels

mne/viz/_3d.py
This PR modifies `plot_stc` so that it `use_3d_backend()` instead of `set_3d_backend()`. The former is temporary while the latter modifies subsequent calls. It (hopefully) simplifies backend management in this function.
Closes https://github.com/mne-tools/mne-python/issues/8798
=> MNT: plot_stc backend

doc/conf.py, mne/annotations.py, mne/bem.py, mne/coreg.py, mne/datasets/eegbci/eegbci.py, mne/datasets/kiloword/kiloword.py, mne/datasets/sleep_physionet/age.py, mne/datasets/sleep_physionet/temazepam.py, mne/decoding/base.py, mne/decoding/search_light.py, mne/dipole.py, mne/epochs.py, mne/event.py, mne/fixes.py, mne/io/base.py, mne/io/meas_info.py, mne/label.py, mne/preprocessing/_regress.py, mne/preprocessing/nirs/_tddr.py, mne/report.py, mne/simulation/source.py, mne/utils/mixin.py, requirements_doc.txt
For testing and eventually using https://github.com/numpy/numpydoc/pull/302 to improve our docstrings. Our `tests/test_docstring_parameters` catch some but not all of the same errors.
=> MRG, MAINT: NumpyDoc validation in sphinx build

doc/changes/latest.inc, mne/epochs.py, mne/tests/test_epochs.py
Takes care of part of https://github.com/mne-tools/mne-realtime/issues/21. The rest will require changes in mne_realtime.
=> MRG, BUG: Fixes for realtime

.github/workflows/linux_conda.yml, .github/workflows/linux_pip.yml, .github/workflows/macos_conda.yml, azure-pipelines.yml, tools/get_minimal_commands.sh
Just some minor CI checks here while I work on https://github.com/mne-tools/mne-realtime/pull/22
=> MAINT: Update CIs

.circleci/config.yml, tools/get_minimal_commands.sh
One more I realized we probably wanted after #8847
=> MAINT: Unify handling of env vars

doc/changes/latest.inc, mne/channels/channels.py, mne/io/bti/bti.py
=> "resp" channel is for respiration, not responses

mne/preprocessing/_peak_finder.py, mne/preprocessing/eog.py
This came up during discussions via NeuroSpin folks
=> MRG, DOC: Better documentation of EOG detection "thresh" param

mne/viz/_brain/tests/test_brain.py
This PR fixes https://github.com/mne-tools/mne-python/issues/8873
=> FIX: azure

mne/viz/_figure.py
=> VIZ, FIX: make annotations immediately visible when scrolling via click on scrollbar

mne/io/edf/tests/test_gdf.py
I wrote a test guaranteed to fail within a year. And it did.
This one should last a bit longer hopefully.
=> MAINT: Fix test

doc/_static/style.css, tutorials/epochs/plot_30_epochs_metadata.py
fixes the new theme so that HTML-rendered dataframes will be scrollable.
=> DOC, STY: fix dataframe scrolling

doc/changes/0.22.inc
=> Move #8874 backport to correct changelog section

doc/changes/latest.inc, mne/viz/backends/_pyvista.py, tutorials/misc/plot_ecog.py
Closes #8868
Love that VTK provides an even simpler solution to this problem!
=> MRG, FIX: Fix coordinate calculations

doc/changes/latest.inc, mne/viz/_figure.py
=> VIZ: fix pick index when right-click on channel name in ica plot

doc/changes/latest.inc, doc/conf.py, doc/preprocessing.rst, mne/preprocessing/__init__.py, mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_maxwell.py
Requested on Discourse. I've used this function a number of times previously, seems reasonable to expose it for advanced users. Single-letter `S` follows the publication nomenclature.
=> MRG, ENH: Add Maxwell basis computation

mne/epochs.py
Did a few cleanups and fixed a bunch of forgotten things that were overlooked when implementing the many changes during the code review process.
=> DOC: Fixes to metadata docstring

tools/azure_dependencies.sh, tools/github_actions_dependencies.sh
We can now test PyQt5 on their server. Let's see if it works.
=> MAINT: Better pre

tutorials/epochs/plot_10_epochs_overview.py
Fixes an issue introduced in the PR #9009.
Remove mention of events in the epochs plot description of the tutorial.
(Sorry @drammock I forgot to undo this bit)
=> MRG, FIX: Update epochs plot description in the tutorial

tools/circleci_dependencies.sh
Deal with a PyQt5 linking bug.
=> MAINT: Circle

mne/report.py
=> MAINT: Simplify expression (followup to #9015)

doc/changes/latest.inc, mne/report.py, mne/tests/test_report.py
This will enable users to enrich their reports with custom JS.
We already allow for custom CSS and HTML, so adding custom JS is a logical next step.
=> MRG, ENH: Allow adding custom JavaScript to Report

tools/circleci_dependencies.sh
Linking earlier should fix CircleCI.
=> MAINT: Link earlier

examples/visualization/plot_evoked_whitening.py
Example: Fixes #8910.
Change the referencing to use footcite
=> [DOC] fix bibtex plot_evoked_whitening

doc/changes/latest.inc, doc/changes/names.inc, mne/preprocessing/maxwell.py
=> DOC update footcite maxwell.py

examples/time_frequency/plot_time_frequency_global_field_power.py
Fixes #8908
Fix the bibtex references.
=> bibtex fix plot_time_frequency_global_field_power

mne/source_estimate.py
Fixes bibtex citation issue#8929.
See above, adds bibtex citation.
=> Fix bibtex citation issue #8929.

mne/stats/regression.py
Fixes #8933. Updated Bibtex Reference for regression.py
=> FIX: bibtex #8933

examples/visualization/plot_mne_helmet.py
Fixes #9006.
Pivots the helmet plot.
Here is the new plot:
=> FIX: fix sideways helmet plot

tutorials/sample-datasets/plot_sleep.py
Closes #8942.
Added bibtex referencing format to plot_sleep.
=> DOC: use bibtex in plot_sleep

mne/viz/evoked.py
missing bibtex, closes #8935
added footcite reference
=> Use footcite in evoked.py

tutorials/preprocessing/plot_15_handling_bad_channels.py
Fixes #8937.
Change the referencing to work with sphinxcontrib-bibtex
=> fix bibtex plot_15_handling_bad_channels

mne/datasets/eegbci/eegbci.py
Example: Fixes #8915.
changed reference to footbibliography
=> footcite footbibliography change

tutorials/stats-sensor-space/plot_stats_cluster_erp.py
=> update citations with bibtex

mne/label.py
Fixes #8924 
use bibtex in mne/label.py
=> using bibtex for reference

tutorials/source-modeling/plot_compute_covariance.py
=> Change Citations to footcite for plot_compute_covariance.py

mne/stats/permutations.py
=> [MRG] Fix bibtex of stats/permutation.py

tutorials/sample-datasets/plot_brainstorm_phantom_elekta.py
closes #8941
add footcite reference
=> use footcite in plot_brainstorm_phantom_elekta.py

examples/visualization/plot_sensor_noise_level.py
new citation style was added. 
Fixes #8912
=> added bibtex citation

examples/simulation/plot_simulated_raw_data_using_subject_anatomy.py
DOC: #8904
use bibtex in plot_simulated_raw_data_using_subject_anatomy.py
=> DOC: use bibtex in plot_simulated_raw_data_using_subject_anatomy.py (#8904)

tutorials/preprocessing/plot_40_artifact_correction_ica.py
Example: Fixes #8938.
Fix the footcites.
together with @NeuroLaunch
=> DOC: ica example

mne/preprocessing/xdawn.py
Example: Fixes #8927.
use bibtex in xdawn.py
=>  DOC: use bibtex in xdawn.py (#8927) 

doc/conf.py, mne/simulation/raw.py, requirements_doc.txt
Fixes #8957 .
Adds a copy button to all code blocks using sphinx-copybutton. 
Updated the requirements_doc.txt to reflect addition of sphinx-copybutton.
=> DOC : Adds copy button to code blocks

examples/stats/plot_sensor_regression.py, mne/datasets/kiloword/kiloword.py, tutorials/stats-sensor-space/plot_stats_cluster_erp.py
Example: Fixes issue #8905 insert bibtex citation.
See above, insert bibtex citations.
=> Fix bibtex citation in plot_sensor_regression.py issue#8905

mne/datasets/sleep_physionet/temazepam.py
closes #8921 
Add 2 bibtex citations into temazepam.py.
=> DOC: Fix bibtex citation temazepam.py #8921.

mne/inverse_sparse/mxne_inverse.py
Fixes issue #8922 
Added bibtex citations for mxne_inverse.py
=> DOC: Fix bibtex citation mxne_inverse.py #8922.

examples/preprocessing/plot_xdawn_denoising.py
Fixes #9005.
Change references position from the top to the bottom of the example.
=> Xdawn issue

mne/io/meas_info.py
Example: Fixes #8882 .
Adding one sentence to the doc under 'lowpass'
=> adding one sentence regarding the lowpass filter

mne/datasets/limo/limo.py
#9074 was merged too soon, it needed a fix.  This is that fix.
@sappelhoff can you review?
=> fix errant merge (references outside docstring)

mne/viz/_brain/_brain.py, mne/viz/_brain/tests/test_brain.py, mne/viz/backends/_pyvista.py
This small PR is a refactor of the scalar bar attribute in `Brain`.
It's a part of https://github.com/mne-tools/mne-python/pull/8997
=> MNT: scalar bar

mne/stats/parametric.py
Fixes bibtex citation issue #8931 
Adds bibtex citation in parametric.py.
=> DOC: Fix bibtex citation in parametric.py #8931.

tutorials/source-modeling/plot_dipole_orientations.py
Fixes issue #8944.
Added bibtex citation in plot_dipole_orientations.py.
=> DOC: Fix bibtex citation in plot_dipole_orientations.py #8944.

doc/references.bib, mne/connectivity/spectral.py
Fixes issue #9148 .
Fixed the citations to be in bibtex format in spectral.py and added one reference (BrunaEtAl 2018) to references.bib
=> DOC: Fix bibtex citation and add reference to references.bib #9148

examples/datasets/spm_faces_dataset.py, examples/preprocessing/plot_find_ref_artifacts.py, examples/preprocessing/plot_ica_comparison.py, examples/preprocessing/plot_run_ica.py, tutorials/preprocessing/plot_40_artifact_correction_ica.py
We broke Circle builds by merging #9099. This PR attempts to fix the problem.
=> Fix doc build on main

doc/references.bib, mne/stats/multi_comp.py
Fixes #8930 .
updated bibtext and references.bib for 'Correction for multiple comparison using FDR' in multi_comp.py
The html doc have been built properly locally
=> bibtext and reference.bib updated for 'Correction for multiple comparison using FDR' in multi_comp.py

mne/decoding/tests/test_transformer.py
I'm going to merge to deal with https://github.com/scikit-learn/scikit-learn/issues/19726 and if it breaks something, fix it quickly...
Updated test to use modern `pytest` methods while I was in there
=> MAINT: Fix for sklearn regression

mne/channels/layout.py, mne/viz/topomap.py
Add axes plot to Layout, see example:
```
import mne
box = (0, 100, 0, 100)
pos = np.random.random((10, 4))
layout = mne.channels.Layout(box, pos, ['test'] * 10, range(10), 'test')
layout.plot(show_axes=True)
```
=> [MRG, BUG, ENH] Add axes for plot mne.channels.layout

mne/transforms.py
Added footcite to transform.py 
closes #8934
=> added footcite for transform.py

.github/workflows/codespell_and_flake.yml, Makefile, doc/glossary.rst, doc/references.bib, mne/epochs.py, tutorials/epochs/plot_40_autogenerate_metadata.py
Fixes #8974.
I added the citation for hierarchical event descriptors in the glossary, added this citation to the tutorial (plot_40_autogenerate_metadata.py ) and to epochs.py. 
Also fixed a couple typos in the description in plot_40_autogenerate_metadata.py.
=> DOC: Add HEDs to glossary and reference in tutorial and epochs.py  #8974.

doc/changes/latest.inc, mne/data/html_templates.py, mne/epochs.py, mne/report.py, mne/tests/test_epochs.py, tutorials/misc/plot_report.py
Reference issue #9177
Add `_repr_html_` for BaseEpochs:
(updated image)
=> MRG, ENH: add _repr_html_ method in the class BaseEpochs

examples/simulation/plot_source_simulator.py, mne/epochs.py, mne/simulation/source.py, mne/simulation/tests/test_source.py, mne/utils/__init__.py, mne/utils/check.py
Should fix recent CircleCI failures that started when we merged #9166, cc @NeuroLaunch @hoechenberger . The PR was not the problem, it just exposed an error in the example. I added some extra sanity checking of types so that hopefully the error is nicer when users make this mistake.
=> BUG: Fix example dtype

mne/viz/_3d.py, mne/viz/tests/test_3d.py, tutorials/source-modeling/plot_visualize_stc.py
Take care of https://app.circleci.com/pipelines/github/mne-tools/mne-python/7505/workflows/8ed068b5-563d-4754-aa83-c98e625c1cbb/jobs/26566
=> MAINT: Update for latest mpl

mne/conftest.py, mne/utils/_testing.py, mne/viz/tests/test_ica.py
hopefully fixes our MPL 3.4.0 testing woes
=> MAINT: fix click testing

doc/references.bib, mne/datasets/sleep_physionet/_utils.py, mne/inverse_sparse/mxne_optim.py
=> DOC: Last few footbibs

doc/changes/latest.inc, mne/preprocessing/ecg.py, mne/preprocessing/tests/test_ecg.py
=> FIX: Make find_ecg_events work even if ECG peak detection doesn't yield anything

mne/stats/regression.py
Doc hotfix for #9237
Small correction as pointed out by @drammock
=> Doc hotfix for #9237

mne/epochs.py, mne/evoked.py, mne/io/base.py, mne/io/tests/test_apply_function.py, mne/tests/test_epochs.py, mne/tests/test_evoked.py, mne/utils/docs.py
closes #9234 
I've locally updated the test for `epochs.apply_function()` and I'm a bit surprised / wondering if there's another bug in there.  Marking as draft until I've figured it out one way or another.  It seems like when applied channel-wise it gets applied to an ndarray that is `(n_epochs, n_times)` and it's not clear to me that that's the right thing to do (maybe it should really be epoch-wise and channel-wise?)
cc @nordme and @vpeterson
=> Fix apply function

mne/viz/_figure.py
closes #8955 
I'd rather figure out *why* this problem arose, but the allure of a fairly inexpensive one-line fix was too seductive... we'll see if it slips past the code-quality censors :)
=> make raw.plot() behave under MPL 3.4.x

doc/changes/latest.inc, mne/epochs.py, mne/tests/test_epochs.py
=> MRG, ENH: Epochs.equalize_event_counts() operates on all events by default

mne/io/nicolet/nicolet.py, mne/io/nicolet/tests/test_nicolet.py
=> ENH+DOC: read_raw_nicolet raise informative message when passing header fname

mne/utils/docs.py
=> DOC montage parameter

mne/decoding/tests/test_transformer.py
Regression was fixed upstream, restore test.
Closes #9173
=> MAINT: Restore test

doc/changes/latest.inc, mne/viz/_3d.py
=> FIX: flat map plot in notebook

tools/circleci_dependencies.sh
=> MAINT: Use latest SG

mne/preprocessing/ica.py
Deal with our linkcheck failure over the weekend
https://app.circleci.com/pipelines/github/mne-tools/mne-python/7870/workflows/958847b8-e02a-41f6-95c2-c76bd4ffbc7a/jobs/27378
=> MRG, DOC: Update link

doc/changes/latest.inc, mne/label.py, mne/tests/test_label.py
=> MRG, BUG: Fix grow_labels

doc/changes/latest.inc, mne/viz/_brain/_brain.py, mne/viz/_brain/surface.py, mne/viz/_brain/view.py, mne/viz/tests/test_3d.py, tools/circleci_download.sh, tutorials/source-modeling/plot_visualize_stc.py
=> MRG, BUG: Fix positioning of flatmaps

tutorials/raw/30_annotate_raw.py
This is already mentioned in the tutorial text above the respective code block I'm changing here, but a respective question came up anyway on the forum. So let's be even more explicit.
https://mne.discourse.group/t/annotating-continuous-data
=> MRG, DOC: Explicate that Annotations onsets & durations are in seconds in Annotations tutorial

mne/tests/test_report.py
fixes a failing test of our sphinx-gallery scraper
=> maint: fix scraper test

mne/viz/_figure.py
an element of #8761
cc @jasmainak
=> restore MPL toolbar for PSD plots

mne/report.py, tutorials/intro/70_report.py
=> improve coreg report plot

tutorials/evoked/30_eeg_erp.py, tutorials/intro/15_inplace.py, tutorials/io/60_ctf_bst_auditory.py, tutorials/preprocessing/55_setting_eeg_reference.py
Here are some tweaks to a couple tutorials, and an overhaul of the EEG ERP one.  Marking as draft because the EEG ERP one takes too long on my system, so I'm sure Circle will complain, any suggestions to speed it up are welcomed.  I also wonder if there's a better dataset to use than `sample`... thoughts (@hoechenberger maybe?)
=> MRG: Some tutorial tweaks

tutorials/evoked/20_visualize_evoked.py, tutorials/forward/10_background_freesurfer.py, tutorials/intro/20_events_from_raw.py, tutorials/raw/20_event_arrays.py, tutorials/raw/40_visualize_raw.py
moderate overhaul of freesurfer background tutorial; the rest is just cleanup of some old TODO items, and removal of no-longer-required `:class:` tags along the way.
=> more tutorial tweaks

doc/install/advanced.rst
This PR follows https://github.com/mne-tools/mne-python/issues/9360#issuecomment-829520105 and adds `MNE_3D_OPTION_ANTIALIAS` to the list of variables to set if there is an issue with Mayavi.
Closes https://github.com/mne-tools/mne-python/issues/9360
=> DOC: Update Mayavi troubleshooting section

doc/install/contributing.rst, doc/install/index.rst, doc/install/mne_python.rst
=> doc: update version requirement

doc/changes/latest.inc, doc/changes/names.inc, doc/source_space.rst, mne/label.py, mne/tests/test_label.py, tutorials/inverse/20_dipole_fit.py
I needed to find dipole labels from anatomical atlas, couldn't find any info how to do it until I stumbled on MNE discord and larsoner  helped me.
We both agree this should be in tutorial, or maybe there should be even a function/helper to find anatomical labels easily.
It might be worth looking at https://github.com/miykael/atlasreader/tree/master/atlasreader integration.
=> ENH: add anatomical label finding from atlas to dipole fit tutorial

doc/changes/latest.inc, mne/data/html_templates.py, mne/io/base.py, mne/io/tests/test_raw.py
=> FIX : html repr with RawArray

doc/changes/latest.inc, mne/data/html_templates.py, mne/io/meas_info.py, mne/io/tests/test_meas_info.py, tutorials/intro/30_info.py
=> add Projections to HTML repr

doc/conf.py
closes #9410 
thanks for the heads-up @jona-sassenhagen!
=> fix homepage link

doc/changes/latest.inc, mne/channels/montage.py, mne/channels/tests/test_montage.py, mne/io/fieldtrip/tests/helpers.py, mne/io/fieldtrip/utils.py, mne/utils/numerics.py
=> MRG, BUG: Fix head coordinate frame

.circleci/config.yml, .github/workflows/circle_artifacts.yml, .gitignore, azure-pipelines.yml, mne/conftest.py
Codecov reporting is [broken in that PRs show up as our current coverage](https://community.codecov.com/t/pr-commits-showing-up-in-default-main-branch-coverage/2945), which makes our homepage badge say wrong things like we have 32% coverage. This PR will fix this hopefully by switching to the Bash uploader, which hopefully is less buggy.
In the meantime, I'm also going to try to improve our Azure reporting to also have coverage. First commit will hopefully replicate the coverage-as-main problem, then I'll try to fix it with the bash uploader.
Closes #9188
=> MAINT: Better Azure reporting, fix codecov

doc/changes/latest.inc, doc/forward.rst, mne/bem.py, mne/commands/mne_make_scalp_surfaces.py
=> ENH : add make_scalp_surfaces function to public API

mne/utils/tests/test_config.py
see https://github.com/mne-tools/mne-python/pull/9465#discussion_r650310239
=> TESTS: Use fake MNE home dir (followup fix for #9465)

doc/changes/names.inc
@jasmainak your old link is down so our `linkcheck` build complained, I figure this one is better anyway. Okay with you?
=> MRG, DOC: Update names

tools/azure_dependencies.sh
Should hopefully fix the timeouts we've had lately. I'm pretty sure it's a problem with Mayavi building against this:
https://pypi.org/project/vtk/9.0.20210612.dev0/
=> MAINT: Make Azure happy

mne/channels/montage.py, mne/channels/tests/test_montage.py, mne/io/meas_info.py, mne/utils/__init__.py, mne/utils/docs.py, tutorials/intro/70_report.py
The type listing was wrong in #9447, would have made @sappelhoff's life easier in https://github.com/mne-tools/mne-bids/pull/807
=> MRG, BUG: Fix error message listing of types

doc/install/pre_install.rst
In your list of [MNE-friendly packages](https://mne.tools/stable/install/pre_install.html) I added my package which implements artificial neural networks to solve the EEG inverse problem. I would be happy if you agreed to share this repository on the MNE website.
Keep up the good work!
With kind regards,
Lukas Hecker
=> New package mention in https://mne.tools/stable/install/pre_install.html

doc/overview/roadmap.rst, examples/datasets/opm_data.py
Adds some stuff to our roadmap
=> DOC: Update roadmap with more items

doc/conf.py, mne/datasets/utils.py, tutorials/clinical/20_seeg.py, tutorials/clinical/30_ecog.py
Address new data in https://github.com/mne-tools/mne-misc-data/pull/5.
Ok, there is a bit of an issue with the coordinate transforms that I am still working out, but I think everything otherwise is okay.
=> [MRG, ENH] Change the sEEG tutorial to support new data

doc/changes/latest.inc
Fix incorrect link introduced in #9489.
=> Fix method link in latest.inc

mne/io/meas_info.py, mne/io/tests/test_meas_info.py, tools/circleci_dependencies.sh
Don't warn when anonymizing w/o daysback and meas_date is None
required for https://github.com/mne-tools/mne-bids/pull/815
=> Don't warn when anonymizing w/o daysback and when meas_date is None

mne/surface.py, requirements_doc.txt
There were just a few small things left over from #9484.
=> [MRG, MAINT] Remove Nipy Dependency, Note to explain ``voxel_neighbors``

doc/changes/latest.inc, mne/viz/epochs.py, mne/viz/tests/test_epochs.py
=> Fix plotting of events when there are overlapping epochs

doc/conf.py, mne/channels/tests/test_interpolation.py, mne/conftest.py, mne/inverse_sparse/tests/test_mxne_inverse.py, mne/io/artemis123/tests/test_artemis123.py, mne/simulation/tests/test_raw.py, mne/utils/docs.py, mne/viz/tests/test_evoked.py
Unrelated CI parts of / speedups in #9503
=> MRG, MAINT: Speed up CIs

examples/time_frequency/time_frequency_erds.py
Fix recent CircleCI failure due to `inplace` deprecation
https://pandas.pydata.org/docs/reference/api/pandas.CategoricalIndex.reorder_categories.html
=> MRG, MAINT: Deal with pandas dep

tutorials/intro/40_sensor_locations.py
I've updated the sensor locations tutorial to make it a little easier to read.
=> Improve sensor locations tutorial

mne/io/_digitization.py, mne/io/tests/test_raw.py
closes https://github.com/mne-tools/mne-bids/issues/839
=> FIX: repr of DigPoint in voxel space

azure-pipelines.yml, mne/minimum_norm/tests/test_inverse.py, mne/tests/test_morph.py, mne/tests/test_source_estimate.py, mne/viz/tests/test_epochs.py, mne/viz/tests/test_raw.py
Hopefully allows Azure to finish in time.
=> MAINT: More slow tests

mne/fixes.py, mne/viz/_figure.py, mne/viz/tests/test_3d.py, mne/viz/tests/test_topo.py, mne/viz/tests/test_topomap.py, mne/viz/topomap.py, mne/viz/utils.py
Running the latest version of matplotlib I hit some errors in local testing. This fixes them.
=> MRG, MAINT: Updates for mpl deprecations

doc/changes/latest.inc, mne/io/hitachi/tests/test_hitachi.py, mne/preprocessing/nirs/_beer_lambert_law.py, mne/preprocessing/nirs/_scalp_coupling_index.py, mne/preprocessing/nirs/nirs.py, mne/utils/docs.py
I was doing something silly during data analysis and this warning would have helped me see and fix it earlier.
@rob-luke can you look?
=> MRG, ENH: Add warning when distances are bad

examples/visualization/evoked_topomap.py, examples/visualization/evoked_whitening.py, mne/viz/topomap.py, mne/viz/utils.py, tutorials/clinical/20_seeg.py
Fixes some minor bugs introduced in #9550 and #9543 leading to https://app.circleci.com/pipelines/github/mne-tools/mne-python/8964/workflows/650b583f-7484-464e-9b78-228002d276f3/jobs/30745/tests
=> MRG, BUG: Fix bug with tight_layout

doc/changes/latest.inc, mne/viz/_brain/_brain.py, mne/viz/_brain/tests/test_brain.py, mne/viz/utils.py
This PR fixes https://github.com/mne-tools/mne-python/issues/9562
I was able to reproduce it locally, can you try it now @hoechenberger ?
=> FIX: brain RGBA screenshot

azure-pipelines.yml
Hopefully gets us around https://github.com/numpy/numpy/issues/19469
=> MAINT: Try workaround removal

doc/changes/latest.inc, mne/label.py, mne/surface.py, mne/tests/test_dipole.py, mne/tests/test_label.py, mne/utils/docs.py, mne/viz/_brain/_brain.py, tutorials/simulation/70_point_spread.py
=> MRG, ENH: Add label geometry methods

mne/viz/_figure.py, mne/viz/evoked.py, mne/viz/utils.py
More deprecations that we need to deal with due to https://github.com/matplotlib/matplotlib/pull/20585
=> MRG, MAINT: More mpl deps

.github/workflows/circle_artifacts.yml, .github/workflows/codespell_and_flake.yml, .github/workflows/compat_minimal.yml, .github/workflows/compat_old.yml, .github/workflows/linux_conda.yml, .github/workflows/linux_pip.yml, .github/workflows/macos_conda.yml
Maybe this will help with our GitHub actions queue
=> CI: Add concurrency to Actions

doc/changes/latest.inc, doc/preprocessing.rst, doc/visualization.rst, mne/chpi.py, mne/tests/test_chpi.py, mne/viz/__init__.py, mne/viz/misc.py, mne/viz/tests/test_misc.py, tutorials/preprocessing/59_head_positions.py
adds computation of SNR of the HPI coils.
=> add HPI SNR calculation and plotting

mne/utils/docs.py
Example: Fixes #9551.
Document specification about PTP rejection based on different types of channels
=> change documentation about PTP rejection for diff ch types

mne/_freesurfer.py, mne/source_space.py, mne/viz/_3d.py, mne/viz/misc.py
Puts `_check_mri` in a more appropriate module.
=> [MAINT, MRG] Move `_check_mri` to _freesurfer.py

doc/changes/latest.inc, mne/viz/_figure.py, mne/viz/tests/test_raw.py
=> enforce minimum data browser window size

examples/visualization/eeglab_head_sphere.py
=> [BUG, MRG] Fix biosemi example coordinate frames

mne/viz/_3d.py
This small PR adds the subject name to the window title.
Closes https://github.com/mne-tools/mne-python/issues/9615
=> ENH: Add participant name / ID in plot_alignment

doc/conf.py, doc/install/advanced.rst, doc/install/index.rst, doc/install/install_python.rst, doc/install/mne_python.rst, doc/install/updating.rst, doc/links.inc, doc/overview/faq.rst, doc/overview/get_help.rst, doc/overview/index.rst
=> update installation recommendations

doc/changes/latest.inc, doc/preprocessing.rst, mne/channels/__init__.py, mne/channels/montage.py, mne/channels/tests/test_montage.py
We now have a [Localite digitizer system](https://www.localite.de/en/products/eeg-pinpoint/), so MNE-Python needs a reader 😄.
=> Add reader for Localite dig files

doc/conf.py, tools/circleci_dependencies.sh, tools/setup_xvfb.sh
revives #9664, which couldn't be re-opened because I force-pushed while it was closed.
=> Fix circle

mne/datasets/utils.py
=> fix calling fetch_data with removed param

mne/annotations.py, mne/channels/channels.py, mne/tests/test_annotations.py, mne/utils/__init__.py, mne/utils/check.py
Following #9525 #9523 
I noted some repeated code and put it in a function in utils
There are lots of checking code already. Does something already exist to do this check?
=> MRG: Put repeated code in a function

doc/changes/latest.inc
=> update what's new

mne/conftest.py, mne/preprocessing/artifact_detection.py, mne/stats/cluster_level.py, mne/tests/test_rank.py, mne/utils/tests/test_numerics.py, mne/viz/_3d.py, tutorials/inverse/20_dipole_fit.py
With these changes, everything passes with the latest versions of our deps on Python 3.10. Couldn't test VTK because even compiling from source and trying to use the latest version it's not yet compatible with 3.10 it seems (of course).
=> MRG, MAINT: Updates for deprecations

examples/inverse/compute_mne_inverse_volume.py, examples/visualization/publication_figure.py, mne/viz/backends/_pyvista.py, tutorials/forward/30_forward.py, tutorials/inverse/30_mne_dspm_loreta.py, tutorials/inverse/80_brainstorm_phantom_elekta.py, tutorials/preprocessing/50_artifact_correction_ssp.py, tutorials/raw/30_annotate_raw.py
Found by running `make html_dev-memory` locally with latest versions of all libraries.
Also fixes a bug where we try to `renderer._sphere` with no points by short-circuiting the plotting code.
=> MRG, BUG: Fix minor CircleCI bugs

doc/references.bib
Adds URL or DOI to two papers where it was previously missing.
=> BibTeX updates

mne/conftest.py, tools/azure_dependencies.sh, tools/github_actions_dependencies.sh
Avoid --pre dipy until https://github.com/dipy/dipy/pull/2435 is dealt with
=> MRG, MAINT: Deal with dipy error

doc/changes/latest.inc, mne/viz/_3d.py, mne/viz/_brain/_brain.py, mne/viz/_brain/tests/test_brain.py, mne/viz/backends/_abstract.py, mne/viz/backends/_pysurfer_mayavi.py, mne/viz/backends/_pyvista.py, mne/viz/backends/tests/test_renderer.py
=> [ENH, MRG] Add remove methods to `mne.viz.Brain`

doc/changes/latest.inc, mne/inverse_sparse/mxne_inverse.py, mne/inverse_sparse/tests/test_mxne_inverse.py
cc @PABannier 
let me know what you think
=> MRG: avoid warning in SURE when passing grid & allow to return empty stc

mne/viz/_mpl_figure.py
Updates call for SpanSelector properties, tested locally
=> MAINT: Update matplotlib

doc/changes/latest.inc, doc/changes/names.inc, mne/channels/tests/test_channels.py, mne/io/pick.py
Fixes bug #9703 
Before the fix function pick (channels.py) could pick less channels then parameter list contains (see bug description) 
and after the fix  it suppose to handle the …
=> FIX: #9703 suspicious behavior in pick function

doc/conf.py, doc/funding.rst, tutorials/epochs/60_make_fixed_length_epochs.py
Also fixes a warning-as-error bug on `main`, a build bug due to `mne-connectivity` release, plus adds URLs for funding sources that I could find.
=> MRG, DOC: Link to funding

mne/viz/_brain/_brain.py
=> Fix doc build for PyVista 0.32

mne/tests/test_cov.py, tools/azure_dependencies.sh, tools/github_actions_dependencies.sh
Let's see if dipy pre works now that https://github.com/dipy/dipy/pull/2435 has been merged
=> FIX: Restore dipy

mne/utils/_logging.py, mne/utils/tests/test_logging.py
Allow downstream modules (e.g., mne-bids, mne-connectivity, etc.) to do this:
```
<in mne_bids.utils>
def warn(msg, category=RuntimeWarning):
from mne.utils import warn as _warn
return _warn(msg, category, module='mne_bids',
ignore_namespaces=('mne', 'mne_bids')
```
Then when they use `mne_bids.utils.warn(...)` with functions that have a `verbose` decorator, the magical `stacklevel` traversal and `verbose`-conditional warning emission will work properly. Overhead at the MNE-Python end is minimal because our default `ignore_namespaces=('mne',)` will evaluate in the list comprehensions in negligible time.
@alexrockhill it would be great if you could test your MNE-BIDS PR in conjunction with this. In the meantime you'll probably need to vendor this version of the function in the case where …
=> MRG, MAINT: Add ignore_namespaces to mne.utils.warn

mne/tests/test_cov.py, mne/viz/_3d.py, mne/viz/tests/test_3d.py, tutorials/clinical/30_ecog.py
Closes #9737
Within-cycle bugfix so no `latest.inc` update required
=> MRG, BUG: Fix surface plot regression

examples/visualization/brain.py
Fixes #9619.
Ok, a good start I think but there are a few PRs on deck that would make it more functionally complete. I think once those get done it would be a good time to revisit this and get it merged.
What do you think @rob-luke?
=> [ENH, MRG] `mne.viz.Brain` visualization tutorial

doc/conf.py, tutorials/epochs/60_make_fixed_length_epochs.py
Should hopefully fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/10151/workflows/02aee80b-ca58-4490-9a76-87a3c36c0c9b/jobs/34349
=> MAINT: Ignore mne-connectivity syntax error

doc/changes/latest.inc, mne/io/persyst/persyst.py, mne/io/persyst/tests/test_persyst.py
Fixes: #9745 
Improves the reading of the Persyst reader.
=> [MRG] Fix Persyst reader bug lower-casing all events

mne/datasets/config.py
Fixes: https://github.com/mne-tools/mne-python/pull/9762#discussion_r712788591
cc: @agramfort
=> [MRG] Fix upstream config.py issue in datasets

mne/gui/_ieeg_locate_gui.py
The labels were too small and were hard to see on a light background so this makes them larger with a black stroke.
=> [ENH, MRG] Make directional labels more visible

azure-pipelines.yml, doc/conf.py, doc/install/contributing.rst, mne/tests/test_cov.py, requirements_doc.txt, tools/azure_dependencies.sh
=> MRG, MAINT: Test doc build on Windows

doc/changes/latest.inc, mne/annotations.py, mne/tests/test_annotations.py
=> [MRG, BUG] Fix appending Annotations with channel names

MANIFEST.in, doc/changes/latest.inc, doc/datasets.rst, mne/datasets/__init__.py, mne/datasets/_phantom/base.py, mne/datasets/_phantom/phantom_otaniemi.txt, mne/datasets/tests/test_datasets.py, mne/dipole.py, setup.py, tutorials/inverse/80_brainstorm_phantom_elekta.py
Turns out the CT I already had was for the Otaniemi phantom. I'm waiting to hear back if we can get a CT of the newer phantom for the VectorView / TRIUX systems.
Closes #9792
=> MRG, ENH: Add Otaniemi phantom based on CT

doc/changes/latest.inc, mne/forward/_make_forward.py, mne/forward/tests/test_make_forward.py, mne/viz/_3d.py, mne/viz/tests/test_3d.py
Messing around with coil defs I ended up hitting a 2D `coil_def` case that's easy enough to fix. I also made custom `coil_def` errant usage easier to debug, which I do not think warrants a second `latest.inc` entry.
=> MRG, BUG: Better coil_def and plot_alignment handling

mne/datasets/_fetch.py
fixes #9806 (typo in commit message)
=> fix fetch_dataset() when force=False and no config key

mne/decoding/receptive_field.py, mne/inverse_sparse/mxne_optim.py, mne/utils/docs.py
New attempt after #9935 turned out to be misguided.
=> MRG: New attempt to slightly improve verbose docstring

azure-pipelines.yml, mne/conftest.py, mne/forward/tests/test_make_forward.py, mne/report/tests/test_report.py, mne/surface.py, mne/tests/test_bem.py, mne/viz/tests/test_3d.py
Take care of deprecation warnings about Windows 2016 like
https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=16280&view=logs&j=8d04c17d-3f6b-5313-febd-debdd8b57f4c
Closes #9930
=> MRG, MAINT: Bump CI image

.circleci/config.yml, README.rst, azure-pipelines.yml, doc/install/contributing.rst
Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/11169. @marsipu ignore errors on Azure and CircleCI until this is merged and you can rebase or merge with `upstream/main`
=> CI: Fix CircleCI and Azure

doc/changes/latest.inc, examples/visualization/3d_to_2d.py, mne/viz/_3d.py, mne/viz/backends/_pysurfer_mayavi.py, mne/viz/backends/_pyvista.py, tutorials/clinical/30_ecog.py
=> MRG, BUG: Fix bugs with snapshot_brain_montage

doc/changes/latest.inc, mne/surface.py, tutorials/clinical/10_ieeg_localize.py
Fixes https://github.com/mne-tools/mne-python/issues/9938.
=> [BUG, MRG] Actually fix circular bug this time

mne/conftest.py, mne/coreg.py, mne/gui/_coreg.py, mne/gui/tests/test_coreg_gui.py, mne/viz/backends/_abstract.py, mne/viz/backends/_notebook.py, mne/viz/backends/_pysurfer_mayavi.py, mne/viz/backends/_qt.py
I need this locally for the test to pass, otherwise it uses the PyVista backend. Bug introduced in #9913, cc @GuillaumeFavelier
=> BUG: Force mayavi in test that uses it

doc/changes/0.24.inc
fix circle error:
```
changes/0.24.inc:20: WARNING: Duplicate substitution definition name: "New Contributor"
```
=> remove duplicate substitution [skip github][skip azp]

doc/changes/latest.inc, mne/forward/_make_forward.py, mne/forward/tests/test_make_forward.py
In #9893 I forgot to account for the translation term when checking to see if sensors were inside the sphere
=> MRG, FIX: Fix interior check

doc/changes/0.18.inc, doc/changes/names.inc
this contributor's github page is 404, and their pages on both english and french versions of LinkedIn show up as "this profile is not available"
=> fix linkcheck

doc/changes/latest.inc, doc/conf.py, tutorials/clinical/10_ieeg_localize.py
Here is the procedure for doing the alignment in freeview as the `Dipy` alignment doesn't always work.
cc @leosunpsy (feel free to review)
=> [ENH, MRG] Add manual alignment procedure to ieeg localize tutorial

doc/changes/latest.inc, mne/source_estimate.py, mne/tests/test_source_estimate.py, tutorials/clinical/30_ecog.py
Fixes #9971.
I went ahead and did this one, looks better now I think.
=> [BUG, MRG] Fix projection error

requirements_doc.txt
Should fix failures in #9990, cc @mscheltienne 
Upstream issue is https://github.com/pydata/pydata-sphinx-theme/issues/508, will revert once pydata-sphinx-theme fixes compat
=> FIX: Work around Sphnix release

doc/changes/latest.inc, mne/io/brainvision/brainvision.py, mne/io/brainvision/tests/test_brainvision.py
=> Warn on missing header in BrainVision files

doc/changes/0.24.inc, doc/changes/latest.inc, mne/report/report.py, mne/report/tests/test_report.py, tutorials/intro/70_report.py
=> MRG: Add extensive checking for Report tags

mne/externals/pymatreader/pymatreader.py, mne/externals/pymatreader/utils.py, mne/io/eeglab/eeglab.py, tools/github_actions_dependencies.sh
Follow-up to #9973 that uses the merged solution in https://github.com/scipy/scipy/pull/15004
cc @thht do you want me to make a PR to pymatreader? If not, let me know when you've merged a variant of this fix and I'll copy-paste into our vendored version
~~EDIT: Marking WIP until https://github.com/nilearn/nilearn/pull/3053 is merged and I can undo the pin to my `nilearn` branch~~
=> MRG, MAINT: Update for SciPy namespace

mne/externals/pymatreader/pymatreader.py, mne/externals/pymatreader/utils.py
this is the version of the pymatreader changes in #10005 as implemented in upstream pymatreader. the changes are only minor so i do not expect any problems.
thanks again @larsoner for proposing the fixes!
=> update pymatreader to version 0.0.26

setup.cfg
This makes the output of our tests a little more readable.
=> Show colored pytest output

.circleci/config.yml, tools/circleci_dependencies.sh
Implements a suggestion from @sappelhoff in https://github.com/mne-tools/mne-python/issues/10006#issuecomment-975421020 to make things build faster. It won't be enough to fix our problems, but it should at least make things faster and more robust to memory issues.
=> MRG, MAINT: Use better machine for CircleCI

tools/circleci_dependencies.sh, tutorials/inverse/20_dipole_fit.py
Doesn't fix the timeout, but should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/11535/workflows/6b0dc081-4cda-46c5-baf5-68c34877eb1a/jobs/38626
=> MAINT: Fix CircleCI error

doc/changes/latest.inc
Adds missing changelog from #9929
=> Add haemoglobin SNIRF support to changelog

doc/_static/style.css, doc/conf.py, doc/install/contributing.rst
tries to make the contrib guide more approachable.
=> contributor guide improvements

doc/changes/latest.inc, mne/surface.py, mne/tests/test_surface.py, mne/viz/_brain/_brain.py
Fixes #10023.
I'm a bit stuck, it doesn't look like anything is happening here. Anyone know how to fix this?
=> [MRG, ENH] Add `fill_holes` argument to `mne.viz.Brain.add_volume_labels`

mne/epochs.py, mne/io/base.py
=> MRG: Improve concatenate_epochs() docstring

doc/install/contributing.rst
Should fix [our linkcheck error](https://app.circleci.com/pipelines/github/mne-tools/mne-python/11604/workflows/6efd2408-e49c-4223-ad08-48d71b1a1686/jobs/38833). Will check the CircleCI output then merge
=> DOC: Fix link

.circleci/config.yml
Run our circle-front to check to see if we have the same problem as https://github.com/QB3/sparse-ho/pull/13
=> MRG, MAINT: Fix output

mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py
Follow-up to #10041
cc @agramfort
=> Don't warn when using decim with ICA.fit() on epochs

mne/utils/docs.py
Following #10061
@hoechenberger If you have a better formulation in mind, don't hesitate!
=> Update docstring for tmin tmax in epochs

.circleci/config.yml, examples/inverse/mixed_source_space_inverse.py, mne/viz/backends/_pyvista.py, tools/circleci_dependencies.sh, tutorials/clinical/20_seeg.py, tutorials/inverse/60_visualize_stc.py
This checks to see if depth peeling is [causing our new 3D rendering problems](https://github.com/mne-tools/mne-python/pull/10071#issuecomment-985047664). If it is, we can add a MNE_3D_OPTION_DEPTH_PEELING like we have for ANTIALIAS.
=> CI: Try no depth peeling

mne/viz/backends/renderer.py, mne/viz/backends/tests/test_renderer.py, requirements.txt, tools/azure_dependencies.sh
Test if VTK version still needs to be constrained for Windows.
Closes #10099
=> Remove constrain on vtk version for windows

doc/overview/people.rst
=> Adam to Core-Devs

doc/overview/people.rst
restores alphabetical order after #10111 and adds Alex R as well
=> update steering council page

doc/changes/latest.inc, mne/epochs.py, mne/tests/test_epochs.py
closes #10106
~~Should I add a whatsnew entry? Or is this too minor?~~
=> [MRG] FIX: Clearer (unambiguous) logging during Epochs instantiation

.github/workflows/linux_pip.yml, mne/conftest.py, tools/github_actions_dependencies.sh
Locally tests pass, let's see if CircleCI agrees.
=> MRG, MAINT: Add 3.10 to CIs

doc/changes/latest.inc, doc/conf.py, doc/sphinxext/gh_substitutions.py, doc/sphinxext/newcontrib_substitutions.py
I finally got this working, so long annoying `.. |new contrib| replace:: **new contrib**` !
=> newcontrib sphinx role [skip azp][skip github]

mne/viz/topomap.py
This is a #10130 followup
See https://github.com/mne-tools/mne-python/pull/10130#issuecomment-993664217
cc @drammock
=> MRG: Change intersphinx reference for MPL gridspec

mne/coreg.py, mne/gui/_coreg.py, mne/viz/backends/_abstract.py, mne/viz/backends/_notebook.py, mne/viz/backends/_qt.py
This small PR contains the changes about tooltips, some suggestions of improvement and bug fixes extracted from #10117
=> ENH: new coreg gui features

mne/gui/_coreg.py
This small PR fixes some elements of coreg based on https://github.com/mne-tools/mne-python/pull/10117#pullrequestreview-835362663
=> ENH: coreg GUI fixes

mne/epochs.py, mne/tests/test_epochs.py
follow up on Epochs annotations PR
=> cosmit + IO bug fix on epochs annotations

doc/install/index.rst, mne/gui/_ieeg_locate_gui.py, tutorials/clinical/10_ieeg_localize.py, tutorials/clinical/20_seeg.py, tutorials/clinical/30_ecog.py
Fixes review suggestions in https://github.com/openjournals/joss-reviews/issues/3897.
=> [ENH, MRG] Add dependencies to tutorials, fix GUI sizing

mne/epochs.py, tutorials/io/60_ctf_bst_auditory.py
=> [BUG] Fix tutorial from Epochs Concatenation

mne/viz/_brain/_brain.py, mne/viz/backends/_pyvista.py
This PR fixes issues found in https://github.com/mne-tools/mne-python/pull/10166#issuecomment-1003691825
=> WIP,FIX: pyvista 3d backend

mne/conftest.py
Let's see if this makes things green again.
=> FIX: Ignore statsmodels<->pandas issue

doc/changes/latest.inc, mne/epochs.py, mne/tests/test_epochs.py
=> MRG, BUG: Fix save-load baseline bug

doc/install/pre_install.rst
fixes whitespace glitch introduced in #10174
=> fix rST formatting glitch

doc/changes/latest.inc, mne/gui/_ieeg_locate_gui.py, mne/gui/tests/test_ieeg_locate_gui.py
Fixes https://github.com/mne-tools/mne-python/issues/10180.
I'm not sure I would use it, but it looks really cool and apparently Barry would like to use it so I have no problem adding it.
=> [ENH, MRG] Add maximum intensity projection button to ieeg locate gui 

examples/io/read_neo_format.py
Taking care of [linkcheck](https://app.circleci.com/pipelines/github/mne-tools/mne-python/12285/workflows/c3ccea08-5a2c-4e89-98d4-065ea60aeafb/jobs/40369) before @drammock can get to it :)
=> FIX: Fix neo link

doc/changes/latest.inc, mne/viz/_3d.py
| `main`        | PR           |
| ------------- |:-------------:|
| ![image](https://user-images.githubusercontent.com/2046265/149619612-079c543b-acf7-41c5-a2e8-d9b31d1b14b4.mov)     | ![image](https://user-images.githubusercontent.com/2046265/149619453-bbd9b8f1-97ce-4ff7-9676-d18ae5343b24.mov) |
WIP:
=> MRG: Change default coord frame and interaction style of plot_alignment() to match new behavior of Coreg UI

doc/changes/names.inc, doc/overview/governance.rst
Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/12371/workflows/e1a6a291-dc85-4b86-a085-025d028be830/jobs/40552
=> FIX: Linkcheck

mne/gui/tests/test_ieeg_locate_gui.py
Restores the test @alexrockhill removed in #10202
=> FIX: Restore test

mne/gui/_ieeg_locate_gui.py, mne/viz/_brain/_brain.py, mne/viz/utils.py
Fixes https://github.com/mne-tools/mne-python/issues/10225.
Sorry @BarryLiu97  I wrote the PR without thinking this might have been a good one for you, next time.
=> [BUG] Close renderer in ieeg locate GUI

LICENSE.txt, README.rst
- Fixes issue #10228
- Updates License dates on README.rst
- Updates License dates on LICENSE file
=> [MRG] License update (#10228)

doc/changes/latest.inc, mne/report/report.py, mne/report/tests/test_report.py, mne/utils/docs.py
Fixes #10164
@jasmainak would this already improve things for you a bit?
=> MRG: Better error message for bad tags in Report, and allow tags to be a string

doc/conf.py, doc/mri.rst, mne/channels/montage.py, mne/coreg.py, mne/gui/_coreg.py, mne/io/_digitization.py, mne/io/meas_info.py, mne/utils/docs.py
Splitting the changes from #10237 into smaller, separate PRs.
=> MRG: Documentation improvements extracted from #10237

doc/changes/latest.inc, mne/report/report.py, tutorials/intro/70_report.py
=> MRG: Add alpha parameter to Report.add_trans() to control head transparency

doc/changes/latest.inc, mne/coreg.py, mne/gui/_coreg.py, mne/tests/test_coreg.py
This is a first step towards resolving #10227
=> MRG: Publicly expose MRI fiducials in Coregistration class

doc/changes/latest.inc, mne/gui/_coreg.py, mne/gui/tests/test_coreg_gui.py
This exposes `Coregistration` via `CoregistrationUI.coreg`
Closes #10227
=> Publicly expose Coregistration instance from CoregistrationUI

tools/github_actions_dependencies.sh
Numba is out for 3.10 so let's add it back in.
=> MAINT: Numba on 3.10

mne/gui/_coreg.py
Partially extraced from #10242 and #10224
- status bar is now stored in `self._widgets`
- `_forward_widget_command()` has a docstring and new functionality (extracted from #10224)
This was worked out together with @GuillaumeFavelier
=> MRG: Refactor and extend a few things in CoregistrationUI

mne/gui/_coreg.py, mne/viz/backends/_qt.py
Also reorders and slightly changes text of MEG helmet / EEG electrode view options.
=> MRG: Lock CoregistrationUI widgets when placing fiducials

doc/changes/latest.inc, mne/filter.py, mne/tests/test_filter.py
=> BUG: Fix validation of low-level filt funcs

mne/gui/_coreg.py
This PR fixes the error with ICP:
```
Aligning using ICP
Start     median distance:  17.40 mm
ICP  1  median distance:  12.46 mm
File "<decorator-gen-563>", line 24, in _redraw
File "/home/guillaume/source/mne-python/mne/gui/_coreg.py", line 711, in _redraw
for key in self._redraws_pending:
RuntimeError: Set changed size during iteration
```
=> FIX: coreg GUI - ICP

mne/viz/ica.py
Fixes #10264.
Like discussed, I updated the description what info picks represent.
=> DOC: change picks description in ICA.plot_properties()

mne/gui/tests/test_gui_api.py, mne/viz/backends/_abstract.py, mne/viz/backends/_notebook.py, mne/viz/backends/_qt.py
This PR follows #10253 and refactors the GUI API, improve testing and overall consistency.
=> MNT: GUI API

mne/gui/_coreg.py, mne/gui/tests/test_coreg_gui.py
This is something that makes my life easier while working with @SophieHerbst 👌
=> Retain Coregistration instance after the CoregistrationUI window was closed

doc/links.inc, doc/overview/roadmap.rst
#10281 reminded me that our roadmap is a bit out of date. This brings it up to date, mostly by moving one "in-progress" to "done" (dask/parallel, thanks @agramfort @hoechenberger !) and several "open" to "in-progress" (things funded by CZI and hopefully soon NIH, but we're starting work regardless).
=> DOC: Update roadmap

doc/changes/latest.inc, mne/event.py, mne/tests/test_event.py
=> FIX : set event onset to first_samp not 0 with initial_value is True

mne/viz/backends/_notebook.py
This PR suggests a proper implementation of the multi-area dock system for the `notebook` 3d backend.
*It deals with some `XXX:` in there.*
=> MNT: multi-area dock system for the notebook 3d backend

doc/install/mne_python.rst
Following this post: https://mne.discourse.group/t/mne-python-installation-in-windows-does-not-work/4336/7
@mmagnuski I am not fully satisfied with the text, if you have a better idea, please propose a change. Maybe a warning that the spyder and the spyder-kernel version must match?
=> MRG: Update install instruction when using Spyder

doc/changes/latest.inc, examples/datasets/opm_data.py, examples/forward/left_cerebellum_volume_source.py, examples/inverse/read_inverse.py, examples/preprocessing/movement_detection.py, examples/time_frequency/source_power_spectrum_opm.py, examples/visualization/3d_to_2d.py, examples/visualization/eeg_on_scalp.py, mne/viz/_3d.py, mne/viz/tests/test_3d.py, tools/circleci_dependencies.sh, tutorials/clinical/20_seeg.py, tutorials/clinical/30_ecog.py, tutorials/forward/20_source_alignment.py, tutorials/forward/25_automated_coreg.py, tutorials/forward/30_forward.py, tutorials/forward/35_eeg_no_mri.py, tutorials/intro/40_sensor_locations.py, tutorials/inverse/35_dipole_orientations.py, tutorials/inverse/70_eeg_mri_coords.py, tutorials/inverse/80_brainstorm_phantom_elekta.py, tutorials/inverse/85_brainstorm_phantom_ctf.py, tutorials/inverse/90_phantom_4DBTi.py
Closes #10308
@dasdiptyajit feel free to see if this fixes your problem
Our input validation for `trans` was deficient, this fixes it. cc @alexrockhill since I think this was your code at some point.
It also touches all tutorials that use `plot_alignment` to see if it breaks anything...
=> BUG: Fix bug with plot_alignment checks

doc/changes/latest.inc, examples/preprocessing/movement_compensation.py, examples/preprocessing/movement_detection.py, examples/visualization/3d_to_2d.py, tutorials/preprocessing/60_maxwell_filtering_sss.py
Fixes https://github.com/mne-tools/mne-python/issues/10312
=> [BUG, MRG] Fix plot_alignment bugs

azure-pipelines.yml, doc/changes/latest.inc, mne/conftest.py, mne/utils/docs.py, mne/viz/_figure.py, mne/viz/backends/_utils.py, mne/viz/raw.py, mne/viz/tests/test_raw.py, mne/viz/utils.py
Closes https://github.com/mne-tools/mne-qt-browser/issues/45
cc @marsipu
=> API: Change name to qt

paper.md
=> add MNE R01

paper.md
Adds funding before publication for https://github.com/openjournals/joss-reviews/issues/3897
=> Add funding

paper.md
=> One last fix

paper.md
Two authors should have been mentioned in funding
=> Add funding coverage

mne/datasets/config.py, mne/io/nirx/tests/test_nirx.py
@rob-luke made me realize that I didn't need to add some files to the testing data that I added for #10277, so we've removed them from the testing dataset. This updates us to the latest version.
=> MAINT: Update NIRx tests

mne/annotations.py, mne/forward/forward.py, mne/io/base.py, mne/io/tests/test_raw.py, mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py, mne/tests/test_annotations.py, mne/tests/test_event.py, mne/utils/numerics.py
Closes #10195
This one took a long time, but hopefully with the added tests, `logger.debug` calls, and debugging code in the tests (in case something breaks) things will be easier to fix next time we have problems with Annotations.
@jsosulski @kcsaba12 feel free to test this branch. I think it makes the example from #10195 work as expected
=> BUG: Fix bug with crop and annot

doc/changes/latest.inc
=> DOC: Latest

doc/changes/latest.inc, mne/beamformer/_lcmv.py, mne/beamformer/resolution_matrix.py, mne/beamformer/tests/test_lcmv.py, mne/utils/docs.py, tutorials/inverse/50_beamformer_lcmv.py
=> API: Deprecate max_ori_out

mne/dipole.py
Fixes a very small typo that I think I wrote actually, sorry!
=> [DOC, BUG] Fix very small typo

mne/source_estimate.py, mne/utils/docs.py
Fixes https://github.com/mne-tools/mne-python/issues/10374.
=> [BUG, DOC, MRG] Fix volume source estimate type

doc/changes/latest.inc, mne/viz/_brain/_brain.py
Fixes leftovers from https://github.com/mne-tools/mne-python/pull/10373
=> [DOC, MRG] Small fixes

doc/install/contributing.rst
Closes #10329
Feel free to merge if you're happy @mmagnuski
=> DOC: Update contrib instructions

mne/utils/config.py
One more to sneak into 1.0. Needs https://github.com/pyvista/pyvista/pull/2250 which will hopefully be merged soon.
=> ENH: Safer sys_info

doc/changes/latest.inc, mne/utils/config.py
Closes #10398
Feel free to try it @hoechenberger
=> FIX: VTK Version

mne/utils/check.py, mne/utils/tests/test_check.py
Closes #10404
A fun little regex exercise :)
=> BUG: Fix backward compat check_version

mne/channels/montage.py
=> [BUG, MRG] Fix typo [skip azp] [skip actions]

mne/utils/config.py
@hoechenberger 
https://user-images.githubusercontent.com/2365790/156887721-f09aabcb-f489-4b25-b569-7b2ced5efc67.mp4
=> FIX: Make sys_info print incrementally

doc/changes/latest.inc, doc/changes/names.inc, mne/io/nihon/nihon.py
Fixes #10428 similar to [this PR](https://github.com/mne-tools/mne-python/pull/9384)
=> FIX: support latin1 in channels in nihon files

doc/changes/latest.inc, mne/io/nihon/nihon.py, mne/io/nihon/tests/test_nihon.py
fix bug so that read_raw_nihon handles duplicates in channels
=> FIX handle duplicate channels

tools/circleci_dependencies.sh
Let's see if this fixes https://app.circleci.com/pipelines/github/mne-tools/mne-python/13301/workflows/ae3b8cb2-12da-449b-8656-235e43b6877d/jobs/42590
=> FIX: Upgrade on CircleCI

doc/install/check_installation.rst, doc/install/installers.rst
Closes #10446
Once this is merged, I plan to start the 1.0 release process
=> DOC: Document name properly [skip azp] [skip actions]

.github/workflows/codespell_and_flake.yml, .github/workflows/compat_minimal.yml, .github/workflows/compat_old.yml, .github/workflows/linux_conda.yml, .github/workflows/linux_pip.yml, .github/workflows/macos_conda.yml
It looks like we don't need to use [bulldozer](https://github.com/palantir/bulldozer) to get automerge. (@hoechenberger I did look into conda-forge -- they have [their own action](https://github.com/conda-forge/automerge-action) FYI). GitHub provides this natively, but we need to set up branch protection rules saying that status commits must pass -- and for this, we need better / more specific GH actions job names, which I've added here. Then I'll add branch protection rules (that can always be ignored by maintainers, as this is needed from time to time) and then there should be a button added to PRs that says "squash+merge once status checks pass" or so:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-mergin …
=> ENH: Add automerge

doc/install/installers.rst, doc/install/installers_platform_selector.html
To be merged once the new installers have been released.
See https://github.com/mne-tools/mne-installers/pull/111
=> Update links to 1.0.0_1 installers

doc/changes/names.inc, mne/datasets/config.py, tutorials/clinical/30_ecog.py
Should fix failures like https://app.circleci.com/pipelines/github/mne-tools/mne-python/13492/workflows/5e4ace34-cc33-442d-a65b-6bb6c2e840ac/jobs/42995
EDIT: And https://app.circleci.com/pipelines/github/mne-tools/mne-python/13491/workflows/3472533a-df7c-4c10-9a06-f3bc9faeffa4/jobs/42994
Will merge and backport once CIs are happy
=> BUG: Fix URL

mne/datasets/_fsaverage/base.py, mne/datasets/_phantom/base.py, mne/datasets/config.py
fetch_fsaverage was now failing for example
=> URL change due to OSF API change

doc/changes/latest.inc, examples/visualization/brain.py, mne/viz/_brain/_brain.py, mne/viz/backends/_pyvista.py, tutorials/inverse/35_dipole_orientations.py
=> [BUG, MRG] Fix Quiver3D default behavior

doc/install/installers_platform_selector.html
Bump for https://github.com/mne-tools/mne-installers/releases/tag/v1.0.2
=> DOC: Update installers

mne/tests/test_coreg.py
This is just a little test I wrote because it seemed not be true for some data that I have. Given that it works on `main`, it suggests I perhaps used `mne coreg` before we had some `talxfm` fixes in place (?). In any case, might as well add it for consistency!
=> MAINT: Extra test for coreg

doc/changes/latest.inc, mne/conftest.py, mne/coreg.py, mne/gui/_coreg.py, mne/gui/tests/test_coreg_gui.py, mne/tests/test_coreg.py
=> MRG: Fix coreg UI didn't start if only a high-resolution head model was available

examples/inverse/multi_dipole_model.py
The new example looks great @wmvanvliet, I just saw that there wasn't a Sphinx reference and recently added them to all the examples so just adding it for consistency. I know there is a long-format version but I think it's nice to have a short standardized version to facilitate referencing.
=> [MAINT, MRG] Add sphinx example reference

tutorials/preprocessing/40_artifact_correction_ica.py
This follows up on the recent PR to add tips to the main ICA tutorial so that users know about the keyboard shortcuts.
=> [ENH, MRG] Add tip for ica properties plot

mne/bem.py
this fixes a glitch in a freesurfer shell script on certain versions of freesurfer.
=> fix for broken subjdir

mne/viz/_3d.py, mne/viz/_mpl_figure.py, mne/viz/evoked.py, mne/viz/tests/test_evoked.py, mne/viz/utils.py
I updated to latest `matplotlib` main and got some deprecation warnings, this should bring us into compliance.
=> MAINT: Deal with mpl deps

doc/_static/versions.json, doc/conf.py
Closes #10598
Fix for backward incompat change https://github.com/pydata/pydata-sphinx-theme/pull/604 which fails silently and gives bad URLs
=> MAINT: Fix for pydata-sphinx-theme

doc/changes/latest.inc, mne/utils/config.py
=> [ENH] Add sys info for mne-icalabel

mne/preprocessing/_csd.py
cc @agramfort @alexrockhill
This simplifies #10619 via @agramfort's proposal
=> Simplify #10619

mne/gui/_ieeg_locate_gui.py
Fixes issue where info was locked.
=> [BUG, MRG] fix info write access

mne/time_frequency/multitaper.py
I'm just gonna check what the tests are doing.
=> WIP: Fix mne.time_frequency.multitaper Nyquist adjustment

doc/changes/1.0.inc, mne/io/edf/edf.py
=> Backport #10638

mne/viz/topomap.py
=> Improvements to the plot_topomap docstring (#10651)

Makefile, README.rst, doc/changes/latest.inc, doc/conf.py, doc/install/contributing.rst, doc/references.bib, examples/decoding/ems_filtering.py, examples/time_frequency/time_frequency_global_field_power.py, mne/channels/channels.py, mne/forward/forward.py, mne/io/fiff/tests/test_raw_fiff.py, mne/stats/_adjacency.py, mne/stats/cluster_level.py, mne/stats/parametric.py, mne/surface.py, mne/utils/docs.py, tutorials/clinical/10_ieeg_localize.py, tutorials/forward/90_compute_covariance.py, tutorials/machine-learning/50_decoding.py, tutorials/stats-sensor-space/10_background_stats.py, tutorials/stats-sensor-space/40_cluster_1samp_time_freq.py, tutorials/stats-sensor-space/75_cluster_ftest_spatiotemporal.py, tutorials/stats-source-space/20_cluster_1samp_spatiotemporal.py, tutorials/stats-source-space/30_cluster_ftest_spatiotemporal.py, tutorials/stats-source-space/60_cluster_rmANOVA_spatiotemporal.py, tutorials/stats-source-space/70_cluster_rmANOVA_time_freq.py, tutorials/time-freq/50_ssvep.py
closes #10595
this is a massive PR to update the docs with all I have learned in:
- #10595
- #10602 
- #10604
I think I also identified and fixed several typos and/or mistakes, but I would be very happy for some thorough reviews to ensure that I don't introduce false facts.
=> [MRG] DOC: clarify cluster-based permutation testing

doc/changes/latest.inc, mne/utils/docs.py, mne/viz/_brain/_brain.py, mne/viz/_brain/tests/test_brain.py, mne/viz/backends/_pyvista.py
Fixes https://github.com/mne-tools/mne-python/issues/10660.
=> [ENH, MRG] Add mne.viz.Brain.get_view method

Makefile, README.rst, doc/conf.py, doc/install/contributing.rst, doc/references.bib, examples/decoding/ems_filtering.py, examples/time_frequency/time_frequency_global_field_power.py, mne/channels/channels.py, mne/forward/forward.py, mne/io/fiff/tests/test_raw_fiff.py, mne/stats/_adjacency.py, mne/stats/cluster_level.py, mne/stats/parametric.py, mne/surface.py, mne/utils/docs.py, tutorials/clinical/10_ieeg_localize.py, tutorials/machine-learning/50_decoding.py, tutorials/stats-sensor-space/10_background_stats.py, tutorials/stats-sensor-space/40_cluster_1samp_time_freq.py, tutorials/stats-sensor-space/75_cluster_ftest_spatiotemporal.py, tutorials/stats-source-space/20_cluster_1samp_spatiotemporal.py, tutorials/stats-source-space/30_cluster_ftest_spatiotemporal.py, tutorials/stats-source-space/60_cluster_rmANOVA_spatiotemporal.py, tutorials/stats-source-space/70_cluster_rmANOVA_time_freq.py, tutorials/time-freq/50_ssvep.py
=> Backport #10658

doc/changes/latest.inc, mne/io/bti/bti.py, mne/io/bti/tests/test_bti.py
Fixes a bug from the mailing list. Feel free to test @britta-wstnr !
=> BUG: Fix bug with BTi loc

mne/gui/_ieeg_locate_gui.py
This just fixes a read-only view file error.
=> [MAINT, MRG] Fix read-only error

mne/time_frequency/tfr.py, mne/utils/docs.py, mne/viz/_brain/_brain.py, mne/viz/topomap.py
Just fixes some copy-paste documentation with a reference in the docdict.
=> [MAINT, MRG] Refactor DRY Topo doc

.github/ISSUE_TEMPLATE/config.yml
=> allow blank issues

doc/_static/style.css
Fixes #10724
cc @larsoner @drammock
=> MRG: Remove tutorial thumbnail popovers

examples/visualization/montage_sgskip.py
=> fix example plotting montages

doc/_static/style.css, requirements_doc.txt
Ideally this would wait for https://github.com/pydata/pydata-sphinx-theme/pull/731 and would update the commit hash accordingly, but don't treat that as a blocker.
=> style fixes for latest theme version [skip azp][skip actions]

doc/changes/latest.inc, tutorials/forward/80_fix_bem_in_blender.py
Fixes https://github.com/mne-tools/mne-python/issues/10684 part.
=> [BUG, MRG] Fix links, add note to Blender tutorial

doc/changes/latest.inc, doc/conf.py, requirements_doc.txt, tutorials/forward/80_fix_bem_in_blender.py
Fixes https://github.com/mne-tools/mne-python/issues/10771.
=> [ENH, MRG] First youtube video in docs! 

doc/changes/latest.inc, mne/evoked.py, mne/viz/_3d.py
=> MRG: Default to "terrain" interaction style in field plots

doc/changes/latest.inc, tutorials/clinical/10_ieeg_localize.py
=> [ENH, MRG] Add intracranial electrode contact location video

doc/changes/latest.inc, mne/io/meas_info.py
Fixes #10471 (correctly report the number of digitized points available).
=> Fix info._repr_html_

.github/workflows/macos_conda.yml, tools/get_minimal_commands.sh
First let's see which command is actually hanging
Closes #10805
=> WIP: Check macOS problem [skip azp] [skip circle]

doc/conf.py
Fixes warning causing CIs to fail in https://github.com/mne-tools/mne-python/pull/10824.
=> [MAINT, MRG] Fix nilearn intersphinx

examples/forward/source_space_morphing.py
=> update path handling in examples/forward/source_space_morphing.py

examples/decoding/decoding_rsa_sgskip.py
closes #10808
[skip azp][skip actions]
=> update path handling in examples

doc/conf.py
Companion to #10841
Docs build on my machine with this at least!
=> MAINT: Reduce doc build warning ignores

examples/forward/left_cerebellum_volume_source.py
Updated path handling
project 10809
=> [DOC, MRG] path fix adeline

mne/conftest.py, mne/decoding/tests/test_search_light.py, mne/source_space.py, mne/tests/test_source_space.py, mne/viz/_3d.py
Let's get CIs green again.
Closes #10853
Works around #10852 but let's keep it open for @agramfort for a proper fix
=> MAINT: Better path handling

examples/inverse/snr_estimate.py
Sprint 2022 - closes #10817 
Path handling changes: /examples/inverse/snr_estimate.py
=> [Doc, WIP] update path handling

examples/inverse/multidict_reweighted_tfmxne.py
Sprint 2022 - closes #10816 
update path handling: examples/inverse/multidict_reweighted_tfmxne.py
=> [DOC, WIP] update path handling 2

examples/io/read_xdf.py
Sprint 2022 - closes #10821 
update path handling: examples/io/read_xdf.py
=> [DOC] path handling 3

examples/preprocessing/movement_compensation.py
Sprint 2022 - closes #10822 
update path handling: examples/preprocessing/movement_compensation.py
=> [DOC] path handling 4

examples/preprocessing/movement_detection.py, examples/preprocessing/muscle_detection.py, examples/preprocessing/muscle_ica.py
closes #10831 
closes #10833 
closes #10834
=> Fix path handing for examples/preprocessing/*

mne/datasets/config.py
Let's see if it works again...
=> MAINT: Try using GH for testing again

examples/inverse/morph_surface_stc.py
Sprint 2022 - closes #10815 
update path handling - examples/inverse/morph_surface_stc.py
=> [DOC] path handling 5

examples/datasets/opm_data.py
Sprint 2022 - closes #10807 
update path handling: examples/datasets/opm_data.py
=> [DOC] path handling 6

tutorials/clinical/10_ieeg_localize.py, tutorials/clinical/20_seeg.py, tutorials/clinical/30_ecog.py
Update path handling 
path handling updated in tutorials/clinical folder:
10_ieeg_localize.py
20_seeg.py
30_ecog.py
=> [DOC] update path handling - clinical tutorial folder

doc/conf.py, doc/install/installers.rst
spring 2022 - closes #10698 
changes hourglass on installers page to be consistent with other icons
=> [DOC] hourglass icon change

tutorials/epochs/10_epochs_overview.py, tutorials/epochs/20_visualize_epochs.py, tutorials/epochs/30_epochs_metadata.py, tutorials/epochs/50_epochs_to_data_frame.py, tutorials/epochs/60_make_fixed_length_epochs.py
sprint 2022 - updating path handling
updates path handling in epochs folder of tutorials:
10_epochs_overview.py
20_visualize_epochs.py
30_epochs_metadata.py
50_epochs_to_data_frame.py
60_make_fixed_length_epochs.py
=> [DOC] tutorials/epochs path handling 

examples/inverse/mixed_source_space_inverse.py, mne/forward/_make_forward.py, mne/forward/tests/test_make_forward.py, mne/utils/docs.py
=> fix info type checking (allow path-like)

mne/decoding/tests/test_search_light.py
remove pytest.skip for new sklearn
=> fix for new sklearn

tutorials/inverse/10_stc_class.py, tutorials/inverse/20_dipole_fit.py, tutorials/inverse/70_eeg_mri_coords.py, tutorials/inverse/80_brainstorm_phantom_elekta.py, tutorials/inverse/85_brainstorm_phantom_ctf.py
Sprint 2022 - updating path handling
updating path handling in tutorials/inverse:
10_stc_class.py
20_dipole_fit.py
70_eeg_mri_coords.py
80_brainstorm_phantom_elekta.py
85_brainstorm_phantom_ctf.py
=> [DOC] updating path handling inverse folder

examples/preprocessing/otp.py
closes #10835
Removed Unused Import 'op'
The parenthesis is required for the 'read_raw_fif' import.
=> Removed unused import and updated the path.

doc/_includes/institutional-partners.rst, doc/changes/names.inc
Thanks [Circle weekly linkcheck](https://app.circleci.com/pipelines/github/mne-tools/mne-python/15100/workflows/8dc7afef-cb75-4bd8-96fb-7e6b883e1375/jobs/46444).
@bloyl let me know if you have a better link for you like https://www.linkedin.com/in/lukebloy , the page I linked to seems to just have your name + email.
=> MAINT: Update CHOP links

tutorials/intro/10_overview.py, tutorials/intro/15_inplace.py, tutorials/intro/20_events_from_raw.py, tutorials/intro/30_info.py
Sprint 2022 - update path handling
update path handling in tutorials/intro:
10_overview.py
15_inplace.py
20_events_from_raw.py
30_info.py
=> [DOC] path handling intro folder

doc/glossary.rst, mne/datasets/_fetch.py, mne/forward/forward.py, mne/source_space.py
Closes #10901
@jadrew43 can you look and see if these are readable enough?
=> DOC: Document Forward and SourceSpaces

doc/changes/latest.inc, mne/io/reference.py, mne/io/tests/test_reference.py
=> BUG: Fix bug with Epochs.add_reference_channels

.github/workflows/linux_pip.yml, azure-pipelines.yml, tools/setup_xvfb.sh
Let's see if we can see why pip-pre is failing on Linux
=> MAINT: Fix Qt issue

doc/changes/latest.inc, mne/epochs.py, mne/evoked.py, mne/io/base.py, mne/io/edf/tests/test_edf.py, mne/io/fiff/tests/test_raw_fiff.py, mne/source_estimate.py, mne/time_frequency/tests/test_tfr.py, mne/time_frequency/tfr.py, mne/utils/docs.py
we said we'd make this API change for 0.23 but it never happened.
=> to_data_frame API change

doc/changes/latest.inc, mne/viz/ica.py
Fixes: #10934 
Fix the doc string.
=> [DOC] Fix ICA plot_sources "picks" documentation

doc/changes/latest.inc, mne/surface.py, mne/tests/test_surface.py
FIx a bug when calling _project_onto_surface with method != "accurate" and return_nn == True.
=> Fix bug in _project_onto_surface

environment.yml, requirements.txt, server_environment.yml
a fix (temporary) for #10939, until we discover the root cause.
=> exclude pyvista 0.35.2

tools/circleci_dependencies.sh
follow-up to #10949 which didn't fully fix the problem
=> pin pyvista on CircleCI

azure-pipelines.yml, mne/utils/_testing.py
=> MRG: Replace check_version from _testing.py with the same function in check.py

doc/conf.py, examples/decoding/decoding_spoc_CMC.py, mne/beamformer/_lcmv.py, mne/channels/montage.py, mne/commands/tests/test_commands.py, mne/decoding/base.py, mne/forward/_make_forward.py, mne/inverse_sparse/mxne_inverse.py, mne/io/array/tests/test_array.py, mne/io/artemis123/artemis123.py, mne/io/ctf/ctf.py, mne/io/ctf/hc.py, mne/io/ctf/markers.py, mne/io/edf/tests/test_edf.py, mne/io/fiff/tests/test_raw_fiff.py, mne/io/tests/test_meas_info.py, mne/io/tests/test_raw.py, mne/source_space.py, mne/tests/test_epochs.py, mne/tests/test_evoked.py, mne/tests/test_source_estimate.py, mne/time_frequency/tests/test_tfr.py, mne/transforms.py, mne/utils/config.py, mne/utils/docs.py, mne/viz/_mpl_figure.py, mne/viz/tests/test_epochs.py
Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/15491/workflows/fdd936b6-5619-4a06-8ef6-2ef1276a6b01/jobs/47264
=> MAINT: Deal with SciPy<->sklearn dep

doc/changes/latest.inc, mne/time_frequency/tfr.py, mne/viz/misc.py, mne/viz/tests/test_misc.py, mne/viz/tests/test_topo.py, mne/viz/tests/test_topomap.py, mne/viz/topomap.py
Part of https://github.com/mne-tools/mne-python/pull/10920.
=> [ENH, MRG] Cast complex evoked to power for visualization

doc/changes/latest.inc, mne/time_frequency/psd.py, mne/time_frequency/tests/test_psd.py
=> BUG: Fix bug with median bias

doc/changes/latest.inc, mne/time_frequency/tests/test_tfr.py, mne/time_frequency/tfr.py
Part of https://github.com/mne-tools/mne-python/pull/10920.
=> [ENH, MRG] Add provenance to TFR baseline application

mne/time_frequency/psd.py, mne/time_frequency/tests/test_psd.py
As an intellectual challenge I followed https://github.com/mne-tools/mne-python/issues/10996#issuecomment-1203239429 to its conclusion, but happy to use @mmagnuski's version instead if it works the same or better!
=> BUG: Fix bug with nan handling

doc/conf.py, mne/source_estimate.py, mne/utils/docs.py, mne/viz/epochs.py, mne/viz/ica.py, mne/viz/raw.py, requirements_doc.txt
some low-hanging fruit that was left over from the sprint.
=> Various docfixes

doc/sphinxext/gen_commands.py, mne/export/tests/test_export.py
=> MAINT: Work around eeglabio warning

mne/viz/backends/_notebook.py, mne/viz/backends/_qt.py
Follow up from https://github.com/mne-tools/mne-python/pull/10913
=> [MAINT] Followup backend fix

mne/report/report.py, mne/utils/docs.py, mne/viz/ica.py, mne/viz/topomap.py
Minor documentation improvement.
=> [DOC, MRG] Detail what picks=None does for ICA

mne/bem.py, mne/commands/mne_flash_bem.py, mne/commands/tests/test_commands.py, mne/datasets/_fetch.py, mne/datasets/eegbci/eegbci.py, mne/datasets/tests/test_datasets.py, mne/datasets/utils.py, mne/gui/tests/test_coreg.py, mne/parallel.py, mne/utils/__init__.py, mne/utils/_testing.py, mne/utils/tests/test_testing.py, mne/viz/_brain/tests/test_notebook.py
=> Deprecations 1.1

doc/conf.py
=> Fix style of 'bool' x-ref by resolving to the class instead of the std:label

mne/time_frequency/csd.py, mne/time_frequency/tests/test_csd.py
When I took out `kwargs` in this PR #10986, I really needed to put back in some of the args. This is just cleaning that up.
=> [MAINT, MRG] Add params to csd_tfr

.github/workflows/codespell_and_flake.yml, Makefile, ignore_words.txt, mne/coreg.py, mne/decoding/ssd.py, mne/evoked.py, mne/io/brainvision/brainvision.py, mne/io/curry/curry.py, mne/io/nihon/nihon.py, mne/preprocessing/tests/test_eeglab_infomax.py, mne/utils/dataframe.py, tutorials/stats-sensor-space/75_cluster_ftest_spatiotemporal.py
=> fixes for latest codespell release

doc/changes/latest.inc, mne/utils/docs.py, mne/viz/topomap.py, tutorials/time-freq/20_sensors_time_frequency.py
=> allow dict for PSD topomap parameter "bands" 

doc/conf.py, mne/conftest.py, mne/viz/backends/_abstract.py, mne/viz/evoked.py
Let's get things green, then go back and fix (in case it's not trivial)
=> MAINT: Ignore dep temporarily

mne/viz/tests/test_epochs.py, tutorials/epochs/20_visualize_epochs.py
tutorial and tests changes that ought to have been in #11050
=> update tutorial & tests for new plot_topomap bands API

mne/time_frequency/tfr.py
Fixes https://github.com/mne-tools/mne-python/issues/10695.
Fixes minor issue related to indentation of admonitions.
=> [DOC] Fix rendering of TFR docstrings

doc/conf.py, examples/decoding/decoding_rsa_sgskip.py, examples/time_frequency/time_frequency_global_field_power.py, examples/visualization/brain.py, mne/conftest.py, mne/fixes.py, mne/label.py, mne/time_frequency/tests/test_tfr.py, mne/utils/check.py, mne/viz/_3d.py, mne/viz/_brain/tests/test_brain.py, mne/viz/_mpl_figure.py, mne/viz/backends/_utils.py, mne/viz/backends/tests/test_abstract_notebook.py, mne/viz/circle.py, mne/viz/epochs.py, mne/viz/evoked.py, mne/viz/ica.py, mne/viz/tests/test_3d.py, mne/viz/tests/test_3d_mpl.py, mne/viz/tests/test_evoked.py, mne/viz/tests/test_ica.py, mne/viz/tests/test_raw.py, mne/viz/tests/test_topomap.py, mne/viz/topomap.py, mne/viz/utils.py, tutorials/clinical/30_ecog.py, tutorials/time-freq/50_ssvep.py
It fails locally but it's some progress already.
Closes #11063
Closes #11062
=> MAINT: Work around matplotlib bugs and dep

mne/cov.py, mne/utils/docs.py, mne/viz/epochs.py, mne/viz/raw.py, mne/viz/topomap.py
first steps toward #11032.  Only touches docstrings.
=> plot_topomap docstring dedup

examples/simulation/plot_stc_metrics.py, mne/simulation/metrics/metrics.py, mne/simulation/metrics/tests/test_metrics.py
=> MAINT: Code cleanups for metrics

doc/changes/latest.inc, mne/gui/_coreg.py, mne/gui/tests/test_coreg.py, mne/viz/backends/_qt.py
@olafhauk feel free to test and merge/approve if you're happy
=> FIX: Update helmet during ICP

examples/inverse/psf_ctf_vertices.py
Fixes minor issue with unnecessary documentation line in PSF/CTF example.
Removed line
method = 'MNE'  # can be 'MNE' or 'sLORETA'
because method is not used in the example.
Any …
=> DOC: removed unnecessary line in PSF example

doc/changes/latest.inc, doc/inverse.rst, mne/minimum_norm/__init__.py, mne/minimum_norm/inverse.py, mne/minimum_norm/tests/test_inverse.py, mne/time_frequency/tfr.py
The MNE methods part of https://github.com/mne-tools/mne-python/pull/10920.
=> [ENH, MRG] Add time-frequency epoch source estimation

mne/utils/_logging.py
Example: Fixes #11117.
Fixed typo in example
=> [FIX] Typo in example

doc/changes/latest.inc, doc/install/contributing.rst, mne/simulation/tests/test_metrics.py, mne/utils/docs.py, mne/utils/tests/test_docs.py, mne/viz/_brain/_brain.py, mne/viz/_brain/tests/test_brain.py
follow-up of #11097 
closes #11111
=> Use FutureWarnings instead of DeprecationWarnings 

mne/viz/backends/tests/test_abstract_notebook.py
The upstream fix is in, so this should work again
=> MAINT: Restore matplotlib test

tutorials/clinical/30_ecog.py
fixes CircleCI after https://github.com/mne-tools/mne-bids/pull/1061
=> include . in BIDS extension in ECoG tutorial

tutorials/io/20_reading_eeg_data.py
=> DOC: fix link to BV spec

doc/conf.py, mne/conftest.py, tutorials/preprocessing/35_artifact_correction_regression.py
Should fix the failure observed by @wmvanvliet in https://github.com/mne-tools/mne-python/pull/11046/
=> MAINT: Avoid failures due to distutils

doc/changes/names.inc
The best I could do to fix our linkcheck failure:
https://app.circleci.com/pipelines/github/mne-tools/mne-python/16194/workflows/d606325b-39eb-4712-b060-dea32139cdb4/jobs/48753
=> MAINT: Update link

examples/inverse/psf_volume.py, requirements_testing.txt, tools/azure_dependencies.sh, tools/github_actions_dependencies.sh
Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/16244/workflows/f81a68f0-e4ae-4eac-97cf-ab6fe41d7306/jobs/48858
=> MAINT: Reduce memory consumption

doc/changes/latest.inc, mne/io/proj.py, mne/io/tests/test_proj.py
=> Add == and != methods between Projection

doc/changes/latest.inc, doc/changes/names.inc, mne/evoked.py, mne/viz/_proj.py, mne/viz/evoked.py, mne/viz/ica.py, mne/viz/tests/test_evoked.py
Reverts mne-tools/mne-python#11017
closes #11149 
reopens #10612
=> Revert "[MRG, ENH] Use spatial_colors by default in Evoked.plot()"

.github/workflows/circle_artifacts.yml
=> MAINT: Limit redirector check

mne/datasets/config.py
related to:
- https://github.com/mne-tools/mne-python/issues/11113
=> [MRG] update testing dataset

requirements_doc.txt
=> MAINT: Work around zmq wheel bug

doc/changes/latest.inc, mne/source_space.py, mne/tests/test_source_space.py
=> DOC: Fix docs of surf source spaces

examples/inverse/label_activation_from_stc.py, examples/preprocessing/eog_artifact_histogram.py, tutorials/preprocessing/50_artifact_correction_ssp.py
this should hopefully fix our CircleCI build_docs_main failures du jour.
=> fixes for deprecations in MPL 3.6

mne/time_frequency/spectrum.py, mne/time_frequency/tests/test_spectrum.py
closes #11177
new test fails on main and passes locally.
also includes a small refactor of two other spectrum tests, to make more DRY.
=> Fix spectrum proj

doc/changes/latest.inc, mne/minimum_norm/inverse.py, mne/minimum_norm/tests/test_inverse.py
=> BUG: Check reference in apply_inverse_epochs

doc/changes/latest.inc, mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py
Fixes bug reported here https://mne.discourse.group/t/ica-find-bads-muscle-gives-a-typeerror/5619/2.
=> [BUG, MRG] Fix bug in find_bads_muscle

examples/datasets/brainstorm_data.py
=> reduce memory

mne/time_frequency/spectrum.py, mne/time_frequency/tests/test_spectrum.py, tutorials/time-freq/20_sensors_time_frequency.py
=> add EpochsSpectrum.average()

mne/conftest.py, mne/viz/backends/_notebook.py
Will merge once it comes back green
=> MAINT: Fix notebook backend

doc/overview/people.rst
this new section will be referenced in our CoC, once https://github.com/mne-tools/.github/pull/1/ is merged.
=> add CPGRL doc section

mne/commands/mne_kit2fiff.py
The command to install the package is `pip install mne-kit-gui`
=> DOC:  fix mne-kit-gui package name

doc/changes/latest.inc, doc/changes/names.inc, mne/channels/montage.py
None
Just changing documentation to reflect correct values for coord_frame
non important
=> Fix make_dig_montage documentation for correct coord_frame values

azure-pipelines.yml, requirements.txt
Work around https://github.com/matplotlib/matplotlib/issues/24155
=> MAINT: Fix CIs

doc/changes/latest.inc, mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py, mne/viz/ica.py
=> BUG: Maintain ica.reject_ on I/O round-trip

.github/workflows/codespell_and_flake.yml, Makefile, mne/io/eeglab/tests/test_eeglab.py
Fixes failures in codespell on `main`.
=> [MAINT, MRG] Fix codespell

.circleci/config.yml, tools/circleci_download.sh, tools/get_minimal_commands.sh, tools/get_testing_version.sh
Should make failures like this more clear
https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=22408&view=logs&jobId=d2de176e-a8da-5d2d-82f1-e561f5072d99&j=d2de176e-a8da-5d2d-82f1-e561f5072d99&t=31c9678a-d931-5c83-a3af-265696269d2a
=> MAINT: Better check of bash commands

doc/changes/latest.inc, doc/changes/names.inc, mne/utils/mixin.py
Fixes #11262.
Check `tmin` and `tmax` types for `crop` for `TimeMixin`.
=> check type tmin tmax timemixin

doc/changes/latest.inc, doc/changes/names.inc, mne/utils/mixin.py
Small fix for #11262
https://mne.tools/dev/whats_new.html formatting: was missing backticks in latest.inc. Personal site was http and not https in names.inc (updated gh profile as well).
=> latest.inc formatting

doc/install/installers.rst
last step of 1.2.1 patch release. All URLs tested already so I'll merge without waiting for CIs.
=> update installer links to 1.2.1

doc/changes/latest.inc, doc/inverse.rst, examples/inverse/dics_epochs.py, mne/beamformer/__init__.py, mne/beamformer/_dics.py, mne/beamformer/tests/test_dics.py
The beamformer methods part of https://github.com/mne-tools/mne-python/pull/10920.
=> Add time-frequency resolved DICS beamformer

doc/changes/latest.inc, mne/bem.py, mne/defaults.py, mne/export/tests/test_export.py, mne/io/eeglab/eeglab.py, mne/io/eeglab/tests/test_eeglab.py, mne/tests/test_bem.py, mne/time_frequency/tests/test_spectrum.py, mne/utils/__init__.py, mne/utils/check.py, mne/utils/docs.py
=> Fix eeglab ch pos units

doc/changes/latest.inc, mne/_freesurfer.py, mne/tests/test_coreg.py
Looks like I never added a very good test for `unscale=True`, because the logic was backward :(
=> BUG: Fix bug with unscale=True

mne/time_frequency/spectrum.py
Just a small tweak that I realized was incorrect
=> DOC: Document default

doc/conf.py
Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/17037/workflows/666aa313-3632-4165-b6d0-f5fc4deab93b/jobs/50533
=> MAINT: Fix docs

mne/evoked.py, mne/io/array/array.py, mne/io/meas_info.py
going from: 
To:
See issue here: https://mne.tools/stable/generated/mne.io.RawArray.html
=> Fix docstring list syntax

doc/conf.py, mne/conftest.py, mne/io/ctf/markers.py, mne/label.py, mne/utils/config.py, mne/viz/backends/_utils.py, mne/viz/ica.py, requirements_doc.txt
Let's see if https://github.com/joblib/threadpoolctl/issues/131 is fixed
=> TST: Test threadpoolctl

doc/changes/latest.inc, doc/changes/names.inc, mne/viz/misc.py, tutorials/preprocessing/25_background_filtering.py
Example: Edits for #7678 .
plot_filter - changed linewidth parameter to be the same value for all 3 plots + added grid to the plots
plot_ideal_filter - fixed the alpha argument not used in the function; changed linewidth
=> Update plot_filter, plot_ideal_filter functions

doc/changes/latest.inc, mne/channels/channels.py, mne/channels/tests/test_montage.py, mne/io/pick.py, mne/viz/epochs.py, mne/viz/evoked.py, mne/viz/tests/test_epochs.py
=> BUG: Fix bug with plot_epochs_image

doc/conf.py, tutorials/preprocessing/60_maxwell_filtering_sss.py
Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/17283/workflows/b0c301cf-3c2a-4cd7-ba52-0076c3792360/jobs/51060
Will merge once CircleCI comes back green
=> MAINT: Work around ipy dep

doc/changes/latest.inc, mne/viz/_brain/surface.py
=> [BUG][MRG] Fix surface finding for mne.viz.Brain

mne/decoding/csp.py, mne/preprocessing/ica.py, mne/time_frequency/multitaper.py, mne/time_frequency/tests/test_multitaper.py, mne/time_frequency/tfr.py, mne/viz/topomap.py, mne/viz/utils.py
expecting some failures, but fingers crossed
=> 1.4dev0 deprecations and TODOs

doc/changes/latest.inc, mne/conftest.py, mne/gui/_core.py, mne/gui/_coreg.py, mne/gui/tests/test_core.py, mne/gui/tests/test_coreg.py, mne/gui/tests/test_gui_api.py, mne/gui/tests/test_ieeg_locate.py, mne/viz/_brain/_brain.py, mne/viz/_brain/tests/test_brain.py, mne/viz/backends/_pyvista.py, mne/viz/backends/_qt.py, mne/viz/backends/_utils.py, mne/viz/backends/renderer.py, requirements.txt, tools/cirrus_dependencies.sh
Closes #11394 
Tested locally with `SUBJECTS_DIR=$PWD python -uim mne coreg`
=> BUG: Fix bug with splash screen

mne/conftest.py
Should fix a failure seen in PyVista
https://github.com/pyvista/pyvista/actions/runs/3903839795/jobs/6670305045
Closes #11415
=> MAINT: Update ignore for pyzmq

mne/io/base.py
Looks like there was a small bug in my last PR #11388 . This should hopefully fix it.
=> FIX for notch_filter with annotations

doc/changes/latest.inc, mne/gui/_ieeg_locate.py, mne/gui/tests/test_ieeg_locate.py, mne/viz/topomap.py
Fixes https://mne.discourse.group/t/unable-to-transform-montage-following-ieeg-electrode-localization-with-gui/5647/8
=> [BUG, MRG] Fix how montage is set in ieeg locate gui

mne/epochs.py, mne/evoked.py, mne/io/base.py, mne/preprocessing/ica.py, mne/preprocessing/tests/test_ica.py, mne/simulation/tests/test_raw.py, mne/time_frequency/spectrum.py
=> harmonize plot_psd() and compute_psd().plot()

mne/tests/test_annotations.py
=> [MRG] Test for notch filter when multiple segments involved

tools/azure_dependencies.sh, tools/github_actions_dependencies.sh
Let's get CIs green while we wait for NumPy/SciPy
=> MAINT: Avoid SciPy bug for now

doc/changes/latest.inc, doc/events.rst, mne/__init__.py, mne/event.py, mne/tests/test_event.py
Fixes #11429.
I've included some examples that can be used as doctests, but I'm not sure if we're doing doctests or if "proper" tests would be preferable.
=> Add count_events() function

doc/changes/latest.inc, mne/datasets/config.py, tutorials/forward/50_background_freesurfer_mne.py
Add video of inflated brain as suggested by @larsoner.
=> [ENH, MRG] Add inflated brain video to tutorial

doc/changes/latest.inc, mne/utils/config.py
This should fix the issue reported at https://mne.discourse.group/t/error-importing-mne-on-windows/6254
=> Fix configuration folder discovery on Windows

mne/preprocessing/ieeg/_projection.py, mne/viz/_brain/_brain.py
A few leftovers from https://github.com/mne-tools/mne-python/pull/11437
=> [MAINT, MRG] Follow-up efficiency improvements to inflated brain sEEG

requirements.txt, tutorials/evoked/20_visualize_evoked.py
This should fail first, then I'll fix it
=> MAINT: Fix CircleCI build

doc/changes/1.3.inc, doc/install/installers.rst
Will check links in rendered doc, merge, backport.
=> DOC: Update installer links [skip azp] [skip actions] [skip cirrus]

doc/changes/0.24.inc, ignore_words.txt, mne/decoding/tests/test_csp.py, mne/forward/forward.py, mne/utils/check.py
Fixes flake failing here: https://github.com/mne-tools/mne-python/pull/11352
=> [MAINT, MRG] Fix failing flake tests

tutorials/epochs/40_autogenerate_metadata.py
I mostly fixed some minor typos and reworded some sentences slightly.
=> Minor improvements for metadata tutorial

README.rst
Fixes #11551. I've removed all CI badges, kept Codecov, and added a badge for our Discourse forum.
=> Clean up badges

doc/changes/latest.inc, mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_maxwell.py, mne/tests/test_import_nesting.py, requirements.txt
Fixes a small bug with `compute_maxwell_basis(info, int_order=0)` and adds doc requested by @cbrnr in #11559 for test_import_nesting
=> BUG: Fix bug with compute_maxwell_basis(..., int_order=0)

mne/time_frequency/tests/test_spectrum.py, mne/viz/tests/test_topomap.py
See for example failures in #11502
=> MAINT: Fixes for matplotlib and pandas

mne/viz/evoked.py, mne/viz/topo.py
Fixes [pycodestyle error](https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes) E713:
```
test for membership should be ‘not in’
```
=> MAINT: Fix pycodestyle issue E713

.github/config.yml
Fixes #11593.
Remove garbage Unicode characters that are not displayed by my editor or browser.
=> DOC: Get rid of garbage Unicode characters

mne/utils/config.py
For https://github.com/mne-tools/mne-bids-pipeline/issues/728#issuecomment-1486723479
Not worth a changelog or test update I think (we already test somewhere that stuff added to the list shows up)
=> ENH: Add mne-bids-pipeline to mne sys_info

doc/changes/latest.inc, mne/html_templates/report/image.html.jinja
=> Display SVG figures correctly in Report

examples/preprocessing/locate_ieeg_micro.py, mne/tests/test_surface.py, requirements.txt, requirements_doc.txt, tools/azure_dependencies.sh, tools/github_actions_dependencies.sh, tutorials/clinical/10_ieeg_localize.py
https://discourse.vtk.org/t/vtk-python-wheels/11212
=> MAINT: Use VTK prerelease wheels in pre jobs

doc/install/installers.rst
Note that this is meant to go into the `maint/1.3` branch
=> Fix Linux installer command line

doc/_includes/institutional-partners.rst, doc/changes/names.inc, doc/conf.py, doc/references.bib, mne/channels/montage.py, mne/io/cnt/cnt.py
Should fix the weekend's linkcheck errors
=> MAINT: Linkcheck

examples/datasets/brainstorm_data.py, examples/preprocessing/eeg_csd.py, examples/preprocessing/find_ref_artifacts.py, examples/time_frequency/source_power_spectrum_opm.py, examples/visualization/sensor_noise_level.py, mne/report/report.py, mne/report/tests/test_report.py, tutorials/clinical/60_sleep.py, tutorials/epochs/20_visualize_epochs.py, tutorials/epochs/30_epochs_metadata.py, tutorials/intro/10_overview.py, tutorials/inverse/80_brainstorm_phantom_elekta.py, tutorials/io/60_ctf_bst_auditory.py, tutorials/preprocessing/10_preprocessing_overview.py, tutorials/preprocessing/30_filtering_resampling.py, tutorials/preprocessing/50_artifact_correction_ssp.py, tutorials/preprocessing/59_head_positions.py, tutorials/preprocessing/70_fnirs_processing.py, tutorials/raw/40_visualize_raw.py, tutorials/simulation/10_array_objs.py, tutorials/time-freq/10_spectrum_class.py, tutorials/time-freq/20_sensors_time_frequency.py
=> silence spectrum plot warning in examples/tutorials [circle full]

.circleci/config.yml, .mailmap, CITATION.cff, SECURITY.md, codemeta.json, doc/_static/versions.json, doc/changes/0.19.inc, doc/changes/0.20.inc, doc/changes/0.21.inc, doc/changes/0.22.inc, doc/changes/0.23.inc, doc/changes/0.24.inc, doc/changes/1.0.inc, doc/changes/1.1.inc, doc/changes/1.2.inc, doc/changes/1.3.inc, doc/changes/1.4.inc, doc/changes/names.inc, doc/cited.rst, doc/whats_new.rst, mne/tests/test_annotations.py, tools/generate_codemeta.py
On this step now:
https://github.com/mne-tools/mne-python/wiki/How-to-make-a-major-or-minor-release#commit-and-push
Will merge when green and tag as 1.4.0 then continue
=> MAINT: Release 1.4.0

azure-pipelines.yml, requirements.txt
Let's see if this gets things green. I'll open an issue to remind us to fix things properly at some point
=> MAINT: Avoid problematic PySide6

mne/viz/backends/_pyvista.py
Update for https://github.com/pyvista/pyvista/pull/4518
=> MAINT: Update for PyVista deprecation

mne/viz/epochs.py, mne/viz/tests/test_epochs.py, tutorials/clinical/20_seeg.py, tutorials/epochs/10_epochs_overview.py, tutorials/epochs/20_visualize_epochs.py, tutorials/epochs/30_epochs_metadata.py, tutorials/evoked/40_whitened.py, tutorials/simulation/10_array_objs.py, tutorials/simulation/80_dics.py
Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/19407/workflows/351149c0-a8b7-48e9-b87a-15e299bffbdb/jobs/55471
=> DEP: Fix post-deprecation warnings

doc/changes/latest.inc, mne/chpi.py, mne/tests/test_chpi.py
=> BUG: Fix bug with SNR calculation

doc/changes/1.1.inc, mne/utils/docs.py
Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/19439/workflows/47d02536-68a3-419f-9b4b-8eb5808776a1/jobs/55538
Will merge once CircleCI comes back happy
=> DOC: Fix docs

mne/preprocessing/eog.py, mne/preprocessing/ica.py
addresses user request in https://mne.discourse.group/t/eog-please-help-distinguish-blinks-from-saccades/7137
=> add logging message about which EOG channel used for blink detection

mne/parallel.py, mne/tests/test_parallel.py
Workaround for https://github.com/joblib/joblib/issues/1473
=> MAINT: Work around joblib bug

doc/conf.py
Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/19478/workflows/2f8acfed-f324-4002-a0be-5378452aa90d/jobs/55621
=> MAINT: Update for linkcheck [circle linkcheck]

doc/changes/latest.inc, doc/changes/names.inc
=> add missing changelog from 11773

.github/workflows/tests.yml, doc/conf.py, examples/time_frequency/time_frequency_erds.py, mne/conftest.py, mne/io/tag.py, mne/viz/tests/test_topomap.py, mne/viz/topomap.py, tools/azure_dependencies.sh, tools/github_actions_dependencies.sh, tools/github_actions_test.sh
Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/19515/workflows/883d330d-9f75-4f24-82e0-cc9a70d0c02e/jobs/55702
=> MAINT: Ignore warning in example

doc/changes/latest.inc, doc/changes/names.inc
update doc for https://github.com/mne-tools/mne-python/pull/11786
cc @Sam54000
=> udpate doc for 11786

mne/conftest.py, mne/time_frequency/tests/test_spectrum.py
=> MAINT: Better fix for deprecation

doc/install/mne_tools_suite.rst, doc/links.inc
I thought these packages deserve an entry in the list.
=> add links to MNE suite

mne/io/base.py, mne/io/brainvision/brainvision.py, mne/io/bti/bti.py, mne/io/bti/tests/test_bti.py, mne/io/ctf/ctf.py, mne/io/egi/egi.py, mne/io/egi/egimff.py, mne/io/eyelink/tests/test_eyelink.py, mne/io/fiff/raw.py, mne/io/hitachi/hitachi.py, mne/io/kit/kit.py, mne/io/nihon/nihon.py, mne/io/tests/test_raw.py
Closes #11825
No need for `latest.inc` update since this isn't user-facing (publict attributes were preserved).
@scott-huberty you can see that the `read_raw_eyelink` variant of the test is marked `xfail`. That way we can merge this when green and you can take over in a follow-up PR :)
=> MAINT: Check raw class attributes

doc/changes/latest.inc, mne/_freesurfer.py, mne/annotations.py, mne/conftest.py, mne/event.py, mne/filter.py, mne/preprocessing/ica.py, mne/rank.py, tools/github_actions_test.sh
The OpenBLAS bug has been fixed I think, so this should work.
=> MAINT: Restore pip-pre test fullness

doc/changes/latest.inc, mne/beamformer/tests/test_lcmv.py, mne/source_space.py
=> BUG: Fix bug with LCMV source space restriction

.circleci/config.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, .yamllint.yml, azure-pipelines.yml, environment.yml
Just a bunch of indentation changes to make `yamllint` happy. Will mark for squash+merge then in some follow-up PR add the resulting hash to `revs-ignore`.
=> MAINT: Fix YAML spacing

doc/conf.py, mne/conftest.py, mne/viz/_mpl_figure.py, mne/viz/topo.py, mne/viz/utils.py
=> MAINT: Work around NumPy deprecation

.mailmap, CITATION.cff, SECURITY.md, codemeta.json, doc/Makefile, doc/_static/versions.json, doc/changes/0.17.inc, doc/changes/0.8.inc, doc/changes/1.5.inc, doc/cited.rst, doc/whats_new.rst, ignore_words.txt, mne/channels/tests/test_interpolation.py, mne/label.py, mne/report/report.py, mne/transforms.py
Should be all the stuff needed to cut a GitHub release. Will mark for merge-when-green, then continue at https://github.com/mne-tools/mne-python/wiki/How-to-make-a-major-or-minor-release#make-a-release-tag
Closes #11843
=> MAINT: Release 1.5.0

doc/changes/devel.rst, mne/io/snirf/_snirf.py, mne/io/snirf/tests/test_snirf.py, mne/tests/test_bem.py, mne/time_frequency/tests/test_spectrum.py, requirements_testing_extra.txt
=> BUG: Fix bug with snirf birthday

doc/changes/devel.rst
related to issue #11767 and PR #11769
=> added documentation of changes for PR #11769

mne/filter.py, mne/io/base.py
Fixes #11688.
Updated documentation of notch_filter to reflect which methods (fir, iir, spectrum_fit) work in which situations (single or multiple stop-bands)
=> corrected documentation for notch filter function

mne/cov.py
> AttributeError: `np.complex_` was removed in the NumPy 2.0 release. Use `np.complex128` instead.
=> Replace np.complex_ with np.complex128

mne/utils/__init__.py, mne/utils/_logging.py, mne/utils/misc.py, mne/viz/_brain/_brain.py
Attempt at automatically creating weak references mentioned in https://github.com/mne-tools/mne-python/pull/11891#issuecomment-1697565405
=> MAINT: Use automatic weakref decorator

doc/changes/devel.rst, mne/preprocessing/maxfilter.py, mne/tests/test_docstring_parameters.py
=> API: Deprecate mne maxfilter

doc/conf.py, tutorials/epochs/40_autogenerate_metadata.py, tutorials/epochs/50_epochs_to_data_frame.py
Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/20434/workflows/b47e2f41-6467-45b8-b063-aeb81849d0f6/jobs/58107
=> MAINT: Fix examples for newer pandas

doc/changes/devel.rst, mne/viz/_brain/_brain.py, mne/viz/_brain/tests/test_brain.py
=> Fix bug with Brain.add_annotation when reading from file

doc/changes/v1.2.rst, doc/conf.py
Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/20452/workflows/8714338f-dd5e-4a79-9e81-e92d09df29eb/jobs/58161
=> MAINT: Work around seaborn<->pandas warning

mne/conftest.py, mne/gui/tests/test_gui_api.py, mne/viz/_brain/tests/test_notebook.py, mne/viz/backends/tests/test_abstract.py, requirements.txt
I can't remember why these tests didn't work on Windows. Let's see if they magically do. If they don't I might try debugging locally.
=> MAINT: Test notebook on Windows

.mailmap
a couple quick mailmap updates, I just happened to notice the need for them when looking at https://github.com/mne-tools/mne-python/pulse
=> mailmap updates

.github/CODEOWNERS
=> [MAINT] Add to codeowners

.github/CODEOWNERS
=> Add cbrnr to codeowners

.github/CODEOWNERS
See: https://github.com/mne-tools/mne-python/issues/11973
=> Add ADAM2392 to codeowners

mne/viz/evoked_field.py, tutorials/evoked/20_visualize_evoked.py
This should fix the doc build. It follows a similar approach as the `Brain` object, namely to expose a `.plotter` so that things like `set_3d_title` work also when passing `EvokedField` objects.
=> Add EvokedField.plotter

doc/conf.py, doc/install/contributing.rst
Toward https://github.com/mne-tools/mne-python/issues/11114, let's see if we can even get a graph to show and if it looks okay. If we can't, we should just close https://github.com/mne-tools/mne-python/issues/11114 since the feature will not be usable for us.
If it does look okay, I'll add it to the docs somewhere and we can merge.
=> ENH: Build API entry usage graphs

mne/_fiff/meas_info.py
Originally brought up in https://github.com/mne-tools/mne-python/pull/11798#discussion_r1337919770
@larsoner / @drammock  / @britta-wstnr , can you read the text I added, and let me know if it is clear/sensible to you?
=> MAINT, DOC: add eyetracking & Dipole convention for loc array to Info class API

mne/io/fiff/tests/test_raw_fiff.py
=> Fix minor typo found by codespell

examples/time_frequency/time_frequency_erds.py
A couple of trivial changes to fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/20998/workflows/3389b7ef-7967-44e4-8873-b9461c939c6b/jobs/59610. Will mark for merge-when green to keep CIs happy
=> MAINT: Fix example

doc/changes/devel.rst, mne/_fiff/meas_info.py, mne/_fiff/tests/test_meas_info.py, mne/forward/forward.py, mne/forward/tests/test_forward.py, mne/utils/docs.py
Closes #12022
Closes #12031 
No need for latest.inc update for #12031 I think because it's more or less an improvement to the error that gets raised
@mscheltienne feel free to mark for merge-when-green if you're happy. Feel free to test it with your gigantic forward solution but in principle if it fails it's some HDF5 bug.
=> ENH: Add Forward.save and hdf5 support

mne/chpi.py, mne/tests/test_chpi.py
Closes #11968
Not convinced we need a `devel.rst` for this since it's just a new warning for people
=> MAINT: Warn when fitting cHPI amplitudes on Maxwell filtered data

mne/viz/evoked_field.py, tutorials/visualization/20_ui_events.py
Only mess with the plot if not inside a Brain, including setting the interaction style.
Closes #12045
=> BUG: Fix bug with camera resetting

.github/CODEOWNERS
=> Revise cbrnr code ownership

mne/_ola.py, mne/beamformer/_lcmv.py, mne/datasets/brainstorm/bst_auditory.py, mne/datasets/brainstorm/bst_phantom_ctf.py, mne/datasets/brainstorm/bst_phantom_elekta.py, mne/datasets/brainstorm/bst_raw.py, mne/datasets/brainstorm/bst_resting.py, mne/datasets/sleep_physionet/age.py, mne/datasets/sleep_physionet/temazepam.py, mne/datasets/tests/test_datasets.py, mne/decoding/base.py, mne/decoding/csp.py, mne/decoding/transformer.py, mne/minimum_norm/resolution_matrix.py, mne/preprocessing/ecg.py, mne/time_frequency/multitaper.py, mne/viz/montage.py, pyproject.toml, setup.py, tutorials/inverse/50_beamformer_lcmv.py, tutorials/preprocessing/25_background_filtering.py, tutorials/preprocessing/45_projectors_background.py, tutorials/stats-sensor-space/20_erp_stats.py
Make better use of pyproject.toml by moving project metadata and build system settings there from setup.py. Now, basically all that setup.py does is dynamically generating package dependencies.
=> Move more metadata and build flags from setup.py to pyproject.toml

.github/CODEOWNERS
Happy sprinting over there!
Here are my edits on CODEOWNERS.
=> add details for Denis

mne/_fiff/meas_info.py, mne/_fiff/tests/test_meas_info.py
Fix bug introduced in #12039
Closes #12062
=> BUG: Fix bug with pickling MNEBadsList

mne/viz/_brain/tests/test_brain.py
Marking for merge when green to keep things green
=> MAINT: Work around PySide 6.5.3 event loop error

doc/changes/names.inc
#12066 forgot to add a `names.inc` entry
=> add Ivan to names.inc

mne/channels/channels.py, mne/channels/tests/test_channels.py, tutorials/stats-sensor-space/40_cluster_1samp_time_freq.py, tutorials/stats-sensor-space/75_cluster_ftest_spatiotemporal.py
Tiny follow-up to https://github.com/mne-tools/mne-python/pull/12066 that should take care of.https://app.circleci.com/pipelines/github/mne-tools/mne-python/21262/workflows/00a4b341-9c05-48bb-ba8f-7928ec3b7ae0/jobs/60179
=> BUG: Fix bug with ch_name resolution

examples/preprocessing/eeg_bridging.py
Fix typo newly found by codespell.
Introduced by #10571.
=> DOC: Fix typo found by codespell

mne/epochs.py, mne/io/bti/read.py, mne/io/ctf/res4.py, mne/io/edf/edf.py, mne/io/egi/egi.py, mne/io/egi/egimff.py, mne/io/nihon/nihon.py, mne/io/nsx/nsx.py, mne/preprocessing/realign.py, mne/report/tests/test_report.py, mne/surface.py, tools/azure_dependencies.sh, tools/github_actions_dependencies.sh
1. A little doc tweak to improve the example for how to get the times for `realign_raw`:
2. A `logger.info` tweak so that instead of seeing this misleading thing:
```
Cropping -27.599 s from the start of other
```
People will see:
```
Cropping 27.599 s from the start of other
```
=> DOC: Better documentation of realign_raw

doc/changes/v0.17.rst, doc/changes/v0.18.rst, doc/changes/v1.0.rst, doc/changes/v1.1.rst, doc/changes/v1.4.rst, doc/changes/v1.5.rst
Fixing minor sphinx style typos.
=> DOC: fix sphinx style typos

.pre-commit-config.yaml, doc/_includes/dig_formats.rst, doc/development/contributing.rst, doc/documentation/design_philosophy.rst, doc/documentation/index.rst, doc/install/mne_tools_suite.rst, mne/decoding/tests/test_search_light.py, pyproject.toml, tools/azure_dependencies.sh, tools/github_actions_dependencies.sh
As suggested by @mscheltienne. It did find a few legit errors (and bugs with rstcheck).
=> MAINT: Add rstcheck to CIs and pre-commit

tutorials/clinical/60_sleep.py
=> fix docstring in 60_sleep.py

pyproject.toml
I think we need this to get us closer to gold FOSS best practices
=> MAINT: Add branch coverage

README.rst
This should hopefully finally fix #11791.
=> Use gray logo (works in light and dark modes)

doc/changes/devel.rst, mne/epochs.py, mne/io/base.py, mne/preprocessing/ica.py, mne/utils/docs.py, mne/viz/_figure.py, mne/viz/epochs.py, mne/viz/ica.py, mne/viz/raw.py
Closes https://github.com/mne-tools/mne-qt-browser/issues/150
=> Add argument splash to disable splash-screen from Qt-browser

.pre-commit-config.yaml, doc/_includes/channel_interpolation.rst, doc/_includes/inverse.rst, doc/_includes/ssp.rst, doc/conf.py, doc/development/roadmap.rst, doc/links.inc, tutorials/machine-learning/50_decoding.py, tutorials/preprocessing/25_background_filtering.py
1. Update roadmap to move things around (open->in-progress->done)
2. Update to latest stats thinking and verbiage
3. Add MNE-LSL stuff
4. Fix `:label:` which is nonstandard to use `:name:` instead
=> MAINT: Update roadmap

mne/utils/docs.py
=> DOC: permutation test docstrings should link to adjacency reader

tools/circleci_dependencies.sh
=> band-aid for circleCI [skip azp][skip actions]

tools/circleci_dependencies.sh, tutorials/clinical/30_ecog.py
Once CircleCI comes back green I'll merge manually
=> MAINT: Update for mne-bids stable

pyproject.toml
=> FIX: download link in pyproject.toml

doc/changes/names.inc, doc/links.inc
should resolve problems seen here: https://app.circleci.com/pipelines/github/mne-tools/mne-python/22087/workflows/51abbb5f-3748-4a90-ad5a-758627029926/jobs/61937
=> fix broken links

mne/commands/mne_coreg.py
=> BUG: Fix passing removed params to command

doc/_static/style.css
=> fix icon link colors

doc/install/installers.rst
=> MAINT: Bump installer version

doc/changes/devel/12326.other.rst, tutorials/preprocessing/15_handling_bad_channels.py
=> Fix sphinx roles and parenthesis

mne/tests/test_epochs.py, mne/tests/test_source_estimate.py, mne/time_frequency/tests/test_tfr.py
=> MAINT: Fix for pip-pre

doc/changes/devel/12444.bugfix.rst, mne/preprocessing/artifact_detection.py
=> Fix validation of ch_tpye in annotate_muscle_zscore

mne/io/edf/edf.py
=> fix leap-year-induced test failure

doc/changes/names.inc, doc/conf.py
Fixes non-spurious errors in [linkcheck](https://app.circleci.com/pipelines/github/mne-tools/mne-python/23206/workflows/789aebf3-693d-4725-b5ea-efb1d93c40a6/jobs/64265)
=> MAINT: Fix links

tools/azure_dependencies.sh, tools/github_actions_dependencies.sh
Try to fix persistent errors in https://github.com/mne-tools/mne-python/pull/12477
=> MAINT: Fix pip-pre errors

mne/preprocessing/tests/test_lof.py
Work around https://github.com/scikit-learn/scikit-learn/issues/28625
=> MAINT: Work around sklearn bug

mne/viz/backends/_utils.py
Companion PR to https://github.com/mne-tools/mne-qt-browser/pull/236.
=> Remove bundle name hack on macOS

azure-pipelines.yml, mne/preprocessing/tests/test_lof.py, tools/azure_dependencies.sh
Just checking to see if it's still an issue
=> MAINT: Work around SciPy dev bug

azure-pipelines.yml, tools/azure_dependencies.sh, tools/github_actions_dependencies.sh
Reenable SciPy first to check to make sure scikit-learn is okay, then reenable numpy 2.0.
=> MAINT: Reenable pre scipy and numpy

mne/conftest.py, mne/utils/config.py, tools/azure_dependencies.sh, tools/github_actions_dependencies.sh
Okay in theory this should work now :crossed_fingers:
=> MAINT: Reenable NumPy 2.0

.github/workflows/tests.yml, azure-pipelines.yml, mne/export/_edf.py, mne/export/tests/test_export.py, mne/morph.py, mne/utils/dataframe.py, tools/azure_dependencies.sh, tools/github_actions_dependencies.sh, tools/install_pre_requirements.sh
In theory this should work now that https://github.com/scikit-learn/scikit-learn/pull/28692 has landed and new wheels presumably uploaded
Closes #12521
=> MAINT: Restore OMP_NUM_THREADS=2 on Windows

.circleci/config.yml, doc/changes/names.inc, doc/conf.py, doc/install/mne_tools_suite.rst
Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/23538/workflows/8001182d-a544-400f-87e3-861c4a04239d/jobs/64969/resources
=> MAINT: Bump to large resource class

doc/changes/devel/12536.bugfix.rst, mne/time_frequency/psd.py, mne/time_frequency/tests/test_psd.py, mne/time_frequency/tests/test_spectrum.py
=> align FFT windows to good data spans in psd_array_welch

doc/install/mne_tools_suite.rst
Just adding Meggie under the related software section..
Is it fine?
-- Erkka
=> Add Meggie under Related Software documentation

examples/forward/left_cerebellum_volume_source.py
Minor fix following #12544 and #12495
=> fix command in example comment

.git_archival.txt
I think this is what we should do based on https://github.com/mne-tools/mne-bids/issues/1246 and the linked issue there
=> MAINT: Remove ref-names

mne/time_frequency/spectrum.py, mne/utils/docs.py
=> add docstring note about legacy n_fft default

tools/dev/ensure_headers.py
UP028 Replace `yield` over `for` loop with `yield from`
=> STY: Apply ruff/pyupgrade rule UP028

.git-blame-ignore-revs, examples/decoding/decoding_rsa_sgskip.py, examples/decoding/decoding_xdawn_eeg.py, mne/decoding/tests/test_base.py, mne/decoding/tests/test_search_light.py, mne/stats/_adjacency.py, mne/viz/backends/_pyvista.py, tools/install_pre_requirements.sh
Should hopefully get CIs green. Will open an issue for the sklearn stuff because it's not trivial. Working on a PyVista fix but don't want to wait for them to merge it.
=> FIX: Fixes for pip-pre

examples/inverse/source_space_snr.py, mne/viz/_brain/_brain.py
=> Brain sliders hotfix

doc/changes/devel/12620.bugfix.rst, mne/decoding/tests/test_search_light.py, tools/vulture_allowlist.py
=> fix for sklearn metadata

mne/preprocessing/eyetracking/_pupillometry.py
Minor addition to the docstring for eyetracking blink interpolation.
=> DOC: blink interpolation changes annot descs

mne/io/eeglab/eeglab.py, mne/io/kit/kit.py
Small fix for #12542 (DOC, no-changelog-entry-needed)
=> Add docstring details in epoch readers

mne/beamformer/tests/test_lcmv.py, mne/stats/_adjacency.py, mne/stats/tests/test_cluster_level.py, mne/utils/check.py, tutorials/stats-sensor-space/40_cluster_1samp_time_freq.py, tutorials/stats-sensor-space/75_cluster_ftest_spatiotemporal.py
Should fix https://app.circleci.com/pipelines/github/mne-tools/mne-python/24289/workflows/ce6b2952-98af-4177-b0b0-5c594c6615fb/jobs/66569 introduced by #12646
=> FIX: Fix combine check

doc/changes/devel/12652.newfeature.rst, mne/annotations.py, mne/io/brainvision/brainvision.py, mne/io/brainvision/tests/test_brainvision.py
=> Add option to ignore BrainVision marker types

doc/changes/devel/12659.other.rst, doc/changes/names.inc, doc/install/mne_tools_suite.rst
This is a method to localize the superficial generators with their spatial extent using the Maximum Entropy on the Mean.
References : 
- **cMEM with stable clustering**. [MEG source localization of spatially extended generators of epileptic activity: comparing entropic and hierarchical bayesian approaches.](http://www.ncbi.nlm.nih.gov/pubmed/23418485) Chowdhury RA, Lina JM, Kobayashi E, Grova C. PLoS One. 2013;8(2):e55969
- **wMEM**. [Wavelet-based localization of oscillatory sources from magnetoencephalography data.](http://www.ncbi.nlm.nih.gov/pubmed/22410322) Lina J, Chowdhury R, Lemay E, Kobayashi E, Grova C. IEEE Trans Biomed Eng. 2012 Mar 6.
=> Adding MEM localization method to MNE-tools

.github/release.yaml
x-ref to: https://github.com/mne-tools/mne-python/pull/12635
=> Add release.yaml to ignore bot authors

.circleci/config.yml, .github/dependabot.yml, .github/workflows/tests.yml, environment.yml, tools/circleci_dependencies.sh, tools/github_actions_env_vars.sh, tools/install_pre_requirements.sh, tutorials/inverse/50_beamformer_lcmv.py
Should hopefully fix our doc build. Also going to check to make sure conda is working okay
=> MAINT: Fix doc build

mne/utils/docs.py
=> Correct `Epochs.apply_function` docstring

.github/PULL_REQUEST_TEMPLATE.md
In https://github.com/mne-tools/mne-qt-browser/pull/263 I noticed that a bunch of unnecessary text shows up, so in case people don't delete it on their own let's put it in a HTML comment.
=> MAINT: Update PR template

LICENSE.txt
Another year, another license update (a bit late, but better than never).
=> Update license year to 2024

mne/preprocessing/_css.py, mne/preprocessing/tests/test_css.py
Closes #12373
Turns out we do already have the flexibility / functionality needed, so this is a tiny test tweak (adding a second case) and a doc update so no changelog update needed.
=> DOC: Document CSS more completely

mne/io/snirf/_snirf.py, mne/io/snirf/tests/test_snirf.py
Fix a minor bug related to the `date` change, caught in https://github.com/mne-tools/mne-bids/pull/1278. Marking for self-merge to help get MNE-BIDS CIs green.
=> BUG: Fix bug with SNIRF date

mne/rank.py, mne/tests/test_rank.py
Closes https://github.com/mne-tools/mne-bids-pipeline/issues/972
Trivial within-release fix so I'll mark for self-merge
=> BUG: Fix bug with f-string

README.rst, doc/install/advanced.rst, doc/install/check_installation.rst, mne/preprocessing/eyetracking/_pupillometry.py
Miscellaneous easy fixes as I went through our open issues.
- fixes #12753 
- fixes #12314 
- fixes #12313
=> 3 miscellaneous documentation fixes

examples/inverse/morph_volume_stc.py, tools/circleci_dependencies.sh, tools/install_pre_requirements.sh
pymatreader has been revamped a bit (https://github.com/conda-forge/pymatreader-feedstock/pull/9), let's make sure it works.
=> MAINT: Test against pymatreader dev version

mne/datasets/config.py
Following: https://github.com/mne-tools/mne-testing-data/pull/115
=> Update hash and version of testing dataset

doc/_includes/institutional-partners.rst, doc/changes/devel/12803.bugfix.rst, doc/changes/devel/12804.bugfix.rst, doc/conf.py, mne/_freesurfer.py, mne/forward/forward.py, mne/source_space/_source_space.py, mne/utils/check.py
=> Backport #12803 and #12804

mne/io/ant/tests/test_ant.py
c.f. this comment: https://github.com/mne-tools/mne-python/pull/12811#issuecomment-2310015748
=> Add missing @testing.requires_testing_data

mne/preprocessing/hfc.py
=> Fix docstring typos

doc/changes/devel/12792.newfeature.rst, mne/datasets/config.py, mne/io/ant/ant.py, mne/io/ant/tests/test_ant.py, pyproject.toml, tools/vulture_allowlist.py, tutorials/io/20_reading_eeg_data.py
That should be the last round of tests files and tests to add for this reader.
Completes in `< 3s` locally.
=> [MRG] Add additional tests for ant reader

.github/PULL_REQUEST_TEMPLATE.md, tools/github_actions_test.sh
Poor https://github.com/mne-tools/mne-python/pull/1234 gets a lot of errant references. Let's put suggestions in comments.
Happy to modify other templates if people have seen similar problems elsewhere.
=> MAINT: Improve PR template

environment.yml
Fixes #12863 
Matches min. Python version 3.10 of `pyproject.toml`
=> [MAINT] Update minimum Python version to 3.10 in `environment.yml`

mne/decoding/tests/test_base.py, mne/preprocessing/ica.py, mne/utils/progressbar.py
=> DOC: ICA -> fix typo, add func ref, use list

pyproject.toml
Following the discussion in https://github.com/mne-tools/mne-bids/pull/1314
=> Update spacing for comments in pyproject.toml

mne/utils/docs.py
fixes https://mne.discourse.group/t/possible-bug-in-bids-split-namig/10484/5?u=sappelhoff
cc @larsoner @hoechenberger
=> doc: clarify bids split naming

mne/decoding/base.py, mne/decoding/ems.py, mne/decoding/receptive_field.py, mne/decoding/search_light.py, mne/decoding/ssd.py, mne/decoding/tests/test_base.py, mne/decoding/tests/test_receptive_field.py, mne/decoding/tests/test_search_light.py, mne/decoding/time_delaying_ridge.py, mne/fixes.py, mne/preprocessing/xdawn.py, tools/install_pre_requirements.sh
Fixes coming from discussion in https://github.com/scikit-learn/scikit-learn/issues/30237 that aren't too bad. Marking for merge-when-green. Long-term we should fix with https://github.com/mne-tools/mne-python/issues/12952.
=> MAINT: Fixes for latest sklearn

mne/utils/docs.py
See for example: https://mne.tools/stable/generated/mne.io.Raw.html#mne.io.Raw.crop
=> DOC: specify tmax_raw param may be None, and what it means

doc/changes/devel/12986.bugfix.rst, doc/changes/names.inc, mne/io/cnt/cnt.py
Hi there, this is quick PR request to fix bug when loading CNT file in issue #12982.
=> Fix: update cnt.py to check missing annotation

mne/_fiff/meas_info.py
- fixes https://github.com/mne-tools/mne-python/issues/12824
=> DOC: fix return value doc of inst.get_montage()

doc/api/preprocessing.rst, mne/channels/__init__.pyi
=> expose transform_to_head in API docs

doc/sphinxext/mne_doc_utils.py, examples/preprocessing/otp.py, mne/datasets/utils.py
Should help with https://app.circleci.com/pipelines/github/mne-tools/mne-python/25945/workflows/91d59acc-36da-4687-82d7-ce6fe29a7e5b/jobs/70061 to ensure we download early.
Running with circle full but no other CIs so will need to be manually merged instead of merge-when-green'ed.
=> MAINT: Also update fsaverage in sample

doc/sphinxext/related_software.py, tools/install_pre_requirements.sh
Trivial CI fixes for https://github.com/wmvanvliet/mne-faster/pull/9 and adding statsmodels pre back in now that they fixed their pre wheel build
=> MAINT: Use statsmodels pre and fix CircleCI

examples/preprocessing/movement_compensation.py, examples/preprocessing/otp.py, mne/preprocessing/maxwell.py, mne/preprocessing/tests/test_maxwell.py, tutorials/inverse/85_brainstorm_phantom_ctf.py
Closes #13131
No need for changelog entry because within-release bugfix of new feature
=> BUG: Fix bug with movecomp and t=0

doc/development/contributing.rst
CC @larsoner 
I have not tested after installing extensively --- but I guess this makes sense given the installation procedure? Otherwise happy to first give the environment a bit of a longer spin.
=> Fix dev installation guide

examples/io/read_impedances.py
=> DOC: fix typo in examples/io/read_impedances.py

.github/workflows/circle_artifacts.yml, .github/workflows/tests.yml
=> FIX: Bumps

tools/install_pre_requirements.sh
=> MAINT: Fix pip-pre with PyVista

examples/datasets/opm_data.py, mne/viz/_brain/_brain.py, mne/viz/_figure.py, mne/viz/tests/test_raw.py, mne/viz/tests/test_utils.py, mne/viz/utils.py
Fix for [CircleCI failure](https://app.circleci.com/pipelines/github/mne-tools/mne-python/27221/workflows/f2ea8390-7937-4927-a6f8-3d8858373891/jobs/72728) (hopefully!) just by making the figure bigger plus a workaround for https://github.com/matplotlib/matplotlib/issues/29915. No changelog entry needed I think since changing the default `axes.prop_cycle` is a very rare corner case for users.
=> BUG: Fix bug with example

mne/conftest.py, tools/install_pre_requirements.sh
PyVista updated and should now work with latest vtk dev, so let's use it
=> MAINT: Restore VTK dev

mne/filter.py, tools/install_pre_requirements.sh
Tiny fix to get CIs green [again](https://github.com/mne-tools/mne-python/actions/runs/14864876559/job/41960247144?pr=13241). Pretty trivial `np.atleast_1d` here so marking for merge-when-green.
=> MAINT: Fix bug with filter attenuation check

doc/changes/devel/13293.newfeature.rst, mne/_fiff/pick.py
=> ENH: channel_indices_by_type now has an exclude param

doc/sphinxext/mne_doc_utils.py, examples/inverse/morph_volume_stc.py, mne/utils/tests/test_config.py, tutorials/inverse/50_beamformer_lcmv.py
Closes #13297
Due to skips to save CI resources, will need to be manually merged once CircleCI comes back happy (hopefully on first commit!)
=> MAINT: Fix doc build failure due to deprecation

mne/inverse_sparse/tests/test_mxne_inverse.py
Maybe help with https://github.com/mne-tools/mne-python/actions/runs/16216726398/job/45787803068?pr=13259 ?
=> MAINT: Make MxNE test more robust

doc/index.rst
=> Capitalize Get Help

.github/CODEOWNERS
It just generates too much noise for me.
=> Remove `hoechenberger` and `cbrnr` from `CODEOWNERS`

doc/changes/dev/13393.bugfix.rst, mne/decoding/_fixes.py, mne/decoding/base.py, mne/decoding/csp.py, mne/decoding/receptive_field.py, mne/decoding/search_light.py, mne/decoding/ssd.py, mne/decoding/tests/test_ged.py, mne/decoding/tests/test_receptive_field.py, mne/decoding/tests/test_search_light.py, mne/decoding/tests/test_ssd.py, mne/decoding/tests/test_transformer.py, mne/decoding/tests/test_xdawn.py, mne/decoding/time_delaying_ridge.py, mne/decoding/transformer.py, mne/decoding/xdawn.py, tools/vulture_allowlist.py
=> BUG: Decoding compliance with sklearn

tools/install_pre_requirements.sh
According to https://github.com/apache/arrow/issues/47308 this should work again
=> MAINT: Put back pyarrow pre
